### ISSUE TITLE
[Oneplus 6] USB host is not working

### ISSUE THREAD

**Issue by axm2** [phhusson/treble_experimentations#100]
USB devices (OTG or audio devices) are not detected

**Comment by phhusson** [comment]
Works on AOSP?

**Comment by axm2** [comment]
I haven't tried on aosp yet. I'll try tonight

**Comment by axm2** [comment]
Just checked, doesn't work on AOSP either. Maybe its a hardware thing, since stock OOS has an option to temporarily turn on OTG storage

**Comment by phhusson** [comment]
Enabling vbus power supply is doing echo 1 > /sys/class/power_supply/usb/otg_switch according to
https://gitlab.com/darkobas/android_device_oneplus_oneplus6/blob/android-8.1/DeviceParts/src/org/omnirom/device/UsbOtgSwitch.java#L31

**Comment by phhusson** [comment]
Implemented in Treble Settings.
