### ISSUE TITLE
Cubot P20 MT6750T (AOSP v206) Fix video Whatsapp,Viber,Instagram.

### ISSUE THREAD

**Issue by Joker152** [phhusson/treble_experimentations#1000]
Open vendor/etc/media_codec.xml. Delete the line <Include href= " media_codecs_mediatek_video.xml " / > and reboot the device.Video shows well in Whatsapp, Viber and other apps. But the video camera does not record. Maybe this information will help you solve the problem in the following gsi.

**Comment by treble2019** [comment]
Is this the command for unlock bootloader cubot P20 - and flash rom? Thanks for your response!

```
$ fastboot devices
$ fastboot flashing unlock
press volume up to allow unlocking
$ fastboot flash system system-arm64-aonly-gapps-nosu.img
$ fastboot reboot
```
