### ISSUE TITLE
[AOSP 10.0] [Mediatek] Video in indirect rendering loops when hardware decoded

### ISSUE THREAD

**Issue by MCArTyR** [phhusson/treble_experimentations#1002]
On Android 10, video aren't rendered properly when not in direct rendering (i.e. webview), they are kinda looped for 1s

**Comment by phhusson** [comment]
Known workaround is to remove media_codecs_mediatek_video.xml line in /vendor/etc/media_codecs.xml
But still no fix found.

Possible ways to look at:
- `setprop debug.hwui.skip_empty_damage false`

**Comment by MCArTyR** [comment]
Its fix a sound?

**Comment by phhusson** [comment]
Do you see sound in the description of the bug?

**Comment by MCArTyR** [comment]
"On all tenths of gsi at me glitches with a sound"..."and sounds are reproduced incorrectly"

**Comment by phhusson** [comment]
blah you're right, usual issue of people reporting multiple issues at once... I'm removing the part about audio

**Comment by MCArTyR** [comment]
Okay, but what about sound? Me must to make other issue?

**Comment by phhusson** [comment]
yup.

**Comment by phhusson** [comment]
Ok, looks like I still don't understand where the issue actually comes from.
I thought it was indirect rendering, but "Disable HW overlay" doesn't trigger the bug in Nova Video Player.
Viewing youtube with HTML Viewer doesn'tr trigger the issue
Setting debug.hwui.skip_empty_damage doesn't fix the issue

I checked the issue isn't related to video format by viewing ./res/raw/system_nav_fully_gestural.mp4 in Nova Video Player
Settings doesn't do anything sneaky, it just uses plain old android media player.
If I switch Nova Video Player to "Android Media Player" mode, the issue doesn't appear.

**Comment by MCArTyR** [comment]
After i'm remove "media_codecs_mediatek_video.xml line in /vendor/etc/media_codecs.xml"
videos (in settings gestures) at all gone missing.

**Comment by MCArTyR** [comment]
Apparently I incorrectly removed the link, because after returning the unedited media_codecs.xml videos did not appear back.

**Comment by MCArTyR** [comment]
uh

**Comment by vague369** [comment]
I have this same problem with WhatsApp and Twitter. Doesn't seem to show up in YouTube or VLC though.

**Comment by phhusson** [comment]
Probably related issue: When enabling Night Mode, night mode is "blinking" between various levels of red.

**Comment by MCArTyR** [comment]
?

**Comment by phhusson** [comment]
Tracked in https://issuetracker.google.com/issues/148962635

**Comment by phhusson** [comment]
aosp-master doesn't have the issue
aosp-android10-gsi does have the issue.

Looking at the diff in-between, I see those commits that could be relevant:
- frameworks/native d66b6c2f0355573456be65905407da92d79205c7
- frameworks/native 968fc9aa0577dd7cd97cd3416803d2eba4ae021f & 5b47bbc7da3ee6f50e75eaf443176ff1bc4384d6

**Comment by MCArTyR** [comment]
64 / 10000
АНГЛИЙСКИЙ
Перевести вGoogleBing
Yes, the new release fixed the problem with the video. But what about the sound? #1013

**Comment by phhusson** [comment]
This isn't a forum, it is a bug tracker.

**Comment by gilless2** [comment]
the project CAOS Fixed the problem in their gsi
it worked for me anyway

**Comment by phhusson** [comment]
Yes I fixed it a month ago.
