### ISSUE TITLE
AOSP 10.0 v206-No Boot 

### ISSUE THREAD

**Issue by duypham341** [phhusson/treble_experimentations#1003]
I am using Xiaomi redmi 6a flash rom AOSP 9.0 v123, I go to TWRP recovery format factory, and flash AOSP 10.0 v206 system-quack-arm32_binder64-ab-gapps.img my phone cant boot to system. The device has android logo suspended.

**Comment by phhusson** [comment]
logcat?

**Comment by duypham341** [comment]
logcat here [https://drive.google.com/file/d/1-7jP_pTFhsXHoMSNhaO2JbQ8nHR2zBqf/view?usp=drivesdk](url)

**Comment by phhusson** [comment]
I need logcat of when the device is stuck on Android animation.
This is a log of recovery.

**Comment by duypham341** [comment]
I can flash AOSP 9.0 v123 but i dont flash file AOSP 10.0 v206 " system-quack-arm32_binder64-ab-gapps.img" on my phone.

**Comment by phhusson** [comment]
I thought you said it doesn't boot. How do you know it doesn't boot if you
can't flash it?

**Comment by duypham341** [comment]
Sorry you ,i flash successful. thanks for your support. Close post

**Comment by phhusson** [comment]
What was the issue? How did you fix it?
You need to explain so that future users with the same issue as you can
come here and see how to do it correctly.

**Comment by duypham341** [comment]
i download and install driver off Redmi 6a, unlock bootloader, flash recovery Twrp, format factory, flash bootlegged rom for Cactus, flash Gapp,flash magisk, boot to rom bootlegged, com back Twrp,format factory, flash system_arm32_binder64_ab.img , after reboot .
