### ISSUE TITLE
AOSP 10.0 v207 stuck on bootloop.huawei p 8 lite 2017

### ISSUE THREAD

**Issue by cigny61** [phhusson/treble_experimentations#1009]

**Comment by phhusson** [comment]
Did it work on v206?

**Comment by cigny61** [comment]
no. also with 26 lock on bootloop.

**Comment by phhusson** [comment]
Does one of my pie work?

**Comment by cigny61** [comment]
i use AOSP 9.0 v123.everything well

**Comment by phhusson** [comment]
I guess when you say "Stuck on bootloop" it means it remains on the "Android" boot animation
If that's the case, you have adb working at that time, so please provide `adb logcat`.

If you have magisk, please try without magisk first.

**Comment by cigny61** [comment]
when I tried to install AOSP 10.0 v207 I had no magisk.si.ero I was stuck in the startup animation "Android. now I went back to AOSP 9.0 v123. I can just try again to install AOSP 10.0 v207, and I will provide adb logcat, thanks.

**Comment by cigny61** [comment]
12-16 15:37:26.712 21164 21164 E PackageManager: Failed to create app data for com.google.android.ext.shared, but trying to recover: com.android.server.pm.Installer$InstallerException: android.os.ServiceSpecificException: Failed to prepare /data/user_de/0/com.google.android.ext.shared (code 2)
12-16 15:37:26.711   705  1412 E installd: Failed to prepare /data/user_de/0/com.google.android.ext.shared: No such file or directory
12-16 15:37:26.713   705  1412 E         : Couldn't opendir /data/user_de/0/com.google.android.ext.shared: No such file or directory
12-16 15:37:26.713   705  1412 E installd: Failed to delete /data/user_de/0/com.google.android.ext.shared: No such file or directory
12-16 15:37:26.713 21164 21164 W PackageManager: com.android.server.pm.Installer$InstallerException: android.os.ServiceSpecificException: Failed to delete /data/user_de/0/com.google.android.ext.shared (code 2)
12-16 15:37:26.713   705  1412 E cutils  : Failed to mkdir(/data/user_de/0/com.google.android.ext.shared): No such file or directory
12-16 15:37:26.713   705  1412 E installd: Failed to prepare /data/user_de/0/com.google.android.ext.shared: No such file or directory
12-16 15:37:26.714 21164 21164 D PackageManager: Recovery failed!
12-16 15:37:26.713   705  1412 E installd: Failed to prepare /data/user_de/0/com.google.android.ext.shared: No such file or directory
12-16 15:37:26.715   705  1412 E cutils  : Failed to mkdir(/data/user_de/0/com.android.mms.service): No such file or directory
12-16 15:37:26.715   705  1412 E installd: Failed to prepare /data/user_de/0/com.android.mms.service: No such file or directory
12-16 15:37:26.715 21164 21164 E PackageManager: Failed to create app data for com.android.mms.service, but trying to recover: com.android.server.pm.Installer$InstallerException: android.os.ServiceSpecificException: Failed to prepare /data/user_de/0/com.android.mms.service (code 2)
12-16 15:37:26.715   705  1412 E installd: Failed to prepare /data/user_de/0/com.android.mms.service: No such file or directory
12-16 15:37:26.716   705  1412 E         : Couldn't opendir /data/user_de/0/com.android.mms.service: No such file or directory
12-16 15:37:26.716   705  1412 E installd: Failed to delete /data/user_de/0/com.android.mms.service: No such file or directory
12-16 15:37:26.717 21164 21164 W PackageManager: com.android.server.pm.Installer$InstallerException: android.os.ServiceSpecificException: Failed to delete /data/user_de/0/com.android.mms.service (code 2)
12-16 15:37:26.717   705  1412 E cutils  : Failed to mkdir(/data/user_de/0/com.android.mms.service): No such file or directory
12-16 15:37:26.717   705  1412 E installd: Failed to prepare /data/user_de/0/com.android.mms.service: No such file or directory
12-16 15:37:26.718 21164 21164 D PackageManager: Recovery failed!
12-16 15:37:26.717   705  1412 E installd: Failed to prepare /data/user_de/0/com.android.mms.service: No such file or directory
12-16 15:37:26.719   705  1412 E cutils  : Failed to mkdir(/data/user_de/0/android): No such file or directory
12-16 15:37:26.719   705  1412 E installd: Failed to prepare /data/user_de/0/android: No such file or directory
12-16 15:37:26.719 21164 21164 E PackageManager: Failed to create app data for android, but trying to recover: com.android.server.pm.Installer$InstallerException: android.os.ServiceSpecificException: Failed to prepare /data/user_de/0/android (code 2)
12-16 15:37:26.719   705  1412 E installd: Failed to prepare /data/user_de/0/android: No such file or directory
12-16 15:37:26.720   705  1412 E         : Couldn't opendir /data/user_de/0/android: No such file or directory
12-16 15:37:26.720   705  1412 E installd: Failed to delete /data/user_de/0/android: No such file or directory
12-16 15:37:26.721 21164 21164 W PackageManager: com.android.server.pm.Installer$InstallerException: android.os.ServiceSpecificException: Failed to delete /data/user_de/0/android

**Comment by cigny61** [comment]
<pre>2-16 15:37:38.643 21618 21640 E libprocessgroup: CgroupMap::FindController called for [21618] failed, RC file was not initialized properly
12-16 15:37:38.643 21618 21640 W libprocessgroup: JoinCgroup: controller cpuset is not found
12-16 15:37:38.643 21618 21640 E libprocessgroup: CgroupMap::FindController called for [21618] failed, RC file was not initialized properly
12-16 15:37:38.643 21618 21640 W libprocessgroup: JoinCgroup: controller cpuset is not found
12-16 15:37:38.643 21618 21640 E libprocessgroup: CgroupMap::FindController called for [21618] failed, RC file was not initialized properly
12-16 15:37:38.643 21618 21640 W libprocessgroup: JoinCgroup: controller cpuset is not found
12-16 15:37:38.643 21618 21640 E libprocessgroup: CgroupMap::FindController called for [21618] failed, RC file was not initialized properly
12-16 15:37:38.643 21618 21640 W libprocessgroup: JoinCgroup: controller cpuset is not found
12-16 15:37:38.643 21618 21640 E libprocessgroup: CgroupMap::FindController called for [21618] failed, RC file was not initialized properly
12-16 15:37:38.643 21618 21640 W libprocessgroup: JoinCgroup: controller cpuset is not found
12-16 15:37:38.643 21618 21640 E libprocessgroup: CgroupMap::FindController called for [21618] failed, RC file was not initialized properly
12-16 15:37:38.643 21618 21640 W libprocessgroup: JoinCgroup: controller cpuset is not found
12-16 15:37:38.643 21618 21640 E libprocessgroup: CgroupMap::FindController called for [21618] failed, RC file was not initialized properly
12-16 15:37:38.643 21618 21640 W libprocessgroup: JoinCgroup: controller cpuset is not found
12-16 15:37:38.643 21618 21640 E libprocessgroup: CgroupMap::FindController called for [21618] failed, RC file was not initialized properly
12-16 15:37:38.643 21618 21640 W libprocessgroup: JoinCgroup: controller cpuset is not found
12-16 15:37:38.643 21618 21640 E libprocessgroup: CgroupMap::FindController called for [21618] failed, RC file was not initialized properly
12-16 15:37:38.643 21618 21640 W libprocessgroup: JoinCgroup: controller cpuset is not found
12-16 15:37:38.643 21618 21640 E libprocessgroup: CgroupMap::FindController called for [21618] failed, RC file was not initialized properly
12-16 15:37:38.643 21618 21640 W libprocessgroup: JoinCgroup: controller blkio is not found
12-16 15:37:38.643 21618 21640 E libprocessgroup: CgroupMap::FindController called for [21618] failed, RC file was not initialized properly
12-16 15:37:38.643 21618 21640 W libprocessgroup: JoinCgroup: controller blkio is not found
12-16 15:37:38.643 21618 21640 E libprocessgroup: CgroupMap::FindController called for [21618] failed, RC file was not initialized properly
12-16 15:37:38.643 21618 21640 W libprocessgroup: JoinCgroup: controller blkio is not found
12-16 15:37:38.643 21618 21640 E libprocessgroup: CgroupMap::FindController called for [21618] failed, RC file was not initialized properly
12-16 15:37:38.643 21618 21640 W libprocessgroup: JoinCgroup: controller blkio is not found
12-16 15:37:38.643 21618 21640 W libprocessgroup: SetAttribute: unknown attribute: MemSoftLimit
12-16 15:37:38.643 21618 21640 W libprocessgroup: SetAttribute: unknown attribute: MemSwappiness
12-16 15:37:38.643 21618 21640 W libprocessgroup: SetAttribute: unknown attribute: MemSoftLimit
12-16 15:37:38.643 21618 21640 W libprocessgroup: SetAttribute: unknown attribute: MemSwappiness
12-16 15:37:38.643 21618 21640 E libprocessgroup: CgroupMap::FindController called for [21618] failed, RC file was not initialized properly
12-16 15:37:38.643 21618 21640 W libprocessgroup: JoinCgroup: controller memory is not found
12-16 15:37:38.649 21618 21618 I netd    : Registering NetdNativeService: 8.1ms
12-16 15:37:38.653 21618 21618 I ServiceManagement: Registered android.system.net.netd@1.1::INetd/default (start delay of 176ms)
12-16 15:37:38.654 21618 21618 I netd    : Registering NetdHwService: 4.7ms
12-16 15:37:38.654 21618 21618 I netd    : Netd started in 108ms
<font color="#4E9A06"><b>io@linux</b></font>:<font color="#3465A4"><b>~</b></font>$ 

</pre>
