### ISSUE TITLE
[Help Post][IMEI null] All the gsi Rom

### ISSUE THREAD

**Issue by eg-abdurrahman** [phhusson/treble_experimentations#1012]
I got a problem.
There is no IMEI in my device.
Even I flash my stock firmware and it's also IMEI missing.
Please Help

**Comment by cernodile** [comment]
Since it doesn't appear on your stock firmware - this isn't a GSI specific issue you're facing, but rather you wiping your NVRAM/NVDATA. What device and chipset?

**Comment by eg-abdurrahman** [comment]
Its Walton Primo R5 ,
mt6739 chipset

**Comment by cernodile** [comment]
What did you do to cause this error? Did you use SP Flash Tool with Format All? If so - then your IMEI is permanently wiped unless it's serviced. You can assign temporary IMEI that persist until factory reset by sending AT commands over terminal as root or use the "MAUI META" tool. Alternatively, if you have made a full device backup (including nvram/nvdata), you can reflash the partition.

Example of the AT command on my old MT6753 phone
`echo 'AT+EGMR=1,7,"IMEI"'>/dev/pts/16`

**Comment by eg-abdurrahman** [comment]
yes..i used to use sp flash tool and i did format all .
but i have the fully flash file... including nvram/nvdata everything even
its showing IMEI null.

**Comment by cernodile** [comment]
If its a nvdata/nvram file provided by your OEM's firmware files - then those are usually blanked out files. If you don't happen to have a backup of your own then you're stuck with the temporary solutions brought up above. There is no permanent fix as far as I am aware. A word of advice for your next device is to avoid "Format All" at all costs, it can render your device useless second-hand if you have to manually "hack in" the IMEI each reset. I am sorry for your loss.

**Comment by eg-abdurrahman** [comment]
all was my fault..
i  make my phone like a garbage ,,,
thanks for your kind information.
