### ISSUE TITLE
ELEPHONE Solider boot animation AOSP 208

### ISSUE THREAD

**Issue by yura73** [phhusson/treble_experimentations#1017]
boot animation AOSP 208
[logcat boot.txt](https://github.com/phhusson/treble_experimentations/files/3974379/logcat.boot.txt)

**Comment by phhusson** [comment]
did it boot properly before?

**Comment by yura73** [comment]
not at all aosp equally boot animation.

**Comment by phhusson** [comment]
ok, some people managed to boot it just fine, you're doing something wrong.
Which variant did you flash and why?
Did you flash vbmeta?

**Comment by yura73** [comment]
AOSP firmware 200-208 at all only bootanimation without magisk phh. and with magisk phh.

**Comment by phhusson** [comment]
Which variant? Arm64? A/B?
And why did you chose this one?

The only trustworthy app for that is Treble Info

**Comment by yura73** [comment]
![Screenshot_20191217-193631](https://user-images.githubusercontent.com/55551619/71020289-b2b4ca80-2104-11ea-9247-9e742a3f1682.png)

**Comment by phhusson** [comment]
ok.
Since you have Android boot animation, that means adb work.
So please get `adb logcat`

**Comment by yura73** [comment]
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/3974649/logcat.txt)
AOSP 10.0 v208 magisk phh.

**Comment by yura73** [comment]
[logcat -v.txt](https://github.com/phhusson/treble_experimentations/files/3974707/logcat.-v.txt)

**Comment by yura73** [comment]
Did I give the correct logcat?

**Comment by phhusson** [comment]
Yup logcat is good
Issue is

12-17 17:48:37.934  3965  3965 E vndksupport: Could not load
/vendor/lib/egl/libGLES_mali.so from sphal namespace: dlopen failed:
library "libstdc++.so" not found.

**Comment by yura73** [comment]
What should i do?

**Comment by yura73** [comment]
I copied libstdc++.so  from the stock firmware to vendor .  firmware started !!!!!!!
thank you very much !!!!

**Comment by rashydos** [comment]
Hi @yura73 

how did you copied this lib to vendor? it gives me read-only even if I mount /vendor as RW. after coping that failed, it change to RO automatically !!

also I have add the lib to vendor.img but after flash I didn't found it !
Thanks

**Comment by yura73** [comment]
put to stock firmware
1)TWRP
USE THIS DECODING ARCHIVE
[decrypt_soldier.zip](https://github.com/phhusson/treble_experimentations/files/4374523/decrypt_soldier.zip)
2)Magisk
Then with the help of any file manager with root rights. I use total commander

**Comment by rashydos** [comment]
Thanks @yura73 and @phhusson 

I finally success to boot android 10

adb root
adb remount
adb shell cp /system/lib/vndk-26/libstdc++.so /system/lib/vndk-sp-26/libstdc++.so

also, I have updated the file /system/etc/ld.config.26.txt by adding libstdc++.so and /system/${LIB}/vndk-sp-26 at many placed (not only namespace.vndk.link.default.shared_libs didn' work for me)

as attachement my file that work

[ld.config.26.txt](https://github.com/phhusson/treble_experimentations/files/4376246/ld.config.26.txt)
