### ISSUE TITLE
[AOSP 10] Magisk manager does not issue root.

### ISSUE THREAD

**Issue by Adm0** [phhusson/treble_experimentations#1029]
Leagoo T8s (mt6750T) , vendor 8.1.
Installed:
GSI - AOSP v10 v208 (system-quack-arm64-aonly-gapps).
Magisk-phh - 20.1 (20100).
Magisk manager - 7.4.0 (253).

Logcat
`12-23 00:16:25.701 13256 13256 F linker  : CANNOT LINK EXECUTABLE "/system/bin/app_process": "/apex/com.android.runtime/lib/libc++.so" is 32-bit instead of 64-bit`

```
file -L /system/bin/app_process                                  
/system/bin/app_process: ELF shared object, 64-bit LSB arm64, dynamic (/system/bin/linker64)
file /apex/com.android.runtime/lib/libc++.so
/apex/com.android.runtime/lib/libc++.so: ELF shared object, 32-bit LSB arm
```

**Comment by phhusson** [comment]
Let's centralize all the issues related to magisk to #1008
