### ISSUE TITLE
[Nokia 3.1 Plus] [V123] Flashing magisk breaks wifi.

### ISSUE THREAD

**Issue by zapacitu18** [phhusson/treble_experimentations#1031]
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/3996156/logcat.txt)

**Comment by phhusson** [comment]
https://github.com/topjohnwu/Magisk/issues/552

**Comment by zapacitu18** [comment]
Thanks, fixed by insmod wmt_drv.ko.
