### ISSUE TITLE
[Galaxy J6] Stuck in boot logo !

### ISSUE THREAD

**Issue by ChemsoDev** [phhusson/treble_experimentations#1034]
Galaxy j6
sm-j600f
android9
Launched with android 8
Bootloader v5 I think it's still android 8 bl
arm32binder64
I have also an unofficial arm64 vendor image works fine for me 

@NotTYX 
@phhusson 
I flashed the aosp 10 v208
My phone stuck in the boot logo
I tried to edit the rw-system.sh (removed some lines u know samsung power hal)
I tried also to delete it completely
Fixed the context in twrp

I tried both arm32binder64 with original vendor and boot
And arm64 with modified 64bit vendor for my phone
Note: I was running aosp9 havocos2.9 aex9
In both arm32binder64 and arm64 without problems
So... what's new in aosp 10 that prevent the device from booting up?
And thanks for the hard work @phhusson !

**Comment by phhusson** [comment]
What do you mean "stuck in the boot logo"? Which one? If it's Android boot
logo, then ADB is working and you can retrieve logs using adb logcat.

Le mer. 25 déc. 2019 à 16:02, Chemso Dev <notifications@github.com> a
écrit :

**Comment by ChemsoDev** [comment]
Android boot logo
U mean if it's the bootloader or the android logo right?

**Comment by ChemsoDev** [comment]
@phhusson I can't access my PC right now
How can I retrieve logs

**Comment by NotTYX** [comment]
Had to literally mention me? I have no idea if there is a way for a64 to work. Are you in the J6 Development group on telegram? If yes, tell me your username. Maybe i can try help. But i think you have to reflash the a64 vendor.

**Comment by ChemsoDev** [comment]
I mention u cz u have a j6 and u said that u have a working android 10 on it... Kinda!
I'm not in the group send me the link that will be appreciated!

**Comment by NotTYX** [comment]
Join here. I will pm you.
https://t.me/j6offlinecharging

**Comment by ChemsoDev** [comment]
@phhusson any help over here

**Comment by ChemsoDev** [comment]
Yo its working!
Got it to work thanks to some famous xda members for their hard work.
To install any android Q gsi on any galaxy j6
J6_Universal_ARM64_GSI_Patch(modified 64 bit vendor):
https://drive.google.com/file/d/1-fyZ_D73-SyOqBtqacI_uiqREcvBDq2O/view
System.img: any phh based gsi
For updates or maybe android 11 128bit vendor ;) join that telegram group
Join «J6 Development» on Telegram: https://t.me/galaxyJ600X


@phhusson thanks for ur hard work u r the head of the gsi community so don't give up and keep up homie 
Don't forget to add that vendor and telegram group to the J6 page
