### ISSUE TITLE
[Huawei MediaPad M5 lite] Fingerprint enrolment not working

### ISSUE THREAD

**Issue by tinloaf** [phhusson/treble_experimentations#1036]
I'm running your AOSP 10.0 v208 (AOSP 9.0 does not boot) on a Huawei MediaPad M5 lite (Model Number "BAH2-W19 8.0.0.230(C431)"). Most things work fine.

After the first boot, the fingerprint sensor worked as expected. However, after a reboot, all my fingerprints are gone and I cannot enroll new fingerprints. I can get to the wizard that allows me to add a fingerprint, and I can get to the "Lift, then touch again" screen, where a circle fills a little bit every time you put your finger on the sensor. However, shortly before it completes I get the error message "Enrolment was not completed. Fingerprint enrolment didn't work. Try again or use a different finger." This always happens at the very end, i.e., I suspect when my finger was sufficiently scanned and the fingerprint should be added to the system.

You can find a `logcat` output, starting when I open the fingerprint dialogue and ending after the error, here: https://cloud.tinloaf.de/s/YRobzF7EikRb5tk 

Please let me know if there is anything else I can do to help debugging this!

**Comment by agentum1** [comment]
+1 on BAH2-L09.
Pls heeelp)

**Comment by tinloaf** [comment]
@phhusson and me actually debugged this the other night. I had a working solution which I tried to put into a PR [here](https://github.com/tinloaf/device_phh_treble/commit/51be51649bee7e840e0aca48ece132ebfb1ab3e1), but somehow that solution is not working for me anymore. Maybe the `chcon` I removed was necessary after all? I hope to have a working solution (again) within a couple of days.

**Comment by tinloaf** [comment]
@agentum1 If you feel comfortable with `adb`, you might want to check out https://github.com/phhusson/device_phh_treble/pull/160 .

Basic instructions:
* Get the modified `rw-system.sh` from that PR.
* Run `adb root ; adb remount ; adb push rw-system.sh /system/bin/rw-system.sh` to upload the modified file to your tablet.
* Reboot your tablet

If you saw the same problem as me, that should fix it. However: No guarantees whatsoever. ;-)

**Comment by agentum1** [comment]
> 
> 
> @agentum1 If you feel comfortable with `adb`, you might want to check out [phhusson/device_phh_treble#160](https://github.com/phhusson/device_phh_treble/pull/160) .
> 
> Basic instructions:
> 
>     * Get the modified `rw-system.sh` from that PR.
> 
>     * Run `adb root ; adb remount ; adb push rw-system.sh /system/bin/rw-system.sh` to upload the modified file to your tablet.
> 
>     * Reboot your tablet
> 
> 
> If you saw the same problem as me, that should fix it. However: No guarantees whatsoever. ;-)

It works! Great job! TY!

**Comment by tinloaf** [comment]
The PR has made it into the latest release, therefore this should be fixed. :)

**Comment by fourofspades** [comment]
Fingerprint enrollment regression in 214.  Clean flash of 213 works, clean flash of 214 fails.

Mediapad MT 8.4 (hi3660)

**Comment by fourofspades** [comment]
Also an observation, gestures on the fingerprint sensor should be disabled during enrollment.

**Comment by tinloaf** [comment]
@fourofspades This is the `rw-system.sh` before my patch: https://github.com/tinloaf/device_phh_treble/raw/04583fa95a6c58d25dda7644002f9da05eee3ab2/rw-system.sh

Can you verify that your fingerprint reader works with it? if so, could you provide us with the output of 

`ls -lRZ /data/sec_storage_data`

and 

`ls -lRZ /sec_storage`? Thanks!

**Comment by fourofspades** [comment]
`Chicago:/ # ls -lRZ /data/sec_storage_data
/data/sec_storage_data:
total 3
drwx------ 4 system system u:object_r:teecd_data_file:s0 3488 2020-03-28 08:59 fp

/data/sec_storage_data/fp:
total 6
drwx------ 4 system system u:object_r:teecd_data_file:s0 3488 2020-03-28 08:59 data
drwx------ 3 system system u:object_r:teecd_data_file:s0 3488 2020-03-28 08:55 sec_storage_data

/data/sec_storage_data/fp/data:
total 6
drwx------ 2 system system u:object_r:teecd_data_file:s0 3488 2020-03-28 08:59 fpc
drwx------ 3 system system u:object_r:teecd_data_file:s0 3488 2020-03-28 08:59 system

/data/sec_storage_data/fp/data/fpc:
total 6
-rw------- 1 system system u:object_r:teecd_data_file:s0 3264 2020-03-28 09:04 139D7EDCB41CFCECE8EE442E6DCF75EEA29C592C01522A3EC19BEB4A9DF0FA0D
-rw------- 1 system system u:object_r:teecd_data_file:s0 3264 2020-03-28 09:04 139D7EDCB41CFCECE8EE442E6DCF75EEA29C592C01522A3EC19BEB4A9DF0FA0D.bk

/data/sec_storage_data/fp/data/system:
total 3
drwx------ 3 system system u:object_r:teecd_data_file:s0 3488 2020-03-28 08:59 users

/data/sec_storage_data/fp/data/system/users:
total 3
drwx------ 3 system system u:object_r:teecd_data_file:s0 3488 2020-03-28 08:59 0

/data/sec_storage_data/fp/data/system/users/0:
total 3
drwx------ 2 system system u:object_r:teecd_data_file:s0 3488 2020-03-28 08:59 fpdata

/data/sec_storage_data/fp/data/system/users/0/fpdata:
total 246
-rw------- 1 system system u:object_r:teecd_data_file:s0  3264 2020-03-28 09:04 4A94E62AA1CDC7EE246D74BD3F0088F920C659DB1E93B16896256D2120B07C9A
-rw------- 1 system system u:object_r:teecd_data_file:s0  3264 2020-03-28 09:04 4A94E62AA1CDC7EE246D74BD3F0088F920C659DB1E93B16896256D2120B07C9A.bk
-rw------- 1 system system u:object_r:teecd_data_file:s0 58560 2020-03-28 09:04 7ADBBE8542544D808DDCB783CEC041FF0A13EF46DC1D517F11D3A526641ADD38
-rw------- 1 system system u:object_r:teecd_data_file:s0 58560 2020-03-28 09:04 7ADBBE8542544D808DDCB783CEC041FF0A13EF46DC1D517F11D3A526641ADD38.bk
-rw------- 1 system system u:object_r:teecd_data_file:s0 58560 2020-03-28 08:59 AD5CAD5179D6148AF66E5DA9D9C23188E4381A969A54BB94A851CB1905ED9AF0
-rw------- 1 system system u:object_r:teecd_data_file:s0 58560 2020-03-28 08:59 AD5CAD5179D6148AF66E5DA9D9C23188E4381A969A54BB94A851CB1905ED9AF0.bk

/data/sec_storage_data/fp/sec_storage_data:
total 3
drwx------ 3 system system u:object_r:teecd_data_file:s0 3488 2020-03-28 08:55 fp

/data/sec_storage_data/fp/sec_storage_data/fp:
total 3
drwx------ 2 system system u:object_r:teecd_data_file:s0 3488 2020-03-28 08:55 calibration

/data/sec_storage_data/fp/sec_storage_data/fp/calibration:
total 168
-rw------- 1 system system u:object_r:teecd_data_file:s0 83136 2020-03-28 09:00 027950D22134500CCDDAA82244FC6FBD231DCE75D8128330D63996211C051AFD
-rw------- 1 system system u:object_r:teecd_data_file:s0 83136 2020-03-28 09:00 027950D22134500CCDDAA82244FC6FBD231DCE75D8128330D63996211C051AFD.bk
Chicago:/ # ls -lRZ /sec_storage
/sec_storage:
total 3
drwx------ 4 system system u:object_r:teecd_data_file:s0 3488 2020-03-28 08:59 fp

/sec_storage/fp:
total 6
drwx------ 4 system system u:object_r:teecd_data_file:s0 3488 2020-03-28 08:59 data
drwx------ 3 system system u:object_r:teecd_data_file:s0 3488 2020-03-28 08:55 sec_storage_data

/sec_storage/fp/data:
total 6
drwx------ 2 system system u:object_r:teecd_data_file:s0 3488 2020-03-28 08:59 fpc
drwx------ 3 system system u:object_r:teecd_data_file:s0 3488 2020-03-28 08:59 system

/sec_storage/fp/data/fpc:
total 6
-rw------- 1 system system u:object_r:teecd_data_file:s0 3264 2020-03-28 09:04 139D7EDCB41CFCECE8EE442E6DCF75EEA29C592C01522A3EC19BEB4A9DF0FA0D
-rw------- 1 system system u:object_r:teecd_data_file:s0 3264 2020-03-28 09:04 139D7EDCB41CFCECE8EE442E6DCF75EEA29C592C01522A3EC19BEB4A9DF0FA0D.bk

/sec_storage/fp/data/system:
total 3
drwx------ 3 system system u:object_r:teecd_data_file:s0 3488 2020-03-28 08:59 users

/sec_storage/fp/data/system/users:
total 3
drwx------ 3 system system u:object_r:teecd_data_file:s0 3488 2020-03-28 08:59 0

/sec_storage/fp/data/system/users/0:
total 3
drwx------ 2 system system u:object_r:teecd_data_file:s0 3488 2020-03-28 08:59 fpdata

/sec_storage/fp/data/system/users/0/fpdata:
total 246
-rw------- 1 system system u:object_r:teecd_data_file:s0  3264 2020-03-28 09:04 4A94E62AA1CDC7EE246D74BD3F0088F920C659DB1E93B16896256D2120B07C9A
-rw------- 1 system system u:object_r:teecd_data_file:s0  3264 2020-03-28 09:04 4A94E62AA1CDC7EE246D74BD3F0088F920C659DB1E93B16896256D2120B07C9A.bk
-rw------- 1 system system u:object_r:teecd_data_file:s0 58560 2020-03-28 09:04 7ADBBE8542544D808DDCB783CEC041FF0A13EF46DC1D517F11D3A526641ADD38
-rw------- 1 system system u:object_r:teecd_data_file:s0 58560 2020-03-28 09:04 7ADBBE8542544D808DDCB783CEC041FF0A13EF46DC1D517F11D3A526641ADD38.bk
-rw------- 1 system system u:object_r:teecd_data_file:s0 58560 2020-03-28 08:59 AD5CAD5179D6148AF66E5DA9D9C23188E4381A969A54BB94A851CB1905ED9AF0
-rw------- 1 system system u:object_r:teecd_data_file:s0 58560 2020-03-28 08:59 AD5CAD5179D6148AF66E5DA9D9C23188E4381A969A54BB94A851CB1905ED9AF0.bk

/sec_storage/fp/sec_storage_data:
total 3
drwx------ 3 system system u:object_r:teecd_data_file:s0 3488 2020-03-28 08:55 fp

/sec_storage/fp/sec_storage_data/fp:
total 3
drwx------ 2 system system u:object_r:teecd_data_file:s0 3488 2020-03-28 08:55 calibration

/sec_storage/fp/sec_storage_data/fp/calibration:
total 168
-rw------- 1 system system u:object_r:teecd_data_file:s0 83136 2020-03-28 09:00 027950D22134500CCDDAA82244FC6FBD231DCE75D8128330D63996211C051AFD
-rw------- 1 system system u:object_r:teecd_data_file:s0 83136 2020-03-28 09:00 027950D22134500CCDDAA82244FC6FBD231DCE75D8128330D63996211C051AFD.bk`

**Comment by fourofspades** [comment]
Apologies, the regression came betweeen 212 and 213 (the image downloads have the same name, and I got a bit mixed up).   A clean flash of 212, fingerprints enroll, anything later (213, 214) all fail.

The requested commands when run with 212:

Chicago:/ # ls -lRZ /data/sec_storage_data
/data/sec_storage_data:
total 3
drwx------ 4 system system u:object_r:teecd_data_file_system:s0 3488 2020-03-28 12:52 fp

/data/sec_storage_data/fp:
total 6
drwx------ 4 system system u:object_r:teecd_data_file_system:s0 3488 2020-03-28 12:52 data
drwx------ 3 system system u:object_r:teecd_data_file_system:s0 3488 2020-03-28 12:48 sec_storage_data

/data/sec_storage_data/fp/data:
total 6
drwx------ 2 system system u:object_r:teecd_data_file_system:s0 3488 2020-03-28 12:52 fpc
drwx------ 3 system system u:object_r:teecd_data_file_system:s0 3488 2020-03-28 12:52 system

/data/sec_storage_data/fp/data/fpc:
total 6
-rw------- 1 system system u:object_r:teecd_data_file_system:s0 3264 2020-03-28 12:54 139D7EDCB41CFCECE8EE442E6DCF75EEA29C592C01522A3EC19BEB4A9DF0FA0D
-rw------- 1 system system u:object_r:teecd_data_file_system:s0 3264 2020-03-28 12:54 139D7EDCB41CFCECE8EE442E6DCF75EEA29C592C01522A3EC19BEB4A9DF0FA0D.bk

/data/sec_storage_data/fp/data/system:
total 3
drwx------ 3 system system u:object_r:teecd_data_file_system:s0 3488 2020-03-28 12:52 users

/data/sec_storage_data/fp/data/system/users:
total 3
drwx------ 3 system system u:object_r:teecd_data_file_system:s0 3488 2020-03-28 12:52 0

/data/sec_storage_data/fp/data/system/users/0:
total 3
drwx------ 2 system system u:object_r:teecd_data_file_system:s0 3488 2020-03-28 12:52 fpdata

/data/sec_storage_data/fp/data/system/users/0/fpdata:
total 246
-rw------- 1 system system u:object_r:teecd_data_file_system:s0  3264 2020-03-28 12:54 4A94E62AA1CDC7EE246D74BD3F0088F920C659DB1E93B16896256D2120B07C9A
-rw------- 1 system system u:object_r:teecd_data_file_system:s0  3264 2020-03-28 12:54 4A94E62AA1CDC7EE246D74BD3F0088F920C659DB1E93B16896256D2120B07C9A.bk
-rw------- 1 system system u:object_r:teecd_data_file_system:s0 55488 2020-03-28 12:52 9EE8F7A486AC0C1900EF4ED1EFD3FD45AD06AF50A624643C59515BACA7545B1E
-rw------- 1 system system u:object_r:teecd_data_file_system:s0 55488 2020-03-28 12:52 9EE8F7A486AC0C1900EF4ED1EFD3FD45AD06AF50A624643C59515BACA7545B1E.bk
-rw------- 1 system system u:object_r:teecd_data_file_system:s0 64704 2020-03-28 12:54 E1B77D2BD61F414443498103C10E2FF012CA495BCCAF2172DC34185B1BC71303
-rw------- 1 system system u:object_r:teecd_data_file_system:s0 64704 2020-03-28 12:54 E1B77D2BD61F414443498103C10E2FF012CA495BCCAF2172DC34185B1BC71303.bk

/data/sec_storage_data/fp/sec_storage_data:
total 3
drwx------ 3 system system u:object_r:teecd_data_file_system:s0 3488 2020-03-28 12:48 fp

/data/sec_storage_data/fp/sec_storage_data/fp:
total 3
drwx------ 2 system system u:object_r:teecd_data_file_system:s0 3488 2020-03-28 12:48 calibration

/data/sec_storage_data/fp/sec_storage_data/fp/calibration:
total 168
-rw------- 1 system system u:object_r:teecd_data_file_system:s0 83136 2020-03-28 12:52 027950D22134500CCDDAA82244FC6FBD231DCE75D8128330D63996211C051AFD
-rw------- 1 system system u:object_r:teecd_data_file_system:s0 83136 2020-03-28 12:52 027950D22134500CCDDAA82244FC6FBD231DCE75D8128330D63996211C051AFD.bk
Chicago:/ # ls -lRZ /sec_storage
/sec_storage:
total 3
drwx------ 4 system system u:object_r:teecd_data_file_system:s0 3488 2020-03-28 12:52 fp

/sec_storage/fp:
total 6
drwx------ 4 system system u:object_r:teecd_data_file_system:s0 3488 2020-03-28 12:52 data
drwx------ 3 system system u:object_r:teecd_data_file_system:s0 3488 2020-03-28 12:48 sec_storage_data

/sec_storage/fp/data:
total 6
drwx------ 2 system system u:object_r:teecd_data_file_system:s0 3488 2020-03-28 12:52 fpc
drwx------ 3 system system u:object_r:teecd_data_file_system:s0 3488 2020-03-28 12:52 system

/sec_storage/fp/data/fpc:
total 6
-rw------- 1 system system u:object_r:teecd_data_file_system:s0 3264 2020-03-28 12:54 139D7EDCB41CFCECE8EE442E6DCF75EEA29C592C01522A3EC19BEB4A9DF0FA0D
-rw------- 1 system system u:object_r:teecd_data_file_system:s0 3264 2020-03-28 12:54 139D7EDCB41CFCECE8EE442E6DCF75EEA29C592C01522A3EC19BEB4A9DF0FA0D.bk

/sec_storage/fp/data/system:
total 3
drwx------ 3 system system u:object_r:teecd_data_file_system:s0 3488 2020-03-28 12:52 users

/sec_storage/fp/data/system/users:
total 3
drwx------ 3 system system u:object_r:teecd_data_file_system:s0 3488 2020-03-28 12:52 0

/sec_storage/fp/data/system/users/0:
total 3
drwx------ 2 system system u:object_r:teecd_data_file_system:s0 3488 2020-03-28 12:52 fpdata

/sec_storage/fp/data/system/users/0/fpdata:
total 246
-rw------- 1 system system u:object_r:teecd_data_file_system:s0  3264 2020-03-28 12:54 4A94E62AA1CDC7EE246D74BD3F0088F920C659DB1E93B16896256D2120B07C9A
-rw------- 1 system system u:object_r:teecd_data_file_system:s0  3264 2020-03-28 12:54 4A94E62AA1CDC7EE246D74BD3F0088F920C659DB1E93B16896256D2120B07C9A.bk
-rw------- 1 system system u:object_r:teecd_data_file_system:s0 55488 2020-03-28 12:52 9EE8F7A486AC0C1900EF4ED1EFD3FD45AD06AF50A624643C59515BACA7545B1E
-rw------- 1 system system u:object_r:teecd_data_file_system:s0 55488 2020-03-28 12:52 9EE8F7A486AC0C1900EF4ED1EFD3FD45AD06AF50A624643C59515BACA7545B1E.bk
-rw------- 1 system system u:object_r:teecd_data_file_system:s0 64704 2020-03-28 12:54 E1B77D2BD61F414443498103C10E2FF012CA495BCCAF2172DC34185B1BC71303
-rw------- 1 system system u:object_r:teecd_data_file_system:s0 64704 2020-03-28 12:54 E1B77D2BD61F414443498103C10E2FF012CA495BCCAF2172DC34185B1BC71303.bk

/sec_storage/fp/sec_storage_data:
total 3
drwx------ 3 system system u:object_r:teecd_data_file_system:s0 3488 2020-03-28 12:48 fp

/sec_storage/fp/sec_storage_data/fp:
total 3
drwx------ 2 system system u:object_r:teecd_data_file_system:s0 3488 2020-03-28 12:48 calibration

/sec_storage/fp/sec_storage_data/fp/calibration:
total 168
-rw------- 1 system system u:object_r:teecd_data_file_system:s0 83136 2020-03-28 12:52 027950D22134500CCDDAA82244FC6FBD231DCE75D8128330D63996211C051AFD
-rw------- 1 system system u:object_r:teecd_data_file_system:s0 83136 2020-03-28 12:52 027950D22134500CCDDAA82244FC6FBD231DCE75D8128330D63996211C051AFD.bk

**Comment by fourofspades** [comment]
and here is some logcat (1 week expiry): https://pastebin.com/53jV1GZ0

**Comment by tinloaf** [comment]
I don't immediately see the problem here - however, since the problem was introduced in v213, it's probably not caused by my patch - although your logcat also looks like a permission problem. I don't have the time to work on it right now. Would you mind opening a new issue for this so that it does not get lost?

**Comment by fourofspades** [comment]
Sure will do.

**Comment by fourofspades** [comment]
https://github.com/phhusson/treble_experimentations/issues/1211
