### ISSUE TITLE
Umidigi A1 Pro - no camera 

### ISSUE THREAD

**Issue by RalphMalph1** [phhusson/treble_experimentations#104]
I flashed v21 over stockrom with factory reset, flash system.
Everything looks good. Font and screen are small, but after putting that biggest it is ok.
But there is no camera-app.
I installed open-camera and it gives me "Failed to open camera. Camera may be in use by another app"

Hereby the logs. The 1st is from boot to entering android.
The 2nd is from android and then starting open-camera and closing again.
[umidigi_a1_pro_no_working_camera1.txt](https://github.com/phhusson/treble_experimentations/files/2153238/umidigi_a1_pro_no_working_camera1.txt)
[umidigi_a1_pro_no_working_camera2.txt](https://github.com/phhusson/treble_experimentations/files/2153239/umidigi_a1_pro_no_working_camera2.txt)

**Comment by phhusson** [comment]
07-01 23:35:24.395   302   302 W /system/bin/hwservicemanager: getTransport: Cannot find entry android.hardware.camera.provider@2.4::ICameraProvider/legacy/0 in either framework or device manifest.
wtf

Can attach your /vendor/manifest.xml?

**Comment by phhusson** [comment]
hum actually I get this warning on another device as well, so it's not relevant

This bit is more relevant
07-01 23:35:25.096   524   587 I CameraProviderManager: Camera provider internal/0 ready with 0 camera devices

On a mt6580 device with working camera I get:
06-27 00:58:31.581   606   715 I CameraProviderManager: Camera provider internal/0 ready with 2 camera devices

**Comment by phhusson** [comment]
in your logs, the camera HAL is properly running (no lib error or whatever), with pid 539
The HAL properly detects the two attached camera (namely gc5025 and s5k3l8)
07-01 23:35:25.066   539   539 I mtkcam-devicemgr: [logLocked] Physical Devices: # 2
07-01 23:35:25.066   539   539 I mtkcam-devicemgr: [logLocked] --
07-01 23:35:25.066   539   539 I mtkcam-devicemgr: [logLocked]   [00] -> orientation(wanted/setup)=( 90/90 ) BACK  hasFlashUnit:1 SENSOR_DRVNAME_S5K3L8_MIPI_RAW [PhysEnumDevice:0xf1c1ff90]
07-01 23:35:25.066   539   539 I mtkcam-devicemgr: [logLocked] --
07-01 23:35:25.066   539   539 I mtkcam-devicemgr: [logLocked]   [01] -> orientation(wanted/setup)=(270/270) FRONT hasFlashUnit:0 SENSOR_DRVNAME_GC5025_MIPI_RAW [PhysEnumDevice:0xf1c204d0]

When comparing with a reference mtk device, the only log that could be interesting is:
07-01 23:35:24.781   539   539 E mtkcam-devicemgr: [loadDeviceFactory] dlopen: libmtkcam_device1.so error=dlopen failed: library "libgybeauty.so" not found (operator()){#179:vendor/mediatek/proprietary/hardware/mtkcam/legacy/main/hal/devicemgr/CameraDeviceManagerBase.cpp}
and
07-01 23:35:25.044   539   539 E mtkcam-devicemgr: The symbole createVirtualCameraDevice for device version 1 does not exist!!! (operator()){#118:vendor/mediatek/proprietary/hardware/mtkcam/legacy/main/hal/devicemgr/CameraDeviceManagerBase_camera.cpp}

On my reference device, I do have a libgybeauty.so, and compared to your logs, I get virtual devices, while you get none.
I'm guessing libmtkcam_device3.so would give you camera 2 API, and libmtkcam_device1.so camera 1 (but requires libgybeauty.so that you don't have)

Do you have a dump of your stock /system and /vendor?

**Comment by RalphMalph1** [comment]
I found:
/vendor/lib/libmtkcam_device1.so (stock and v21 ofcourse because it is in /vendor)
/vendor/lib64/libmtkcam_device1.so (stock and v21 ofcourse because it is in /vendor)
/system/lib/libgybeauty.so (stock only, not in your v21)
/system/lib64/libgybeauty.so (stock only, not in your v21)

**Comment by phhusson** [comment]
can you try to copy /system/lib64/libgybeauty.so to /system/lib64/vndk and same with lib not 64 and reboot?

**Comment by RalphMalph1** [comment]
readonly hmmm, have to find out how to change to rw

**Comment by RalphMalph1** [comment]
the libgybeauty I copied succesfully, but still no working camera
here the logcat from inside android , starting open camera , closing log (hope it is enough)
[umidigi_a1_pro_no_working_camera2.txt](https://github.com/phhusson/treble_experimentations/files/2154641/umidigi_a1_pro_no_working_camera2.txt)

**Comment by phhusson** [comment]
the logs that is needed is log at startup, not logs when starting camera

**Comment by RalphMalph1** [comment]
ok
[umidigi_a1_pro_no_working_camera3.txt](https://github.com/phhusson/treble_experimentations/files/2154670/umidigi_a1_pro_no_working_camera3.txt)

**Comment by phhusson** [comment]
07-02 11:42:28.713   539   539 E mtkcam-devicemgr: [loadDeviceFactory] dlopen: libmtkcam_device1.so error=dlopen failed: library "libBlurModoule.so" not found (operator()){#179:vendor/mediatek/proprietary/hardware/mtkcam/legacy/main/hal/devicemgr/CameraDeviceManagerBase.cpp}
copy libBlurModoule.so? :P

**Comment by RalphMalph1** [comment]
yes I just saw it in the log, was already busy...lol
Thanx for your support though :-)

**Comment by RalphMalph1** [comment]
now libgybeauty422.so

**Comment by RalphMalph1** [comment]
and libgybeauty420.so

after all that open camera works !!!!

**Comment by RalphMalph1** [comment]
Is it not better to put those files in /vendor/lib ?
How to prevent to do this again with new version? are you implementing these files in your rom?

**Comment by phhusson** [comment]
yes yes it's better to put it in /vendor, it's just that writing /system/ has more changes to work than /vendor :p

Does Google Play/SafetyNet say your device is certified?

**Comment by RalphMalph1** [comment]
I will try to put the files in /vendor/lib and /vendor/lib64 and will let you know.

The stock is certified.
Your v21 is not certified!

**Comment by RalphMalph1** [comment]
Safetynet i didnt try

**Comment by RalphMalph1** [comment]
Before you change anything... I doubt if i installed v21. I am reflashing now and i realize that i had gapps in my previous installation. I will let you know

**Comment by phhusson** [comment]
my ROM is not certified, that's expected, don't worry

**Comment by RalphMalph1** [comment]
I am very sorry. I was sure that I had 21, but I was not testing with v21 as I told you. Now I have v21 and will test things again (also with the camera, will try to put the files in vendor)

**Comment by RalphMalph1** [comment]
/vendor is readonly. adb root + adb remount is not working. Any idea how to make it rw

**Comment by RalphMalph1** [comment]
Question: when lock-screen is on, in the right lower corner there is a camera-icon. When sliding that it asks me to start CAMERA or OPEN CAMERA. I choose CAMERA and it works....the default google cam.
But there is no "link" in de app-drawer for this camera-app. Any idea?

**Comment by Nonta72** [comment]
If the camera app disappears, you need to reflash the rom with wipes or use another camera app

**Comment by phhusson** [comment]
FWIW, you could be interested in #241 to be able to update easily with your camera support.

**Comment by stevea76** [comment]
> /vendor is readonly. adb root + adb remount is not working. Any idea how to make it rw

I too have the same issue trying to add the camera lib files but cannot do so as read only.
[umidigi A1 Pro camera lib files.zip](https://github.com/phhusson/treble_experimentations/files/2825854/umidigi.A1.Pro.camera.lib.files.zip)

**Comment by stevea76** [comment]
resolved by adding to /system/lib/vndk

**Comment by RalphMalph1** [comment]
Really? You solved it?

**Comment by stevea76** [comment]
using mixplorer just copy & pasted the lib & lib64 files above to all the system/lib(lib64)/vndk folders, added them to all the vndk and open camera works. Also used shortcut app to create shortcut widget to stock camera and this works too

**Comment by RalphMalph1** [comment]
I tried a couple of times, but I cannot get it to work
Just installed AOSP 9.0 v111 , still no default camera-app

**Comment by RalphMalph1** [comment]
I installed now AOSP 8.1 v29
Still no default camera-app , but double click the powerbutton opened the camera app...but error
Then I copied the files and rebooted...after that it was working.
Also Open Camera

Too bad this is not working in AOSP 9.0

**Comment by stevea76** [comment]
K used ALSO 9 v111 and added the files to vndk folders, rebooted and open camera works, then used shortcut app off playstore and default camera working as well

**Comment by RalphMalph1** [comment]
> m

Too bad it is not working for me...8.1 I do the same and that is working

**Comment by stevea76** [comment]
Did you add the files to all the vndk folders in v111 @RalphMalph1 (vndk-26-27-28 & sp-26-27-28)?

**Comment by phhusson** [comment]
Lol.
Your device isn't running all vndk s at the same time.

**Comment by stevea76** [comment]
Well as I don't know which vndk to add them to I put them in all, and camera is now working. 😀

**Comment by RalphMalph1** [comment]
I put the filed in /system/lib/vndk
And in /system/lib64/vndk

And it is not working... Are there more vndk directories?

**Comment by RalphMalph1** [comment]
> 
> 
> Well as I don't know which vndk to add them to I put them in all, and camera is now working. 😀

How do you put it in all?
What do you mean by that?
