### ISSUE TITLE
[Redmi Note 8 Pro] Auto-brightness

### ISSUE THREAD

**Issue by tvardero** [phhusson/treble_experimentations#1040]
From #1028 quoting phhusson:
> For auto-brightness you'll probably just need to make an overlay. Create a new issue with stock ROM framework res and getprop and /vendor/build.prop

[getprop.txt](https://github.com/phhusson/treble_experimentations/files/4016112/getprop.txt)
[build.prop.txt](https://github.com/phhusson/treble_experimentations/files/4016127/build.prop.txt)
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/begonia-p-oss
You can get firmware from https://xiaomifirmwareupdater.com/miui/ , device is "begonia", global v11 version.

ROM is MIUI 11

**Comment by tvardero** [comment]
Both on AOSP 9 and AOSP 10

**Comment by jumper047** [comment]
If somebody wont, he may check overlay here -  phhusson/vendor_hardware_overlay/pull/174
