### ISSUE TITLE
[RR] Audiofx Crashing

### ISSUE THREAD

**Issue by darkestDark** [phhusson/treble_experimentations#105]
Everytime playing Music  AudioFx crashes.
Ui AudioFx couldnt be opened. Cleaning Data doesnt help.
Looks like a Null Value return causing it. Logcat attached.

Device Honor 9 lite.
[logcatAudiofx.log.txt](https://github.com/phhusson/treble_experimentations/files/2154038/logcatAudiofx.log.txt)

**Comment by phhusson** [comment]
I'm closing this bug since I no longer maintain a RR.
