### ISSUE TITLE
[Redmi Note 8 Pro][AOSP 9] RIL issue

### ISSUE THREAD

**Issue by tvardero** [phhusson/treble_experimentations#1051]
SIM password was asked. IMEI1 and IMEI2 are not empty.

Redmi Note 8 Pro 128 Gb [begonia]
AOSP 9 latest ARM64 AB, gappsed version.
No Magisk
Mediatek Helio G90T
MIUI 11 vendor

[logcat.txt](https://github.com/phhusson/treble_experimentations/files/4022271/logcat_calls.txt)
[build.prop.txt](https://github.com/phhusson/treble_experimentations/files/4022273/build.prop.txt)
[getprop.txt](https://github.com/phhusson/treble_experimentations/files/4022274/getprop.txt)
![Screenshot_20200104-203208](https://user-images.githubusercontent.com/45442278/71770095-a4064a00-2f31-11ea-91e3-3a0755297543.png)
![Screenshot_20200104-203244](https://user-images.githubusercontent.com/45442278/71770097-a8cafe00-2f31-11ea-9bee-1d227fc45230.png)

**Comment by phhusson** [comment]
That's a global official stable vendor?

**Comment by phhusson** [comment]
Does internet connection work?
Have you tried second slot?
Please provide logs generated right after a reboot with:
`adb logcat -b all`

**Comment by tvardero** [comment]
> That's a global official stable vendor?

Yes, it is. Vendor from MIUI11, global version.

> Does internet connection work?

Wifi only. But i somehow received service message from my carrier about my wrong internet settings. 

> Have you tried second slot?

No change.

> Please provide logs generated right after a reboot with:
`adb logcat -b all`

one moment

**Comment by jumper047** [comment]
RIL works fine on official Havoc 2.9 (based on 9.0).

**Comment by MisterShXwn** [comment]
I made an account to report that in multiple Android 10 GSIs such as Havoc OS 3.4, EvoX 4.169, and AncientOS 3.5, there are issues with RIL. I am on stock Vendor (Android 9 MIUI 11, Begonia). Everything works but the service. Configuring APN settings does nothing.

[logcat.txt](https://github.com/phhusson/treble_experimentations/files/4554666/logcat.txt)
First time doing something like this. I'm not sure if the contents of the log will help.

![md](https://user-images.githubusercontent.com/64559158/80648636-827c2180-8a3e-11ea-81a2-6cb6122504bc.jpg)
In screenshot above, network shows as disconnected no matter what I do.

![pinfo](https://user-images.githubusercontent.com/64559158/80648639-827c2180-8a3e-11ea-9fe8-412d88e7eda8.jpg) 
In phone info, toggling "Mobile Radio Power" and attempting to enable mobile data does nothing. Signal strength is also static.

**Comment by tvardero** [comment]
Not a problem anymore, besides no one use A9 on begonia.
