### ISSUE TITLE
Sony Xperia XZ sensors issues!

### ISSUE THREAD

**Issue by xelmasx** [phhusson/treble_experimentations#1056]
Except fingerprint sensor,  rest of sensors are not working "accelerometer, gyro, proximity, barometer, compass,".

First of all , I flashed "aosp_f8331_10.0_2019-12-24-TREBLE-NIGHTLY.zip"  after that flashed "system-quack-arm64-ab-gapps.img.xz" on it.

Everything works fine, as I said above "except sensors".

**Comment by phhusson** [comment]
that's a community treble, ask your treble dev.

**Comment by xelmasx** [comment]
Thanks for reply.
