### ISSUE TITLE
Android 10 phh Quack (all versions) media codecs not working on Tecno Spark 3 pro (mt6761) (a64 a/b)

### ISSUE THREAD

**Issue by samuelKuseka** [phhusson/treble_experimentations#1058]
I've had this issue since v204 on my phone. Everytime you try to play an audio file it shows 

>  can not open this file 

And ringtones and other system sounds have glitches 
Videos don't play too. 
I'm on v 208 now and it's still the same.
My phone has a pie vendor

**Comment by WilameSouza** [comment]
all mediatek have this problem on Quack

**Comment by phhusson** [comment]
Duplicate of #1002 

See https://issuetracker.google.com/issues/148962635
