### ISSUE TITLE
Random reboots on Huawei P20 Pro

### ISSUE THREAD

**Issue by reppi05** [phhusson/treble_experimentations#106]
Hey,

I'm getting random reboots on my P20 Pro CLT-L29 on every GSI so far.

I've just tried newest AOSP vanilla. Phone was just laying around untouched, screen on for about 10 minutes and then the reboot occured. Same thing about 10 mins later once again.

Logcat till reboot attached.

If you need other files or logs just tell me and I will get them ASAP.

Thank you for your help and effort! We would love to be finally able to run GSIs on our phones.

[aosp-reboot.txt](https://github.com/phhusson/treble_experimentations/files/2154050/aosp-reboot.txt)

Reppi

**Comment by phhusson** [comment]
I see nothing specific in the logs, except perhaps broken NFC :/
Can you get me logs from /sys/fs/pstore?

**Comment by reppi05** [comment]
Thanks for checking.

I checked that folder but it was completely empty after reboot.

**Comment by reppi05** [comment]
Oh, tried again and here we go. The files of the /pstore/ folder. But /splash2 was completely empty. For your information I pulled the files after the second reboot.


[pstore.zip](https://github.com/phhusson/treble_experimentations/files/2154644/pstore.zip)

**Comment by reppi05** [comment]
Could it be kernel panic?

**Comment by phhusson** [comment]
hum, this log has a reboot after only 3 minutes, and says that you requested the reboot
[  171.972625s][pid:1,cpu6,init]init: application: namesystem_server ,pid( 959)  request shutdown sys.powerctl - reboot,userrequested

**Comment by reppi05** [comment]
That's weird. Might be the reboot to TWRP after the random reboot occured. Tried to grab some new files for you. I hope you can work with those at least. Don't know what I could do else to assist you.
[pstore_new.zip](https://github.com/phhusson/treble_experimentations/files/2158663/pstore_new.zip)
[reboot_aosp.txt](https://github.com/phhusson/treble_experimentations/files/2158664/reboot_aosp.txt)

**Comment by phhusson** [comment]
<3>[  615.662780s][pid:274,cpu0,hwboot_time]hwboot_timer:update timer [long and short]!
<3>[  615.662841s][pid:274,cpu0,hwboot_time]hwboot_timer: 10 minutes timer expired! boot fail!

**Comment by phhusson** [comment]
do you have kernel sources?

**Comment by reppi05** [comment]
Yes sir. Should be this: 

http://download-c1.huawei.com/download/downloadCenter?downloadId=99493&version=421449&siteCode=worldwide

**Comment by phhusson** [comment]
Ok so the kernel expects that someone calls BFMR_SET_BOOT_STAGE ioctl on /dev/bfm or something like that, but noone does.
Do you have a dump of stock ROM? (with system.img, vendor.img, product.img, ...)

**Comment by reppi05** [comment]
I only have this and don't know what you exactly mean by dump. Can you work with this?

https://drive.google.com/drive/folders/1CjCiDcvG-XSryH4kp1BjBEFwu9TKKMd4

**Comment by reppi05** [comment]
Got some help and now I got everything you need I suppose:
https://drive.google.com/folderview?id=1gqfUrFAyGSumQsy9GoBaDgel7CYg7gA2

**Comment by reppi05** [comment]
Can you solve the issue and will you implement it in your next update?

**Comment by sideflip15** [comment]
bump!

**Comment by David6910** [comment]
Please help us @phhusson, we want a stable treble...

**Comment by phhusson** [comment]
Can you remove /system/bin/uncrypt and retry?

> adb root
> adb remount
> adb shell rm /system/bin/uncrypt

**Comment by David6910** [comment]
@phhusson oh god! i think it works now! But its only me or when i try to unlock the phone with a 4 digits pin i get wrong pin

**Comment by David6910** [comment]
https://i.imgur.com/LqFj1WQ.png 20 minutes on !

**Comment by David6910** [comment]
@phhusson Ok stays on! without any reboot!

**Comment by phhusson** [comment]
I believe this issue has been fixed now in my releases
If this isn't the case, feel free to re-open this issue.
