### ISSUE TITLE
Pls add fix fingerprint for Vsmart live (meizu 16xs)

### ISSUE THREAD

**Issue by tipukingteam** [phhusson/treble_experimentations#1065]
My device vsmart live fingerprint error
Please fix me in the next updates.
Fingerprint source code:https://github.com/thinhx2/vsmart_V620A_fod_hal?files=1

**Comment by phhusson** [comment]
pls send vsmart live

Le sam. 11 janv. 2020 à 16:29, tipukingteam <notifications@github.com> a
écrit :
