### ISSUE TITLE
[HTC U11+ ocm][ASOP10 v204, 208, 209] Camera not working

### ISSUE THREAD

**Issue by 7HE-W0R1D** [phhusson/treble_experimentations#1067]
Every time I open the camera, it crashes.
Now AOSP10 v209, vendor htc stock 9.0.
Non of the camera app works(Open camera, stock camera...), including those QR code scanning apps.
I grabbed some logs using logcat, hope that will help.
(I reported the same issue but didn't get a response; it's issue #939 )
[logcat01.log](https://github.com/phhusson/treble_experimentations/files/4050759/logcat01.log)

**Comment by usman0tahir** [comment]
Hey! did you ever get it to work?
and what about your Bluetooth bug?

**Comment by 7HE-W0R1D** [comment]
Sorry bro the camera never worked... so I changed to havoc os after closed the issue.
However, I do manage to get to audio working with this:
https://github.com/phhusson/treble_experimentations/issues/48#issuecomment-403554459
just copy those three files to /system/etc and reboot the phone.
The phone call still comes from the speaker but in a normal voice, the other media sounds all come through Bluetooth.
