### ISSUE TITLE
Huawei P20 Lite Stuck

### ISSUE THREAD

**Issue by mo-bay** [phhusson/treble_experimentations#1068]
Hi,

I've tried installing the AOSP 10 V209 rom but after booting the phone is stuck on blank screen with ab vanilla or is stuck on the welcome please wait screen with gapps. I've tried 206 and I am stuck on the android logo.

I am attaching the log cat link for the v209 vanilla. 
[Terminal Saved Output.log](https://github.com/phhusson/treble_experimentations/files/4057113/Terminal.Saved.Output.log)

**Comment by gkeegan** [comment]
Was the phone on emui 8 or emui 9 vendor? According to wiki you need to use a-only for Emui 8 devices.

**Comment by mo-bay** [comment]
It was emui 8 from the vendor, but was upgraded to Emui 9. will I still need to use a-only?

**Comment by gkeegan** [comment]
Not sure. Wiki doesn't specify. For the regular P10 it uses AB when on Emui 9, but who knows if that is reflective of the P10 lite.

**Comment by mo-bay** [comment]
ok, I restored to to Emui 9 and then used flash boot to install the AB rom, The phone started but the        simcard was not read, and some apps where crashing. According to the wiki I just have to flash it with fast boot. does it have any requirements of having TWRP installed?

ps : I forgot to mention this the dual sim variant (perhaps they all are)

**Comment by mo-bay** [comment]
Attaching fresh logcat [
[logcatv2.txt](https://github.com/phhusson/treble_experimentations/files/4060026/logcatv2.txt)
](url)

**Comment by mo-bay** [comment]
Issue resolved, had to factory reset from EMUI Recovery.
