### ISSUE TITLE
Moto G6 Play, the random wifi drops connection can be solved

### ISSUE THREAD

**Issue by choice77** [phhusson/treble_experimentations#1085]
Moto G6 play works very well on treble gsi made by Pieere (Oreo/Pie versions), but theres a little bug when smartphone go idle. The problems are two: 

1 - When turnoff the screen or internet connection are idle, the dhcpd (or dhclinet) needs to reconnect to router. For this wifi re-connection (link up wlps0) is necessary about 12 seconds to communicated with router. (And about 10 seconds with static ip on moto g6 play wifi settings).

2 - Because, the problem one, apps on second plan (whatsapp, twitter) are totatly off when the screen is off or smartphone are idle.

On logcat, the only error message are:
```
linker
CANNOT LINKER EXECUTABLE "/system/vendor/bin/ims_rtp_daemon: library "vendor.qti.imsrtpservice@1.0.so" not found
```
The log bellow shows that a binary code by qualcomm or motorola that is responsable for communicate between acpi modes  and wifi are not linked, or not can be distributed on treble roms (because is proprietary code).

The problem related, occur with all versions 8 and 9 of treble gsi roms.
Is it possible to resolve?

**Comment by phhusson** [comment]
This problem has absolutely nothing to do with WiFi.
This is for ViLTE

**Comment by choice77** [comment]
Thanks, for this technichal tip, phhusson!
