### ISSUE TITLE
[SM-J701MT] [AOSP 10.0 v209] Random Reboot

### ISSUE THREAD

**Issue by Noryub** [phhusson/treble_experimentations#1088]
Im facing  the problem of random reboots in my device with the latest Android Version, PIE GSI ROMS works flawless.

Im aware that **maybe** this is a problem caused by OMX and some Media Codecs, but there is no issue open or closed about this on this repository. Lets be sure about this.

I just want to see the exact error in the logcat that cause this reboots and know if there is a possible fix to this, please help me.

<< Useful Info >>
GSI ROM:  system-quack-arm64-aonly-vanilla.img.xz
Kernel: CronosKernel 5.0
Treble: Not Google-Certified, using SpagetX. (G965F Vendor with VNDK-28)
Stock Rom: J701MTVJS7CSG1

[ZIP REMOVED]

**Comment by phhusson** [comment]
What's needed for logs is /proc/last_kmsg and/or /sys/fs/pstore and your zip doesn't contain either

**Comment by Noryub** [comment]
Sorry, now here is the files.

[BugReport_2.zip](https://github.com/phhusson/treble_experimentations/files/4133070/BugReport_2.zip)

**Comment by Noryub** [comment]
> What's needed for logs is /proc/last_kmsg and/or /sys/fs/pstore and your zip doesn't contain either

This will take a while, to give you those files I will have to reinstall Android 10.

Please be patient, I will give them to you soon.

**Comment by phhusson** [comment]
no problem: I just get mails when you send messages here, so it's
totally asynchronous

**Comment by Noryub** [comment]
Now, there is the files.

[BugReport_2.zip](https://github.com/phhusson/treble_experimentations/files/4133446/BugReport_2.zip)

**Comment by Noryub** [comment]
Another one with other reboot, just in case.

[BugReport_3.zip](https://github.com/phhusson/treble_experimentations/files/4133532/BugReport_3.zip)

**Comment by phhusson** [comment]
Was the device frozen before the reboot?

**Comment by Noryub** [comment]
Freeze? No, I think not.
It happens randomly doing anything, It is instantaneous.

**Comment by phhusson** [comment]
K, that's a bug in your kernel.

See "task tee_irq_bh:1413 blocked for more than 720 seconds"

**Comment by Noryub** [comment]
Bug in the kernel then...
What can I do?

**Comment by phhusson** [comment]
Ask the kernel developer to look at the log (the one in bugreport_3.zip is
fine for that) and fix it?

**Comment by Noryub** [comment]
Ok I will do it, thanks for helping me!
I think this issue can be closed now.
