### ISSUE TITLE
Onplus 7 pro OTG issue

### ISSUE THREAD

**Issue by biboyrafik25** [phhusson/treble_experimentations#1090]
When i connect my usb device phone says you need format it. When its done says the same thing. In twrp works fine

**Comment by phhusson** [comment]
Plug in your computer, do `adb logcat -c`m unplug, plug usb device, wait
10s, unplug, do `adb logcat -d > logs.txt` and attach logs.txt here

**Comment by biboyrafik25** [comment]
I understand whats the problem : first installation done with android 10 base and no issue. 2nd installation was done with android 9 base why ? because i want 90hz and i use this way 
![Annotation 2020-01-30 093202](https://user-images.githubusercontent.com/55406730/73432708-96cb5800-4343-11ea-9a94-d6944426fc05.png)

**Comment by phhusson** [comment]
You could try
https://play.google.com/store/apps/details?id=eu.chainfire.tv.hz&hl=en_US
to force to 90hz


Le jeu. 30 janv. 2020 à 09:33, biboyrafik25 <notifications@github.com> a
écrit :

**Comment by biboyrafik25** [comment]
ok i will try and and what about warp charge ?

**Comment by phhusson** [comment]
There is no opensource solution available for warp charge at the moment,
and I don't want to include device-specific closed source blobs.
My recommendation is to stick with AndroPlus' magisk module.

Le jeu. 30 janv. 2020 à 10:05, biboyrafik25 <notifications@github.com> a
écrit :

> ok i will try and and what about warp charge ?
>

**Comment by biboyrafik25** [comment]
i understand thx a lot for ur patience ;)

**Comment by phhusson** [comment]
For hz issue, please dump the result of:
`adb shell dumpsys SurfaceFlinger`

**Comment by biboyrafik25** [comment]
sorry but i can't copy the result to a .text file with powershell

**Comment by phhusson** [comment]
`adb shell dumpsys SurfaceFlinger > dumpsys-sf.txt`
and attach dumpsys-sf.txt

Le jeu. 30 janv. 2020 à 11:02, biboyrafik25 <notifications@github.com> a
écrit :

**Comment by biboyrafik25** [comment]
Its done....
Ps : on en apprend tous les jours LOL
[dumpsys-sf.txt](https://github.com/phhusson/treble_experimentations/files/4133429/dumpsys-sf.txt)

**Comment by phhusson** [comment]
Hum, that's with AndroPlus' dtbo right?
The only mode listed is 90fps, no 60fps

**Comment by biboyrafik25** [comment]
No weird
Dtbo works only with pie base. i have now ur gsi with Android Q base

**Comment by phhusson** [comment]
So you think you're currently running 60fps?

**Comment by biboyrafik25** [comment]
no i think its running 90fps now dislpay very smooth and previous install it was not the case and I had checked with Aida64 which indicated me 60hz

**Comment by biboyrafik25** [comment]
thx for ur help
