### ISSUE TITLE
Treble Build Error

### ISSUE THREAD

**Issue by him1234** [phhusson/treble_experimentations#1096]
<pre>[438/1166] including packages/apps/Backgrounds/app/src/main/Android.mk ...
/bin/bash: 第 0 行: test: -gt: 需要一元表达式
[626/1166] including system/sepolicy/Android.mk ...
<b>system/sepolicy/Android.mk:79: </b><font color="#FF55FF"><b>warning: </b></font><b>BOARD_SEPOLICY_VERS not specified, assuming current platform version</b>
<b>system/sepolicy/Android.mk:89: </b><font color="#FF55FF"><b>warning: </b></font><b>Be careful when using the SELINUX_IGNORE_NEVERALLOWS flag. It does not work in user builds and using it will not stop you from failing CTS.</b>
[1155/1166] including vendor/lineage/bootanimation/Android.mk ...
<b>vendor/lineage/bootanimation/Android.mk:19: </b><font color="#FF55FF"><b>warning: </b></font><b>TARGET_SCREEN_WIDTH is not set, using default value: 1080</b>
<b>vendor/lineage/bootanimation/Android.mk:23: </b><font color="#FF55FF"><b>warning: </b></font><b>TARGET_SCREEN_HEIGHT is not set, using default value: 1920</b>
[1166/1166] including vendor/vndk-tests/Android.mk ...
<b>build/make/core/Makefile:28: </b><font color="#FF55FF"><b>warning: </b></font><b>overriding commands for target `/media/him1234/source2/lineage/out/target/product/phhgsi_arm64_a/system/etc/apns-conf.xml&apos;</b>
<b>build/make/core/base_rules.mk:412: </b><font color="#FF55FF"><b>warning: </b></font><b>ignoring old commands for target `/media/him1234/source2/lineage/out/target/product/phhgsi_arm64_a/system/etc/apns-conf.xml&apos;</b>
ninja: error: &apos;/media/him1234/source2/lineage/out/target/common/obj/JAVA_LIBRARIES/sap-api-java-static_intermediates/classes-header.jar&apos;, needed by &apos;/media/him1234/source2/lineage/out/target/common/obj/APPS/Bluetooth_intermediates/classes-full-debug.jar&apos;, missing and no known rule to make it
18:27:24 ninja failed with: exit status 1
</pre>
I have a problem when compiling lineages16.0 GSI.
Can you help me to solve this problem?
Thank you very much!!!!!!!!

**Comment by wxo1** [comment]
Same here, no idea how to fix. Did you ever figure this out?

**Comment by him1234** [comment]
> Same here, no idea how to fix. Did you ever figure this out?

Not yet.

**Comment by him1234** [comment]
> > Same here, no idea how to fix. Did you ever figure this out?
> 
> Not yet.

I've given up to solve it.
