### ISSUE TITLE
HTC U11+ problem with boot

### ISSUE THREAD

**Issue by sardroid** [phhusson/treble_experimentations#11]
HTCU11+ with v14 - flashing fine, after flashing the charging lamp lights up, but it's still hanging on the Android logo. After factory reset charging lamp lights not up and phone still ganging on the Android logo. When I try to do logcat in fastboot shows: waiting for device. Maybe I'm gonnaflash TWRP and then I'll try?

**Comment by phhusson** [comment]
Does adb devices -l see the device?
With TWRP, you can read logs from /proc/last_kmsg so that can be useful

**Comment by sardroid** [comment]
I flashing the system.img with the command: fastboot -S 512M flash system system.img

**Comment by sardroid** [comment]
c:\fastboot>adb devices -l
List of devices attached
FA7CC1E00017           unauthorized

**Comment by sardroid** [comment]
I did not do a factory reset. Only reboot.

**Comment by sardroid** [comment]
Flashing TWRP now to make a logcat?

**Comment by phhusson** [comment]
Yeah, you can try reading /proc/last_kmsg or /sys/fs/pstore/* from twrp

**Comment by sardroid** [comment]
TWRP flashed. How to make a logcat in it?

**Comment by sardroid** [comment]
I'm sorry, but I have not done it yet.

**Comment by phhusson** [comment]
no you don't need root. anything in /sys/fs/pstore?

**Comment by sardroid** [comment]
c:\fastboot>adb shell /sys/fs/pstore
/sbin/sh: /sys/fs/pstore: Permission denied

**Comment by sardroid** [comment]
Maybe the factory reset will help?

**Comment by sardroid** [comment]
Only then that the charging diode goes out.

**Comment by phhusson** [comment]
ls /sys/fs/pstore

**Comment by sardroid** [comment]
c:\fastboot>adb shell ls /sys/fs/pstore

c:\fastboot>

and nothing happens

**Comment by sardroid** [comment]
c:\fastboot>adb shell ls /sys/fs/pstore
error: device unauthorized.
This adbd's $ADB_VENDOR_KEYS is not set; try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.

**Comment by sardroid** [comment]
after factory reset:
c:\fastboot>adb devices -l
List of devices attached
FA7CC1E00017           unauthorized

**Comment by phhusson** [comment]
Right, you'll need a system.img with force authorized adb. I'll give you that in a few hours.

**Comment by sardroid** [comment]
Great news:) Thank you.

**Comment by phhusson** [comment]
https://drive.google.com/open?id=1A87kqIFodmydgnzVrMEPjhkUq4B1QsUQ
This should give you access to adb

**Comment by sardroid** [comment]
Thank you. After flashing, do the factory reset?

**Comment by phhusson** [comment]
it would be better to, yes

**Comment by sardroid** [comment]
Oki

**Comment by sardroid** [comment]
After the factory reset the phone still hangs on the Android logo and the charging diode is off.

**Comment by phhusson** [comment]
but does adb work now?

**Comment by sardroid** [comment]
c:\fastboot>adb shell ls /sys/fs/pstore
ls: /sys/fs/pstore: Permission denied

**Comment by phhusson** [comment]
yeah so you got adb working. so you can adb logcat

**Comment by sardroid** [comment]
adb logcat -d ?

**Comment by phhusson** [comment]
hum yeah should work

**Comment by sardroid** [comment]
[log.docx](https://github.com/phhusson/treble_experimentations/files/1857418/log.docx)

**Comment by phhusson** [comment]
Same thing with 
https://drive.google.com/open?id=1YU4xbXUC6zRZGL2R3ULAf23ju6AME8yZ

**Comment by sardroid** [comment]
Downloading

**Comment by sardroid** [comment]
[logcat2.docx](https://github.com/phhusson/treble_experimentations/files/1857573/logcat2.docx)

**Comment by phhusson** [comment]
Does 8.0 version boot?
https://www.androidfilehost.com/?fid=817906626617958349

**Comment by sardroid** [comment]
I've tried this version before and it was the same.

**Comment by jinbolx** [comment]
I have the same issuse when i updated my htc u11+ ,i tried to degraded the phone‘s software version to the
first version by flash stock system.img  then flash the treble image and it does boot

**Comment by sardroid** [comment]
How you downgraded the phone?

**Comment by sardroid** [comment]
@jinbolx downgrade to 1.10 did not help.

**Comment by phhusson** [comment]
for some additional logs, please do (while the phone ie stuck on android bootanimation)
adb root
then in adb shell; do strace -f -p 1 -s 300 -o /dev/str
then ~ 30s later, press ctrl-c to stop it
then adb pull /dev/str
And then send the retrieved "str" file here

**Comment by sardroid** [comment]
Here is:


[str.zip](https://github.com/phhusson/treble_experimentations/files/1859158/str.zip)

**Comment by sardroid** [comment]
Did it help?

**Comment by sardroid** [comment]
Any news?

**Comment by sardroid** [comment]
@phhusson ?

**Comment by sardroid** [comment]
Thank you for trying. I wish you a healthy and joyful Easter holiday.

**Comment by newyesor** [comment]
I have the same issuse when i updated my htc u11+ .
I hae downgrade os to 1.10.xxx.x then  flash Ruu oldversion.
I try to flash system again and I try to  format data berfore press reboot system.
I try to  flash systemV9 then boot pass on my devices.

**Comment by newyesor** [comment]
I try to flash system.img from above link and device stuck android logo.
C:\adb>adb devices -l
List of devices attached
FA7AW1E00416           device product:treble_arm64_agS model:Phh_Treble_with_GApps device:phhgsi_arm64_a

**Comment by phhusson** [comment]
could you link me to a dump of boot, system, vendor partition of stock rom?

**Comment by newyesor** [comment]
I will upload file  boot, system, vendor partition of stock rom.

**Comment by sardroid** [comment]
I can put a link to ruu with stock rom.

**Comment by sardroid** [comment]
1.24.401.7: https://androidfilehost.com/?fid=890129502657592631

**Comment by DroidAlexandra** [comment]
https://forum.xda-developers.com/showthread.php?t=1672425

**Comment by newyesor** [comment]
Boot 1.24.400.3
https://drive.google.com/open?id=1QDrWTdYNhR07X2IRzKRNL59BIx_y3Zjh

**Comment by DroidAlexandra** [comment]
https://forum.xda-developers.com/showthread.php?t=2534428

Extracting RUU files

**Comment by DroidAlexandra** [comment]
https://forum.xda-developers.com/chef-central/android/tool-universal-htc-ruu-rom-decryption-t3382928

Okay that one actually works, sorry

**Comment by phhusson** [comment]
I'll also need your /vendor/etc/fstab...

**Comment by newyesor** [comment]
I will upload file system.img (1.24.400.3) .

**Comment by phhusson** [comment]
could you get me adb shell su 0 dmesg when starting GSI?

**Comment by newyesor** [comment]
I am not pull adb shell su 0 dmesg  or also adb shell su 0 ls -lZ /firmware/image/.

**Comment by phhusson** [comment]
sorry I don't understand

**Comment by newyesor** [comment]
Sorry,I do not use this above cmd for test it.
adb shell su 0 dmesg
adb shell su 0 ls -lZ /firmware/image/.

**Comment by sardroid** [comment]
adb shell su 0 dmesg:
[adb shell su 0 dmesg.docx](https://github.com/phhusson/treble_experimentations/files/1865549/adb.shell.su.0.dmesg.docx)

**Comment by sardroid** [comment]
c:\fastboot>adb shell su 0 ls -lZ /firmware/image/
total 61216
-r--r----- 1 system system u:object_r:vfat:s0   230056 2017-12-20 13:03 mba.mbn
-r--r----- 1 system system u:object_r:vfat:s0     1012 2017-12-20 13:03 modem.b00
-r--r----- 1 system system u:object_r:vfat:s0     7400 2017-12-20 13:03 modem.b01
-r--r----- 1 system system u:object_r:vfat:s0     8488 2017-12-20 13:03 modem.b02
-r--r----- 1 system system u:object_r:vfat:s0     8728 2017-12-20 13:03 modem.b03
-r--r----- 1 system system u:object_r:vfat:s0   219040 2017-12-20 13:03 modem.b04
-r--r----- 1 system system u:object_r:vfat:s0   308779 2017-12-20 13:03 modem.b05
-r--r----- 1 system system u:object_r:vfat:s0    50232 2017-12-20 13:03 modem.b06
-r--r----- 1 system system u:object_r:vfat:s0   132268 2017-12-20 13:03 modem.b07
-r--r----- 1 system system u:object_r:vfat:s0   352340 2017-12-20 13:03 modem.b08
-r--r----- 1 system system u:object_r:vfat:s0  2550204 2017-12-20 13:03 modem.b09
-r--r----- 1 system system u:object_r:vfat:s0       45 2017-12-20 13:03 modem.b10
-r--r----- 1 system system u:object_r:vfat:s0  1101824 2017-12-20 13:03 modem.b11
-r--r----- 1 system system u:object_r:vfat:s0 19003920 2017-12-20 13:03 modem.b12
-r--r----- 1 system system u:object_r:vfat:s0   287632 2017-12-20 13:03 modem.b13
-r--r----- 1 system system u:object_r:vfat:s0     1148 2017-12-20 13:03 modem.b14
-r--r----- 1 system system u:object_r:vfat:s0   517552 2017-12-20 13:03 modem.b16
-r--r----- 1 system system u:object_r:vfat:s0 16137633 2017-12-20 13:03 modem.b17
-r--r----- 1 system system u:object_r:vfat:s0  2689224 2017-12-20 13:03 modem.b18
-r--r----- 1 system system u:object_r:vfat:s0    67136 2017-12-20 13:03 modem.b20
-r--r----- 1 system system u:object_r:vfat:s0   664019 2017-12-20 13:03 modem.b21
-r--r----- 1 system system u:object_r:vfat:s0 11104256 2017-12-20 13:03 modem.b22
-r--r----- 1 system system u:object_r:vfat:s0   131072 2017-12-20 13:03 modem.b23
-r--r----- 1 system system u:object_r:vfat:s0  1048576 2017-12-20 13:03 modem.b24
-r--r----- 1 system system u:object_r:vfat:s0   433920 2017-12-20 13:03 modem.b25
-r--r----- 1 system system u:object_r:vfat:s0    81476 2017-12-20 13:03 modem.b26
-r--r----- 1 system system u:object_r:vfat:s0     4848 2017-12-20 13:03 modem.b27
-r--r----- 1 system system u:object_r:vfat:s0      224 2017-12-20 13:03 modem.b28
-r--r----- 1 system system u:object_r:vfat:s0     8412 2017-12-20 13:03 modem.mdt
-r--r----- 1 system system u:object_r:vfat:s0      405 2017-12-20 12:54 modemr.jsn
-r--r----- 1 system system u:object_r:vfat:s0  5222489 2017-12-20 13:03 qdsp6m.qdb
-r--r----- 1 system system u:object_r:vfat:s0       27 2017-12-20 12:27 radiover.cfg
-r--r----- 1 system system u:object_r:vfat:s0       27 2017-12-20 12:27 version.cfg

c:\fastboot>

**Comment by sardroid** [comment]
@phhusson Can I help you somehow?

**Comment by phhusson** [comment]
Can you try with https://drive.google.com/open?id=1YU4xbXUC6zRZGL2R3ULAf23ju6AME8yZ ?
I don't really expect it to boot, but I guess it should be able to boot further
So please gather adb logs on it

**Comment by DroidAlexandra** [comment]
Downloading.

**Comment by DroidAlexandra** [comment]
As you expected, it still get's stuck on Android logo, logs attached. 

[u11plus v2.txt](https://github.com/phhusson/treble_experimentations/files/1865672/u11plus.v2.txt)

**Comment by phhusson** [comment]
Ok, so actually my changes changed nothing at all.

I think I understand the issue, I guess that's the security patch level.
I changed security patch level to 2017-12-01 (as is written in the system.img you've given me)
https://drive.google.com/open?id=1YU4xbXUC6zRZGL2R3ULAf23ju6AME8yZ
Can you try with this?

**Comment by sardroid** [comment]
Downloading

**Comment by sardroid** [comment]
Factory reset with command fastboot -w before reboot?

**Comment by phhusson** [comment]
no need to factory reset

**Comment by DroidAlexandra** [comment]
Still stuck on Android logo, logs in a minute

**Comment by sardroid** [comment]
Damn, I made a factory. And a bad sign, because the charging diode does not light up. I'll wait a few minutes. Later I try without a factory.

**Comment by phhusson** [comment]
Sounds like your device got its battery depleted, you should flash stock back, to let it recharge

**Comment by DroidAlexandra** [comment]
[u11plus v3.txt](https://github.com/phhusson/treble_experimentations/files/1865728/u11plus.v3.txt)
Logs from build with Dec security patch

**Comment by sardroid** [comment]
My log:
[log.docx](https://github.com/phhusson/treble_experimentations/files/1865740/log.docx)

**Comment by DroidAlexandra** [comment]
> Sounds like your device got its battery depleted, you should flash stock back, to let it recharge

That's why I got 2 Muskie on my desk haha :P

**Comment by sardroid** [comment]
No no. When I did not do the factory after the reboot, the charging diode was on.

**Comment by phhusson** [comment]
https://drive.google.com/open?id=1YU4xbXUC6zRZGL2R3ULAf23ju6AME8yZ
This one also says it is an Android 8.0.0 instead of 8.1.0

**Comment by DroidAlexandra** [comment]
My charging LED is also always off while stuck on the Android logo, but my battery is full because I'm constantly plugged in while working in fastboot (LED works in fastboot/download)

**Comment by sardroid** [comment]
I never upload a system.img without a minimum of 90% of the battery.

**Comment by sardroid** [comment]
Downloading.

**Comment by DroidAlexandra** [comment]
BOOTED!!

**Comment by sardroid** [comment]
Really??

**Comment by DroidAlexandra** [comment]
Latest 8.0 build seems working fine after one reboot, I went trough the setup screen fine, fingerprint and camera working, all seems stable.

Do you need logs anyway?

**Comment by phhusson** [comment]
I guess that's good news, but I'm miles away from a proper fix...

Can you dump me the content of /proc/device-tree folder?

**Comment by DroidAlexandra** [comment]
Regarding the other mobile data issue.

SIM card recognised fine.
It asked me to reboot when I inserted it and it asked me if I want to use SIM 1 as main sim.
It connects (I see signal bars, can call), but no mobile data.

German o2/Telefonica

Dump in a moment

**Comment by phhusson** [comment]
Well let's discuss this on proper issue
https://github.com/phhusson/treble_experimentations/issues/2

**Comment by DroidAlexandra** [comment]
That took strange long to pull 14582 files 
[device-tree.zip](https://github.com/phhusson/treble_experimentations/files/1865784/device-tree.zip)

**Comment by sardroid** [comment]
Affirmative-booting. @phhusson You are my hero.

**Comment by DroidAlexandra** [comment]
Gonna need to resize the partition, not enough space to even download AdAway hosts files

**Comment by newyesor** [comment]
I have the  issuse when i updated my htc u11+
I flash the treble image and it does boot.
My devices is not see sd card.

**Comment by sardroid** [comment]
When I make a call, I can not hear anything in the phone.

**Comment by newyesor** [comment]
@DroidAlexandra
How to fix mobile data ?

**Comment by sardroid** [comment]
@newyesor only @phhusson can help...

**Comment by edwkmho** [comment]
File system_tmp.img provide on 11 Apr

command : fastboot flash system system.img

Result as below :
target reported max download size of 2399200000 bytes
erasing 'system'...
OKAY [  0.293s]
sending 'system' (1488044 KB)...
FAILED (remote: data too large, 1523757300 > 1319157760)
finished. total time: 2.324s

**Comment by sardroid** [comment]
@edwkmho try: fastboot -S 512M flash system system.img

**Comment by edwkmho** [comment]
[HTC U11Plus_Radio_Log.txt](https://github.com/phhusson/treble_experimentations/files/1899972/HTC.U11Plus_Radio_Log.txt)

**Comment by edwkmho** [comment]
Many thanks sardroid

**Comment by edwkmho** [comment]
@phhusson 
1.Bluetooth seems to work with connection to JBL speaker and Windows PC
2. USB-c Mic not working - when plug in phone no reaction at all.
3. Google Play Store will work for a short while then remain Download Pending, need to reboot for it to work. 
4. PC cant see phone folder when connected with USB

**Comment by phhusson** [comment]
Closing since boot works now
