### ISSUE TITLE
[ulefone armor 6e]night light intensity randomly changing

### ISSUE THREAD

**Issue by fherenda1** [phhusson/treble_experimentations#1116]
When scrolling significant change in night light can be noticed. It seems to happen whenever I scroll and gets back to normal after stopping.

**Comment by phhusson** [comment]
I think there is another issue already opened for this elsewhere
Anyway it is tracked at google's at
https://issuetracker.google.com/issues/149114355

Le mar. 18 févr. 2020 à 17:02, fherenda1 <notifications@github.com> a
écrit :
