### ISSUE TITLE
[Infinix Note 6] No X-Pen support

### ISSUE THREAD

**Issue by AndyCGYan** [phhusson/treble_experimentations#1125]
Device: Infinix Note 6 (x610)
Treble status: Yes, system-as-root, native
Stock Android version: 9 - full dump [here](https://github.com/AndroidDumps/infinix_infinix-x610_dump)

X-Pen doesn't work - system won't respond to its touches or plug/unplug.
lshal output: [lshal.txt](https://github.com/phhusson/treble_experimentations/files/4234990/lshal.txt)
Logcat while unplugging then plugging in the pen: [pen_log.txt](https://github.com/phhusson/treble_experimentations/files/4234993/pen_log.txt)
Unlike Samsung with Wacom digitizers, this device seems to use Hanvon technology.

**Comment by AndyCGYan** [comment]
Additional info: the pen input is registered in the OS as `/dev/input/event5` "Elan Touchscreen Pen", and there's a pen position detector (a pair of spring-loaded pins in the pen slot) as `/dev/input/event4` "xpen".
I've captured a short sequence of `getevent` output corresponding to pen removal -> write -> pen insert: 
[getevent.txt](https://github.com/phhusson/treble_experimentations/files/4249994/getevent.txt)

**Comment by phhusson** [comment]
todo: compare event type and axis with input-event-code to see if it is a
mouse or what

**Comment by AndyCGYan** [comment]
Can you explain a bit more? Should I go find a BT mouse and record its sequence as well for comparison?

**Comment by phhusson** [comment]
Right sorry for the lack of explanation, I was on lunch and wanted mostly not to forget it :P

Anyway, in /usr/include/linux/input-event-codes.h you'll find a description of the values.

In your case, first for event4:
```
/dev/input/event4: 0001 00bf 00000001
/dev/input/event4: 0001 00bf 00000000
```
#define EV_KEY          0x01
#define KEY_F21         191

I'm not sure what was it. I guess that's when you removed the pen from the phone?
So it press key F21 when you remove the pen

Now for the real events on event5
```
/dev/input/event5: 0003 0035 00000275 # EV_ABS ABS_MT_POSITION_X
/dev/input/event5: 0003 0036 000006f7 # EV_ABS ABS_MT_POSITION_Y
/dev/input/event5: 0003 003a 00000000 # EV_ABS ABS_MT_PRESSURE
/dev/input/event5: 0003 003b 0000000f # EV_ABS ABS_MT_DISTANCE
/dev/input/event5: 0001 014a 00000001 # EV_KEY BTN_TOUCH
/dev/input/event5: 0000 0002 00000000 # EV_SYN SYN_MT_REPORT
```

So, I'm quite perplex, it looks like you don't have close events, you only get events when the pen actual touches the screen? That's pretty unusual for a pen

And then, it seems to me that it just behaves like a touchscreen, so it should at least behave like a touchscreen (I'd expect better from a pen, but well...)

Please dump `adb shell dumpsys input` perhaps we'll see why android doesn't think it is a touchscreen
(or there is only one touchscreen allowed at a time? that'd kind of make sense)

**Comment by AndyCGYan** [comment]
> I'm not sure what was it. I guess that's when you removed the pen from the phone?

Right, removal and insertion. I don't mind if this pen detector doesn't get accounted for, as I have no use for it on AOSP anyway.
(Unless the digitizer only activates when there's a removal event - which as my tests show is not the case)

> Please dump `adb shell dumpsys input` perhaps we'll see why android doesn't think it is a touchscreen
> (or there is only one touchscreen allowed at a time? that'd kind of make sense)

[dumpsys_input.txt](https://github.com/phhusson/treble_experimentations/files/4250431/dumpsys_input.txt)

**Comment by phhusson** [comment]
My recommendation is to try this:
edit frameworks/native/services/inputflinger/EventHub.cpp and change
```
    // See if this is a touch pad.
    // Is this a new modern multi-touch driver?
    if (test_bit(ABS_MT_POSITION_X, device->absBitmask)
            && test_bit(ABS_MT_POSITION_Y, device->absBitmask)) {
        // Some joysticks such as the PS3 controller report axes that conflict
        // with the ABS_MT range.  Try to confirm that the device really is
        // a touch screen.
        if (test_bit(BTN_TOUCH, device->keyBitmask) || !haveGamepadButtons) {
            device->classes |= INPUT_DEVICE_CLASS_TOUCH | INPUT_DEVICE_CLASS_TOUCH_MT;
        }
    // Is this an old style single-touch driver?
    }
```
to
```
    // See if this is a touch pad.
    // Is this a new modern multi-touch driver?
    if (test_bit(ABS_MT_POSITION_X, device->absBitmask)
            && test_bit(ABS_MT_POSITION_Y, device->absBitmask)
&& !test_bit(ABS_DISTANCE, device->absBitmask)) {
        // Some joysticks such as the PS3 controller report axes that conflict
        // with the ABS_MT range.  Try to confirm that the device really is
        // a touch screen.
        if (test_bit(BTN_TOUCH, device->keyBitmask) || !haveGamepadButtons) {
            device->classes |= INPUT_DEVICE_CLASS_TOUCH | INPUT_DEVICE_CLASS_TOUCH_MT;
        }
    // Is this an old style single-touch driver?
    }
```

This should make android detect it as a stylus rather than touchscreen

**Comment by AndyCGYan** [comment]
> My recommendation is to try this:
> edit frameworks/native/services/inputflinger/EventHub.cpp and change

Unfortunately due to the coronavirus situation my build machine is currently unreachable...
It'd be wonderful if you could provide a test image (this device is ARM64 AB), but I'm totally cool if that's not feasible. Thanks for looking into this!

**Comment by phhusson** [comment]
Sure no problem:
https://treble.phh.me/system-test-pen.img

**Comment by AndyCGYan** [comment]
> Sure no problem:
> https://treble.phh.me/system-test-pen.img

[dumpsys_input-2.txt](https://github.com/phhusson/treble_experimentations/files/4251112/dumpsys_input-2.txt)
Note that this one is from the test build, while all previous logs and stuff are from stock Pie (I mean, I don't have output from unaltered AOSP).
Surprisingly I noticed that `/dev/input/event4` is working correctly under AOSP; `/dev/input/event5` still doesn't respond when I use the pen though.
Anything else I need to grab?

**Comment by phhusson** [comment]
k, it still says `DeviceType: touchScreen`

Please add log in frameworks/native/services/inputflinger/EventHub.cpp where I said to do the changes, and check if you go in the `test_bit(BTN_TOUCH` section for touchscreen?

There is also a second touchscreen section for legacy touchscreens, also check with log if you go there

And well add log in pen section, but I'm guessing you're not going there considering the logs

**Comment by AndyCGYan** [comment]
> Please add log in frameworks/native/services/inputflinger/EventHub.cpp

Is it correct to use `ALOGD`? If yes, none of the 3 sections are triggered.

**Comment by phhusson** [comment]
I believe it is correct, but just add a log at the beginning of the
function, it should always be called
perhaps you need to do `#define LOG_NDEBUG 0` at the beginning of the file
Also I usually ALOGE to be more confident logs arrive :D

**Comment by AndyCGYan** [comment]
> I believe it is correct, but just add a log at the beginning of the function, it should always be called perhaps you need to do `#define LOG_NDEBUG 0` at the beginning of the file Also I usually ALOGE to be more confident logs arrive :D

Weird, I did all of these but I still don't see any related logs, not even the one I added at the beginning of the func. I did see EventHub spew out some VERBOSE (`ALOGV`?) logs though, imma try that tomorrow.

**Comment by AndyCGYan** [comment]
Nope, I still don't get logs at all :(
All that EventHub spews out are:
```
V EventHub: wake() called
V EventHub: awoken after wake()
```

**Comment by AndyCGYan** [comment]
So uh, anything else I can do at this point?

**Comment by AndyCGYan** [comment]
One more ping - it'd be a pity to see the main attraction of the device go to waste.

**Comment by phhusson** [comment]
Right.
I'll try to make a fake /dev/input using uniput that reproduces those capabilities to try and and reproduce this issue

**Comment by phhusson** [comment]
In the /sys node for that device, you should have access to absmask keymask evmask, etc. could you send them here?

**Comment by AndyCGYan** [comment]
```
Infinix-X610:/sys/class/input/event5/device/capabilities # ls
abs ev ff key led msc rel snd sw
Infinix-X610:/sys/class/input/event5/device/capabilities # cat *
c61000000000003
b
0
1c03 0 6 4000000000000000 0 0
0
0
0
0
0
```

**Comment by phhusson** [comment]
After parsing this leads to:
```
ABS_X
ABS_Y
ABS_MT_TOUCH_MAJOR
ABS_MT_POSITION_X
ABS_MT_POSITION_Y
ABS_MT_PRESSURE
ABS_MT_DISTANCE

EV_SYN
EV_KEY
EV_ABS

KEY_F21
KEY_F23
KEY_F24

BTN_TOOL_PEN ( = BTN_DIGI)
BTN_TOOL_RUBBER
BTN_TOUCH
BTN_STYLUS
BTN_STYLUS2
```

It's weird it behaves as a touchscreen, but defines itself quite nicely has a pen.

Does stock rom have hover support? like you have the pen near the screen but not touching it and it shows a cursor

**Comment by AndyCGYan** [comment]
> Does stock rom have hover support? like you have the pen near the screen but not touching it and it shows a cursor

As far as I can remember, yes but kinda sloppy - the cursor has a huge delay following the pen tip's movements, unlike Sammy's S-Pen.

**Comment by AndyCGYan** [comment]
Any further discoveries?

**Comment by AndyCGYan** [comment]
Device sold, closing issue.
