### ISSUE TITLE
"All sound comes from main speaker" Samsung

### ISSUE THREAD

**Issue by Edgars-Cirulis** [phhusson/treble_experimentations#1126]
Brand: Samsung
Device: Galaxy A6 +

All sounds comes from main speaker aka Bluetooth audio / In-Call it forces to speaker. / Everything else works okay expect Audio.

[dumpsys.txt](https://github.com/phhusson/treble_experimentations/files/4238445/dumpsys.txt)

[logcat_02-22-2020_01-04-13.txt](https://github.com/phhusson/treble_experimentations/files/4238449/logcat_02-22-2020_01-04-13.txt)

**Comment by phhusson** [comment]
please attach your /vendor/etc/audio_policy_configuration.xml

**Comment by thorgod949** [comment]
I'm running an Galaxy S9 960U. Here is the file you asked for. I'm having the same issue.

https://pastebin.com/9dd3PGaX

**Comment by Fzndox** [comment]
This issue persists in v216.
