### ISSUE TITLE
Audio bug in Calls  J4 Core

### ISSUE THREAD

**Issue by kapmino269-MG** [phhusson/treble_experimentations#1127]
Hello ,
 Aosp oreo , pie , Q was tested . All is stable .
# Except 2 Bugs :
1 - Dual sim doesn't work (fixed)  ..... [HERE](https://github.com/phhusson/treble_experimentations/issues/1066#issuecomment-588475626)
2 - Audio bug .....  in Call .(Calls is working but unfortunately no audio will work from earpiece  , and audio will be  moved to speaker and won't  work also)
# Informations and Logs : 
 - [Bugreport.zip](https://github.com/phhusson/treble_experimentations/files/4227677/Bugreport.zip)
logcat , dumpsys , dmesg .
- phone : SM-J410G
- VENDOR : oreo (vndk 27)
- system : arm a only 
# Pictures  : 
![IMG_20200223_095824_815](https://user-images.githubusercontent.com/48631763/75106276-4f26ac00-5623-11ea-80a4-571fc5e275e9.jpg)
![IMG_20200223_095828_696](https://user-images.githubusercontent.com/48631763/75106277-5057d900-5623-11ea-98de-d405d59da85d.jpg)

**Comment by kapmino269-MG** [comment]
Lshal result : 
[lshal.txt](https://github.com/phhusson/treble_experimentations/files/4312539/lshal.txt)

**Comment by kapmino269-MG** [comment]
@phhusson
At first , Hope to be well (as corona virus ) .
Excuse me , Any news about this issue?? 
Is there missing files which u need ?

Thanks .

**Comment by phhusson** [comment]
Update after some discussion on Telegram:

Those devices are using samsung radio HAL versioned 1.1, at the moment I only have 1.2
On Qualcomm devices, there is no in-call audio because I fixed it a long time ago, using `radio.am` HAL
It looks like samsung has the same thing with `oemAmInd`. So the goal is to fix ISecRadioIndication so that the indication arrives to Android framework.

**Comment by AnonnymousJC** [comment]
@phhusson any news about the bug fix?

**Comment by kapmino269-MG** [comment]
@phhusson  
1- I found that j4 plus Oreo vendor ril & radio libs  is the same as j4 core Oreo vendor ril & radio libs .
2- In j4 plus with Oreo vendor , this issue isn't there .

From point 1 and 2 , it sounds  that it is audio issue after trying I found fix by editing audio XML file in vendor and issue was fixed .


Here is the zip :  https://androidfilehost.com/?fid=4349826312261823140



Thanks for your help .

**Comment by phhusson** [comment]
Could you show the actual differences between the xml files

**Comment by kapmino269-MG** [comment]
Done
