### ISSUE TITLE
[AOSP Q] [Teclast m30] [MT6797x] booting does not finish [logcat]

### ISSUE THREAD

**Issue by asuvoro** [phhusson/treble_experimentations#1134]
Tried some ways to flash ROM but no success (with some scripts from 4pda.ru).
Here is log with clear install after reflashing factory rom ([link to dl rom](Tried some ways to flash ROM)).
Log attached with ext .zip, but it is 7z-format.

**Comment by phhusson** [comment]
Log isn't attached :-)

**Comment by asuvoro** [comment]
Ooops. Sorry... :-) 
[catlog_teclast_m30_q.zip](https://github.com/phhusson/treble_experimentations/files/4243713/catlog_teclast_m30_q.zip)

**Comment by asuvoro** [comment]
[factory wirmware dl link](https://mega.nz/#!1FY1BA4Q!aLM899AghOQHnnDdR5f_6L0IqADZxUieKJqqYwhi2rI)

**Comment by phhusson** [comment]
Okay so the error is
```
02-24 07:50:00.162   629   629 I ccci_mdinit(3): wait_for_property: no property of :init.svc.emdlogger3, loop:0
02-24 07:50:00.167 24244 24244 E vndksupport: Could not load /vendor/lib/egl/libGLES_mali.so from sphal namespace: dlopen failed: library "libstdc++.so" not found.
02-24 07:50:00.167 24244 24244 E libEGL  : load_driver(/vendor/lib/egl/libGLES_mali.so): unknown
02-24 07:50:00.167 24244 24244 F libEGL  : couldn't find an OpenGL ES implementation, make sure you set ro.hardware.egl or ro.board.platform
02-24 07:50:00.167 24244 24244 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 24244 (main), pid 24244 (main)
```

That rings a bell, I thought it was already fixed, but well
Try copying /system/lib/vndk-26/libstdc++.so to /system/lib/vndk-sp-26/libstdc++.so

While the system is booting do:
```
adb root
adb remount
adb shell cp /system/lib/vndk-26/libstdc++.so /system/lib/vndk-sp-26/libstdc++.so 
```

**Comment by asuvoro** [comment]
While booting system, adb not accepting commands:
> D:\adb_spft\teclast>adb root
> adbd cannot run as root in production builds
> 
> D:\adb_spft\teclast>adb remount
> Not running as root. Try "adb root" first.
> 
> D:\adb_spft\teclast>adb shell cp /system/lib/vndk-26/libstdc++.so /system/lib/vndk-sp-26/libstdc++.so
> cp: /system/lib/vndk-sp-26/libstdc++.so: Read-only file system

But I've booted into TWRP and copied file.
New log attached
[logcat_teclast.zip](https://github.com/phhusson/treble_experimentations/files/4244671/logcat_teclast.zip)

**Comment by phhusson** [comment]
Hum that's weird. You don't have magisk installed, do you? This could
prevent adb root from working, and would explain the
`java.lang.RuntimeException: Socket unset or invalid:
ANDROID_SOCKET_usap_pool_secondary` error

**Comment by asuvoro** [comment]
....before that I've reinstalled AOSPv123. :) 

Ok. I've made full-factory restore of firmware.
Flashed only aosp-system.211, and done factory-reset it via original recovery.

original vendor:
[00_orig.zip](https://github.com/phhusson/treble_experimentations/files/4244918/00_orig.zip)

some newer vendor image:
[00.zip](https://github.com/phhusson/treble_experimentations/files/4244860/00.zip)

**Comment by phhusson** [comment]
You still need to do
```
adb root
adb remount
adb shell cp /system/lib/vndk-26/libstdc++.so /system/lib/vndk-sp-26/libstdc++.so 
```

though the question is whether adb root no works now that you have flashed stock unmodified without magisk boot.img

**Comment by asuvoro** [comment]
Yes, of course. It was already done. And then logs collected.
Now folder listing is:
```
D:\adb_spft\teclast>adb shell ls /system/lib/vndk-sp-26/
android.hardware.graphics.allocator@2.0.so
android.hardware.graphics.common@1.0.so
android.hardware.graphics.mapper@2.0.so
android.hardware.renderscript@1.0.so
android.hidl.base@1.0.so
android.hidl.memory@1.0.so
hw
libRSCpuRef.so
libRSDriver.so
libRS_internal.so
libbacktrace.so
libbase.so
libbcinfo.so
libblas.so
libc++.so
libcompiler_rt.so
libcutils.so
libft2.so
libhardware.so
libhidlbase.so
libhidlmemory.so
libhidltransport.so
libhwbinder.so
libion.so
liblog.so
liblzma.so
libpng.so
**libstdc++.so**
libunwind.so
libutils.so
libz.so
```

**Comment by phhusson** [comment]
Ok, then edit /system/etc/ld.config.26.txt and change
```
namespace.vndk.link.default.shared_libs += libclang_rt.asan-arm-android.so:libclang_rt.hwasan-arm-android.so:libclang_rt.ubsan_standalone-arm-android.so:libclang_rt.tsan-arm-android.so
```

to

```
namespace.vndk.link.default.shared_libs += libclang_rt.asan-arm-android.so:libclang_rt.hwasan-arm-android.so:libclang_rt.ubsan_standalone-arm-android.so:libclang_rt.tsan-arm-android.so:libstdc++.so
```

you can use adb pull/adb push to retrieve and push-back the file

**Comment by asuvoro** [comment]
error still exists 

`02-22 18:14:16.883  3676  3676 I Zygote  : ...preloaded 64 resources in 59ms.                                                                         02-22 18:14:16.889  3676  3676 I Zygote  : ...preloaded 41 resources in 7ms.                                                                          02-22 18:14:16.890  3676  3676 D ZygoteInitTiming_lazy: PreloadResources took to complete: 271ms                                                      02-22 18:14:16.903  3830  3830 I WifiService: WifiService starting up with Wi-Fi disabled                                                             02-22 18:14:16.920  3830  4043 I chatty  : uid=1000 system_server expire 1 line                                                                       02-22 18:14:16.923  3681  3681 E wificond: No interface is found                                                                                      02-22 18:14:16.926  3676  3676 E vndksupport: Could not load /vendor/lib/egl/libGLES_mali.so from sphal namespace: dlopen failed: library "libstdc++.so" not found.                                                                                                                                         02-22 18:14:16.926  3676  3676 E libEGL  : load_driver(/vendor/lib/egl/libGLES_mali.so): unknown                                                      02-22 18:14:16.926  3676  3676 F libEGL  : couldn't find an OpenGL ES implementation, make sure you set ro.hardware.egl or ro.board.platform          02-22 18:14:16.927  3676  3676 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 3676 (main), pid 3676 (main)                           `

**Comment by asuvoro** [comment]
[01.zip](https://github.com/phhusson/treble_experimentations/files/4245394/01.zip)

**Comment by asuvoro** [comment]
Hmmm.
In folder system/etc I can see ld.config.26.txt which you recommend to change.
But there is no file vndksp.libraries.26.txt 
Is it correct?

**Comment by asuvoro** [comment]
Also applied recommendation to folder
/system/lib64/vndk-sp-26/

No difference

**Comment by SDSkyKlouD** [comment]
Hello,  
I have same model (Teclast M30) and tried to boot Android 10 GSIs.  
Since the device can boot Android 9 GSIs without any preceding processes (just flash system img and it boots!), I thought 10 GSIs will also fine but it's wrong...  
  
Like @phhusson recommended and @asuvoro tried, I copied `/system/lib/vndk-26/libstdc++.so` to `/system/lib/vndk-sp-26/libstdc++.so` but there was no luck.  
After I search for the error `Could not load /vendor/lib/egl/libGLES_mali.so from sphal namespace: dlopen failed: library "libstdc++.so" not found.`, I found https://github.com/phhusson/treble_experimentations/issues/1017#issuecomment-567000385 !!  
  
As @yura73 said, I copied `/system/lib/vndk-26/libstdc++.so` to `/vendor/lib/libstdc++.so` and eventually the boot animation plays boot finish animation!! Now the device successfully boot an Android 10 GSI image ✌✌  
Hope this helps! 😉  
  
※ If the device still doesn't boot successfully, you can flash [ZygoteFix v2](https://www.cyanogenmods.org/downloads/zygotefix-v2-for-android-10/) **and then** [Permissiver v5](https://www.cyanogenmods.org/downloads/permissiver-v5-for-android-10-gsi/) in TWRP.

**Comment by asuvoro** [comment]
@SDSkyKlouD, 
wow! thank you!

I remember, i've tried it so too. But at 1st time it did'nt work for me. Strange...
Now I repeated this. And booting finished very quickly. No patches were applied.

**Comment by asuvoro** [comment]
It seems like v.213 working for me

**Comment by asuvoro** [comment]
closing it. info added at device's page

**Comment by SubSonix** [comment]
@SDSkyKlouD Could you tell me how you replaced the file please? I believe I'm having the same issue (I'm having a boot loop when trying 10 GSI)

**Comment by asuvoro** [comment]
@SubSonix File replaced via adb. I've booted into recovery, mounted partition and then pushed file into right place.
You have to upload adb_key from you PC before.

**Comment by SubSonix** [comment]
What is adb_key please?

And which files? I've done the above with the same issue. Mine seems to be stuck on something unrelated https://github.com/phhusson/treble_experimentations/issues/1217#issuecomment-676844162
