### ISSUE TITLE
AOSP9 - Samsung Galaxy Tab S4 (gts4lwifi) - Magnetic case enable/disable screen

### ISSUE THREAD

**Issue by Avrution** [phhusson/treble_experimentations#1136]
Results of the adb shell getevent

add device 1: /dev/input/event11
  name:     "msm8998-tavil-snd-card Button Jack"
add device 2: /dev/input/event10
  name:     "msm8998-tavil-snd-card Headset Jack"
could not get driver version for /dev/input/mice, Not a typewriter
add device 3: /dev/input/event5
  name:     "sec_e-pen-pad"
add device 4: /dev/input/event0
  name:     "qpnp_pon"
could not get driver version for /dev/input/mouse2, Not a typewriter
add device 5: /dev/input/event3
  name:     "sec_touchpad"
add device 6: /dev/input/event1
  name:     "meta_event"
add device 7: /dev/input/event9
  name:     "certify_hall"
add device 8: /dev/input/event8
  name:     "hall"
could not get driver version for /dev/input/mouse3, Not a typewriter
add device 9: /dev/input/event6
  name:     "sec_virtual-e-pen"
could not get driver version for /dev/input/mouse1, Not a typewriter
add device 10: /dev/input/event7
  name:     "gpio_keys"
add device 11: /dev/input/event4
  name:     "sec_e-pen"
could not get driver version for /dev/input/mouse4, Not a typewriter
add device 12: /dev/input/event2
  name:     "sec_touchscreen"
could not get driver version for /dev/input/mouse0, Not a typewriter
/dev/input/event8: 0005 0015 00000000
/dev/input/event8: 0000 0000 00000000
/dev/input/event2: 0003 0039 00000051
/dev/input/event2: 0001 014a 00000001
/dev/input/event2: 0001 0145 00000001
/dev/input/event2: 0003 0035 000004fe
/dev/input/event2: 0003 0036 00000543
/dev/input/event2: 0003 0030 00000008
/dev/input/event2: 0003 0031 00000008
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0030 00000007
/dev/input/event2: 0003 0031 00000007
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0030 00000008
/dev/input/event2: 0003 0031 00000008
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0030 00000009
/dev/input/event2: 0003 0031 00000009
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000502
/dev/input/event2: 0003 0036 00000540
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000504
/dev/input/event2: 0003 0036 0000053e
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000506
/dev/input/event2: 0003 0036 0000053d
/dev/input/event2: 0003 0030 0000000b
/dev/input/event2: 0003 0031 00000008
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 0000050a
/dev/input/event2: 0003 0036 0000053e
/dev/input/event2: 0003 0030 0000000a
/dev/input/event2: 0003 0031 00000007
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 0000050b
/dev/input/event2: 0003 0030 0000000b
/dev/input/event2: 0003 0031 00000008
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 0000050c
/dev/input/event2: 0003 0036 0000053d
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 0000050d
/dev/input/event2: 0003 0036 0000053c
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 0000050e
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 0000050f
/dev/input/event2: 0003 0036 0000053b
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000510
/dev/input/event2: 0003 0036 0000053a
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0030 0000000c
/dev/input/event2: 0003 0031 00000009
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000511
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0030 0000000a
/dev/input/event2: 0003 0031 00000007
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000512
/dev/input/event2: 0003 0036 00000539
/dev/input/event2: 0003 0030 0000000c
/dev/input/event2: 0003 0031 00000009
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000513
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0036 00000538
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0036 00000536
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000514
/dev/input/event2: 0003 0036 00000537
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000515
/dev/input/event2: 0003 0030 0000000b
/dev/input/event2: 0003 0031 00000008
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0030 0000000c
/dev/input/event2: 0003 0031 00000009
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000516
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000515
/dev/input/event2: 0003 0036 00000536
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0036 00000535
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000517
/dev/input/event2: 0003 0036 00000533
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 0000051e
/dev/input/event2: 0003 0036 0000052c
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000528
/dev/input/event2: 0003 0036 00000524
/dev/input/event2: 0003 0030 0000000b
/dev/input/event2: 0003 0031 00000008
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 0000052f
/dev/input/event2: 0003 0036 0000051e
/dev/input/event2: 0003 0031 0000000b
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000537
/dev/input/event2: 0003 0036 00000518
/dev/input/event2: 0003 0030 0000000d
/dev/input/event2: 0003 0031 0000000d
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 0000053f
/dev/input/event2: 0003 0036 00000512
/dev/input/event2: 0003 0030 0000000c
/dev/input/event2: 0003 0031 00000009
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000545
/dev/input/event2: 0003 0036 0000050e
/dev/input/event2: 0003 0030 0000000b
/dev/input/event2: 0003 0031 00000008
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000549
/dev/input/event2: 0003 0036 00000509
/dev/input/event2: 0003 0030 0000000a
/dev/input/event2: 0003 0031 00000007
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 0000054d
/dev/input/event2: 0003 0036 00000503
/dev/input/event2: 0003 0030 0000000b
/dev/input/event2: 0003 0031 00000008
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 0000054f
/dev/input/event2: 0003 0036 000004ff
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000550
/dev/input/event2: 0003 0036 000004fe
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000551
/dev/input/event2: 0003 0036 000004fd
/dev/input/event2: 0003 0030 0000000c
/dev/input/event2: 0003 0031 00000009
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0030 0000000b
/dev/input/event2: 0003 0031 00000008
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000552
/dev/input/event2: 0003 0036 000004fe
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000553
/dev/input/event2: 0003 0036 000004fd
/dev/input/event2: 0003 0030 00000009
/dev/input/event2: 0003 0031 00000009
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 0000055a
/dev/input/event2: 0003 0036 000004fc
/dev/input/event2: 0003 0030 00000008
/dev/input/event2: 0003 0031 00000008
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000564
/dev/input/event2: 0003 0036 000004f5
/dev/input/event2: 0003 0030 00000004
/dev/input/event2: 0003 0031 00000004
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0039 ffffffff
/dev/input/event2: 0001 014a 00000000
/dev/input/event2: 0001 0145 00000000
/dev/input/event2: 0000 0000 00000000
/dev/input/event8: 0005 0015 00000001
/dev/input/event8: 0000 0000 00000000
/dev/input/event8: 0005 0015 00000000
/dev/input/event8: 0000 0000 00000000
/dev/input/event2: 0003 0039 00000052
/dev/input/event2: 0001 014a 00000001
/dev/input/event2: 0001 0145 00000001
/dev/input/event2: 0003 0035 000004f9
/dev/input/event2: 0003 0036 000003e5
/dev/input/event2: 0003 0030 00000009
/dev/input/event2: 0003 0031 00000006
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0030 00000007
/dev/input/event2: 0003 0031 00000004
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0031 00000007
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0031 00000004
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 000004fe
/dev/input/event2: 0003 0036 000003e6
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000501
/dev/input/event2: 0003 0036 000003e7
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000503
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0031 00000007
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000504
/dev/input/event2: 0003 0036 000003e6
/dev/input/event2: 0003 0031 00000004
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0036 000003e5
/dev/input/event2: 0003 0031 00000007
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000505
/dev/input/event2: 0003 0036 000003e4
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0036 000003e3
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000506
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000507
/dev/input/event2: 0003 0036 000003e4
/dev/input/event2: 0003 0030 00000009
/dev/input/event2: 0003 0031 00000006
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000509
/dev/input/event2: 0003 0036 000003e5
/dev/input/event2: 0003 0030 00000007
/dev/input/event2: 0003 0031 00000007
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 0000050a
/dev/input/event2: 0003 0036 000003e4
/dev/input/event2: 0003 0030 00000009
/dev/input/event2: 0003 0031 00000006
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 0000050c
/dev/input/event2: 0003 0036 000003e3
/dev/input/event2: 0003 0031 00000009
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 0000050f
/dev/input/event2: 0003 0031 00000006
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0030 0000000a
/dev/input/event2: 0003 0031 00000007
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000510
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000511
/dev/input/event2: 0003 0030 0000000b
/dev/input/event2: 0003 0031 00000008
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000512
/dev/input/event2: 0003 0036 000003e2
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0036 000003e1
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0036 000003e0
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0031 0000000b
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0031 00000008
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0030 0000000a
/dev/input/event2: 0003 0031 0000000a
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0030 0000000b
/dev/input/event2: 0003 0031 0000000b
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0031 00000008
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0030 0000000a
/dev/input/event2: 0003 0031 00000007
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000514
/dev/input/event2: 0003 0036 000003e3
/dev/input/event2: 0003 0030 00000007
/dev/input/event2: 0003 0031 00000004
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 0000051c
/dev/input/event2: 0003 0036 000003ea
/dev/input/event2: 0003 0030 00000006
/dev/input/event2: 0003 0031 00000006
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 00000527
/dev/input/event2: 0003 0036 000003f4
/dev/input/event2: 0003 0030 00000005
/dev/input/event2: 0003 0031 00000005
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0035 0000052f
/dev/input/event2: 0003 0036 000003f8
/dev/input/event2: 0003 0030 00000004
/dev/input/event2: 0003 0031 00000003
/dev/input/event2: 0000 0000 00000000
/dev/input/event2: 0003 0039 ffffffff
/dev/input/event2: 0001 014a 00000000
/dev/input/event2: 0001 0145 00000000
/dev/input/event2: 0000 0000 00000000
/dev/input/event8: 0005 0015 00000001
/dev/input/event8: 0000 0000 00000000

It will continue forever with the case closed.  event2 is closed and event8 is opened.

**Comment by phhusson** [comment]
Ok, so there is
```
/dev/input/event8: 0005 0015 00000000
/dev/input/event8: 0000 0000 00000000
```

which is
EV_SW   
SW_FLIP                 0x15    /* set = flip cover */

SW_FLIP is Samsung-specific and not in mainline kernel

Should be pretty easy to plug-back in frameworks, I'll give a look.

**Comment by Avrution** [comment]
Thank you.  Samsung specific seems to be the name of the game with most things not working correctly.

**Comment by phhusson** [comment]
To be fair, standard/usual way is SW_LID, which was historically used in Android for slider keyboards, which doesn't turn off screen.

SW_LID now refers to laptops being closed/open, which would turn off screen. So it's closer to flip cover.
So yeah semantics isn't totally clear.
I wouldn't be suprised if Samsung uses SW_LID for keyboard covers detection

**Comment by phhusson** [comment]
Your device is arm64 aonly correct?

i'll make you a test image

**Comment by Avrution** [comment]
Correct

**Comment by phhusson** [comment]
https://treble.phh.me/sys-sam-lid.img

**Comment by Avrution** [comment]
Thank you.  Is this still based on 9?  I'm stuck on the Samsung logo in the same way the 10 builds do for this device.

**Comment by phhusson** [comment]
Ah, I missed that part.
No that's an android 10 image. Could you link me to the boot issue?

**Comment by Avrution** [comment]
I haven't opened one for that yet, been spending all of my time with different 9 roms trying to find something that works correctly.  Seems most have abandoned 9 for 10 already and stopped incorporating your fixes.

Just down to the lid on/off and getting the rest of the brightness back.

**Comment by Avrution** [comment]
The best I can get is a kernel log, since I can't even get to the logo or adb to connect.

[kernellog.zip](https://github.com/phhusson/treble_experimentations/files/4246140/kernellog.zip)
