### ISSUE TITLE
[AOSP 10 phh][Realme U1]Audio from main speaker dosent work

### ISSUE THREAD

**Issue by MeNoobie** [phhusson/treble_experimentations#1139]
Audio from main speaker dosent work but all other speakers(ex earpiece) work properly

dump url: https://github.com/AndroidDumps/realme_rmx1831_dump

logcat wile speaker switching
[Stock logcat.txt](https://github.com/phhusson/treble_experimentations/files/4256188/Stock.logcat.txt)

[v212AOSP10NoAudio.txt](https://github.com/phhusson/treble_experimentations/files/4273756/v212AOSP10NoAudio.txt)

Devise name : realme u1

Mt 6771

Gsi version v123

OTHER(wer provided on telegram)
$ getprop |grep -e audio -e smartpa
[init.svc.audioserver]: [running]
[init.svc.vendor.audio-hal-4-0]: [running]
[ro.vendor.mtk_audio_alac_support]: [1]
[ro.vendor.mtk_audio_ape_support]: [1]
[ro.vendor.mtk_audio_tuning_tool_ver]: [V2.2]
[ro.vendor.mtk_hifiaudio_support]: [1]
[vendor.audiohal.modem_1.epof]: [0]
[vendor.audiohal.recovery.mic_mute_on]: [0]
[vendor.audiohal.speech.shm_init]: [1]

OLD logcat 

[treble v123 call switching.txt](https://github.com/phhusson/treble_experimentations/files/4256196/treble.v123.call.switching.txt)

logcat_02-25-2020_21-13-00.txt](https://github.com/phhusson/treble_experimentations/files/4256209/logcat_02-25-2020_21-13-00.txt)

[logcat_02-25-2020_21-17-22.txt](https://github.com/phhusson/treble_experimentations/files/4256210/logcat_02-25-2020_21-17-22.txt)

**Comment by AJdevloper** [comment]
Somebody please help...
I have same issue

**Comment by phhusson** [comment]
Working/stock-side:
```
speakerOn(), sampleRate = 32000, device = 2
speakerOn(), mono Profile set VOICE_32000
+dspOnBoardSpeakerOn(), SampleRate = 32000, MD_type = 0, Audio_i2s0_hd_Switch = 1
Enable speaker echo reference path for MD
speakerOn(), sampleRate = 32000, device = 2
speakerOn(), mono Profile set VOICE_32000
updateFeatureMask() featureType:4, flagon:0
```

Not working, GSI-side:
```
speakerOn(), sampleRate = 32000, device = 2
Error: VOICE_32000 invalid value, ret = -22
+dspOnBoardSpeakerOn(), SampleRate = 32000, MD_type = 0, Audio_i2s0_hd_Switch = 1
Enable speaker echo reference path for MD
startOutputDevice_l(), pcm_is_ready(0xf0884dc0) == false due to cannot set hw params: Invalid argument, close pcm.
AUD_ASSERT(mSpkPcmOut != __null) fail: "vendor/mediatek/proprietary/hardware/audio/common/V3/aud_drv/AudioALSAHardwareResourceManager.cpp", 339L
shell: cant create socket with aed: Connection refused
speakerOn(), sampleRate = 32000, device = 2
```

**Comment by phhusson** [comment]
Can you give a full `getprop` on stock rom?

**Comment by MeNoobie** [comment]
[FullGetpropGSIV213.txt](https://github.com/phhusson/treble_experimentations/files/4293622/FullGetpropGSIV213.txt)
[StockGetprop.txt](https://github.com/phhusson/treble_experimentations/files/4293623/StockGetprop.txt)

**Comment by MeNoobie** [comment]
this issue has been fixed by  adding
 echo 1 >  /proc/tfa98xx/oppo_tfa98xx_fw_update  at the end of system/bin/rw-system.sh to fix  the main speaker 

thx to @phhusson
