### ISSUE TITLE
[AOSP 10] insane battery drain on Huawei MediaPad M5 WiFi only tablet

### ISSUE THREAD

**Issue by fourofspades** [phhusson/treble_experimentations#1141]
Looking at logcat, it appears to be related telephony, android phone app and all the related services crashing and constantly respawning. Seen on b210 and b212.

This should not be occurring on a device without telephony ril.

It does not occur on the same device when running AOSP9 GSI b123

**Comment by fourofspades** [comment]
![Screenshot-20200226-081148](https://user-images.githubusercontent.com/61576868/75519247-b3b68200-59fa-11ea-8ef2-a17d74bef4a6.png)

**Comment by fourofspades** [comment]
Battery life difference between 9 GSI and 10GSI, from full charge, screen off to 0%

AOSP GSI 10: 4 hours
AOSP GSI 9: 8 days

Same device, same conditions. (WiFi enabled, device idle, clean flash, no other apps)

**Comment by phhusson** [comment]
Ah that's the usual issue that Android doesn't know what a tablet is anymore.
I'll try reproducing the issue.

**Comment by phhusson** [comment]
Well, looks like this is enough:

`rm -Rf /system/priv-app/TeleService`

**Comment by fourofspades** [comment]
Will flash and try.  Is there a fix in the GSI incoming, or will these need be done every time?

Will post feedback once I have flashed it and tried it out.

Thanks for looking into this.

**Comment by fourofspades** [comment]
OK, fell at the first hurdle.  Got it flashed, but system is readonly.   None of the online solutions I found to mount system partition as read/write work.    I don't use TWRP or any custom recovery (they have a habit of bricking this device), so I run stock everything, aside unlocked bootloader, I just wipe everything and flash the system GSI.

**Comment by fourofspades** [comment]
Running sane AOSP 9, but keek to switch to 10, as this was the only show stopper for my device. It's quite time consuming switching back and forth, so before I try this (and potentially fail and have to switch back to 9), asking for advice;. Will this make my system RW in 10 to allow me to delete suggested directory;

 adb root ; adb remount

Happy to try this fix out, but keen not to waste half a day trying it because of a misunderstanding on my part as to wahtt that command does.

**Comment by fourofspades** [comment]
This appears to have fixed it.

**Comment by fourofspades** [comment]
@phhusson  Is this something that can be fixed in the ROM?  If not, if I created a pull request that added an option in the treble app to do the above steps, would be be OK to merge it?

**Comment by phhusson** [comment]
I believe it can be fixed, but I'm afraid there might be a lot of bugs in
series to pull, so yeah send the PR I can merge that

Le ven. 8 mai 2020 à 14:57, fourofspades <notifications@github.com> a
écrit :
