### ISSUE TITLE
[Gapps] Download pending issue

### ISSUE THREAD

**Issue by cawilliamson** [phhusson/treble_experimentations#115]
I was looking in to the Gapps "download pending" issue and found a workaround:

1.) Install *-nosu* GSI image as normal (with -w)
2.) Boot TWRP
3.) Install opengapps nano for 8.1 (arm64)
4.) Boot

You will now have a completely working gapps install without any of this "download pending" junk.

With this in mind - I may be missing something here but couldn't we just add the nano (or pico) opengapps to the GSI and close off this "pending download" nonsense once and for all? 👍

I'll look in to this and submit a PR.

**Comment by phhusson** [comment]
This is already opengapps nano.
It's just that I'm using AOSP integration, instead of the install zip.

This bug is tracked at https://github.com/opengapps/aosp_build/issues/184#issuecomment-402693331
