### ISSUE TITLE
AOSP10 - Samsung Galaxy Tab S4 (gts4lwifi) - Doesn't boot past Samsung logo

### ISSUE THREAD

**Issue by Avrution** [phhusson/treble_experimentations#1163]
Wanted to move this out of the other thread for future reference.

9 versions boot fine, but 10 gets stuck on the Samsung logo and goes no further.  

Unable to connect via ADB during this process, so only able to pull a kernel log.

[kernellog.zip](https://github.com/phhusson/treble_experimentations/files/4299738/kernellog.zip)

**Comment by satmandu** [comment]
How do you pull a kernel log without adb?

**Comment by Avrution** [comment]
From TWRP

**Comment by Avrution** [comment]
If there is another way to properly pull a bootlog then I'm more than happy to try.

**Comment by gtr33m** [comment]
Did you make any progress on this? I have the sm-t835 with the same issue.

**Comment by Avrution** [comment]
Don't think there will be anymore progress until we get Android 10 next month

**Comment by Avrution** [comment]
Treble images are now AB instead of A only - now booting.  Closing.
