### ISSUE TITLE
Audio not work on UMIDIGI X

### ISSUE THREAD

**Issue by chicato83** [phhusson/treble_experimentations#1174]
UMIDIGI X Helio P60.

### Problem with the audio in the system-quack-arm64-ab-gapps.img.xz [v213}
The audio in speakers does not work, when I use any app for music like AIMP2 , Youtube or spotify.
The speaker does not work in call also.

### GSI Logcat
[logcatgsi.txt](https://github.com/phhusson/treble_experimentations/files/4315431/logcatgsi.txt)

### Stock ROM Logcat
[logcatstock.txt](https://github.com/phhusson/treble_experimentations/files/4315625/logcatstock.txt)

**Comment by phhusson** [comment]
Stock:
```
03-10 21:45:29.642   703   976 D AudioSmartPaController: speakerOn(), sampleRate = 32000, device = 2
03-10 21:45:29.642   703   976 D AudioSmartPaController: +dspOnBoardSpeakerOn(), SampleRate = 32000, MD_type = 0, Audio_i2s0_hd_Switch = 1
03-10 21:45:29.642   703   976 D AudioSmartPaController: Enable speaker echo reference path for MD
03-10 21:45:29.642   703   976 D AudioSmartPaController: +setSmartPaRuntime(), device = 0, mode = 2 
03-10 21:45:29.642   703   976 D         : fs16xx: Ex_Fs16xx_SpeakerOn:174: Ex_Fs16xx_SpeakerOn enter. sample rate=32000 device = 0
03-10 21:45:29.642   703   976 D         : fs16xx: Ex_Fs16xx_SetSamplerate:119: Ex_Fs16xx_SetSamplerate enter.
03-10 21:45:29.646   703   976 D         : fs16xx: Ex_Fs16xx_SetSamplerate:130: Ex_Fs16xx_SetSamplerate exit.
03-10 21:45:29.646   703   976 E         : fs16xx: fs16xx_powerdown powerdown = 0
03-10 21:45:29.647   703   976 E         : fs16xx: fs16xx_set_preset set preset 1.
03-10 21:45:29.650   703   976 D         : fs16xx: fs16xx_set_preset:387: fs16xx_set_preset exit err=0.
03-10 21:45:29.664   703   976 D         : fs16xx: fs16xx_set_tempr_protection:693: fs16xx_set_tempr_protection enter. enable=1
03-10 21:45:29.664   703   976 D         : fs16xx: fs16xx_set_tempr_protection:713: fs16xx_set_tempr_protection exit.
03-10 21:45:29.664   703   976 D         : fs16xx: Ex_Fs16xx_SpeakerOn:227: Ex_Fs16xx_SpeakerOn exit.
```

GSI:
```
03-10 19:45:38.076   639   774 D AudioALSAHardwareResourceManager: +startOutputDevice(), new_devices = 0x2, mOutputDevices = 0x0, mStartOutputDevicesCount = 0 SampleRate = 32000
03-10 19:45:38.076   639   774 D AudioALSADeviceParser: compare pcm success = 31, stringpair = Speaker_PLayback
03-10 19:45:38.077   639   774 D AudioSmartPaController: speakerOn(), sampleRate = 32000, device = 2
03-10 19:45:38.077   639   774 D AudioSmartPaController: +dspOnBoardSpeakerOn(), SampleRate = 32000, MD_type = 0, Audio_i2s0_hd_Switch = 1
03-10 19:45:38.077   639   774 D AudioSmartPaController: Enable speaker echo reference path for MD
03-10 19:45:38.077   639   774 D AudioSmartPaController: +setSmartPaRuntime(), device = 0, mode = 2
03-10 19:45:38.077   639   774 D         : fs16xx: Ex_Fs16xx_SpeakerOn:174: Ex_Fs16xx_SpeakerOn enter. sample rate=32000 device = 0 
03-10 19:45:38.077   639   774 E         : fs16xx: Ex_Fs16xx_SpeakerOn failed, device not initialized.
```

Please give a link to your stock rom

**Comment by Hamachi-geek** [comment]
Here is StockROM:
https://community.umidigi.com/forum.php?mod=viewthread&tid=19161&extra=page%3D1

**Comment by chicato83** [comment]
I installed the AOSP 9.0 v123 and I have the same issue with the audio. But I see something when I play a video or audio y can heard it in the heard speaker.

I think it is a problem with the vendor Im no sure.

**Comment by chicato83** [comment]
I installed the v215. 
system-quack-arm64-ab-gapps.img.xz

And I still not have sound in the internal speakers. Any solution for this?

**Comment by phhusson** [comment]
I actually think Umidigi fixed this issue.
Could you flash their V1.0_20200306.V3.10 and try again?

**Comment by chicato83** [comment]
Every time I flash the gsi I use that version to go back to stock rom V1.0_20200306.V3.10.
Yesterday when I installed v215 to test the fingerprint code it was in that version.

V1.0_20200306.V3.10.

**Comment by chicato83** [comment]
Thanks to @phhusson for the solution of the issue.

Fix.
Copy your stock rom's system/etc/smartpa_params/fs16xx_01s_mono.preset to gsi's system/etc/smartpa_params/fs16xx_01s_mono.preset

LINK for download the file. 
[GDRIVE](https://drive.google.com/open?id=1Pah8LW-PGH5qkqNMXmY5C7cBg42ERlyG)

Command to follow:

```
adb root
adb shell mount -o remount,rw /
adb shell mkdir /system/etc/smartpa_params
adb push fs16xx_01s_mono.preset /system/etc/smartpa_params/
adb reboot
```

That is all.

**Comment by Hamachi-geek** [comment]
I tried to fix a speaker with the way @chicato83 told.
In the end,speaker is fixed!
Thank you so much.
But fingerprint scaner is not working.
I'll find the way to use fingerprint scaner .

**Comment by Tr00zin45** [comment]
works on AOSP 11.0 v300.j ?

**Comment by ponces** [comment]
[Fixed](https://github.com/phhusson/device_phh_treble/commit/95cdb160d546b623de0f9ae29805a52dcc51706d)  ;)
