### ISSUE TITLE
Cubot QUEST does not boot AOSP 10 GSI

### ISSUE THREAD

**Issue by bahamut657** [phhusson/treble_experimentations#1179]
AOSP 9 image boots succesfully(last release). But after flashing the AOSP 10 the device remain on Andorid text loading

**Comment by Fsadju** [comment]
did you install magisk-pph.zip trough twrp ?
--------------------------------
also am having  problem using latest [AOSP 10] [V213] on cubot x18 plus device , internal storage shows 8GB storage in total or 2.90GB free space and 6GB takes system space , but it should have about 60 GB internal storage

**Comment by bahamut657** [comment]
No i've not installed MAGISK at all. Is it required?

**Comment by phhusson** [comment]
No, it's just that if you were using magisk, then in that case, you need a
correct magisk.
But since you're not using magisk, don't flash any magisk.

**Comment by bahamut657** [comment]
@phhusson  Can you assist me to debug the problem? I'm a developer too

**Comment by MMan1982** [comment]
,@phhusson is there any chance to fix cubot quest boot problem?

**Comment by MMan1982** [comment]
> @phhusson Can you assist me to debug the problem? I'm a developer too
> 
> PS. If you need donation to support your work, let me know I can donate some BATs

Do you have a logcat from boot?? Can you attach there?

**Comment by bahamut657** [comment]
@MMan1982 can you explain me how to get logcat when stucking on boot animation please?
If you can help me, I can try the newest @phhusson release next data.
Regards

**Comment by MMan1982** [comment]
run this command on your computer before booting your phone up, and it will wait for the device:

adb -d logcat

Also, make sure you can connect to adb with your phone in working order before trying to logcat during boot:

1. android sdk installed
2. proper usb driver installed

**Comment by MMan1982** [comment]
> @MMan1982 can you explain me how to get logcat when stucking on boot animation please?
> If you can help me, I can try the newest @phhusson release next days.
> Regards

run this command on your computer before booting your phone up, and it will wait for the device:

adb -d logcat

Also, make sure you can connect to adb with your phone in working order before trying to logcat during boot:

1. android sdk installed
2. proper usb driver installed

I hope it will be work! Without adb is not possible :(

**Comment by bahamut657** [comment]
Hi @MMan1982 
I re-flashed the laster release of Android10 GSI , but now I'm stucked in bootloop.
I get the CUBOT logo on booting (and the Orange state) but the device seems to reboot after 5 secs with no output on adb logcat -d
Any ideas?
(I' ve not installed TWRP this time because touchscreen not working on it)

**Comment by MMan1982** [comment]
Ehm:( I've did some googling about the problem and i found that you can get a working adb when twrp running,but if you not installed it then you cannot try it:( Sorry. I have no more idea then :(

**Comment by MMan1982** [comment]
Új

> Hi @MMan1982
> I re-flashed the Android10 GSI last release (v215, but also v214 do the same) , but now I'm stucked in bootloop.
> I get the CUBOT logo on booting (and the Orange state) but the device seems to reboot after 5 secs with no output on adb logcat -d
> Any ideas?

Ehm:( I've did some googling about the problem and i found that you can get a working adb when twrp running,but if you not installed it then you cannot try it:( Sorry. I have no more idea then :(

**Comment by bahamut657** [comment]
I've got it installed without touchscreen but I can send command via adb shell 
Let me know

Regards

**Comment by MMan1982** [comment]
Try: Adb logcat > logcat.txt
And then copy logcat.txt,if adb logcat print anything. With twrp your computer must see drives on your phone if i good..

**Comment by MMan1982** [comment]
> I've got it installed without touchscreen but I can send command via adb shell
> Let me know
> 
> Regards

Try: Adb logcat > logcat.txt
And then copy logcat.txt,if adb logcat print anything. With twrp your computer must see drives on your phone if i good..

**Comment by MMan1982** [comment]
> I've got it installed without touchscreen but I can send command via adb shell
> Let me know
> 
> Regards

Try first adb logcat,if it print anything then create that file.

**Comment by bahamut657** [comment]
Installed also magisk-phh.zip . GSI AOSP 9 191210 works.
All other GSI release Android9 or Android10 doesn't. @phhusson any ideas?

Anyone can help me debug the problem?
I flashed all the ROM with fastboot after unxz the compressed file.

@MMan1982 do you have a fully working TWRP for this device or, as in mine, the touchscreen not working in RECOVERY?

**Comment by bahamut657** [comment]
Ehi all!!
I finally resolve the issue, the problem isn't in the ROM itself but in the operations sequence.
Now all works and I'm enjoyng Android 10 GSI (finally).
In order to make it work:
1) Reboot to fastboot
2) Perform fastboot -w 
3) Flash STOCK BOOT partition
4) Flash the GSI ROM
5) Flash the vbmeta with the following command: fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
6) Now reboot in recovery and Wipe Userdata/Cache/Dalvik
7) Flash Gapps and Magisk (if needed)
Et voilat.
Thank you all for the support, I mark this issue as resolved

**Comment by R2P091** [comment]
Hello  bahamut657, maybe you could help me : I own a Cubot Quest too (stock V11). I'd like to install a GSI rom (treble app say It's a go, ARM64 A only) but anyway I try I always finish on bootloops.... Will you share your experience please? (I tried your method and the one found on XDA regarding AOSP 9 GSI...)

**Comment by bahamut657** [comment]
Hi @R2P091! 
To install the GSI ROMs, in our device, is not so difficult. I explain to you how you can do it yourself. 
I try this procedure only with stock v13 ROM and not the native v11 (but I don't know if it could be the difference).
Another problem is the image you choose. CubotQuest is AB device not Aonly (TrebleCheck is reporting wrong device, TrebleInfo app works, like phusson said)

So, having a CUBOT Quest with stock v13, you can follow the procedure reported in the CUBOT Quest GSI Wiki page (I've just updated the wiki page with the correct procedure and the correct device type).
Remember to follow all the steps like described in the wiki page (using that I'm able to flash GSI 11 also).

If you need TWRP for your device you can find one in 4pda site (it works for me, but the touchscreen inside TWRP will not, so you have to connect an OTG USB + mouse to control the screen - but following the Wiki Page you have not to flash ROM using TWRP).

Let me know, I'm available to support you ;)
Regards

**Comment by R2P091** [comment]
Many thanks for your fast and kind reply. I will check The Wiki page and will let you know.
Btw ther is an unofficial TWRP working on Cubot Quest.
Regards

**Comment by R2P091** [comment]
Could you please give me the link to the "CUBOT Quest GSI wiki", I can't find it sorry...

**Comment by bahamut657** [comment]
In top of this page there is the Wiki link

[](https://github.com/phhusson/treble_experimentations/wiki) this is the main page

[](https://github.com/phhusson/treble_experimentations/wiki/Cubot-Quest)

**Comment by R2P091** [comment]
Thank you and sorry, I'm quiet new here ...
When you say flash"STOCKBOOT.img" and "VBMETA.img" these 2 come from the lastest stock rom (V14) right?
If you need the working TWRP let me know.

**Comment by bahamut657** [comment]
Stock boot.img is from my ROM. I'm installing v13, so i re-flash Boot.img inside the v13 package that I downloaded from the CUBOT website.

VBMETA.img is from the same pakage

Do you have a working touch screen on TWRP? 
If so, can you send me a link to download? (I've got the 3.3.1 version by Mechanik - other guys seems to work with v11 ROM, is it possible that v13 introduce some additional security check? )

**Comment by R2P091** [comment]
Many thanks for your help : highly appreciated...I'll give it a try and will let you know.
I got my working TWRP from here : https://unofficialtwrp.com/unofficial-twrp-3-3-1-root-cubot-quest/
It worked on every stock rom (V11, V13 and V14) I tried....

**Comment by R2P091** [comment]
thanks to you I was successful to install AOSP (I guess my problem came from the A only GIS...). I'm facin a problem though : phone is encrypted ( I placed the "-W" commande and did a factory reset  but phone stay encrypted... Any clue? (I can't use data backup in TWRP...)

**Comment by bahamut657** [comment]
Format userdata after flashing GSI with TWRP (or fastboot) and reboot the phone

**Comment by R2P091** [comment]
I did that twice but TWRP says "formatting data using mke2fs, done. Updating partition details...Failed to mount '/system' (invalid argument)...done.
Still encrypted....

**Comment by R2P091** [comment]
I am really sorry to bother you that much....

**Comment by R2P091** [comment]
No matter what I wipe or format it keeps saying "phone encrypted"....

**Comment by bahamut657** [comment]
Do u prerform `fastboot -w` twice,like in the wiki guide? Do u follow all the steps in a single fastboot session?

**Comment by R2P091** [comment]
I did but I'm gonna give it another chance...

**Comment by bahamut657** [comment]
Ensure that it prints "wiping userdata" or something similar (before procede with other steps)
The encryption problem is only due to missing formatting

**Comment by R2P091** [comment]
I did it again, following your tutorial step by step but it still says "encrypted".... When or where should I see the "wiping userdata". I know I'm getting close but damn!!!!

**Comment by R2P091** [comment]
BTW : my twrp is still working on android 11

**Comment by R2P091** [comment]
As the system is GIS, I guess that the "default encrypted" comes from the "vendor" partition right?

**Comment by bahamut657** [comment]
For me, a `fastboot -w` twice after first boot and than rebooting, resolve the encryption problem.
If not, ask phhusson for more help.
Regards

**Comment by JonnyTech** [comment]
Try flashing the following file, taken from stock rom: [userdata.zip](https://github.com/phhusson/treble_experimentations/files/5850685/userdata.zip)

```
$ unzip userdata.zip
$ fastboot flash userdata userdata.img
```

That file is a clean data filesystem for the device:

```
$ simg2img userdata.img userdata.img.raw
$ file userdata.img.raw 
userdata.img.raw: Linux rev 1.0 ext4 filesystem data, UUID=5ddf0a37-b3d0-4d87-8b33-b98043cbcf41, volume name "data" (extents) (large files) (huge files)
```

**Comment by bahamut657** [comment]
If the method suggested by  @JonnyTech  doesn t work, Can you please attach the output of the doubled `fastboot -w`?
Regards

**Comment by R2P091** [comment]
Hello JonnyTech , many thanks for your help.
I flashed the userdata.zip afetr I flahed everything else (bahamut657 great method,no magisk, and my GSI is with gapps). Unfortunately phone is still encrypted (TWRP ask for a password, and internal storage shows 0Mb so no way to back it up).
I'm not that good with flashing so I guess I did soething wrong : do I have to only flash (after unzipping) "fastboot flash userdata userdata.img" or do I have to send the two following commands ($ simg2img userdata.img userdata.img.raw
$ file userdata.img.raw )?

**Comment by R2P091** [comment]
sure bahamut657 , here it is..
[Log 22-01-2020.txt](https://github.com/phhusson/treble_experimentations/files/5854583/Log.22-01-2020.txt)

**Comment by JonnyTech** [comment]
> do I have to only flash (after unzipping) "fastboot flash userdata userdata.img"

Yes, that is correct.

If you do want to try flashing the unsparsed image (iirc about 4gb), do it from TWRP ("install" >> "install image" section).

**Comment by bahamut657** [comment]
Can you try booting TWRP and connect to it using ADB (`adb shell`). 
Once logged in:
`twrp wipe userdata`
`twrp wipe data`
and reboot

**Comment by bahamut657** [comment]
If methods posted before doesn't work , try this one (from ADB in TWRP)
`recovery --wipe_data --set_filesystem_encryption=off`
Regards

**Comment by R2P091** [comment]
> > do I have to only flash (after unzipping) "fastboot flash userdata userdata.img"
> 
> Yes, that is correct.
> 
> If you do want to try flashing the unsparsed image (iirc about 4gb), do it from TWRP ("install" >> "install image" section).

What is unsparsed image and where to find it please?

**Comment by JonnyTech** [comment]
> What is unsparsed image and where to find it please?

Use `simg2img` to expand file: `simg2img userdata.img userdata.img.raw`

**Comment by R2P091** [comment]
bahamut657, 
I tried the 3 commands but phone stays encrypted (see the log please).
When I use "recovery --wipe_data --set_filesystem_encryption=off" TWRPP reboots and cmd screen stays on the last line of the log : I LANG : ru..... I know I'm close. ;-)

**Comment by bahamut657** [comment]
Can you attach the logs for the last 3 commands?

If you boot the ROM, and it says Phone is encrypted, is not present an option to factory reset the phone? (If I remember correctly the very first time I've got this problem...)

**Comment by R2P091** [comment]
[Log.22-01-2021- 2.txt](https://github.com/phhusson/treble_experimentations/files/5855193/Log.22-01-2021-.2.txt)
here is the log...
I did a "factory reset" from TWRP, I could see the real size of my internal storage then but as soon as I reboot to system, phone is encrypted back. I made a factory reset from my phone' parameters but there again,it reboots as encrypted...
What is TWRP UI please?

**Comment by R2P091** [comment]
> > What is unsparsed image and where to find it please?
> 
> Use `simg2img` to expand file: `simg2img userdata.img userdata.img.raw`

You mean that: I connect my phone (fastboot) and run this command with platform tools? It will push the image into my phone?

**Comment by R2P091** [comment]
Do you think that the default encryption may be caused by vbmeta.img ( kind of default option somewhere in there?). Is it really necessary to flash the vbmeta.img?

**Comment by R2P091** [comment]
I tried to flash  -w + -w + boot.img + systeme+ userdata (JonnyTech file) then reboot (no vbmeta.img) : android 11 boots easily but still have an encrypted phone....

**Comment by R2P091** [comment]
Whatever I try , I get an encrypted phone... What would you recommend F2FS or EXT4 partition for data and system?
Every time I perform a "factory reset" (via my phone parameters that leads me to TWRP), I get a red message saying "failed to mount '/system' (invalid argument)....

**Comment by JonnyTech** [comment]
After you format userdata from TWRP, are you then able to mount `/data` and write and read files to it? If yes then the issue is that your phone encrypts `/data` on boot and you need to edit `fstab` to stop it happening.

**Comment by JonnyTech** [comment]
> I get a red message saying "failed to mount '/system' (invalid argument)....

Hold on. Did I misread the issue? I thought that the problem is with `/data`, not `/system`. What...?

**Comment by R2P091** [comment]
JonnyTech, I'm not good enough to say but when I try to make a backup with TWRP it says "system image (2600Mb), Vendor image (800Mb) and date (excl.storage) (0Mb). That's my main concern as "data" always says (0Mb) i can't backup anything...

**Comment by JonnyTech** [comment]
So that is after you have rebooted into the system? And your version of TWRP does not support encryption. OK, can you post your `fstab` file, mine is in `/vendor/etc/fstab.qcom`, yours may be somewhere similar.

We are looking for the word `forceencrypt` in that file. If is exists, change it to `encryptable`. Then reformat /data (twice) and reboot.

**Comment by R2P091** [comment]
Yes you're right : every time I reboot, my data get encrypted. My unofficial TWRP version says "3.3.1 by Mehanik6 Cubot Quest". Should I change my TWRP for a more specific one?

**Comment by R2P091** [comment]
It's getting worst : now when I try to push the "--disable-verity --disable-verification flash vbmeta vbmeta.img" command, fastboot says "dns server doesn't make authority for that zone" (sorry poor translation from French). I used to be successful with this command...

**Comment by JonnyTech** [comment]
One issue at a time. Fix `fstab` first. Ask in phh telegram group for other issues.

**Comment by R2P091** [comment]
I will thanks
