### ISSUE TITLE
Blu Bold N1 finger print not work any gsi

### ISSUE THREAD

**Issue by mrmazakblu** [phhusson/treble_experimentations#1183]
Device works 99% out of the box with phh gsi. 

In screen fingerprint.
Logs can be added as needed.

Device info page.
http://www.deviceinfohw.ru/devices/item.php?item=56201

Firmware dump page.

https://github.com/mrmazakblu/blu_n0030ww_dump

**Comment by phhusson** [comment]
I removed offline charging since that's another issue.

please give the result of `adb shell lshal`

**Comment by mrmazakblu** [comment]
[bold-lshal.txt](https://github.com/phhusson/treble_experimentations/files/4334339/bold-lshal.txt)

**Comment by mrmazakblu** [comment]
unlock menu is available in the settings menu. But green circle never appears on screen.

**Comment by mrmazakblu** [comment]
[bold-lshal-skipped.txt](https://github.com/phhusson/treble_experimentations/files/4334369/bold-lshal-skipped.txt)

these warnings came with the lshal command also.

**Comment by phhusson** [comment]
Ok, so set persist.sys.fp.fod.location.X_Y the to x,y of your sensor
and persist.sys.fp.fod.size.width_height to 190,190

Le dim. 15 mars 2020 à 15:55, mrmazakblu <notifications@github.com> a
écrit :

**Comment by mrmazakblu** [comment]
I try to grep for persist.sys.fp.fod.location
it has no found results

**Comment by phhusson** [comment]
Why do you think I'm telling you to set it?!?

**Comment by mrmazakblu** [comment]
ok

**Comment by mrmazakblu** [comment]
I have made the setprop and rebooted, confirmed with getprop | grep to see they are added, but have not been able to get the green circle to appear.

**Comment by phhusson** [comment]
Show the `getprop |grep` you did and its result?

**Comment by mrmazakblu** [comment]
C:\Users\Mr>adb shell setprop persist.sys.fp.fod.location.X_Y 100,100

C:\Users\Mr>adb shell setprop persist.sys.fp.fod.size.width_height 190,190

C:\Users\Mr>adb reboot

C:\Users\Mr>adb shell "getprop | grep fp.fod
[persist.sys.fp.fod.location.X_Y]: [100,100]
[persist.sys.fp.fod.size.width_height]: [190,190]

C:\Users\Mr>adb shell lshal > bold-lshal-2.txt

**Comment by phhusson** [comment]
You're running my AOSP v213 or v214?

**Comment by mrmazakblu** [comment]
214

**Comment by phhusson** [comment]
hum i don't understand, you should have a green circle. not at the right place, your x,y is totally wrong, you'd get the green circle on top-left
should more be something like 400,1800 if your screen is 1080p

**Comment by mrmazakblu** [comment]
I do actually have the green circle. It was so high it was hidden. I am moving it around to about. Where it was on stock. I assume when I get the right spot it will register on the setup page.

**Comment by mrmazakblu** [comment]
![Screenshot_20200315-125704](https://user-images.githubusercontent.com/23422338/76706410-a3bac580-66bd-11ea-9c1a-a62a3476c0e9.png)

**Comment by phhusson** [comment]
Please send a screenshot of fingerprint sensor in stock rom.
And measure x,y based on this

**Comment by mrmazakblu** [comment]
i was trying to put it too low.

**Comment by mrmazakblu** [comment]
![Screenshot_20200315-133616](https://user-images.githubusercontent.com/23422338/76707042-74f31e00-66c2-11ea-9adb-03bb6f2bca8b.png)

**Comment by mrmazakblu** [comment]
measures 540,2000

trying that position out, will update if it reads fingerprint

**Comment by phhusson** [comment]
You need to do -95 on both values because it's not the center but the corner

Le dim. 15 mars 2020 à 19:08, mrmazakblu <notifications@github.com> a
écrit :

**Comment by mrmazakblu** [comment]
TY, i didn't realize that. but  now the green circle lines up, it is not registering fingerprint yet. It recognizes a touch at that pixel location and turns on the green light, but that is all I see it doing.

**Comment by phhusson** [comment]
Ok, now please provide logcat right after boot, and when trying to enroll

**Comment by mrmazakblu** [comment]
[Uploading fresh-boot.txt…]()

**Comment by mrmazakblu** [comment]
[fresh-boot.txt](https://github.com/phhusson/treble_experimentations/files/4334857/fresh-boot.txt)

**Comment by phhusson** [comment]
Right I see, it's a different goodix HAL, though it's also named goodix as the one I had previously.

I'll see what I can do.

**Comment by phhusson** [comment]
Ok, first thing:
As root, do
`echo 1 > /proc/leds/hbm_mode`
then
`echo 0 > /proc/leds/hbm_mode`

What does it do?

**Comment by mrmazakblu** [comment]
Echo 1 made screen bright, slider was still set at low.

Echo 0 returned to slider set brightness

**Comment by mrmazakblu** [comment]
So, this apk may need to be reversed to find the command string needed?

https://github.com/mrmazakblu/blu_n0030ww_dump/tree/full_k71v1_64_bsp-user-9-PPR1.180610.011-1563880452-release-keys/system/system/priv-app/PriGoodixFingerprintManager

**Comment by phhusson** [comment]
it's not really command "string", it's mostly two ints
I'll do a blind try before that though
Both Xiaomi and the previous goodix fingerprint I had was using {10, 1} and
{10, 0} so we could just try that

Le lun. 16 mars 2020 à 21:18, mrmazakblu <notifications@github.com> a
écrit :

**Comment by mrmazakblu** [comment]
This file is all the references to "sendcommand" i was able to find

[fnd-sndcmd.txt](https://github.com/phhusson/treble_experimentations/files/4340895/fnd-sndcmd.txt)

**Comment by phhusson** [comment]
To look for sendCommand you'll need to decompile goodix APKs

Here is a blind test image,  I doubt it works but who knows:
https://treble.phh.me/sys-bold-n1-fp1.img

If it fails, please include a logcat.

**Comment by mrmazakblu** [comment]
That is where I got that list from. I used apk tool to decide and decompile the goodix apk, and used findstr to show "sendComand" lines in the whole decompiled folder. 

Trying this new image after work, will post log. When done. ~6 hours or so. 

Ty

**Comment by mrmazakblu** [comment]
log shows "PHH-Enroll" entries, but did not register any fingerprints yet.

[bold-n1-fp1-log.txt](https://github.com/phhusson/treble_experimentations/files/4345902/bold-n1-fp1-log.txt)

**Comment by phhusson** [comment]
`03-17 17:16:21.346  1311  1311 I android_os_HwBinder: HwBinder: Starting thread pool for getting: vendor.goodix.hardware.biometrics.fingerprint@2.1::IGoodixFingerprintDaemon/default`

Connecting to goodix fingerprint sensor worked fine
And from what I can see from the logs, there hasn't been any error sending the command

We can see goodix HAL receive the commands:

`03-17 17:16:46.873   929   929 D [GF_HAL][SZCustomizedProductTest]: [executeCommand] cmdId = 10 (NULL)`

However it looks like command 10 isn't known by goodix hal, so that's probably not this, I'll dig into the stock rom to check what's the proper command.

**Comment by mrmazakblu** [comment]
Anything I can do to help?, Just let me know..

**Comment by mrmazakblu** [comment]
Would a log from stock rom enrolling fingerprint show the cmID ?

**Comment by phhusson** [comment]
Yeah you're reasoning is right, it could help.

**Comment by mrmazakblu** [comment]
Here is logcat while enrolling FP on stock. 
 I see multiple cmID #, I hope this file helps.

[bold-n1-fp1-log-stock.txt](https://github.com/phhusson/treble_experimentations/files/4351549/bold-n1-fp1-log-stock.txt)

**Comment by phhusson** [comment]
Perfect

https://treble.phh.me/sys-bold-n1-fp2.img

**Comment by mrmazakblu** [comment]
Nice. The fingerprint now works. I needed to still manually do the setprop. but after a reboot it worked. 

on the fp1 test i had done a dirty update, so the setprop was still active from before?????

this time on fp2, since i had to go to stock I needed to do full wipe,.

[bold-n1-fp2-log2--after setprop.txt](https://github.com/phhusson/treble_experimentations/files/4351987/bold-n1-fp2-log2--after.setprop.txt)
[bold-n1-fp2-log--before setprop.txt](https://github.com/phhusson/treble_experimentations/files/4351988/bold-n1-fp2-log--before.setprop.txt)

**Comment by mrmazakblu** [comment]
I do not see the error myself in this log. Maybe you can find it. 

![screen](https://user-images.githubusercontent.com/23422338/77021703-dda9f700-695d-11ea-8328-c38373142e16.png)
[bold-n1-fp2-log3--unknown-error.txt](https://github.com/phhusson/treble_experimentations/files/4352169/bold-n1-fp2-log3--unknown-error.txt)

**Comment by phhusson** [comment]
You're sending very mixed messages there :P

You managed to enroll succesfully, but authentification doesn't work, is that what you're saying?

**Comment by mrmazakblu** [comment]
That is what happened.

I was able to enroll FP.  Then I locked phone to test it. It worked. I did 5 or 6 lock/ unlock cycles. They all worked. 
Then after about 20 minutes, it no longer worked. 

During that time Google was loading apps from my cloud backup. I need to wipe phone again, and see if FP works without Google updates???

**Comment by phhusson** [comment]
Ok, I'm guessing it's something pretty simple.

When you fail authenticating with your finger, set brightness manually to 100%, and try again
I guess I need to implement the echo 1 > /proc/leds/hbm_mode thingy

**Comment by mrmazakblu** [comment]
That seems to have worked. I cleared all prints, reentered. And retested. FP works and authentics again..

**Comment by phhusson** [comment]
I enabled HBM stuff in here, please test:
https://treble.phh.me/sys-bold-n1-fp3.img

**Comment by mrmazakblu** [comment]
Test build 3 does the same. 
If screen brightness is not set to full, then FP fails. 

Also noticed if I use shell to echo 0 to /proc/.... Hbm_mode , screen goes bright, as expected.

But if I go to lock screen to try FP. The brightness returns to lower level, as set by adaptive brightness. 

I will add a log of trying to unlock, then manually adjust brightness to full and repeat the unlock with fp.

**Comment by mrmazakblu** [comment]
[fp3-hbm_mode.txt](https://github.com/phhusson/treble_experimentations/files/4357083/fp3-hbm_mode.txt)

**Comment by phhusson** [comment]
Okay, well please do `setenforce 0` from a root-ed shell, and (without rebooting) try again

**Comment by mrmazakblu** [comment]
Made into permissive. And tried again. Still will not turn bright. So FP still fails.

Interesting.... I cat the hbm_mode file , it was at 1


I "echo" it to now be 0.

Try to unlock with fp. Did not work.

Cat hbm_mode again, it was now set to 1, but screen never went bright.

So permissive allowed for hbm_mode to be automatically changed, it's just not all that seems to be needed

**Comment by mrmazakblu** [comment]
Stock logcat shows two lines at beginning of FP and 2 at end.

setHBMMode open = true
setHBMByNode value = 1

setHBMMode open = false
setHBMByNode value = 0

**Comment by mrmazakblu** [comment]
There is a specific timing issue with the hbm_mode 0 & 1 settings. 

Setting the phone permissive actually does work with the hbm_mode build tweeks. 

But hbm must be zero first. If it is already a 1, setting 1 will not make screen bright. 
And setting hbm while Android is unlocked does not seem to be enough.

I needed to adb shell set the hbm mode to 0 while on the lock screen in order for touching the FP to make it bright.

**Comment by mrmazakblu** [comment]
So I think if hbm_mode was added to see context, and the echo command was modified to first echo 0 then 1, this will work.
But I don't know how you did made it, so I cant modify and make a pull request. 

Thanks for you work on this. Again you have shown how top notch Dev you are.

**Comment by mrmazakblu** [comment]
> Okay, well please do `setenforce 0` from a root-ed shell, and (without rebooting) try again

How to make this work without leaving system in permissive?

**Comment by taher34** [comment]
Can any help me to fix fingerprint in condor allure x. please

**Comment by mrmazakblu** [comment]
Test images from this issue have expired from GitHub, I assume. They all show 404 not available. I have them, and uploaded the last image test3 to Android file host. Here is link.

https://www.androidfilehost.com/?w=files&flid=300270

**Comment by phhusson** [comment]
@mrmazakblu can you `ls -lZ /proc/leds/hbm_mode`?
I'll add a quick and dirty chmod/chcon/chown in rw-system.sh

**Comment by mrmazakblu** [comment]
> @mrmazakblu can you `ls -lZ /proc/leds/hbm_mode`?
> I'll add a quick and dirty chmod/chcon/chown in rw-system.sh

C:\Users\Mr>adb shell su -c 'ls -lZ /proc/leds/hbm_mode'
-rw-rw-rw- 1 system system u:object_r:proc:s0 0 2020-05-20 20:16 /proc/leds/hbm_mode

**Comment by mrmazakblu** [comment]
I left this phone for short while, I was using Redmi note 8 instead. I came back and tried the current latest release. V221. The FOD is working on this version.
