### ISSUE TITLE
Sony Xperia XZ fingerprint sensor!

### ISSUE THREAD

**Issue by xelmasx** [phhusson/treble_experimentations#1193]
we shouldn't use fingerprint option!
1. I guess it doesn't let phone go to deep sleep. 
2. it restart phone randomly that restart cause to drain battery.

**Comment by mirh** [comment]
If it's a phone specific issue, report back to your device's dev. Not here. 
https://forum.xda-developers.com/xperia-xz/development/f8331-2-project-treble-xperia-xz-t4029421
