### ISSUE TITLE
No incoming audio in phone calls [Razer Phone/cheryl/potentially all CAF devices]

### ISSUE THREAD

**Issue by linuxct** [phhusson/treble_experimentations#12]
Logcat and dmesg seem okay.  
Tried changing the Dialer app to Google's stock one, didn't fix the issue.  
Also tried re-routing the audio from the earspeaker to the actual speakers, and to Bluetooth headset, but didn't solve the issue. Only sound that comes from them is a loud 'beep' when the call ends.   
3rd party VoIP apps like Telegram or WhatsApp have no issues at all with in-call audio.
  
May need custom audio re-routing inside the mixer_paths?

**Comment by linuxct** [comment]
Manually extracting the following files from the razer DP1 image (injecting their respective vdex's)   
framework/qcrilhook.jar  
framework/qti-telephony-common.jar  
framework/QtiTelephonyServicelibrary.jar  
and placing them inside the system partition along with their respectives permission xml's **DIDN'T SOLVE** the issue.  

This means MSM8996 fixes don't help in the MSM8998.

**Comment by DroidAlexandra** [comment]
Getting my Razer phone tomorrow, let's see then, subscribed to issue.

**Comment by linuxct** [comment]
As a follow up to last night's comment, trying to inject the Apks corresponding to Qcomm RIL QtiTelephonyService, QtiSystemService, Qcrilmsgtunnel from the stock rom into the GSI didn't work either.  
Just adding as much info as I can so that no one needs to mess around with already tested stuff.

**Comment by linuxct** [comment]
As an update, @TheCrazyLex and I have tried by adding the flag "AUDIO_OUTPUT_FLAG_FAST" to the primary output mixport inside vendor's audio_policy_configuration, still with the same results

**Comment by linuxct** [comment]
New update. I've delete the Razer signature from the files QtiTelephonyService, QtiSystemService, Qcrilmsgtunnel, and resigned them with the system signing key. Now files are installable and services run like normal. For the specific case of Qcrilmsgtunnel, I've faced the issue that it was missing a library from HIDL, but that file is indeed present in the system after comparing the tree output between GSI image and Razer image.   

![photo_2018-04-07_22-30-01](https://user-images.githubusercontent.com/3966313/38460092-8bdf731c-3ab3-11e8-9996-79019a23c93b.jpg)  

Concerned, I decompiled the apk in question and changed `<uses-library android:name="android.hidl.manager@1.0-java" />` to `<uses-library android:name="android.hidl.manager@1.0-java" android:required="false" />`. Now the file loads up properly and is running in the system as a background task.  

![photo_2018-04-07_22-32-51](https://user-images.githubusercontent.com/3966313/38460099-a4324afc-3ab3-11e8-92a5-66981fc53c41.jpg)  


Now, I moved the missing libs back to the system to check if audio worked, and this is what happened: 
[log.txt](https://github.com/phhusson/treble_experimentations/files/1886713/wow.txt). System becomes unstable, Android phone crashes constantly at boot, and all apps begin to crash due to mismatch in time service.  

From the log, we can extract the following 2 errors:  
`04-02 16:07:57.408  3945  3945 I zygote64: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.codeaurora.internal.IExtTelephony$Stub" on path: DexPathList[[zip file "/system/framework/qti-telephony-common.jar"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]` 
and
`04-02 16:07:57.412  3945  3945 I zygote64: Rejecting re-init on previously-failed class java.lang.Class<com.qualcomm.qti.internal.telephony.QtiRIL>: java.lang.IncompatibleClassChangeError: Superclass com.android.internal.telephony.RIL of com.qualcomm.qti.internal.telephony.QtiRIL is declared final (declaration of 'com.qualcomm.qti.internal.telephony.QtiRIL' appears in /system/framework/qti-telephony-common.jar)`  

Final thought: I'm done :)

**Comment by linuxct** [comment]
I've fixed it. I'll write up one last comment with everything needed to reproduce the fix on any device.

**Comment by linuxct** [comment]
Check out these thread I've made to bloat this issue less: https://forum.xda-developers.com/project-treble/trebleenabled-device-development/treble-qualcomm-device-call-audio-check-t3774818  
This isn't a permanent fix however, and can be addressed directly from compilation time in GSIs.

**Comment by phhusson** [comment]
Some investigations about the always-on-speaker mode:
Editing audio_policy_configuration.xml to include Earpiece as attachedDevices, and change devicePort Earpiece from AUDIO_CHANNEL_IN_MONO to AUDIO_CHANNEL_OUT_MONO makes earpiece working!
Going to speaker mode works as well.
Going back from speaker doesn't though.

**Comment by phhusson** [comment]
The same change without actually changing audio_policy_configuration.xml:
https://github.com/phhusson/platform_frameworks_av/commit/3f7e564c89bad9e7adaff0d400865eb13e27bb38
