### ISSUE TITLE
GEt rid of boot msg "Your device has been unlocked and can't be trusted" P20 lite

### ISSUE THREAD

**Issue by geppone70** [phhusson/treble_experimentations#1203]
to get rid of "Your device has been unlocked and
can't be trusted" boot msg on P20 lite, can I relock the FRP and Bootloader?
After the factory reset, will system treble rom boot again? 

thanks

**Comment by Montelion** [comment]
No. You can't.
Yes, it will remove the boot message, but it will prevent the rom from booting up.

**Comment by Montelion** [comment]
Btw you should probably close this, as your question has been answered. Thanks

**Comment by geppone70** [comment]
Ok
