### ISSUE TITLE
Brightness at half when 100% on Honor 8X Max on Any GSI (AB) Rom

### ISSUE THREAD

**Issue by riadhtaihi** [phhusson/treble_experimentations#1204]
Hi Team,

I installed LOS 17.1 and a couple of other GSI roms yesterday on my Honor 8X Max (At last) and it worked super duper fast, however The screen is not fully bright (Like 50 %).

I have been reading here and there that the issue comes from VENDOR Overlays, is there way anybody can help me fix this please?

Should I backup my Stock Vendor or something else from Stock to use with GSI Roms?
I am very tired of EMUI which is very intrusive and slow.

Thank you/Merci d'avance!

**Comment by riadhtaihi** [comment]
@phhusson Any idea maybe ?

**Comment by AndyCGYan** [comment]
Ooh, 8X Max is GSI capable? I've read otherwise... Off-topic, but can you briefly outline how (other than unlocking BL first, ofc)?

**Comment by riadhtaihi** [comment]
Hi @AndyCGYan Most all of devices from 8.1 are likely to be Treble GSI compatible, you just gotta find what Partition it uses. For this device, it was kinda tricky as it was supposed to be A partition but I found out that it on EMUI 8 neither  or AB worked, so after several tests, I found out that using any EMUI 9, we gotta use AB and not A, so I tried LOS 17.1 and worked like a charm but as TWRP is not the best for this device and I did not want to bother decrypt it, then root and install GAPPS, I preferred to install AOSP 10 now and it works like a charm.

Simply, reset factory your phone from Recovery, then reboot in Fastboot and in Command line use:

sudo fastboot system GSIIMAGE.IMG 

fastboot reboot

The OS should boot within 1 or 2 minutes maximum, but the only drawback is the brightness that is low.

**Comment by AndyCGYan** [comment]
Thanks @riadhtaihi , knowing that it can be done, I've ordered myself a Huawei Enjoy Max (basically the same device rebranded), hopefully I'll be able to assist in the issue (looking into it or simply providing logs) when it arrives.
BTW, your LOS 17.1 GSI is likely my production :) (or probably eremitein's which is based on mine)

**Comment by riadhtaihi** [comment]
@AndyCGYan I wanted LOS as well but unless you finda rooter and gapped version, it will bothersome to root it and gapp it. I do like LOS as well but for a strange reason brightness is worse in it than AOSP, so for now I am with it, untill we fix the issue.

Update: I tried the method of adding overlay file to vendor from XDA but nothing changed.
Link:https://forum.xda-developers.com/project-treble/trebleenabled-device-development/overlay-enable-night-light-adaptive-t3741965

I think that we will need to add a few files from Stock rom to our GSI ROM. 
Let me know if anything from your side.

**Comment by riadhtaihi** [comment]
Update:

Partially solved by replacing a few Libs. But now it stays from 50 % to 100  and does not go lower.

**Comment by AndyCGYan** [comment]
Got my Enjoy Max, here are some details and observations:
- `ro.vendor.build.fingerprint = qti/sdm660_64/sdm660_64:9/PKQ1.181203.001/jenkins11210111:user/release-keys`
(Huawei really doesn't care about their QCOM devices eh)
- No overlay in `/vendor` at all
- Brightness node is `/sys/class/leds/lcd-backlight/brightness`
- Max brightness is 4095 as indicated by `/sys/class/leds/lcd-backlight/max_brightness`
- When nothing is set, or with `setprop persist.sys.qcom-brightness -1`, brightness slider has a range of 10-255
- With `setprop persist.sys.qcom-brightness 255`, range is 1-28
- With `setprop persist.sys.qcom-brightness 4095`, the slider exhibits a multi-segment behavior, range is 1-37
@phhusson Kinda surprised that the typical `setprop` doesn't deal with the issue, what else can we try?

@riadhtaihi You're right, that TWRP is kinda wonky, touch rarely works and no ADB/MTP. Still I decrypted data because only then will TWRP be able to read/write internal storage and serve some real purpose (backup/restore works properly).

**Comment by riadhtaihi** [comment]
Hey @AndyCGYan replacing some libs make the brightness go until 100% normally but, still the Automatic brightness does not seem to work and if we replace those Libs, we will have a brightness from 50 to 100% and not 0 to 100%.

I think we need to add a different overlay that I added.
The trick with that TWRP is that if the touch stops working, just plugin a Keybaord or mouse and it will work again ;)
Decrypting data has became easier even from the system itself and without TWRP.

So, let's communicate somewhere on Telegram if you don't mind ;)

**Comment by AndyCGYan** [comment]
> Hey @AndyCGYan replacing some libs make the brightness go until 100% normally but, still the Automatic brightness does not seem to work and if we replace those Libs, we will have a brightness from 50 to 100% and not 0 to 100%.

I'd rather not kang stuff into `/system` unless it's the only option...

> So, let's communicate somewhere on Telegram if you don't mind ;)

Same ID as here; better join the [PHH Treble group](https://t.me/phhtreble) as well while you're at it.

**Comment by duxiaofeng-github** [comment]
@riadhtaihi press volume up + power button. release at 3th boot, touch will work, at least in my 8x max.

**Comment by riadhtaihi** [comment]
Thx @duxiaofeng-github 
I found another way to make Touch work on TWRP.
Just insert a keyboard or mouse and it will work again ;)

**Comment by duxiaofeng-github** [comment]
@riadhtaihi may i ask you which version of LOS you are using? i can't find a LOS match honor 8x max
 on its official website. in the end i flash a 10.1 AOSP on this project and it works well.

**Comment by riadhtaihi** [comment]
@duxiaofeng-github I used 17.1 and 16.1 from this list:
https://github.com/phhusson/treble_experimentations/wiki/Generic-System-Image-%28GSI%29-list

**Comment by duxiaofeng-github** [comment]
i see, have you try the official Google GSI？i try @phhusson 's AOSP, it works perfect. i'm wondering what's the different between Google GSI, phhusson's AOSP and LOS.

**Comment by AndyCGYan** [comment]
@duxiaofeng-github AOSP and LOS are two different ROMs altogether. Google's probably won't even work.

**Comment by riadhtaihi** [comment]
@duxiaofeng-github @phhusson  's AOSP is tweaked and improved for various devices, while AOSP Pure is not. However, I do prefer LOS than AOSP, I've been using it since its creation and it has always been good throughout the years

**Comment by duxiaofeng-github** [comment]
well, i met the same issue now. i flash the latest ASOP and found out its max brightness is about 50% than official emui rom.

**Comment by rocwellg** [comment]
Hello team,

This is my first attempt to flash GSI roms when I decided to update my Huawei Enjoy Max ( latest version on EMUI8).
I've been playing around for a few days now and tested quite a lot of GSI roms.
Almost all of them ended up into bootloop (tried fastboot flash with stock recovery, and TWRP). The only workable combination is to flash AOSP 8.1 phhusson (system-arm64-aonly-vanilla-nosu.) and Magisk .

I have been reading a lot of posts and seems 8xMax/ Enjoy Max should work with a number of GSI rom which is apparently not like my case.

I was wondering if any of you could give me some guidance on it.

Thank you !!!

**Comment by nation888** [comment]
CLUE;

After trying several GSI's on my 8x Max all seemed to have this back light issue combined with a false limited space issue. I tried Phhusson system-quack-arm64-ab-vanilla.img and backlight works. Still the false space issue.
