### ISSUE TITLE
Razer Phone 2: SMS, MMS, VoLTE Issues

### ISSUE THREAD

**Issue by Reznor7** [phhusson/treble_experimentations#1209]
I am attempting to get VoLTE, SMS, and MMS working correctly on my phone. 

Scenario #1: Phone set to GSM/WCDMA preferred
- able to send/receive sms and mms
- able to make/receive phone calls (non-VoLTE HD)

Scenario #2: I have ims-q.apk installed and the ims xml installed in /system/etc/permissions. Phone set to LTE only - IMS Status shows as registered
- able to receive sms
- **NOT** able to send sms
- able to send/receive mms
- able to make/receive phone calls (VoLTE HD)

With ims-q and ims xml **NOT** installed, and phone set to LTE only
- **NOT** able to receive sms/mms
- able to send sms/mms
- **NOT** able to make/receive phone calls (non-VoLTE HD) - as expected

I haven't grabbed any logcats, but if you would would like something specific, please let me know. I feel I'm close to getting the phone working 100%. This is the last remaining issue.

**Comment by Reznor7** [comment]
Never mind; I finally got it sorted!

**Comment by phhusson** [comment]
You don't have the only Razer Phone 2 in the world, I'm sure other people
would be interested to know how you fixed those issues.

**Comment by Reznor7** [comment]
Sorry about that. I pushed the ims xml file to /system/etc/permissions and installed the ims-q.apk. I then rebooted into TWRP and moved the org.codeaurora.ims (renamed it to this) folder from /data/app to /system/app. Everything has been working perfectly for the past day or so even though multiple reboots.

**Comment by lss4** [comment]
Actually with ims-q.apk as well as the xml, I find myself "lose" SIM card (No service) after a while, and there's no way to bring it back other than rebooting (toggling Airplane mode does not help). Additionally, the moment the SIM card was "lost", I'd receive a new copy of the last SMS I received, so I would immediately know that I should reboot the phone.

Uninstalling ims-q fixed that issue for me, and for some reasons, I could still receive SMS normally even across reboots. At present I only have the ims xml file systemlessly installed to /system/etc/permissions.

The phone is currently set to use LTE/WCDMA (WCDMA is what my carrier uses for 3G), from the default LTE/UMTS auto (PRL). It was set when I was diagnosing the issue above. Interestingly, for some reasons, this setting has persisted across reboots on Havoc 3.2 GSI which I'm currently running, while normally (at least with my old phones), this setting shouldn't persist even across a single toggle of Airplane mode.

**Comment by Reznor7** [comment]
I am on T-Mobile and have my phone set to GMS/WCDMA/LTE. SMS would get stuck at "Sending" until I moved the ims-q folder to /system/app.

**Comment by gdundee** [comment]
> Sorry about that. I pushed the ims xml file to /system/etc/permissions and installed the ims-q.apk. I then rebooted into TWRP and moved the org.codeaurora.ims (renamed it to this) folder from /data/app to /system/app. Everything has been working perfectly for the past day or so even through multiple reboots.

On my phone there is no app folder inside of system, should I create it?  Also, where did you get the xml file from?

**Comment by lss4** [comment]
> On my phone there is no app folder inside of system, but there is an app folder in /system/system, should I copy the app contents there and do I need to rename it from the org.codeaurora.ims-10Lnm6Hrg09WP4msVnXMhQ... Also, where did you get the xml file from, and what is the full file name? I'd greatly appreciate the help! Just let me know.

/system/system is for SaR (system-as-root). In that case, that would be /system/system/app.

Renaming is not necessary, but I rename it to make it match with the usual system app folder naming conventions.

And for the xml file, it should have already been there on newest GSIs, though I recall there's a flashable zip somewhere if you don't.

Note that you don't really need to put the files to actual system. You can do it systemlessly via Magisk if you already have a module active, by putting the installed ims folder to that module's system folder so it'll look like you've put it into the system folder. This way you can keep them across ROM/GSI updates. The only catch for this is that you must manually toggle VoLTE off then on to keep VoLTE working (when it works, you'll see a VoLTE icon).

**Comment by gdundee** [comment]
My XML file was already there.  I already tried putting it in the system/system/app folder, but now it's not even registering the sim card.  And settings keeps force closing when I try to look at my network settings.  Do I have to do it through magisk, or is it okay that I did it through TWRP by manually moving the folder?

**Comment by lss4** [comment]
> My XML file was already there. I already tried putting it in the system/system/app folder, but now it's not even registering the sim card. And settings keeps force closing when I try to look at my network settings. Do I have to do it through magisk, or is it okay that I did it through TWRP by manually moving the folder?

Can't be sure about direct installation to system, as I always do this on Magisk. Make sure the ims stuffs' permissions are correct (for files, it should be 644 or rw-r--r--).

By the way, are you using Verizon (or other similar carriers)? If so, the issue you're facing might be a different one.

**Comment by gdundee** [comment]
I am on AT&T with a Razer Phone 2.  I tried following the steps that others provided, but they did not work for me.  I took a random guess, and I got my phone sending/receiving sms!  Boot to TWRP recovery, mount the system partition, then from /data/app I copied the com.google.android.ims-o1t4F.... to the /system/system/app folder.
