### ISSUE TITLE
[Nubia Z18 mini] Backlight can't be set

### ISSUE THREAD

**Issue by phhusson** [phhusson/treble_experimentations#121]
cf https://github.com/phhusson/treble_experimentations/issues/119

**Comment by FydeSW** [comment]
I'm having the same problem, for now I managed by changing the value manually with a script.

echo 1000 > /sys/class/leds/lcd-backlight/brightness
chmod 444 /sys/class/leds/lcd-backlight/brightness

I also change permissions so the system can't change it back.

**Comment by phhusson** [comment]
Could you check https://github.com/phhusson/treble_experimentations/issues/128 ?

**Comment by FydeSW** [comment]
I checked but my problem seems different, the slider doesn't work at all, if I move it nothing happens, but if I set the number manually in /sys/class/leds/lcd-backlight/brightness the brightness changes as expected, and the values go from 0 to 4095, the higher the brighter, very predictable.

`cat /sys/class/leds/lcd-backlight/max_brightness`
returns 4095

I ran
`setprop persist.sys.qcom-brightness 4095`
but nothing changes.

**Comment by phhusson** [comment]
ok, please send me de-odexed stock system/frameworks/services.jar (or send
me the vdex perhaps I'll be able to extract it )

**Comment by Diimili** [comment]
when editing
`/sys/class/leds/lcd-backlight/brightness    `   
it works when it is lower than max_brightness,
but the brightness return to the value of
  `    /sys/class/leds/lcd-backlight/max_brightness     `
after lock screen and relock screen 
when editing 
  `    /sys/class/leds/lcd-backlight/max_brightness   `
it works , and 
`/sys/class/leds/lcd-backlight/brightness    `   
become the same value as max_brightness
and won't be changed after lock screen and relock screen
the screen become dark when max_brightness is from 1 to 254 
255-4095 keep the largest brightness
the default value of max_brightness is 4095 in AOSP

**Comment by Diimili** [comment]
the real max brightness is
`    /sys/class/leds/lcd-backlight/nubia_led/max_brightness    ` (255)
and
`    /sys/class/leds/lcd-backlight/wled/max_brightness    `(4095)
edit these two values won't change brightness

**Comment by FydeSW** [comment]
If you edit
`/sys/class/leds/lcd-backlight/brightness`
and you change permissions to 444 it won't change back to max, that's what I'm doing now.

**Comment by phhusson** [comment]
vdexExtractor segfaults on this services.vdex, so you'll need to de-odex the jar

**Comment by Diimili** [comment]
I decode framework-res.apk from stock rom. It'll be helpful .
[framework-res.zip](https://github.com/phhusson/treble_experimentations/files/2346092/framework-res.zip)

**Comment by Diimili** [comment]
de-odex services.vdex
[Smali_services-deodex.zip](https://github.com/phhusson/treble_experimentations/files/2346859/Smali_services-deodex.zip)

**Comment by phhusson** [comment]
Based on this de-odexed services, I'm pretty confident that the command mentioned before should work:

> setprop persist.sys.qcom-brightness 4095

Details:
Reading LightsService$LightImpl.smali shows that the setBrightness function has two code paths leading to setLightLocked, one for mId == 0 (== screen backlight), and in this case it does:
setScreenLightLocked(brightness & v0, 0, 0, 0, brightnessMode);

The only weirdness is about this & v0 (where v0 is android/os/PowerManager;->INTERNAL_BRIGHTNESS_ON).

Could you deodex framework.jar as well to check the value of this?

**Comment by Diimili** [comment]
I cannot find framework.odex in /system foilder
and framework.jar is an empty file only with mainfest.mf
when type "setprop persist.sys.qcom-brightness 4095" in android terminal , either no error showed , or nothing changed
here is the log
[adb.log](https://github.com/phhusson/treble_experimentations/files/2351409/adb.log)

**Comment by FydeSW** [comment]
> Based on this de-odexed services, I'm pretty confident that the command mentioned before should work

It does work! The first time I think I messed with files and permissions too much and it wasn't working, but now it works, sorry and thank you!

**Comment by FydeSW** [comment]
Here it is.
[prop.zip](https://github.com/phhusson/treble_experimentations/files/2351554/prop.zip)

**Comment by Diimili** [comment]
adding
` setprop persist.sys.qcom-brightness 4095 `
is OK.
but I cannot find this in build.prop of stock rom
[build.prop.txt](https://github.com/phhusson/treble_experimentations/files/2352300/build.prop.txt)
This issue can be closed if there is no other problems.
