### ISSUE TITLE
Fingerprint enrollment failing on Huawei Mediapad M5 since b213

### ISSUE THREAD

**Issue by fourofspades** [phhusson/treble_experimentations#1211]
Last working build was b212, since then, all build fail to enroll fingerprint.

and here is some logcat whilst trying to enroll (1 week expiry): https://pastebin.com/53jV1GZ0

Snippet: 
teecd : type=1400 audit(0.0:904): avc: denied { search } for name="sec_storage_data" dev="mmcblk0p64" ino=13 scontext=u:r:tee:s0 tcontext=u:object_r:teecd_data_file:s0 tclass=dir permissive=0
03-28 13:46:17.855 666 672 E teecd_vendor: mkdir /data/sec_storage_data/fp fail
03-28 13:46:17.857 831 975 E fpc_tac : fpc_tac_send_cmd failed with retval: -69
03-28 13:46:17.857 831 975 E fpc_fingerprint_hal: do_enroll_out failed -38
03-28 13:46:17.858 831 975 E fpc_fingerprint_hal: dsm_buf:dsm_fingerprint,912001004,sensor_id=0x3206,ChargerType=0,do_enroll: fpc_tac_end_enrol failed, index=-69
03-28 13:46:17.858 831 975 E fpc_fingerprint_hal:
03-28 13:46:17.858 831 975 D FingerprintDevice: onError(1), vendorCode(0)

**Comment by phhusson** [comment]
@tinloaf if it isn't your patch, then i guess it is this one:
https://github.com/phhusson/device_phh_treble/commit/dc8484b74fb928d400938d87b43e9a5417a1274c

**Comment by fourofspades** [comment]
If you want me to try anything out, or provide any more logs, more than happy to try and get this fixed, so it works with all devices.

**Comment by Montelion** [comment]
Same on Huawei P20 lite, do you still need logs?

**Comment by fourofspades** [comment]
This might be fixed in v215, not seeing the problem anymore, not done a full wipe, but have registered new fingerprints sucessfully.   Has something changed that might have fixed this?

**Comment by fourofspades** [comment]
Confirmed fixed in v215 clean install, enrollment works fine again.  Something fixed it.
