### ISSUE TITLE
Huawei fingerprint gestures defaulting to on makes registration cumbersome

### ISSUE THREAD

**Issue by fourofspades** [phhusson/treble_experimentations#1212]
The Huawei fingerprint gestures are a nice touch, but they should be disabled during registration, it's far too easy to perform a back gesture during registration.

The simplist fix would be to change the default value to off.

**Comment by phhusson** [comment]
I don't really understand how it makes registration cumbersome, but anyway I agree it should be disabled by default

**Comment by fourofspades** [comment]
Now working better.  It was previously very easy to do a back gesture that closed the page on setup.
