### ISSUE TITLE
AOSP 10.0 v214 not booting up on my S10+

### ISSUE THREAD

**Issue by zunaid321** [phhusson/treble_experimentations#1219]
Hey Sir! 

I hope you are having a good day. Your last build did boot on my S10+ but your latest release v214 is not booting up. It get stuck in the boot logo. Can you please try to look into the issue?

Thanks!

**Comment by phhusson** [comment]
If you're stuck you probably have adb working, so please generate a `adb logcat`

**Comment by zunaid321** [comment]
Hey! Thanks for the speedy reply.
I did try to collect a logcat but no devices are getting detected under adb.

**Comment by zunaid321** [comment]
So umm is there any hope?

**Comment by phhusson** [comment]
Try to boot gsi, then reboot into recovery, and retrieve /proc/last_kmsg

**Comment by zunaid321** [comment]
[phh214-Android10-arm64AB-last_kmsg-S10+.txt](https://github.com/phhusson/treble_experimentations/files/4416462/phh214-Android10-arm64AB-last_kmsg-S10%2B.txt)

@phhusson Sir here is the file!

**Comment by phhusson** [comment]
That's pretty weird.

If you flash v213 in-place without changing anything else, the device boots fine?

Also please redo the log, the same way, though with the phone folder (i usually take a pack of frozen beans and put my phone on it for 10 minutes), your logs is a bit noisy because DDR didn't keep all the bits

**Comment by zunaid321** [comment]
Which patch is Descendant X GSI is using?
That is booting fine in my phone.

**Comment by zunaid321** [comment]
Tried from 214 to 210 -> same problem

It gets stuck in the initial samsung logo.
It doesnt even go to the "android" logo.

@phhusson

**Comment by zunaid321** [comment]
Had to flash stock rom and did it over again.
It was the custom vendor that was messing it up!

**Comment by phhusson** [comment]
Hum so are you saying that it is now working? I don't understand

**Comment by zunaid321** [comment]
Yes bro! It's working now! Using the stock vendor of firmware CTC9!

**Comment by phhusson** [comment]
Okay cool, thanks.
