### ISSUE TITLE
Leagoo xrover shutsdown when you disconnect from charger

### ISSUE THREAD

**Issue by devrieshh** [phhusson/treble_experimentations#1237]
After installing  AOSP 10.0 v213 and reboot into it,the rom reboots emidiatly after disconnect from USB battery icon says -1;% even when there is 65%or more in it.

**Comment by phhusson** [comment]
What if you boot without charger?

**Comment by devrieshh** [comment]
I don't have the rom on my phone anymore,so I don't know for sure,but it booted,and after a few minutes it shuts down, always with-1%

**Comment by devrieshh** [comment]
i installed the newest ,AOSP 10.0 v215 it installed ok,but unfortunatly it has the same battery issue.
 -1% after booting without usb connection it shows logo and shuts down after a minute.
after rebooting connected it starts again

**Comment by devrieshh** [comment]
> What if you boot without charger?

**Comment by devrieshh** [comment]
i installed the newest ,AOSP 10.0 v215 it installed ok,but unfortunatly it has the same battery issue.
-1% .
After booting without usb connection it shows logo and shuts down after a minute.
When rebooting, connected on usb port computer,it starts again

**Comment by phhusson** [comment]
Battery gauge works fine when usb is connected?

**Comment by devrieshh** [comment]
what is that

**Comment by devrieshh** [comment]
ok problem solved,had to flash vendor.img from my leagooxrover stock rom
(flash rom,flash vendor,flash boot)
