### ISSUE TITLE
[Note 10+ snapdragon ] fingerprint enroll doesn't register finger

### ISSUE THREAD

**Issue by manofsteel2017** [phhusson/treble_experimentations#1244]
Both aren't that important but would be good to have fingerprint at last working.
Don't have logs. Can provide if really needed 
I tried to set setprop persist.sys.phh.samsung fingerprint 0

But that didn't work lol

**Comment by phhusson** [comment]
Pie or Q vendor?
That's ultrasonic sensor correct?
What's precise behaviour?


Le mer. 8 avr. 2020 à 22:41, manofsteel2017 <notifications@github.com> a
écrit :

**Comment by manofsteel2017** [comment]
I didn't get any vibration
I moved my finger everywhere lol
Only have option to set up or skip


Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by manofsteel2017** [comment]
Also for Q vendor

**Comment by phhusson** [comment]
Please test sys-test-fp-sec3.img

**Comment by manofsteel2017** [comment]
Flashed and tested
Still not working.

No vibration or anything when trying to set up finger
Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by phhusson** [comment]
exactly same behaviour?
Please provide logcat

Le jeu. 9 avr. 2020 à 15:23, manofsteel2017 <notifications@github.com> a
écrit :

**Comment by manofsteel2017** [comment]
[Log_2020-04-09_09-49-25.txt](https://github.com/phhusson/treble_experimentations/files/4456547/Log_2020-04-09_09-49-25.txt)

**Comment by phhusson** [comment]
This log is completely wrong, I don't know why.
There isn't a single reference to `phh` (case insensitive), which is pretty much impossible

1. You're sure you flashed correct image?
2. Please generate logs this way:
- try to enroll finger
- right after you pressed twice your finger, do:
`adb logcat -b all -d > log.txt`
And send log.txt here

**Comment by manofsteel2017** [comment]
Hey I wiped everything and flashed the IMG you sent and I was able to add finger after the step was completed.
Voice set up kept looping back to finger print
I had to run without gapps

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by phhusson** [comment]
Well you can bypass broken setup wizard with four corners bypass on first
screen of setup wizard:
Press top left corner then top right then bottom right them bottom left

So does fingerprint work after than enroll?

Le jeu. 9 avr. 2020 à 20:56, manofsteel2017 <notifications@github.com> a
écrit :

**Comment by manofsteel2017** [comment]
yeah dont mind the step up issue
yyeah fingerprint is working
thanks but  that build has issue though the multitask button dont work lol
went back to regular build
you can merge things on next build
oh any fix for flashlight
other that
you can close the ticket
________________________________

**Comment by phhusson** [comment]
ok great thanks
Fix commited in https://github.com/phhusson/platform_frameworks_base/commit/24b47f6cedf

Please open a new issue for flashlight
