### ISSUE TITLE
V215 -Mi 8 pro -Screen display

### ISSUE THREAD

**Issue by asmallbit** [phhusson/treble_experimentations#1248]
There is always a green circle on the screen and when you try to click some buttons under the circle,it can not be done.like the button 'terms' on this picture.
![Screenshot_20200409-235034](https://user-images.githubusercontent.com/57493581/78914425-f456f000-7abc-11ea-801a-4b87d3485d17.png)

**Comment by phhusson** [comment]
This green button is an artifact of under-display fingerprint.
If you reboot, it should disappear.
However, does under-display fingerprint work for you?

**Comment by asmallbit** [comment]
Thanks for you advice it has disappeared.and it doesn't work
