### ISSUE TITLE
Redmi Note 5a (ugglite)

### ISSUE THREAD

**Issue by zainarbani** [phhusson/treble_experimentations#125]
please add support for this device too, we have compiled oreo rom (crdroid 4.4) but camera not working (not kernel driver issue) maybe vendor/device issue.

Thanks

**Comment by phhusson** [comment]
Is that an OEM treble device?

Le dim. 22 juil. 2018 à 14:42, zainarbani <notifications@github.com> a
écrit :

**Comment by zainarbani** [comment]
i think no, maybe you can check on here:

vendor & device
https://github.com/muralivijay/android_device_xiaomi_ugglite
https://github.com/muralivijay/android_vendor_xiaomi_ugglite

**Comment by zainarbani** [comment]
seem Moto e5 play Lineage 15.1 had camera issue, also see your comment there :) you said already find out how to fix those issue. maybe you can help & support us

**Comment by phhusson** [comment]
Sorry, but I only support OEM Treble implementations

**Comment by phhusson** [comment]
(but then you might suggest to ask your treble dev to go on my telegram channel to discuss this with other people who ported treble to their devices)

**Comment by zainarbani** [comment]
okay, Thanks
