### ISSUE TITLE
Build error: Unable to open '[...]/CalculatorGoogle_intermediates/package.apk' for verification

### ISSUE THREAD

**Issue by CReimer** [phhusson/treble_experimentations#1252]
I tried compiling Quack Phh-Treble in a GApps NoSU variant. So I wouldn't have to replace Magisk Recovery with TWRP just to run unSU and replace it back with Magisk

I followed your README file instructions with the docker container. It feels a bit dated because of Ubuntu 16.04 but it seems to work fine for quite some time. Until it doesn't:

https://pastebin.com/SM9YXnVL

```build-dakkar.sh rr aosp10 arm64-ab-gapps-nosu``` 

The easiest way for me would be if you provided an arm64-ab-gapps-nosu build. But now since I came this far in the build process, I'd also like to figure out what went wrong and how to fix it.

**Comment by CReimer** [comment]
Okay. I messed up build-dakkar.sh parameters. "rr" shouldn't be there. Will try again later without "rr"

**Comment by CReimer** [comment]
```[ 78% 82542/104603] target Prebuilt: CalculatorGoogle (out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk)
FAILED: out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk
/bin/bash -c "(rm -f out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk ) && (cp \"vendor/opengapps/sources/all/app/com.google.android.calculator/23/nodpi/78000303.apk\" \"out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk\" ) && (if (zipinfo out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk 'lib/*.so' 2>/dev/null | grep -v ' stor ' >/dev/null) ; then out/soong/host/linux-x86/bin/zip2zip -i out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk -o out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk.tmp -0 'lib/**/*.so'  && mv -f out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk.tmp out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk ; fi ) && (if ! out/host/linux-x86/bin/zipalign -c  4 out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk >/dev/null ; then mv out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk.unaligned; out/host/linux-x86/bin/zipalign -f -p 4 out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk.unaligned out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk.aligned; mv out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk.aligned out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk; fi )"
Unable to open 'out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk' for verification
Unable to open 'out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk.unaligned' as zip archive
mv: bad 'out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk.aligned': No such file or directory
[ 78% 82543/104603] target Prebuilt: CalendarGooglePrebuilt (out/target/product/phhgsi_arm64_ab/obj/APPS/CalendarGooglePrebuilt_intermediates/package.apk)
FAILED: out/target/product/phhgsi_arm64_ab/obj/APPS/CalendarGooglePrebuilt_intermediates/package.apk
/bin/bash -c "(rm -f out/target/product/phhgsi_arm64_ab/obj/APPS/CalendarGooglePrebuilt_intermediates/package.apk ) && (cp \"vendor/opengapps/sources/all/app/com.google.android.calendar/21/nodpi/2016546753.apk\" \"out/target/product/phhgsi_arm64_ab/obj/APPS/CalendarGooglePrebuilt_intermediates/package.apk\" ) && (if (zipinfo out/target/product/phhgsi_arm64_ab/obj/APPS/CalendarGooglePrebuilt_intermediates/package.apk 'lib/*.so' 2>/dev/null | grep -v ' stor ' >/dev/null) ; then out/soong/host/linux-x86/bin/zip2zip -i out/target/product/phhgsi_arm64_ab/obj/APPS/CalendarGooglePrebuilt_intermediates/package.apk -o out/target/product/phhgsi_arm64_ab/obj/APPS/CalendarGooglePrebuilt_intermediates/package.apk.tmp -0 'lib/**/*.so'  && mv -f out/target/product/phhgsi_arm64_ab/obj/APPS/CalendarGooglePrebuilt_intermediates/package.apk.tmp out/target/product/phhgsi_arm64_ab/obj/APPS/CalendarGooglePrebuilt_intermediates/package.apk ; fi ) && (if ! out/host/linux-x86/bin/zipalign -c  4 out/target/product/phhgsi_arm64_ab/obj/APPS/CalendarGooglePrebuilt_intermediates/package.apk >/dev/null ; then mv out/target/product/phhgsi_arm64_ab/obj/APPS/CalendarGooglePrebuilt_intermediates/package.apk out/target/product/phhgsi_arm64_ab/obj/APPS/CalendarGooglePrebuilt_intermediates/package.apk.unaligned; out/host/linux-x86/bin/zipalign -f -p 4 out/target/product/phhgsi_arm64_ab/obj/APPS/CalendarGooglePrebuilt_intermediates/package.apk.unaligned out/target/product/phhgsi_arm64_ab/obj/APPS/CalendarGooglePrebuilt_intermediates/package.apk.aligned; mv out/target/product/phhgsi_arm64_ab/obj/APPS/CalendarGooglePrebuilt_intermediates/package.apk.aligned out/target/product/phhgsi_arm64_ab/obj/APPS/CalendarGooglePrebuilt_intermediates/package.apk; fi )"
Unable to open 'out/target/product/phhgsi_arm64_ab/obj/APPS/CalendarGooglePrebuilt_intermediates/package.apk' for verification
Unable to open 'out/target/product/phhgsi_arm64_ab/obj/APPS/CalendarGooglePrebuilt_intermediates/package.apk.unaligned' as zip archive
mv: bad 'out/target/product/phhgsi_arm64_ab/obj/APPS/CalendarGooglePrebuilt_intermediates/package.apk.aligned': No such file or directory
16:35:01 ninja failed with: exit status 1```

Unfortunately the same problem

**Comment by wlya** [comment]
Same issue here.
`
$. build/envsetup.sh
$lunch treble_arm64_bgS_userdebug
$make -j1 systemimage
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=10
TARGET_PRODUCT=treble_arm64_bgS
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.15.0-96-generic-x86_64-Ubuntu-16.04.6-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=QQ2A.200405.005
OUT_DIR=out
============================================
09:31:59 Disallowed PATH tool "locale" used: []string{"locale", "-a"}
09:31:59 See https://android.googlesource.com/platform/build/+/master/Changes.md#PATH_Tools for more information.
09:32:03 Disallowed PATH tool "locale" used: []string{"locale", "-a"}
09:32:03 See https://android.googlesource.com/platform/build/+/master/Changes.md#PATH_Tools for more information.
[  0% 1/22058] target Prebuilt: CalculatorGoogle (out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk)
FAILED: out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk
/bin/bash -c "(rm -f out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk ) && (cp \"vendor/opengapps/sources/all/app/com.google.android.calculator/23/nodpi/78000303.apk\" \"out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk\" ) && (if (zipinfo out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk 'lib/*.so' 2>/dev/null | grep -v ' stor ' >/dev/null) ; then out/soong/host/linux-x86/bin/zip2zip -i out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk -o out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk.tmp -0 'lib/**/*.so'  && mv -f out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk.tmp out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk ; fi ) && (if ! out/host/linux-x86/bin/zipalign -c  4 out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk >/dev/null ; then mv out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk.unaligned; out/host/linux-x86/bin/zipalign -f -p 4 out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk.unaligned out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk.aligned; mv out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk.aligned out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk; fi )"
Unable to open 'out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk' for verification
Unable to open 'out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk.unaligned' as zip archive
mv: bad 'out/target/product/phhgsi_arm64_ab/obj/APPS/CalculatorGoogle_intermediates/package.apk.aligned': No such file or directory
09:32:14 ninja failed with: exit status 1
`

**Comment by wlya** [comment]
@CReimer 
Using this command to fix this error.
```repo forall -r '.*opengapps.*' -c 'git lfs fetch && git lfs checkout'```

**Comment by CReimer** [comment]
Thanks. That fixed it.

**Comment by AllCach** [comment]
didn't worked((
