### ISSUE TITLE
[Samsung Galaxy Tab S3] AOSP 10 - won't Boot

### ISSUE THREAD

**Issue by cruzzer** [phhusson/treble_experimentations#1255]
**Samsung Galaxy Tab S3 [SM-T820]**

I can successfully flash and boot AOSP 9.0 (e.g. v117, v119, v123), but not AOSP 10.0 (e.g. v210,  v215). Treble was setup using Valera1978's [post](https://forum.xda-developers.com/galaxy-tab-s3/development/project-treble-based-android-9-0-t3918235) over at xda-developers.

Attached is the logcat output. Let me if you need more information or want me to try something. Thank you for all your efforts

[galax_s3_aosp10.log](https://github.com/phhusson/treble_experimentations/files/4467226/galax_s3_aosp10.log)

**Comment by phhusson** [comment]
I think the issue is this:
```
12-18 14:28:39.618  1383  1383 E APM::Serializer: deserialize: libxml failed to resolve XIncludes on /vendor/etc/audio_policy_configuration.xml document.
12-18 14:28:39.621  1383  1383 E APM::Serializer: deserialize: no source found with name=USB Device In
```

Since this is a community Treble and not an OEM Treble, you'll need to fix it on your own (though I sure I can help)

**Comment by cruzzer** [comment]
Merci Pierre-Hugues for your response. I'm now looking at another setup and will let this rest for now.

For people reading this issue, I can confirm that multiple AOSP 9.0 versions of phhusson install and boot successfully on the Galaxy Tab S3. The recents list did end up being blank. I had the same behavior on an unrelated ROM. I suspect that is do to the "treble" setup by Valera1978. I did not do further testing then that.

Thank you
