### ISSUE TITLE
Bootloop gsi 215 elephone

### ISSUE THREAD

**Issue by te1401** [phhusson/treble_experimentations#1270]
hello I tried to install gsi v215 but it remains stuck on Android image I was unable to connect the smartphone in adb but I found this log in twpr
[recovery.log](https://github.com/phhusson/treble_experimentations/files/4511470/recovery.log)

**Comment by SevralTimes** [comment]
It's a recovery log)

**Comment by te1401** [comment]
Hello Good morning, thanks for the reply.  by chance can you tell me how to recover a log cat because when I install the GSI and connect the smartphone to the PC it does not recognize it I tried in every way even to install new while the drivers
