### ISSUE TITLE
[G610F] No camera and lots of reboots in v216

### ISSUE THREAD

**Issue by needpandora** [phhusson/treble_experimentations#1284]
I am on J7 Prime v216-arm64-aonly-vanilla with pico Gapps. I took some logs. Can you see any problems, and if so can you pinpoint them? Thanks.

1. [Camera.txt](https://github.com/phhusson/treble_experimentations/files/4593854/Camera.txt)

2. [Random_Reboots.txt](https://github.com/phhusson/treble_experimentations/files/4593863/Random_Reboots.txt)

![OnPaste 20200507-182438](https://user-images.githubusercontent.com/64700653/81313130-1ded4200-9090-11ea-821f-d1575d2e1b5a.png)

**Comment by at644** [comment]
Ive also faced the problem with random reboots on my J6. Guessing thats an Exynos problem which hasn't been diagnosed yet.
