### ISSUE TITLE
android Q v216 charge offline mt6763 

### ISSUE THREAD

**Issue by nattawut7684** [phhusson/treble_experimentations#1299]
I'm using ulefone power 5. I want to know if there is a vendor code similar to vendor.qti.hardware.alarm@1.0.hal.  I tried this one and it doesn't work.  Or when there is a way to code  What to do?  Please those who know.I'm sorry that English is not good enough to use google translate.I need to use the charger to turn off the device.  Because if you turn on the device, afraid of the bomb

**Comment by phhusson** [comment]
Do you know what vendor.qti.hardware.alarm does? It's a bit weird
referencing a feature by NOT describing it

**Comment by nattawut7684** [comment]
> I'm using ulefone power 5. I want to know if there is a vendor code similar to [vendor.qti.hardware.alarm@1.0.hal](mailto:vendor.qti.hardware.alarm@1.0.hal). I tried this one and it doesn't work. Or when there is a way to code What to do? Please those who know.I'm sorry that English is not good enough to use google translate.I need to use the charger to turn off the device. Because if you turn on the device, afraid of the bomb
