### ISSUE TITLE
Can't install to DOOGEE S95 

### ISSUE THREAD

**Issue by miyoken** [phhusson/treble_experimentations#1307]
I tried to install custom rom below.
https://github.com/phhusson/treble_experimentations/releases

But install was failed and my phone doesn't boot.
I didn't backup system image.
Does anyone have system image of DOOGEE S95 or custom rom what  can install to DOOGEE S95?

**Comment by phhusson** [comment]
How did you install it precisely? Which variant?

Le dim. 10 mai 2020 à 17:18, Kenichi Miyoshi <notifications@github.com> a
écrit :

**Comment by miyoken** [comment]
Thank you for reply Mr.phhusson.
I tried installed below via "Flash the GSI USing ADB Fastboot Method".

- system-quack-arm-ab-vanilla.img
- system-quack-arm-aonly-vanilla.img
- system-quack-arm64-ab-gapps.img
- system-quack-arm64-ab-vanilla.img
- system-quack-arm64-aonly-gapps.img
- system-quack-arm64-aonly-vanilla.img

I referenced this page.
https://www.getdroidtips.com/how-to-install-generic-system-image-on-project-treble-devices-phh-treble/

command is below.
1. adb reboot bootloader
2. fastboot flashing unlock (I coulodn't use oem unlock on my device)
3. devicesfastboot flash system xxxx.img
4. fastboot flashing lock (Orange state occurred when reboot, if unlock device)
5. fastboot reboot

Please help me.

**Comment by phhusson** [comment]
Did you flash vbmeta partition?

Le dim. 10 mai 2020 à 23:45, Kenichi Miyoshi <notifications@github.com> a
écrit :

**Comment by miyoken** [comment]
No I didn't.
I think I need vbmeta.img for flash but I don't have it.
Where can I get vbmeta.img?

**Comment by phhusson** [comment]
you can try with
https://dl.google.com/developers/android/qt/images/gsi/vbmeta.img

**Comment by miyoken** [comment]
Thank you.

I tried below command.

```
https://source.android.com/setup/build/gsi?hl=ja#flashing-gsis
fastboot --disable-verification flash vbmeta vbmeta.img
fastboot erase system
fastboot flash system system.img
fastboot -w
Fastboot reboot
```

But orange state occurred when reboot device.
> Orange State
> Your devices has been unlocked and can't be trusted
> Your devices will boot in 5 seconds

**Comment by phhusson** [comment]
Don't do `fastboot -w`. Reboot into recovery and do factory reset from there

Le mar. 12 mai 2020 à 07:35, Kenichi Miyoshi <notifications@github.com> a
écrit :

**Comment by miyoken** [comment]
Thank you phhussion.

I tried below command again after factory reset, "android" logo appeared.
`fastboot flashing unlock
fastboot flashing unlock_critical
fastboot --disable-verification flash vbmeta vbmeta.img
fastboot erase system
fastboot flash system system.img
Fastboot reboot`

But it didn’t proceed to next display from "android" logo.

**Comment by phhusson** [comment]
Now you should have adb to make logs.

Le dim. 17 mai 2020 à 03:00, Kenichi Miyoshi <notifications@github.com> a
écrit :

**Comment by miyoken** [comment]
Dear phhussion.
I succeed boot at latest "system-quack-arm64-ab-gapps.img"!
Thank you.
