### ISSUE TITLE
Video in latest chrome

### ISSUE THREAD

**Issue by Graviter** [phhusson/treble_experimentations#1316]
Meizu m8, arm64a, vendor 8.1. aosp/aosp based gsi.
Chrome 74.0.3729.136 all videos work fine. Newest chrome version/dev/beta/canary black screen/errors on some sites. But web youtube work.
Log https://drive.google.com/file/d/1DJ7xyUWpE9O40X7sWZRUUDh1qol_tgCS/view

**Comment by tmvkrpxl0** [comment]
how about closing this
