### ISSUE TITLE
[Huawei P20 lite] Laggy animations

### ISSUE THREAD

**Issue by Dekamir** [phhusson/treble_experimentations#132]
**Reproduction:**
Launching overview
Switching to an app from overview
Quick switching (via double tap)
Closing overview
Launching an app
IME opening
Pop-up window

Happens on all Treble ROMs except AOSiP and Pixel Experience.

**Comment by Dil3mm4** [comment]
[SurfaceFlinger dumpsys](https://pastebin.com/p7EiBM0F)
[gfxinfo dumpsys](https://pastebin.com/pSDW1ufX)

**Comment by Dil3mm4** [comment]
This is ugly and untested, but maybe, if Quickstep it's using snapshots it could help reducing the lags over overview animation

https://github.com/Descendant/frameworks_base/commit/b7ddb4cee8716682a829d34f0c4aa4ab6591a55c

**Comment by phhusson** [comment]
Let's close that old thing, even though I'm pretty sure this has never been fixed.
