### ISSUE TITLE
Xiaomi Redmi Note 8 Pro (begonia) mediatek AVC decoder

### ISSUE THREAD

**Issue by timbortnik** [phhusson/treble_experimentations#1322]
Running 216 securized over latest global stock pie vendor, I've got an issue with facebook videos in Chrome
```
05-18 19:04:35.067  4112  4210 I cr_MediaCodecBridge: create MediaCodec video decoder, mime video/avc
05-18 19:04:35.068  4112  4210 W MediaCodec-JNI: try to release MediaCodec from JMediaCodec::~JMediaCodec()...
05-18 19:04:35.068  4112  4210 W MediaCodec-JNI: done releasing MediaCodec from JMediaCodec::~JMediaCodec().
05-18 19:04:35.069  4112  4210 E cr_MediaCodecUtil: Failed to create MediaCodec: video/avc, codecType: 0
05-18 19:04:35.069  4112  4210 E cr_MediaCodecUtil: java.lang.IllegalArgumentException: Failed to initialize video/avc, error 0xfffffffe
05-18 19:04:35.069  4112  4210 E cr_MediaCodecUtil: 	at android.media.MediaCodec.native_setup(Native Method)
05-18 19:04:35.069  4112  4210 E cr_MediaCodecUtil: 	at android.media.MediaCodec.<init>(MediaCodec.java:1865)
05-18 19:04:35.069  4112  4210 E cr_MediaCodecUtil: 	at android.media.MediaCodec.createDecoderByType(MediaCodec.java:1810)
05-18 19:04:35.069  4112  4210 E cr_MediaCodecUtil: 	at org.chromium.media.MediaCodecUtil.a(PG:17)
05-18 19:04:35.069  4112  4210 E cr_MediaCodecUtil: 	at org.chromium.media.MediaCodecBridgeBuilder.createVideoDecoder(PG:3)
05-18 19:04:35.070  8093  8560 E chromium: [ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"video decoder reinitialization failed"}
05-18 19:04:35.071  8093  8112 E chromium: [ERROR:batching_media_log.cc(35)] MediaEvent: {"pipeline_error":3}
05-18 19:04:35.074  3910  4046 D         : PlayerBase::stop() from IPlayer

```
The workaround that fixed the issue was to comment out AVC decoder in /vendor/etc/media_codecs_mediatek_video.xml

What would be the best way to apply this or similar fix in GSI?

**Comment by phhusson** [comment]
This isn't a fix.
You're disabling the hardware video decoding altogether, which is a bad idea for a huge number of reasons.
So let's fix the hardware decoder.

This log is unusable, it just says hardware decoder doesn't work, which isn't helpful. Could you give me actual logs?

**Comment by timbortnik** [comment]
What do I need to do to get actual logs?

**Comment by phhusson** [comment]
Just usual adb logcat

Le lun. 18 mai 2020 à 19:46, Tim Bortnik <notifications@github.com> a
écrit :

**Comment by timbortnik** [comment]
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/4646348/logcat.txt)

**Comment by phhusson** [comment]
Okay, download https://treble.phh.me/test-omx-chrome-mtk-libstagefright.32.so and push it to /system/lib/libstagefright.so

and download https://treble.phh.me/test-omx-chrome-mtk-libstagefright.64.so and push it to /system/lib64/libstagefright.so and try again
No matter whether it starts working or not, do a log after trying.

**Comment by timbortnik** [comment]
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/4646783/logcat.txt)
Did not help - a full-screen white flash appears, then stuck as before

**Comment by phhusson** [comment]
Was the full-screen white flash there before?

**Comment by timbortnik** [comment]
Full-screen did not flash before, otherwise looks the same from ui.

To test a notion of disabling mtk-avc is a pure evil, I did the following:
- captured top with AVC disabled, Chrome HW video decoding acceleration enabled:
```  PID USER         PR  NI VIRT  RES  SHR S[%CPU] %MEM     TIME+ ARGS                                                    
 4287 u0_a89       10 -10 1.7G 282M 237M S 55.3   4.9   2:23.29 com.android.chrome:privileged_process0
 4435 u0_i2        10 -10 1.7G 175M 100M S 42.3   3.0   1:53.20 com.android.chrome:sandboxed_process0:org.chromium.cont+
  892 system       -2  -8 1.0G  53M  39M R 40.0   0.9  15:10.36 surfaceflinger
  835 system       -3  -8 375M  12M  12M S 26.3   0.2   8:38.29 android.hardware.graphics.composer@2.1-service
  972 mediacodec   20   0 564M  26M  16M S 22.0   0.4   1:03.12 media.codec hw/android.hardware.media.omx@1.0-service
```
- captured top with Chrome HW video decoding acceleration disabled:
```  PID USER         PR  NI VIRT  RES  SHR S[%CPU] %MEM     TIME+ ARGS                                                    
 4990 u0_a89       20   0 1.6G 223M 187M S 45.6   3.9   0:26.62 com.android.chrome:privileged_process0
  892 system       -2  -8 1.0G  51M  39M R 43.0   0.8  16:29.66 surfaceflinger
 5065 u0_i7        20   0 1.6G 143M  89M S 36.3   2.5   0:28.62 com.android.chrome:sandboxed_process0:org.chromium.cont+
  835 system       -3  -8 374M  12M  12M S 27.3   0.2   9:15.57 android.hardware.graphics.composer@2.1-service
  972 mediacodec   20   0 564M  22M  14M S 22.3   0.3   1:21.44 media.codec hw/android.hardware.media.omx@1.0-service
  968 media        20   0 135M  25M  17M S 15.0   0.4   0:07.99 mediaserver
 1609 audioserver  20   0  89M  22M  13M S  9.3   0.3   0:37.24 android.hardware.audio@4.0-service-mediatek
 1404 radio        20   0 1.1G  48M  39M S  8.3   0.8  11:19.13 mtkfusionrild -l libmtk-ril.so
```
Visual difference - with just AVC disabled, video is smooth

**Comment by phhusson** [comment]
Ok looking at the logs, it's just that my change wasn't valid.
Try those:
https://treble.phh.me/test2-omx-chrome-mtk-libstagefright.32.so => /system/lib/libstagefright.so
https://treble.phh.me/test2-omx-chrome-mtk-libstagefright.64.so => /system/lib64/libstagefright.so

**Comment by timbortnik** [comment]
Same issue as with first test libs visually
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/4649304/logcat.txt)

**Comment by phhusson** [comment]
Grmbl I'm stil fighting with ubsan sorry
https://treble.phh.me/test3-omx-chrome-mtk-libstagefright.64.so =>
/system/lib64/libstagefright.so
https://treble.phh.me/test3-omx-chrome-mtk-libstagefright.32.so =>
/system/lib/libstagefright.so

Le mar. 19 mai 2020 à 11:06, Tim Bortnik <notifications@github.com> a
écrit :

**Comment by timbortnik** [comment]
UI - same
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/4650092/logcat.txt)

**Comment by phhusson** [comment]
Okay, that's progress:
05-19 13:49:09.905  9096  9234 E ACodec  : Managed to allocate 4
buffers (-1 extra)

Though I'm still fighting ubsan.
New tests:
https://treble.phh.me/test4-omx-chrome-mtk-libstagefright.32.so =>
/system/lib/libstagefright.so
https://treble.phh.me/test4-omx-chrome-mtk-libstagefright.64.so =>
/system/lib64/libstagefright.so

I've just noticed you're using fake properties (either through
Securize or magisk hide props). Could you test without those?
I'm thinking Chrome might trigger different behaviour based on
reported Android version, and you report Android 9.

**Comment by timbortnik** [comment]
Properties - just securize, no root/magisk, and it's a bit scary to toggle secureze unless fresh backup is ready. I can reflash clean rooted 216, if absolutely necessary, but would like to avoid this as much as possible.
Latest test libs behave just as regular ones from UX point
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/4650547/logcat.txt)

**Comment by timbortnik** [comment]
I wonder, is it really that bad to fall back to OMX.google.h264.decoder ?
Attaching a log with disable mtk avc (test libs)
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/4650619/logcat.txt)

**Comment by phhusson** [comment]
This issue could be related to https://github.com/bromite/bromite/issues/445
Could you try with bromite 83.0.4103.46?

**Comment by timbortnik** [comment]
Behavior for Bromite, Chrome stable and Chrome beta is the same.
The vimeo referenced in the ticket is just smarter than FB - it shows a message that the player crashed.
All 3 play everything just fine with google codec

**Comment by timbortnik** [comment]
Discovered that the issue does not happen in Firefox and Webview.
While Firefox is a different browser, webview makes me wonder, was this split justified by chrome bugs going out of control? https://www.androidpolice.com/2019/10/24/android-10-no-longer-uses-chrome-app-to-render-pages-inside-apps/?amp

**Comment by timbortnik** [comment]
A logcat for https://vimeo.com/channels/staffpicks/323783503 playing fine in Firefox.
Could sepolicy be in charge?
[logcat2.txt](https://github.com/phhusson/treble_experimentations/files/4655063/logcat2.txt)

CPUutilization looks worse than in chrome with sw decoder
```  PID USER         PR  NI VIRT  RES  SHR S[%CPU] %MEM     TIME+ ARGS                                                    
10417 u0_a215      10 -10  10G 447M 279M R 92.0   7.8   1:52.59 org.mozilla.firefox
10605 u0_a215      10 -10 5.3G 117M  85M S 27.0   2.0   0:20.41 org.mozilla.firefox:media
  876 system       -2  -8 1.0G  51M  36M S 24.3   0.8  34:29.38 surfaceflinger
 1004 mediacodec   20   0 113M  19M  13M S 19.6   0.3   1:28.56 media.codec hw/android.hardware.media.omx@1.0-service
  833 system       -3   0 355M  11M  11M S 13.0   0.1  20:46.70 android.hardware.graphics.composer@2.1-service
 2855 u0_a163      20   0 6.5G 213M 140M S 10.3   3.7   2:22.48 app.greyshirts.firewall
 1613 audioserver  20   0  90M  20M  10M S  7.3   0.3   1:20.46 android.hardware.audio@4.0-service-mediatek
```

**Comment by timbortnik** [comment]
I moved forward and upgraded to global beta Q vendor. 
https://forum.xda-developers.com/redmi-note-8-pro/how-to/miui-11-0-1-0-global-rn8p-android-10-t4066603 https://bigota.d.miui.com/V11.0.1.0.QGGMIXM/miui_BEGONIAGlobal_V11.0.1.0.QGGMIXM_44690b4daa_10.0.zip
This issue does not exist with this vendor.
The only reasonable outcome is to assume the bug is vendor-specific.
Thank you @phhusson !
