### ISSUE TITLE
Meizu 16T bootloops

### ISSUE THREAD

**Issue by essoojay** [phhusson/treble_experimentations#1324]
Meizu 16T bootloops after Android 9 or 10 installation. Disabled boot verify, installed Magisk, failed to boot. It bootloops endlessly.

Treble Supported on Phone
Tried A and AB
Flashed 216 dirty on Flyme 8.0.0.1A
Flashed vbmeta.img and boot.img from stock,  both TWRP and Fastboot. No way! Always bootloop.

Direct Google GSI 10 and 11 flashed successfully by vbmeta.img and then system.img

Tried other GSI ROMs like Crao, Lineage unofficial, PHh ..all bootloops

Anyone know what am doing wrong? 

Thanks

**Comment by essoojay** [comment]
My bad, Meizu 16T shipped with android 9+ hence GSI AB required. Flashed AB and all is fine!
Please close!

**Comment by UesugiErii** [comment]
@essoojay 
Hi，I tried many times, and I still cant install android10 on meizu16T, can you tell me how to install?
what is boot.img and vbmeta.img, how to get and use?
