### ISSUE TITLE
Redmi 7A Android 10 media issues

### ISSUE THREAD

**Issue by AyronOliveira** [phhusson/treble_experimentations#1325]
Hi
I'm facing some issues with android 10 gsi ROM's. Some music player apps don't show and organize my musics correctly (empty album list or music list). Now I currently using Lineageos 17.1 GSI by Andy Yan, but I've also tested with your AOSP 10 GSI, and has same issue. I'm using the latest vendor for my phone (Pie vendor). On android Pie GSI ROM's I don't have that issues
![Screenshot_20200519-155218_M�sica](https://user-images.githubusercontent.com/65622438/82367327-0136ff80-99ea-11ea-807a-578eaa24d613.png)
![Screenshot_20200519-155407_M�sica](https://user-images.githubusercontent.com/65622438/82367333-0300c300-99ea-11ea-9df1-1fc231a79e53.png)

**Comment by KhushrajRathod** [comment]
Please explain how, or why you think this is the OS's fault. It will help in fixing the issue if there is one.

**Comment by AyronOliveira** [comment]
Hi. Thank's for the reply
 I think it's OS related because I've tried four GSI ROM's based on android 10 (AOSP 10, Lineage OS 17.1, CAOS and LOSQ) and all them have the same issue with music player. The default Lineage music player (Eleven) and Aosp music player show the album list empty. I can play music, but it can't organize and access music by Artist>Album>Music, how this fault is across various ROM's based on android 10, and android 9 GSI ROM's don't have this issue, I think it's related to media provider service, I've seen in logcat some errors related to "SqLite invalid colum".
I've attached the logcat part related to the error when I try to open the artist>album list in Lineage music app. It's seem to be media provider related.
[logcat music app.txt](https://github.com/phhusson/treble_experimentations/files/4686137/logcat.music.app.txt)

**Comment by AyronOliveira** [comment]
My device use Arm32 binder 64 AB partition ROM's

**Comment by KhushrajRathod** [comment]
Alright could you give an example of a music player that has this issue from either f-droid or goolag play store

**Comment by AyronOliveira** [comment]
AOSP Music+

**Comment by KhushrajRathod** [comment]
Ok send a sample album/link to somewhere I could download a no copyright album, so I can test this

**Comment by AyronOliveira** [comment]
https://www.bensound.com/bensound-music/bensound-summer.mp3

**Comment by KhushrajRathod** [comment]
#ItWorksOnMyMachine, I'm using almost the same setup as yours, Redmi 7A with AOSP GSI v217. Try using AOSP v217 instead of lineage

![photo_2020-05-27_10-34-02](https://user-images.githubusercontent.com/44947946/82979830-a878ef80-a005-11ea-8c8e-07738d4aea30.jpg)
![photo_2020-05-27_10-34-05](https://user-images.githubusercontent.com/44947946/82979832-aa42b300-a005-11ea-9475-a778e7e70489.jpg)

@phhusson Please close

**Comment by KhushrajRathod** [comment]
@AyronOliveira As a Side note, you can download the latest fastboot zip from [here](https://mirom.ezbox.idv.tw/en/phone/pine/), this links to the official MIUI download, you could flash the vendor image that's inside the fastboot zip

**Comment by mehedigapp** [comment]
I have arm aonly device, in this phone most of the gsi rom stuck
bootanimation means when booting it showing only bootanimation and not pass
it. I don't no what is problem and how to fix.

**Comment by mehedigapp** [comment]
I have arm aonly device, in this phone most of the gsi rom stuck
bootanimation means when booting it showing only bootanimation and not pass
it. I don't no what is problem and how to fix.

**Comment by KhushrajRathod** [comment]
> I have arm aonly device, in this phone most of the gsi rom stuck bootanimation means when booting it showing only bootanimation and not pass it. I don't no what is problem and how to fix.

Not the correct place to ask, open a new issue

**Comment by AyronOliveira** [comment]
Ok. Thank's to the support!
