### ISSUE TITLE
[Xiaomi MIX 2S] Bluetooth audio not working in LineageOS since v22

### ISSUE THREAD

**Issue by notsyncing** [phhusson/treble_experimentations#133]
Hello, recently I found the bluetooth audio stopped working, logs complaining about `A2DP profile is not ready, return error`. After some work, I found the commit 

```
e0578a08008296e61703a9b0d438ce082bdbb8da 
"audiopolicy: update APM to use custom audio policy configuration "
```

in https://github.com/LineageOS/android_frameworks_av (https://github.com/LineageOS/android_frameworks_av/commit/e0578a08008296e61703a9b0d438ce082bdbb8da)

This commit causes APM to load config from `/vendor/etc/audio/` instead of `/vendor/etc`, thus breaks bluetooth audio on my device. Revert this makes bt audio work again.

AOSP did not have this commit, so I guess it works in aosp.

Though I think this should blame xiaomi's buggy vendor implementation, but I'm wondering if there was anything we could do? Should I maintain a fork, or submit a revert to LineageOS? Thanks very much!

**Comment by bgcngm** [comment]
Here: https://review.lineageos.org/#/c/LineageOS/android_device_xiaomi_polaris/+/222603/

If you want to stick to common audio policy config ( /vendor/etc/audio_policy_configuration.xml ), then you can simply add this hax in init.rc `mount none /vendor/lost+found /vendor/etc/audio bind`

**Comment by bgcngm** [comment]
@notsyncing  the second hax was confirmed to be working. I am still waiting for confirmation about the linked one (which I prefer), tho.

**Comment by notsyncing** [comment]
@bgcngm Thanks very much for this fix! But the linked one looks the same as your second hax, so which one did you need to confirm?

**Comment by bgcngm** [comment]
It turned out that the preferred one doesn't quite work.

**Comment by mjevange** [comment]
Do we know which of these fixes is confirmed working?

**Comment by mjevange** [comment]
@notsyncing I can confirm that by using /vendor/etc/audio_policy_configuration.xml BT media audio if working again for me. This fix should be implemented here

**Comment by rbuehlma** [comment]
Adding
`mount -o bind /vendor/lost+found /vendor/etc/audio || true`
at the end of /system/bin/rw-system.sh
solves the issue for me as well. Could this be included in the rom or is there a reason against?

**Comment by notsyncing** [comment]
Today I see this: https://github.com/phhusson/device_phh_treble/pull/26
This should fix the issue.

**Comment by mansonstein** [comment]
> Adding
> `mount -o bind /vendor/lost+found /vendor/etc/audio || true`
> at the end of /system/bin/rw-system.sh
> solves the issue for me as well. Could this be included in the rom or is there a reason against?

Solve on MI MIX 3!
