### ISSUE TITLE
Honor View 10 -  Fingerprint sensor stopped working with v216

### ISSUE THREAD

**Issue by CReimer** [phhusson/treble_experimentations#1330]
With v216 my fingerprint sensor stopped working. Android tells me to add fingerprints, but I already had fingerprints registered with v215. When I try to register a fingerprint and it tells me to touch the sensor now, nothing happens.

Although fingerprint gestures work fine

**Comment by CReimer** [comment]
Downgrading to 215 did not fix it. Any idea what to look out for in logcat? It's pretty busy and while touching the sensor nothing shows up related to the sensor

**Comment by CReimer** [comment]
Unfortunately still broken in v217pre

Here's a full logcat of my device: https://gist.github.com/CReimer/ba7024b7bc3171be70c4049d3c7972a0

**Comment by phhusson** [comment]
Is that logcat after trying to enroll fingerprint?

**Comment by CReimer** [comment]
I'm not 100% sure. But just now while trying to create another logcat it works again fine. I really don't know what went wrong until now.

But since my fingerprint sensor seems to work for now this issue can be closed.

I'll reopen it, if the problem occurs again.

Thanks
