### ISSUE TITLE
Fingerprint broken on Realme X2 pro 

### ISSUE THREAD

**Issue by sathish2026** [phhusson/treble_experimentations#1341]
Fingerprint icon shows up but not registering with Realme UI android 10 vendor. Latest aosp gsi
[fp.txt](https://github.com/phhusson/treble_experimentations/files/4710376/fp.txt)

**Comment by GT020** [comment]
Ya, no response by fp but it works on stock ui with magisk too

**Comment by phhusson** [comment]
How do I do the upgrade?

**Comment by GT020** [comment]
> How do I do the upgrade? Le lun. 1 juin 2020 à 17:17, gaurav <notifications@github.com> a écrit :
> […](#)
> Ya, no response by fp but it works on stock ui with magisk too — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

you can download update from realme's website and flash via twrp or i can help u with upgrade on our tg group

**Comment by phhusson** [comment]
from logcat error is
`05-31 22:05:19.761  1778  1778 E [GF_HAL][SZFingerprintCore]: [prepareEnrollRequest] spmt is not pass, please to do the process of spmt`

**Comment by sathish2026** [comment]
ya exactly , but how this can be fixed?

**Comment by phhusson** [comment]
i don't know, I remember having this issue, but I can't remember how I
fixed it... I think a strace would help

Le lun. 1 juin 2020 à 19:26, Sathishkumar <notifications@github.com> a
écrit :

**Comment by sathish2026** [comment]
can you how to take strace?

**Comment by phhusson** [comment]
After a lot of work, I found that the fix is simply to set ro.boot.realme.lockstate=0.

**Comment by sathish2026** [comment]
Thanks man waiting to test it

**Comment by phhusson** [comment]
Well you can it yourself, it'll be much faster:
```
> adb root
> adb shell
# remount
# echo -e '\nro.boot.realme.lockstate=0\n' >> /system/build.prop
reboot
```

**Comment by sathish2026** [comment]
thanks will try

**Comment by GT020** [comment]
> Well you can it yourself, it'll be much faster:
> ```
> > adb root
> > adb shell
> # remount
> # echo -e '\nro.boot.realme.lockstate=0\n' >> /system/build.prop
> reboot
> ```
> 

very good news

**Comment by 4j17h** [comment]
> After a lot of work, I found that the fix is simply to set ro.boot.realme.lockstate=0.
> 
> I'm adding that for next version.

Great work as usual, but I still don't understand why only X2 Pro got effected, realme X2 & other devices have no issues though. Anyways thanks for finding it :)

**Comment by sathish2026** [comment]
Fixed thanks phh

**Comment by priyalmahadik** [comment]
Hi Guys
i have the same problem with my x2 pro can you tell me how to do this as i am not aware of any coding, is that code have to put in phone or adb?

**Comment by geethagovind-ch** [comment]
> Well you can it yourself, it'll be much faster: ```
> adb root adb shell
> # remount # echo -e '\nro.boot.realme.lockstate=0\n' >> /system/build.prop reboot ```

i tried in cmd in pc still dont work in realme x50pro
