### ISSUE TITLE
Oneplus 6 no ims and no volte

### ISSUE THREAD

**Issue by ron9k** [phhusson/treble_experimentations#1342]
Oneplus 6 quack v217 fresh install. Booted ok, but no ims and then no volte. Also very slow charging.
Thank you for your hard work on treble 👍

06-01 18:03:16.303 W/Telephony(2635): AccountEntry: registerMmTelCapabilityCallback: registration failed, no ImsService available. Exception: CapabilityCallbackManager - MmTelFeature binder is dead. (code: 1)
[logs-2020-06-01-18-21-53.zip](https://github.com/phhusson/treble_experimentations/files/4712431/logs-2020-06-01-18-21-53.zip)

**Comment by phhusson** [comment]
you can install ims with https://github.com/KhushrajRathod/VoLTE-Fix

**Comment by ron9k** [comment]
Khushraj Rathod: THIS IS BROKEN. These are magisk modules, they can be installed via Magisk Manager or TWRP
Travis CI build log - https://travis-ci.com/KhushrajRathod/VoLTE-Fix/builds/169071270/

**Comment by phhusson** [comment]
You can use install-adb.sh instead of the magisk module, that's my recommendation.
(Since I recommend NOT to use Magisk)

**Comment by ron9k** [comment]
Ok did not try magisk module. I tried APK version, install-local.sh version. But IMS not registered.
I must have done something wrong in ADB. Tried sh ./install-adb.sh 64 and su -c sh ./install-adb.sh 64.
I think I will uninstall magisk. Is it possible to use Superuser with banking apps?

**Comment by KhushrajRathod** [comment]
@phhusson Solved here https://github.com/KhushrajRathod/VoLTE-Fix/issues/3, looks like your persistprops binary doesn't work :P (I'll have to test this properly as I already had the props set)

**Comment by KhushrajRathod** [comment]
So now that I remember this, persistprops *is* working. If your TWRP cannot decrypt data, it's not persistprops' fault
@phhusson You could close this
