### ISSUE TITLE
No Ambient Mode feature on Alcatel 1S

### ISSUE THREAD

**Issue by drago06** [phhusson/treble_experimentations#1343]
Hello. I have an Alcatel 1S and I've got no Ambient Mode option on my Assistant settings. Is it possible to get it working. Thanks in advance.

**Comment by phhusson** [comment]
Does your stock ROM have this hardware feature?

**Comment by drago06** [comment]
Unfortunately no. And I just found out that the system says it's a Pixel 2 XL because I flashed Pix3lify and PIXELARITY Magisk modules. So, isn't there a way to enable it?

**Comment by drago06** [comment]
And also, after I clean reinstalled the ROM, navigation gestures in settings are gone, I had to enable them through adb

**Comment by phhusson** [comment]
Well then this is out of the scope of this project.
As for the navigation gestures that's a known bug of v217 that will be fixed in tomorrow's v218
