### ISSUE TITLE
[mi8ee] in-display finger print does not work

### ISSUE THREAD

**Issue by nopeno** [phhusson/treble_experimentations#1344]
phh version is v216, the attachement is the logcat.

[1.log](https://github.com/phhusson/treble_experimentations/files/4715621/1.log)

**Comment by asmallbit** [comment]
Maybe you can read this [passage](https://forum.xda-developers.com/mi-8-pro/how-to/how-to-enable-fingerprint-gsi-t4108859) and follow it, use MIUI 12 vendor of Mi 8 EE instead of Mi 8 PRO.

**Comment by nopeno** [comment]
it is ok after re-flash MIUI 12
