### ISSUE TITLE
[mi8ee] [v218] reboot after unlock screen

### ISSUE THREAD

**Issue by nopeno** [phhusson/treble_experimentations#1345]
the system rebooted after unlocking the screen without doing anything. 
and then, unlocking screen, reboot again after serveral minutes.
and more

the attachment is the logcat
[2.log](https://github.com/phhusson/treble_experimentations/files/4720589/2.log)

**Comment by phhusson** [comment]
Clear PhhTrebleApp's data. This should fix this issue

**Comment by nopeno** [comment]
ok. it is ok after clear data.
