### ISSUE TITLE
huawei p20 lite - v218 broken sound

### ISSUE THREAD

**Issue by wax77** [phhusson/treble_experimentations#1348]
updating to v218 the phone has no sound working (no ringtone, no play music, no sound in youtube, etc...)

with v216 all fine, not tested on v217

bye

**Comment by phhusson** [comment]
Oreo vendor?

**Comment by wax77** [comment]
please explain better your question...

yes the phone was purchased with oreo, if is that the question

thank you

**Comment by phhusson** [comment]
And you never installed EMUI9?

**Comment by wax77** [comment]
yes sure, updated to eumi 9.1 before install your rom

i have also installed in the past openkirin roms (when I was on oreo)

in the update oreo->pie the phone was also rebranded from c55 to c432

bye

**Comment by wax77** [comment]
thank you phhusson but also on v219 no sound/multimedia working

do you need some logs?

thank you

**Comment by alt1478** [comment]
One with GSI and custom ROMs is to provide logcat

**Comment by wax77** [comment]
[logs.zip](https://github.com/phhusson/treble_experimentations/files/4748379/logs.zip)

the logs

thank you

**Comment by wax77** [comment]
Ant news, suggestione?

Thank you

**Comment by wax77** [comment]
v220, works!!!

thank you phhusson ;)
