### ISSUE TITLE
[Samsung Galaxy S9+ (SM-G965F)] MTP does not work

### ISSUE THREAD

**Issue by abun880007** [phhusson/treble_experimentations#135]
file transfer via MTP does not work.
Tested on RR rom.
Logcat attached
[mtpbroken.txt](https://github.com/phhusson/treble_experimentations/files/2263337/mtpbroken.txt)

Please let me know if i can provide any further info.

Thanks

**Comment by Tigger2014** [comment]
Also seeing this happen for me, it appears to happen on all treble roms for the s9 if thats any help

**Comment by phhusson** [comment]
see https://github.com/phhusson/treble_experimentations/issues/225
