### ISSUE TITLE
Night light is unstable [Doogee N100]

### ISSUE THREAD

**Issue by Cyberavater** [phhusson/treble_experimentations#1354]
If enable night light it keeps flickering to normal mode.
Link to stock rom: https://cloud.mail.ru/public/46WH/m65NPMvAR/
I'm new to this if there is any other info that I should provide please let me know, with how.

**Comment by Cyberavater** [comment]
@phhusson Can I get your attention plz?

**Comment by phhusson** [comment]
https://github.com/phhusson/treble_experimentations/issues?q=is%3Aissue+night+light+mediatek

**Comment by Cyberavater** [comment]
Hope it gets fixed soon.
I'm closing it as it'll be discussed farther at #1230
