### ISSUE TITLE
Security patch switching from june to march on xperia 10

### ISSUE THREAD

**Issue by ttocs99** [phhusson/treble_experimentations#1360]
hi. i have installed quak ab gapps via fastboot and flashed my devices boot and vendor.img. all works but the security patch has went from june to march. all i had done was remove root via securize and aftter reboot it switches to march. i can confirm that after a dirty flash it does go back to june but will go back to march after securize and reeboot. this is on Xperia 10 using oem boot and vendor.

**Comment by AndyCGYan** [comment]
Securize shows your vendor SPL, simple as that.

**Comment by ttocs99** [comment]
So isn't there anyway possible to keep the June update when using securize.

**Comment by phhusson** [comment]
Only the value displayed change. The actual protection against security flaws didn't change.
Security patches have both a vendor-side and framework-side. When you apply a GSI with june Security Patch Level, you have only june framework-side, and keep march vendor-side.
Doing Securize tricks security patch level, but doesn't change the fact that you have the june protections.
