### ISSUE TITLE
Cannot startup with SC9863A

### ISSUE THREAD

**Issue by Bocchi-Chan2023** [phhusson/treble_experimentations#1365]
Teclast p80x with SC9863A cannot start-up with this GSI.
It will stop at bootanimation.
Is it possible to fix it? Thank you
Edit: Google official GSI will start normally. (android10)

**Comment by drago06** [comment]
Got an Alcatel 1S with the same chipset. This rom works without bugs-just warms up. Try rebooting, it doesn't boot at the first start. Regarding the google gsi, did you try android 10 or 11?

**Comment by GalaxyNight** [comment]
@drago06 
Thank you very much. I'll try it now.
