### ISSUE TITLE
Huawei Mate 10 Lite boot logo bootloop

### ISSUE THREAD

**Issue by D0G3L0V3R** [phhusson/treble_experimentations#1375]
My Huawei Mate 10 Lite won't boot with the latest build. It's stuck at the "Unlocked bootloader" message and reboots until it goes into eRecovery. I had no problem with couple of the 1XX builds and if i remeber correctly v215 didn't have any issue either. Only thing I had to do was to format /data to remove encryption, and flash magisk-phh.zip and DIsableForceEncryption_DisableDM-Verity.zip. If that helps I also have the same issue with HavocOS 3.6 GSI, but can run latest Descendant just fine (but I can't find what phh version it's based on) Also tried flashing different kernel like Labyrinth and Permissiver_v4 for Android10 both on custom and stock kernel. I'll try to update with logs as soon as possible, but it might take a while beacuse I can't play much with my phone when I have work the next day.

**Comment by D0G3L0V3R** [comment]
Fixed it! I had some free time and finally managed to extract my stock vbmeta.img. I went the vbmeta route and... IT WORKS NOW! I am very happy that I encountered this problem beacuse my phone can now be TWRP free (TWRP is awesome and all, but I usually just do the flash 'n forget so it's only a safetynet tripper for me).  Also thank you phhusson for maintaining this amazing piece of software. Your GSI builds are my daily drivers and i hardly ever encounter any trouble with them <3

**Comment by Milor123** [comment]
@D0G3L0V3R  do you work it in GSI Android 11 roms? or 12? I am trying but all do bootloop in the own animation. Can u help me? I have tried flashing vbmeta after system gsi rom, but not work for me and my phone partitions are decrypted.

**Comment by Milor123** [comment]
> @D0G3L0V3R do you work it in GSI Android 11 roms? or 12? I am trying but all do bootloop in the own animation. Can u help me? I have tried flashing vbmeta after system gsi rom, but not work for me and my phone partitions are decrypted.

I've found the solution for my huawei mate 10 lite and i've write a post, please check [https://forum.xda-developers.com/t/gsi-rom-upgrading-mate-10-lite-to-android-11-guide-basic.4365843/#post-85989009](https://forum.xda-developers.com/t/gsi-rom-upgrading-mate-10-lite-to-android-11-guide-basic.4365843/#post-85989009)
