### ISSUE TITLE
VoLTE can't be enabled on Moto G7 Power

### ISSUE THREAD

**Issue by Ultracoolguy** [phhusson/treble_experimentations#1378]
Title says it all, entering good old \*#\*#4636#\*#\* and entering "Phone information" gives me this:

![Screenshot-Edited](https://user-images.githubusercontent.com/19539392/85948000-b5a73800-b93d-11ea-87f4-cdb9bfb4ec53.png)

Using [https://github.com/KhushrajRathod/VoLTE-Fix](voLTE-fix) didn't work. I'll happily give any other information.

**Comment by phhusson** [comment]
How did you install it?
Looks like it failed.
Safest way is using install.sh script from pc

Le dim. 28 juin 2020 à 14:50, Ultracoolguy <notifications@github.com> a
écrit :

**Comment by Ultracoolguy** [comment]
Looks like that was it. I used the .zip for installing, however I tried now the install.sh and it worked! I know have(or atleast, appears to be) both Wifi calling and VoLTE. Thank you!
