### ISSUE TITLE
[Umidigi A1 Pro] Ambient-display very dark/dim

### ISSUE THREAD

**Issue by RalphMalph1** [phhusson/treble_experimentations#138]
I have installed the pre-release V23 on my Umidigi A1 Pro.

Notifications are almost not visible in Ambient-display-mode
The screen lights up, but very very dark. Almost not visible

**Comment by phhusson** [comment]
My recommendation would be that you create an RRO (cf https://github.com/phhusson/vendor_hardware_overlay) for Umidigi A1 Pro which sets:
<integer name="config_screenBrightnessDoze">10</integer>

Don't hesitate to ask for help
