### ISSUE TITLE
[AOSP 10 GSI] Moto G7 Play's Rear Fingerprint Sensor isn't supported

### ISSUE THREAD

**Issue by AL2009man** [phhusson/treble_experimentations#1382]
Although, Moto G7 Play has a Rear Fingerprint Sensor and worked on Stock OEM ROM, Android 10 GSI doesn't seem to support it. [(might explain why Moto G7 Play modified version of LineageOS listed that as "DOES NOT WORK")](https://forum.xda-developers.com/g7-play/development/gsi-lineageos-17-1-modified-t4075035)

Phone: Moto G7 Play XT1952-6 - AOSP 10 v220 Gapps using Spaceminer's TWRP as my Recovery Mode.

and yes, I got Logcat covered: [logcat.txt](https://github.com/phhusson/treble_experimentations/files/4848489/logcat.txt)

**Comment by ghtmp** [comment]
Look [here](https://github.com/phhusson/treble_experimentations/wiki/Moto-G7-Play). 
There might be no specific entry for G7, but the problem was already mentioned in #1072

**Comment by Dunedan** [comment]
Using AOSP 11 300.l the fingerprint sensor works for me now on a Motorola Moto G7 Play.
