### ISSUE TITLE
[AOSP 10 GSI] Honor 8 Pro - No sound from Speakers

### ISSUE THREAD

**Issue by FlyingBackdoor** [phhusson/treble_experimentations#1384]
Sound working in
Earpiece
BT earphone
wired earphone

Not working in main speaker

[logs.log](https://github.com/phhusson/treble_experimentations/files/4853705/logs.log)
[dmesg.log](https://github.com/phhusson/treble_experimentations/files/4853709/dmesg.log)

**Comment by Anutrix** [comment]
Why was this closed? @FlyingBackdoor

**Comment by FlyingBackdoor** [comment]
> Why was this closed? @FlyingBackdoor 

Didn't got any attention also I changed the device.
