### ISSUE TITLE
[Google GSI 10 - Redmi Note 8 pro] No Service - Network Issue

### ISSUE THREAD

**Issue by araams** [phhusson/treble_experimentations#1394]
Flashed GSI 10 to Redmi Note 8 Pro.
Everything works fine except Mobile services.
Both the sim cards are detected and even the carriers are identified.
But 'No Service' and 'No Network found' while searching.

Any one came across the same issue?

**Comment by araams** [comment]
Logs using adb for your reference.
[adb_logcat1.txt](https://github.com/phhusson/treble_experimentations/files/4878321/adb_logcat1.txt)

**Comment by 00p513-dev** [comment]
No support for google gsi
