### ISSUE TITLE
[GSI 10] - adb not working

### ISSUE THREAD

**Issue by bahamut657** [phhusson/treble_experimentations#1395]
adb shell not working 
The device is unauthorized but neither happened on device. 
In standard ROM it prompt for enabliing, than connect with no problem

**Comment by phhusson** [comment]
Works for me, so you'll have to give more infos.

**Comment by bahamut657** [comment]
Is it possible that it iis not working due to magisk-phh.zip flashed?
Another thing is that I cannot open Magisk (It closes immediately)

**Comment by phhusson** [comment]
If you have an a-only device, then yes magisk would lead to adb being stock
in unauthorized mode

**Comment by bahamut657** [comment]
Yes I can confirm that my device is an A-only partition. (But I've flashed the AB package with no problem)
No solution to use adb ? Neither from network?

**Comment by phhusson** [comment]
Disable magisk?

**Comment by bahamut657** [comment]
How can I disable Magisk?
When I try to open it, it closes iimmediately.
Thanks in advice

**Comment by phhusson** [comment]
Flash stock rom's boot.img
