### ISSUE TITLE
[GSI 10] - No Mobile Internet - No service

### ISSUE THREAD

**Issue by bahamut657** [phhusson/treble_experimentations#1396]
Sometimes it happens that:
 - Mobile Network stop working, sometimes 2 times a day sometimes it doesn't happens for a couple of days
 - Sometimes No service on top left of status bar is notified, but the signal is present. The only way to make it disappear is rebooting

**Comment by phhusson** [comment]
Works for me, so you'll have to give more infos.

**Comment by bahamut657** [comment]
How I can provide more infos? 
Do you need the logcat? (I think so, but I cannot connect to adb)
My chipset is a Mediatek 6762, the device is CUBOT QUEST

**Comment by rffalbum** [comment]
Same here with Cubot P20 but the service works when in 2G mode

**Comment by bahamut657** [comment]
@rffalbum do you have a working adb? If so can you attach the logcat to investigate on the issue?

**Comment by rffalbum** [comment]
Got this log via 3c toolbox hope it would be helpful in resolving the issues

**Comment by rffalbum** [comment]
> @rffalbum do you have a working adb? If so can you attach the logcat to investigate on the issue?

Got this log via 3c toolbox hope it would be helpful in resolving the issues

**Comment by rffalbum** [comment]
> @rffalbum do you have a working adb? If so can you attach the logcat to investigate on the issue?

Got this log with 3C toolbox
https://drive.google.com/folderview?id=1RgDTbapgAN8K-URcsEF4qJfyg7srvaFf

**Comment by bahamut657** [comment]
Thank you so much.
It seems that the interesting lines in the logs are:
```
sys_prop(PROP_MSG_SETPROP2): Unable to interface_start service ctl [android.hardware.radio@1.0::IRadio/slot1] uid:1000 gid:1000 pid:298
E/02:07:22.229 hwservicemanager(  298)
Failed to set property for starting android.hardware.radio@1.0::IRadio/slot1
W/02:07:22.229 libc    (  298)
Unable to set property "ctl.interface_start" to "android.hardware.radio@1.0::IRadio/slot1": error code: 0x20
I/02:07:22.227 ServiceManagement( 5721)
```
@phhusson  can you help us to understand the problem?
Regards

**Comment by martament** [comment]
Same Error here with Mediapad M5 lite.

Even flashing old version wont help.

[ 1412.414489] [pid:1,cpu2,init]init: sys_prop(PROP_MSG_SETPROP2): Unable to interface_start service ctl [android.hardware.radio@1.0::IRadio/slot1] uid:1000 gid:1000 pid:365
[ 1413.414489] [2020:07:16 12:57:05][pid:1,cpu3,init]init: sys_prop(PROP_MSG_SETPROP2),name:ctl.interface_start,value:android.hardware.radio@1.0::IRadio/slot1: Permission denied

**Comment by MMan1982** [comment]
> Thank you so much @rffalbum.
> It seems that the interesting lines in the logs are:
> 
> ```
> sys_prop(PROP_MSG_SETPROP2): Unable to interface_start service ctl [android.hardware.radio@1.0::IRadio/slot1] uid:1000 gid:1000 pid:298
> E/02:07:22.229 hwservicemanager(  298)
> Failed to set property for starting android.hardware.radio@1.0::IRadio/slot1
> W/02:07:22.229 libc    (  298)
> Unable to set property "ctl.interface_start" to "android.hardware.radio@1.0::IRadio/slot1": error code: 0x20
> I/02:07:22.227 ServiceManagement( 5721)
> ```
> 
> @phhusson can you help us to understand the problem?
> Regards

Bahamut,is there something new about that?New bugs or something?Cubot answered me that this phone is never will be updated to Android 10.

**Comment by bahamut657** [comment]
Hi @MMan1982 !
No news or enanchements on the Android 10 GSI ROM at the moment.
I'm using it as daily ROM, but sometimes I have to reboot the device to restore Mobile Internet (also fast reboot seems to work).
@phhusson any news about this issue?

**Comment by MMan1982** [comment]
Bahamut657

> Hi @MMan1982 !
> No news or enanchements on the Android 10 GSI ROM at the moment.
> I'm using it as daily ROM, but sometimes I have to reboot the device to restore Mobile Internet (also fast reboot seems to work).
> @phhusson any news about this issue?

Hi,

Is this the same issue? https://github.com/phhusson/treble_experimentations/issues/1626

Bahamut,can you test it?

**Comment by bahamut657** [comment]
Hi @MMan1982 !!
It seems the same issue. I notice that when I travel, changing location, the Mobile data are always lost and I have to reboot (or fast reboot) the device.
Later, I'll try the service restart suggested by @phhusson (I have to re-flash the BOOT partition before, to get access to ADB)

Thanks for the info @MMan1982 !! ;)

**Comment by MMan1982** [comment]
> Hi @MMan1982 !!
> It seems the same issue. I notice that when I travel, changing location, the Mobile data are always lost and I have to reboot (or fast reboot) the device.
> Later, I'll try the service restart suggested by @phhusson (I have to re-flash the BOOT partition before, to get access to ADB)
> 
> Thanks for the info @MMan1982 !! ;)

Fixed in AOSP 11.0 v300.k ! Can you try it and update the bug list in wiki?Which bugs are present now?

**Comment by bahamut657** [comment]
Wow @MMan1982   ! What a wonderful news (and thanks to @phhusson  for his work).

I will update the Cubot QUEST with this ROM this afternoon (or at the latest tomorrow afternoon) , hoping that nothing break up upgrading to Android 11 :D

You are the first person I will inform ;)

Best regards

**Comment by bahamut657** [comment]
Hey @MMan1982 !
I succesfully flashed Android 11 GSI Last release (AOSP 11.0 v300.l).
For the moment I can confirm that: 
- ROM works smootly
- I can flash the Gapps version of the ROM (system-roar-arm64-ab-gapps.img.xz) using the same fastboot method (this time I re-tryied flashing the system image using TWRP and a mouse, but it seems that flashing image bring to unbootable system).

To flash the ROM follow the steps described in WIKI, on CUBOT Quest page.

I double check the mobile connection to see if the issue is resolved.
Thanks too much to @phhusson to bringing Android11 working on our phone

Best regards ;)

**Comment by phhusson** [comment]
For the issue to be fixed, you need to tick the option in treble settings
(automatically resetart radio or something like that)

**Comment by bahamut657** [comment]
Ok, thanks for the info @phhusson.
Can I wait to reproduce the issue and check the tick after it happens? 
It restarts the service immediately when I enable it?

**Comment by phhusson** [comment]
Yes

7 janv. 2021 15:10:10 MaDPaPo <notifications@github.com>:

**Comment by bahamut657** [comment]
@phhusson I've configured the phone and installed some additional Gapps  (Gmaps, Camera ...).
I rebooted the phone, and now it remains stucked on Android boot animation. 

What could be happened?

**Comment by phhusson** [comment]
No idea, you should be able to get logcat

**Comment by bahamut657** [comment]
adb logcat -d remains in <waiting for device> state
Can I read the boot logs in other ways (using TWRP)?

**Comment by bahamut657** [comment]
So I perform a factory reset (re-formatting data partition) using TWRP.
Rebooting the phone not seems to work.
Now, I configured offline the intial screen, configured APN, and rebooted the phone.

The phone remains stucked in Android animation screen (so it seems it is not directly connected to installed apps).

I'm currently using the system-roar-arm64-ab-gapps.img.xz image.
@phhusson , should I try system-roar-arm64-ab-vndklite-gapps.img.xz (to exclude system R/W problems) or system-roar-arm64-ab-vanilla.img.xz (to exclude gapps problems) ?

**Comment by bahamut657** [comment]
Hi all
I find a procedure to restore the mobile connection, hoping phhusson can integrate it in "Restart RIL" functionality if it works for all.
The procedure for me is:

Reboot phone -> Mobile data are working
Press automatically restart RIL -> RIL is restarted and Mobile Data are not working (signaling NO SIM - no Mobile DATA)
Now in the dialer APP, insert ##4636## and open the "connection settings" panel
=> Magically, LTE connection now works (and NO SIM is gone away)
Anyone can test this case on Mediatek device? (@MMan1982, @rffalbum , @martament ) ?
Regards ;)

**Comment by MMan1982** [comment]
Hi,

Sorry i will try,but until fingerprint unlock and nfc not working i cannot use as daily rom,so i cannot test. Now i have serious glitches in factory v14 rom,i am thinking to upgrade phhusson's gsi11. Problems fixed on this??

**Comment by MMan1982** [comment]
> Hi all
> I find a procedure to restore the mobile connection, hoping phhusson can integrate it in "Restart RIL" functionality if it works for all.
> The procedure for me is:
> 
> 1. Reboot phone -> Mobile data are working
> 2. Press automatically restart RIL -> RIL is restarted and Mobile Data are not working (signaling NO SIM - no Mobile DATA)
> 3. Now in the dialer APP, insert `*#*#4636#*#*` and open the "connection settings" panel
>    => Magically, LTE connection now works (and NO SIM is gone away)
>    Anyone can test this case on Mediatek device? (@MMan1982, @rffalbum , @martament ) ?
>    Regards ;)

Btw,in 11 v306 booting crash fixed.

**Comment by MMan1982** [comment]
@bahamut657 Bahamut can i send you an email?I have a working recovery(touchscreen works too) on my Quest,i wanna try gsi11,but i got flashing error,and twrp restored with the factory recovery..

**Comment by bahamut657** [comment]
Resolved by installing all packages under IMS Features (under Phh Treble Settings)
