### ISSUE TITLE
Asus Zenfone 4 (2017) z01k  will not boot up

### ISSUE THREAD

**Issue by someaguy** [phhusson/treble_experimentations#14]
Installed the GSI following the instructions listed [here](https://www.xda-developers.com/flash-generic-system-image-project-treble-device/) with no luck. :(

**Comment by phhusson** [comment]
Well that's normal, zf4 doesn't have real Treble
Possibly, CLT works
https://forum.xda-developers.com/project-treble/trebleenabled-device-development/tool-capire-le-treble-terble-vendor-t3774629
