### ISSUE TITLE
User-build fails (SELINUX_IGNORE_NEVERALLOWS := true cannot be used in user builds)

### ISSUE THREAD

**Issue by hersche** [phhusson/treble_experimentations#1413]
Hello, i would like to create a unrooted user-build as a single banking-app doesn't start out of this reason.

I managed to build the userdebug-image via docker and it works. For This, i needed to

- Add python3 to docker-file
- Change GSMExpress-fetch-path (clone-path from gitlab)

Those 2 changes are just a by-the-way-hint, affected general building for me. They're a bit out of context, just wanted to mention them.

When i do the user-build, it ends up like this:

> [ 77% 858/1108] including system/sepolicy/Android.mk ...
> FAILED: 
> system/sepolicy/Android.mk:88: error: SELINUX_IGNORE_NEVERALLOWS := true cannot be used in user builds.
> 21:37:33 ckati failed with: exit status 1

My command was:

> docker run -ti \
>    -v $(pwd):/treble \
>    -v $(pwd)/../treble_output:/treble_output \
>    -w /treble_output \
>    treble /bin/bash /treble/build-dakkar.sh aosp10 arm64-ab-gapps-nosu-user

i didn't found any place to change this variable global. Changing it in system/sepolicy/Android.mk leaded to fail later in the compile-process.

However, i wanna thank you for doing this at all, the rom is working very well and my manufacturer doesn't provide updates anymore - so, thanks to you, i_(and soon also others) am secured again :)

**Comment by phhusson** [comment]
> Hello, i would like to create a unrooted user-build as a single banking-app doesn't start out of this reason.

Have you simply tried pressing "securize" in treble settings? It transforms a userdebug build with su to a user build without su.

SELINUX_IGNORE_NEVERALLOWS is defined somewhere in device/phh/treble, but removing it you'll hit other issues

**Comment by hersche** [comment]
thanks for this hint, just trying it right now, wasn't aware of it.

i've to say that i builded a unrooted userdebug-image and the app still crashes, but i suspect because of debug-system (they just say, rooted and some lineageos..)

i would rather need to set it to false, but guess the result is the same. let's see. may i just workaround that single app.. thanks also for the direction of the folders, will try around.

**Comment by hersche** [comment]
ok, i've to say i give it up, at least for the moment, and just use the alternative authentification-way. i tried some stuff and ended up in some selinux-stuff as you propably know already.

feel free to close the issue, for me its fine.. :)
