### ISSUE TITLE
[Huawei P Smart - Kirin 659] USSD response is not displayed

### ISSUE THREAD

**Issue by washinson** [phhusson/treble_experimentations#142]
[logcat_errors.txt](https://github.com/phhusson/treble_experimentations/files/2298452/logcat_errors.txt)
[logcat_all.txt](https://github.com/phhusson/treble_experimentations/files/2298453/logcat_all.txt)
USSD response is not displayed with any phone app. But SIM operator got request.

**Comment by washinson** [comment]
Sorry, logcat above from omnirom(with this issue).
AOSP logcat:
[e.txt](https://github.com/phhusson/treble_experimentations/files/2301704/e.txt)
[a.txt](https://github.com/phhusson/treble_experimentations/files/2301705/a.txt)

**Comment by Skyrimus** [comment]
Same problem on MTK chipsets

**Comment by phhusson** [comment]
WIP on @Dil3mm4 side

**Comment by VigneshS007** [comment]
![image](https://user-images.githubusercontent.com/15701137/50535112-57dd3880-0b6c-11e9-9bb9-c030650655da.png)
 Is the USSD bug fixed in latest v108?  
as per the image its fixed. but is there separate fix file for it?

**Comment by Dil3mm4** [comment]
This can be closed

**Comment by Skyrimus** [comment]
@Dil3mm4, can i fix fu.cking calls on mt6735 if use same fix for mt6739?
