### ISSUE TITLE
Flashlight doesn't work After battery is at 15%

### ISSUE THREAD

**Issue by ShahrukhAbrar** [phhusson/treble_experimentations#1424]
Device:Tecno Spark 4 lite
Chipset:MT6761

After battery drops down to 15% flashlight stops working . If battery is above 15% or is at charging when below 15% flash works fine

**Comment by ufos97** [comment]
That is how it work since official Android 8 so it's not a problem just get used to it like that

**Comment by ShahrukhAbrar** [comment]
Is there a way to deactivate this feature, mostly my mobile is at 7-18% and
this a quiet a inconvenience.
