### ISSUE TITLE
Lenovo Smart Tab M10 [TB-X605F]

### ISSUE THREAD

**Issue by Yahoo-Mike** [phhusson/treble_experimentations#1427]
The device hangs on boot after flashing GSI ROM.  The manufacturer logo appears, but does not get to the boot animation.

If I also install Disable_Dm-verity_forceencrypt (and format /data), the screen goes blank after about 20 seconds and goes into Qualcomm 900E mode.

Flashing magisk v20.4 and "fastboot -w" make no difference.

The X605F supports treble with VNDK Lite version 28. It's A-only & arm64.

I don't know if it still matters but in [vendor] in ld.config.vndk_lite.txt on the stock ROM, namespace.default.isolated = false.

ADB does not start, so I can't get a logcat. When I reboot to TWRP, there are no tombstones, ramoops or last_kmsg to report.

I uncommented the first few lines of rw-system.sh, but /cache/phh/logs/ is never created.

The /vendor/init/hw init.*.rc files refer to 10+ files that don't exist on the GSI (but do exist in the stock ROM).

**Comment by phhusson** [comment]
How did you check you it's an a-only device?

**Comment by Yahoo-Mike** [comment]
Hackintosh5's app reports:
	* Your device does not support System-as-root.  Use an A-only operating system
	* Seamless Upgrades are not supported

Also, [ro.build.ab_update] and [ro.boot.slot_suffix] are not defined as system properties.

I forgot to mention that, in relation to verified boot, there is no vbmeta partition.

**Comment by phhusson** [comment]
That's on the vndk 28 vendor? (The result might change after vendor upgrade)

**Comment by Yahoo-Mike** [comment]
Device was originally released with Oreo, then upgraded to Pie.  
Currently:

X605F:/ # **getprop | grep vndk**
[ro.vndk.lite]: [true]
[ro.vndk.version]: [28]

X605F:/ # **find . -name "*vndk*" 2>/dev/null**
./system/lib64/vndk-sp-28
./system/lib64/libvndksupport.so
./system/etc/vndksp.libraries.28.txt
./system/etc/ld.config.vndk_lite.txt
./system/lib/vndk-sp-28
./system/lib/libvndksupport.so

**Comment by phhusson** [comment]
My question is whether you checked whether it was a-only or a/b on vndk 28
or vndk 26.

**Comment by Yahoo-Mike** [comment]
I was running the latest OTA (vndk 28) when I checked.

I can re-load Oreo ROM and check again, if you want.

**Comment by Yahoo-Mike** [comment]
Using the stock Oreo vendor.img works. I'll start a support thread, because there's a few issues like forceencrypt and device name/model not populating etc.  When that's sorted, I'll register the device as working with the project.
