### ISSUE TITLE
Camera doesn't work on Mi Max 3 nitrogen

### ISSUE THREAD

**Issue by MyOxy** [phhusson/treble_experimentations#1437]
I have tried several different camera apks, incl. original MiUi camera. I also have tried all options in PHH treble settings. No way to get the camera working

**Comment by phhusson** [comment]
Adb shell dumpsys media.camera

**Comment by MyOxy** [comment]
nitrogen$ adb shell dumpsys media.camera
Can't find service: media.camera
 n service found

**Comment by phhusson** [comment]
From running AOSP?

**Comment by MyOxy** [comment]
Yepp AOSP vanilla arm64 a-only

**Comment by MyOxy** [comment]
system-quack-arm64-aonly-vanilla.img.xz

**Comment by MyOxy** [comment]
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/5047640/logcat.txt)

Hope the logcat will help

**Comment by phhusson** [comment]
Error is:
`08-05 21:45:19.064  3160  3160 E vndksupport: Could not load /vendor/lib/hw/camera.sdm660.so from default namespace: dlopen failed: library "libft2.so" not found.`

Device is 8.1 native, so it is allowed to be vndk lite.

Try with Q MIUI vendor to copy /system/lib/libft2.so to /system/lib/vndk-29. I'm kinda expecting it to fail again, so just get logcat again afterwards.

**Comment by MyOxy** [comment]
you are right, same error 
08-11 16:25:14.783  2908  2908 W android.hardwar: type=1400 audit(0.0:77): avc: denied { read } for name="libft2.so" dev="mmcblk0p77" ino=6049 scontext=u:r:hal_camera_default:s0 tcontext=u:object_r:unlabeled:s0 tclass=file permissive=0
08-11 16:25:14.792  2296  2328 D IccSmsInterfaceManager: [IccSmsInterfaceManager] Added GSM cell broadcast channels range 4379 to 4379
08-11 16:25:14.793  2296  2328 D IccSmsInterfaceManager: [IccSmsInterfaceManager] Calling setCellBroadcastActivation(true)
08-11 16:25:14.795  2908  2908 E vndksupport: Could not load /vendor/lib/hw/camera.sdm660.so from default namespace: dlopen failed: library "libft2.so" not found.

[logcat.txt](https://github.com/phhusson/treble_experimentations/files/5057510/logcat.txt)

**Comment by phhusson** [comment]
well I expected same error but on another file :P
Issue here is the way you pushed the file (TWRP I guess?)

From a root terminal running on the GSI, do:
```
remount
mount -o remount,rw /
restorecon /system/lib/vndk-29/libft2.so
```

then reboot, and try again

**Comment by MyOxy** [comment]
Yes, I love the TWRP file manger and terminal 

I have now done everything via Android terminal. result the same

[logcat.txt](https://github.com/phhusson/treble_experimentations/files/5058136/logcat.txt)

**Comment by phhusson** [comment]
This last logcat is a net regression compared to the previous one, there is no trace of libft2.so anymore at all...?

**Comment by MyOxy** [comment]
line 3234 
08-05 21:45:14.547  3099  3099 E vndksupport: Could not load /vendor/lib/hw/camera.sdm660.so from default namespace: dlopen failed: library "libft2.so" not found.

**Comment by phhusson** [comment]
yup. did you maybe reflash GSI and didn't copy the file again or something
like that?

**Comment by MyOxy** [comment]
The log comes after a reflash of the GSI and coping and running all commands. 

I can reflash the GSI without coping the file. No problem

**Comment by phhusson** [comment]
no, that's the opposite. I meant /it looks like to me/ that you didn't copy
the file again

Can you do `ls -lZ /system/lib/vndk-29/libft2.so` after your changes to
confirm everything when correctly?

**Comment by MyOxy** [comment]
OK, I will flash again ( I'm always going back to Pie because it'S my main driver), copy the file and so on and will post the result of the ls command

**Comment by phhusson** [comment]
k hum, we can try on pie vendor for the moment. Do the same commands, but
replace vndk-29 with vndk-28. It could raise other issues (because of using
vndk 29 libs on vndk 28), but error messages should be clear.

**Comment by MyOxy** [comment]
OKydoky. Will adb root shell do the job or do I need root terminal ?

**Comment by phhusson** [comment]
adb root; adb shell is actually preferred over using TWRP
Just do:
```
adb root
adb remount
adb shell cp /system/lib/libft2.so /system/lib/vndk-28/libft2.so
adb reboot
```
By copying the file this way you won't need restorecon.

**Comment by MyOxy** [comment]
So, error is gone, but camera not working
[logcat-28.txt](https://github.com/phhusson/treble_experimentations/files/5068692/logcat-28.txt)

|android:/ $ ls -lZ /system/lib/vndk-28/libft2.so                             
-rwxrwxrwx 1 root root u:object_r:system_lib_file:s0 631744 2020-08-13 13:13 /system/lib/vndk-28/libft2.so

T

**Comment by phhusson** [comment]
`08-13 13:20:10.244  3396  3396 E vndksupport: Could not load
/vendor/lib/hw/camera.sdm660.so from default namespace: dlopen failed:
library "libicui18n.so" not found.`

Same thing with that lib now then :-)

```
adb root
adb remount
adb shell cp /system/lib/libicui18n.so /system/lib/vndk-28/libicui18n.so
adb reboot
```

**Comment by MyOxy** [comment]
should I save the complete folder from MiUi - Q  for future use ? Because this /system/lib/libicui18n.so deosn't exist on your vanilla and I have to make first a complete flash of MiUi - q

**Comment by phhusson** [comment]
nope don't take it from MIUI.
Copy /system/lib/vndk-27/libicui18n.so to /system/lib/vndk-28/libicui18n.so
in that case

**Comment by MyOxy** [comment]
There is no libicui18n.so in  /system/lib/vndk-27/

**Comment by MyOxy** [comment]
short update, I'm getting always errors with new files which I'm now copy step by step from /system/lib to system/lib/vndk-28 or 29.

**Comment by phhusson** [comment]
Don't forget to write down the whole list so I can integrate those
afterwards :P

**Comment by MyOxy** [comment]
Yes, but now I stuck at line 3081
08-13 17:59:52.352  2902  2902 E vndksupport: Could not load /vendor/lib/hw/camera.sdm660.so from default namespace: dlopen failed: library "libandroid.so"
Have copied it to 27 / 28 / 29 but still get this error
[logcat-7.txt](https://github.com/phhusson/treble_experimentations/files/5070096/logcat-7.txt)

**Comment by MyOxy** [comment]
So, these files I have copied
adb shell cp /external_sd/copy/libft2.so /system/lib/vndk-28/libft2.so
adb shell cp /external_sd/copy/libandroid.so /system/lib/vndk-28/libandroid.so
adb shell cp /system/lib/vndk-27/libicui18n.so /system/lib/vndk-28/libicui18n.so
adb shell cp /system/lib/libjnigraphics.so /system/lib/vndk-28/libjnigraphics.so
adb shell cp /system/lib/libmedia.so /system/lib/vndk-28/libmedia.so
adb shell cp /system/lib/libandroidfw.so /system/lib/vndk-28/libandroidfw.so
adb shell cp /system/lib/libinput.so /system/lib/vndk-28/libinput.so
adb shell cp /system/lib/libsensor.so /system/lib/vndk-28/libsensor.so
adb shell cp /system/lib/libandroid_runtime.so /system/lib/vndk-28/libandroid_runtime.so
adb shell cp /system/lib/libnetd_client.so /system/lib/vndk-28/libnetd_client.so
adb shell cp /system/lib/libhwui.so /system/lib/vndk-28/libhwui.so
adb shell cp /system/lib/libprocessgroup.so /system/lib/vndk-28/libprocessgroup.so
adb shell cp /system/lib/libsonivox.so /system/lib/vndk-28/libsonivox.so

But now the libandroidicu.so is missing. And I can't find it anywhere.

[logcat-15.txt](https://github.com/phhusson/treble_experimentations/files/5073679/logcat-15.txt)

**Comment by MyOxy** [comment]
OK, now I have copied 48 libs to /vndk-28 and .... stuck with an error I can't solve.
 Line 3708:

08-14 18:35:20.907  5545  5545 E vndksupport: Could not load /vendor/lib/hw/camera.sdm660.so from default namespace: dlopen failed: cannot locate symbol "uprv_free_58" referenced by "/system/lib/vndk-28/libicui18n.so"....

[logcat-49.txt](https://github.com/phhusson/treble_experimentations/files/5075786/logcat-49.txt)

**Comment by MyOxy** [comment]
Hi, 

do you see any change to get the camera running ?

**Comment by MyOxy** [comment]
Issue solved. I have first installed last Chinese MiUI Rom and than LOS17/eOS-Q GSI. Now Camera works out of the box
