### ISSUE TITLE
Xiaomi Mi Mix 2s fingerprint interferes with UI

### ISSUE THREAD

**Issue by aeppacher** [phhusson/treble_experimentations#144]
If you touch the fingerprint scanner when the screen is on, it selects the first item in the current screen. This is insanely frustrating when you are at the bottom of a web page, you touch the sensor by mistake and it scrolls the whole way up to the top because you have selected the first element in the app

**Comment by phhusson** [comment]
Can you extract /system/usr/keylayout from stock ROM?
Also, run adb shell getevents, and get me the results when doing various gestures on the fingerprint
(just click, long press, double click, swipe left/up/right/down)

**Comment by aeppacher** [comment]
I will log the events when I get home tonight

**Comment by aeppacher** [comment]
I tried getevents but that is not found, I tried running adb shell getevents but no events show up when I touch the fingerprint sensor or perform any actions. 

On the stock os fingerprint gestures aren't supported, just unlocking the phone with it

**Comment by rbuehlma** [comment]
Here you are. I was not able to produce any thing else than touching the reader and releasing. Swiping and so on did not made a difference.

`add device 1: /dev/input/event5
  name:     "sdm845-tavil-snd-card Button Jack"
add device 2: /dev/input/event4
  name:     "sdm845-tavil-snd-card Headset Jack"
add device 3: /dev/input/event0
  name:     "qpnp_pon"
add device 4: /dev/input/event1
  name:     "uinput-goodix"
could not get driver version for /dev/input/mice, Not a typewriter
add device 5: /dev/input/event2
  name:     "synaptics_dsx"
could not get driver version for /dev/input/mouse0, Not a typewriter
add device 6: /dev/input/event3
  name:     "gpio-keys"
/dev/input/event1: 0001 0066 00000001
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 0066 00000000
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 0066 00000001
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 0066 00000000
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 0066 00000001
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 0066 00000000
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 0066 00000001
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 0066 00000000
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 0066 00000001
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 0066 00000000
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 0066 00000001
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 0066 00000000
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 0066 00000001
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 0066 00000000
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 0066 00000001
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 0066 00000000
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 0066 00000001
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 0066 00000000
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 0066 00000001
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 0066 00000000
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 0066 00000001
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 0066 00000000
/dev/input/event1: 0000 0000 00000000
`

**Comment by rbuehlma** [comment]
Adding this file:
https://github.com/LineageOS/android_device_xiaomi_polaris/blob/lineage-15.1/keylayout/uinput-goodix.kl
to /system/usr/keylayout
and
https://github.com/LineageOS/android_device_xiaomi_polaris/blob/lineage-15.1/idc/uinput-goodix.idc
to /system/usr/idc
Solves this issue by disabling the fingerprint sensor as input device. Fingerprint itself still works.

I'm not sure how the linked repo is related to this one?

**Comment by phhusson** [comment]
Thanks for those informations, so the fix is indeed easy, but implementing
it will be a bit more complicated.

Please give me the result of "find /vendor/usr"

**Comment by rbuehlma** [comment]
/vendor/usr doesn't exist. I did look into the twrp dump of the vendor partition. If it helps you, I can provide both, the system dump and vendor dump of miui to you.

**Comment by phhusson** [comment]
Nope that's not needed. 
I now have all the information I need. Thanks. 
(this probably won't be fixed in next version but the one after)

**Comment by rbuehlma** [comment]
Thanks for looking into it. The rom already works very good for me :)

**Comment by phhusson** [comment]
Should be fixed with https://github.com/phhusson/device_phh_treble/commit/f53a56ee1dab6665dc5ad874bd58af83cd411ce6

Download
https://github.com/phhusson/device_phh_treble/blob/android-9.0/rw-system.sh

Try to replace your rw-system.sh with this
adb root
adb remount
adb push rw-system.sh /system/bin/rw-system.sh
adb reboot

**Comment by rbuehlma** [comment]
I verified that it is enough to add the uinput-goodix.kl file.

I'm not sure whether it as good idea to replace the rw-system.sh on my 8.1 Android with the above version from 9.0?

Should the 9.0 builds be similarly mature for my devices compared to 8.1? If yes, I would give it a try. 8.1 has only minor issues and works very well for me.

**Comment by phhusson** [comment]
Well there is a small but minor difference between 8.1 and 9.0 script

remove /system/etc/permissions/android.hardware.consumerir.xml before pushing rw-system.sh, and you should be fine

**Comment by phhusson** [comment]
Cool thanks.
I'll need a final confirmation in the actual release if that's possible.

**Comment by rbuehlma** [comment]
Will it also be in the next 8.1 release or only 9.0?

**Comment by phhusson** [comment]
should be both if I don't fail

**Comment by rbuehlma** [comment]
I can confirm this is fixed with v24
