### ISSUE TITLE
Xiaomi K30 Pro Partition Not Found

### ISSUE THREAD

**Issue by blackzafiqz** [phhusson/treble_experimentations#1441]
`C:\Users\black>fastboot flash system "C:\Users\black\Downloads\system-quack-arm64-ab-gapps.img"
Sending sparse 'system' 1/3 (786428 KB)            OKAY [ 18.777s]
Writing 'system'                                   FAILED (remote: 'Partition not found')
fastboot: error: Command failed`

I got this error when following this guide [https://github.com/phhusson/treble_experimentations/wiki/Xiaomi-Redmi-K30-Pro---Zoom-Edition---Poco-F2-Pro](url) . I also check there is not system partition, only super.img is available

**Comment by phhusson** [comment]
You didn't do `fastboot reboot fastboot` as instructed.

**Comment by blackzafiqz** [comment]
> You didn't do `fastboot reboot fastboot` as instructed.

I did that and it will open recovery instead of fastboot. Is there any specific vbmeta.img i need to flash? currently I extract it from fastboot rom

`C:\Users\black>fastboot reboot fastboot
Rebooting into fastboot                            OKAY [  0.002s]
< waiting for any device >
fastboot: error: Failed to boot into userspace fastboot; one or more components might be unbootable.`

**Comment by phhusson** [comment]
Do you have stock recovery or custom recovery? It's possible a custom
recovery doesn't support this.

**Comment by blackzafiqz** [comment]
> Do you have stock recovery or custom recovery? It's possible a custom recovery doesn't support this.

okay reflash stock recovery seems fixed my problem. thank you

**Comment by blackzafiqz** [comment]
@phhusson i got new problem though. seems like device manager detect my device as "lmi", and i cant find any driver for it. Already installed driver provided by google and quallcom. Can you attach the driver link? Already googled it but still cant find

**Comment by blackzafiqz** [comment]
Got it after windows update.

**Comment by blackzafiqz** [comment]
@phhusson 
i reflash my phone from beginning but it just gonna boot into fastboot. Can you look into it?
[https://downloads.blackzafiqz.com/2020-08-14%2001-35-54.mkv](url)
