### ISSUE TITLE
[Nokia 7 Plus] Pie: Camera doesn't work

### ISSUE THREAD

**Issue by sanshu-rom** [phhusson/treble_experimentations#145]
logcat all
[aosp.txt](https://github.com/phhusson/treble_experimentations/files/2307035/aosp.txt)
logcat radio
[aospradio.txt](https://github.com/phhusson/treble_experimentations/files/2307036/aospradio.txt)
pm list
[pm.txt](https://github.com/phhusson/treble_experimentations/files/2307037/pm.txt)

**Comment by phhusson** [comment]
Your log is too slow... do:
adb reboot; adb logcat -b all -d > log.txt
the adb logcat will wait for the device to boot

**Comment by sanshu-rom** [comment]
Log in boot process
[nokialog.txt](https://github.com/phhusson/treble_experimentations/files/2308810/nokialog.txt)
Log after boot
[nokialogboot.txt](https://github.com/phhusson/treble_experimentations/files/2308811/nokialogboot.txt)

**Comment by phhusson** [comment]
For camera, try with another camera app, Open Camera for instance.

**Comment by simonsmh** [comment]
My device has an unusable Camera2 app on AOSP 9, too. Open Camera is working.
[This is AOSP 9 fail.log](https://github.com/phhusson/treble_experimentations/files/2339588/fail.log)
[This is AOSP 8 success.log](https://github.com/phhusson/treble_experimentations/files/2339589/success.log)

**Comment by sanshu-rom** [comment]
Opencamera works, and now I've found that it's not that I can't recognize the SIM card, but that I can't recognize the meid and can only use it in Sim1
all
[nokia20180902log.txt](https://github.com/phhusson/treble_experimentations/files/2342946/nokia20180902log.txt)
radio
[nokia20180902radio.txt](https://github.com/phhusson/treble_experimentations/files/2342948/nokia20180902radio.txt)

**Comment by raysenlau** [comment]
Base on 9.0 vendor(v3_150) it seems works well，the SIM card can recognize and 4G Data, but calling has no sound audio. test on v103

**Comment by sanshu-rom** [comment]
It can start in 9 of vendor? You can try to apply to the operator to shut down volte, and the call should be normal.@raysenlau

**Comment by raysenlau** [comment]
Yes, it is sure. hmd has changed the 9.0 vendor and it includes same overlay folder.
The Pixel Experience - P has the same issue.
I will try it later.

**Comment by sanshu-rom** [comment]
What kind of operator is your Sim? I tested CDMA. It has no signal.

**Comment by raysenlau** [comment]
My operator is CMCC and China Telecom (CDMA), model TA-1062

**Comment by sanshu-rom** [comment]
Me too. Do you have any signals on both cards? Have you ever tried havoc P?

**Comment by sanshu-rom** [comment]
Based on DP4 flash, I found that there were no signals in all two cards. Are you a Chinese version or an international version of ta-1062?@raysenlau

**Comment by sanshu-rom** [comment]
I tried @raysenlau's way to use Android 9 vendor, but I still had no signal.@phhusson 
This is the log:
[all.txt](https://github.com/phhusson/treble_experimentations/files/2347874/all.txt)

**Comment by raysenlau** [comment]
@sanshu-rom Are you flash boot with TWRP, I just tried the stock boot.img with Magisk v16.7 patched, then fastboot flash system command.

**Comment by sanshu-rom** [comment]
I've found the problem. It's something wrong with my operation, but the problem has been solved. Is the call on AOSP normal?

**Comment by sanshu-rom** [comment]
Dual card can not dial Jin Xin, signal, display 4G, but can not access the Internet.@phhusson
[9-all.txt](https://github.com/phhusson/treble_experimentations/files/2348229/9-all.txt)
