### ISSUE TITLE
Auto select the first option when  touching finger print while the device was unlocked

### ISSUE THREAD

**Issue by MXAN2CHA** [phhusson/treble_experimentations#1453]
my device is Redmi 9 (lancelot) phh-aosp-vanilla
everything is fine,but when i touch the finger print scanner at the back of the device,it auto select the first option of screen
for example :i open the settings app,and i touch my fp and it get into the phh treble settings.
it is annoying since the fp module is at the middle of the device due to the 4 camera.
if testing is needed,i'm glad to help.
and thanks to phh's work

**Comment by phhusson** [comment]
You probably just need to add your device to this list:
https://github.com/phhusson/device_phh_treble/blob/android-10.0/rw-system.sh#L87

On-device the file is in /system/bin/rw-system.sh

**Comment by MXAN2CHA** [comment]
okay,i understand how it works,but i'm sorry i can't do the testing for you,my collage send me a new phone card,so i need my phone ready to work,so i flash back to official rom,i'll have i try when this device is able to do some test,if it works,i'll leave a commmet here to help this gsi to adapt more device
