### ISSUE TITLE
Alldocube M8 T806K - MT6797

### ISSUE THREAD

**Issue by SubSonix** [phhusson/treble_experimentations#1454]
I cannot for the life of me get GSI 10 to work (I got it working once then tried to use a TWRP and had to start over)

It'll either boot loop or just hand on the android logo.

GSI 9 seems to work fine, as I used that for a few days before going back to trying to get 10 installed.

Can you offer a suggestion to install this reliably?

I'm currently running it on stock till I can figure out something solid. Stock is 8.0.0

I've tried dm-verity on/off AND/OR force encryption on/off.

Tried with both system-quack-arm64-aonly-gapps.img and system-quack-arm64-aonly-vanilla.img

![Screenshot_20200825-195249](https://user-images.githubusercontent.com/3277416/91160710-17e9a280-e70d-11ea-8db1-5310f0d641f1.png)

**Comment by GalaxyNight** [comment]
Can't start up after these steps?
"fastboot -w"
"fastboot erase system"
"fastboot flash system image.img"
"fastboot reboot"

**Comment by SubSonix** [comment]
No.

At this point I have a feeling that it just won't work with 10, but I'd like to hear that from @phhusson to ease my mind

**Comment by phhusson** [comment]
There is no hard reason for it not to work, but I would need logcat.

**Comment by SubSonix** [comment]
Thanks mate, that's all I needed to hear, I'll get it all set up again tonight and add it here when I have it :)

**Comment by SubSonix** [comment]
Actually before I do continue, I ran a few commands from this site - https://www.xda-developers.com/install-android-q-beta-gsi-project-treble/

And the results are; 

adb shell getprop ro.treble.enabled = true

adb shell cat /system/etc/ld.config.28.txt | grep -A 20 "\[vendor\]" - this didn't technically work as I don't have ld.config.28.txt, but in ld.config.txt it said namespace.default.isolated = false

adb shell cat /proc/mounts | grep -q /dev/root && echo "system-as-root" || echo "non-system-as-root" = non-system-as-root as expected

Does this matter, should I still continue with Android 10?

Keeping in mind that 9 worked and from all I've read It shouldn't have from what I can tell.

**Comment by SubSonix** [comment]
@phhusson Still awaiting your response for the above post before I begin.
Just tagging you in case you weren't notified, not trying to bother you and I hope it doesn't :)

**Comment by SubSonix** [comment]
[verify off .txt](https://github.com/phhusson/treble_experimentations/files/5140981/verify.off.txt)
[verify on logcat.txt](https://github.com/phhusson/treble_experimentations/files/5140982/verify.on.logcat.txt)

So I went ahead and did the installation as I was bored lol, the files about are verify on - stock boot.img and verify off is with dm-verity and forced encryption disabled.

**Comment by phhusson** [comment]
Right, see https://github.com/phhusson/treble_experimentations/issues/1162 for a workaround

**Comment by SubSonix** [comment]
With either boot.img?

And just as Is now, any need to erase anything before/after?

**Comment by phhusson** [comment]
Well I initially just checked verify on, since I always look at unmodified boot.img/vendor first.

I don't really understand what's going on in verify off.

**Comment by SubSonix** [comment]
I'll work with unmodified first then, but I've a feeling dm-verify might be a problem.

I'll report back in a moment.

**Comment by phhusson** [comment]
The changes described in the other issue are in /system. /system with my
GSI CAN'T have dm-verity enabled. If you can get adb logcat working it
means dm-verity is already properly disabled for /system.

**Comment by SubSonix** [comment]
adb: error: failed to stat remote object '/system/lib/vndk-26/libstdc++': No such file or directory

**Comment by SubSonix** [comment]
adb: error: failed to stat remote object '/system/lib/vndk-26/libstdc++': No such file or directory

**Comment by SubSonix** [comment]
Sorry, I didn't read the entire other post, do I need to modify the txt?

**Comment by SubSonix** [comment]
On a unrelated note, when trying to sideload I get the error:

Error: get_partition_info_from_scatter fail

Trying to sideload gapps pico as I find the non vanilla gsi a bit bloated :)

**Comment by SubSonix** [comment]
*UPDATE* Managed to port a twrp  and got it working, sideloaded gapps and all is well so far :)

Thank you for your assistance phhusson, I really do appreciate what you've created here and I wish you the best :)

**Comment by SubSonix** [comment]
Having more issues, heading to bed, will report back tomorrow.

**Comment by SubSonix** [comment]
Okay, so I thought I caused this issue with twrp, but now after starting from stock again and copying libstdc++.so and modifying ld.config.26.txt I'm having the same issue still.

This tablet has 32GB of storage, but after installing the GSI It takes me down to 4GB for some reason.

Any ideas?

**Comment by SubSonix** [comment]
Sorted it with a factory wipe :)

**Comment by danielehrhardt** [comment]
My AllDoCube does reboot to fastboot mode when i flashed GSI does someone know why?

**Comment by TechVR777** [comment]
> _UPDATE_ Managed to port a twrp and got it working, sideloaded gapps and all is well so far :)
> 
> Thank you for your assistance phhusson, I really do appreciate what you've created here and I wish you the best :)

Hi can you tell me how you got twrp working and after how you install Android 10 on the Alldocube M8.  If you can share me the TWRP file and give me some instructions how to do it this would be great. Its a great tablet specs but the digital side  default installation is so bad (an old android version locked up with no update possible without hack)...

**Comment by SubSonix** [comment]
I can't remember sorry, It's been too long.

I've given up on it currently, as every time it goes flat/is turned off I have to go through reinstalling everything all over again.
