### ISSUE TITLE
Headphones not getting detected in latest build

### ISSUE THREAD

**Issue by amandogra1997** [phhusson/treble_experimentations#1457]
I really liked your rom you also included Nubia specific features to the rom but there is a issue with the rom that 3.5 mm headphones are not getting detected I have tried everything but all in vain I hope you'll try to solve in next build good luck for that.

**Comment by phhusson** [comment]
Have you tried selecting alternate audio settings in Treble settings =>
Qualcomm settings?

Le mer. 26 août 2020 à 20:02, amandogra1997 <notifications@github.com> a
écrit :

**Comment by amandogra1997** [comment]
thanks yeah it has started working
