### ISSUE TITLE
Lenovo S5 K520

### ISSUE THREAD

**Issue by AaaDDie** [phhusson/treble_experimentations#1461]
My TWRP 3.2.3-1 is not recognizing system-quack-arm64-aonly-gapps.xz. - I have placed inside the internal memory and in SD card but it doesn't show up using the Mount feature of the recovery tool. Please advise? 

Its a Lenovo S5 K520

**Comment by phhusson** [comment]
Xz is a compression file format, so you need to decompress the file.

**Comment by AaaDDie** [comment]
Doh!

**Comment by AaaDDie** [comment]
Thank you for the help, I am sure you have probably guessed by now that I am a noob and this is the first time I am doing this. Decompressing the Xz file leaves us with an Image file, the tutorial I am following shows the GSI rom to be a Zip and not an Image file. Can you please shed some more light on it or direct me to someplace else? Thank you.

**Comment by AaaDDie** [comment]
> Xz is a compression file format, so you need to decompress the file. 

Thank you for the help, I am sure you have probably guessed by now that I am a noob and this is the first time I am doing this. Decompressing the Xz file leaves us with an Image file, the tutorial I am following shows the GSI rom to be a Zip and not an Image file. Can you please shed some more light on it or direct me to someplace else? Thank you.

**Comment by phhusson** [comment]
With TWRP, select flash, "System Image", and it should list you the img
file.

**Comment by AaaDDie** [comment]
Thank you, it worked perfectly.
