### ISSUE TITLE
[Redmi 8] Bluetooth media issue

### ISSUE THREAD

**Issue by GTMF99** [phhusson/treble_experimentations#1464]
Hi, I'm on a Redmi 8 which I'd recently install Havoc OS 3.8 (arm64 AB img), everything was working properly until I tried to use my wireless earbuds, I connected them succesfully, but when I tried to play some music (on AIMP) there was no sound. After testing with many combinations in Treble Settings and rebooting, still no sound. Later I realized that call audio was properly routed through the earbuds, still no media and notification sound (even when enabling media audio in Bluetooth device's settings), so, can someone review the following logcat and audio_policy? (when I pair and try to play something on the earbuds), please...

[logcat.txt](https://github.com/phhusson/treble_experimentations/files/5177421/logcat.txt)
[audio_policy.txt](https://github.com/phhusson/treble_experimentations/files/5177427/audio_policy.txt)

Thanks in advance 👍

**Comment by GTMF99** [comment]
Solved with patch found on device's Telegram group (pm for more info...)

**Comment by phhusson** [comment]
Please give more infos a out the fix

Le lun. 7 sept. 2020 à 19:08, Gabriel Mendez <notifications@github.com> a
écrit :

**Comment by bartekhm8** [comment]
How can I pm somebody? I don't see that option

**Comment by bartekhm8** [comment]
Can you give me link for that patch?
