### ISSUE TITLE
htc u11+ cannot boot 

### ISSUE THREAD

**Issue by jinbolx** [phhusson/treble_experimentations#147]
[AOSP 9.0] [EXPERIMENTAL] [2018-08-21] Phh-Treble  cannot boot ,then boot into bl mode .

AOSP 8.1] [2018-08-16] Phh-Treble        this version can boot

**Comment by phhusson** [comment]
Get me /sys/fs/pstore and/or /proc/last_kmsg

**Comment by jinbolx** [comment]
how to get it?

**Comment by yefonme** [comment]
> Get me /sys/fs/pstore and/or /proc/last_kmsg
I tried on my U11+,there is nothing in /sys/fs/pstore, and the /proc/last_kmsg file does not exist.

**Comment by phhusson** [comment]
Could be a dupe of https://github.com/phhusson/treble_experimentations/issues/309, or not (I'm guessing not)

@xymopen sorry I'm (very) late, your link is dead.

Could someone get me logs again?

**Comment by xymopen** [comment]
Sorry my U11+ was (physical) damaged and I cannot grab another logcat.
