### ISSUE TITLE
[Xiaomi Mi 8 SE] No adaptive brightness or AOD

### ISSUE THREAD

**Issue by technoboi1** [phhusson/treble_experimentations#148]
[getprop.txt](https://github.com/phhusson/treble_experimentations/files/2310665/getprop.txt)

[overlay.zip](https://github.com/phhusson/treble_experimentations/files/2310673/overlay.zip)
[framework.zip](https://github.com/phhusson/treble_experimentations/files/2310674/framework.zip)

**Comment by technoboi1** [comment]
phhusson, do you need these files?

**Comment by linuxct** [comment]
Mind giving this overlay a try? Extract the apk, then place it inside /system/overlay/ and reboot 
[treble-overlay-xiaomi-mi8se.apk.zip](https://github.com/phhusson/treble_experimentations/files/2329127/treble-overlay-xiaomi-mi8se.apk.zip)

**Comment by linuxct** [comment]
@phhusson add flag pending validation please

**Comment by technoboi1** [comment]
I try it, adaptive brightness switch is here now, but after i enabled it, brightness doesnt change automatically on sunny and dark.

**Comment by Asureus** [comment]
Please try this [new version](https://github.com/phhusson/treble_experimentations/files/2363944/treble-overlay-xiaomi-mi8se_v3.zip)

If it's working for you, I'll submit a PR based on this version.

**Comment by phhusson** [comment]
@Asureus I don't think you PR-ed this, did you?
If it works for you, that's enough for the PR
