### ISSUE TITLE
Samsung Galaxy Tab A 8.0" wifi 2019 (SM-T290) doesn't boot Project Treble

### ISSUE THREAD

**Issue by Ryzen5-3600** [phhusson/treble_experimentations#1483]
Hi, I am trying to get Project Treble to work on this device. But every variant that I try, it just leads to a bootloop. But it does install without any issues or errors in TWRP. To have TWRP to install and boot correctly, I have to have the Android 9 firmware bootloader installed on the device. But I have the latest Android 10 vendor installed. For the GSI, I am trying the Android 10 versions. And yes, the tab does have support from Samsung for Project Treble. Any help would be helpful. Thanks.

**Comment by Ryzen5-3600** [comment]
@phhusson

**Comment by Avrution** [comment]
By chance, have you tried both A and AB versions?  My tablet is a different model, but with A9 it used A and that changed to AB with A10.

**Comment by Ryzen5-3600** [comment]
> By chance, have you tried both A and AB versions? My tablet is a different model, but with A9 it used A and that changed to AB with A10.

Yes I have. That also resulted in a bootloop.

**Comment by Ryzen5-3600** [comment]
> By chance, have you tried both A and AB versions? My tablet is a different model, but with A9 it used A and that changed to AB with A10.

Thank you. It no longer bootloops.
