### ISSUE TITLE
Mobiistar C1 Shine got stucked at Boot animation and not completing booting...

### ISSUE THREAD

**Issue by Amit172233** [phhusson/treble_experimentations#1489]
Mobiistar C1 Shine got stucked at Boot animation and not completing booting...
Plz help developers...

**Comment by phhusson** [comment]
Got logs?

Le dim. 27 sept. 2020 à 10:33, Amit172233 <notifications@github.com> a
écrit :

**Comment by Amit172233** [comment]
No, I had said "It is not completing the booting then how could I get logs...."

**Comment by Amit172233** [comment]
I had given 30 minutes and flashed without gapps it not working i think its a no-boot issue

**Comment by phhusson** [comment]
Adb logcat may work on android logo, have you checked?

Le dim. 27 sept. 2020 à 13:02, Amit172233 <notifications@github.com> a
écrit :

**Comment by Amit172233** [comment]
No adb serial port showing on pc :-( 
No luck

**Comment by phhusson** [comment]
How did you fix it(

**Comment by Amit172233** [comment]
I was using modified  boot image of magisk

**Comment by Amit172233** [comment]
I was using midified boot image of magisk
