### ISSUE TITLE
WIFI and sim card not work on moto g6 plus with stock 8.0 vendor

### ISSUE THREAD

**Issue by rakeeboy** [phhusson/treble_experimentations#149]
hi,phhusson,the V102 can boot on my moto g6 plus with stock 8.0 vendor,but WIFI and sim card not work,baseband version  unknown.  Magisk not installed
here is the log:
[log.txt](https://github.com/phhusson/treble_experimentations/files/2315564/log.txt)

**Comment by phhusson** [comment]
Does it work on v23?
Do you have stock 8.0 boot.img?
Try to setenforce 0, and wait a minute
