### ISSUE TITLE
Aosp 11.0 v300.a (Moto g6 Play Bootloop)

### ISSUE THREAD

**Issue by MarcosPearce** [phhusson/treble_experimentations#1492]
Moto g6 Play bootloop using vendor 8.0
system-roar-arm-aonly-vanilla.img.xz
[logcattop.txt](https://github.com/phhusson/treble_experimentations/files/5293373/logcattop.txt)

**Comment by phhusson** [comment]
bootloop = stuck on Android animation?

Le lun. 28 sept. 2020 à 17:36, MarcosPearce <notifications@github.com> a
écrit :

**Comment by MarcosPearce** [comment]
animation does not appear, the screen goes black it turns on and off.

**Comment by phhusson** [comment]
Ok, I'll check again on my Moto E5, it's possible that I botched the
release, I should answer you in few hours.

>

**Comment by MarcosPearce** [comment]
Ok thanks for the help and the good work

**Comment by Ruben8ap** [comment]
I confirm this situation I have just done the test and the same thing has happened. I attach another logcat if necessary. Thanks phh for your work !!!
[logcat[Moto G6 Play].txt](https://github.com/phhusson/treble_experimentations/files/5293999/logcat.Moto.G6.Play.txt)

**Comment by phhusson** [comment]
ok problem found, i forgot to push https://github.com/phhusson/platform_external_selinux/commit/00f7989d79ad8e219dae29de8e8f20e4dbab008a
and
https://github.com/phhusson/platform_system_linkerconfig/commit/d4880eec8fa830f6c8fe68fe1ebbb05adc5bbbb1

before releasing v300.a

I'll probably respin pretty soon with those.

**Comment by phhusson** [comment]
v300.b pushed

**Comment by Ruben8ap** [comment]
> v300.b pushed

Thanks phh, I'm going to test it and confirm if everything is fine.

**Comment by Ruben8ap** [comment]
> v300.b pushed

Done, It has already booted thanks phh !!

![Screenshot_20200928-185540.png](https://user-images.githubusercontent.com/50933625/94495260-4270c480-01bf-11eb-8aad-4654cea20528.png)
