### ISSUE TITLE
Terrible battery life on Huawei Y6 (2018) [ATU-L21]

### ISSUE THREAD

**Issue by milankragujevic** [phhusson/treble_experimentations#150]
I'm experiencing terrible battery life on my phone, meaning it lasts for about 3-6 hours of use then turns off, and remains hot at all times. This doesn't happen on Huawei's stock system.

**Comment by phhusson** [comment]
Which GSI?
I've been told this device doesn't boot my GSI, did you do something?
Get me a logcat dump more than few minutes after boot

Le jeu. 23 août 2018 à 21:51, Milan Kragujević <notifications@github.com> a
écrit :

**Comment by milankragujevic** [comment]
Any GSI, I tried LineageOS and built my own with your buildsystem. It boots it pretty well and everything works so I don't know who misinformed you. I'll build another image for myself with the latest commits then test and send you the logcat.

**Comment by milankragujevic** [comment]
So, it doesn't happen anymore. Weird. Battery was 85% 12 hours ago, it's now at 75%. Pretty good. Thanks for fixing it, whoever did it :+1:
