### ISSUE TITLE
AOSP 11.0 v300.b Note 20 Ultra stuck on Android animation 

### ISSUE THREAD

**Issue by manofsteel2017** [phhusson/treble_experimentations#1500]
Won't boot up on note 20 ultra.
Just stuck on Android animation 

Tried to grab pstore logs but its empty.
Will try and get a log but unlikely 
I can try anything requires

**Comment by phhusson** [comment]
K we need to force-enable ADB.

Add this to rw-system.sh at line 3:

```
	mount -t configfs none /config
	rm -Rf /config/usb_gadget
	mkdir -p /config/usb_gadget/g1

	echo 0x12d1 > /config/usb_gadget/g1/idVendor
	echo 0x103A > /config/usb_gadget/g1/idProduct
	mkdir -p /config/usb_gadget/g1/strings/0x409
	echo phh > /config/usb_gadget/g1/strings/0x409/serialnumber
	echo phh > /config/usb_gadget/g1/strings/0x409/manufacturer
	echo phh > /config/usb_gadget/g1/strings/0x409/product

	mkdir /config/usb_gadget/g1/functions/ffs.adb
	mkdir /config/usb_gadget/g1/functions/mtp.gs0
	mkdir /config/usb_gadget/g1/functions/ptp.gs1

	mkdir /config/usb_gadget/g1/configs/c.1/
	mkdir /config/usb_gadget/g1/configs/c.1/strings/0x409
	echo 'ADB MTP' > /config/usb_gadget/g1/configs/c.1/strings/0x409/configuration

	mkdir /dev/usb-ffs
	chmod 0770 /dev/usb-ffs
	chown shell:shell /dev/usb-ffs
	mkdir /dev/usb-ffs/adb/
	chmod 0770 /dev/usb-ffs/adb
	chown shell:shell /dev/usb-ffs/adb

	mount -t functionfs -o uid=2000,gid=2000 adb /dev/usb-ffs/adb

	/apex/com.android.adbd/bin/adbd &

	sleep 1
	echo none > /config/usb_gadget/g1/UDC
	ln -s /config/usb_gadget/g1/functions/ffs.adb /config/usb_gadget/g1/configs/c.1/f1
	ls /sys/class/udc |head -n 1 > /config/usb_gadget/g1/UDC

	sleep 2
	echo 2 > /sys/devices/virtual/android_usb/android0/port_mode
```

You'll probably screw SELinux un the process, so after editing the file do:
`chcon u:object_r:phhsu_exec:s0 /system/bin/rw-system.sh`

**Comment by manofsteel2017** [comment]
these lines can be added through terminal in twrp right ? like system/bin/rw-system.sh
i mean i'm sure i can get the sh on pc and edit it from there lol
________________________________

**Comment by phhusson** [comment]
Typing them manually from twrp sounds super annoyingz modify the file on
your pc

Le mer. 30 sept. 2020 à 23:50, manofsteel2017 <notifications@github.com> a
écrit :

**Comment by manofsteel2017** [comment]
haha i figured
will let you know how it goes.
so  after that i'd have adb right even on android logo?
________________________________

**Comment by manofsteel2017** [comment]
after latest security update 
300b/c no longer stuck on android animation
it's bootlooping now. 
android 10 quack works fine including brightness slider, sd card, MTP
i'm not sure what we can try now since i'm bootlooping

**Comment by phhusson** [comment]
well rollback to 300.a and do the rw-system.sh changes i instructed you to

**Comment by manofsteel2017** [comment]
they are all bootloop now

**Comment by manofsteel2017** [comment]
this is fixed with 300f 
boots up fine

**Comment by datwenjie** [comment]
Hi, may I know how to flash GSi on Note 20 Ultra??
