### ISSUE TITLE
Go apps on arm64?

### ISSUE THREAD

**Issue by milankragujevic** [phhusson/treble_experimentations#151]
Is there support for building with Go apps on arm64? I built it once, but it was constantly crashing because webview was complaining of wrong architecture in logcat. I can retry if it's supposed to work, but am just wondering if it's even supported? Thanks.

**Comment by phhusson** [comment]
Android Go is specifically for low end devices, and as of O this is only supported on 32bits devices.
So no, there is no support for go gapps on arm64.
