### ISSUE TITLE
Magisk not work on ASOP 11.0 v300.f

### ISSUE THREAD

**Issue by Oshawott-kun** [phhusson/treble_experimentations#1512]
hey man
i have issue. i flash magisk canary and is work. but i open magisk manager is 5(installed: N/A) i flash 3 times. i got same issue (installed: N/A). if magisk not work for ASOP 11.0. please comment me i will close this issue.

device:SM-A515F

**Comment by Rachsutha** [comment]
moto one action .... As well

**Comment by jaydm99** [comment]
Yes. No known compatible version of magisk available yet for phh roar.

**Comment by Oshawott-kun** [comment]
Okay it is weird.my friend can flash magisk on aosp 11.0 with the same device. Ah I dont have idea okay i will close this issue. If have solution please reopen. Okay thanks
