### ISSUE TITLE
AOSP-10-quack-v222-arm64-aonly does not boot on cubot P20

### ISSUE THREAD

**Issue by treble2019** [phhusson/treble_experimentations#1522]
system-quack-v222-arm64-aonly-vanilla.img

Device: Cubot P20

Aosp10 does not boot. The device comes with AOSP 8 (A only arm64). Aosp8 works OK.

Log file: adb logcat

https://bin.snopyta.org/?20db33a9699f3d48#8rZrD38XurLQBGYmJ3vCUmrcSSKz214CWuHCMEpUWQ3H

**Comment by phhusson** [comment]
`

   1. 10-07 15:30:14.568 2231 2231 E Zygote : java.lang.RuntimeException:
   Socket unset or invalid: ANDROID_SOCKET_usap_pool_secondary

`

that's a known bug of magisk. Either uninstall Magisk, or use "phh-magisk"

**Comment by treble2019** [comment]
Thanks for quick reply.
I have installed magisk in boot (as as boot-patched.img) for the stock ROM. 

I thought GSI only flashed in system as system.img. Does installing magisk in boot still annoy quack-gsi?
Thanks

**Comment by phhusson** [comment]
Yes, magisk does assumptions about what's in system.img which are wrong

**Comment by treble2019** [comment]
Thank you so much... just installed your android-roar image. Works mostly fine. 
except.
` Process android.process.media has crashed too many times: killing!`

(says also - Serial console enabled. performance is impacted.. To disable check bootloader...)

**Comment by phhusson** [comment]
This error probably means you did a bad factory reset. Try to do a factory
reset using stock oem unmodified recovery

**Comment by treble2019** [comment]
Thanks for quick reply. I did try factory reset (from stock recovery). Still the same issue. I will get back to roar after sometime. Need a daily driver :-)
