### ISSUE TITLE
moto e5 play not booting (comcast variant)

### ISSUE THREAD

**Issue by TheNextGamer21** [phhusson/treble_experimentations#1527]
I tried installing the android 11 treble rom, system-roar-arm-aonly-vanilla.img.xz. I unzipped the file, booted my phone into fastboot, erased data, cache, dalvik, etc.. and ran these commands

1. fastboot flash modem NON-HLOS.bin (my sim card was not working)
2. fastboot erase modemst1 
3. fastboot erase modemst2 
4. fastboot flash system roar.img (renamed it to that)

The flash was successful and I entered flashboot reboot

My phone starts saying your bootloader is unlocked, and reboots sometimes into fastboot, sometimes into bootloop

Note: The previous android 10 gsi, system-quack-arm-aonly-gapps.img, works perfectly and boots just fine

Any help would be greatly appreciated

**Comment by TheNextGamer21** [comment]
Note: lineage os 18 (android 11) gsi is also able to boot, bot I like phh-treble more :)

**Comment by phhusson** [comment]
Got logs?

**Comment by TheNextGamer21** [comment]
IDK what logs to get, sorry I was in school

My bootloader is completely unlocked

I have both the arm32 stock rom and an arm64 aospextended rom, both supporting treble

I would prefer to use stock rom, I have twrp and orangefox recovery

Note: when flashing the android 11 gsi, I notice an error

PS C:\Users\rever\Desktop\Firmware> fastboot flash system C:\Users\rever\Desktop\platform-tools\roar.img
target reported max download size of 535822336 bytes
Invalid sparse file format at header magi

**Comment by TheNextGamer21** [comment]
If you want logs however, I would be happy to get them if you could tell me how to, thanks!

**Comment by phhusson** [comment]
Flash GSI, boot it, then in recovery get /proc/last_kmsg and
/sys/pfs/pstore and send them here

Le ven. 9 oct. 2020 à 22:33, TheNextGamer21 <notifications@github.com> a
écrit :

**Comment by TheNextGamer21** [comment]
So I should basically just flash my stock rom and try it

Ok I will do it in an hour

**Comment by TheNextGamer21** [comment]
None of those files exist, I don't even think android is able to boot

Videos of error:
https://www.youtube.com/watch?v=fe7u7zZ70Mk
https://www.youtube.com/watch?v=HO52PeDx6DE

Logs:
PS C:\Users\rever\Desktop\Firmware> fastboot flash system C:\Users\rever\Desktop\system-roar-arm64-ab-vanilla.img
target reported max download size of 535822336 bytes
sending sparse 'system' (458752 KB)...
OKAY [ 15.088s]
writing 'system'...
OKAY [  9.950s]
sending sparse 'system' (458752 KB)...
OKAY [ 15.608s]
writing 'system'...
OKAY [  9.701s]
sending sparse 'system' (458752 KB)...
OKAY [ 15.645s]
writing 'system'...
OKAY [  9.697s]
sending sparse 'system' (458752 KB)...
OKAY [ 15.831s]
writing 'system'...
OKAY [  9.714s]
sending sparse 'system' (434392 KB)...
OKAY [ 14.877s]
writing 'system'...
OKAY [  9.196s]
finished. total time: 125.322s

**Comment by TheNextGamer21** [comment]
Side Note: The device says bad key because the bootloader is unlocked, it disappears once android's boot animation comes up, which it never does in my case

**Comment by phhusson** [comment]
Why are you flashing A/B variant? I'm pretty sure it's supposed to be a-only

Le sam. 10 oct. 2020 à 00:45, TheNextGamer21 <notifications@github.com> a
écrit :

**Comment by 0x15f2d** [comment]
> Note: when flashing the android 11 gsi, I notice an error
> 
> PS C:\Users\rever\Desktop\Firmware> fastboot flash system C:\Users\rever\Desktop\platform-tools\roar.img
> target reported max download size of 535822336 bytes
> Invalid sparse file format at header magi

I also got that error too. Use img2simg to convert the image to sparse form so it can be flashed correctly.

But usually, a normal ext4 image would work with fastboot fine and bootable if those spare free space doesn't eat up the whole system partition.

But prefer converting to sparse.

**Comment by phhusson** [comment]
"Invalid sparse file format at header magic" IS NOT AN ERROR
This is perfectly normal, ignore it, and sparsing it won't change a thing

**Comment by TheNextGamer21** [comment]
ohhh thats why, i need a only varient

I'll try that later today, if it works, issue resolved

**Comment by TheNextGamer21** [comment]
Issue still persists, same behavior

Logs:
PS C:\Users\rever\Desktop> fastboot flash system .\system-roar-arm-aonly-vanilla.img
target reported max download size of 535822336 bytes
Invalid sparse file format at header magi
sending sparse 'system' (517254 KB)...
OKAY [ 17.075s]
writing 'system'...
OKAY [ 11.620s]
sending sparse 'system' (512138 KB)...
OKAY [ 17.074s]
writing 'system'...
OKAY [ 11.579s]
sending sparse 'system' (194940 KB)...
OKAY [  6.517s]
writing 'system'...
OKAY [  4.570s]
finished. total time: 68.447s
PS C:\Users\rever\Desktop> fastboot reboot
rebooting...

**Comment by phhusson** [comment]
and still nothing in /sys/fs/pstore or /proc/last_kmsg in TWRP?

Le sam. 10 oct. 2020 à 19:42, TheNextGamer21 <notifications@github.com> a
écrit :

**Comment by TheNextGamer21** [comment]
nope, nothing

**Comment by TheNextGamer21** [comment]
again, android 10 phh boots fine

**Comment by TheNextGamer21** [comment]
but not android 11

**Comment by TheNextGamer21** [comment]
i will try it with an arm64 ab custom rom

**Comment by TheNextGamer21** [comment]
wait, i think there are log files

**Comment by phhusson** [comment]
K, flash Android 11 GSI, boot it, reboot into fastboot, flash Android 10
GSI, and grab /sys/fs/pstore and /proc/last_kmsg from Android 10 GSI (DO
NOT reboot into recovery))

Le sam. 10 oct. 2020 à 20:09, TheNextGamer21 <notifications@github.com> a
écrit :

**Comment by TheNextGamer21** [comment]
twrp allows me to output the android 11 logs

**Comment by TheNextGamer21** [comment]
i believe

**Comment by TheNextGamer21** [comment]
ok so I should re install android (stock rom), flash android 11 gsi, boot it, reboot into fastboot, flash android 10 gsi, and grab /sys/fs/pstore without going into recovery?

How do I do that without recovery (new to fastboot so idk)

**Comment by phhusson** [comment]
No, flash Android 10 GSI, do factory reset, boot it once, reboot into
fastboot, flash Android 11 GSI, boot it once, flash Android 10, boot it,
recover logs.
You need to go into recovery only for the factory reset which is done
before flashing Android 11.

**Comment by dammy123** [comment]
How did you get the aosp extended gsi

**Comment by TheNextGamer21** [comment]
i have the full aosp extended rom

**Comment by TheNextGamer21** [comment]
including system, boot, etc...

**Comment by TheNextGamer21** [comment]
it is NOT a gsi, it is a full rom

**Comment by TheNextGamer21** [comment]
according to the treble app, as far as i remember, it was arm64 and supported AB (system as root)

**Comment by TheNextGamer21** [comment]
OK so first thing, when the system crashes on boot, fastboot says the reason is reboot mode set to fastboot

What I did
Entered fastboot
Flashed stock rom
Flashed android 11
Booted android 11
Entered fastboot
Flashed android 10
DID NOT BOOT ANDORID 10

What do I do now

**Comment by TheNextGamer21** [comment]
oh i see what u want me to do

how am i supposed to pull files from the phone without recovery mode

**Comment by phhusson** [comment]
Whichever way you want, adb, root explorer, terminal...

Le sam. 10 oct. 2020 à 20:29, TheNextGamer21 <notifications@github.com> a
écrit :

**Comment by TheNextGamer21** [comment]
OK so first thing, when the system crashes on boot, fastboot says the reason is reboot mode set to fastboot

What I did
Entered fastboot
Flashed stock rom
Flashed android 10
Booted it (system starts successfully and connects to cellular and wifi network)
Entered fastboot
Flashed android 11
Booted it (fails after 10 seconds and enters fastboot)
Flashed android 10
Now on the welcome screen

What do I do now

**Comment by TheNextGamer21** [comment]
Ok device not play protect certified (dont care google)
Gonna install root file explorer (zarchiver)
What files should I get

**Comment by phhusson** [comment]
/sys/fs/pstore and /proc/last_kmsg

Le sam. 10 oct. 2020 à 20:57, TheNextGamer21 <notifications@github.com> a
écrit :

**Comment by TheNextGamer21** [comment]
/sys/fs/pstore is a folder?

**Comment by TheNextGamer21** [comment]
[logs.zip](https://github.com/phhusson/treble_experimentations/files/5359773/logs.zip)

**Comment by phhusson** [comment]
well the only file in this zip  is empty. Yes pstore is a folder

Le sam. 10 oct. 2020 à 21:11, TheNextGamer21 <notifications@github.com> a
écrit :

**Comment by TheNextGamer21** [comment]
its empty???

**Comment by phhusson** [comment]
yes the only file in the zip is logs/pstore/annotate-ramoops-0 and its size
is 0

**Comment by TheNextGamer21** [comment]
Here is screenshot
![Screenshot_20201010-141546](https://user-images.githubusercontent.com/72624720/95663276-8212a700-0b03-11eb-8b82-51c5cf96c13f.png)

**Comment by phhusson** [comment]
well it says 0 byte so empty...

Le sam. 10 oct. 2020 à 21:19, TheNextGamer21 <notifications@github.com> a
écrit :

**Comment by TheNextGamer21** [comment]
IDK what to ecen

**Comment by TheNextGamer21** [comment]
IDK what to even do now

**Comment by TheNextGamer21** [comment]
I'll try it with the arm64 ab rom

**Comment by TheNextGamer21** [comment]
@phhusson I found a rom for my phone that supports treble and is much more likely to work

https://forum.xda-developers.com/moto-e5/development/rom-aospextended-rom-v6-7-moto-e5-play-t4096167

**Comment by TheNextGamer21** [comment]
system has successfully started android 11 using the 3rd party rom

Until @phhusson finds a fix, you can only use 3rd party roms to be able to use the android 11 gsi

Issue CLOSED

**Comment by phhusson** [comment]
How am I supposed to find a fix if you won't help me...?

Le sam. 10 oct. 2020 à 21:41, TheNextGamer21 <notifications@github.com> a
écrit :

**Comment by TheNextGamer21** [comment]
@phhusson idk what to get when the file is 0 bytes

**Comment by TheNextGamer21** [comment]
it baffles me how android 10 gsi boots but android 11 gsi does not

I will re open the issue I guess

**Comment by TheNextGamer21** [comment]
I noticed one thing, when I flashed it with the 3rd party rom, it did not show the sparse error while flashing, not sure why

**Comment by TheNextGamer21** [comment]
what phone do u have

**Comment by TheNextGamer21** [comment]
Fix found: I was using the motorola e5 generic firmware, but I needed to use my carrier specific firmware (as the hardware is carrier specific). Once I flashed comcast's firmware, I was able to boot android 11

Issue CLOSED
