### ISSUE TITLE
bootloop on bv9900

### ISSUE THREAD

**Issue by openStove** [phhusson/treble_experimentations#1533]
I've successfully flashed the recovery with twrp, then I tried to flash system, with the last lienage from here (A-only), and I got a boot loop... I've flashed the system back to the vendors one, and I'm able to boot at least again on the stock droid...

I've also tried to flash system over fastboot, its the same..

Treble compatibility check was made, I have A-only, and installed the A-image

**Comment by Ahmedazim7804** [comment]
try to make clean install if orange fox recovery project is available try that recovery
i was getting same problem so i tried clean install and its boot-up in mi max 2 (oxygen) arm64-a only

**Comment by openStove** [comment]
That doesn't help much...
blackview has no orange fox image available... 
I've already tried clean install over MTK tools...

**Comment by Elenedeath** [comment]
strange, i have an european BV9900 EEA received with rom 'BV9900_EEA_S900AA_V1.0_20200522V12_20200523-0035'
and have a A/B phone.
I compile my own build of TWRP because the only found, doesn't work on my phone.
I flash this image 'lineage-17.1-20201012-UNOFFICIAL-treble_arm64_bvS.img.xz'on the phone without wipe data on first try, but want boot see a lot of error. due to this i wipe data, phone work but a really strange glitch, doesn't disapear. it's the only bug i found for the moment and i need to investigate before issue something here.

For me, your treble check are incorrect. need to recheck with the correct app and if you are sure you have a A only system maybe try another TWRP or build one like me.

**Comment by openStove** [comment]
> Strange, i have a european BV9900 EEA received with rom 'BV9900_EEA_S900AA_V1.0_20200522V12_20200523-0035'
> and i have an A/B phone.
> 
> I have compiled my own version of TWRP because the only version I found does not work on my phone.
> 
> I flashed this image 'lineage-17.1-20201012-UNOFFICIAL-treble_arm64_bvS.img.xz' on the phone without wipe the data on the first try, but on startup it was full of application crashes.
> 
> Due to this i wipe data, the phone works but a really annoying graphics issue does not go away. it's the only bug i found for the moment in 2 hour test and i need to investigate before issue something here.
> 
> For me, your treble check are incorrect. You need to recheck with the correct app and if you are sure you have a A only system maybe try another TWRP or build one like me.
> 
> ps: try this app work great for me > https://play.google.com/store/apps/details?id=tk.hack5.treblecheck
> 
> edit: i found a workaround to the graphical bug, go in Phh Treble Settings > Misc Features > uncheck Disable HW overlays and the bug disapear.

Would you give me your twrp ? It would probably save me time...
Thanks for the advices, I'll try this later today !

**Comment by openStove** [comment]
You were write, the app you mentioned tell me I've a A/B phone, and the other treble check app told me A-only... I think I have the same as you

**Comment by Elenedeath** [comment]
for sure this is my build something doesn't work like mtp usb and usb OTG, i work on this.
But backup and restore on internel and external storage work.
Need to try encryption backup but for the rest, it's fine.

https://github.com/Elenedeath/twrp_device_Blackview_BV9900/releases/download/V0.1-alpha/TWRP340-BV9900.img

**Comment by openStove** [comment]
I'm really lost : 
When I flash your twrp, I'm going into bootloop, i'm also not able anymore to boot normaly
When I flash again the stock recovery, I'm able again to boot to both recovery and system... why?

**Comment by Elenedeath** [comment]
maybe not the same phone has me or maybe my recovery are phone specific, not a pro of TWRP compilation but do the job.

Send me your recovery and i check and try to compile a custom one for your phone.I can check if you have something different than my stock recovery.

**Comment by dammy123** [comment]
Can I also send my stock recovery I also need twrp I usually work with adb

**Comment by Elenedeath** [comment]
yes i want your stock recovery

**Comment by openStove** [comment]
Hi Elene,
I updated the recovery here, but actually is the one from the stockrom published by Blackview here : https://bbs.blackview.hk/viewtopic.php?f=291&t=532819

https://github.com/openStove/bv9900

**Comment by openStove** [comment]
Could you tell me how to you flash twrp ? over sp_flash_tool oder flashboot ?

**Comment by 007fred50** [comment]
Hello,

have you a twrp file? if so boot into fastboot
(fastboot boot twrp.img) wait for the boot-logo boot up

does that help you?

**Comment by openStove** [comment]
After a lot of trial error, what I was missing was flashing vbmeta...

So here for the next newbies, what worked by me, thank to the help I get :
`fastboot -u flash system lineage-17.1-20201215-UNOFFICIAL-treble_arm64_bvS.img
`

And then using stock rom images : 

`fastboot -u flash --disable-verity --disable-verification  vbmeta BV9900_EEA_S900AA_V1.0_20191225V08_user_20200103_2/vbmeta.img `

`fastboot -u flash userdata  BV9900_EEA_S900AA_V1.0_20191225V08_user_20200103_2/userdata.img`

**Comment by Gaeldrin** [comment]
@openStove you absolutely amazing human being, I just want to say THANK YOU as I spent last couple of days trying to figure this out with no success - I even saw one or two places mention flashing vbmeta but **nowhere** any specific instructions on how/when to do it. Again, thank you for thinking about writing the info.
