### ISSUE TITLE
[Note 20ultra Snapdragon 11.0 v300.f] broken brightness and MTP

### ISSUE THREAD

**Issue by manofsteel2017** [phhusson/treble_experimentations#1535]
Hi Phh,
Seems like everything is working on note 20
Only thing that's broken is brightness, fingerprint and MTP
Logs below. 
[alogcat.2020-10-16-10-32-28-0400.txt](https://github.com/phhusson/treble_experimentations/files/5392331/alogcat.2020-10-16-10-32-28-0400.txt)

**Comment by phhusson** [comment]
How broken is brightness?

Le ven. 16 oct. 2020 à 16:33, manofsteel2017 <notifications@github.com> a
écrit :

**Comment by manofsteel2017** [comment]
Broken as the slider stays at one place.
Full brightness 😂😂😂

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by manofsteel2017** [comment]
also broken on android 10 too
however google gsi had it working. only problem it randomly froze and rebooting makes it unusable

**Comment by phhusson** [comment]
the freeze and reboots happen on my GSI too?

Le ven. 16 oct. 2020 à 20:03, manofsteel2017 <notifications@github.com> a
écrit :

**Comment by manofsteel2017** [comment]
No your gsi is fine
Only stuff I mentioned above are broken.

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by manofsteel2017** [comment]
brightness and MTP working now

**Comment by datwenjie** [comment]
Hi, may I know how to flash GSi on Note 20 Ultra??
