### ISSUE TITLE
New Installing This Proyect

### ISSUE THREAD

**Issue by FsDefalt** [phhusson/treble_experimentations#1538]
Hi there!! I comment here the "issue" because I need a little bit of help :) 

I have an **Honor 7C (LND-L29)** with **Android 8.0.0** and **EMUI 8.0.0** and today i've discovered this proyect which PHHUSSON is working on and it looks so good. This are my phone's specs: 

**CPU's ARCH:** _ARMv8-A_ 
**Kernel's ARCH:** _aarch64_
**Unlocked Bootloader:** _YES_
**Custom Recovery:** _YES (TWRP 3.2.1)_

The thing is, i went to the github page where the last release is (https://github.com/phhusson/treble_experimentations/releases/tag/v222) but I exactly don't understand how can I flash the image in my phone because I always have installed all my ROMs in .zip files.

I hope you could help me, thanks btw.

**Comment by reverseflash2** [comment]
1. Download and extract the .img file.
2. Put your device in fastboot mode
3. Enter:Fastboot erase system
4. Enter: Fastboot flash system xxx.img

Note: replace the xxx with the file name

**Comment by FsDefalt** [comment]
Okey but, what about the specs?? Do I have to choose one in particular from those on that page?

**Comment by reverseflash2** [comment]
Is your device a only or a/b partition?

**Comment by reverseflash2** [comment]
Ur device is arm right?

**Comment by reverseflash2** [comment]
Download the arm a or a/b with or without gapps

**Comment by FsDefalt** [comment]
My device is ARMv8-A and about partition, treble check is saying that i have one partition of only a

**Comment by reverseflash2** [comment]
Wait a minute is ur device treble compatible?

**Comment by FsDefalt** [comment]
Yup, Treble check sais 

Proyect Treble
Supported

**Comment by reverseflash2** [comment]
Ok but does it say treble compatible?

**Comment by FsDefalt** [comment]
It's in spanish but if u want i can send a picture

**Comment by reverseflash2** [comment]
Ok do u need gapps?

**Comment by FsDefalt** [comment]
![IMG_20201019_200316.jpg](https://user-images.githubusercontent.com/71466761/96494105-2dc79f80-1246-11eb-9c86-f040ee55cfe6.jpg)

There it is, and yes I need them I suppose

**Comment by reverseflash2** [comment]
K then download the arm a only gapps . Do u want me to link the file?

**Comment by FsDefalt** [comment]
Please, if is not a problem

**Comment by reverseflash2** [comment]
Paste this is ur browser


https://github.com/phhusson/treble_experimentations/releases/download/v222/system-quack-arm-aonly-gapps.img.xz

**Comment by FsDefalt** [comment]
K done, one thing, are you sure this will work? i mean, if I share my phone's specs of Droid Info can you confirm to me if the file you send is which i need please?

**Comment by reverseflash2** [comment]
It should

**Comment by reverseflash2** [comment]
Tell me if it doesn't work

**Comment by reverseflash2** [comment]
Share ur phones specs with me so I can be sure it works

**Comment by FsDefalt** [comment]
![IMG_20201019_201157.jpg](https://user-images.githubusercontent.com/71466761/96495045-8ea3a780-1247-11eb-88e4-fae64f2ad3dc.jpg)

![IMG_20201019_201141.jpg](https://user-images.githubusercontent.com/71466761/96495063-9400f200-1247-11eb-92a9-f971f7c015bf.jpg)

This are my phone's specs

**Comment by reverseflash2** [comment]
I'm pretty sure it will work if not tell me

**Comment by FsDefalt** [comment]
Ok, I'm very nervous that's why i'm asking a lot...

**Comment by FsDefalt** [comment]
Now this says, select partition to flash image

Cust image
odm image
product image
system image
vendor image
version image 

Do i have to choose anyone or not

**Comment by FsDefalt** [comment]
Bootloop...

**Comment by reverseflash2** [comment]
Choose system

**Comment by reverseflash2** [comment]
Try disable dm verity?

**Comment by FsDefalt** [comment]
how

**Comment by reverseflash2** [comment]
Join this telegram group there will be more help available:logs&device&gsi
version – #phh-treble - It's never ~lupus~ vendor problem
https://t.me/phhtreble/283195 <---

Read before any question ^^^
https://t.me/phhtreble

**Comment by ger-serega** [comment]
ARM64 A

**Comment by sale2000** [comment]
your device is Arm 64. Please flash as systemimage
example:
system-quack-arm64-aonly-vanilla.img.xz

after you flash - remember to format user-data partition. In TWRP you need to type YES (not sure if TWRP is in spanish). and also factory reset from TWRP. If it works then type here.

**Comment by devrieshh** [comment]
you have to extract the xz file so it is ....vanilla.img   than put your phone in fastboot mode...  adb reboot fastboot (or with buttons power and volume up) than ....
fastboot flash system  system-quack-arm64-aonly-vanilla.img
ab-gapps
if that doesnt work (with my elephone e10) you have to do ...adb reboot fastboot  (in fastbootd menu) and do   ./fastboot flash system  system-quack-arm64-.aonly-vanilla.img
