### ISSUE TITLE
Samsung Galaxy Note 10+ 5G No Headphone Audio

### ISSUE THREAD

**Issue by kaldigo** [phhusson/treble_experimentations#1542]
When I use USB-C headphones the buttons work but i am getting no audio coming through. Bluetooth headphones work fine. Here is the link to my audio_policy_configuration.xml as I have heard that it needs to be changed to fix the issue but I cant find an information how it needs to be changed. https://pastebin.com/mdCehec7

**Comment by phhusson** [comment]
Qualcomm or exynos variant?
If it's Qualcomm variant try "use alternate audio policy" ln Qualcomm
settings in treble settings

Le lun. 26 oct. 2020 à 19:08, Igor Kaldowski <notifications@github.com> a
écrit :

**Comment by igorkaldowski** [comment]
Its the exynos varient.

**Comment by igorkaldowski** [comment]
I took a look at the files in the folder and found the usb_audio_policy_configuration.xml. I don't know if that helps or if I have to merge the 2 somehow. Here is the link:
https://pastebin.com/FPKr4g2b
