### ISSUE TITLE
Oneplus 7T No VOLTE/Wifi Calling

### ISSUE THREAD

**Issue by gonzalezb** [phhusson/treble_experimentations#1543]
On the OnePlus 7T VOLTE/WIFI calling do not work so you have to switch from LTE to 3G just to make a call and text and go back to LTE to use data using data settings. This is the only thing keeping me from going to it as a daily if you know of any tricks to get it working on current version please let me know.

**Comment by gonzalezb** [comment]
Even if Volte can not be done that is fine but i want to be able to call and text while on LTE.

**Comment by phhusson** [comment]
Install http://treble.phh.me/stable/ims-q.64.apk reboot, wait 2 minutes, reboot, wait 2 minutes, you should be good to go.

**Comment by gonzalezb** [comment]
Thank you very much didn't even have to reboot it worked right away.
