### ISSUE TITLE
[ASUS Zenfone 5 (2018)] Unable to boot v300.f/g

### ISSUE THREAD

**Issue by AndyCGYan** [phhusson/treble_experimentations#1553]
Device: ASUS Zenfone 5 (2018)
Treble status: Yes, non-SaR A-only, native
Stock Android version: 8 (VNDK 26) or 9 (VNDK 28)

Neither versions of stock base would boot v300.f/g. Stock 8 base does a splash loop, while 9 base reboots after splash into the bootloader.
In both cases, after rebooting into TWRP to check, pstore and last_kmsg are absent.
Tried changing fstab to use EXT4 data (ASUS likes F2FS), no change.
Android 10 GSIs boot normally.

**Comment by AndyCGYan** [comment]
After some difficulty in building kernel, I finally enabled pstore and got some ramoops - see if it's of any use?
[pstore.zip](https://github.com/phhusson/treble_experimentations/files/5505036/pstore.zip)

**Comment by phhusson** [comment]
I attach here for the reference the logs of a device that succeeds to boot a-only (Moto E5, vndk 26, arm32)

[logs.txt](https://github.com/phhusson/treble_experimentations/files/5505543/logs.txt)


What I see as difference is:
```
[    6.118942] (CPU:5-pid:1:init)audit: type=1400 audit(9876167.109:9): avc:  denied  { create } for  pid=1 comm="init" name="system_ext" scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=lnk_file permissive=0
[    6.118988] (CPU:5-pid:1:init)init: Command 'symlink /system/system_ext /system_ext' action=early-fs (/system/etc/init/apex-setup.rc:18) took 0ms and failed: symlink() failed: Permission denied
```
so add a `allow init system_file:lnk_file create_file_perms;` in device/phh/treble/sepolicy/init.te and try again

**Comment by AndyCGYan** [comment]
@phhusson I don't have an AOSP workspace though, and according to others' reports, only AOSP boots on A-only so far. Can I modify this on-device myself, or get a test build from you?

**Comment by phhusson** [comment]
https://treble.phh.me/s-zf5.img.xz

**Comment by AndyCGYan** [comment]
Yes that's it, booted! It lags compared to Q, but that's not the concern here.
Please push the fix (if it doesn't impact other devices that is); I'll close this issue now.
