### ISSUE TITLE
Can't flash into Xiaomi 10 lite zoom, always auto reboot.

### ISSUE THREAD

**Issue by t0of** [phhusson/treble_experimentations#1555]
Can't flash into Xiaomi 10 lite zoom, always auto reboot.
Plz

**Comment by phhusson** [comment]
You meanbthag you can't even finish fastboot flash system and it reboots
before that the end?

Le dim. 1 nov. 2020 à 19:18, SeventhFlow <notifications@github.com> a
écrit :

**Comment by xsquad-pro** [comment]
After the logo is displayed, after shaking, repeat this step.

**Comment by t0of** [comment]
unsubscribe
