### ISSUE TITLE
[Meizu M2 mini] [AOSP 11] no sound

### ISSUE THREAD

**Issue by ger-serega** [phhusson/treble_experimentations#1559]
Meizu m2 mini, MTK 6735, ARM64 A, VENDOR 9 ANDROID
Installed firmware - AOSP 11.0 v300.i
There is no sound (call, messages, alarm clock), only the sound of touching the screen works.  Some audio players play mp3 files.  There is a problem with playing video files.  The log is attached.
[logcat_11-04-2020_12-39-58.txt](https://github.com/phhusson/treble_experimentations/files/5488522/logcat_11-04-2020_12-39-58.txt)

**Comment by phhusson** [comment]
What device?
Which GSI?

**Comment by ger-serega** [comment]
Meizu m2 mini, MTK 6735, ARM64 A, VENDOR 9 ANDROID
Installed firmware - AOSP 11.0 v300.i

**Comment by yura73** [comment]
similar problem
elephone solider
mtk6797t arm64a only
vendor 8.0.0(oreo)
AOSP 11.0 v300.i
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/5489552/logcat.txt)

**Comment by phhusson** [comment]
@yura73 
1.  No this isn't related
2.  https://github.com/phhusson/treble_experimentations/issues/874#issuecomment-555740688 says you got it fixed...?

**Comment by phhusson** [comment]
@ger-serega well, considering this isn't an official OEM vendor, I can only assume this is a bug of your vendor.
Unless the issue doesn't happen on other of my AOSP GSI.

**Comment by yura73** [comment]
> @yura73
> 
> 1. No this isn't related
> 2. [#874 (comment)](https://github.com/phhusson/treble_experimentations/issues/874#issuecomment-555740688) says you got it fixed...?

sound works great on all your releases except aosp v300

**Comment by ger-serega** [comment]
Similarly, in releases with 10 android, the sound works, but in releases with 11 android, there is no sound.

**Comment by yura73** [comment]
[Music.zip](https://github.com/phhusson/treble_experimentations/files/5493502/Music.zip)
in my opinion the problem is that this application does not work

**Comment by ger-serega** [comment]
OK, but then why are the sound problems selective - the sound of unlocking the screen and touching the screen works and the rest do not?

**Comment by yura73** [comment]
https://github.com/phhusson/treble_experimentations/issues/1611#issuecomment-745096731

**Comment by ger-serega** [comment]
problem solved
