### ISSUE TITLE
build-dakkar.sh | Warning: request a ThreadPool with 1 threads, but LLVM_ENABLE_THREADS has been turned off

### ISSUE THREAD

**Issue by nexus76** [phhusson/treble_experimentations#156]
Hello,

I tried to compile
bash ../treble_experimentations/build-dakkar.sh lineage160 arm64-ab-gapps-nosu
on Ubuntu 18.04 but the job quits here:

Warning: request a ThreadPool with 1 threads, but LLVM_ENABLE_THREADS has been turned off
clang-6.0: error: unable to execute command: Aborted (core dumped)
clang-6.0: error: linker command failed due to signal (use -v to see invocation)
ninja: build stopped: subcommand failed.
18:06:38 ninja failed with: exit status 1
thanks & regards

**Comment by phhusson** [comment]
This log isn't an error. It is just a warning.
You should give much more logs

**Comment by nexus76** [comment]
in out/soong.log I found more details
2018/08/29 00:20:34.919922 build/soong/ui/build/exec.go:95: ninja failed with: exit status 1
which log do you want to see?

**Comment by bju2000** [comment]
for use option -j (your cpu max theread x2)?

**Comment by Shadowghost** [comment]
This warning shouldn't prevent you from compiling the image. I have it too, but after some research I'm not sure if we should change that variable after all.
You can change it by exporting it with a parameter, eg `export LLVM_ENABLE_THREADS=<value>`

**Comment by friendlymaninthisworld** [comment]
@Shadowghost does "<value>" = 1 or what?
