### ISSUE TITLE
[Chuwi Hi9 Air] [AOSP 11] Reboot to recovery after Android logo screen (RescueParty)

### ISSUE THREAD

**Issue by santosst3** [phhusson/treble_experimentations#1562]
Device name: Chuwi Hi9 Air
AOSP version: ROAR v300i A-only vanilla (same behaviour at 300f and 300g versions)
Vendor version: Oreo VNDK26

The device loads the Android logo screen and after some time (~6min) it reboots to recovery.
console-ramooops and last_kmsg files were taken after trying to boot v300i.

[console-ramoops_v300i.txt](https://github.com/phhusson/treble_experimentations/files/5491591/console-ramoops_v300i.txt)
[last_kmsg_v300i.txt](https://github.com/phhusson/treble_experimentations/files/5491592/last_kmsg_v300i.txt)

log_cleanflash2_v300g was obtained with v300g, this is the logcat with the last messages before the "promp_and_wipe_data" command and rebooting to recovery. I was not able to get the same log file with v300i but I suppose that is the same problem.

[log_cleanflash2_v300g.txt](https://github.com/phhusson/treble_experimentations/files/5491593/log_cleanflash2_v300g.txt)

I am available if any other information or log file is needed, or if you want to test something in my device. Thank you very much.

**Comment by santosst3** [comment]
Following phh's recommendations, I added "libstdc++.so" to /system/system_ext/apex/com.android.vndk.v26/etc/vndksp.libraries.26.txt. It was enough to solve the reboot to recovery problem.
I also added "liblogwrap.so" to the same file and pushed this lib via ADB to /system/system_ext/apex/com.android.vndk.v26/lib64 (I got it from my stock ROM in /etc/lib64). With these two modifications, the system no longer has linker errors on log.

[vndksp.libraries.26.txt](https://github.com/phhusson/treble_experimentations/files/5506946/vndksp.libraries.26.txt)

However, the boot process stuck on Android boot animation. This is the obtained log file:

[log_new_ldconfig.txt](https://github.com/phhusson/treble_experimentations/files/5506949/log_new_ldconfig.txt)

**Comment by phhusson** [comment]
What's the kernel version?

**Comment by phhusson** [comment]
In the logs I see:
`03-01 00:37:33.024  5192  5192 I zygote  : fcntl(F_ADD_SEALS) failed: Invalid argument, no memfd support.`

I'm guessing this is related to:
https://android-review.googlesource.com/c/platform/external/perfetto/+/1376217

Now, this doesn't have to be an issue, because it says:
`03-01 00:37:33.024  5192  5192 I zygote  : Falling back to ashmem implementation for JIT zygote mapping`

But then this triggers:
`03-01 00:37:33.023  5192  5192 W main    : type=1400 audit(0.0:218): avc: denied { execute } for path="/dev/ashmem" dev="tmpfs" ino=10276 scontext=u:r:zygote:s0 tcontext=u:object_r:ashmem_device:s0 tclass=chr_file permissive=0`

**Comment by santosst3** [comment]
Kernel version is 3.18.60. If I understand correctly, a bigger problem would occur with kernel versions <3.17, correct?

However, I saw it in a log of Quack v222:
`08-05 19:49:34.684 18100 18100 I ashmem  : memfd: device VNDK version (26) is < Q so using ashmem.`

So I think Chuwi Hi9 Air doesn't support memfd.

**Comment by santosst3** [comment]
An update: I tried to boot v300i again with the updated "vndksp.libraries.26.txt" file AND force-encrypt disabled through [disabler tool by Zackptg5](https://forum.xda-developers.com/android/software/universal-dm-verity-forceencrypt-t3817389/post77091359) (which disables dm-verity too), and the system boots well.

I think the zip doesn't touch in anything but the boot partition, so I am led to believe that there is a problem with decrypting the data partition. I don't know if it's related, but in the sent log file, the following line is repeated several times:

`03-01 00:36:58.147   746   746 I MAL-Daemon:  (     check_decrypt_ready,  180) vold.decrypt = `

**Comment by santosst3** [comment]
UPDATE: The problem is related to the encryption of the data partition. It's a common issue in R builds; some users reported it on the TG group: when they don't set a pattern for screen lock in the first boot, the device gets stuck on boot animation after rebooting.

However, since the Hi9Air reboots in the first boot, the user isn't able to set up the secure boot, and therefore the system gets stuck on the boot animation.

The most obvious workaround is to disable force-encrypt (for example, installing the [disabler tool](https://forum.xda-developers.com/android/software/universal-dm-verity-forceencrypt-t3817389/post77091359)); however, I found two workarounds to suppress this problem for users that wish for an encrypted data partition:

1- Install quack-v222, setup the secure boot and dirty upgrade to roar;
2- Temporarily disable the force-encryption, install roar and boot it once, then restore /boot and /vendor partitions, reboot again and set up the secure boot (when you do this, the system does not restart during boot, but even so the /userdata partition is encrypted).

I will close this issue since it's a bit far from the initial problem, which is solved since v300j.
