### ISSUE TITLE
Fod icon won't appear even after setting required fp files in vendor

### ISSUE THREAD

**Issue by sdn1324** [phhusson/treble_experimentations#1568]
Overall the latest aosp was pretty good but had these issues-
1) no fp initially but got fingerprint setup option in settings after putting up necessary fp files in vendor.
2)no volte and vowifi settings
Device- Realme X2 Pro (RMX1931EX)

**Comment by phhusson** [comment]
On what? Latest release (AOSP 10) or latest alpha (AOSP 11)?

**Comment by sdn1324** [comment]
On latest A11 alpha

**Comment by phhusson** [comment]
Yup that version doesn't have fod support.

**Comment by sdn1324** [comment]
Cool thanks for the headsup!
