### ISSUE TITLE
VoLTE and Mediatek

### ISSUE THREAD

**Issue by HemanthJabalpuri** [phhusson/treble_experimentations#1598]
@phhusson
I am user of your GSI using CAOS(based on v222 Q) in Xiaomi Redmi Note 9 merlin_in Mediatek Helio G85 chipset which came preinstalled with Android 10(Q).

In telegram group you said you need a MTK device with Android 10 vendor and you bought Realme C11 for this. Xiaomi Redmi Note 9, I am using has above requirement. But how can I help you?

VoLTE in Mediatek is like a dream I think. Many devices are having this issue(may be all?). In INDIA there is a SIM called JIO(www.jio.com), which ONLY works on 4G LTE mode i.e., we can't use it in 3G or 2G.

If we use JIO in GSI there only Mobile Data works with the support of LTE but cannot dail or receive calls, messages(because of VoLTE not working).

Some says that it is possible to support VoLTE in Mediatek, below are some of those links.
=>https://github.com/techyminati/mediatek_volte_fix this I can't use, in Android 10 I don't know how to modify system partition.(adb remount fails)

=>https://medium.com/swlh/modding-the-redmi-note-8-pro-an-adventure-e473e84d4d14

=>https://forum.xda-developers.com/search.php?searchid=469386569 which has VoLTE fixed ROMs for some devices.

=>https://www.xda-developers.com/xiaomi-edl-unbrick-authorized-mi-accounts

=>https://workifytech.com/freelance-jobs/volte-on-mediatek-gsi-1327

If someone are free to develop something that fix VoLTE, I will provide the things like logs, apks, screenshots etc.

Similar issues:- #1501, #1400, #1306, #869, #405, #423

Thanks

**Comment by HemanthJabalpuri** [comment]
Closing this since @phhusson got his Realme C11 unlocked today and testing in it.

**Comment by HemanthJabalpuri** [comment]
From AOSP R 300j VoLTE is working in Mediatek.
Pictures by @sarthakroy2002
![20201214_125905](https://user-images.githubusercontent.com/39197123/102052718-8497c280-3e0c-11eb-8f7d-f57b91d1e539.jpg)
![20201214_125858](https://user-images.githubusercontent.com/39197123/102052742-8b263a00-3e0c-11eb-9dbf-ea6d17e6c60b.jpg)

**Comment by Tahirpatel12345** [comment]
I tried 5 gsi and I cannot make and receive calls in gsi. It shows call ended. I tried many gsi corvus, crdroid, pixel exp plus, leanage, evolutionx



This problem is only with jio Sim when try with other sim everything works only issue with jio volte



**Smartphone information**

 - Device: [Samsung galaxy a31]

 - OS: [Android 12l,13]

 - GSI Base version: [latest builds of corvus,  pixel exp+, crdroid, leanage, evolutionx]

**Comment by ayusc** [comment]
Post in thread 'Jio sim is not working with #LineageOS' https://xdaforums.com/t/jio-sim-is-not-working-with-lineageos.4625489/post-89416859
