### ISSUE TITLE
How 

### ISSUE THREAD

**Issue by kokodeawa** [phhusson/treble_experimentations#1605]
How I download correctly the ANDROID 10 GSI ROM files for the J4 2018 I am not clear, I'm just a newbie but I am very determined to update my device: c
https://theupgradeguide.com/install-android-10-on-galaxy-j4-aosp-gsi-treble-rom-how-to-guide/

**Comment by Djsmk123** [comment]
https://github.com/phhusson/treble_experimentations/releases/tag/v222 
download any with tagged arm32_binder64-a-only

**Comment by AnthonyKeyYT** [comment]
Hola por el nombre me parece que hablas español, para empezar, tu dispositivo tiene liberación permanente en caso de pertenecer a alguna compañía? Si la respuesta es sí, o ya está liberado, lo siguiente es instalar el TWRP, para eso buscas la versión más reciente en la aplicación de TWRP en la Play Store o en la página oficial de TWRP, de ahí si ya conoces los comandos adb, pues simplemente flasheas el recovery, si no sabes de lo que hablo, te recomiendo que busques en Google "como flashear TWRP en *nombre de tu dispositivo*" otra cosa que te recomiendo buscar es si tú teléfono tiene el bootloader desbloqueado o también conocido como Desbloqueo OEM, de ahí ya comienza lo más fácil, de ahí solo descargas esta imagen del sistema:
https://github.com/phhusson/treble_experimentations/releases/download/v222/system-quack-arm32_binder64-aonly-gapps.img.xz
Esta te incluye las aplicaciones de Google, la colocas de preferencia en una micro SD y reinicias tu teléfono en modo recovery, puedes escribir en adb mientras tú teléfono está encendido el comando: adb reboot recovery
O puedes hacerlo manualmente apagando tu teléfono y después solo precionas la tecla de encendido y la de volumen abajo (la tecla puede variar según el dispositivo, te recomiendo que busques como reiniciar en modo recovery) ya estando dentro del TWRP te recomiendo hacer una copia de respaldo, en el propio TWRP se puede en la opción backup, después de hacer la copia de vas a wipe y selecionas system desliza y cuando termine, te vas a install, cambias el modo de .ZIP a .ISO y ahora solo buscas la imagen del sistema, ya sea en la micro SD o donde la hayas puesto, realizas y en teoría ya debería de estar instalada la imagen.

**Comment by kokodeawa** [comment]
Gracias por la explicacion agradesco un monton <3
