### ISSUE TITLE
[HELP] Impossible to create a working vendor overlay

### ISSUE THREAD

**Issue by UDPSendToFailed** [phhusson/treble_experimentations#1608]
I'm trying to create an overlay to fix the automatic screen brightness, but it doesn't change anything. I have tried with both _framework-res.apk_ and _framework-res__auto_generated_rro_vendor.apk_, none of them worked. 
Sensor testing apps like AIDA64 can read the light sensor, but the system itself doesn't, I think the patch doesn't even get loaded.

![image](https://user-images.githubusercontent.com/16057404/101241301-1446be00-36f5-11eb-9ad4-ccfeb5b579b2.png)

Is it possible to fix this, or I'm stuck with changing the brightness manually?

Here is the device's folder which I have added: 

https://github.com/UDPSendToFailed/vendor_hardware_overlay/tree/master/Samsung/T590

**Comment by gsihelp** [comment]
I think you need to put your apk in 

` /system/product/overlay
`
See this post: https://forum.xda-developers.com/t/gsi-10-lineageos-17-x-gsi-all-archs.4004673/post-84147613

**Comment by UDPSendToFailed** [comment]
Thanks for the idea! I did that, and nothing changed, the auto-brightness function is still not working. :/
