### ISSUE TITLE
AOSP 11.0 v300.j\AOSP 11.0 v300.i\ Ringtones do not work. Media files do not play.

### ISSUE THREAD

**Issue by yura73** [phhusson/treble_experimentations#1611]
the problem is that it is impossible to install ringtones and play media files on the vendor 8.0.0 mtk 6797t processor.
the logs have this

-09 11:51:28.879  5448  5448 W MediaCodecsXmlParser2: unable to open media codecs configuration xml file: /data/misc/media/media_codecs_profiling_results.xml
12-09 11:51:28.879  5448  5448 W MediaCodecsXmlParser2: parseTopLevelXMLFile(/data/misc/media/media_codecs_profiling_results.xml) failed
12-09 11:51:28.879  5448  5448 E MediaCodecsXmlParser2: Cannot find the role for a decoder of type audio/x-adpcm-dvi-ima
12-09 11:51:28.879  5448  5448 E MediaCodecsXmlParser2: Cannot find the role for a decoder of type audio/x-adpcm-ms
12-09 11:51:28.879  5448  5448 E MediaCodecsXmlParser2: Cannot find the role for a decoder of type audio/alac
12-09 11:51:28.880  5448  5448 E MediaCodecsXmlParser2: Cannot find the role for a decoder of type audio/ape
12-09 11:51:28.880  5448  5448 E MediaCodecsXmlParser2: Cannot find the role for a decoder of type audio/x-ms-wma
12-09 11:51:28.880  5448  5448 E MediaCodecsXmlParser2: Cannot find the role for a decoder of type video/divx
12-09 11:51:28.880  5448  5448 E MediaCodecsXmlParser2: Cannot find the role for a decoder of type video/divx3
12-09 11:51:28.880  5448  5448 E MediaCodecsXmlParser2: Cannot find the role for a decoder of type video/x-ms-wmv
12-09 11:51:28.880  5448  5448 E MediaCodecsXmlParser2: Cannot find the role for a decoder of type video/xvid
12-09 11:51:28.881  5448  5448 I ServiceManagement: Removing namespace from process name android.hardware.media.omx@1.0-service to omx@1.0-service.
12-09 11:51:28.881   233   233 W         : (5)[233:hps_main][HPS] (0x70E1)(0)<1>(2) action end (257)(359)(0) (0)(0)(1) (4)(4)(2)(0)(1)(0) (0)(257)(0)(0) (0)<2>(1)
12-09 11:51:28.892  5448  5448 W MediaCodecsXmlParser: unable to open media codecs configuration xml file: /data/misc/media/media_codecs_profiling_results.xml
12-09 11:51:28.892  5448  5448 I ServiceManagement: Removing namespace from process name android.hardware.media.omx@1.0-service to omx@1.0-service.
12-09 11:51:28.893  5448  5448 I android.hardware.media.omx@1.0-service: Treble OMX service created.
12-09 11:51:28.899  5457  5457 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdNativeBacktrace
12-09 11:51:28.900   712   712 I tombstoned: received crash request for pid 1144
12-09 11:51:28.900   712   712 I tombstoned: found intercept fd 512 for pid 1144 and type kDebuggerdNativeBacktrace
12-09 11:51:28.900  5457  5457 I crash_dump64: performing dump of process 1144 (target tid = 1144)
12-09 11:51:28.922     0     0 I         : -(6)[0:swapper/6]Detected VIPT I-cache on CPU6

**Comment by JonnyTech** [comment]
Also on vendor 8.1 (vndk 27) but this is a known issue and @phhusson is aware.

**Comment by yura73** [comment]
problem solved
thank you very much Hami_Do
For Oreo vendor users using R gsi who have media bugs (ringtones, audio / video player ..).
paste the attached file inside the zip into:
/apex/com.android.media/etc/seccomp_policy/mediaextractor.policy
[mediaextractor.zip](https://github.com/phhusson/treble_experimentations/files/5693878/mediaextractor.zip)

(needs root).
link to post
https://4pda.ru/forum/index.php?s=&showtopic=892755&view=findpost&p=102541547

**Comment by JonnyTech** [comment]
I see that the file contains `arm64` references - will it work for `arm` too?

```
@include /apex/com.android.media/etc/seccomp_policy/crash_dump.arm64.policy
@include /apex/com.android.media/etc/seccomp_policy/code_coverage.arm64.policy
```

Maybe this is the important element as it is not in my file:

```
newfstatat: 1
```
I have Oreo vender (vndk27) and remember something about multiple `@include`'s not being parsed correctly. How can they be combined?
