### ISSUE TITLE
AOSP 10 v222 Unable to enable Bluetooth on Teclast M30

### ISSUE THREAD

**Issue by Menion2k** [phhusson/treble_experimentations#1615]
Hi

I have managed to install and launch android 10 v222 Gapps on Teclast M30.

It required relocation of libstd++.so to /vendor/lib

It works quite OK, I am monitoring battery drain, but the biggest problem is that I cannot enable Bluetooth. 

Is there anything I can do, or take loga or similar to troubleshoot it?

Thanks, bye

**Comment by yura73** [comment]
![Screenshot_20201209-223317076](https://user-images.githubusercontent.com/55551619/101684246-c8867280-3a6e-11eb-9e64-5b3361e338d0.jpg)

**Comment by yura73** [comment]
settings/Phh treble settings/misc features

**Comment by Menion2k** [comment]
@yura73 Thank you! Problem solved ;)
