### ISSUE TITLE
AOSP 11 are not booting in Motorola G7 Power

### ISSUE THREAD

**Issue by lordgerox** [phhusson/treble_experimentations#1616]
Edited issue for more specific issue the OS flashed but no boot in any version of a/b images the phone uses snapdragon 632 CPU i flashed a wrong variant?

**Comment by phhusson** [comment]
Previous version worked?

**Comment by lordgerox** [comment]
EDIT :
AOSP 11 booted after flash ARM64 A/B FLOSS VARIANT overwriting pixel experience 10 in B partition
closed issue for now
