### ISSUE TITLE
[Samsung Galaxy S9] stereo speaker not functional

### ISSUE THREAD

**Issue by sepi82** [phhusson/treble_experimentations#163]
Only the speaker on the bottom works.. the earpiece, which acts as a supportive speaker (stereo) on stock S9 ROMs does not work on the GSI - any fix?

**Comment by phhusson** [comment]
This has been done in Lineage:
https://github.com/LineageOS/android_device_samsung_star-common/tree/lineage-15.1/audio

The question is what is the shim needed for. Perhaps we don't need it, or there is a better to set it.
Worst way, this can probably be done with a LD_PRELOAD, but I'd really rather not to.

If we only need audioloader, that's a very easy option to add inside the Treble App, but this needs testing.

**Comment by sepi82** [comment]
Ok.. can you assist me how to assist you with this? ;) I'd be happy to help!

**Comment by phhusson** [comment]
So I gave a quick try at simply calling AudioService::setParameters, and it doesn't work.
I'll check if the shim helps.

**Comment by sepi82** [comment]
Any progress here?

**Comment by sepi82** [comment]
Huhu :)

**Comment by phhusson** [comment]
Another way to fix it:
https://github.com/jesec/android_device_samsung_star-common/commit/d75bfa1080d8c04552e68de2c8ef2bc09b7e615d

**Comment by sepi82** [comment]
Still not working.. :(

**Comment by phhusson** [comment]
Fixed in https://github.com/phhusson/treble_app/commit/7eae005766ae4cd0e04209582d573ac94fd31eb1
