### ISSUE TITLE
AOSP 11 won't boot at Galaxy A10s (SM-A107F)

### ISSUE THREAD

**Issue by stephnradd** [phhusson/treble_experimentations#1635]
After disabling vbmeta, flash magisk-patched boot.img and flash the system, my phone just showed the samsung logo then turn off then showing logo again then turn off again. it loops!

gsi version : system-roar-a64-ab-vanilla.img (11.0 v300j)

**Comment by phhusson** [comment]
Did you try without magisk?

24 déc. 2020 04:58:03 stephnradd <notifications@github.com>:

**Comment by stephnradd** [comment]
Did you mean magisk-patched boot.img? No, i didn't.

Other way, i accidentally figured out how to fix it.
While the phone is looping the boot, turn it off and enter recovery, then do factory reset, reboot system, then let the phone loops the boot once, then enter recovery again, mount system, and reboot system. My phone magically boots into home screen!

**Comment by stephnradd** [comment]
By the way, thanks for your response!

**Comment by Xasya** [comment]
А можно инструкцию как на A107f вы установили прошивку?

**Comment by Xasya** [comment]
Help!!!!

**Comment by qxxt** [comment]
@stephnradd So, after that. Did the magisk work?
