### ISSUE TITLE
Redmi Note 9S A/B partition?

### ISSUE THREAD

**Issue by nitanmarcel** [phhusson/treble_experimentations#1636]
I have a feeling that the wiki for the Redmi Note 9S is wrong. I have the 9 Pro which is the same phone but the global variant while 9S is the India variant. 

The 9 Pro doesn't come with an A/B partition and seamless updates and looking at the firmware download size it doesn't hint to an A/B device, the firmware sizes for both phones look the same.

I've also encountering users saying that they had a newer phone from a specific carrier and they mentioned that while the A only version didn't worked the A/B ones did even if their device where A-only but with `system-as-root` partition.

What problems could this cause? None, but the A/B GSIs usually tend to be bigger so it limits the range of devices it can use, thankfully this is not a problem with Phh's GSIs since they are pretty small.

**Comment by phhusson** [comment]
When it comes to GSI, A-only or A/B doesn't mean having a and b slots( anymore).
Yes your device requires a/b variant, no matter the carrier.

26 déc. 2020 18:29:54 Nitan Alexandru Marcel <notifications@github.com>:

**Comment by nitanmarcel** [comment]
> When it comes to GSI, A-only or A/B doesn't mean having a and b slots( anymore). Yes your device requires a/b variant, no matter the carrier. 26 déc. 2020 18:29:54 Nitan Alexandru Marcel <notifications@github.com>:

Oh, oki. The is for the explanation, I knew that A/B meant only A/B partitions but it looks that changed.

Thanks again
