### ISSUE TITLE
[UMIDIGI One Pro] Don't boot 

### ISSUE THREAD

**Issue by dimusa6** [phhusson/treble_experimentations#164]
When i reboot my phone to try Android P GSI, the logcat says:

`CANNOT LINK EXECUTABLE "/system/bin/sh": library "libdirect-coredump.so" not found`

And that is. Anybody have any solution for it?

**Comment by phhusson** [comment]
Sounds like you set SELinux permissive?

Le ven. 31 août 2018 à 02:59, Diego Muñoz <notifications@github.com> a
écrit :

**Comment by phhusson** [comment]
You have stock boot.img?

**Comment by dimusa6** [comment]
Duplicate libc.so in system/lib and system/lib64, and rename to libdirect-coredump.so

**Comment by phhusson** [comment]
Fixed in V207 by setting LD_PRELOAD to `:` (aka empty but not actually empty)
