### ISSUE TITLE
Tecno Spark 4 Air OTG not working

### ISSUE THREAD

**Issue by HaBeBu** [phhusson/treble_experimentations#1648]
On stock firmware worked...

**Comment by phhusson** [comment]
Cf https://github.com/phhusson/treble_experimentations/issues/1006
Try running ` echo 1 > /sys/devices/platform/tran_battery/OTG_CTL`

**Comment by ailtonallen** [comment]
@HaBeBu I have Pouvoir 2, and I would like to know if you can use mobile data, especially 4G

**Comment by HaBeBu** [comment]
@ailtonallen I can't verity it because I haven't mobile internet

**Comment by HaBeBu** [comment]
@phhusson Not working(

**Comment by phhusson** [comment]
You'll need to give me more infos than that...
Did it say anything when running that command?

**Comment by HaBeBu** [comment]
No, I ran it via sudo

**Comment by HaBeBu** [comment]
I learned somewhere, I can enable software USB-host, when I put file android.hardware.usb.host.xml in /system/etc/permissions.
I can`t do is because /system mounted read-only.

**Comment by phhusson** [comment]
Please take a screenshot of how you tried to run the command I've given you.
You can check with `pm list features` if android.hardware.usb.host is
already declared or not
But if you check USB host via a keyboard/mouse or usb drive, then you don't
need this.
Amd you can remount /system read-write.

**Comment by HaBeBu** [comment]
![Ko0z6GKq_aI](https://user-images.githubusercontent.com/73099219/103545028-08941600-4eb2-11eb-8b02-fa5c7323406f.jpg)
![9KIihBoEAhU](https://user-images.githubusercontent.com/73099219/103545030-0af67000-4eb2-11eb-9234-bc73d340e4c0.jpg)
I tried to remount /system read-write, but it did not works. (I have a/b system, others not works on my phone)

**Comment by HaBeBu** [comment]
@phhusson
I DO IT WITH CONNECTED OTG CABLE AND THIS COMMAND WORKS!!!
THANK YOU!!!
