### ISSUE TITLE
[Question] Upgrading to vndklite variant

### ISSUE THREAD

**Issue by AlleSchonWeg** [phhusson/treble_experimentations#1658]
Hi,
i'm running system-roar-arm64-ab-gapps.img.xz (11.0 v300.j) at the moment. Is it possible to dirty flash 11.0 v300.l and the vndklite version of the image. Because i want r/w access.
Thanks

**Comment by phhusson** [comment]
Yes

8 janv. 2021 08:08:42 AlleSchonWeg <notifications@github.com>:

**Comment by AlleSchonWeg** [comment]
Thank you
