### ISSUE TITLE
[Samsung Galaxy S9] GSI Widevine L3 only?

### ISSUE THREAD

**Issue by sepi82** [phhusson/treble_experimentations#166]
Seems like the GSI on the S9 is confed to Security Level 3 Widevine and tho is NOT able to play HD content from e.g. Netflix. The S9 is actually able to play HD on Netflix with Stock ROMs.

**Comment by bju2000** [comment]
L3 may be forced after bootloader unlock This is not a GSI issue.

**Comment by phhusson** [comment]
Did someone actually check whether L1 is possible on rooted stock ROM, with bootloader unlocked?

**Comment by penn5** [comment]
L1 can never be achieved with an unlocked bootloader.

**Comment by phhusson** [comment]
That's wrong.
Pixels do.
My XZ1 and my Mi9 expose L1 in GSI
I still couldn't test it though.

**Comment by penn5** [comment]
Weird, i thought its a requirement of Widevine to erase keys if they could be comprimised by insecure software. 
At least, huawei do erase them. I've seen it in the logs

**Comment by phhusson** [comment]
That's true. But that applies to the code that can read the widevine key.
On all modern platforms (I'm pretty sure that includes Huawei, and is even required as part of Widevine L1, only L2 wouldn't require it), widevine keys are encrypted with a key that is not accessible from Android in any way.

**Comment by penn5** [comment]
Yeah its encrypted (you can see the decryption in fastboot logs) and its in the TEE. I'm just surprised that they let you use L1 in unlocked bootloader on other devices
