### ISSUE TITLE
Bootloop MT6765 AOSP 11.0 v300.l

### ISSUE THREAD

**Issue by hayzy00** [phhusson/treble_experimentations#1664]
Android 10 64 A/B GSI's all worked great for my device (Oukitel K12) but now for 11 I get stuck on manufacturers boot screen (before Android Logo)  treble check says that VNDK 28 is bundled alongside and supports system as root. 

I have tried 64 ab (as this worked with android 10 GSI) AND VNDKLITE but I get stuck on boot. 

The stock ROM was based on Android 9 and I am now trying to flash system over your 10 GSI.

I did notice that prior to flashing 10 treble check reported that it was a only but no a only ROM would work only ab, now it says ab. 

Any suggestions? 

Great work so far keeping our devices alive!

**Comment by Skyrimus** [comment]
Same problem on ZTE Blade 20 Smart, all Android 10 GSI works fine, MT6771, stock vndk 28, tried arm64_ab_vanilla and arm64_ab_vndklite_vanilla, have bootloop on logo and then turns off with a long vibration

**Comment by bahamut657** [comment]
Can you try following the Cubot Quest guide on Wiki? (follow the GSI 10 flashing guide and ensure to perform twice the `fastboot -w` command - it seems that the first time it does not wipe userdata)

**Comment by hayzy00** [comment]
Thank you for the suggestion. 

Following the guide with the addition of an extra  -w command I managed to get past OEM bootscreen and into Android Bootscreen but it would just hang on that page. 

It is strange because with 10 I did not to do anything except flash Magisk patched boot and gsi as system and it goes straight in. 

One step closer though I guess!

**Comment by phhusson** [comment]
Magisk usually prevents Android 11 from booting

**Comment by bahamut657** [comment]
Yes. Like phusson said you have to flash the stock boot not patched one.
If you follow the guide, It flashes stock boot after `fastboot -w`

**Comment by Skyrimus** [comment]
Ok, i will try flash it with stock boot image, send you later

**Comment by hayzy00** [comment]
Sorry I may not have been clear.

Following the guide you shared but with android 11 with stock boot it gets stuck on android logo.

I was only able to boot android 10 gsi with magisk patched boot image.

**Comment by hayzy00** [comment]
I am still no further with this GSI and this particular phone. I have installed on another phone.

**Comment by hayzy00** [comment]
> Yes. Like phusson said you have to flash the stock boot not patched one.
> If you follow the guide, It flashes stock boot after `fastboot -w`

Yes this is what I did, I flashed stock as described. 

What I was saying was that A10 would only boot with patched boot img. A11 won't boot no matter what I do.

**Comment by hayzy00** [comment]
Solved (Finally!).

here's exactly what I did, some steps may not be necessary but it worked;

$ fastboot -w (will erase all execpt userdata)
$ fastboot -w (will erase all including userdata - first execution will not)
$ fastboot flash boot <STOCKBOOT.img>
$ fastboot flash system GSIimagefile.img
$ fastboot --disable-verity --disable-verification flash vbmeta <VBMETA.img>
$ fastboot reboot

Then boot into recovery,

wipe cache partition,
reboot,
reboot into recovery,
wipe data/factory reset,
reboot.

**Comment by danielehrhardt** [comment]
> Solved (Finally!).
> 
> here's exactly what I did, some steps may not be necessary but it worked;
> 
> $ fastboot -w (will erase all execpt userdata)
> $ fastboot -w (will erase all including userdata - first execution will not)
> $ fastboot flash boot <STOCKBOOT.img>
> $ fastboot flash system GSIimagefile.img
> $ fastboot --disable-verity --disable-verification flash vbmeta <VBMETA.img>
> $ fastboot reboot
> 
> Then boot into recovery,
> 
> wipe cache partition,
> reboot,
> reboot into recovery,
> wipe data/factory reset,
> reboot.

Somehow my device is stuck in fastboot mode

**Comment by hayzy00** [comment]
Which device? 

Make sure you enable secure startup on the rom you are moving from.
