### ISSUE TITLE
it is not possible to install the certificate

### ISSUE THREAD

**Issue by umko9** [phhusson/treble_experimentations#1666]
AOSP 11.0 v300.l
it is not possible to install the adguard program certificate. In manual mode, it is also impossible to install, even when using root access

**Comment by phhusson** [comment]
Have you already checked it there was a known issue open on adguard?

9 janv. 2021 09:02:37 umko9 <notifications@github.com>:

**Comment by umko9** [comment]
no open

**Comment by umko9** [comment]
Manual install work
