### ISSUE TITLE
[Android 11] Any possibility to provide a non-root/Magisk-friendly flavor?

### ISSUE THREAD

**Issue by lss4** [phhusson/treble_experimentations#1667]
It seems AOSP 11 GSI includes phh-su which makes installing Magisk not straightforward.

The following actions must be performed **in correct order** to make Magisk installable (see [this Magisk issue](https://github.com/topjohnwu/Magisk/issues/3593), or precisely, [this comment](https://github.com/topjohnwu/Magisk/issues/3593#issuecomment-754326443)).

1. `mount -o remount,rw /`
2. `mv /bin/resetprop /bin/phh-resetprop`
3. `phh-securize.sh`

The `phh-securize` script **MUST** be executed last (or you won't be able to perform 1 and 2) and the system will reboot afterwards. Then you can reboot to recovery to install Magisk as usual (Canary is recommended).

So the question would be if it's possible to provide a `nosu` flavor that doesn't contain any root-related stuffs (like how it used to be on some Android 10 and earlier GSIs), so one can directly install Magisk on it without going through this.

~~Plus, having a `nosu` flavor would make updating system straightforward as well, as with Magisk, the user in most cases will not need to touch `/system` at all and thus a new GSI build can be flashed right on top of a previous GSI build with a good chance of success.~~

**NOTE:** The procedure's result varies among different GSIs. I tested this on CAOS and [it does not work](https://github.com/eremitein/treble-patches/issues/15#issuecomment-735778405).

**NOTE 2:** It seems the creation of `/system/sbin` and the moving of existing `/system/bin/resetprop` away is necessary even if the ROM is already securized (phh-su not present), or Magisk won't be installed correctly (and leaves an invalid state where Magisk stuffs are present, but cannot be seen by the Manager). As a result, flashing a newer GSI on top of an existing one won't be as straightforward as I have originally thought.

**Comment by pvagner** [comment]
oF2PKS at XDA brought this commit to my attention....
https://github.com/aosp-tissot/device_phh_treble/commit/ff57b50433ac03f31a7550d8418baab50e919fbc

It would be super awesome for devices with no TWRP support.
Also on android 11 system partition is not writable.

**Comment by lss4** [comment]
> oF2PKS at XDA brought this commit to my attention....
> [aosp-tissot/device_phh_treble@ff57b50](https://github.com/aosp-tissot/device_phh_treble/commit/ff57b50433ac03f31a7550d8418baab50e919fbc)
> 
> It would be super awesome for devices with no TWRP support.
> Also on android 11 system partition is not writable.

This would be a good addition. Recent AOSP GSI releases have renamed its default `resetprop` to something else so one should be able to install Magisk without touching the system partition.

Also, if you're using a vndklite Android 11 GSI, the system partition can be mounted r/w. It's the non-vndklite variant on which system partition is not writable.

**Comment by pvagner** [comment]
When the system partition is contained in the super partition system partition is read only no matter what the OS.
I think most modern MTK based devices from xiaomi and sister vendors are made this way.
Adding this would be really helpfull.

**Comment by lss4** [comment]
> When the system partition is contained in the super partition system partition is read only no matter what the OS.
> I think most modern MTK based devices from xiaomi and sister vendors are made this way.
> Adding this would be really helpfull.

Not sure. My Samsung Galaxy Tab S7+ uses a `super` partition, yet TWRP and Multi-disabler can mount stock FW and vndklite GSI (though not bootable at the moment) r/w.

The only situation when mounting system r/w failed was with a non-vndklite GSI (also not bootable at the moment). In that case, Multi-disabler would not be able to mount `/system_root` r/w to conduct changes and complained "Even that attempt failed".

**Comment by jisakiel** [comment]
+1 to this request. Some tablets can't hold the vndklite gapps flavour (too big), so the choice is between gapps and being able to run phh-securize.sh. Also, not every tablet has twrp available or able to mount /system, so flashing some minimal gapps over a phh-securized system is not feasible. 

Magisk brings the ability to pass validation, without which there's no app-store sanctioned way of installing i.e. Netflix :).

**Comment by phhusson** [comment]
Aurora Store lets you install Netflix in very little time, and there is no "is safetynet broken today?" worries

1 mai 2021 00:37:57 Jisakiel ***@***.***>:

**Comment by lss4** [comment]
> +1 to this request. Some tablets can't hold the vndklite gapps flavour (too big), so the choice is between gapps and being able to run phh-securize.sh. Also, not every tablet has twrp available or able to mount /system, so flashing some minimal gapps over a phh-securized system is not feasible.
> 
> Magisk brings the ability to pass validation, without which there's no app-store sanctioned way of installing i.e. Netflix :).

Recently some unofficial GSIs have provided the `bvN` (AB, vanilla, non-root/pre-securized) flavor that this issue is about, just not as common as it was with Android 10 GSIs. With the collision issue (regarding `resetprop`) resolved, there's nothing blocking a successful installation of Magisk on `N` flavors anymore, so I'll be closing the issue.

Just I'm not sure if official phh builds can offer the `N` flavors eventually so users who prefer using Magisk can install it without having to touch `/system` at all (not to mention mounting `/system` r/w is _impossible_ on non-vndklite).

A while ago I installed [NitrogenOS GSI (from braiagsi)](https://sourceforge.net/projects/braiagsi/files/NitrogenOS/20210405/) `bvN` flavor on my Razer Phone 2, which works out-of-box with a Magisk-patched kernel image that all I need is to actually install the Manager itself, and everything works afterwards.

> Aurora Store lets you install Netflix in very little time

I'm yet to try actually using my Google account for Aurora just to be safe, because Aurora Store [clearly violates Google Play Store TOS](https://auroraoss.com/faq/#accounts). Using it anonymously is probably fine, though.

> and there is no "is safetynet broken today?" worries

Truth is, I've hidden myself behind the walls of Magisk Hide for too long that I no longer know how widespread Safety Net (or other similar safety mechanisms) is now. Not to mention when I saw the ["Not Certified" warning and that I couldn't log in to my account](https://github.com/phhusson/treble_experimentations/issues/1784) when I was trying GSI (without Magisk) on my Galaxy S7+, I was surprised because I personally have never actually seen that message before, not even once.

Just because the app did not say anything with rooted devices before, does not mean the app isn't checking for root. At one time I saw this message, "This app will be terminated due to security violation", showed up in one of my games, which I've never seen before (so I suspected something was broken, but the error went away after reboot). That message, as well as the aforementioned Not Certified warning, made me realize that the world has changed too much that I know very little about the present-day world.

By the way, many games have very _vague_ lines in TOS about punishing bad activities that I'm a bit paranoid that being caught for rooting can be considered a bannable TOS violation. As such, I usually enable Magisk Hide on whatever app that I don't trust (including the majority of apps on Play Store), to avoid getting myself into trouble, especially getting myself banned in games that I liked and have invested a lot into, which unfortunately happened to me once before (the game in question, well, was notorious about checking root and even USB debugging).

**Comment by GoedendagMC** [comment]
My device does not have vndklite support, nor does it have TWRP. It's an arm64 a/b (supports system-as-root, does not support seamless upgrades). I am absolutely completely stuck on how to get a GSI working on it with Magisk. Please help...
