### ISSUE TITLE
I have a question, which a/b or a only for SD665 (Realme 5i) ?

### ISSUE THREAD

**Issue by eldiomedes** [phhusson/treble_experimentations#1670]
I'm fairly new to this treble, but was wondering, I checked with 2 apps, one says "to use an a/b rom as system as root avilable", other says "detected to have a only partition"..this got me confused. Device is Realme 5i RMX 2030 (SD665). Thanks.

**Comment by hayzy00** [comment]
Why not just make sure you have the original stock ROM and try both? Then update this post and let us all know! 

My phone said a only but a only ROMs would not work spent hours trying allsorts until I tried a/b which worked straight away!

**Comment by eldiomedes** [comment]
> Why not just make sure you have the original stock ROM and try both? Then update this post and let us all know!
> 
> My phone said a only but a only ROMs would not work spent hours trying allsorts until I tried a/b which worked straight away!

I'll do that. It's just, haven't done any custom rom stuff in a while. Probably Galaxy SII was the last ages ago. I suppose treble supported devices that comes with Android 9 or over, require a/b roms.

**Comment by eldiomedes** [comment]
I'm an idiot. Should have done research properly ..lol. It's written on the FAQ section
Why should I use GSI for A/B devices to some A-only devices? : On Android 9, Google changed the requirements and all devices shipped with Android 9 must use "system-as-root". Before this change, only A/B devices were system-as-root and GSI name was separated by A-only and A/B. For this historical reasons, you have to use GSI for A/B on the devices shipped with Android 9+.
