### ISSUE TITLE
No sound when making call - v300l - on Armor_3W

### ISSUE THREAD

**Issue by oopen** [phhusson/treble_experimentations#1671]
There is no sound when I make a call.
Nether on headphone or speaker.
I don't hear caller and caller don't hear me.

But on call receiving all work. 

Arrmor 3w
v300l

**Comment by bauxitoid** [comment]
Same with Umidigi Power 3.

**Comment by devrieshh** [comment]
same with elephone E10 (Mediatek MT6762 Helio P22, 64-Bit Processor)

**Comment by devrieshh** [comment]
I guess i solved the problem with flashing stock roms vendor.img and boot.img  over the flashed AOSP 11.0 v300.l
 Extracting the stock rom super.img (where the vendor.img in is)with      https://forum.xda-developers.com/t/extract-system-img-vendor-img-and-product-img-from-super-img.4184901/

**Comment by oopen** [comment]
I haver try to flash boot.img & vendor.img
extracted from the last Armor_3W stock rom (GQ3060RF2_AGS62_Ulefone_EEA_20200903_V09（Eu）.zip) this don't work.

No sound when I call
Sometime no sound when I receive a call.

Loudspeaker don't work : volume is minimum.

**Comment by oopen** [comment]
Problem persist with v301 & v302.

Update information :

- No call sound randomly for out/in going calls.
- I don't ear randomly, but caller/called can ear me.

- Secondly loudspeaker have no sound when this occur.
- But when I can ear : loudspeaker has a very low volume level (seam to be not activated), sometime volume peak (like normally) form less than 1 second.

**Comment by oopen** [comment]
No sound, annd sound echo, Fix on v305
