### ISSUE TITLE
Add "Automatically restart RIL" for Mediatek devices loosing radio when out of range

### ISSUE THREAD

**Issue by yura73** [phhusson/treble_experimentations#1678]
Yes, it really helps and the connection is restored, but the phone application does not see the network after that. only reboot helps.
mtk 6797 vendor 8.0.0

**Comment by MMan1982** [comment]
Read please https://github.com/phhusson/treble_experimentations/releases/tag/v300.k

**Comment by phhusson** [comment]
Screenshot?

**Comment by yura73** [comment]
![Screenshot_20210119-105052](https://user-images.githubusercontent.com/55551619/105010588-96d8d200-5a44-11eb-9d10-09be20c9d82c.png)

**Comment by yura73** [comment]
![Screenshot_20210119-105134_Phone](https://user-images.githubusercontent.com/55551619/105010616-a0fad080-5a44-11eb-9d22-9768f319c468.png)

**Comment by bahamut657** [comment]
Hi all
I find a procedure to restore the mobile connection, hoping phhusson can integrate it in "Restart RIL" functionality if it works for all.
The procedure for me is:
1) Reboot phone -> Mobile data are working
2) Press automatically restart RIL -> RIL is restarted and Mobile Data are not working (signaling NO SIM - no Mobile DATA) 
3) Now in the dialer APP, insert  *#*#4636#*#* and open the "connection settings" panel
=> Magically, LTE connection now works (and NO SIM is gone away)

Anyone can test this case on Mediatek device?

**Comment by yura73** [comment]
Unfortunately, your method does not work on my device.

**Comment by bahamut657** [comment]
Hi @yura73 

From your screenshot It seems that not only mobile data are not working but also phone call.
Is It correct?
If so, the problem seems little different from mine.
In my Mediatek, only mobile data breaks after some times the phone Is powered on, but I can perform call without problems(it Is not programmatical, It could happened while driving to another city or if my phone loses signal)

**Comment by yura73** [comment]
Yes, mobile data does not work and it is impossible to make calls

**Comment by bahamut657** [comment]
But does this problem start immediately after boot? Or does it happened only sometimes?
Are your APN configured correctly?

**Comment by yura73** [comment]
This happens after the phone loses connection for natural reasons.  after reboot the connection works

**Comment by yura73** [comment]
APN right

**Comment by yura73** [comment]
try adding to build.prop following lines

ro.telephony.ril_class=MediaTekRIL
ro.telephony.ril.config=fakeiccid

**Comment by poppypundit** [comment]
@yura73 Did the build prop edit work. This seems to be the only bug on 309,  Android 11 builds for me. Does the "Automatically Restart RIL" treble app option work? 
MTK6750T Leagoo T8S.

**Comment by yura73** [comment]
I stopped using gsi because the problem cannot be solved
this is the only 11 gsi problem for my device mtk 6797t

**Comment by poppypundit** [comment]
Thank you for getting back. Many thanks... 🙏
