### ISSUE TITLE
Fast charging on Motorola One Action doesn't work

### ISSUE THREAD

**Issue by Aleksandar1996** [phhusson/treble_experimentations#1682]
I installed AOSP 11.0 v300.l version and noticed that fast charging is not working.

**Comment by phhusson** [comment]
How do you know?

Le dim. 17 janv. 2021 à 18:57, Aleksandar1996 <notifications@github.com> a
écrit :

**Comment by Aleksandar1996** [comment]
Hi, I got the impression that battery was charging slower than before. Maybe it's just subjective feeling. I'll check again on the next charge and close issue if subjectivity is the case.

**Comment by Aleksandar1996** [comment]
Fast charging is working correctly.
