### ISSUE TITLE
Angelican android 10 gogaps

### ISSUE THREAD

**Issue by Pahanchec** [phhusson/treble_experimentations#1683]
[bugreport.zip](https://github.com/phhusson/treble_experimentations/files/5828281/bugreport.zip)
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/5828282/logcat.txt)

**Comment by Pahanchec** [comment]
system-quack-arm32_binder64-ab-go

**Comment by phhusson** [comment]
There is no information about what the issue is.
