### ISSUE TITLE
[Redmi 9c nfc] android 10 no nfc

### ISSUE THREAD

**Issue by Pahanchec** [phhusson/treble_experimentations#1684]
[bugreport.zip](https://github.com/phhusson/treble_experimentations/files/5830145/bugreport.zip)
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/5830150/logcat.txt)

**Comment by phhusson** [comment]
What's angelican? Is that the phone model?

**Comment by Pahanchec** [comment]
Angelican- redmi 9c nfc

**Comment by phhusson** [comment]
ok. Which GSI?

**Comment by Pahanchec** [comment]
system-quack-arm32_binder64-ab-go

**Comment by Pahanchec** [comment]
AOSP 10.0 v222
