### ISSUE TITLE
[Xiaomi Mi 6x] Front flash always on when front camera is used

### ISSUE THREAD

**Issue by markg85** [phhusson/treble_experimentations#169]
Hi,

If the front facing camera is used the flash is always on. Regardless of the flash setting you used.

**Comment by suwakowww** [comment]
When I append some texts (copy from MIUI `/system/build.prop`, thanks for [Tadi's dump](https://github.com/TadiT7/xiaomi_wayne_dump/blob/CORRUPTED---wayne-user-8.1.0-OPM1.171019.011-8.7.12-release-keys/system/build.prop)) to `/system/build.prop`, it seems working normally.
the following texts:
````
#Expose aux camera for below packages
camera.aux.packagelist=org.codeaurora.snapcam,com.android.camera,com.qualcomm.qti.qmmi
vendor.camera.aux.packagelist=org.codeaurora.snapcam,com.android.camera,com.qualcomm.qti.qmmi
#disable UBWC for camera
persist.camera.preview.ubwc=0
persist.camera.stats.test=0
persist.camera.depth.focus.cb=0
persist.camera.isp.clock.optmz=0
persist.camera.linkpreview=0
persist.camera.isp.turbo=1
persist.camera.set.afd=4

#exif info for camera
persist.sys.exif.make=Xiaomi
persist.sys.exif.model=MI 6X

#properties for camera front flash lux
persist.imx376_sunny.low.lux=310
persist.imx376_sunny.light.lux=280

persist.imx376_ofilm.low.lux=310
persist.imx376_ofilm.light.lux=280

#properties for bokeh switch master and slave lux
persist.bokeh.switch.lux=290

#properties for open camera 3 normal mode switch master and slave lux
persist.camera.auxswitch.threshold=330
persist.camera.mainswitch.threshold=419
````

there is also configured dual-camera (append `persist.camera.expose.aux=1` to `/system/build.prop` ), but it's seems still not working. (detected 3 rear cameras, but two of these are the same one, and dual-camera still not working)
