### ISSUE TITLE
Galaxy S10 Lite reboot OEM logo

### ISSUE THREAD

**Issue by amaterasushen** [phhusson/treble_experimentations#1692]
I can't start Android 11 AOSP 11.0 v300.l, it keeps restarting on the OEM logo (samsung logo).

info:
arm64
dynamic partition
installed using TWRP fastbootd.
I'm using the Android 11 vendor on my phone, version TL1.
variant: system-roar-arm64-aonly-vanilla.img.
I only have last_kmsg, there is no pstore.
i am using custom vbmeta to start custom firmware (required on samsung devices).

I tried to format using "fastboot -w" and tried to format using TWRP and it still didn't start. I can't get logcat.

[last_kmsg.txt](https://github.com/phhusson/treble_experimentations/files/5858969/last_kmsg.txt)

update:
I tried to start the Quack variant of Android 11 V222 and it didn't start either. Same problem that I reported.
[last_kmsg-android-10.txt](https://github.com/phhusson/treble_experimentations/files/5859009/last_kmsg-android-10.txt)

**Comment by phhusson** [comment]
You must use ab variant not a only.

22 janv. 2021 23:27:30 Flávio Amorim da Rocha <notifications@github.com>:
