### ISSUE TITLE
Galaxy S9+ (SM-G965F) - Touchscreen unresponsive after phone wakes up from sleep state

### ISSUE THREAD

**Issue by drmarkb** [phhusson/treble_experimentations#17]
Touchscreen is unresponsive after phone wakes up from sleep state. 
OS hasn't frozen, only touchscreen thats unresponsive.

logcat will be uploaded shortly

**Comment by pouyab** [comment]
Same here,is it kernel related or sth? That's the only major problem with the s9+ ROM

**Comment by phhusson** [comment]
I'm still waiting for kernel logs..

**Comment by drmarkb** [comment]
Logs captured: https://drive.google.com/file/d/1soOeO8ttduhTHmic00vzTadyLpf2r9Oj/view?usp=drivesdk

Device powered on, left for a couple of mins and screen was unresponsive on wake up. 
USB mouse then connected to unlock phone and grab syslogs.

**Comment by phhusson** [comment]
Lineage's fix is:
https://github.com/LineageOS/android_kernel_samsung_universal9810/commit/e441595fba61b8f887a105f245213a75c15246d9

**Comment by phhusson** [comment]
I've made an equivalent user-space fix:
https://github.com/phhusson/platform_system_core/commit/047403e9d97281f18f22282daa6851615aacf25c

It is not 100% reliable, I had a fail in an after-noon of tests. But then when it fails, just put the phone back to sleep, wait a bit, wake up again and it's working

**Comment by phhusson** [comment]
Proper fix in https://github.com/phhusson/device_phh_treble/commit/e064c6f3107ad92f8b19891a93104d80e8482935
