### ISSUE TITLE
[Realme 6] Auxiliary cameras aren't being detected on GSI

### ISSUE THREAD

**Issue by daeSundae** [phhusson/treble_experimentations#1704]
Hello there, our auxiliary cameras (Wide Angle and Macro) aren't detected on GSIs.

Device: Realme 6 /RMX2001

These are 
`adb shell dumpsys media.camera` dumps both from Realme UI (cam.txt) and GSI (dump.txt)

[dump.txt](https://github.com/phhusson/treble_experimentations/files/5917270/dump.txt)
[cam.txt](https://github.com/phhusson/treble_experimentations/files/5917273/cam.txt)

and also here the full dump including vendor for Realme 6 as you had requested

https://github.com/pjgowtham/full_oppo6785-user-10-qp1a.190711.020-0b36b6c4f9b3bf3b-release-keys_oppo6785_dump

**Comment by ZanjiDiaz** [comment]
Bro you have full dump of realme 6? the link is no longer working. Thank you

**Comment by daeSundae** [comment]
@ZanjiDiaz https://github.com/SamarV-121/dumps/tree/full_oppo6785-user-10-QP1A.190711.020-0b36b6c4f9b3bf3b-release-keys

**Comment by daeSundae** [comment]
It was fixed with this commit: https://github.com/phhusson/platform_frameworks_av/commit/9baa78c7bd75638e1b9ebd4377596e997275927d  (and when i installed GSI over ColorOS11 - which is the same software version Oneplus Nord 2 was released with.)
