### ISSUE TITLE
Could't boot: Markw

### ISSUE THREAD

**Issue by ivysrono** [phhusson/treble_experimentations#1716]
Xiaomi Redmi 4 Pro / Prime 
markw
A | arm64

All reboot to fastboot:
Phh GSI:
AOSP 11.0 v300.l `system-roar-arm64-aonly-vanilla.img`
AOSP 10.0 v222 `system-quack-arm64-aonly-vanilla.img`

CAOS:
`caos-v300l-210117-arm64-avZ.img`

Havoc GSI:
```
Havoc-OS-v3.12-20201230-Official-arm64-aonly.img
Havoc-OS-v4.1-20210208-arm64-aonly-Official.img
```

The only boot system is `Havoc-OS-v3.12-20201221-markw-Official.zip`

@phhusson @SKULSHADY @eremitein

**Comment by phhusson** [comment]
What device?

11 févr. 2021 07:04:29 ivysrono <notifications@github.com>:

**Comment by ivysrono** [comment]
Xiaomi Redmi 4 Pro / Prime 
markw
A | arm64

**Comment by phhusson** [comment]
Sooooo this isn't with stock unmodified OEM vendor?

**Comment by ivysrono** [comment]
I have flashed https://bigota.d.miui.com/V10.2.2.0.MCECNXM/miui_HM4_V10.2.2.0.MCECNXM_d4251f8a27_6.0.zip firstly, however, useless.

**Comment by phhusson** [comment]
How do you know your device supports Treble?

**Comment by ivysrono** [comment]
1. Your wiki
2. https://github.com/kevintresuelo/treble/releases

**Comment by eremitein** [comment]
> Xiaomi Redmi 4 Pro / Prime
> markw

this device released with Android 6 https://www.gsmarena.com/xiaomi_redmi_4_prime-8263.php
so, device is not Treble compatible

**Comment by ivysrono** [comment]
Checked by https://github.com/kevintresuelo/treble/releases
![Screenshot_Markw](https://user-images.githubusercontent.com/2649544/107840937-9d632b00-6df1-11eb-81dd-0db5e1becbb8.jpg)

https://github.com/phhusson/treble_experimentations/wiki
![图片](https://user-images.githubusercontent.com/2649544/107840964-dd2a1280-6df1-11eb-87d5-cb73c69a4ce4.png)

**Comment by eremitein** [comment]
> Xiaomi Redmi 4 Pro / Prime

this device haven't native Treble support
"First of all, it is important to note that Treble has only been implemented since Android 8.0 Oreo... all smartphones **released natively under Android 8.0 Oreo (or higher) are required to be compatible with Treble**" ([source link](https://es.gearbest.com/blog/new-gear/what-is-treble-and-how-do-i-check-the-compatibility-of-my-device-5806))

> Checked by https://github.com/kevintresuelo/treble/releases

wrong app, use https://play.google.com/store/apps/details?id=tk.hack5.treblecheck

> Havoc-OS-v3.12-20201221-markw-Official.zip

also this is custom device specific ROM, and his vendor i guess is not fully Treble compatible

**Comment by ivysrono** [comment]
So @phhusson may need to edit wiki?

**Comment by ivysrono** [comment]
@eremitein Test by https://play.google.com/store/apps/details?id=tk.hack5.treblecheck
![Screenshot_Markw_1](https://user-images.githubusercontent.com/2649544/107868276-06b07000-6ebe-11eb-8cd2-60e9271ca6cb.jpg)

**Comment by JonnyTech** [comment]
> So @phhusson may need to edit wiki?

The wiki is publically editable.

**Comment by eremitein** [comment]
> @eremitein Test by https://play.google.com/store/apps/details?id=tk.hack5.treblecheck

well, try to boot AOSP 9 GSI - you need Pie vendor for that
(maybe user, who set "markw" in wiki, tested Pie GSI)

**Comment by ivysrono** [comment]
@eremitein After flashed https://github.com/ShihabZzz/Releases/releases from @ShihabZzz , the VNDK Lite Version updated to 30.0
