### ISSUE TITLE
Imidigi A1 Pro AOSP 9.0 v103

### ISSUE THREAD

**Issue by stevea76** [phhusson/treble_experimentations#173]
Force closing, rebooting to lockscreen in general use Umidigi A1 Pro chipset	MediaTek MT6739
graphics	PowerVR GE8100
processor	Quad core, 1.5 GHz, Cortex A53
ram	3 GB

**Comment by stevea76** [comment]
[logcat.zip](https://github.com/phhusson/treble_experimentations/files/2348183/logcat.zip)

**Comment by phhusson** [comment]
8.1 works?

**Comment by stevea76** [comment]
8.1 works (with the known exception of camera/incoming calls)

**Comment by stevea76** [comment]
Many thanks, I will give it a go.

**Comment by stevea76** [comment]
Perhaps I am missing something here, but the option to set GPU renderer is not present in the Developer Options to switch.

**Comment by stevea76** [comment]
In my stock rom developer options set GPU renderer: openGL (default) or openGL (Skia)  Is there a way to set the set the GL via adb commands? as the option is not showing in the developer options Hardware accelerated rendering on 9.0 GSI

**Comment by phhusson** [comment]
Try those two: (it's not persist across reboots)
setprop debug.hwui.renderer skiagl
setprop debug.hwui.renderer opengl

**Comment by stevea76** [comment]
You sir are a genius, problem solved, no more lock ups, fantastic, thank you!

**Comment by stevea76** [comment]
I just need to find a way to make it permanent (sorry did not read the warning not persist across reboots), many thanks again

**Comment by phhusson** [comment]
So which one works for you?

**Comment by phhusson** [comment]
Could you dump your /vendor/lib/egl ?

**Comment by stevea76** [comment]
setprop debug.hwui.renderer opengl this one worked. Will try to dump /vendor/lib/egl (once I have googled frantically how to do so) would this be from my stock vendor file?

**Comment by stevea76** [comment]
[AOSP_9_vendor_lib_egl.zip](https://github.com/phhusson/treble_experimentations/files/2358212/AOSP_9_vendor_lib_egl.zip)
[umidigia1pro_stock_vendor_lib_egl.zip](https://github.com/phhusson/treble_experimentations/files/2358213/umidigia1pro_stock_vendor_lib_egl.zip)

**Comment by phhusson** [comment]
Ok, download https://raw.githubusercontent.com/phhusson/device_phh_treble/android-9.0/rw-system.sh inside your adb folder
then do:

adb root
adb remount
adb push rw-system.sh /system/bin/rw-system.sh
adb reboot

It should fix it permanently

**Comment by stevea76** [comment]
many thanks, this has seemed to have made it permanent. first time it loaded to a blank screen, but factory reset, tried again and all good so far, thank you.

**Comment by stevea76** [comment]
Tested yesterday and all seems good, only had a couple of lock ups which may be related to the device having lots of tasks running at the time, as far as I can tell it is resolved, sent thanks via PayPal for your work on this.
