### ISSUE TITLE
AOSP 11.0 v301 not work music

### ISSUE THREAD

**Issue by umko9** [phhusson/treble_experimentations#1749]
New update is not work yandex music and google music. Not play music track. MTK helio p60

**Comment by umko9** [comment]
No play video wathsapp

**Comment by assoc** [comment]
Can you take some logs via [Logcat](https://play.google.com/store/apps/details?id=com.dp.logcatapp) ([on F-Droid](https://f-droid.org/en/packages/com.dp.logcatapp/))? Clear them before trying video/audio playback, then pause and save.

**Comment by umko9** [comment]
[logcat_03-08-2021_02-03-25.txt](https://github.com/phhusson/treble_experimentations/files/6097959/logcat_03-08-2021_02-03-25.txt)

**Comment by assoc** [comment]
Same thing with audio/mp4a-latm decoder. Should be fixed with [v302](https://github.com/phhusson/treble_experimentations/releases/tag/v302).

**Comment by umko9** [comment]
Fix 302 thx
