### ISSUE TITLE
[Xiaomi MIX 2S] Distorted sound with AOSP 9.0 v104

### ISSUE THREAD

**Issue by rbuehlma** [phhusson/treble_experimentations#175]
The sound for at least Notifications (like Gmail) and Videos (Youtube) is distorted. What Information would help to analyze that?

**Comment by aeppacher** [comment]
Audio is distorted from speakers as well as bluetooth if that narrows it down. Mi Mix 2s

**Comment by aeppacher** [comment]
Can you guys try this [system.img](https://drive.google.com/open?id=1C48hSBlDE8WwsHFiETC2-U2uoDMitbhw) and confirm if this fixes sound. If not, open terminal emulator and type the following commands

```
su
getprop ro.vendor.build.fingerprint

```

and paste the output here

**Comment by rbuehlma** [comment]
Yes, with this image, the sound is fixed for me.

**Comment by dbjungle** [comment]
@aeppacher Sound worked for me on this image as well.  Is the fix something I can replicate on another image?

**Comment by aeppacher** [comment]
@dbjungle https://github.com/phhusson/device_phh_treble/pull/38

**Comment by dbjungle** [comment]
It turns out I don't have those /system/lib/soundfx and /system/lib64/soundfx directories, but I do still have the sound issues on the main img.

**Comment by dbjungle** [comment]
I was able to find it on my device under /system/vendor/lib and /system/vendor/lib64.  I can confirm this fixed the sound on my device as well!  Thanks!

**Comment by rbuehlma** [comment]
This is fixed in v105
