### ISSUE TITLE
(Galaxy A51 4g version) system on read-only

### ISSUE THREAD

**Issue by KatoTempest** [phhusson/treble_experimentations#1766]
The question is that I try to mount the system to be able to test an overlay that I made for this device, but it indicates that the system is in read-only, I am using the vndk lite variant, and I even tried caos that is always in RW, the error continues, but when I put the overlay from the system I receive a bootloop, I will attach a log that I take out of the bootloop
pd. I used adb push and it also tells me that the system is in read-only maybe it has to see that I am using oneui 3.x as a base, thanks for reading me

[bootloop.txt](https://github.com/phhusson/treble_experimentations/files/6168640/bootloop.txt)

**Comment by phhusson** [comment]
Adb root
Adb remount system
Adb reboot
Adb root
Adb remount system

From there you should be able to adb push

19 mars 2021 05:33:00 KatoTempest ***@***.***>:

**Comment by KatoTempest** [comment]
I will try right now, if I have any error I will notify

**Comment by KatoTempest** [comment]
C:\Users\Licht\Desktop\platform-tools_r30.0.5-windows\platform-tools>adb push treble-overlay-samsung-a51.apk /system_root/system/product/overlay
treble-overlay-samsung-a51.apk: 1 file pushed, 0 skipped. 36.7 MB/s (49573 bytes in 0.001s)
adb: error: failed to copy 'treble-overlay-samsung-a51.apk' to '/system_root/system/product/overlay': remote secure_mkdirs failed: Permission denied

**Comment by KatoTempest** [comment]
C:\Users\Licht\Desktop\ahaha\platform-tools_r30.0.5-windows\platform-tools>adb push treble-overlay-samsung-a51.apk /system/product/overlay
treble-overlay-samsung-a51.apk: 1 file pushed, 0 skipped. 52.7 MB/s (49573 bytes in 0.001s)
I work by omitting the system_root, something weird for me

**Comment by phhusson** [comment]
there is no system_root in gsi. I guess you're doing it from twrp instead?

Le ven. 19 mars 2021 à 18:44, KatoTempest ***@***.***> a
écrit :

**Comment by KatoTempest** [comment]
I am doing it from the gsi, the recovery is not very stable to be able to use that

**Comment by KatoTempest** [comment]
Although after putting the apk I have bootloop, I will attach a log

[log.txt](https://github.com/phhusson/treble_experimentations/files/6173217/log.txt)

**Comment by phhusson** [comment]
Well yes, your overlay is broken:
03-19 11:47:16.978  5480  5480 E System  : Caused by:
java.lang.RuntimeException: display brightness threshold array and ambient
brightness threshold array have different length
