### ISSUE TITLE
rip git.rip

### ISSUE THREAD

**Issue by sebagerard** [phhusson/treble_experimentations#1772]
Hello,

First thanks all for the awesome work done here ;-)

I'm trying to build but got error about partner_gms

`<project path="vendor/partner_gms" name="mtkgms/partner_gms" remote="gitrip" revision="11" />`

git.rip website is officially shutted down

Is `mtkgms/partner_gms` mandatory?

Sorry if it's not very clear :-)

**Comment by phhusson** [comment]
It's used for google apps. If you don't plan on building a gapps variant you can remove it from manifest

21 mars 2021 01:13:00 sebagerard ***@***.***>:

**Comment by sebagerard** [comment]
ok thank you ;-)
