### ISSUE TITLE
Nokia 3.2 + AOSP 11.0 v302 and audio (jack and bluetooth)

### ISSUE THREAD

**Issue by SebastienThibaut** [phhusson/treble_experimentations#1774]
Hello,

I've just updated my phone with the latest version of your aosp.
It works great but I have an issue with the audio part.
When I use Netflix, Youtube ou a music player on my phone (like vlc or another app for example), I can hear the sound on the speaker of my phone.

When I plug my earphones, the phone doesn't detect it.
When I pair my bluetooth earphones, they are connected, but doesn't change anything. The sound is always played on the phone's speaker.
I've tried with a JBL headset too.

Finally i've reinstall all the system but it doesn't change anything?

What can I do to solve it ?

Thank you for your help and for your great work.

**Comment by phhusson** [comment]
Try:
- use alternate audio policy in treble settings/Qualcomm settings
- disable a2dp offload in treble settings/misc
- force headset switch in treble/misc
- disable audio effects

22 mars 2021 20:59:21 SebastienThibaut ***@***.***>:

**Comment by skittels15** [comment]
Make overlay for your device. Examples in vendor_hardware_overlay repo

**Comment by SebastienThibaut** [comment]
Hello,

Many thanks for your quick replies.

@ phhusson : unfortunately, it doesn't seem to change anything. The sound continues to be played on the phone's speaker.

@ skittels15 : I'm sorry but i'm not a developper and i don't understand how to add this overlay.

Thank you

**Comment by SebastienThibaut** [comment]
Hello,

I've tried to change settings in phh-treble parameters, but it still doesn't work.
I also try to flash again the rom (i thought it was maybe a parameter i've changed somewhere or an app i've installed). It is the same too.

Could you help me to solve this issue ?

Thank you

**Comment by skittels15** [comment]
> Hello,
> 
> Many thanks for your quick replies.
> 
> @ phhusson : unfortunately, it doesn't seem to change anything. The sound continues to be played on the phone's speaker.
> 
> @ skittels15 : I'm sorry but i'm not a developper and i don't understand how to add this overlay.
> 
> Thank you

https://github.com/phhusson/treble_experimentations/wiki/How-to-create-an-overlay%3F

**Comment by skittels15** [comment]
Examples in **vendor_hardware_overlay** repo

**Comment by krynyx** [comment]
I had the same problem when I was testing the treble ROM in Redmi 9A. To use earphone/headphone with jack connection, I had installed an app to modify the sound policy. It's worked fine to me.

**Comment by SebastienThibaut** [comment]
@krynyx 
Could you give me the name of the app you used to solve the problem ?
I tried some apps but none of them allowed me to use my headphones.
Thanks in advance.

@skittels15 
I will read your link and try to apply this later.
Thank you for your help.

**Comment by krynyx** [comment]
> @krynyx
> Could you give me the name of the app you used to solve the problem ?
> I tried some apps but none of them allowed me to use my headphones.
> Thanks in advance.
> 
> @skittels15
> I will read your link and try to apply this later.
> Thank you for your help.

Audio Router: https://m.apkpure.com/audio-router/audiomix.audiooutputsource
Enable Audio Policy option to Always on and it will work.

**Comment by krynyx** [comment]
> @krynyx
> Could you give me the name of the app you used to solve the problem ?
> I tried some apps but none of them allowed me to use my headphones.
> Thanks in advance.
> 
> @skittels15
> I will read your link and try to apply this later.
> Thank you for your help.

Sorry! I have tested now, and I have solved this problem checking these options on "Misc Features" (Settings > Phh Treble Settings > Misc Features) and rebooting the device:

Force headset switch (Huawei...)
Use alternate way to detect headphone...
Force-disable A@DP offload

**Comment by eric-pierce** [comment]
I'm running into this same issue on an unrelated tablet (Lenovo Tab m8) running lineage-18.1-20220616-UNOFFICIAL-arm64_bvS.img.xz from https://sourceforge.net/projects/andyyan-gsi/files/lineage-18.x/.  

Enabling the three settings mentioned in https://github.com/phhusson/treble_experimentations/issues/1774#issuecomment-849040229 and rebooting isn't changing the behavior, is there another setting or combination I should be tweaking? If not, is there another way to resolve this?

**Comment by thomas-catt** [comment]
I have a Nokia 3.2, and initially also faced this same problem like many others. But I don't know how exactly, it doesn't happen anymore for me, regardless of installing any ROM even after wiping. I think what fixed it for me was a simple factory reset from settings. It may not be it, but I do seem to remember that it fixed my issue.

For the headphone jack to work, I sometimes need to enable 'Headset' icon from status bar icons (the SysUI Tuner menu).

**Comment by SebastienThibaut** [comment]
Hello,

I don't use this phone anymore.
This problem is solved for me.

Thanks a lot and sorry for the lately answer.
