### ISSUE TITLE
Lenovo K5 Play bootloop

### ISSUE THREAD

**Issue by gombalr99** [phhusson/treble_experimentations#1781]
This ROM bootloop in my device, Lenovo K5 Play

**Comment by banx** [comment]
I confirm I have the same problem on a Lenovo E10. Flashing the `system-roar-arm-aonly-vanilla.img` image file from `AOSP 11.0 v303` release, displays the message `Invalid sparse file format at header magic`. After rebooting, the device is stuck in an endless boot-loop.
Note: the original boot partition is used (No Magisk).

I got the [same issue](https://github.com/eremitein/treble-patches/issues/32) with LOS 18.1, but they suggested to try the AOSP first.

**Comment by gombalr99** [comment]
> I confirm I have the same problem on a Lenovo E10. Flashing the `system-roar-arm-aonly-vanilla.img` image file from `AOSP 11.0 v303` release, displays the message `Invalid sparse file format at header magic`. After rebooting, the device is stuck in an endless boot-loop.
> Note: the original boot partition is used (No Magisk).
> 
> I got the [same issue](https://github.com/eremitein/treble-patches/issues/32) with LOS 18.1, but they suggested to try the AOSP first.

did it work? and can enter the homescreen?

**Comment by banx** [comment]
> did it work? and can enter the homescreen?

No it didn't work. 
I suspect that the problem has originated when they started using [sas-creator](https://github.com/phhusson/sas-creator) to generate the A-only images here. I am basing my doubt on the fact that flashing android 10 images didn't cause such problem before. But this is yet to be confirmed.
