### ISSUE TITLE
[Huawei P8 Lite] AOSP 8.1v25-26 Bootloop

### ISSUE THREAD

**Issue by rgcv** [phhusson/treble_experimentations#179]
The issue is with /system/overlay/treble-overlay-huawei-PRA.apk
For some reason, it crashes zygote

Original post:
Tested flashing AOSP 8.1v25 on top of v23, made P8 Lite 2017 go into bootloop. Flashing back to v23 fixed the problem.

**Comment by phhusson** [comment]
Got any logs?

**Comment by rgcv** [comment]
Sorry, no, I'll try and get some later on, if possible. Hum.. guessing I can just fetch 'em raw from the device? Sorry again, bit of a noob 😞

**Comment by phhusson** [comment]
Can you check the content of /data/resource-cache/overlays.list when you're in this state?
with adb shell su 0 cat /data/resource-cache/overlays.list

**Comment by phhusson** [comment]
Ok.
Please do adb shell su 0 rm -f /system/overlay/treble-overlay-huawei-PRA.apk

**Comment by rgcv** [comment]
Had to remount `/system` as read-write first (it's ro by default) using
`adb shell su 0 mount -o remount,rw /system`
It successfully deleted the apk. Here's an updated list of the available overlays:
```sh
total 284
-rw-r--r-- 1 root root  5300 2018-09-05 20:06 treble-overlay-NightMode.apk
-rw-r--r-- 1 root root  5746 2018-09-05 20:06 treble-overlay-asus-zenfone5.apk
-rw-r--r-- 1 root root  5744 2018-09-05 20:06 treble-overlay-asus-zenfone5z.apk
-rw-r--r-- 1 root root  5760 2018-09-05 20:06 treble-overlay-caf-ims.apk
-rw-r--r-- 1 root root  5305 2018-09-05 20:06 treble-overlay-devinputjack.apk
-rw-r--r-- 1 root root 10183 2018-09-05 20:06 treble-overlay-huawei-ANE.apk
-rw-r--r-- 1 root root  9694 2018-09-05 20:06 treble-overlay-huawei-BND.apk
-rw-r--r-- 1 root root  9675 2018-09-05 20:06 treble-overlay-huawei-DUK.apk
-rw-r--r-- 1 root root  9710 2018-09-05 20:06 treble-overlay-huawei-LLD.apk
-rw-r--r-- 1 root root  9666 2018-09-05 20:06 treble-overlay-huawei-RNE.apk
-rw-r--r-- 1 root root  9673 2018-09-05 20:06 treble-overlay-huawei-STF.apk
-rw-r--r-- 1 root root  9666 2018-09-05 20:06 treble-overlay-huawei-VTR.apk
-rw-r--r-- 1 root root  9700 2018-09-05 20:06 treble-overlay-huawei-WAS.apk
-rw-r--r-- 1 root root  6468 2018-09-05 20:06 treble-overlay-huawei.apk
-rw-r--r-- 1 root root  5734 2018-09-05 20:06 treble-overlay-lg-g7.apk
-rw-r--r-- 1 root root 12604 2018-09-05 20:06 treble-overlay-moto-g6plus.apk
-rw-r--r-- 1 root root  8650 2018-09-05 20:06 treble-overlay-oneplus-op6.apk
-rw-r--r-- 1 root root  9266 2018-09-05 20:06 treble-overlay-sharp-s2.apk
-rw-r--r-- 1 root root  9857 2018-09-05 20:06 treble-overlay-webview.apk
-rw-r--r-- 1 root root  5289 2018-09-05 20:06 treble-overlay-wifi5g.apk
-rw-r--r-- 1 root root  5728 2018-09-05 20:06 treble-overlay-xiaomi-mi8.apk
-rw-r--r-- 1 root root  5728 2018-09-05 20:06 treble-overlay-xiaomi-mi8ee.apk
-rw-r--r-- 1 root root  5731 2018-09-05 20:06 treble-overlay-xiaomi-mi8se.apk
-rw-r--r-- 1 root root  5734 2018-09-05 20:06 treble-overlay-xiaomi-mia2lite.apk
-rw-r--r-- 1 root root 11589 2018-09-05 20:06 treble-overlay-xiaomi-mimix2s.apk
-rw-r--r-- 1 root root  9274 2018-09-05 20:06 treble-overlay-xiaomi-mipad4.apk
-rw-r--r-- 1 root root  5741 2018-09-05 20:06 treble-overlay-xiaomi-pocof1.apk
-rw-r--r-- 1 root root  5734 2018-09-05 20:06 treble-overlay-xiaomi-redmi6pro.apk
```
No PRA overlay in sight. A reboot sufficed, bootloop is gone, and the update has been applied. Here's a screenshot of the September security patch in System info:

<img src="https://user-images.githubusercontent.com/4052080/45917802-e0b14d80-be74-11e8-8fdd-1a5f9e1a52b4.png" alt="screenshot_20180922-143404" height="800"></img>

So.. Does the PRA overlay apk come bundled with the 8.1 system image? Or would an erasure of the system partition remove that APK, therefore not incurring a bootloop? I can't quite recall, but I think I tried a clean system flash of v25 and it still put the device in a loop.

I'm guessing the PRA apk is in the system image.. which should probably be removed then? Not sure.

Anyways, that fixed it for me, thank you so very much for the help! :+1:

**Comment by rgcv** [comment]
Just updated from v25 to v26, the issue is exactly the same. Deleting the `PRA` apk solves the loop once again :+1:

**Comment by rgcv** [comment]
@Dil3mm4 I did not wipe /data, no.. Don't really wanna lose any, just flashed on top of the existing system partition, barebones.
Rebranded? How so?
Don't recall getting any failures per se.. What does HuRU mean/spell? 😕
