### ISSUE TITLE
Redmi Note 9t 5G (Cannong)  cannot enable radio power

### ISSUE THREAD

**Issue by gsuzeda** [phhusson/treble_experimentations#1793]
Device: Cannong
Model: Redmi Note 9t (global)
Manufacturer: Xiaomi
SoC: MTK Dimensity 800u
Vendor tree: https://github.com/AndroidBlobs/vendor_xiaomi_cannong
Firmware used: https://xiaomifirmwareupdater.com/miui/cannong/ - Global lastest 
image used: AOSP 11 v303 and v304
Issue: Device turns on normally and detects the SIM card, however it is not possible to enable radio power.

was tried: 
activate manually through * # * # 4636 # * # *
switch preferred network
flash vbmeta and boot after the system image
flash custom kernel

notes:
AOSP10 works perfectly
The device supports the 5g network

logcat:
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/6280963/logcat.txt)

**Comment by dsclee1** [comment]
Experiencing the same issue. In practice this means no telephony, no phone signal, no 3g/4g/5g data.

**Comment by gsuzeda** [comment]
updating the situation:
both in google stock gsi and in @Eternityson GSIs the signal works perfectly

**Comment by phhusson** [comment]
Ok, please try with my GSI and remove /system/bin/rw-system.sh

**Comment by gsuzeda** [comment]
<img width="537" alt="image" src="https://user-images.githubusercontent.com/40251034/119271442-eb00e800-bbd7-11eb-886a-e488dfb4593b.png">

I can not

**Comment by gsuzeda** [comment]
<img width="547" alt="image" src="https:mtp:/cannon/Internal Storage/Pictures/Screenshots/Screenshot_2021-05-24-02-01-49.png
mtp:/cannon/Internal Storage/Pictures/Screenshots/Screenshot_2021-05-24-02-07-12.png
mtp:/cannon/Internal Storage/Pictures/Screenshots/Screenshot_20210523-180427.png
mtp:/cannon/Internal Storage/Pictures/Screenshots/Screenshot_2021-05-24-02-01-49.png
mtp:/cannon/Internal Storage/Pictures/Screenshots/Screenshot_2021-05-24-02-07-12.png
mtp:/cannon/Internal Storage/Pictures/Screenshots/Screenshot_20210523-180427.png
mtp:/cannon/Internal Storage/Pictures/Screenshots/Screenshot_2021-05-24-02-01-49.png
mtp:/cannon/Internal Storage/Pictures/Screenshots/Screenshot_2021-05-24-02-07-12.png
mtp:/cannon/Internal Storage/Pictures/Screenshots/Screenshot_20210523-180427.png
//user-images.githubusercontent.com/40251034/119271613-a9247180-bbd8-11eb-9863-db9cbf7ec8f0.png">

i can not

**Comment by gsuzeda** [comment]
![Screenshot_2021-05-24-02-01-49](https://user-images.githubusercontent.com/40251034/119271674-ea1c8600-bbd8-11eb-978d-61aab8410de9.png)
![Screenshot_2021-05-24-02-07-12](https://user-images.githubusercontent.com/40251034/119271676-eab51c80-bbd8-11eb-8dbd-9be4a9dcbd9b.png)
![Screenshot_20210523-180427](https://user-images.githubusercontent.com/40251034/119271677-eb4db300-bbd8-11eb-8170-679083d7282a.png)
<img width="550" alt="image" src="https://user-images.githubusercontent.com/40251034/119271699-faccfc00-bbd8-11eb-8aea-e728d9144b98.png">

i can not 
I tried in recovery and adb with the device on and with recovery

**Comment by dsclee1** [comment]
I think that issue is due to the super partition. You'll need to install superrepack to allow the system partition to be writable.

https://forum.xda-developers.com/t/tool-win-lin-and-darw-super-image-tools-extract-or-make-partitions-rw-in-super-partition.4120963/

**Comment by phhusson** [comment]
Nope, that's a "feature" of some devices, super partition (or system in pie) can only be modified from bootloader or recovery, not running system, that's a hardware feature

24 mai 2021 14:10:08 David ***@***.***>:

**Comment by dsclee1** [comment]
I had a situation where I couldn't write anything to the system partition even in recovery due to the system partition being marked read-only within the super partition. It was only after I ran the superrepack tool on the rooted normal side that I could go back into recovery to edit files in the system partition.

I'd provide evidence to confirm this, but unfortunately my phone is now bricked after trying to install Xiaomis MIUI 12.5 beta images! And Xiaomi have _helpfully_ decided that we shouldn't be allowed to use the SP Flash Tool without authorisation.

**Comment by phhusson** [comment]
You can trivially bypass super's readonly flag with `blockdev --setrw /dev/block/dm-X`. No need to flash anything

24 mai 2021 15:33:50 David ***@***.***>:

**Comment by dsclee1** [comment]
Thanks, that's good to know. @gsuzeda that would be 'blockdev --setrw /dev/block/dm-2' for our CANNONG devices.

**Comment by phuallday** [comment]
can i use this way for Redmi9a(dandelion)?

**Comment by gsuzeda** [comment]
I couldn't remove the file

On adb shell:
1|:/system/bin # rm -f rw-system.sh                                            
rm: rw-system.sh: Device or resource busy

On terminal and on recovery:
![photo_2021-06-03_14-55-11](https://user-images.githubusercontent.com/40251034/120690608-d47e4a80-c47b-11eb-9200-bc85d63a5d78.jpg)
![photo_2021-06-03_14-55-07](https://user-images.githubusercontent.com/40251034/120690632-d942fe80-c47b-11eb-919f-5cff61ac781d.jpg)

**Comment by phuallday** [comment]
try command with adb
adb root
adb shell

**Comment by phuallday** [comment]
I deleted the file rw-system.sh but signal not turn on.pls help me phhusson

**Comment by gsuzeda** [comment]
fixed with the new a11 vendor
