### ISSUE TITLE
Poco M3 Audio for Speaker: Earpiece plays together with Speaker

### ISSUE THREAD

**Issue by edwining01** [phhusson/treble_experimentations#1799]
While played with `earpiece`, only `earpiece` had sound.
But when played with `speaker`, **both** `earpiece` and `speaker` had sound.

In logcat, it could not find the process id.

```
adb shell logcat
```

Result: [logcat.txt](https://gist.github.com/edwining01/8d8217159dc8f27f98505f07befcd207/raw/e159120eda6e0787a962319fb6951078d5625760/logcat.txt) ([gist](https://gist.github.com/edwining01/8d8217159dc8f27f98505f07befcd207))

On line 868-869:
```
04-12 13:44:04.235  2028  6464 D android.hardware.audio@2.0-service: ACDBFILE_MGR: Property for the pid 000133B7 not found
04-12 13:44:04.235  2028  6464 D android.hardware.audio@2.0-service: [Data Manager] -> Failed to fetch the property info for pid 000133B7 
```

```
adb shell ps -A | grep [aA]udio
```

Result:

```
USER            PID   PPID     VSZ    RSS WCHAN            ADDR S NAME
  222 ??         0:00.07 root            325      2       0      0 rescuer_thread      0 I [uaudio_svc]
audioserver    2021      1   61072   1796 binder_ioctl_write_read 0 S android.hardware.audio@2.0-service
audioserver    2132      1 11256376  2424 binder_ioctl_write_read 0 S audioserver
```

Seems there was a miss match here, although I could still hear sound. Is it the reason behind?

**Comment by KaMyKaSii** [comment]
But the standard of the Poco M3 is to play the sound by the three speakers at the same time, no?

**Comment by edwining01** [comment]
Thanks. I found it supports `Stereo Speakers` from [here](https://gadgetrange.com/xiaomi/2020/12/20/poco-m3-poco-made-the-same-mistake-again) and tested with some audio and thats it. Although there was an error message, it does not affect daily use. **Its a feature not a bug.** Issue can close.
