### ISSUE TITLE
v305 on Jasmine_sprout (Xiaomi Mi A2) Play Store certification gone

### ISSUE THREAD

**Issue by xatornet** [phhusson/treble_experimentations#1807]
Using a clean install of the latest official FW, jasmine_global_images_V11.0.22.0.QDIMIXM_10.0, then erasing system_a, system_b, flashing v305 for A/B with GAPPS on both system partitions, then fastboot -w. It boots and works great, but I cannot use Google Services as I get that Google Certification is not working on this device.

**Comment by phhusson** [comment]
Register your device on https://www.google.com/android/uncertified/

To get the ID, you can either:
- adb root, then adb shell, press enter, and at the new prompt, inside adb
shell, do sqlite3 /data/data/com.google.android.gsf/databases/gservices.db
   'select * from main where name = "android_id";'
- https://play.google.com/store/apps/details?id=com.evozi.deviceid =>
Google Service Framework (GSF) ID
- for multiuser see
https://github.com/phhusson/treble_experimentations/issues/1794#issuecomment-816632811

**Comment by xatornet** [comment]
Yeah, already did this and it'w working. But now I have some doubts... is this going to work for a limited time? or is it a "one time thing" to do?
Also, thanks for the quick response

**Comment by phhusson** [comment]
It's one time thing until you factory reset

**Comment by xatornet** [comment]
Ok, good to know. Thanks for your amazing work, rom works like a charm on Xiaomi Mi A2!! I'll close the issue.
