### ISSUE TITLE
cubot X19: AOSP 11.0 v306: phone gets stuck on "android" flashing on the screen after a restart of the phone.

### ISSUE THREAD

**Issue by babaghanush** [phhusson/treble_experimentations#1814]
hello,  

cubot X19: AOSP 11.0 v306: phone gets stuck on "android" flashing on the screen after a restart of the phone.  The initial installation works fine, and the phone powers on all the way to the main OS.  But after navigating in the OS, installing various programs, and making setting changes, if you happen to restart the phone, the phone will not boot up again.  After the initial boot the phone will not go past the written flashing "android" screen.  I have tried wiping cache from recovery menu, and it doesn't help.

You can do a wipe cache and also a factory wipe/reset from the recovery menu, and the phone will then bootup again for the first time, but again when you install programs and done customizing the OS to your liking, and then rebooting it will again put the phone in the same above condition.

**Comment by phhusson** [comment]
Set a lockscreen and when prompted for secure boot say yes

27 avr. 2021 14:51:56 babaghanush ***@***.***>:

**Comment by babaghanush** [comment]
That did it.  Thanks for the prompt answer.  I appreciate it.
