### ISSUE TITLE
[Galaxy A51 4G versión] Backlight issues by TrebleApp

### ISSUE THREAD

**Issue by KatoTempest** [phhusson/treble_experimentations#1816]
After installing this gsi with the overlay, notice that an "automatic" configuration of TrebleApp disables the overlay settings, what I mean is that the brightness works randomly, although when I disable that option it seems to work fine, I would like to know if it could be disabled or something that option some new Users have brightness problems for that option, which is in "Treble App"> Samsung setting> max backlight scale.
P.S. If this issue should not be here you can close it or something if necessary, I just wanted to report this error on this device

**Comment by phhusson** [comment]
Remove it from
https://github.com/phhusson/treble_presets/blob/master/infos.json and make
a PR

Le mer. 28 avr. 2021 à 18:24, KatoTempest ***@***.***> a
écrit :

**Comment by KatoTempest** [comment]
I also just noticed that the overlay is not present in the gsi, a bit strange since it was accepted in the PR of a month ago, I guess something is wrong with the overlay
