### ISSUE TITLE
Need to ignore Oreo ims.apk on Pie

### ISSUE THREAD

**Issue by PlayFriik** [phhusson/treble_experimentations#183]
Title pretty much sums up my issue. I have an Estonian carrier called "Telia".
I didn't have any issues with cellular data on the v103.

Edit: I forgot to mention that I use OnePlus 3T.
Edit 2: Reflashing Vendor seems to have fixed this issue.
Edit 3: Never mind, it randomly started happening again.

**Comment by phhusson** [comment]
https://forum.xda-developers.com/showpost.php?p=77602599&postcount=587

**Comment by phhusson** [comment]
If you run your ims.apk through this script:
https://github.com/phhusson/apps_repacker_aosp/blob/master/VoLTE-CAF/build.sh
And you simply install the apk (no need to put it in system or vendor since
v104) it should work

Le dim. 16 sept. 2018 à 04:26, Simon Shi <notifications@github.com> a
écrit :

**Comment by phhusson** [comment]
Should be fixed with https://github.com/phhusson/device_phh_treble/commit/23fcb001119b2ca0d03e4169c3570bbfee050ad2

**Comment by codejoe87** [comment]
> 
> 
> Should be fixed with [phhusson/device_phh_treble@23fcb00](https://github.com/phhusson/device_phh_treble/commit/23fcb001119b2ca0d03e4169c3570bbfee050ad2)

Same problems on Moto G6 Plus. Sim is not getting recognized. I don't have /vendor/app/ims/ folder and I'm using latest version v105. Here is logcat https://ghostbin.com/paste/jzfxc

**Comment by ThEMarD** [comment]
> > Should be fixed with [phhusson/device_phh_treble@23fcb00](https://github.com/phhusson/device_phh_treble/commit/23fcb001119b2ca0d03e4169c3570bbfee050ad2)
> 
> Same problems on Moto G6 Plus. Sim is not getting recognized. I don't have /vendor/app/ims/ folder and I'm using latest version v105. Here is logcat https://ghostbin.com/paste/jzfxc

Selinux denial. Yours is apparently in system/app/ims.apk so something in your selinux sepolicies would need to be fixed (might be solved by also moving that ims.apk to the proper location).

If Moto G6 Plus isn't a treble enabed device? Vendor folder would be in /system/vendor.

09-19 13:03:54.536  1803  1803 W package-parsing: type=1400 audit(0.0:108): avc: denied { open } for uid=1000 path="/system/app/ims.apk" dev="mmcblk0p67" ino=4308 scontext=u:r:system_server:s0 tcontext=u:object_r:media_rw_data_file:s0:c512,c768 tclass=file permissive=0
09-19 13:03:54.540  1803  1865 W ziparchive: Unable to open '/system/app/ims.apk': Permission denied
09-19 13:03:54.540  1803  1865 E system_server: Failed to open APK '/system/app/ims.apk' I/O error
09-19 13:03:54.557  1803  1803 W PackageManager: Failed to parse /system/app/ims.apk: Failed to parse /system/app/ims.apk

**Comment by phhusson** [comment]
@ThEMarD well, if they have ims in */system/* in my gsi, it means they installed it themselves.

**Comment by ThEMarD** [comment]
Oh, now that you mentioned it? That makes more sense heh since usually apps within the apps folder is usually also within a folder with the same name as the app, so yeah, definitely device-side bug and not GSI.

**Comment by codejoe87** [comment]
@phhusson and @ThEMarD

Moto G6 Plus stock rom have ims.apk in /system/app/ims.

Also I don't have installed manually any system app so ims.apk isn't presented.
