### ISSUE TITLE
[Realme 7 Pro] Touchscreen never works

### ISSUE THREAD

**Issue by egayghost** [phhusson/treble_experimentations#1831]
![IMG_20210510_161016_386](https://user-images.githubusercontent.com/59923073/117627002-4da2be80-b1aa-11eb-9e0d-77da1f68199e.jpg)

[logcat.txt](https://github.com/phhusson/treble_experimentations/files/6450540/logcat.txt)

Dump rom link: 
A10: https://download.c.realme.com/osupdate/RMX2170PU_11_OTA_0330_all_gtjL6QJe25sL.ozip

A11: https://github.com/Mediatek-leaks/qti_atoll_dump/tree/qssi-user-11-RKQ1.200903.002-eng.root.20210203.003534-release-keys/

Kernel source: https://github.com/realme-kernel-opensource/realme7pro_AndroidQ-kernel-source

Touchscreen issue

**Comment by phhusson** [comment]
Fixed with https://github.com/phhusson/device_phh_treble/commit/07e17110caaf4aad911a1c4abc468a12f4f06947
