### ISSUE TITLE
[Realme C12 RMX2189] Fingerprint enrolls but cant unlock phone

### ISSUE THREAD

**Issue by noname-rrr** [phhusson/treble_experimentations#1834]
Sir, 
Fingerprint can be enrolled in settings but unable to unlock device with fingerprint.
logs attached  are from stock rom after,
-reboot
- enter  pin code
- lock again your screen
- unlock screen with fingerprint
[logs.txt](https://github.com/phhusson/treble_experimentations/files/6458464/logs.txt)

**Comment by phhusson** [comment]
you found a fix?
