### ISSUE TITLE
[Teclast M30] M5P4 variant does not exist in Wiki

### ISSUE THREAD

**Issue by lululock71** [phhusson/treble_experimentations#1846]
Hi,

Just got a M30, variant M5P4 and I noticed there's no mention of it in the [Wiki](https://github.com/phhusson/treble_experimentations/wiki/Teclast-M30) and no link to its stock ROM too.

This model has been bought in late 2020 and may be the latest variant it has before the M30 Pro has been released.

Here's the link for the V1.02 ROM from Teclast Website : [OneDrive](https://onedrive.live.com/?authkey=%21ANwP6Y1f2XiBe6c&cid=A120532B51026BDA&id=A120532B51026BDA%212790&parId=A120532B51026BDA%212077&action=locate)

**Comment by ShahrukhAbrar** [comment]
You can just create one yourself

**Comment by phhusson** [comment]
This is a wiki. You can add it yourself.

17 mai 2021 10:56:14 lululock71 ***@***.***>:

**Comment by lululock71** [comment]
How ?
