### ISSUE TITLE
[grus aka Mi9SE] [AOSP 11 v307] Changing Lower brightness or aux camera setting breaks brightness

### ISSUE THREAD

**Issue by snzk0** [phhusson/treble_experimentations#1848]
Hi,

I flashed your GSI build of AOSP 11 and everything seems to work pretty well except when I mess with the settings under "Phh Treble Settings -> Misc Features", the brightness gets stuck at 100% and cannot be changed (both the slider and the brightness setting do not have effect anymore).

The brightness works normally if the settings are untouched, but breaks (after reboot) if the setting are turned on (and does not revert to working if the settings are turned back off).

I only tried "Allow setting brightness to the lowest possible" and "Expose Aux cameras", and the behaviour is the same for the two. Factory reset fixes the issue (at the cost of all apps/settings). Any idea what causes this and how I can fix the issue without factory reset?

Thx for the GSI btw :)

**Comment by phhusson** [comment]
Try toggling use alternate backlight scale?

18 mai 2021 12:25:24 snzk0 ***@***.***>:

**Comment by snzk0** [comment]
It works! I'd be interested in what the options do (setprop? change xml?). Do you have any pointers on where in the code I can look?
