### ISSUE TITLE
BQ Twin Pro/ Leagoo T8S - Crash of telephony service in all bilds 11.

### ISSUE THREAD

**Issue by evgendobro** [phhusson/treble_experimentations#1859]
Hi! I tried all bilds 11 whith your patches, and telephony service crashes at all. But in bilds 10 all works fine.
MT6750 
arm64
aonly
vndk27
Vendor rom - Freeme 4 Android 8.1
Russia
I hope for your help!!! Snx!!!

**Comment by evgendobro** [comment]
The problem has been resolved. In the APN settings of my operator (Tele2), I needed to disable authentication.

**Comment by phhusson** [comment]
That's interesting, thanks for the feedback

22 mai 2021 16:11:58 evgendobro ***@***.***>:
