### ISSUE TITLE
[Nokia 1 DS] Serious problem with radio

### ISSUE THREAD

**Issue by kutiz21** [phhusson/treble_experimentations#186]
Supports some of Network bands.

You can't change networking band.

Force the 1st SIM working in 2G first (and reboot) in Mobile network to make the modem software doesn't crashed. Then you will allowed to change any network mode without SIM unrecognizable bug.

You need to reboot the phone every single time you change network band or network mode.

For 2nd SIM/non-mobile data SIM. Choose 2G network.

Precise model number is TA-1047

As described in the page

https://github.com/phhusson/treble_experimentations/wiki/Nokia-1

But this one is the most important thing.

**Comment by phhusson** [comment]
logs?

**Comment by kutiz21** [comment]
I reinstalled and locked the bootloader so. No. And google play services is broken on this ROM. Basically crashed a lot with updated Google Play services.

**Comment by kutiz21** [comment]
Nokia fixed this with a new vendor build from 00WW_1_*, so no more radio panic and crashes. And the only thing that buggy was the choosing what sim to have data connection (If choosing SIM2 as data SIM, both SIM will have no coverage, but no radio panic and crashing) and the USSD message bug.
