### ISSUE TITLE
[Xiaomi Mi Mix 2s] No in-call audio in both directions with AOSP 9

### ISSUE THREAD

**Issue by rbuehlma** [phhusson/treble_experimentations#188]
If I do a phone call (in or out does not matter), there is no audio in both directions. Same with headphones or speaker.

I have built the rom on my own using build.sh.

Prior flashing this system image, I flashed this beta build (for Android 9 kernel and vendor partition):
http://bigota.d.miui.com/8.9.13/miui_MIMIX2SGlobal_8.9.13_4590eb1e00_9.0.zip

Can I provide any debug info which would help to analyse this?

**Comment by phhusson** [comment]
please provide logcat at start, when doing a call.
Please also provide result of lshal

**Comment by rbuehlma** [comment]
[logcat](https://files.buehlmann.net/xiaomi/188_logcat.txt)
[lshal](https://files.buehlmann.net/xiaomi/188_lshal.txt)

Now that I see the fingerprint in the logcat: I changed the fingerprint to pass safetynet. Could this be the cause?

**Comment by rbuehlma** [comment]
Reverting the fingerprint made no change.

But this one looks suspect:
imsrcsd.cpp:144] Loading RCS lib fails[dlopen failed: library "com.qualcomm.qti.imscmservice@2.0.so" not found]

**Comment by phhusson** [comment]
It is missing logcat at boot

**Comment by rbuehlma** [comment]
My fault. I have read it as "logcat during start of call". Here is one right after booting:
[logcat_boot](https://files.buehlmann.net/xiaomi/188_logcat_boot.txt)

**Comment by phhusson** [comment]
grmbl it doesn't give proper logs.
Can you run logcat -s PHH and keep it open from boot until you make a call,
then copy paste what it said?

Also after the call please dump result logcat -b events -s auditd -d

**Comment by rbuehlma** [comment]
Here you are:
[logcat_phh](https://files.buehlmann.net/xiaomi/188_logcat_phh.txt)
[events](https://files.buehlmann.net/xiaomi/188_events.txt)

logcat -s PHH did not provide a lot output.

**Comment by phhusson** [comment]
does logcat -s PHH give something when you select options in the PHH treble
settings ? Like the signal meter method

**Comment by rbuehlma** [comment]
Something like this:
`- waiting for device -
--------- beginning of system
--------- beginning of crash
--------- beginning of main

09-15 13:03:18.103  5000  5000 D PHH     : Setting signal level method to openkirin
09-15 13:03:23.122  5000  5000 D PHH     : Setting signal level method to default
`

**Comment by ShotSkydiver** [comment]
I'm experiencing the exact same issue, same device (MiX 2S), same original system image flashed. I'm currently running PixelExperience P - UNOFFICIAL. I noticed issues originally when I discovered Apple Music constantly crashes upon opening, with this showing up as the crashlog:
```
09-15 05:18:03.120 10194 10194 E libOpenSLES: unable to find an implementation for the requested effect.
09-15 05:18:03.120 10194 10194 E libOpenSLES: Equalizer initialization failed
09-15 05:18:03.120 10194 10194 E libOpenSLES: unable to find an implementation for the requested effect.
09-15 05:18:03.120 10194 10194 E libOpenSLES: BassBoost initialization failed.
09-15 05:18:03.120 10194 10194 D SVAudioRendererNative: SVOpenSLESOutputMix::SVOpenSLESOutputMix() CreateOutputMix SL_RESULT_SUCCESS
09-15 05:18:03.120 10194 10194 D SVAudioRendererNative: SVOpenSLESOutputMix::SVOpenSLESOutputMix() Realize SL_RESULT_SUCCESS
09-15 05:18:03.120 10194 10194 W libOpenSLES: Leaving Object::GetInterface (SL_RESULT_FEATURE_UNSUPPORTED)
09-15 05:18:03.120 10194 10194 E SVAudioRendererNative: SVOpenSLESOutputMix::SVOpenSLESOutputMix() ERROR SL_IID_EQUALIZER error: 12
09-15 05:18:03.121 10194 10194 D AndroidRuntime: Shutting down VM
09-15 05:18:03.121 10194 10194 E AndroidRuntime: FATAL EXCEPTION: main
09-15 05:18:03.121 10194 10194 E AndroidRuntime: Process: com.apple.android.music, PID: 10194
09-15 05:18:03.121 10194 10194 E AndroidRuntime: java.lang.RuntimeException: Unknown error. ERROR GetInterface SL_IID_EQUALIZER
09-15 05:18:03.121 10194 10194 E AndroidRuntime:        at com.apple.android.music.renderer.javanative.SVOpenSLESEngine$SVOpenSLESEngineNative.create(Native Method)
```

**Comment by rbuehlma** [comment]
I tried to install an earlier beta as base:
http://bigota.d.miui.com/8.9.7/miui_MIMIX2SGlobal_8.9.7_3f1fdd8006_9.0.zip
Same issue there.

Could there be something wrong with my own build?

**Comment by rbuehlma** [comment]
Its somewhat weird:
- Restarted the phone
- Tried about 5 calls, all without audio
- Applied the setenforce 0 from your link
- Did another 2 calls without audio
- After that, every call seems to be fine (with audio).

**Comment by ShotSkydiver** [comment]
WHOA really??? In that exact order of steps?? I'll have to try that again then! The in-call audio bug was the only thing holding me back from making these treble roms a daily driver so that's great news

**Comment by phhusson** [comment]
please give me logcat -b events -s auditd -d after succesful calls.
Having a minute after boot without calls is quite expected

**Comment by rbuehlma** [comment]
You are right. These are the new steps:
- Reboot
- setenforce 0
- wait a few minutes
- Call is with audio

Here the requested logcat:
[188_logcat_successfull_call.txt](https://files.buehlmann.net/xiaomi/188_logcat_successfull_call.txt)

**Comment by rbuehlma** [comment]
I think both are not true ;)

I did my own build to include some more fixes (for bluetooth audio and distorted sound). This build also includes that commit :(
I just checked the build folder and the file
./device/phh/treble/sepolicy/qualcomm.te
does indeed already contain that fix.

**Comment by phhusson** [comment]
Ok, rild moved from "system" to "vendor" SELinux policy, so it no longer gets compatibility attributes.
Defining "rild" type in qualcomm.te fails because it is LATER defined by system/sepolicy/vendor/rild.te.
I guess the fix is to create our own vendor selinux policy, I need to check.

For reference, the vendor selinux is available at:
https://raw.githubusercontent.com/TadiT7/xiaomi_polaris_dump/polaris-user-9-PKQ1.180729.001-8.8.28-release-keys/vendor/etc/selinux/vendor_sepolicy.cil

**Comment by rbuehlma** [comment]
In case it matters, here is the file from the current beta build (8.9.13 global):
https://files.buehlmann.net/xiaomi/vendor_sepolicy.cil
There is quite some diff

**Comment by phhusson** [comment]
Can you try with this?
https://github.com/phhusson/platform_system_sepolicy/commit/b2f375b008283eecff89be1c2d9fdf06c2464622

It's not the nicest patch, but well...

**Comment by rbuehlma** [comment]
Is there a file on the system I can edit or do I need to rebuild the rom? There is no rild.te in my /vendor/ or /system/

**Comment by rbuehlma** [comment]
No, this quick fix does not work. But there is no need for a quick fix. The rom runs very solid such that I can use the setenforce 0 workaround after startup :)

**Comment by phhusson** [comment]
https://github.com/phhusson/device_phh_treble/commit/b544b15e6864b2f310b7cea507e67d46991bd543
I hope this will do

**Comment by rbuehlma** [comment]
Thanks, I'll try it. Will take some time to build the rom :)

**Comment by rbuehlma** [comment]
Yap. this fix works :) Thank you very much.

**Comment by rbuehlma** [comment]
This is fixed in v105
