### ISSUE TITLE
Mediatek RIL stop works after some times. No data until reboot [CUBOT QUEST]

### ISSUE THREAD

**Issue by bahamut657** [phhusson/treble_experimentations#1880]
Finally I got logs about the No Mobile Internet problem until reboot.
Hoping this could help resolving the issue.
Thank you so much for the work done.

[nodata_logcat.log](https://github.com/phhusson/treble_experimentations/files/6593985/nodata_logcat.log)
Best Regards

**Comment by MMan1982** [comment]
> Finally I got logs about the No Mobile Internet problem until reboot.
> Hoping this could help resolving the issue.
> Thank you so much for the work done.
> 
> [nodata_logcat.log](https://github.com/phhusson/treble_experimentations/files/6593985/nodata_logcat.log)
> Best Regards

Good news!I hope it will solved;)
Can you post a log from fingerprint?

https://github.com/phhusson/treble_experimentations/issues/1273

**Comment by bahamut657** [comment]
Resolved installing all packages under IMS Features (Under phh treble settings)
