### ISSUE TITLE
[Huawei Mediapad M5] [AOSP 11 v308] cell signal strength indicator not working

### ISSUE THREAD

**Issue by presslab-us** [phhusson/treble_experimentations#1884]
The indicator always shows an empty triangle.

About phone->SIM status shows: "Signal strength 2147483647 dBm 99 asu" and "Mobile data network type LTE"

Results of `adb shell dumpsys telephony.registry | grep -i signalstrength`
```
mSignalStrength=SignalStrength:{mCdma=CellSignalStrengthCdma: cdmaDbm=2147483647 cdmaEcio=2147483647 evdoDbm=2147483647 evdoEcio=2147483647 evdoSnr=2147483647 level=0,mGsm=CellSignalStrengthGsm: rssi=-113 ber=2147483647 mTa=0 mLevel=0,mWcdma=CellSignalStrengthWcdma: ss=2147483647 ber=2147483647 rscp=2147483647 ecno=2147483647 level=0,mTdscdma=CellSignalStrengthTdscdma: rssi=2147483647 ber=2147483647 rscp=2147483647 level=0,mLte=CellSignalStrengthLte: rssi=2147483647 rsrp=2147483647 rsrq=2147483647 rssnr=0 cqi=2147483647 ta=2147483647 level=0 parametersUseForLevel=0,mNr=CellSignalStrengthNr:{ csiRsrp = 2147483647 csiRsrq = 2147483647 csiSinr = 2147483647 ssRsrp = 2147483647 ssRsrq = 2147483647 ssSinr = 2147483647 level = 0 parametersUseForLevel = 0 },primary=CellSignalStrengthLte}
    mCellInfo=[CellInfoLte:{mRegistered=YES mTimeStamp=2291553756941ns mCellConnectionStatus=2147483647 CellIdentityLte:{ mCi=122172695 mPci=383 mTac=31740 mEarfcn=5035 mBands=[] mBandwidth=2147483647 mMcc=310 mMnc=260 mAlphaLong= mAlphaShort= mAdditionalPlmns={} mCsgInfo=null} CellSignalStrengthLte: rssi=-109 rsrp=-109 rsrq=-9 rssnr=2147483647 cqi=2147483647 ta=2147483647 level=1 parametersUseForLevel=0 android.telephony.CellConfigLte :{ isEndcAvailable = false }}, CellInfoLte:{mRegistered=NO mTimeStamp=2291553756941ns mCellConnectionStatus=2147483647 CellIdentityLte:{ mCi=2147483647 mPci=167 mTac=2147483647 mEarfcn=5035 mBands=[] mBandwidth=2147483647 mMcc=310 mMnc=260 mAlphaLong= mAlphaShort= mAdditionalPlmns={} mCsgInfo=null} CellSignalStrengthLte: rssi=-113 rsrp=-116 rsrq=-16 rssnr=2147483647 cqi=2147483647 ta=2147483647 level=0 parametersUseForLevel=0 android.telephony.CellConfigLte :{ isEndcAvailable = false }}]
```

I can see a reading in there only under "mGsm=CellSignalStrengthGsm: rssi=-113".  I'm currently connected with LTE, maybe that is the problem but not sure what to do with it.

Any other logs or anything I should look at?

**Comment by presslab-us** [comment]
I found this patch for older AOSP which doesn't seem to be applied for AOSP 11.  It looks like the API has changed somewhat and it's not clear how to apply this patch to the latest Android.  I'm also not sure if it's even still needed.

https://github.com/phhusson/treble_patches/blob/dfb61bd27273f11bcb1f11de3d49de030daf374a/patches/platform_frameworks_opt_telephony/0001-Make-better-signal-levels-on-Huawei-devices.patch

**Comment by longnhieu7** [comment]
@presslab-us Have you solve this problem? I am using Pixel Experience Plus on Huawei P20lite and I had choosed the HUAWEI devices in "Treble Settings" for "Misc feastures" but it not work.

**Comment by presslab-us** [comment]
I have not solved the problem.

**Comment by Iceows** [comment]
I have noticed the same problem on Huawei Prague (PRA-LX1)

**Comment by Iceows** [comment]
I have solve the problem. Please see my repo https://github.com/Iceows/huawei_prague_rom/blob/main/patch-diff/001-FixSignalPRA-1stCommit-changes.diff

**Comment by presslab-us** [comment]
@Iceows thanks so much, it's working perfect for me on Android 12

**Comment by presslab-us** [comment]
Fixed with https://github.com/phhusson/platform_frameworks_opt_telephony/pull/9
