### ISSUE TITLE
No sound with headphones over USB-C

### ISSUE THREAD

**Issue by gr0ndpa** [phhusson/treble_experimentations#1886]
Flashed AOSP 11.0 v308 yesterday on my Xiaomi Mi 11 Lite 5G. While BT headset works, common headset over USB-C won't.
"use alternate audio policy" already ticked in phh settings.
No sound from headset when playing a song, but from speaker.
Here logs from MatLog. Hope it helps
[logs-2021-06-06-18-04-52.zip](https://github.com/phhusson/treble_experimentations/files/6604477/logs-2021-06-06-18-04-52.zip)

**Comment by phhusson** [comment]
Please send a zip of all files in /vendor/etc

Le dim. 6 juin 2021 à 18:09, ॐ gr0ndpa ॐ ***@***.***> a
écrit :

**Comment by gr0ndpa** [comment]
Just checked. All files in /vendor/etc are compressed to a zip approx. 300MB

**Comment by phhusson** [comment]
k, all files in /vendor/etc/audio and the files in /vendor/etc that starts
with audio_policy_

Le dim. 6 juin 2021 à 21:30, ॐ gr0ndpa ॐ ***@***.***> a
écrit :

**Comment by gr0ndpa** [comment]
OK, second!

**Comment by gr0ndpa** [comment]
Here we go!!! Thx @phhusson 
[etc_new.zip](https://github.com/phhusson/treble_experimentations/files/6604799/etc_new.zip)

**Comment by phhusson** [comment]
I see no `audio` subfolder, did you mix both? There should be
/vendor/etc/audio_policy_configuration.xml AND
/vendor/etc/audio/audio_policy_configuration.xml, but I see only one of
them (which?)

Le dim. 6 juin 2021 à 21:41, ॐ gr0ndpa ॐ ***@***.***> a
écrit :

**Comment by gr0ndpa** [comment]
OK, Let me check once again

**Comment by gr0ndpa** [comment]
This is inside, please check ss
![photo_2021-06-06_22-37-25](https://user-images.githubusercontent.com/58663588/120939332-24bd0d00-c707-11eb-9bb3-4d49aaa1eeec.jpg)

**Comment by phhusson** [comment]
I'm asking for /vendor/etc/audio_policy_configuration.xml
You're showing me /vendor/etc/audio/audio_policy_configuration.xml

Le dim. 6 juin 2021 à 22:38, ॐ gr0ndpa ॐ ***@***.***> a
écrit :

**Comment by gr0ndpa** [comment]
Sorry!! hope now it's OK!
[audio_policy_configuration.zip](https://github.com/phhusson/treble_experimentations/files/6604924/audio_policy_configuration.zip)
![Screenshot_20210606-230325](https://user-images.githubusercontent.com/58663588/120940106-0fe27880-c70b-11eb-825b-b5d0a07f17ea.png)

**Comment by gr0ndpa** [comment]
Or do you need all of them?

**Comment by CypherUG** [comment]
I'm having a similar issue.

**Comment by gr0ndpa** [comment]
Solved on my Mi 11 Lite 5G with the 309 build! Gr8 job!
Thx @phhusson
