### ISSUE TITLE
The proximity and light sensor on the phone does not work  (cubot king kong mini 2)

### ISSUE THREAD

**Issue by MaiklGureev** [phhusson/treble_experimentations#1907]
Hello. thanks for the firmware. Please fix one problem. The proximity and light sensor on the phone does not work (cubot king kong mini 2).

**Comment by phhusson** [comment]
Give logcat right after reboot, and give the result of `adb shell dumpsys
sensorservice`
Also, how do you test those sensors?

**Comment by MaiklGureev** [comment]
Thank you for your attention, but everything was decided. I reinstalled the firmware and it worked. I don’t know why these 2 sensors didn’t work the first time. 
Now everything works. Thanks for the super firmware. It is 1000 times better than stock from manufacturers.

**Comment by MaiklGureev** [comment]
I am test in https://play.google.com/store/apps/details?id=ru.andr7e.sensortest
