### ISSUE TITLE
S9 Plus Notification Prompt Bug

### ISSUE THREAD

**Issue by EnricoOnG965F** [phhusson/treble_experimentations#191]
https://prnt.sc/kvhxex

i hope the Picture says everything

**Comment by EnricoOnG965F** [comment]
i mean the Notification Prompt is a bit left i think

**Comment by EnricoOnG965F** [comment]
i fixed it by changing Display size but the screen is cut off even with Overlay fix from Enes

**Comment by phhusson** [comment]
What is "Overlay fix from Enes"?
And can you try without it?
Simply rebooting didn't fix the notifications not being at the right place?
Is it centered in landscape mode when scrolling from center?

**Comment by EnricoOnG965F** [comment]
Rebooting fixes it and It is centered in Landscape,.

**Comment by EnricoOnG965F** [comment]
the overlay Fix is a zip to flash with twrp, which fixes the the statusbar for most phones like S9/+
