### ISSUE TITLE
Bug with bluetooth headphones in call (aosp 10 and 11)

### ISSUE THREAD

**Issue by MaiklGureev** [phhusson/treble_experimentations#1914]
hello! I hear my voice when making calls in bluetooth headphones soundpeats true air 2. 
how to fix it?

my device is CUBOT KINGKONGMINI2

**Comment by idfake** [comment]
I can confirm this issue.
Is there anything we can do to help fix this?

**Comment by MaiklGureev** [comment]
I can't say exactly what the reason is, but I have a CUBOT KING KONG MINI 2 phone with the official firmware android 10 and AOSP 10 and I installed the official firmware from CUBOT KING KONG MINI 1 android 9 on it, then AOSP 10 and the problem disappeared. But a bunch of other bugs appeared, for example, the proximity sensor began to turn off during a call and the screen did not start from pressing any button on the phone.

**Comment by idfake** [comment]
This guy [here](https://github.com/phhusson/treble_experimentations/issues/1783#issuecomment-863916443) says https://github.com/phhusson/treble_experimentations/issues/1321 also helped for his Cubot KingKong Mini2.
Can we please get this fix into the image?

**Comment by MaiklGureev** [comment]
I first put the firmware on top of one official one, then another. I do not know how this problem was solved. if you know which file can be responsible for this, you can compare these 2 firmware.

there is no echo in the bluetooth headset
https://www.cubot.net/platform/Support/detail/id/311/cid/8.html

there is an echo in the bluetooth headset
https://www.cubot.net/platform/Support/detail/id/419/cid/60.html

**Comment by MaiklGureev** [comment]
I smashed this phone against the wall.

**Comment by idfake** [comment]
I didn't.
