### ISSUE TITLE
[Galaxy A11] FP Scanner doesn't work.

### ISSUE THREAD

**Issue by CovaleViolet** [phhusson/treble_experimentations#1916]
I successfully flashed AOSP GSI, there's no FP Lock setting, also enabled the workaround option, still nothing.

**Comment by CovaleViolet** [comment]
EDIT: The other lock options such as PIN, Pattern and Password also doesn't work.

**Comment by phhusson** [comment]
fixed with stock unmodified vendor/boot, correct?

Le lun. 21 juin 2021 à 17:41, CovaleViolet ***@***.***> a
écrit :
