### ISSUE TITLE
[Meizu 18] Hangs at splash sometimes

### ISSUE THREAD

**Issue by AndyCGYan** [phhusson/treble_experimentations#1919]
Device: Meizu 18 (meizu_18_CN)
PHH AOSP version: v309
Vendor version: R (Flyme 9)

Device would hang at splash sometimes - the chance of booting up is roughly 50-50. Log shows some SurfaceFlinger crash.

Log since boot: [sfloop.txt](https://github.com/phhusson/treble_experimentations/files/6717220/sfloop.txt)

**Comment by phhusson** [comment]
Try removing https://github.com/phhusson/device_phh_treble/blob/android-11.0/vndk.rc#L50

**Comment by AndyCGYan** [comment]
> Try removing https://github.com/phhusson/device_phh_treble/blob/android-11.0/vndk.rc#L50

Nope, same thing.

**Comment by AndyCGYan** [comment]
Haven't happened once since updating base FW to 9.2.5.0 - closed.
