### ISSUE TITLE
MTP FOR NOTE 9 IS NOT WORKING

### ISSUE THREAD

**Issue by manofsteel2017** [phhusson/treble_experimentations#192]
along with mobile setting

**Comment by phhusson** [comment]
That's two totally different issues
And no need to yell

**Comment by manofsteel2017** [comment]
I wasn't yelling lol
Sorry caps were on

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by phhusson** [comment]
see https://github.com/phhusson/treble_experimentations/issues/225
