### ISSUE TITLE
[Chopin] Flashes violently when the screen is dimmed

### ISSUE THREAD

**Issue by ivysrono** [phhusson/treble_experimentations#1920]
[Xiaomi Poco X3 GT - Full phone specifications](https://www.gsmarena.com/xiaomi_poco_x3_gt-10949.php)
[Redmi Note 10 Pro 5G/POCO X3 GT (chopin) Firmware Downloads | Xiaomi Firmware Updater](https://xiaomifirmwareupdater.com/firmware/chopin/)

Similar to #72 , maybe.
It can be reproduced while dragging the brightness adjustment bar.
The higher the brightness, the more serious the problem. There is basically no problem when the brightness is zero.

**Comment by phhusson** [comment]
Tick "use alternate backlight scale"

26 juin 2021 09:45:51 ivysrono ***@***.***>:

**Comment by ivysrono** [comment]
Thank you very much.
BTW, the 'Enable DT2W' seems not work.
