### ISSUE TITLE
Unusual  Battery consumption & usage data is unavailable even after applying overlay.

### ISSUE THREAD

**Issue by abdullah5490** [phhusson/treble_experimentations#1927]
Its Infinix note7, mtk6768, "system as root" partition, uses AB varients of GSIs.
Battery usage data is unavailable in all GSIs I tried so far. I thought it would be an overlay issue. So I flashed https://github.com/phhusson/treble_experimentations/tree/v309 few days ago because its pre-rooted, build and placed my device's overlay and its now loaded correctly as scene in the screenshot
![overlay](https://user-images.githubusercontent.com/15821394/124502773-855e6900-dddd-11eb-8ca8-33f12261bfa0.png)
After 3 more battery cycles, I'm still seeing this
![battery usage](https://user-images.githubusercontent.com/15821394/124502823-a2933780-dddd-11eb-9742-dedb6a3ceebe.jpeg)
Let me know which kind of logs are needed, I want to cooperate fully to track this issue down. I want to check my battery usage details because its quite higher than expected and I need to know which app is drainning actually.

**Comment by phhusson** [comment]
reboot, go into battery settings, and dump logcat: `adb logcat -b all -d >
log.txt` and attach log.txt

Le lun. 5 juil. 2021 à 19:14, abdullah5490 ***@***.***> a
écrit :

**Comment by abdullah5490** [comment]
> reboot, go into battery settings, and dump logcat: `adb logcat -b all -d > log.txt` and attach log.txt. 

Ok, here it is. I rebooted the device, entered my pattern, go to Settings> Battery> Option menu> Show battery usage> Option menu> Show full device usage. Then closes everything from recent apps list, then taken this log via ADB which i'm attaching below.
[log.txt](https://github.com/phhusson/treble_experimentations/files/6765914/log.txt)

**Comment by abdullah5490** [comment]
Any update found in the logs?

**Comment by phhusson** [comment]
nope, atm i can't see why you would get this behavior

Le jeu. 8 juil. 2021 à 09:39, abdullah5490 ***@***.***> a
écrit :

**Comment by abdullah5490** [comment]
Then, drop few possible fixes that I must try? Because the one and only solution that i know was building overlay, which i've done already but its not working as you scene.

**Comment by abdullah5490** [comment]
Any update about this issue? 
I tried V312 today and getting exactly the same behavior. 
I need to delete my product partition before flashing GSI to resize system partition, is this problem caused by  that?

**Comment by abdullah5490** [comment]
OK, So after  having new overlay, battery usage stats began to display. I'll investigate about the battery consumption and will create a new issue about it.
