### ISSUE TITLE
No Audio in Calls - G4 PLUS_ATHENE

### ISSUE THREAD

**Issue by luisdambrowski** [phhusson/treble_experimentations#193]
calls do not work in Android Pie.

**Comment by luisdambrowski** [comment]
generate logcast?

**Comment by Lyudmila17** [comment]
no need to show any result because the _fucking_ phone doesn't have the required HALs

can you close the issue, @phhusson ?

**Comment by phhusson** [comment]
That's a guess (that's mine at least), or what actually happen?

**Comment by Lyudmila17** [comment]
Just no hal. Motorola works lazily in their devices.

**Comment by phhusson** [comment]
That's a Moto G4. Oh the hell is that Motorola's fault?

**Comment by Lyudmila17** [comment]
As I said, "Motorola works lazily in their devices". This device (and who knows if the rest of them too) has a hardcoded camera HAL, missing HALs (like this one), uses 32bit arch when it supports 64bit, a lot of crap in their kernels... it's simply Motorola's fault.

**Comment by phhusson** [comment]
That's bullshit.
Before treble there was no ""am"" (audiomanager) HAL to handle this issue (there was no point of doing HALs). This isn't a treble native device, so there is no reason it should exist.

Also, doing 32bits is quite the opposite of lazily, it's making the best use of their device.

**Comment by Lyudmila17** [comment]
And what's your explanation for a lot of devices with AM HAL but this doesn't?

Oh yeah? whats the difference then?

**Comment by phhusson** [comment]
The guy who ported treble to this device didn't include the AM HAL?

**Comment by Lyudmila17** [comment]
Ah, you never said I could include the AM HAL. How is it?
