### ISSUE TITLE
Aosp 11.0 v310 vanila

### ISSUE THREAD

**Issue by Gamisu** [phhusson/treble_experimentations#1937]
Mi 8 stock vendor from android 10, can't flash open gapps 11 (pico),error 20 in orange fox recovery "you need android 10 gapps " message popps up

**Comment by phhusson** [comment]
Sounds like a bug in opengapps

**Comment by Gamisu** [comment]
Maybe thats the reason ,there is no official open gapps 11 yet!Thank you for the response ...... you are doing amazing work ....!!!
