### ISSUE TITLE
flashing magisk causes all GSIs to not boot

### ISSUE THREAD

**Issue by kusti420** [phhusson/treble_experimentations#1943]
my device is infinix zero 8 (X687), it has _dynamic partitions_ and every time i try flashing magisk it doesnt boot and throws me into bootloader. ive tried pretty much every magisk version out there, regular and canary, always the same outcome. ive tried both flashing through custom recovery and patching boot img and flashing that through bootloader. what should i do to fix that?

**Comment by voltcraft1** [comment]
https://github.com/phhusson/treble_experimentations/issues/1522#issuecomment-705078951

**Comment by kusti420** [comment]
> [#1522 (comment)](https://github.com/phhusson/treble_experimentations/issues/1522#issuecomment-705078951)

tried phh-magisk v21.0, it boots, but doesnt get installed
doesnt automatically install magisk manager and when i manually install it then it shows installed N/A

**Comment by ShahrukhAbrar** [comment]
if(flashingmagisk=No_Boot)
{
cout<<"Don't";
}
else
cout<<"No support";

**Comment by kusti420** [comment]
fixed it myself
https://forum.xda-developers.com/t/tutorial-magisk-on-gsi-on-devices-with-dynamic-partition.4311045/#post-85384331
