### ISSUE TITLE
Xiaomi Mi A2 Bugs broken led notifications v105

### ISSUE THREAD

**Issue by byblady** [phhusson/treble_experimentations#197]
Dear, in Xiaomi Mi A2, I have detected the following bugs:

* Led notifications, always on.

Regards, dear.

**Comment by flori-uni** [comment]
I've experienced the opposite. My Led notification is allways off.

**Comment by p4block** [comment]
Rebooting a few times toggles the LED state, which is funny. It never properly works, though. 

I have /sys/class/leds :

```
phhgsi_arm64_ab:/ # find /sys/class/leds                                        
/sys/class/leds
/sys/class/leds/red
/sys/class/leds/blue
/sys/class/leds/wled
/sys/class/leds/green
/sys/class/leds/led:flash_0
/sys/class/leds/led:flash_1
/sys/class/leds/led:flash_2
/sys/class/leds/lcd-backlight
/sys/class/leds/led:torch_0
/sys/class/leds/led:torch_1
/sys/class/leds/led:torch_2
/sys/class/leds/led:switch_0
/sys/class/leds/led:switch_1
/sys/class/leds/mmc0::
/sys/class/leds/mmc1::
/sys/class/leds/flashlight
/sys/class/leds/torch-light0_1
/sys/class/leds/torch-light0
/sys/class/leds/torch-light1
```

Only the `red` light is plugged into the actual led, which is white. For some reason it gets initialized to 255 sometimes. 

Attached is my lights hal.

[lights.sdm660.zip](https://github.com/phhusson/treble_experimentations/files/2429070/lights.sdm660.zip)

**Comment by phhusson** [comment]
WIP at https://github.com/phhusson/device_phh_treble/pull/49

**Comment by phhusson** [comment]
Split auto brightness to https://github.com/phhusson/treble_experimentations/issues/226

**Comment by penn5** [comment]
Pie vendor or Oreo vendor?
