### ISSUE TITLE
Does these issues are due to deleting Product partitions?

### ISSUE THREAD

**Issue by abdullah5490** [phhusson/treble_experimentations#1977]
I am having 3 major issues on my Infinix Note7 MTK6768. I think all of these 3 are related to "vendor" thing. While flashing GSI, I have to delete logical-partition product in order to create space for resizing "system" partition. 
As I understand, the "vendor" contents are placed in /product/ (which I deleted before flashing). Is this the  reason of all of these issues I'm facing on my device? If yes, how can I resize system without deleting "product", to fix them?
Read detailed description of my issues along with logs below:
Fake Third sim slot: #1950 
Slow LTE connection: #1934 
No battery usage stats even overlay is present: #1927

**Comment by realKarthikNair** [comment]
product/logical partition isnt part of vendor
