### ISSUE TITLE
The OS boots up perfectly the first time but gets stuck in bootloop (Android logo) after the device is restarted .

### ISSUE THREAD

**Issue by UncleSam450** [phhusson/treble_experimentations#1978]
Hello. I recently installed AOSP 11.0 v312 on my Oukitel K9 (MT6765) using which initially runs perfectly on my device . However, I am  experiencing boot-loops that occurs only after  the device is restarted for the first time. The OS itself always runs perfectly on first boot following the flashing of system.img, however it will always end-up in boot-loops (stuck on Android logo) after the device is restarted. I can use the phone for hours and it will always work perfectly as long as I don't restart or shut down the device. The only way it will boot again is if I wipe data and cache with TWRP , but the problem repeats itself on restart . The system will boot up only once and never again.

I have tried both with vanilla version and gapps versions, but same thing happens. I also re-wiped and re-flashed everything and tested with no apps installed, and no settings altered just to make sure, but same result on first restart.

I have gone back to AOSP 10.0 v222 temporarily as this version runs with no issue, so I assume it must be something with Android 11 ? I was just wondering if anyone may have any clue what could cause this kind of issue. I have been trying to figure this one out for a while . Thanks in advance .

**Comment by phhusson** [comment]
Set up a screen lock and when asked whether to "enable secure boot" say yes

Le dim. 22 août 2021 à 16:19, UncleSam450 ***@***.***> a
écrit :

**Comment by UncleSam450** [comment]
Thank you so much, the device restarted normally, and the issue is now fixed !!! You really made my day.

Thank you for all the AMAZING work you are doing.
