### ISSUE TITLE
VoLTE for AOSP 8.1 on Moto G4 Plus (athene)

### ISSUE THREAD

**Issue by aadityasingh1** [phhusson/treble_experimentations#198]
How to enable VoLTE on AOSP 8.1? There's not any option to enable it.

**Comment by Klozz** [comment]
No option
https://forum.xda-developers.com/showpost.php?p=77641482&postcount=3141

**Comment by aadityasingh1** [comment]
There's not any way to enable VoLTE in AOSP 8.1 like its in AOSP 9.0?

**Comment by phhusson** [comment]
I don't plan on supporting VoLTE on AOSP 8.1
But I'll gladly accept PR-ed backporting my AOSP 9.0 work to 8.1 (simply backporting treble app + VOLTE-CAF RRO should be enough)

**Comment by aadityasingh1** [comment]
Okay thanks.
One more thing camera is completely broken on AOSP 8.1 on athene/moto g4
plus. Everything else is completely smooth experience.
And if you want logs I can provide..
Thanks again 😇
