### ISSUE TITLE
[OnePlus Nord CE 5G] Fingerprint sensor issue

### ISSUE THREAD

**Issue by manugame** [phhusson/treble_experimentations#1989]
I have a problem with my fingerprint sensor, here is the result of `adb shell lshal` and `adb logcat`

[lshal.txt](https://github.com/phhusson/treble_experimentations/files/7085036/lshal.txt)
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/7085037/logcat.txt)

i found in logcat this

```
08-31 17:00:45.116   571   571 E SELinux : avc:  denied  { find } for interface=vendor.oplus.hardware.biometrics.fingerprint::IBiometricsFingerprint sid=u:r:hal_fingerprint_oppo_compat:s0 pid=1723 scontext=u:r:hal_fingerprint_oppo_compat:s0 tcontext=u:object_r:default_android_hwservice:s0 tclass=hwservice_manager permissive=0
08-31 17:00:45.116   571   571 E SELinux : avc:  denied  { find } for interface=vendor.oppo.hardware.biometrics.fingerprint::IBiometricsFingerprint sid=u:r:hal_fingerprint_oppo_compat:s0 pid=1728 scontext=u:r:hal_fingerprint_oppo_compat:s0 tcontext=u:object_r:default_android_hwservice:s0 tclass=hwservice_manager permissive=0
```

I hope this can help.

**Comment by phhusson** [comment]
It's an under-display fingerprint?

**Comment by manugame** [comment]
yes

**Comment by phhusson** [comment]
well under-display fingerprint are mostly not supported, and I don't feel
like doing development for OnePlus currently, since they'll migrate to
ColorOS/Oplus firmwares at some point (and I supposedly already support
Oplus firmwares)

**Comment by manugame** [comment]
Okay thanks

**Comment by phhusson** [comment]
But feel free to reopen once you get Oplus/ColorOS firmware
