### ISSUE TITLE
Mobile network is not available on htc u11+

### ISSUE THREAD

**Issue by jinbolx** [phhusson/treble_experimentations#2]
Mobile network is not available on htc u11+ ,please fix it

**Comment by phhusson** [comment]
Could you check that adb logcat -b radio |grep OEM raises an
OEM_DCFAIL_CAUSE4 or something like that?
I'd guess this is the same bug as Essential PH-1 (and other Qualcomm
platforms)

2018-01-25 12:58 GMT+01:00 jinbolx <notifications@github.com>:

**Comment by jinbolx** [comment]
[log.txt](https://github.com/phhusson/treble_experimentations/files/1669736/log.txt)

**Comment by phhusson** [comment]
Thanks
So that's indeed exactly the same error as Essential PH-1.

**Comment by jinbolx** [comment]
you just release v12,is this bug fixed?

**Comment by DroidAlexandra** [comment]
So that's indeed exactly the same error as Essential PH-1.

Means no proper/full Treble implementation from HTC or what's the exact issue? 
Thanks

**Comment by phhusson** [comment]
As far as I remember, I managed to fix the issue by setting the APN by myself with some specific settings (was it forcing IPv4? adding "ia" to the list of apn types? something else?) but that's fuzzy
Perhaps the first step to debug this would be to take the apns-conf.xml from stock ROM and try to copy the config of your operator's APN

**Comment by jinbolx** [comment]
here is the apns-conf.xml from htc u11+ stock ROM 


[apns-conf.txt](https://github.com/phhusson/treble_experimentations/files/1858314/apns-conf.txt)

**Comment by phhusson** [comment]
Should be fixed in next release

**Comment by phhusson** [comment]
Can you test on v18?

**Comment by newyesor** [comment]
Mobile data is work but it's not perfect download app from playstore.

I found a problem about  download app from playstore .
I can not download multiple app from playstore.
I can fix by remove gapp from this rom and flash new gapp again.

**Comment by phhusson** [comment]
Yeah well that's a known overall problem of the ROM.
Known workaround is to ungrant "storage" permission to Play Store

Thanks
