### ISSUE TITLE
[Xiaomi Redmi 4X] Fingerprints are forgotten at every reboot

### ISSUE THREAD

**Issue by MarcosJungbluth** [phhusson/treble_experimentations#200]
[getprop.txt](https://github.com/phhusson/treble_experimentations/files/2403365/getprop.txt)

The problem has already been fixed in source, but persists in Semi-GSI roms, my fingerprint reader is Goodix

**Comment by Shadowghost** [comment]
Which vendor and boot did you use? Are you on permissive selinux?
Because last time I tewted with official LineageOS 15.1 vendor and boot, fingerprint only showed up in settings when changing to permissive selinux and it didn't stick when adding one on permissive.

**Comment by MarcosJungbluth** [comment]
I used the vendor's ROM lineage-15.1-20180822-UNOFFICIAL-santoni.zip, is the only one that works 100% of the basic functions (flashlight and adaptive brightness) I believe that the selinux is in permissive, I have not changed anything in it lately

In my case, with each Reboot I have to delete all the files in the folder /persist/data/gxfp/0_0 before Reboot to be able to configure it again

**Comment by Shadowghost** [comment]
Oh damn it I misread the title again. It's without "Note", was talking about mido...
You can check selinux state by typing '`getenforce` in a terminal.
Sorry for the confusion.

**Comment by MarcosJungbluth** [comment]
Yep, it's in permissive

**Comment by phhusson** [comment]
I've been told that what is used as a fix in ROM is:
frameworks/base/services/core/java/com/android/server/fingerprint/FingerprintService.java
set CLEANUP_UNUSED_FP to false
I'll definitely not do that (it seems to be a security problem to me), but this might help debugging.
I believe this issue is definitely in the vendor implementation.
