### ISSUE TITLE
[Sharp Aquos S2] No in-call audio.

### ISSUE THREAD

**Issue by Lovetz** [phhusson/treble_experimentations#201]
There is no sound in the headset while talking on the phone. Can not hear the voice of the interlocutor. And he does not hear me. Verified on v105

lshal, the content of /vendor/manifest.xml, and a dump of logcat -s PHH after making a call:
https://drive.google.com/open?id=1XSvanNtCb5U4y-N-ZHiMrZAzJoC_yXK4

**Comment by phhusson** [comment]
All the files are web pages and are close to identical, they are not the files I requested.

**Comment by Lovetz** [comment]
> All the files are web pages and are close to identical, they are not the files I requested.

I apologize for the mistake. Overloaded the files. Now those that are necessary.
https://drive.google.com/open?id=1L2j0Gxwrm5-y7sBPsg0n8BUbi8sWO4gn

**Comment by Lovetz** [comment]
Hi. This archive helps with my issue: https://forum.xda-developers.com/showpost.php?p=77963614&postcount=61
Just replace all files in vendor/etc/ and set 0644 permissions.

**Comment by phhusson** [comment]
I'm closing this because this post is very old. But feel free to re-open it if you feel this issue is still relevant.
