### ISSUE TITLE
on7xelte (G610F) stuck on bootanimation

### ISSUE THREAD

**Issue by Otus9051** [phhusson/treble_experimentations#2014]
I have a Samsung Galaxy J7 Prime 2016 (G610F) on which I flashed the latest A/B Vanilla GSI. I am using H-Vendor from Astrako on XDA. It is stuck on bootanimation for almost an hour now. Please help.

**Comment by maltalef101** [comment]
Sorry to reopen an old issue... but I'm facing the same issue.

How did you manage to fix this? As I see you've closed this thread, I suppose you have indeed found a solution.

**Comment by Otus9051** [comment]
I closed this as a stale issue. Use YumiVendor, it can also boot the latest Android 12 GSI. 
Download: https://dl.7870.otus9051.codes/on7xelte/Vendors/YumiVendor_TESTING.zip
