### ISSUE TITLE
Broken camera record sound s21

### ISSUE THREAD

**Issue by vlubosh** [phhusson/treble_experimentations#2021]
Is possible to check, fix broken audio while video record on s21 exynos devices?
 There is all time rustling sound, like incorrect microphone drivers etc.

**Comment by vlubosh** [comment]
@
[2021-09-12-16-32-32.txt](https://github.com/phhusson/treble_experimentations/files/7271781/2021-09-12-16-32-32.txt)
Here is log from last gsi( it's pixel but the problem is identical)

**Comment by katsvg** [comment]
I'm getting the same issue, no matter what settings are changed in the Treble settings, it wont change. Seems to work fine if you're only recording audio though, as soon as you're recording video together with audio, it completely breaks. (G991B)

**Comment by haridhayal11** [comment]
@phhusson I 'm having this issue as well.

**Comment by haridhayal11** [comment]
I have attached the output of `dumpsys media.audio_policy` when running phh gsi and the audio files from vendor/etc. 

My device is SM-G991B

[s21_audio_policy_dump.txt](https://github.com/phhusson/treble_experimentations/files/7799262/s21_audio_policy_dump.txt)
[s21_vendor_audio_configs.zip](https://github.com/phhusson/treble_experimentations/files/7799263/s21_vendor_audio_configs.zip)

**Comment by katsvg** [comment]
> I have attached the output of `dumpsys media.audio_policy` when running phh gsi and the audio files from vendor/etc.
> 
> My device is SM-G991B
> 
> [s21_audio_policy_dump.txt](https://github.com/phhusson/treble_experimentations/files/7799262/s21_audio_policy_dump.txt) [s21_vendor_audio_configs.zip](https://github.com/phhusson/treble_experimentations/files/7799263/s21_vendor_audio_configs.zip)

Hopefully these are useful, still really not sure why it would bug out like that but i guess it's something to do with Exynos devices in particular

**Comment by zainullahk** [comment]
try using a gcam port

**Comment by katsvg** [comment]
> try using a gcam port

using a gcam port results in the same problem

**Comment by haridhayal11** [comment]
This issue can be closed as I have found a way to resolve this issue.

In /vendor/etc/audio_policy_configuration.xml

Removing Back-Mic from primary input solves this issue.


I have made a flashable zip for replacing the file in /vendor/etc
[Microphone_Fix_GSI_exynos2100.zip](https://github.com/phhusson/treble_experimentations/files/7913595/Microphone_Fix_GSI_exynos2100.zip)

**Comment by phhusson** [comment]
It's not fixed if it involves flashing anything other than GSI.

Thanks for the info, I'll see what I can do with that

Le ven. 21 janv. 2022 à 13:36, Haridhayal ***@***.***> a
écrit :

**Comment by haridhayal11** [comment]
Stock and edited files are inside this zip. You can compare these files @phhusson 

[compare_audio_policy_configuration.zip](https://github.com/phhusson/treble_experimentations/files/7913830/compare_audio_policy_configuration.zip)

**Comment by katsvg** [comment]
> This issue can be closed as I have found a way to resolve this issue.
> 
> In /vendor/etc/audio_policy_configuration.xml
> 
> Removing Back-Mic from primary input solves this issue.
> 
> I have made a flashable zip for replacing the file in /vendor/etc [Microphone_Fix_GSI_exynos2100.zip](https://github.com/phhusson/treble_experimentations/files/7913595/Microphone_Fix_GSI_exynos2100.zip)

assuming this is a workaround, it works perfectly for this case, tested it on the latest GSI version and it doesn't seem to interfere with anything, and it works.

**Comment by abbasupremo** [comment]
Works on Samsung s20+
Tnks a lot
