### ISSUE TITLE
In version v105, the aop 9.0 does not start. not even in the boot animation

### ISSUE THREAD

**Issue by jeangraff** [phhusson/treble_experimentations#203]
8.1 in AOSP usually starts
[logvcc.txt](https://github.com/phhusson/treble_experimentations/files/2406187/logvcc.txt)

**Comment by phhusson** [comment]
device

**Comment by jeangraff** [comment]
Moto g5

**Comment by phhusson** [comment]
that's not an oem treble, so i can't really help you.
Though I can tell from the logs that you're flashing an arm variant, while your vendor is arm64

**Comment by jeangraff** [comment]
Ops is true, I ended up downloading wrong 😂 Sorry for the inconvenience

**Comment by luisdambrowski** [comment]
I had this problem on g4 plus athene. v105 has not started; I thought it was the new boot.img file available;

**Comment by luisdambrowski** [comment]
I had this problem on g4 plus athene. v105 has not started; I thought it was the new boot.img file available;
