### ISSUE TITLE
[Huawei] Camera & IR

### ISSUE THREAD

**Issue by megapinky** [phhusson/treble_experimentations#204]
Hi, Phh v105 gapps load's Huawei stuff like camera and IR remote control, IR don't work and Camera FC in every swap between camera/camcorder, picture can not be taked
Device Mate 10 ALP
https://drive.google.com/file/d/10PTOte2BgZxgPP1OIAjR3-4chvZSzeFC/view?usp=drivesdk

Also charge while device is off don't work, send to recovery can't take logs

**Comment by phhusson** [comment]
That's three issues, not one.
