### ISSUE TITLE
How to download from ci.android.com?

### ISSUE THREAD

**Issue by Kevin8675** [phhusson/treble_experimentations#2049]
Found out that there is a stable android 12 gsi on ci.android.com. How do I dowload? Clicking the download button just gives me a list of things but where is the actual zip to install?

**Comment by phhusson** [comment]
That's quite offtopic, since I don't provide support for Google's GSI
but you take aosp_arm64-img.zip and extract system.img from there

**Comment by Kevin8675** [comment]
I see. Thanks! Sorry I saw the google gsi posted in the wiki and didn't raelly know where else to ask this.
