### ISSUE TITLE
[Huawei Mate 10] "Ok google" hotword doesn't work

### ISSUE THREAD

**Issue by megapinky** [phhusson/treble_experimentations#205]
Phh v105 gapps Hotword "ok Google" don't work
Device Mate 10 ALP 
https://drive.google.com/file/d/1_ULt3G4ikS63EkcIUKfvsxk5sg44B77G/view?usp=drivesdk

https://drive.google.com/file/d/1iOIqtuIRNyCKkXDsvlruepOqsSTro1Mj/view?usp=drivesdk

https://drive.google.com/file/d/1o-jWpwcJPtPsT7C_OqeBqpmXqEabC2p2/view?usp=drivesdk

https://drive.google.com/file/d/1IbeeXGUe4J-q-Is4PkvVvRhmhX7xS5l2/view?usp=drivesdk

**Comment by phhusson** [comment]
Does learning trigger an error? Does learning recognize "Ok google"?
Do you see this issue both when learning is on AND off?
Do you see this issue both when the device is display on, display off on-charge, and display off off-charge?

**Comment by megapinky** [comment]
on v105 learning doesnt give error, finish recognizing "Ok Google" 3 times
Ok google dont work on display on, off, with carger and without
sometime works when Assistan app is open
thanks

**Comment by megapinky** [comment]
Sorry, i try v106 and learning don't load even if data is erased,  "ok Google" only recognized on Google app
When go to launcher the text "ok Google" appears in the search bar for a second
https://drive.google.com/file/d/1ad0w0s3xCJ2hq5ikPWnzKIFSwE6buYrI/view?usp=drivesdk
