### ISSUE TITLE
AOSP 12.0 v400.a: Root not working by default

### ISSUE THREAD

**Issue by CHECK-1234** [phhusson/treble_experimentations#2052]
Problem:
I succesfully booted system-squeak-arm64-ab-vndklite-vanilla.img on LG V40. When I tried termux and did "su" and it did not give me root.

**Comment by phhusson** [comment]
Yup known issue, I added it in the list of known issues of the release note

Le sam. 30 oct. 2021 à 00:47, CHECK-1234 ***@***.***> a
écrit :
