### ISSUE TITLE
Realme C11 :WIFI and camera not working ( v.400a)

### ISSUE THREAD

**Issue by danhu2203** [phhusson/treble_experimentations#2054]
The Camera and WIFI not working on Realme C11.When I open the camera, the camera crashes. When I toggle on wifi, the wifi does not show any connection. The data is working fine. That's the problem for now. I hope it can be fixed

**Comment by phhusson** [comment]
On my AOSP v313?

**Comment by danhu2203** [comment]
on v400a

**Comment by danhu2203** [comment]
when I open camera app, it stays on the camera logo only

**Comment by phhusson** [comment]
Both wifi and camera works fine on my realme c11
are you using STOCK UNMODIFIED OEM vendor?

**Comment by danhu2203** [comment]
so sorry , i use custom rom vendor on that gsi first. Now , using stock rui vendor all working perfectly. Thanks  for your build
