### ISSUE TITLE
[Pixel 2 XL] No RIL, No SIM, No Wifi v400.a

### ISSUE THREAD

**Issue by vatva691** [phhusson/treble_experimentations#2056]
Additional info:
When bootup, Modem Service has been stopped
There was no baseband info in Setting
The system have glitch graphic in scrolling.
IMEI not found
Logs:
[dmesg.txt](https://github.com/phhusson/treble_experimentations/files/7447789/dmesg.txt)
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/7447791/logcat.txt)

**Comment by phhusson** [comment]
Try this:
```
adb root
adb remount
adb shell mkdir -p /firmware/radio
adb shell chcon u:object_r:firmware_file:s0 /firmware
adb shell chcon u:object_r:firmware_file:s0 /firmware/radio
adb reboot
```

**Comment by vatva691** [comment]
thanks, ril and wifi is back,
