### ISSUE TITLE
Realme C1 Camera and Flashlight not work in A12 v400.a

### ISSUE THREAD

**Issue by custosoft** [phhusson/treble_experimentations#2058]
Hello everyone. I just wanna to fix this issue regarding to camera and flashlight.

I installed and open Gcam go and Open Camera but not work because of camera is in another app but the stock camera app disappeared. I enabled Camera Hal3 but nothing happened
Also the flashlight in quick setting is camera is in use but i did not toggle it on. I just take a log and screenshot as proof.

Phone: Realme C1
Vendor: Stock based on Color Os 6 running android 9 Pie. (RMX1811EX_11.A.71)
Gsi used: Aosp 12 v400.a vanilla

Log:
[2021-10-29-23-59-02[1].txt](https://github.com/phhusson/treble_experimentations/files/7457777/2021-10-29-23-59-02.1.txt)

Screenshot:
![Screenshot_20211029-235949](https://user-images.githubusercontent.com/74230345/139785652-1141715c-14f5-4ea6-9b16-52e762ae907b.png)
![Screenshot_20211030-000004](https://user-images.githubusercontent.com/74230345/139785654-1fe53b44-7a5d-4130-a828-ff88afded43f.png)
![Screenshot_20211030-000016](https://user-images.githubusercontent.com/74230345/139785655-e85d5716-aed4-4914-9add-cda1caf7fb96.png)

https://user-images.githubusercontent.com/74230345/139785671-7bb2ecc9-8b24-4cfb-b9db-7523129dd12b.mp4

I hope that you read this issue. TIA.

**Comment by RFX-LEGEND** [comment]
Find a camera app on the play store or install the stock Realm C1 camera app. I can suggest Manual Camera Lite as I use it myself on my Moto X4.

**Comment by custosoft** [comment]
ok. i got it wrong. it must enable camera2api.

**Comment by Aj-style** [comment]
Custosoft , I have realme C1 too and I am facing the same issue camera and flashlight don't work , how did you managed to get camera working ? Please help
