### ISSUE TITLE
An error occurred when the screen brightness decreased!

### ISSUE THREAD

**Issue by iamverycute** [phhusson/treble_experimentations#2066]
My device is Redmi Note 10 5G (camellia) CPU: MTK 700

I try to adjust the screen brightness and reduce it a little...

but after closing the screen, open the screen again, the screen brightness is always 1 ( This does not happen with increased brightness )

```
settings get system screen_brightness  #  value: 1
```
The screen is now black! ( I could see a faint glow from the screen )

I have to connect to the computer, execute command

```
settings put system screen_brightness  50
```
Is there a way to solve it?

If not, I will make an app to listen to the broadcast when the screen is turned on and off, and WRITE_ SECURE_ SETTINGS

Please!  I'll wait for you@phhusson

Sorry, my English is unavailable!

Part of the content is machine translation!

**Comment by iamverycute** [comment]
I can only repair it in a dirty way at present.

https://github.com/iamverycute/brightness_fix

**Comment by phhusson** [comment]
Set minimum backlight level in your device overlay

**Comment by iamverycute** [comment]
> Set minimum backlight level in your device overlay

Oh, man, I have to modify the framework-res.apk ?

I'm tried ro.lcd_min_brightness=50 not work

Thank you!
