### ISSUE TITLE
Custom Recovery doesn't work on Android 12 PHH based builds

### ISSUE THREAD

**Issue by Skelebrawl** [phhusson/treble_experimentations#2069]
My device is a moto one fusion and i'm using Lineage OS 19 build by Andy Yan.
every time i try to enter to recovery the bootsplash of orange fox keeps repeting (like a bootloop)

**Comment by HamzehTamimi** [comment]
same happens to my galaxy a52

**Comment by phhusson** [comment]
This is an issue with recovery, not GSI.
