### ISSUE TITLE
Custom Recovery breaks when using phh Android 12 GSI

### ISSUE THREAD

**Issue by HamzehTamimi** [phhusson/treble_experimentations#2070]
When I install the GSI the and boot back to recovery it keeps showing the splash screen and then black screen and again the splash screen, like a boot loop, whiter it is TWRP or Orange Fox, any help or fix for the problem, to prevent that from happening?

**Comment by phhusson** [comment]
Yes, make a non-broken recovery.
I've been told the issue comes from parsing storage.xml.
