### ISSUE TITLE
The PC cannot recognize the phone.(Huawei P30)

### ISSUE THREAD

**Issue by j7b3y** [phhusson/treble_experimentations#2072]
Hello.
I would like to report a problem I am having with my Huawei P30.
When I connect it to my PC, the PC cannot recognize the phone.
I have checked this with Windows 8,10,11 and Ubuntu 18.04LTS. (I don't have any other environment so I couldn't check it).

(I don't speak English, so I am using a translator. Maybe the text is not correct. Sorry)

**Comment by j7b3y** [comment]
From Windows
"Unable to start this device. (Code 10)

The USB device returned an invalid product description string descriptor."
I was told.

This is a problem that only happens when I put GSI on my Huawei P30.
It did not happen on Stock rom or any other phone, so I don't think it is a PC issue.

**Comment by j7b3y** [comment]
It is highly likely that Huawei intentionally installed it.
Sorry for the dirty eyes.

**Comment by Cyanide-zh** [comment]
> It is highly likely that Huawei intentionally installed it. Sorry for the dirty eyes.

Negative.  USB transfer is available on LYA-AL10 running Pixel Experience GSI android S 2022 January version. [https://github.com/ponces/treble_build_pe/releases/tag/v400.h](url)
