### ISSUE TITLE
[AOSP 12.0 v400.c] Device Not Certified

### ISSUE THREAD

**Issue by yagdev** [phhusson/treble_experimentations#2080]
I can’t log into google or use google apps with this GSI.

Details:
Device: Huawei P20 Lite (ANE-LX1)
GSI Version: Android 12.0 AOSP 400.c
GSI Branch: system-squeak-arm64-ab-gapps

![1A17907A-730D-42E2-B278-8F7F76EA2FCA](https://user-images.githubusercontent.com/53407061/142261914-842d4bf5-438d-4ff1-a930-94a139ed3557.jpeg)
![51F9FC8E-FA17-4374-9205-8735F686B888](https://user-images.githubusercontent.com/53407061/142261926-44a01b7e-6c4d-40f5-ae15-41adb4bc888e.jpeg)

**Comment by truvision-dude** [comment]
yes just use the way around it

**Comment by phhusson** [comment]
Register your device on https://www.google.com/android/uncertified/

To get the ID, you can either:
- adb root, then adb shell, press enter, and at the new prompt, inside adb shell, do sqlite3 /data/data/com.google.android.gsf/databases/gservices.db    'select * from main where name = "android_id";'

**Comment by yagdev** [comment]
Thanks! I didn’t know google had this feature as that’s very cool of them.
