### ISSUE TITLE
[Essential PH-1] RIL/SIM not working 12.0 v400.c

### ISSUE THREAD

**Issue by sambow23** [phhusson/treble_experimentations#2083]
When putting in a SIM, there is no signs that the SIM is recognized
IMEI works
[dmesg.txt](https://github.com/phhusson/treble_experimentations/files/7598371/dmesg.txt)
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/7598372/logcat.txt)

**Comment by phhusson** [comment]
Did you use vndklite variant?

Le mer. 24 nov. 2021 à 20:42, CattaRappa ***@***.***> a
écrit :

**Comment by sambow23** [comment]
I did not, but after trying it I get the same results
[dmesg2.txt](https://github.com/phhusson/treble_experimentations/files/7598698/dmesg2.txt)
[logcat2.txt](https://github.com/phhusson/treble_experimentations/files/7598699/logcat2.txt)

**Comment by truvision-dude** [comment]
What model is your phone, on my moto one 5G ace, it refused to detect sim cards with GSIs until I flashed motorola's android 11 firmware

**Comment by sambow23** [comment]
Its in the issue title, this device doesnt have a Android 11 vendor/firmware so that isnt really possible

**Comment by sambow23** [comment]
Seems like my SIM card slot was dirty, as it seemed to not work on stock as well. Cleaned it and all is good
