### ISSUE TITLE
Bluetooth barcode scanner triggers HOME key

### ISSUE THREAD

**Issue by Pepetruen0** [phhusson/treble_experimentations#210]
Every time I scan a barcode (which literally just sends the string of text plus the enter key) I'm kicked out of the scanning app back to the home screen. Upon further inspection I discovered that this particular secuence is assigned to Home on the system shortcuts. Suffice to say this completely breaks the usability of any bluetooth keyboard since every time the enter key is pressed, the user is sent back to the home screen. Is there any way to disable this behavior?
![screenshot_settings_20180922-183524](https://user-images.githubusercontent.com/10561579/45924472-f8b5bb00-bece-11e8-9547-cf57181462e0.png)

**Comment by phhusson** [comment]
According to your screenshot, Home is Search + Enter, not just Enter
Also, I use bluetooth keyboards (including enter obviously) without any issue.

Could you check the actual keyevents using the adb shell getevent command?
(start the getevent command, and read a barcode, then dump the result of the getevent command)

**Comment by phhusson** [comment]
Any news?
