### ISSUE TITLE
Galaxy A50 Android 12.400.d Can't enter Network settings.

### ISSUE THREAD

**Issue by theh0riz0n** [phhusson/treble_experimentations#2107]
Hi,
I was trying to open Network settings to change to LTE but it crashes when i'm trying to enter. If you want bug report or screen capture feel free to ask me.

**Comment by phhusson** [comment]
Well yes provide logs

**Comment by trelemorele-theprofessionaldumbass** [comment]
Hey thanks for quick reply. I'm attaching bug report and screen capture. I've got 4G working by typing network code to dialer.

> 

> 
[bugreport-treble_arm64_bvN-SQ1D.211205.016.A1-networkcrash.zip](https://github.com/phhusson/treble_experimentations/files/7739281/bugreport-treble_arm64_bvN-SQ1D.211205.016.A1-networkcrash.zip)

**Comment by trelemorele-theprofessionaldumbass** [comment]
[screen-20211218-141451.zip](https://github.com/phhusson/treble_experimentations/files/7739289/screen-20211218-141451.zip)
Heres screen capture.

**Comment by ponces** [comment]
You were using PE GSI and nowhere on your issue you refer that important detail...
It has been fixed since the v400.d release of 18/12/2021.
Please, close the issue.
