### ISSUE TITLE
Galaxy A50 Android 12.400.d Dynamic theming engine does not work.

### ISSUE THREAD

**Issue by theh0riz0n** [phhusson/treble_experimentations#2108]
Hi, Dynamic icons, lockscreen, apps does not work as expected. Only blueish theme is adapting. Also lockscreen font is set to Roboto not Google Sans.

**Comment by ponces** [comment]
You're asking for pixel customizations on an AOSP rom...

**Comment by ponces** [comment]
Please, close the issue.
