### ISSUE TITLE
[Xiaomi Mi MIx 2S] Dac (usb-c to 3.5mm jack) converter not working

### ISSUE THREAD

**Issue by rbuehlma** [phhusson/treble_experimentations#211]
Even when the DAC converter is plugged, the audio comes through the phones speaker.

The mount from this ticket: https://github.com/phhusson/treble_experimentations/issues/133
slaves that issue.

`mount -o bind /vendor/lost+found /vendor/etc/audio || true`

**Comment by notsyncing** [comment]
Today I upgraded my mix2s to Lineage 16.0 GSI (20180924) and did not have this issue, my DAC adapter is working. Could you try to update your vendor to `miui_MIMIX2S_8.9.20_be2f1f2e26_9.0` and try again?

**Comment by phhusson** [comment]
@rbuehlma on what ROM is this?
This mount bind shouldn't change anything on AOSP

**Comment by rbuehlma** [comment]
Ok, its now working for me as well without the mount. Probably I did something wrong or a reboot was required. Thanks anyway.

**Comment by phhusson** [comment]
I'm guessing this is an instability then.
Feel free to change the title of the issue and reopen it, if the issue appears again

**Comment by notsyncing** [comment]
Funny, though usb dac works on my device, I found that I still need the 
```
mount -o bind /vendor/lost+found /vendor/etc/audio || true
```
to make bluetooth audio work. Still a vendor issue then. Let's see if xiaomi would fix this in coming versions.

**Comment by phhusson** [comment]
Reading from /vendor/etc/audio is a lineage modification, it's not in
AOSP. So it's hardly a vendor issue

Le mar. 25 sept. 2018 à 06:42, Song Fuchang <notifications@github.com> a
écrit :

**Comment by notsyncing** [comment]
@rbuehlma I'm using lineage, aosp should not have this issue.
