### ISSUE TITLE
Oneplus N100: 3.5mm jack not working

### ISSUE THREAD

**Issue by flexponsive** [phhusson/treble_experimentations#2110]
Oneplus N100 with release [AOSP 11.0 v313](https://github.com/phhusson/treble_experimentations/releases/tag/v313) installed, the headphone jack is not working. Sound continues to play through the device speakers.

Following the advice given in #49 and #2038, I tried the following:

- "Use alternate way to detect headset" from Phh Treble Settings (and for good measure also tried the "Force headset switch (Huawei)" setting. Neither worked.

- `setprop persist.sys.overlay.devinputjack true` and reboot. No change.

- `getevent`: when jack is plugged in, events appear:
```
/dev/input/event5: 0005 0002 00000001
/dev/input/event5: 0005 0004 00000001
/dev/input/event5: 0005 0007 00000001
/dev/input/event5: 0000 0000 00000000
```

For reference: [adb shell dumpsys media.audio_policy](https://github.com/phhusson/treble_experimentations/files/7739964/audio_policy.txt) and [adb shell getprop](https://github.com/phhusson/treble_experimentations/files/7739965/getprop.txt)

**Comment by phhusson** [comment]
Try use alternate audio policy

**Comment by flexponsive** [comment]
Thanks for very fast reply, that worked! 

I created a wiki page for this device - [OnePlus Nord N100](https://github.com/phhusson/treble_experimentations/wiki/OnePlus-Nord-N100)
