### ISSUE TITLE
please fix the volte issue in exynos processor like 9609/9610 I can't use GSI for the problem As well as my phone dont have so much custom rom support. Please fix the issue

### ISSUE THREAD

**Issue by Suman-1410** [phhusson/treble_experimentations#2115]
please fix the volte issue in exynos processor like 9609/9610 I can't use GSI for the problem As well as my phone dont have so much custom rom support. Please fix the issue

_Originally posted by @Suman-1410 in https://github.com/phhusson/treble_experimentations/discussions/2096#discussioncomment-1850734_

**Comment by aryan0078** [comment]
Same issue on m31

**Comment by phhusson** [comment]
The issue isn't related to being exynos or not.
