### ISSUE TITLE
Any plans to move to GKI?

### ISSUE THREAD

**Issue by zainullahk** [phhusson/treble_experimentations#2118]
google with android 12 released generic kernel any plans to move to this instead?

**Comment by phhusson** [comment]
Instead... of what?
What would you expect from me doing a gki?
Also GKI dates back to Android 11

Le mer. 22 déc. 2021 à 09:31, zainullahk ***@***.***> a
écrit :

**Comment by zainullahk** [comment]
can you help me with this bluetooth issue?
https://github.com/phhusson/treble_experimentations/issues/2117
