### ISSUE TITLE
[MTK Q | A12] SMS breaks with VoLTE enabled.

### ISSUE THREAD

**Issue by ironydelerium** [phhusson/treble_experimentations#2125]
No longer have the log of this issue: I've fixed it personally by patching the MTK IMS APK, but:

https://github.com/phhusson/platform_frameworks_opt_telephony/blob/android-11.0.0_r48-phh/src/java/com/android/internal/telephony/metrics/TelephonyMetrics.java#L2241

https://github.com/phhusson/platform_frameworks_opt_telephony/blob/android-12.0.0_r16-phh/src/java/com/android/internal/telephony/metrics/TelephonyMetrics.java#L2300

Behavior:
Attempt to send SMS.
SMS goes out, though the SMS client doesn't recognize this (it never got notified of success). 
com.mediatek.ims crashes with MethodNotFoundException: 
- caller: com.mediatek.ims.ril.ImsRILAdapter method `void sendSMS(int, int, String, String, boolean, byte[], android.os.Message)` 
- target: com.android.internal.telephony.TelephonyMetrics method `void writeRilSendSms(int, int, int, int)` 

It looks like Google added another parameter to this method (changing it's signature to `void writeRilSendSms(int, int, int, int, long)`), which broke existing IMS implementations.

I worked around it by patching the calling code in the IMS APK (changed so it calls with the extra argument, filled with 0), which seems to work. SMS goes out as expected without crashing the IMS stack.

Patched IMS: [mtk-ims-patched.zip](https://github.com/phhusson/treble_experimentations/files/7776235/mtk-ims-patched.zip)
Changes to IMS: [ims.patch.gz](https://github.com/phhusson/treble_experimentations/files/7776236/ims.patch.gz)

It's probably also reasonable to patch TelephonyMetrics.java:

```
public void writeRilSendSms(int phoneId, int rilSerial, int tech, int format) {
  writeRilSendSms(phoneId, rilSerial, tech, format, 0);
}
```

**Comment by phhusson** [comment]
Thanks. Please send a PR to my frameworks/opt/telephony

**Comment by ironydelerium** [comment]
Will do, as soon as I've tested it on something not my daily driver. (I only have one MTK device at the moment that's got a Q vendor, the others never got anything besides Android 7; should have something by Thursday.)
