### ISSUE TITLE
cant boot into twrp 

### ISSUE THREAD

**Issue by zainullahk** [phhusson/treble_experimentations#2130]
a71 400.e a11 vendor 
when i switch off the phone and hold power and volume up it just boots into the system and not twrp 
it works with adb (adb reboot recovery)

**Comment by phhusson** [comment]
ask your twrp maker to rebase on latest twrp branch

Le lun. 3 janv. 2022 à 14:39, zainullahk ***@***.***> a
écrit :

**Comment by zainullahk** [comment]
it is based on 3.6.0

**Comment by haridhayal11** [comment]
On newer samsungs you have to plug in the usb cable and hold the key combo to boot into recovery. Maybe try that

**Comment by zainullahk** [comment]
notfixed 
i installed magisk to boot into twrp
