### ISSUE TITLE
Bluetooth audio not working

### ISSUE THREAD

**Issue by cuynu** [phhusson/treble_experimentations#2131]
I'm using Nusantara GSI has based on Phhusson GSI.

Can connect to Bluetooth speaker but audio not working on my phone
Vendor has no any folder related with Bluetooth on overlay,app folder
 Phone SoC : Unisoc SC9863A
Original stock firmware android version : 9.0 Pie
![IMG_20220104_192230](https://user-images.githubusercontent.com/90895715/148058467-eb170267-7125-4e7f-aa9b-4cccc464e0dc.jpg)

**Comment by phhusson** [comment]
Try my AOSP GSI.

**Comment by zainullahk** [comment]
in phh treble settings misc enable disable a2dp offload 
fixed it for me

**Comment by cuynu** [comment]
Problem solved, Thank Phhusson and Zainullahk :3
