### ISSUE TITLE
UI lags (~30fps) when on enforcing kernel on Galaxy S21 Exynos series

### ISSUE THREAD

**Issue by haridhayal11** [phhusson/treble_experimentations#2135]
When force 120fps is set in phh settings, everything runs at 30fps
When force 120fps is set in phh settings and Disable HW overlays is ticked, everything runs at 60fps

Increasing min gpu clock doesnt do anything.
`echo 512000 > /sys/kernel/gpu/gpu_min_clock`

```
cat /sys/kernel/gpu/gpu_min_clock                                      
494000
```

**Comment by Star56IQ** [comment]
Help with this

**Comment by DrRambone** [comment]
Confirmed, only 60 Hz with HW disabled, anywise 30Hz

**Comment by haridhayal11** [comment]
This could be seen in the logs
`Access denied finding property "persist.sys.sf.hs_mode"`

I flashed permissive kernel and it partially fixes the issue. No longer need to disable HW. Everything runs at 60fps.
Im not sure about 120fps because the inbuilt fps counter is broken. Needs more testing.

**Comment by haridhayal11** [comment]
@phhusson I fixed 120Hz by removing 60Hz only display modes from dts. You can checkout the commit [here](https://github.com/haridhayal11/android_kernel_samsung_exynos2100/commit/38909dbadc810a0a227958870d3563e74ac6fd27)

**Comment by haridhayal11** [comment]
120Hz issue was sorted out using my kernel. But the ui lags seems to be present even on my kernel (with 120Hz) fixed when it is enforcing. Only thing I could find in the logs when enforcing is whats seen in this [comment](https://github.com/phhusson/treble_experimentations/issues/2135#issuecomment-1016567532). `Access denied finding property "persist.sys.sf.hs_mode"`

When I tick Disable HW overlays. The device works at 120fps.

**Comment by TQMatvey** [comment]
Confirm ui lags.... Sad thing i thought rom specific issues, but now i am noticing those tiny freezes when scroling on all gsis

**Comment by haridhayal11** [comment]
> Confirm ui lags.... Sad thing i thought rom specific issues, but now i am noticing those tiny freezes when scroling on all gsis

What you are referring to is different. You are running enforcing kernel?

**Comment by TQMatvey** [comment]
Oh hm then why an i getting those freezes, scrolling webpage, news, youtube etc, i am getting like tiny freezes

**Comment by haridhayal11** [comment]
> Oh hm then why an i getting those freezes, scrolling webpage, news, youtube etc, i am getting like tiny freezes

Can you keep it out of this issue please? Those arent related to this.

**Comment by haridhayal11** [comment]
Issue is resolved with this https://github.com/phhusson/device_phh_treble/pull/322
