### ISSUE TITLE
Pixel launcher search is black (pe 400.h)

### ISSUE THREAD

**Issue by zainullahk** [phhusson/treble_experimentations#2145]
on pixel experience 400.h the search bar is black
![Screenshot_20220119-221418_Pixel Launcher](https://user-images.githubusercontent.com/72628804/150189980-8ed37294-bb6f-4b77-bc07-39212490a047.png)

**Comment by phhusson** [comment]
This is not the place for Pixel Experience bugs.

**Comment by zainullahk** [comment]
Ok but Ponce's removed the place to report issues on his GitHub and this is
not  a thing on pixel experience official (this is a bug of the light mode
thing )
