### ISSUE TITLE
[Umidigi F1] No Status bar or Nav bar on Android 12 GSIs

### ISSUE THREAD

**Issue by cidlover** [phhusson/treble_experimentations#2149]
In the same boat as another issue I found on here trying to use some Android 12 GSI images which is no status bar nor nav bar, the Fullscreen Immersive bug thing.
LineageOS S: same issue
OctaviOS: same issue
Pixel Experience: Twrp bootloop, not even booting after the dd command, Permissiver or Magisk flash. Instant black screen then back to splash screen

Logcatting is not an option since adb can't see the device since I think it's tied to the surfceflinger or the systemui
The phone has a MediaTek Helio P60 cpu and came out of box with Android 9 Pie so this means Android 11 is my max version on this phone?

**Comment by phhusson** [comment]
I assume you mean you have that issue on my AOSP 12 correct?

Give logs: `adb logcat -b all -d > log.txt` and attach log.txt

**Comment by zainullahk** [comment]
switch to geuster nav and switch back to normal nav

**Comment by cidlover** [comment]
Sorry about no reply for a few days but I have reinstalled Havoc OS 4.3 Android 11 just as a backend so I can have an phone out and about. That and work in the morning is a killer but after my shift tomorrow, I will take a TWRP backup and try again.

I have tried switching back and forth from normal nav to gesture bar had no effect, If I am correct, that's tied to SystemUI too right?

**Comment by toufune** [comment]
I'm using F1Play, but I'm suffering from the same symptoms.
I cannot send logs because ADB cannot be used.

**Comment by cidlover** [comment]
Just tried this GSI: SuperiorOS-12-arm64_ab-bvN-Unofficial.img which got me into a boot animation loop (Looks like it boots then reshows the boot animation again) but my PC saw a ADB device this time and I took a log

@toufune What GSI image did you try, I have tried all 12 GSIs I wanted to and get that or the boot animation loop, have you tried the Permissiver_v5.zip? I have not yet.
https://androidfilehost.com/?fid=6006931924117940902

[logcat.txt](https://github.com/phhusson/treble_experimentations/files/7975607/logcat.txt)

**Comment by toufune** [comment]
I use system-squeak-arm64-ab-vndklite-vanilla-secure.
I haven't tried Permissiver.

**Comment by cidlover** [comment]
@toufune did you have any luck with any Android 12 GSI? I have not tried again with mine with any.
