### ISSUE TITLE
Bluetooth speakers/earbuds do not work

### ISSUE THREAD

**Issue by ByteSeb** [phhusson/treble_experimentations#2156]
When I try to connect to any bluetooth device like a speaker or a pair of earbuds, I get this error where it always fails to connect to them, and when I am able to connect to them, I cannot use them to play any audio, they just are connected and it does not do anything.

![BTError](https://user-images.githubusercontent.com/85042318/151468112-3bd7178a-dd64-4ecc-b5d6-ea30829470e2.jpeg)

**Comment by phhusson** [comment]
No device name

**Comment by ByteSeb** [comment]
Sorry, I forgot. I am using a Moto G8 Power (sofiar)
