### ISSUE TITLE
[OnePlus 10 Pro / Moto Edge X30] Bootloop

### ISSUE THREAD

**Issue by AndyCGYan** [phhusson/treble_experimentations#2160]
Devices: OnePlus 10 Pro / Moto Edge X30, potentially other SM8450 devices
PHH AOSP version: v400.h
Vendor version: S

Loops at bootanim. Notably, audioserver keeps crashing.
In the case of OP10Pro, Google GSI (`S2B2.211203.006`) boots okay; untested on X30 (no longer have a unit).

Log while bootlooping: [log.txt](https://github.com/phhusson/treble_experimentations/files/7965776/log.txt)
`dumpsys media.audio_flinger` from stock: [dsaf-stock.txt](https://github.com/phhusson/treble_experimentations/files/7965778/dsaf-stock.txt)
`dumpsys media.audio_flinger` from Google GSI: [dsaf-google.txt](https://github.com/phhusson/treble_experimentations/files/7965784/dsaf-google.txt)
`lshal` from Google GSI: [lshal-google.txt](https://github.com/phhusson/treble_experimentations/files/7965785/lshal-google.txt)

**Comment by AndyCGYan** [comment]
Formally submitting an issue for public documentation sake. Haven't seen anyone else onto running GSIs on SM8450; if someone did and succeeded with something PHH-based, please inform.

**Comment by phhusson** [comment]
K, crash doesn't seem to be related to audio policy, so I don't think that's my fault. I guess we should look at patches that are specifically in android12-gsi branch. Though since those are non-Google-certified vendors, it could be a bit expected

**Comment by phhusson** [comment]
Can't say I see anything relevant in https://android-review.googlesource.com/q/project:platform%252Fframeworks%252Fav+branch:android12-gsi ...

**Comment by AndyCGYan** [comment]
Found offending commit: https://github.com/phhusson/platform_frameworks_av/commit/34068a3cdea71e28376f35d02f1b2399d3c8d214; reverted and booted (LOS, not AOSP, but shouldn't matter here).

**Comment by AndyCGYan** [comment]
/vendor/etc/[audio_policy_configuration.xml](https://github.com/phhusson/treble_experimentations/files/7965886/audio_policy_configuration.txt)
/vendor/etc/audio/sku_taro{,_qssi}/[audio_policy_configuration.xml](https://github.com/phhusson/treble_experimentations/files/7965888/audio_policy_configuration.txt)

**Comment by AndyCGYan** [comment]
Fixed with https://github.com/phhusson/platform_frameworks_av/commit/bff5b222cbfc12697d72e26abce2c4882499f6d3.
