### ISSUE TITLE
AOSP 12.0 v400.a-b-c-d-e-f-g-h !

### ISSUE THREAD

**Issue by yura73** [phhusson/treble_experimentations#2164]
From release to latest release, the same issues persist on my device.
namely ----
1.does not work system UI
2.flickering display
3.SIM cards are not recognized
there is no way to remove the logs!
device
Doogee S88 Pro 
arm64(sar)
vendor Android 10
СPU MediaTek Helio P70 2.1 GHz MT6771T
GPU ARM Mali G72 MP3 900MHz
communication module firmware- e977_vsim_71_q0_lwtg_v0.2.3_s210729
it's all incorrigible ????

**Comment by phhusson** [comment]
Why can't you show logs?

**Comment by yura73** [comment]
no message appears to allow debugging by usb.

**Comment by yura73** [comment]
[logcat ful.txt](https://github.com/phhusson/treble_experimentations/files/8008806/logcat.ful.txt)
[logcat radio.txt](https://github.com/phhusson/treble_experimentations/files/8008807/logcat.radio.txt)
I managed to remove these logs

**Comment by yura73** [comment]
hope this helps

**Comment by phhusson** [comment]
Did you do a factory reset?

**Comment by phhusson** [comment]
This log is on my AOSP v400.h?

**Comment by yura73** [comment]
I solved the problem by editing the build prop vendor
changing these values

persist.radio.multisim.config=tsts
persist.vendor.radio.msimmode=tsts
ro.vendor.radio.max.multisim=tsts
ro.telephony.sim.count=3
ro.telephony.sim.count=3ro.vendor.sim_refresh_reset_by_modem=1
ro.vendor.mtk_external_sim_support=1
ro.vendor.mtk_external_sim_only_slots=4

like this
persist.radio.multisim.config=dsds
persist.vendor.radio.msimmode=dsds
ro.vendor.radio.max.multisim=dsds
ro.telephony.sim.count=2
ro.telephony.sim.count=3ro.vendor.sim_refresh_reset_by_modem=0
ro.vendor.mtk_external_sim_support=0
ro.vendor.mtk_external_sim_only_slots=0

now everything works great
sorry for wasting time
Thank you

**Comment by branislav-kurajda** [comment]
@yura73 Hey there! Just wondering, are you running AOSP on S88 Pro without any issues?
