### ISSUE TITLE
[Homtom ht17pro (mt6737m)] problem incoming calls.

### ISSUE THREAD

**Issue by vitekrus777** [phhusson/treble_experimentations#217]
aosp 9 of the latest version (105), a problem arose: the incoming to mt6737m do not work.
Such a problem: the caller's beeps are on, but I have nothing displayed.
Here is the logcat from the very beginning of the start, until the first reboot (the script runs there and it reboots the machine):
https://gist.github.com/vitekrus777/e1069f99f4095b241bba7aa91aea5449
Here is the logcat after the first restart and until the boot, then 3 calls (incoming, outgoing, incoming):
https://gist.github.com/vitekrus777/d0a460a4344fc3dc3e0b39c592f5224c

Another logcat. I took it off just before the bell. When you call 2 sim, all is normal, incoming passes and is displayed. Do not pass the incoming on the SIM, which is the default for data transfer. If you change the setting to 2 sim, then when you call it, the connection drops, and then there is no network on both sims.
In the 2 call logcat, first entering 1 sim (with the incoming problem) and then a call for 2 sim (with normal display).
https://gist.github.com/vitekrus777/c2b1097d91f374bf44adc42086cdcefa

Another 2 separate logcat on the radio and on the events. Also 2 calls 1 sim (without display), 2 sim (normal).
[logcat_radio_27.09.2018_15.55.36.txt](https://github.com/phhusson/treble_experimentations/files/2423973/logcat_radio_27.09.2018_15.55.36.txt)
[logcat_events_27.09.2018_15.56.34.txt](https://github.com/phhusson/treble_experimentations/files/2423974/logcat_events_27.09.2018_15.56.34.txt)

**Comment by apogen** [comment]
me also have the same prob with incoming calls on mt6763 umidigi z2

**Comment by phhusson** [comment]
Fixed in https://github.com/phhusson/device_phh_treble/commit/3e655b7c4b737d687388cb466a7a99e93242b7cb

**Comment by penn5** [comment]
Again we need new issue for similar bug
