### ISSUE TITLE
Android security stuck at August 2021

### ISSUE THREAD

**Issue by SotongDJ** [phhusson/treble_experimentations#2175]
- Device
  - Redmi note 10s (rosemary)
- Version
  - AOSP 12.0 v402
- Type
  - system-squeak-arm64-ab-vndklite-gapps-secure
- Build number
  - treble_arm64_bgS-userdebug 12 SQ1A.220205.002 220208 test-keys
- Kernel version
  - 4.14.186-perf-g4dc492d4ca7e

Clean install
I try system-squeak-arm64-ab-vanilla, the patch is February 2022.
And I flash back system-squeak-arm64-ab-vndklite-gapps-secure, the patch return to August 2021

![7e5fa0d6-cbe2-4d48-8b7b-c40f75e5dad7](https://user-images.githubusercontent.com/337402/153118504-c9d4cf22-6909-400c-9909-bdffd67cb6fb.png)

**Comment by phhusson** [comment]
Yes, "secure" fakes vendor's Security Patch Level to cheat SafetyNet into thinking we are OEM's ROM. This doesn't mean the patches are removed.
