### ISSUE TITLE
Whatsapp camera issue.

### ISSUE THREAD

**Issue by kasinjsh** [phhusson/treble_experimentations#218]
I'm using P10 (VTR-L29C432) whit Phh 9.0 v105 right now, but bug exists in 8.1 GSI build also, not specific Phh build issue, it exists on OpenKirin builds also.

When I'm trying to post a new picture in Whatsapp I take add picture button (that small camera icon on right) it opens camera. I take a picture and start writing a caption and if caption ends whit emoji from emoji and press send. Camera window is closed and no picture or caption is sent to Whatsapp.

Logcat if it helps. [Whatsapp bug.txt](https://github.com/phhusson/treble_experimentations/files/2430984/Whatsapp.bug.txt)

Edit: Today I got more serious bug. I was unable to take a picture whit Whatsapp camera. I opened camera, it did open, I framed shot and pressed Shutter button. After a hang camera closed and gave Me an error about unable to open camera. Log attached. After that some process hangs and drains battery.

[whatunablecam.txt](https://github.com/phhusson/treble_experimentations/files/2437130/whatunablecam.txt)

**Comment by CReimer** [comment]
I have the exact same problem on my Honor View 10 (BKL-L09C432B172) and Phh-Treble v107
