### ISSUE TITLE
AOSP 12.0 Mobile data not working

### ISSUE THREAD

**Issue by chen-ky** [phhusson/treble_experimentations#2191]
Device: Huawei Mate 9 (MHA-L29)
Release: AOSP 12.0 v402

Tried on both system-squeak-arm64-ab-gapps.img and system-squeak-arm64-ab-vndklite-gogapps-secure.img

Clean flash both images by running `fastboot erase system` before flashing them with `fastboot flash system xxxxxxxxxx.img`

Logs collected using `adb logcat '*:W'`
[logcat_warn.txt](https://github.com/phhusson/treble_experimentations/files/8052198/logcat_warn.txt)

I have checked the APN settings, everything seems fine and is set correctly, normal phone call seems to work (tested by dialing a USSD code, I assume this is similar to dialing a phone number)

**Comment by Lorramaeloveharry** [comment]
I also encounter this on my Huawei
I think you should enable request ims network on phh settings.

**Comment by chen-ky** [comment]
> I also encounter this before on my Huawei I think you should enable request ims network on phh settings.

Can someone confirm that this works before I try again?

**Comment by CodeingBoy** [comment]
> I also encounter this before on my Huawei I think you should enable request ims network on phh settings.

Thanks. You saved my day. 👍

**Comment by chen-ky** [comment]
> I also encounter this before on my Huawei I think you should enable request ims network on phh settings.

I tried v402 again and can confirm that this fixes the issue.

For anyone wondering, the setting is located at: Settings > Phh Treble Settings > IMS features > Request IMS network
