### ISSUE TITLE
GSI random soft-reboot

### ISSUE THREAD

**Issue by rama982** [phhusson/treble_experimentations#2192]
Device: Infinix Note 10 Pro
Mtk Helio G95 Android 11
Stock Vendor, Stock Kernel, No Magisk

When screen is turned off there is always some random Soft-Reboot. 

How to get logs?

**Comment by rama982** [comment]
here is logcat after soft-reboot happen
[log.txt](https://github.com/phhusson/treble_experimentations/files/8052698/log.txt)

**Comment by phhusson** [comment]
Magisk is 100% there
Looks like crash might be triggered by "Android System Intelligence"? I
don't think I ship this APK in my AOSP? Are you using my AOSP with gapps
pre-integrated?
