### ISSUE TITLE
No LTE/LTE+, stays in H+ all the time [Razer Phone/cheryl]

### ISSUE THREAD

**Issue by linuxct** [phhusson/treble_experimentations#22]
APNs are properly configured, only happens on GSIs.   

![screenshot_phone_services_20180415-095214](https://user-images.githubusercontent.com/3966313/38776155-cfd14aca-4092-11e8-8023-e5945b47ed47.png)

**Comment by phhusson** [comment]
Fixed by https://github.com/phhusson/vendor_hardware_overlay/commit/37f0fc7cd6eb10bd34b217e9ed0126b4771afd88

**Comment by linuxct** [comment]
Issue solved with last comment's after manually cherry-picking it to my device, aka, decompiling the apk, adding the shared user id of system to the manifest and recompiling and signing with platform keys.  

![da0nzl2xcaajwrb](https://user-images.githubusercontent.com/3966313/38777336-79e6ea3e-40a6-11e8-977b-139dd2915360.jpg)
