### ISSUE TITLE
BT issues on P10

### ISSUE THREAD

**Issue by kasinjsh** [phhusson/treble_experimentations#220]
I'm using P10 (VTR-L29C432) whit Phh 9.0 v105 (log is from v104 build) . After a while BT connection starts to not work as it should. I'm testing it whit Xiaomi Mi band (1st version, 2nd revision) whit original Mi Fit app. It can work ok for a while like 12h or more and suddenly Mi Fit can't connect to band. It shows connecting and thats it. After BT toggle it is fine, connection works.

[logcat Pie v104 BT problems Huawei P10.txt](https://github.com/phhusson/treble_experimentations/files/2430990/logcat.Pie.v104.BT.problems.Huawei.P10.txt)

**Comment by phhusson** [comment]
Nowadays, in Treble app, there is an option to enable bluetooth workarounds, using Huawei option should fix this.
