### ISSUE TITLE
[Doogee S88 Pro] GSI 12 fingerprint sensor acting as a button

### ISSUE THREAD

**Issue by PlatonShubin** [phhusson/treble_experimentations#2204]
Hello there. It's not really a big issue but it's kinda inconvenient. On my **Doogee S88 Pro** the rear fingerprint sensor acts as a button in certain apps. In any browser (Google Chrome) as the options button which is very inconventient cause you can touch it unintentionally many times and then page options appear. And in the terminal emulator as well. It keeps inputting this ~ sign when you touch it. A button mapper says this button is "F10 (140)" button. I also have two extra side physical buttons. The upper one is CAMERA (27) and the lower one is F5 (135). Is there any workaround for this?

**Comment by phhusson** [comment]
Yes that's easy to fix.
Give the result of `adb shell getevent -i`
Then, run `adb shell getevent`, then press the fingerprint sensor, then
screenshot what appears on the screen where you ran `adb shell getevent`
Finally, give the result of `adb shell 'getprop |grep fingerprint'`


Le lun. 21 févr. 2022 à 10:28, Platon Shubin ***@***.***> a
écrit :

**Comment by PlatonShubin** [comment]
Here, attached the outputs: 

[getev-fp.txt](https://github.com/phhusson/treble_experimentations/files/8108330/getev-fp.txt)
[getev-i.txt](https://github.com/phhusson/treble_experimentations/files/8108331/getev-i.txt)
[getprop.txt](https://github.com/phhusson/treble_experimentations/files/8108332/getprop.txt)

**Comment by phhusson** [comment]
...
The logs you gave me
they were when you touched FINGERPRINT, not button?

**Comment by PlatonShubin** [comment]
No, not button. Here. First I push the camera button, then the button I would like to be assigned in order to program it from settings. And then fingerprint sensor.

`/dev/input/event1: 0001 00d4 00000001
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 00d4 00000000
/dev/input/event1: 0000 0000 00000000
/dev/input/event1: 0001 003f 00000001
/dev/input/event1: 0000 0000 00000000
^[[15~/dev/input/event1: 0001 003f 00000000
/dev/input/event1: 0000 0000 00000000
/dev/input/event2: 0001 0044 00000001
/dev/input/event2: 0000 0000 00000000
^[[21~/dev/input/event2: 0001 0044 00000000
/dev/input/event2: 0000 0000 00000000`

**Comment by phhusson** [comment]
Doesn't fingerprint also trigger F10 button?

**Comment by PlatonShubin** [comment]
Fingerprint triggers F10 button only, yes. Except it works as a sensor of course.

**Comment by phhusson** [comment]
k. So for the additional keys, ATM I have no plan on how to handle that.

**Comment by PlatonShubin** [comment]
Hmm. Okay. I thought the kl files can be written to remap my buttons to act as other buttons. Thanks for the commit again. Anyway, how can I apply this without building the whole firmware?

**Comment by phhusson** [comment]
Yes, kl can be used to map a button to another
but you probably don't want to map it to another button, you probably want to map it to some app?

Though camera button can indeed be mapped to camera button

you can apply this on your own by downloading raw rw-system.sh and pushing it manually to /system/bin/rw-system.sh

**Comment by PlatonShubin** [comment]
Perfect, thank you! So, to be clear: I want my F5 button to become like one of these so I can set them up to do something here in the settings on LineageOS. Search button for example.

![Screenshot_20220221-212818_LineageOS Settings](https://user-images.githubusercontent.com/5220734/155010133-af11f158-adc0-44aa-8b5e-80b3ad5845ba.png)

**Comment by branislav-kurajda** [comment]
@PlatonShubin Kind sir, would you mind relaying to me your experience with running custom android on S88 Pro? Is there any major/minor trouble? Could you also perhaps point me to some documentation on how to achieve this?

**Comment by PlatonShubin** [comment]
> @PlatonShubin Kind sir, would you mind relaying to me your experience with running custom android on S88 Pro? Is there any major/minor trouble? Could you also perhaps point me to some documentation on how to achieve this?

I'm sorry. I wouldn't have time to explain to you in details how it all was done and describe all the issues. I can just point out that there are indeed some issues with installing custom firmware onto the device. But you can do it if you know how to handle SP FlashTool, bootloader fastboot and adb. And if you have some general knowledge about Android. The device seems hard to be customized because it has some crazy hardware backed attestation for secutity.
You can browse our Russian forum for the infos. But I don't think Google Translate will be able to translate everything... Here: [4PDA](https://4pda.to/forum/index.php?showtopic=999819&st=3780)

Anyhow, custom firmware seems to be working quite decently with some minor issues though. But some guys are somehow very unlucky with it. Even I sometimes think about returning to stock. With Magisk of course.

**Comment by branislav-kurajda** [comment]
Shame that such a beautifully looking device is so unaccommodating to
tinkering and one is destined to be using it with software that does god
knows what. Hell, maybe the time has come to buy a Pinephone. Thank you for
such an exhaustive reply though! I will check the forum...And I wonder, is
there a rugged phone that is "easy" to customize?
