### ISSUE TITLE
Unihertz Jelly 2 gets bootloop from AOSP 12.0 v401 on

### ISSUE THREAD

**Issue by DocMAX** [phhusson/treble_experimentations#2206]
Unihertz Jelly 2 gets bootloop from AOSP 12.0 v401 on.
AOSP 12.0 v400.h works fine.

**Comment by phhusson** [comment]
Sorry, but Unihertz devices are not supported by this GSI.

Unihertz quite literally stole money from me

**Comment by DocMAX** [comment]
Stole money? Please be so gracious and support Jelly2.

**Comment by phhusson** [comment]
I bought a Unihertz Titan Pocket from them, and they never delivered it.

**Comment by DocMAX** [comment]
Seems you helped the guys from pixel experience to make this run on android 10 platform. Maybe you can implemement this here to? Because it works with Jelly 2. Thanks.

**Comment by DocMAX** [comment]
v410 is working
