### ISSUE TITLE
boot issue with a mt6580 tablet on android 12 gsi

### ISSUE THREAD

**Issue by Leaft-prog** [phhusson/treble_experimentations#2208]
I have a boot issue with my mediacom iyo 8 tablet (mt6580 soc)  with android 12, the tablet has pie vendor requiring arm32-binder64 A/B system image, with android 11 boots without problem, but with android 12 doesn't boot. Of course i wiped data and cache using stock recovery but its stuck in the boot screen (not the android logo boot screen).

**Comment by phhusson** [comment]
Can you grab logs?
What kind of "doesn't boot" is it?

**Comment by Leaft-prog** [comment]
Its stuck on the mediacom logo (preloader), i don't know if i can grab logs because it cannot boot on the system partition.

**Comment by Leaft-prog** [comment]
![IMG20220223150638](https://user-images.githubusercontent.com/83707338/155335188-3b3c707d-cd60-4611-88fe-e3b985b4096a.jpg)

**Comment by phhusson** [comment]
(I thought your "mediacom" was a typo of "mediatek". nope, fun. And fun
logo too)
Well if you do `adb devices`, does it show your device?

Le mer. 23 févr. 2022 à 15:07, Leaft-prog ***@***.***> a
écrit :

**Comment by theh0riz0n** [comment]
did you removed dm-verity (Android Verified Boot) by flashing vbmeta?
i had that problem on my motorola but only just was an vbmeta problem.

**Comment by Leaft-prog** [comment]
Yes i also did that i forgot to mention

**Comment by Leaft-prog** [comment]
Maybe later i will try again with the new release maybe its fixed

**Comment by theh0riz0n** [comment]
You could try to go through installing pre release versions of A12
when on 400.h fingerprint sensor on Galaxy A50 was working flawlessly now it little bit off.
also on 400.h fixed boot issues on most devices when i was testing on mine.

**Comment by Leaft-prog** [comment]
All versions of android 12 has the same issue on that device (android 11 works everything except audio codecs, android 10 boots but it has screen orientation issues)

**Comment by theh0riz0n** [comment]
> All versions of android 12 has the same issue on that device (android 11 works everything except audio codecs, android 10 boots but it has screen orientation issues)

thats kinda bad.
if you have stock firmware extract it and you could add libraries to own built gsi. althrough its time consuming.
since my daily driver is a cheap motorola it has its own issues. nfc not working ota glitching but i think it's a global issue.

**Comment by Leaft-prog** [comment]
Yes i have stock the stock firmware  (not sources because its a cheap chinese tablet)

**Comment by theh0riz0n** [comment]
> Yes i have stock the stock firmware (not sources because its a cheap chinese tablet)

i think you would need just extract vendor and add it when building
and it should fix issues that you're facing right now.

**Comment by Leaft-prog** [comment]
Ok i will try that solution if android 12.1 dosen't work

**Comment by Leaft-prog** [comment]
Sadly android 12.1 dosen't boot either, the only difference now its that it reboots maybe i will try the building solution or wait for android 13 release date

**Comment by byf3332** [comment]
The problem is, mt6580 is purely a 32bit processor and will never boot up 64 bit system:(
binder64 is for devices with 64bit processor but on 32bit mode.

**Comment by phhusson** [comment]
@byf3332 that's plain wrong. binder64 is a protocol, not an execution format or assembly. It could work just as well on a 8 bit CPU.

**Comment by Leaft-prog** [comment]
With binder64 using android 11 works (also treble info says that the device needs a binder64 image)

**Comment by Leaft-prog** [comment]
Issue fixed in Android 13
