### ISSUE TITLE
Bluetooth can't turn on

### ISSUE THREAD

**Issue by han-han030** [phhusson/treble_experimentations#2209]
Model: ROG Phone1
On Dot OS 5.2 can't turn on Bluetooth

**Comment by zainullahk** [comment]
report to dotos not here

**Comment by han-han030** [comment]
Ok

**Comment by Rocky7842** [comment]
Run into the same issue a few days ago with the same model.(ROG Phone 1)
Manage to find a solution from a Razer phone 2 post.

1.Do a factory reset
2.Flash your gsi again
3.Boot into TWRP ***before first boot into system!***
4.Mount Vendor
5.Go to file manager go to /vendor/overlay
5.Delete BluetoothResCommon.apk
6.Boot to system

Now Bluetooth can work normally with my airpods, other functions(such as In call Bluetooth audio/Aptx) remain to be investigated.
