### ISSUE TITLE
Torch not working in P10

### ISSUE THREAD

**Issue by kasinjsh** [phhusson/treble_experimentations#221]
I'm using P10 (VTR-L29C432) whit Phh 9.0 v105. Quick Torch in notification is not working, it is greyed out. Hardware seems to be working in system level, tested in Open Camera.

**Comment by mikk150** [comment]
Also affects P20 lite

**Comment by penn5** [comment]
This is resolved, @phhusson please close

**Comment by mikk150** [comment]
also works on P20 lite
