### ISSUE TITLE
[Huawei P10] Mobile Connection keeps connecting and disconnecting on AOSP 11 builds

### ISSUE THREAD

**Issue by kelvinyankey6** [phhusson/treble_experimentations#2210]
Hi. Thanks for all your work. I was trying AOSP 11 and it is great. But there is a massive issue with the mobile connection. It keeps connecting to the correct network and then disconnecting after 1 or 2 seconds. I tried going into the settings to disable auto connecting to a network but even if I disable it, the issue just starts again. On a side note, I tried AOSP 12 but it was really laggy. My device is specifically VTR-L29. 

I appreciate all your help

**Comment by LorainLacosta** [comment]
I also have p10 vtr l29 I'm currently using A12 but it so lag the UI and scrolling are sluggish. But I found temporary fix for this. By slightly increase the frequency of Gpu.

**Comment by kelvinyankey6** [comment]
Hey. Yeah it seems doing this does make things a bit smoother. I also used this app called Lspeed which made things way better. Seemed to make things better. I'm on A12 now because making calls on a cellphone is like the whole point of it lol. Did you manage to get Magisk installed? I'm new to all of this so forgive by noobness

**Comment by LorainLacosta** [comment]
I'm also quite noob and new here

Yeah I managed to install Magisk on my. I also manage to pass safety net in magisk it works great.

I recommend Franco kernel manger
For increasing the GPU.
I'm did put some on tweaks to improve my from lag but I forgot where did I get those tweaks.
Il find it later

**Comment by LorainLacosta** [comment]
Have try set up prop
debug.sf.luma_sampling=0. and persist.traced.enable=0. I tried it did actually work without overclocking my GPU. After I quite lower my phone
CPU frequency to extend my battery

**Comment by kelvinyankey6** [comment]
Yeah. I saw the instructions and did them but the manager is still not detecting Magisk. Generally, why is it that you have to fight with Huawei phones to get something done?

**Comment by kelvinyankey6** [comment]
@LorainLacosta By any chance do you have backups of the stock rom or know where I can get EMUI 9 from? Firmware Finder seems to not be working
