### ISSUE TITLE
letters superimposed on notification icons [LG K41s/K51s]

### ISSUE THREAD

**Issue by Laikayupi** [phhusson/treble_experimentations#2211]
it's not a big problem but that's all it takes for the gsi to be perfect
installing gsi from android 10 everything works, however, the notifications are buggy with the letters on top of the icons

already installing from android 9 the notifications are normal, however, bugs appear such as audio, wifi and lack of digital sensor

this bug happens with both models, K41s and K51s
![Screenshot_20220225-145548_(1)](https://user-images.githubusercontent.com/83295552/155774400-76f84c79-ddc8-432c-bfc9-cf656ecf57b6.png)
![Screenshot_20220225-145539_(1)](https://user-images.githubusercontent.com/83295552/155774406-99ceca3f-3b36-4401-ab04-a9d52d8586c4.png)
![Screenshot_20220225-145525_(1)](https://user-images.githubusercontent.com/83295552/155774409-5a50d181-525d-4c02-9abd-79241215d50e.png)

**Comment by Laikayupi** [comment]
the problem was solved by creating an overlay, now it's perfect

**Comment by phhusson** [comment]
The overlay has been merged in vendor/hardware_overlay?

**Comment by Laikayupi** [comment]
yep, has been replaced by the new one in vendor/overlay

**Comment by phhusson** [comment]
There is a new stock rom that fixes this issue?

**Comment by Laikayupi** [comment]
if it depends on lg it would never solve it, it's an overlay created from your overlay creation tutorial

**Comment by phhusson** [comment]
But I see no overlay for LG K41s in https://github.com/phhusson/vendor_hardware_overlay/tree/pie/LG ?

**Comment by Laikayupi** [comment]
my friend is going to create a pull request, he created the overlays

**Comment by Laikayupi** [comment]
my friend is going to create a pull request, he created the overlays
