### ISSUE TITLE
Xiaomi MI A2 - Camera issue AOSP 12.0 v402

### ISSUE THREAD

**Issue by istiak101** [phhusson/treble_experimentations#2213]
Device: Xiaomi Mi A2
GSI: https://github.com/phhusson/treble_experimentations/releases/tag/v402

After installing the GSI there was no camera app showing. And the flashlight was locked showing camera is running. No other app was able to access the camera.

**Comment by istiak101** [comment]
Solution: Go to Settings > Phh Treble Settings > Misc features > Camera > Force Enable Camera2API HAL3

Tick this and restart your phone.

**Comment by Aj-style** [comment]
@istiak101 is cam 
2api enabler required to flash  ?
Which gsi you flashed ? Like arm64 ab vndklite or just arm 64 ab?

**Comment by istiak101** [comment]
> @istiak101 is cam 2api enabler required to flash ? Which gsi you flashed ? Like arm64 ab vndklite or just arm 64 ab?

@Aj-style no I didn't need to flash cam2api enabler. I flashed ARM64 ab(both vanilla & gapps) but didn't try vndklite.

**Comment by istiak101** [comment]
I flashed both arm64 ab vndklite and arm 64 ab. After enabling Camera2API HAL3 this fixes my camera.
