### ISSUE TITLE
Battery status in AOSP 4.x

### ISSUE THREAD

**Issue by abdullah5490** [phhusson/treble_experimentations#2220]
I'm a big fan and potential user of AOSP GSI. I've scene my phone (infinix note7) in the devices list under wicky. But I faced huge battery drain on every AOSP 3.xx based GSI before even the overlay is present.
Thought to ask if there is any vendor code change in AOSP 4 series, which could fix such battery problems on some devices? I'm hoping to try again with the latest releases of android12 if there is something for me.
Thanks and looking forward towards reply.

**Comment by phhusson** [comment]
Nope, there hasn't been any noticeable battery fix.
If you want it to get fixed, you'll need to reproduce the issue, provide
logs, and more infos.

Le jeu. 10 mars 2022 à 12:52, abdullah5490 ***@***.***> a
écrit :

**Comment by abdullah5490** [comment]
I already shared logs multiple times in past but they said nothing about cause of battery drain according to your reply. but still, battery is quite terible on my mediatek device.
look at the issue no. 1905 and 1927 etc.


Sent from my iPhone

**Comment by phhusson** [comment]
Looking at 1905, you have 2 days of usage, looks pretty standard to me?

**Comment by phhusson** [comment]
And seriously, don't open new tickets

**Comment by phhusson** [comment]
Your latest comment in 1927 says "I'll investigate"
so what have you got?

**Comment by abdullah5490** [comment]
Look at my original issue, there were few replies from u and then you went away and issue is still as it is. https://github.com/phhusson/treble_experimentations/issues/1991
> Your latest comment in 1927 says "I'll investigate"
> 
> so what have you got?
