### ISSUE TITLE
Please add this RMX2195 patch by Eremitein

### ISSUE THREAD

**Issue by Zumamudin17** [phhusson/treble_experimentations#2229]
Please add this fix for RMX2195 fingerprint bug. It works, so  I hope you add this on your GSI 

https://gitlab.com/eremitein/treble-patches/-/blob/caosr/patches/personal/device_phh_treble/0058-try-to-add-support-for-RMX2195.patch

**Comment by phhusson** [comment]
Why is this not a pull-request...?

Anyway I'm a nice mood, so I picked it in https://github.com/phhusson/device_phh_treble/commit/d192015aaf8fbcca5fdf1199d813a81c8e11255a

**Comment by Zumamudin17** [comment]
> Why is this not a pull-request...?
> 
> Anyway I'm a nice mood, so I picked it in [phhusson/device_phh_treble@d192015](https://github.com/phhusson/device_phh_treble/commit/d192015aaf8fbcca5fdf1199d813a81c8e11255a)

**Comment by Zumamudin17** [comment]
Sorry sir. I am really new on GitHub usage so I don't understand how to use pull-request menu correctly. Thank you 🙏 😅
