### ISSUE TITLE
ADB USB debugging not working

### ISSUE THREAD

**Issue by pvagner** [phhusson/treble_experimentations#2235]
I've flashed [system-squeak-arm64-ab-vndklite-floss-secure](https://github.com/phhusson/treble_experimentations/releases/download/v402/system-squeak-arm64-ab-vndklite-floss-secure.img.xz) of v402 android 12. It appears to work fine on my device 3GB variant of Xiaomi redmi 9 codename galahad except of one thing. I am unable to get ADB over USB to work.
When I connect device to computer using USB cable the charging notification sound plays. I change to any of USB modes via the notification tile e.g. to file transfer, PTP, USB tethering, midi. As soon as I change the mode I can see USB device connecting in the dmesg output on my computer. When the USB is connected I am going to Settings -> System -> Developer options and turn on USB debugging. As soon as I enable USB debugging, I can see USB device disconnecting when looking at the dmesg output of my computer. No matter which USB mode I am choosing on the phone it's always like this.
Have you got any clue for me please?

**Comment by CarlosCMD** [comment]
I also have the same issue, have you found a solution yet?

**Comment by pvagner** [comment]
Since that time I have flashed an updated version and it's now working fine. I have no special fix just used an updated build.
