### ISSUE TITLE
[AOSP v411] Can't boot due to broken permissions (?)

### ISSUE THREAD

**Issue by UDPSendToFailed** [phhusson/treble_experimentations#2244]
I'm trying to port my SM-T590 (SDM450) to arm64 vendor, with Android 11-based ROMs it works almost perfectly. However with Android 12, every ROM including Phh AOSP has tons of errors in logcat referring to permission issues (I think?). 

I have set SELinux to permissive, but it didn't really help, logcat gets spammed with `Operation not permitted` and `No such file or directory`. The 64-bit vendor libs are from Galaxy A20s, I didn't commit any other changes besides copying lib64 folder to the vendor partition and adding arm64 ABIs to build.prop and default.prop.

Attached logs from AOSP v411. Thanks for the help!

[logcat.txt](https://github.com/phhusson/treble_experimentations/files/8365847/logcat.txt)
[last_kmsg.txt](https://github.com/phhusson/treble_experimentations/files/8365950/last_kmsg.txt)

**Comment by phhusson** [comment]
well does it work with original vendor?

Le lun. 28 mars 2022 à 22:03, UDPSendToFailed ***@***.***> a
écrit :

**Comment by UDPSendToFailed** [comment]
This device is arm32_binder64, so running on stock vendor makes it impossible to boot arm64 systems. 
Using the custom vendor, arm64 Android 11 ROMs are working fine, but Android 12+ has the issue mentioned before. 
The reason why I want to fix Android 12+ is simple, running on arm64 gives a huge CPU performance boost at almost doubled multi-core scores, and that's a lot on these low-spec hardwares like the Snapdragon 450.
I don't expect a fix specifically for this device, just asking for some guidance on how to start debugging this issue.

**Comment by phhusson** [comment]
Ok, so I'll take your answer as "yes, everything works fine with original
vendor, only my own vendor is broken"

Le mar. 29 mars 2022 à 01:12, UDPSendToFailed ***@***.***> a
écrit :

**Comment by UDPSendToFailed** [comment]
With arm32_binder64 version of Android 12 yes it works, except the camera due to the lack of HAL3 support, and 2 of 4 speakers as mentioned in #953.
