### ISSUE TITLE
Installation failed on Dynamic System Update

### ISSUE THREAD

**Issue by ESD444** [phhusson/treble_experimentations#2245]
I'm using a Realme C15 Qualcomm Edition RMX2195 and I'm an avid follower of project treble. I used to be able to load Android 12 dsu gsi but today when I try to load it just says installation failed. I actually would have stuck to using the Android 12 treble project gsi if not for the problem off being unable to hear calls comin in or going out. I hope this problem would be quickly solved because I would more than love to flash my device and run the gsi for daily use.

**Comment by phhusson** [comment]
DSU is 100% OEM-dependant and there are more reasons for DSU to be broken, that there are reasons for DSU to work.

Hence, I will not give any help on DSU.

**Comment by ESD444** [comment]
I'm willing to flash your gsi to become my daily use on my device but I
need to be able to receive and make calls which what's the problem the last
time I flashed. If that is solved, I wouldn't mind flashing even right now.

EDMUND SONG

**Comment by phhusson** [comment]
Honestly I have no idea what your issue is. I'm not aware of a single Realme device with no voice in calls. Well except yours that is
