### ISSUE TITLE
[Xiaomi Mi A2] No auto-backlight

### ISSUE THREAD

**Issue by phhusson** [phhusson/treble_experimentations#226]
Attached framework-res/overlay courtesy of @byblady
[files.zip](https://github.com/phhusson/treble_experimentations/files/2434899/files.zip)

**Comment by schweppi** [comment]
Are you sure files are also working for a2 **lite** (different hardware)?
I uploaded files from my a2 lite - stock rom - september update.
At least framework-res.apk seems different to the one uploaded by byblady
[overlay_a2_lite.zip](https://github.com/phhusson/treble_experimentations/files/2436964/overlay_a2_lite.zip)

**Comment by phhusson** [comment]
Fair enough

**Comment by linuxct** [comment]
Adding @p4block
