### ISSUE TITLE
moto g play 2021 touch screen stopped working

### ISSUE THREAD

**Issue by artizzle** [phhusson/treble_experimentations#2264]
After a successful flash of the floss version to my moto g play 2021 the touch screen stopped working. I even tried the gapps version which again flashes fine but the touch screen doesn't work. I flashed Magisk before this. Any help would be greatly appreciated. Here is a more detailed version of what I did: https://forum.xda-developers.com/t/after-magisk-and-successful-flash-the-touch-screen-stopped-working.4427703/

thanks!

**Comment by franciskafieh** [comment]
User solved the issue on XDA... this issue can be closed... for people searching up how to fix this, here it is...

you have to run these commands before flashing your system.img:
```shell
fastboot delete-logical-partition system_a
fastboot delete-logical-partition system_b

fastboot create-logical-partition system_a 100000
fastboot create-logical-partition system_b 100000
```

**Comment by franciskafieh** [comment]
@phhusson please close :)
