### ISSUE TITLE
#Bugs in v412

### ISSUE THREAD

**Issue by fob014** [phhusson/treble_experimentations#2267]
#1 no support for volte
#2 4g voice calling not working (( even after installation  IMS app))
#3 Fingerprint when I open set Fingerprint in security settings than whole setting app stop working and I automatically back to home  

Meanwhile rom is  very good I like it much please fix this issue

**Comment by phhusson** [comment]
1. that's three issues
2. it's lacking the minimum expected informations from an issue

**Comment by fob014** [comment]
> 1. that's three issues
> 2. it's lacking the minimum expected informations from an issue

Device Moto g9 Sd662 Android 11 stock
Rom gsi i install   ( system-squeak-arm64-ab-vndklite-gapps-secure.img.xz )
