### ISSUE TITLE
[Xiaomi A2 Lite]: Fingerprint sensor is not working

### ISSUE THREAD

**Issue by schweppi** [phhusson/treble_experimentations#227]
Fingerprint sensor is not working for Xiaomi A2 Lite 4/64.
Slider for volume appears if I press the sensor
Rom version 1.05

**Comment by phhusson** [comment]
Please be more specific:
Do you see fingerprint option in Security Settings?
Can you register a finger?
What happens when you try to authenticate from keyguard? Does it show any error or anything?
Also please provide log at the step where it is failing

**Comment by schweppi** [comment]
> Please be more specific:
> Do you see fingerprint option in Security Settings?
**Yes**
> Can you register a finger?
**No, if i try to register a finger the volume slider appears instead of scanning finger, see 
![register_finger](https://user-images.githubusercontent.com/43758776/46306446-989cd400-c5b4-11e8-8149-4fde754b9f08.png)
> What happens when you try to authenticate from keyguard? Does it show any error or anything?
**Authenticate by pin works, no error**
> Also please provide log at the step where it is failing
What kind of log? How to create/provide it?  Sorry i'm new in this

**Comment by schweppi** [comment]
Some more hints:
- Oreo v23: it's working
- Oroe v25: it's not working
But, if I flash v23, scan a fingerprint and then flash v25 or v125 without wipe data it keeps working in v25 and v125!

**Comment by darweshsinghcgi** [comment]
@schweppi Works for me in both Pie v106 and Oreo v26 on Mi A2 Lite

**Comment by mesilliac** [comment]
The fingerprint sensor on my A2 lite appears to be working (android-9.0 arm64-ab-vanilla-nosu built from source), however long-pressing it is sending a "back" event to apps, which makes the phone pretty annoying to use as it's right where the finger sits when holding the phone.

I checked `adb logcat` and the offending event seems to be this:
```
10-20 20:28:05.650  1073  1281 D fpc_fingerprint_hal: report_input_event - Reporting event type: 1, code: 305, value:1
10-20 20:28:05.651  1073  1281 D fpc_fingerprint_hal: report_input_event - Reporting event type: 1, code: 305, value:0
```

Registering a fingerprint and using it to unlock the phone both seem to work fine for me, however.

I noticed that it's also sending swipe events with codes 195, 196, 197, 198 for left, right, up, down respectively, but these don't seem to be affecting anything.

There's also some sort of unidentified event with a short tap on the sensor...
```
10-20 21:33:48.207  1073  1281 E fpc_fingerprint_hal: report_input_event - Unrecognized trigger_event: 1, trigger_event_type: 65536
10-20 21:33:48.207  1073  1281 E fpc_fingerprint_hal: report_input_event - Unrecognized trigger_event: 1, trigger_event_type: 65536
```
not sure what this is about.

I'm not sure what to do with this information, but can provide more / test changes if needed.

**Comment by mesilliac** [comment]
I just confirmed that this phone needs a similar fix to other Xiaomi devices. A similar fix to https://github.com/phhusson/device_phh_treble/pull/50 worked for me by adding "xiaomi/daisy" to the list

**Comment by schweppi** [comment]
Fingerprint sensor is working for my daisy in v107

**Comment by ibnnrhds** [comment]
Can you help me to fix?
android.hardware.biometrics.fingerprint@2.1-service(1005): onError(5)

**Comment by phhusson** [comment]
I think that nowadays it's fixed.
If it isn't, please reopen this issue.
