### ISSUE TITLE
April image showing patch level February

### ISSUE THREAD

**Issue by istiak101** [phhusson/treble_experimentations#2277]
Build number: treble_arm64_bgS-userdebug 12 SP2A.220405.004 220405 test-keys

Updater showing:
Android version: 12
GSI variant: treble_arm64_bgS-secure
Security patch: February 1, 2022

Also why can't I update through OTA? I am getting error your device does not support OTA updates! My device is Xiaomi MI A2. I have to flash every updates manually. Given your effort I guess that's not a big deal for me at this moment.

Thanks for your awesome work.

**Comment by phhusson** [comment]
>  April image showing patch level February #2277 

You're using the "secure" variant, which lies to apps, to make it look like you're running stock rom. This includes security patch level, it says to apps (including system apps) that it is running stock rom's security patch level.

> Also why can't I update through OTA? I am getting error your device does not support OTA updates! My device is Xiaomi MI A2. I have to flash every updates manually.

Yes your device is not supported for OTA (the requirement is to have dynamic partitions), and there is no short-term plan to support it.

**Comment by istiak101** [comment]
Ah I see. Thank you.
