### ISSUE TITLE
[Xiaomi A2 Lite]: Menu adaptive brightness is not shown

### ISSUE THREAD

**Issue by schweppi** [phhusson/treble_experimentations#229]
Menu adaptive brightness is not shown. Manully controlling of brightness via slider is working.
Affected:
- Oreo - v25 (works in stock oreo Rom - September Patch)
- Pie - v105

**Comment by phhusson** [comment]
Duplicate of #226

**Comment by mesilliac** [comment]
I can confirm this is fixed by https://github.com/phhusson/vendor_hardware_overlay/pull/32
