### ISSUE TITLE
improve security

### ISSUE THREAD

**Issue by Michael8878** [phhusson/treble_experimentations#2305]
Enhance system security by making the system only shut down or restart after the user enters the device password.  this increases the security of the device.  if the device is stolen, the thief will not be able to turn off the device, thus enabling tracking.

Version used: AOSP 12.1 v413 system-squeak-arm64-ab-vndklite-gapps.img.xz

Phone used: Samsung Galaxy A70 (A705MN)

**Comment by phhusson** [comment]
Do long-press on volume down + power.
You'll notice that this triggers a hardware reset.
This hardware reset cannot be disabled.

So thieves can reboot your device just fine even if rebooting requires lockscreen.

**Comment by Michael8878** [comment]
> Do long-press on volume down + power. You'll notice that this triggers a hardware reset. This hardware reset cannot be disabled.
> 
> So thieves can reboot your device just fine even if rebooting requires lockscreen.

Yes, but it can prevent a theft.  and after pressing this set of keys, the device will restart and not turn off, that is, the system will be operational again.

**Comment by phhusson** [comment]
Unless the thief do the combo to boot into recovery or download mode...

**Comment by Michael8878** [comment]
> Unless the thief do the combo to boot into recovery or download mode...

I don't know if it's on all devices, but mine only boots into recovery or download mode, after connecting it to some computer.  if you don't connect it to some computer, recovery mode doesn't start, and neither does the download

**Comment by phhusson** [comment]
Or... you connect it to another smartphone using usb-c <=> usb-c cable. Once thieves know about it, they'll do it systematically and that won't prevent any theft.

**Comment by Michael8878** [comment]
> Or... you connect it to another smartphone using usb-c <=> usb-c cable. Once thieves know about it, they'll do it systematically and that won't prevent any theft.

but not just anyone knows how to do that.  is also adding this option to turn off only after entering the password, it can prevent or make it difficult for a person to reset the device

**Comment by Michael8878** [comment]
> Or... you connect it to another smartphone using usb-c <=> usb-c cable. Once thieves know about it, they'll do it systematically and that won't prevent any theft.

can AVOID or make it difficult for a person to be able to reset to device.
