### ISSUE TITLE
[Razer Phone][pie] Front camera not working

### ISSUE THREAD

**Issue by linuxct** [phhusson/treble_experimentations#231]
The behaviour has changed between 104 and 105.  
In 105, AOSP Camera works, whilst in 104, no Vendor camera would. In 104, flipping to front camera was possible as an action (a 4th camera was listed in the device), but it'd show the back camera in a 180º rotated angle. 

![screenshot_20180821-005234](https://user-images.githubusercontent.com/3966313/46341714-39cd6e00-c639-11e8-9057-56bf8a60abca.png)
![screenshot_20180821-005238](https://user-images.githubusercontent.com/3966313/46341719-3c2fc800-c639-11e8-9b75-68f7a87cbf81.png)

In version 105, changing to the front camera isn't present as an action anymore and can't be toggled to. The 4th camera wasn't listed anymore. 

![screenshot_20181002-115116](https://user-images.githubusercontent.com/3966313/46342154-55854400-c63a-11e8-9932-20091f2fd65f.png)
![screenshot_20181002-115125](https://user-images.githubusercontent.com/3966313/46342156-574f0780-c63a-11e8-87ed-6f30027d91f8.png)

Common in both versions, whenever trying to record a video, the video gets zoomed in (uses the secondary camera?) and turns on EIS. A screen record can be provided.

**Comment by linuxct** [comment]
Solved since v108.

**Comment by DroidAlexandra** [comment]
Activating EIS would naturally zoom the video in, that's the nature of how EIS works, it uses the center of the sensor to allow it "wiggle" or stabilisation movement by moving the recording area around the sensor, the same way OIS would move the entire sensor assembly.

@phhusson any hints on the commit that fixed this? Or was the fix a side effect of doing something else? (as this fix was never mentioned in the v108 changelog)

**Comment by phhusson** [comment]
Well, v108 updated from android pie-release to pie-qr1-release (which I personly call Android 9.1).
That's basically the branch used for Pixel 3.
AOSP had many framework changes in this switch, that's most likely something there.
(and v110 is on pie-qr2-release with even more changes... i'm guessing many things will be broken now /o\)

**Comment by DroidAlexandra** [comment]
Ah okay, so it was fixed (intentionally or not) AOSP side, Thanks
Will email you some stuff not to go off topic here.
