### ISSUE TITLE
Adding Bromite to /system/framework/framework-res.apk

### ISSUE THREAD

**Issue by scotthep** [phhusson/treble_experimentations#2312]
In regards to https://github.com/bromite/bromite/wiki/Installing-SystemWebView, I am interested in being able to use Bromite and Bromite's systemwebview on a GSI.  Could you either add this option as an example of applying a patch in your build instructions or consider adding it to your code base.  I realize that ungoogled-chromium-android is also a possibility but, at this time it is not as current or popular.  Vandium will only run on GrapheneOS unless some of the patches are removed.

Thanks for providing Treble_experimentations

**Comment by phhusson** [comment]
FLOSS variant already ships with Bromite, it already has this modification.
Even non-floss variant have the overlay to accept bromite webviews (assuming it is in /system)
