### ISSUE TITLE
Build instructions on including custom apps

### ISSUE THREAD

**Issue by scotthep** [phhusson/treble_experimentations#2313]
With the exception of Vandium and talkback, the remaining apps in GrapheneOS are upstream binaries:
https://grapheneos.org/source#standalone-apps

I was interested in something similar for a GSI but substituting Bromite for Vandium (Vandium is said not to work outside of GrapheneOS).  I think this would be a popular download for individuals who do not own Pixel devices but are interested in security/privacy.

Either instructions on adding apps to builds or providing them outright would be appreciated.

Thanks

**Comment by phhusson** [comment]
I think looking at https://github.com/phhusson/vendor_foss will help you seeing how to include apps in the build

**Comment by scotthep** [comment]
Great.  I based my suggestion on the Wiki which still shows Lightning as the Browser.

FLOSS versions include the following open source alternatives to GAPPS:

    [phh's Superuser](https://f-droid.org/en/packages/me.phh.superuser/)
    [NewPipe](https://f-droid.org/en/packages/org.schabi.newpipe/)
    [Silence](https://f-droid.org/en/packages/org.smssecure.smssecure/)
    [OsmAnd~](https://f-droid.org/en/packages/net.osmand.plus/)
    [Lightning](https://f-droid.org/en/packages/acr.browser.lightning/)
    [Etar](https://f-droid.org/en/packages/ws.xsoh.etar/)
    [Transportr](https://f-droid.org/en/packages/de.grobox.liberario/)
    [MuPDF viewer](https://f-droid.org/en/packages/com.artifex.mupdf.viewer.app/)
    [AnySoftKeyboard](https://f-droid.org/en/packages/com.menny.android.anysoftkeyboard/)
    [Yalp Store](https://f-droid.org/en/packages/com.github.yeriomin.yalpstore/)
    [K-9 Mail](https://f-droid.org/en/packages/com.fsck.k9/)
    [Riot.im](https://f-droid.org/en/packages/im.vector.alpha/)
    [DAVdroid](https://f-droid.org/en/packages/at.bitfire.davdroid/)
    [Nextcloud](https://f-droid.org/en/packages/com.nextcloud.client/)
    [F-Droid](https://f-droid.org/en/packages/org.fdroid.fdroid/)
