### ISSUE TITLE
[Razer phone] Bluetooth headset in-call audio not working

### ISSUE THREAD

**Issue by linuxct** [phhusson/treble_experimentations#232]
Could be extended to some other devices too.  
Audio routing in msm8996/cheryl is not working properly. Whenever a Bluetooth headset is connected, audio gets re-routed to the phone's earpiece.  

Reading logs, they seem extremely normal for the matter. Kindly have a look.  

[cheryl-bt-incall.log](https://github.com/phhusson/treble_experimentations/files/2437414/cheryl-bt-incall.log)

**Comment by phhusson** [comment]
AFAIK that's for all CAF devices
The issue is most probably that my QtiAudio implementation is partial, and need to plug additional callbacks.
Can you test back your old QtiTelephonyService method you had on Oreo to confirm?

**Comment by shafr** [comment]
Same for Xiaomi Kate. 
I've noticed though that if you connect bluetooth headphones after call had started - then audio get's routed to headphones.

**Comment by rbuehlma** [comment]
I suspect that
https://github.com/phhusson/treble_experimentations/issues/248 and https://github.com/phhusson/treble_experimentations/issues/291
are related to this issue. Therefore, Xiaomi Mi Mix 2S seems to be affected as well.
