### ISSUE TITLE
adb over (Wi-Fi) network fails

### ISSUE THREAD

**Issue by ildar** [phhusson/treble_experimentations#2324]
### Current Behavior:
when ADB debug over Wi-Fi is turned on, I can't connect to the device.

### To Reproduce
1. In Developer Options turn ON the `ADB debug over Wi-Fi`
2. on a PC: `adb connect 10.1.85.75:45103`

### Expected behavior
Expect adb to connect to the device
But I get
> failed to connect to '10.1.85.75:45103': Connection timed out

### Smartphone (please complete the following information):
 - Device: Doogee S59 pro
 - Build Flavor: system-squeak-arm64-ab-vndklite-floss.img.xz
 - Version AOSP 12.1 v413

**Comment by phhusson** [comment]
![2022-05-18_10-10](https://user-images.githubusercontent.com/3642/168990467-5c9bfc85-d029-4008-9131-ce654b84f222.png)

**Comment by ildar** [comment]
ok, thanks. For the ref, the right subcommand is:
> # adb pair
> adb: usage: adb pair <host>[:<port>]
