### ISSUE TITLE
Occasionally no audio in calls on both ends and no ringtone on outgoing calls

### ISSUE THREAD

**Issue by fritz-k** [phhusson/treble_experimentations#2329]
### Describe the bug
Initially calls work perfectly fine. After some time all neither me nor the partner hear any sounds in a call (doesn't matter whether I'm calling or being called) and I don't hear the "ringing" beep when calling someone. Toggling "Qualcomm features/Use alternate audio policy" (the bug happens with both this setting on or off, so it doesn't depend on the state of this setting) or restarting the phone returns the phone into the "working state" with audio working for all calls as expected. Toggling flight mode doesn't help.

### Settings that didn't help (for long)
- "Qualcomm features/Use alternate audio policy"
- "Misc features/Automatically restart RIL"
- "IMS features"
  - "Install IMS APK for Qualcomm vendor"
  - "Request IMS network"
  - "Create IMS APN"
- VoLTE/VoWifi
- Loudspeaker

### Things I didn't test
- Headphones/external speakers
- Vendor hardware overlay

### Smartphone (please complete the following information):
 - Device: Sony Xperia 5 III (pdx-214)
 - Build Flavor: lineage-19.1-20220510-UNOFFICIAL-arm64_bgS-vndklite
 - Version: v413

### Additional context
Call w. audio:
I initiated the call shortly after a restart around. 16:17:38, answered the other phone around 16:17:52 and ended it around 16:18:05.
[call_working_after_restart.log.gz](https://github.com/phhusson/treble_experimentations/files/8741259/call_working_after_restart.log.gz)

Call w/o. audio (~2h later):
I started the call a couple of seconds before 19:19 (no beep), answered the other phone around 19:19:03 (no audio) and ended it around 19:19:20.
[call_no_audio.log.gz](https://github.com/phhusson/treble_experimentations/files/8742347/call_no_audio.log.gz)

Call w. audio (after toggling "Qualcomm features/Use alternate audio policy"):
I toggled "AAP" around 19:20:03, started the call around 19:20:15 (beep audible), answered the other phone around 19:20:28 (audio on both ends) and hung up around 19:20:39.
[call_audio_after_aap_toggle.log.gz](https://github.com/phhusson/treble_experimentations/files/8742348/call_audio_after_aap_toggle.log.gz)

Do you see anything in the logs or have an idea, what might be going on?

Edit: I have both SIM slots in use, if one SIM doesn't have audio in calls, the other one doesn't have either.

**Comment by phhusson** [comment]
This is a known issue. To confirm, you can just go int Treble settings - no need to select anything - to solve the issue.
This is fixed in next release, until then, you can try manually installing updated treble app https://github.com/phhusson/vendor_hardware_overlay/blob/pie/TrebleApp/app.apk

**Comment by JonnyTech** [comment]
@phhusson this is the number one issue that I would like to see fixed in your AOSP 11 (closely followed by the bromite webview name change). I know that you do not want to release an updated v3xx but is there any way to backport this fix?

**Comment by fritz-k** [comment]
Updated TrebleApp seems to have fixed the issue. Thanks for the quick response and fix :)

**Comment by zqhix** [comment]
> This is a known issue. To confirm, you can just go int Treble settings - no need to select anything - to solve the issue. This is fixed in next release, until then, you can try manually installing updated treble app https://github.com/phhusson/vendor_hardware_overlay/blob/pie/TrebleApp/app.apk

After manually installing updated Treble app my IMS features crushes and I think now I absolutely can't hear audio in calls

**Comment by fritz-k** [comment]
> P.S: maybe I'm doing something wrong? What you mean by manually installing?

I  just downloaded the updated apk to the smartphone and installed it (from the file manager I think). After that, all calls had audio working properly.

**Comment by zqhix** [comment]
> > P.S: maybe I'm doing something wrong? What you mean by manually installing?
> 
> I just downloaded the updated apk to the smartphone and installed it (from the file manager I think). After that, all calls had audio working properly.

i think now it works, thanks for reply
