### ISSUE TITLE
[off topic] CAT S22 T9 does not function, instead has popup keyboard

### ISSUE THREAD

**Issue by jesse-osiecki** [phhusson/treble_experimentations#2340]
### Current Behavior:
The numberpad on the CAT S22 functions as only a numberpad. Typing must be done on the touch screen above.

### Expected behavior
It would be nice to have the T9 work below, maybe with suggestions of words above *without* the popup keyboard, maybe with a toggle.

### Smartphone (please complete the following information):
 - Device: [CAT S22]
 - Build Flavor: [system-squeak-arm32_binder64-ab-vanilla.img.xz]
 - Version [V413]

**Comment by evantj** [comment]
https://github.com/sspanak/tt9 does this
