### ISSUE TITLE
Help me！About how remove Root/SU and disable it forever from AOSP 10/11

### ISSUE THREAD

**Issue by han4976** [phhusson/treble_experimentations#2344]
Hello, now I have installed AOSP 11, When I try to remove root from PHH treble settings, the system prompts that a reboot is required.

However, after the system was successfully started, I found that the supersu/root was not successfully removed.

I tried three times, but failed. Cannot remove supersu/root.

How do it？

Help me please.

Thank you.

**Comment by JonnyTech** [comment]
See my comment about removing the files in your other thread
