### ISSUE TITLE
No sound during voice calls.

### ISSUE THREAD

**Issue by 2SHANINGITHUB** [phhusson/treble_experimentations#2347]
### Current Behavior:
When I make voice calls, whether through the top speaker, bottom speaker or Bluetooth headset, I can't hear other people's voices, I've tried many different GSIs and this problem is widespread, My hardwares they are working fine.I also tried many dialers app, the problem is still not solved.

### Describe the bug
Things are very simple,Just no sound during voice calls.

### To Reproduce
1. Go to the dialer app.
2. Dial any number you want.
3. When the call is connected,you will see the error.

### Smartphone:
 - Device: [[Redmi K50Pro](https://www.gsmarena.com/xiaomi_redmi_k50_pro-11372.php)]
 - Build Flavor: [[crDroid-8.5-arm64_bgN-vndklite-Unofficial](https://sourceforge.net/projects/gsi-projects/files/v413/crDroid-8.5/crDroid-8.5-arm64_bgN-vndklite-Unofficial.img.xz/download)]
 - Version [V8.5/Android12]

### Additional context
Redmi k50pro's CPU is MediaTek Dimensity 9000, I guess maybe the CPU is causing the problem, I upload a log file catched by matlog.Hope you guys can find out from the log file.
[calllog.txt](https://github.com/phhusson/treble_experimentations/files/8821468/calllog.txt)

**Comment by 2SHANINGITHUB** [comment]
After restoring the official Xiaomi MIUI system and brushing into GSI again, the problem was solved, although the cause of this problem is unknown, but you can try the above operation if you encounter such problems.

**Comment by wbs306** [comment]
Which miui version have you restore？I have the same problem now

**Comment by 2SHANINGITHUB** [comment]
> Which miui version have you restore？I have the same problem now

稳定版线刷包V13.0.4.0.SLKCNXM，你可以在这里https://xiaomirom.com/rom/redmi-k50-pro-matisse-china-fastboot-recovery-rom/#%E4%B8%8B%E8%BD%BD-%E7%BA%A2%E7%B1%B3-k50-pro-%E7%A8%B3%E5%AE%9A%E7%89%88-fastboot-%E7%BA%BF%E5%88%B7%E5%8C%85下载

**Comment by wbs306** [comment]
好的，感谢

**Comment by 2SHANINGITHUB** [comment]
> @2SHANINGITHUB 你是移动联通还是电信？

我三个运营商都在用，这个问题和运营商无关，可能是刷机清除原系统的时候出现某些错误把手机一些硬件驱动也给清除了，所以每次刷GSI之前最好先刷一下官方的包，还有目前我用CRDROID的GSI会出现电信卡没有信号的问题，不知道别的包怎么样

**Comment by Star-ZER0** [comment]
same problem on HUAWEI P10 (VTR-AL00C00) on Pie (EMUI 9.0.1.179) Vendor

**Comment by Linux-Knife** [comment]
该方法在我的K50上仍然不起作用，无论更换什么底包，什么gsi（pe，pep，crdroid，lingageos）均无法修复通话问题，可以接听电话但听不到任何声音，有大佬有解决办法吗
