### ISSUE TITLE
[Huawei] Regression: Fingerprint gestures are no longer mapped

### ISSUE THREAD

**Issue by phhusson** [phhusson/treble_experimentations#235]
Regression when going from v105 to v106

**Comment by phhusson** [comment]
Fixed with https://github.com/phhusson/device_phh_treble/commit/5b04034d908a03c05af35c572db0f285a099a6b5

**Comment by LuqJensen** [comment]
I shouldve looked at the issues i see. I posted about this in your PIE treble post on [XDA](https://forum.xda-developers.com/showpost.php?p=77919723&postcount=943)
I copied the entire contents of [this folder](https://github.com/phhusson/vendor_hardware_overlay/tree/master/Huawei/Fingerprint)
So i can confirm that it was broken and it should be fixed again with this.

**Comment by Dil3mm4** [comment]
Validated, working.
