### ISSUE TITLE
Help! When using the integrated dialer, you might not hear any audio on the phone. 

### ISSUE THREAD

**Issue by han4976** [phhusson/treble_experimentations#2355]
Android 10/12/13 GSI binaries have the following GSI-specific known issues:

Phone Audio: When using the integrated dialer, you might not hear any audio on the phone. This is due to a change in the telephony service installation location in Android 10.

So, who man can be give me some one help, now how can I do anything to fixed it？

**Comment by phhusson** [comment]
I don't have any Android 13, you're probably in the wrong place.
