### ISSUE TITLE
<title>Bluetooth not working ,and can't call

### ISSUE THREAD

**Issue by AviderMin** [phhusson/treble_experimentations#2361]
### Smartphone (please complete the following information):
 - Device: [e.g. Pixel6]
 - Build Flavor: [e.g. system-squeak-arm64-ab-vndklite-gapps-secure.img.xz]
 - Version [e.g. V412]

### Additional context
 
andriod 12 ,base on emui 9 (base on andriod 9),and it can't call either,kirin 710F

**Comment by ivysrono** [comment]
may same as me #2362

**Comment by phhusson** [comment]
No device name, no gsi version, no precise description if what happen. Read the template.
