### ISSUE TITLE
xiaomi 6X wayne about goodix fingerprint

### ISSUE THREAD

**Issue by zh0uyawen** [phhusson/treble_experimentations#237]
use  the  gsi  of  aosp（pie），my fingerprint do not work ! my fingerprint is goodix .. can you fix it ?thanks！

**Comment by phhusson** [comment]
The commits you mention are simply about cleaning-up old fingerprints. This would only prevent some fingerprints to be registered, it wouldn't be a global "fingerprint doesn't work"

The files in /system/etc/firmware are likely culprit. Can you confirm it?

**Comment by suwakowww** [comment]
I saw these files in `/system/etc/firmware` (on stock rom and some custom roms for wayne).
But GSI don't.

Those files seems outdated, here's the newest files: https://github.com/TadiT7/xiaomi_wayne_dump/tree/wayne-user-9-PKQ1.180904.001-9.3.11-release-keys/system/etc/firmware

**Comment by phhusson** [comment]
This issue is getting old, and I think this device got a working pie vendor, so i'm closing it

Feel free to re-open it if it's still relevant.

**Comment by eremitein** [comment]
still have this bug
xiaomi mi a2 (same as xiaomi mi 6x)
vendor 9
even no fingerprint option in android settings :(
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/6310920/logcat.txt)

11-10 01:58:13.643     0     0 I init    : processing action (post-fs-data) from (/vendor/etc/init/android.hardware.      biometrics.fingerprint@2.1-service.rc:10)
11-10 01:58:13.645     0     0 I init    : Command 'copy /data/vendor/fpc/user.db /data/vendor_de/0/fpdata/user.db'       action=post-fs-data (/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc:13) took 0ms and failed:     Could not read input file '/data/vendor/fpc/user.db': open() failed: No such file or directory
11-10 01:58:13.646     0     0 I init    : Command 'rm /data/vendor/fpc/user.db' action=post-fs-data (/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc:15) took 0ms and failed: unlink() failed: No such file or directory

04-14 14:18:42.301  2230  3777 V FingerprintService: mDaemon was null, reconnect to fingerprint
04-14 14:18:42.307  2230  3777 V FingerprintService: Fingerprint HAL id: 0
04-14 14:18:42.307  2230  3777 W FingerprintService: Failed to open Fingerprint HAL!
04-14 14:18:42.307  2230  3777 I sysui_multi_action: [757,803,799,fingerprintd_openhal_error,802,1]
