### ISSUE TITLE
Samsung devices charging only with ''fast charging''

### ISSUE THREAD

**Issue by Michael8878** [phhusson/treble_experimentations#2388]
Happens on all Samsung devices

When I plug in the charger, it automatically recognizes it as ''Fast Charge''. on samsung devices, you have the option to choose the charging speed, being slow or fast charging. maybe add a choice option in the ''Phh treble settings''?

my device: Samsung Galaxy A70 (A705MN)

AOSP Version: AOSP 12.1 v414

**Comment by captaincookie200** [comment]
i own a galaxy A32 (SM-A325F) i plug it into my 15w fast charging that worked with ONE UI. it doesnt say anything about fast charging or any text indicating it is charging with fast charge at all.

**Comment by Michael8878** [comment]
> i own a galaxy A32 (SM-A325F) i plug it into my 15w fast charging that worked with ONE UI. it doesnt say anything about fast charging or any text indicating it is charging with fast charge at all.

The phone must support fast charging. and the option is in the battery settings
