### ISSUE TITLE
Overview button doesn't work

### ISSUE THREAD

**Issue by cenktaskin** [phhusson/treble_experimentations#2390]
### Current Behavior:
When I click on overview button nothing happens
  
### Describe the bug
Can't toggle the overview via square button on navigation bar. 

### To Reproduce
1. Click on square button on navigation bar

### Expected behavior
To see the overview to jump back to other recent apps

### Smartphone (please complete the following information):
 - Device: Cubot King Kong Mini 2
 - Build Flavor: system-squeak-arm32_binder64-ab-gogapps.img.xz
 - Version 414
 
Only thing I could find related to this in the repo was [this comment](https://github.com/phhusson/treble_experimentations/discussions/2358#discussioncomment-2973476)

**Comment by cenktaskin** [comment]
Switched to system-squeak-arm32_binder64-ab-vndklite-gogapps-secure.img.xz, still ongoing.

**Comment by YAJATapps** [comment]
I can confirm that recent apps button does not work on the following images with version 414:
system-squeak-arm32_binder64-ab-gogapps.img.xz
system-squeak-arm32_binder64-ab-vndklite-gogapps.img.xz

I think it may be related to the gapps version. I tried another version without gapps and it perfectly works:
system-squeak-arm32_binder64-ab-vanilla.img.xz

Device: Redmi 8a (olivelite)

I can provide logs if it can help.

**Comment by cenktaskin** [comment]
> I can confirm that recent apps button does not work on the following images with version 414: system-squeak-arm32_binder64-ab-gogapps.img.xz system-squeak-arm32_binder64-ab-vndklite-gogapps.img.xz
> 
> I think it may be related to the gapps version. I tried another version without gapps and it perfectly works: system-squeak-arm32_binder64-ab-vanilla.img.xz
> 
> Device: Redmi 8a (olivelite)

Can you install google apps to the vanilla version?

**Comment by YAJATapps** [comment]
> > I can confirm that recent apps button does not work on the following images with version 414: system-squeak-arm32_binder64-ab-gogapps.img.xz system-squeak-arm32_binder64-ab-vndklite-gogapps.img.xz
> > I think it may be related to the gapps version. I tried another version without gapps and it perfectly works: system-squeak-arm32_binder64-ab-vanilla.img.xz
> > Device: Redmi 8a (olivelite)
> 
> Apologies I'm new here: Can you install google apps to the vanilla version?

It can be if you find the right gapps package
