### ISSUE TITLE
Can't install google calendar

### ISSUE THREAD

**Issue by cenktaskin** [phhusson/treble_experimentations#2391]
Thanks for the great work. I just started using the image.

### Current Behavior:
Can't install google calendar from app store
  
### Describe the bug
Install fails via play store.

### To Reproduce
1. Go to Play Store
2. Try to install "Google Calendar"
3. See installation error

### Expected behavior
To be able to install the calendar app. As other google apps such as Pay etc. installed flawlessly.

### Smartphone (please complete the following information):
 - Device: Cubot King Kong Mini 2
 - Build Flavor: system-squeak-arm32_binder64-ab-gogapps.img.xz
 - Version 414

**Comment by cenktaskin** [comment]
Switched to system-squeak-arm32_binder64-ab-vndklite-gogapps-secure.img.xz and managed to install

**Comment by franciskafieh** [comment]
Sorry to bother, but do you happen to know if switching to the secure image was actually the thing that fixed it?

**Comment by franciskafieh** [comment]
argh... nvm... i guess google calendar can't run on root :( that sucks
