### ISSUE TITLE
Update from 11.0v13 to 12.1v414 breaks mobile data

### ISSUE THREAD

**Issue by AlleSchonWeg** [phhusson/treble_experimentations#2392]
### Current Behavior:
Mobile Data not working.
  
### Describe the bug
Hi,
i updated my Honor 9 to AOSP 12.1 v414, wipe data and cache. But after the update my mobile data connection (vodafone germany) is not working annymore. Somebody knows what the cause of this problem and how to fix it?

### Expected behavior
Mobile Data should work.

### Smartphone (please complete the following information):
 - Device: Honor 9
 - Build Flavor: system-squeak-arm64-ab-gapps.img
 - Version; V414

**Comment by Master37373** [comment]
Did yo erase efs ? If yes this is probally the cause

**Comment by AlleSchonWeg** [comment]
Hi,
it now works. I have to enable "Request IMS network". I don't know what this setting do, but it works.
