### ISSUE TITLE
Probable Bug in OTA slot switch

### ISSUE THREAD

**Issue by febeslmeisl** [phhusson/treble_experimentations#2408]
During further analysis of #2289 I encoutered following code in [phh-ota.cpp](https://github.com/phhusson/device_phh_treble/blob/android-12.0/ota/phh-ota.cpp):
```
		std::string current_slot;
		std::string next_slot;
		if(!android::base::ReadFileToString("/metadata/phh/img", &current_slot)) {
			next_slot = "a";
		} else {
			if(current_slot.c_str()[0] == 'a')
				next_slot = "b";
		}
		mkdir("/metadata/phh", 0700);
		android::base::WriteStringToFile(next_slot, "/metadata/phh/img");
```
Branch for having "b" in *existing* file /metadata/phh/img seems not covered in the if/elses and might write uninitialized "next_slot" to /metadata/phh/img. Code occures twice in

- switch-slot
- new-slot

(Upper part could also be refactored to a method like "getNextSlot" used in both sections)

**Comment by phhusson** [comment]
Uh yes, my code was very broken, thanks.

**Comment by febeslmeisl** [comment]
Thanks for fixing, but I thing branch "**switch-slot**", as already mentioned above is still affected, because it contained duplicate buggy code with "new-slot". I'm afraid slot switch from b back to a will not work at the moment.
