### ISSUE TITLE
[Xiaomi 11T Pro] [Pixel Experience GSI] Soft reboot with SIGSEGV

### ISSUE THREAD

**Issue by diogotcorreia** [phhusson/treble_experimentations#2410]
### Current Behavior:
Sometimes, randomly, a soft reboot occurs. In the logcat below, I was driving and connected to Android Auto, but it happens in all occasions (even with the phone in my pocket). Normally every few days.

From the logcat, I can see this is a segmentation fault related to a null pointer dereference.
  
### Describe the bug
Soft reboot: the boot animation shows up (the one from the ROM, not the one from Xiaomi), and the phone boots again, without asking for SIM card pin.

### To Reproduce
I have no idea, it happens randomly

### Expected behavior
There should not be any soft reboots. 

### Photos
I don't have photos, but I do have a logcat, which I've cut a snippet around the error (actual error is at line 835):
 
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/9281073/logcat.txt)

### Smartphone (please complete the following information):
 - Device: Xiaomi 11T Pro
 - Build Flavor: [PixelExperience_Plus_arm64-ab-slim-12.1-20220722-UNOFFICIAL.img.xz](https://github.com/ponces/treble_build_pe/releases/tag/v415-plus) by ponces
 - Version: v415
 - Magisk: Yes (25.2) with 3 modules:
   - [Increase Volume Steps v1.0 by blade.sk](https://github.com/bladeSk/magisk-volume-steps/)
   - [NSLENA v1.1 by Aarqw12](https://forum.xda-developers.com/attachments/nslena-v1-1-zip.5549065/)
   - [Universal SafetyNet Fix v2.2.1 by kdrag0n](https://github.com/kdrag0n/safetynet-fix)

### Additional context
It might be relevant that I've installed [YouTube Revanced](https://github.com/revanced) with root recently. It seems to happen more frequently after that, but it still happened before.
One thing that happens, is that the patch to the YouTube app is gone after reboot and the app is borked, so I have to reinstall YouTube.

Guidance on where the problem might be is also welcome, maybe it's not related to the ROM at all

**Comment by phhusson** [comment]
Monitor available memory. The crash is in new() which allocates memory, it might sound like it fails to allocate. Also catch  kernel logs (use `adb logcat -b all` rather than `adb logcat`)

**Comment by diogotcorreia** [comment]
Hi @phhusson,

After trying lots of different things (it takes a while to test since the crash happens ~2 days after boot), I found that neither YouTube Revanced nor the Magisk modules are the cause of the issue, since it still happens with those uninstalled and/or disabled.

I've also updated to the latest version ([v415.1](https://github.com/ponces/treble_build_pe/releases/tag/v415.1-plus)) of Pixel Experience Plus GSI.

I've monitored the processes using `htop` on Termux and `top` through adb, and the culprit is a memory leak on `system_server`.
Below is a set of screenshots right before, during and right after a soft reboot (the phone is still "on", so `adb` doesn't get disconnected), respectively.
![2022-08-26_16-43](https://user-images.githubusercontent.com/7467891/189318078-26f7046b-4b42-4778-8ac3-3573f9915514.png)
![2022-08-26_16-45](https://user-images.githubusercontent.com/7467891/189318091-86854797-5cd4-4a97-b354-6e290d390167.png)
![2022-08-26_16-45_1](https://user-images.githubusercontent.com/7467891/189318101-04330000-4d6a-4a00-bfb0-33c984d8e28e.png)

Memory usage of the `system_server` process goes up gradually (I'd say exponentially tbh, only during the hours before crashing does it go over 25%) during the two days it takes for it to crash.

Here is one of the logcats (not from the same time of the screenshots, I didn't get the logcat for that one), but I guess the cause is always the same.
This time I'm providing the full logcat with kernel logs (with personal information hopefully stripped out), as you requested:
https://drive.google.com/file/d/1RIlqOj1PkjmGjiSdByvGrT9koRva6CDO/view?usp=sharing
The line of the crash is: 146633

Hope this helps, let me know if you need more information.
Thanks for all the work!

**Comment by phhusson** [comment]
Right, then it's a rather known issue.
It's likely I'm the one who introduced this leak, but I don't know where to
look since I've done my changes...
Wild guess would say the issue is with
https://github.com/phhusson/platform_frameworks_native/commit/53b95fca57d2325fd517340dac2e924d420fa8a3
and notably I notice that I'm not freeing path allocated by asprintf
But as you said, it's rather annoying to test
(in your case you can revert this patch altogether, your device doesn't
need it)

Le ven. 9 sept. 2022 à 11:42, Diogo Correia ***@***.***> a
écrit :

**Comment by diogotcorreia** [comment]
I'll try to compile this myself then and see if that's really the issue.
Thanks for the insight!

**Comment by diogotcorreia** [comment]
Hi!
I've fixed the memory leak. It was in that commit indeed, and after running the fix for more than two days, memory usage of `system_server` is still low, as you can see below.
![image](https://user-images.githubusercontent.com/7467891/190854321-ba622d8f-f654-4fae-af4a-4a42e36bd87a.png)

Before the fix, the phone would have restarted by now.

I've [opened a PR](https://github.com/phhusson/platform_frameworks_native/pull/4), but not sure how you handle changes there with so many branches :sweat_smile: 
Let me know if you need me to change anything.

Feel free to close this issue when it's merged :rocket:
