### ISSUE TITLE
Can't mount system as read-write

### ISSUE THREAD

**Issue by blessingmwiti** [phhusson/treble_experimentations#2415]
Wanted to change bootanimation of AOSP 12.1 V 414 but got an error when mounting system as read-write. Any workaround on this?!

**Comment by JonnyTech** [comment]
You must flash the `VNDKLITE` variant to get a read/write filesystem.

**Comment by blessingmwiti** [comment]
> You must flash the `VNDKLITE` variant to get a read/write filesystem.

Okay, but funny thing i can't seem to boot into twrp, it is stuck at twrp logo screen

**Comment by JonnyTech** [comment]
That seems unrelated. Why do you need to boot into TWRP? Flash the image from bootloader with fastboot.

**Comment by blessingmwiti** [comment]
> That seems unrelated. Why do you need to boot into TWRP? Flash the image from bootloader with fastboot.

Did that with the following command

fastboot flash system system.img

But said the size is large

**Comment by JonnyTech** [comment]
VNKDLITE build are larger than the real-only variants. What was the exact message? How big is your system partition?

**Comment by blessingmwiti** [comment]
1.6GB

**Comment by blessingmwiti** [comment]
> Well, compare the size of the uncompressed image with the size of you phone's system partition. You may need to remove stuff from the image that you do not need.
> 
> As you are being difficult and giving full responses then I can no longer help you. Please close this issue and ask on the Telegram group: https://t.me/phhtreble

I installed it suucessfuly, thanks!
