### ISSUE TITLE
it is extremely laggy

### ISSUE THREAD

**Issue by captaincookie200** [phhusson/treble_experimentations#2419]
I am using a galaxy A32 (SM-A325F) with this. i have tried various versions of this GSI and none of them are smooth. (descendant OS, the stock aosp here on releases page, pixel experience [doesn't boot at all] and more. The performance is just unusable. I know i am gonna get hit with "GSI'S are made for various devices so its not guaranteed to work with your device perfectly" but this is the only rom that atleast helps to get some of the phone functionality back. e.g. the headphone jack fix, the flash light level, cameras stuff it all works. but because of the performance i am refraining from using it. is there a way to fix this or should i just stay out of GSI business because my stock rom is causing me problems for some reason and flashing any other GSI fixes it. ANDROID 13 GSI from google works AMAZING. just that it doesn't have the phh's treble settings and that magisk causes system UI to crash. Well back on topic. i saw other users using lineage os 19.1 based on phh's aosp working amazingly but lagging for me. Is there a way to resolve this? Thanks

**Comment by randomguyfromAustria** [comment]
I also use the same phone and it is also lagging on the launcher and on the app switch thngy. You could try installing the last android 11 update for this gsi, which i think is version v313, i tried it and it runs smoother (I tried it on the PixelExperience GSI, which is based of phh treble gsi and it runs smoother).

**Comment by captaincookie200** [comment]
i really wont like downgrading from android 12. i switched to gsi for a reason because the stock samsung firmware is having mobile data bug. (YES STOCK FIRMWARE WTF SAMSUNG) while the GSI fixes it. otherwise i would have remained on stock samsung firmware.

**Comment by captaincookie200** [comment]
oops sorry accidently pressed it

**Comment by randomguyfromAustria** [comment]
I had the same issue on my phone where the stock firmware was causing mobile data issues, posted the issue on XDA that Samsungs OneEWWWI was causing mobile data issues.

**Comment by captaincookie200** [comment]
yep exact same issue with me. like wtf samsung. Why even make these phones? just producing waste because the owner is probs gonna be fed up of the A series devices and will then go and buy  a new phone while these sit in a drawer until they become extremely old.  If your not gonna provide a smooth software experience or support then dont make phones at all.

**Comment by captaincookie200** [comment]
> I also use the same phone and it is also lagging on the launcher and on the app switch thngy. You could try installing the last android 11 update for this gsi, which i think is version v313, i tried it and it runs smoother (I tried it on the PixelExperience GSI, which is based of phh treble gsi and it runs smoother).

hey where did you download the gsi from. after installing it i am stuck in a boot loop. i clean installed not dirty it keeps rebooting at the samsung logo powered by android.

**Comment by randomguyfromAustria** [comment]
> > I also use the same phone and it is also lagging on the launcher and on the app switch thngy. You could try installing the last android 11 update for this gsi, which i think is version v313, i tried it and it runs smoother (I tried it on the PixelExperience GSI, which is based of phh treble gsi and it runs smoother).
> 
> hey where did you download the gsi from. after installing it i am stuck in a boot loop. i clean installed not dirty it keeps rebooting at the samsung logo powered by android.

I downloaded it from the PixelExperience GSI XDA thread.

**Comment by captaincookie200** [comment]
Update: i installed android 11 firmware specifically "A325FXXU2AUJ4" and it removed 100% OF THE LAG. there is no more lag at all! i am using a android 13 spark os gsi from nazim which booted on this but not android 12 firmware for this phone. Also tried android 12 gsi's its super smooth now.
