### ISSUE TITLE
"Disable night mode on some MTK for which it is very slow"

### ISSUE THREAD

**Issue by Zap123** [phhusson/treble_experimentations#242]
Is it possible to have more information on what it is disabled?
I've tried using F.lux and that uses hwcomposer on mediatek but it's really slow, however in the custom Oreo firmware worked fine. 
Apps like Twilight that use the GPU are fast but some part of the screen are not covered by the red tint so not really effective.

MTK6580 (Asus zenfone go Z00VD)

**Comment by phhusson** [comment]
the way this is done with standard AOSP mode makes hwcomposer fall to
OpenGL compositing instead of hardware 2d compositing, hence the slow done.
As far as I know, Twilight just adds a semi transparent window on top of
everything, which doesn't require OpenGL composition.
The question would be why does it fallback to OpenGL when doing with
hwcomposer. I think the issue is that the framework uses a solid color
plane, while Twilight uses a standard surface instead.

**Comment by Zap123** [comment]
Then the rom only disable the setting to enable night mode, is that correct?
I have attached a log of enabling the night mode to document the issue, 

`10-06 20:45:18.852 19718 19718 I f.lux settings: java.io.IOException: Connection refused
10-06 20:45:18.898 19718 19816 I f.lux launcher: Starting f.lux daemon as root...
10-06 20:45:18.910 19718 19816 I f.lux launcher: Running /data/user/0/com.justgetflux.flux/lib/libflux.so
10-06 20:45:18.923 19718 19816 I f.lux launcher: Starting f.lux daemon as root...
10-06 20:45:18.926 19718 19816 I f.lux launcher: Running /data/user/0/com.justgetflux.flux/lib/libflux.so
10-06 20:45:19.027   409   409 D SurfaceFlinger: duplicate layer name: changing Toast to Toast#1
10-06 20:45:19.033   404   404 D vndksupport: Loading /vendor/lib/hw/gralloc.mt6580.so from current namespace instead of sphal namespace.
10-06 20:45:19.037   406   437 I [Gralloc]: usage1: 0x900, format: 1 stride: 240 vertical_stride: 86 size: 82560
10-06 20:45:19.040   406  7229 I [Gralloc]: usage1: 0x900, format: 1 stride: 240 vertical_stride: 86 size: 82560
10-06 20:45:19.042   406  7229 I [Gralloc]: usage1: 0x900, format: 1 stride: 240 vertical_stride: 86 size: 82560
10-06 20:45:19.058   409   587 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x400
10-06 20:45:19.059   406  7229 I [Gralloc]: usage1: 0xf02, format: 1 stride: 240 vertical_stride: 86 size: 82560
10-06 20:45:19.116   404   404 D vndksupport: Loading /vendor/lib/hw/gralloc.mt6580.so from current namespace instead of sphal namespace.
10-06 20:45:19.921   404   404 I hwcomposer: [HWC] (0) displaySetColorTransform hint:1  
10-06 20:45:19.931   464   464 D PQ      : [PQ_SERVICE] return Result::INVALID_ARGUMENTS
10-06 20:45:19.931   404   404 I hwcomposer: [HWC] (0 setColorTransform ) hint:1 ok:0  
10-06 20:45:19.932   409   409 W HwcComposer: **command 0x2000000 generated error 8**
10-06 20:45:20.005   404   404 I hwcomposer: [HWC] (0) displaySetColorTransform hint:1  
10-06 20:45:20.008   464 19852 D PQ      : [PQ_SERVICE] return Result::INVALID_ARGUMENTS
10-06 20:45:20.008   404   404 I hwcomposer: [HWC] (0 setColorTransform ) hint:1 ok:0  
10-06 20:45:20.009   409   409 W HwcComposer: command 0x2000000 generated error 8
10-06 20:45:20.090   404   404 I hwcomposer: [HWC] (0) displaySetColorTransform hint:1  
10-06 20:45:20.092   464   464 D PQ      : [PQ_SERVICE] return Result::INVALID_ARGUMENTS
10-06 20:45:20.092   404   404 I hwcomposer: [HWC] (0 setColorTransform ) hint:1 ok:0  
10-06 20:45:20.093   409   409 W HwcComposer: command 0x2000000 generated error 8
10-06 20:45:20.173   404   404 I hwcomposer: [HWC] (0) displaySetColorTransform hint:1  
10-06 20:45:20.176   464 19852 D PQ      : [PQ_SERVICE] return Result::INVALID_ARGUMENTS
10-06 20:45:20.176   404   404 I hwcomposer: [HWC] (0 setColorTransform ) hint:1 ok:0  
10-06 20:45:20.177   409   409 W HwcComposer: command 0x2000000 generated error 8
10-06 20:45:20.233 19827 19827 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-06 20:45:20.250 19827 19827 W /system/bin/app_process: Could not reserve sentinel fault page
10-06 20:45:20.257   404   404 I hwcomposer: [HWC] (0) displaySetColorTransform hint:1  
10-06 20:45:20.259 19824 19824 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
`

**Comment by phhusson** [comment]
> Then the rom only disable the setting to enable night mode, is that correct?
Yup
