### ISSUE TITLE
3.5 mm jack isn't working on Samsung Galaxy Tab A8 (SM-X205)

### ISSUE THREAD

**Issue by unknown321** [phhusson/treble_experimentations#2431]
### Current Behavior:

3.5 mm jack isn't working.
  
### Describe the bug

Wired headphones work on stock fw, no sound on gsi using dsu.

### To Reproduce

Boot into any gsi image (tried google stock image, phh builds and derivatives), plug in headphones, check sound (e.g. launch youtube).

Built-in fixes don't work, tried:
  - `setprop persist.sys.overlay.devinputjack true`
  - samsung alternate audio policy
  - misc -> force headset switch
  - misc -> alternate way to detect headset
  - misc -> disable audio effects

dumpsys media.audio_policy:
  - stock rom: https://gist.github.com/unknown321/9ad31e07ae3e37d3e96def98fccfd16e
  - gsi: https://gist.github.com/unknown321/2b3af911c6a57f80d3d21bcd246a6aa3

<details><summary>getevent:</summary>

```
$ getevent
could not get driver version for /dev/input/mice, Inappropriate ioctl for device
add device 1: /dev/input/event3
  name:     "grip_sensor"
add device 2: /dev/input/event0
  name:     "hall_irq"
add device 3: /dev/input/event1
  name:     "sec_touchscreen"
add device 4: /dev/input/event2
  name:     "grip_sensor_sub"
add device 5: /dev/input/event6
  name:     "sprdphone-sc2730 Headset Jack"
add device 6: /dev/input/event5
  name:     "gpio-keys"
add device 7: /dev/input/event4
  name:     "grip_sensor_wifi"
add device 8: /dev/input/event7
  name:     "sprdphone-sc2730 Headset Keyboard"
/dev/input/event6: 0005 0002 00000001
/dev/input/event6: 0005 0004 00000001
/dev/input/event6: 0000 0000 00000000
/dev/input/event6: 0005 0002 00000000
/dev/input/event6: 0005 0004 00000000
/dev/input/event6: 0000 0000 00000000
```

</details>

dmesg (boot, plug in, type a little, plug out): https://gist.githubusercontent.com/unknown321/c3804fedb37cd0b168841f3488a506cd/raw/ea494f6c7401c66ad1279dee242143bca6d8bf88/dmesg.txt

```
[ASoC:HDST2730] dapm_jack_switch_control, on
[ASoC:HDST2730] dapm_jack_switch_control can't find kctrl 'Virt HP Jack Switch'
[ASoC:HDST2730] sprd_enable_hmicbias_polling  set polling to enable, current_polling_state 0
[ASoC:HDST2730] sprd_headset_power_set name DIG_CLK_HID, power_on 1, en 0
[ASoC:HDST2730] type_report headset plug in
[ASoC:HDST2730] ERR: vbc_close_fm_dggain is not defined!
```

### Smartphone (please complete the following information):
 - Device: Samsung Galaxy Tab A8, SM-X205 (LTE version)
 - Build Flavor:  system-squeak-arm64-ab-vanilla.img.xz
 - Version: v414

**Comment by handicraftsman** [comment]
Have the same issue on my Tab A8 as well.

If you make a fix, please provide a patch for already installed systems as well.

**Comment by cuynu** [comment]
That problem occurs even on my Masstel_X9 that using Unisoc processor, maybe vendor or kernel problem

**Comment by handicraftsman** [comment]
Well, it's often an overlay issue, you have to make an overlay to make this work. Overlays are made by copying a similar device's overlay in the repo, and then populating it with values from your stock vendors XMLs.

**Comment by unknown321** [comment]
Got kernel sources: https://opensource.samsung.com/uploadSearch -> SM-X205

sound/soc/sprd/codec/sprd/sc2730/sprd-headset-sc2730.c:

```c
 181 #pragma GCC diagnostic push
 182 #pragma GCC diagnostic ignored "-Wunused-function"
 183 int dsp_fm_mute_by_set_dg(void)
 184     __attribute__ ((weak, alias("__dsp_fm_mute_by_set_dg")));
 185 
 186 static int __dsp_fm_mute_by_set_dg(void)
 187 {
 188     pr_err("ERR: dsp_fm_mute_by_set_dg is not defined!\n");
 189     return -1;
 190 }
 191 
 192 int vbc_close_fm_dggain(bool mute)
 193     __attribute__ ((weak, alias("__vbc_close_fm_dggain")));
 194 static int __vbc_close_fm_dggain(bool mute)
 195 {
 196     pr_err("ERR: vbc_close_fm_dggain is not defined!\n");
 197     return -1;
 198 }
 199 #pragma GCC diagnostic pop
```

It looks like headset was successfully recognized; `vbc_close_fm_dggain` errors are just diagnostics, no real errors on driver's side.

**Comment by phhusson** [comment]
look for which files contain 'Virt HP Jack Switch':
`grep 'Virt HP Jack Switch' -r /vendor/etc`
then, look if there are other files with similar name, but not exact match
(like the match is in audio_commands_thingy.xml but there is a
audio_commands_stuff.xml alongside it)

**Comment by unknown321** [comment]
Nothing found for 'Jack Switch'

`/vendor/etc/audio_route.xml`: https://gist.github.com/unknown321/e847376255c18a68763cd34fb043e4d4

`/vendor/etc/audio/sku_sprd/primary_audio_policy_configuration.xml`: https://gist.github.com/unknown321/a9e124a28a85944fc0728134b3a79b78

**Comment by unknown321** [comment]
Works after updating stock system to android 12 (SM-X205_2_20221102150541_fqq8kpn0fu_fac_X205XXS1BVJ1_X205OXM1BVI6_X205XXU1BVI6_X205XXS1BVJ1_SKZ).
