### ISSUE TITLE
android 13 when?

### ISSUE THREAD

**Issue by captaincookie200** [phhusson/treble_experimentations#2432]
I have tried google's android 13 gsi which runs better then most gsi's out there. its super smooth for me. although it doesnt have phh's patches so i cant use much stuff. does someone have a idea on when android 13 gsi's will pop up? i see none right now and i know devs are mostly busy  because life. but i just wanted to ask. thanks

**Comment by captaincookie200** [comment]
i just installed it again and i was gonna live with it until i found that bluetooth does not work at all. OTHERWISE I ABSolutely love it. It is just as smooth as the stock rom for this device. although no google monet themeing. Wish phh's aosp 13 has the same smoothness and more fixes. i am switching back to android 12 now.

**Comment by phhusson** [comment]
So far I'm highly demotivated by this project, so I haven't done any work towards that yet.

**Comment by phhusson** [comment]
So far I'm highly demotivated by this project, so I haven't done any work
towards that yet.

Le ven. 9 sept. 2022 à 12:32, captaincookie200 ***@***.***> a
écrit :

**Comment by exkc** [comment]
More info about this :

https://forum.xda-developers.com/t/gsi-13-lineageos-20-light.4509315/
