### ISSUE TITLE
Bluetooth a2dp offload workaround failed on Android 13 GSI

### ISSUE THREAD

**Issue by weaponmasterjax** [phhusson/treble_experimentations#2448]
### Current Behavior:
The force disable a2dp offload option seems no longer working on **android 13 GSIs** and the bluetooth audio can't be outputed to the earphones/headsets.The audio still gets outputed **by speakers** even though **the system has displayed bluetooth earphones as the current output**
  
### Describe the bug
I used the option force disable a2dp offload in phh app to fix problems with my bluetooth audio output **device on android 12 and it worked**. However on 13 the option nolonger fixes my problems and act like a12 gsi with the option tured off(output audio out from speakers instead of selected device.

### To Reproduce
1. go to settings
2. Click on 'phh gsi settings'
3. Scroll down to 'misc'
4. tick force disable a2dp offload
5. reboot
6. connect bluetooth earphone
7. select the earphone as output in quickstep
8. play music and the audio goes out from speakers

### Expected behavior
The audio get outputed to my earphone and doesn't get played from speakers.

### Smartphone (please complete the following information):
 - Device: Redmi 10a (same hardware as 9a) (codename dandelion)
 - Build Flavor: ArrowOS-13.0-a64_bgN-Unofficial.img
 - Version [v415](https://github.com/phhusson/treble_experimentations/releases/tag/v415)

**Comment by phhusson** [comment]
I didn't make any Android 13 gsi though, not sure why you're sending this
here...

**Comment by captaincookie200** [comment]
its a known bug on nazim gsi's. i guess go try another gsi until you find one that works... i switched away from A13 because alot of things didnt work. but i loved the smoothness and didnt care abt features. i only switched to get intense smoothness which A12/12.1 didnt give.
