### ISSUE TITLE
Q: Is This SavetyNet Compatible

### ISSUE THREAD

**Issue by snoweuph** [phhusson/treble_experimentations#2451]
Can you pass SavetyNet Basic with this on degoogled version (with microg)?

**Comment by pranav-vaid** [comment]
Yes, in my device it is passing SafteyNet. I am using the floss version.

**Comment by snoweuph** [comment]
welp, for my device it didnt work in any way, ive just switched back to stock rom

**Comment by pranav-vaid** [comment]
Well, at first it also didn't worked for my device, then it started working out of the blue. 

I think there might be some connection with profile section in microG's app.
