### ISSUE TITLE
mem leaks in surfaceflinger, system_server and mediaserver

### ISSUE THREAD

**Issue by ildar** [phhusson/treble_experimentations#2453]
### Describe the bug
after a few (~4) days of work some processes consume all the RAM. Killing that processes frees up RAM.

### Smartphone (please complete the following information):
 - Device: AGM H3
 - Build Flavor: lineage_arm64_bvS-userdebug 12 SP2A.220505.002 eng.crossg.
20220511.044624
 - Version SP2A.220505.002

### Additional context
/proc files: 
[proc.txt](https://github.com/phhusson/treble_experimentations/files/9854751/1.txt)

**Comment by phhusson** [comment]
known and fixed in
https://github.com/phhusson/platform_frameworks_native/commit/f8bf40196274a9923f370ba95ce1a6d55cf448f8

**Comment by ildar** [comment]
This is awesome! thanks a lot!
any plans for release?

**Comment by phhusson** [comment]
I pushed v416 for that

**Comment by ildar** [comment]
this is complete now. Thanks a lot!
