### ISSUE TITLE
[Huawei] [Pie] Crash when de-selecting "Automatically select network"

### ISSUE THREAD

**Issue by tobykurien** [phhusson/treble_experimentations#247]
- Settings -> Network & Internet -> Mobile Network -> Advanced
- De-select "Automatically select network"
- Activity crashes, Telephony crashes (mobile networks go offline), but reconnects afterwards
- "Automatically select network" is still selected

**Comment by Dil3mm4** [comment]
@phhusson this is something that it's happening on my PRA too sometimes, sounds like a NPE even if I didn't have time to check via adb logcat. 
Also there seems to be some problems related to high drainage over RIL. 
We may chat about that.

**Comment by Dil3mm4** [comment]
This is a log while in call 
https://pastebin.com/cHgU52zm 

This is a log took reproducing what @tobykurien said (there's something odd for sure)

[logs.txt](https://github.com/phhusson/treble_experimentations/files/2523781/logs.txt)

**Comment by tobykurien** [comment]
No longer crashes on latest version, so closing

**Comment by amrithmmh** [comment]
Is it working with latest build or atleast a11?
which device are you using Prague?
