### ISSUE TITLE
[Xiaomi Mi Mix 2s] In-Call Bluetooth audio stops working after some time

### ISSUE THREAD

**Issue by rbuehlma** [phhusson/treble_experimentations#248]
After some time without a reboot, in-call audio comes through the mobile instead of the connected Bluetooth headset. The volume slider in the phone app still shows the Bluetooth icon at that point. Doing a reboot solves the issue for some time.

This is the output of [logcat](https://files.buehlmann.net/xiaomi/bt_logcat) (during call setup) and [logcat -b events -s auditd -d](https://files.buehlmann.net/xiaomi/bt_events) (after the call)

Rom: AOSP 9.0 v106
Base: miui_MIMIX2SGlobal_8.9.20_8f2e175c08_9.0.zip

Please let me know if I should provide further information.

**Comment by phhusson** [comment]
I'm closing this because this is very old, but feel free to re-open it if needed.
