### ISSUE TITLE
[Moto G6] [Pie] No battery usage data

### ISSUE THREAD

**Issue by Wabo0** [phhusson/treble_experimentations#249]
On a Moto G6 running v106 (`system-arm-aonly-vanilla-nosu.img`):

In Settings -> Battery -> Battery usage it just says "Battery usage data isn't available". Even after running for 20h since last charge.

This might be related, but is about android 5: https://forum.xda-developers.com/android/help/battery-usage-data-isnt-available-t3287013
The `res/xml/power_profile.xml` in my stock system image `framework-res.apk` definitely differs from the one in the treble image.

**Comment by Dil3mm4** [comment]
Please attach your power profile here and we will provide an overlay for your device to include it in the next release (maybe).

**Comment by Wabo0** [comment]
> Please attach your power profile here and we will provide an overlay for your device to include it in the next release (maybe).

I already made a pull request for a hardware overlay (phhusson/vendor_hardware_overlay#33).
