### ISSUE TITLE
[Xiaomi Redmi Note 5] Screen is slow to wake-up when pressing power button

### ISSUE THREAD

**Issue by ivysrono** [phhusson/treble_experimentations#25]
On Whyred (Xiaomi Redmi Note 5, OEM Treble), if "Double press on power button to start camera app" feature is enabled, the device won't wake up

Original bug report:
After press the power button, it is too late to light up the screen, even no light.

Both AOSP v16 and RR v3 have this bug.

**Comment by yshalsager** [comment]
Here's some logs @phhusson 
https://pastebin.com/06K508si
And brightness issue
https://pastebin.com/FuwUMPNM

**Comment by yshalsager** [comment]
@phhusson 
more logs:
https://hastebin.com/peloxijixo.scala
https://pastebin.com/tiWjuXWs
https://hastebin.com/utapahoveq.vbs

**Comment by yshalsager** [comment]
https://pastebin.com/jAvMQE2G

**Comment by phhusson** [comment]
Can you confirm this issue still happens?
Both on my Oreo and Pie releases?
