### ISSUE TITLE
[Rounded corners] Non-device specific

### ISSUE THREAD

**Issue by phhusson** [phhusson/treble_experimentations#251]
Currently, rounded corners is supported only on Galaxy S9(+), which is non-sense.

The steps I have in mind are:
- Rename the name of rounded corners RRO so that it's not S9 specific
- Update treble app to include all (well, as many as possible) devices concerned
- Add a user-selectable toggle
- Perhaps: Make multiple RRO for various sizes

**Comment by Dil3mm4** [comment]
Well, I'm not understanding why we should make a RRO for various sizes when we can declare a 4 dimens.xml like:

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <dimen name="rounded_corner_content_padding">8.0dip</dimen>
    <dimen name="rounded_corner_radius">8.0dip</dimen>
    <dimen name="rounded_corner_radius_top">8.0dip</dimen>
    <dimen name="rounded_corner_radius_bottom">8.0dip</dimen>
</resources>
```

And do a toggle for that within Treble App.

Were you referring to "various sizes" as in different values for the dimen values?

**Comment by phhusson** [comment]
> Were you referring to "various sizes" as in different values for the dimen values?

Yup.
I guess starting with just one value could be already good, and if users ask for more options then add other options...

**Comment by Dil3mm4** [comment]
If we have some more infos about that we could make a standard 2/3 overlays with diff dp. 
Keep me posted.

**Comment by phhusson** [comment]
I added a setting in treble app for it.
