### ISSUE TITLE
Overlay not applying and disappears after a reboot

### ISSUE THREAD

**Issue by Rekik88** [phhusson/treble_experimentations#2513]
I'm trying to build an overlay for my Samsung Galaxy S10Lite. The tests and build finish fine without any errors. When I copy the overly file to /system/product/overlay the next reboot the file disappears and nothing is applied. Am I missing something ?
Using Pixel Expirience Plus GSI A13.

**Comment by phhusson** [comment]
You're using:
```
adb root
adb remount system
adb push xxx.apk /system/product/overlay/xxx.apk
```
?

or are you using some other method?

**Comment by Rekik88** [comment]
I used the adb push when the system is running should I do it through the recovery ?

**Comment by phhusson** [comment]
did you do `adb root` and `adb remount system` ?

**Comment by Rekik88** [comment]
No i didn't remount system

**Comment by Rekik88** [comment]
I followed the commands and still the same thing

**Comment by phhusson** [comment]
How did you do it before those commands?
Are you using magisk?

**Comment by Rekik88** [comment]
And I even tried trying through a Material Files (a root file manager)

**Comment by Rekik88** [comment]
And device rooted with magisk

**Comment by phhusson** [comment]
then put magisk in core mode, or disable it.
it's magisk that prevents you from writing to system partition

**Comment by Rekik88** [comment]
Thanks it worked. Uninstalling magisk solved the problem !
