### ISSUE TITLE
[Cubot X18 Plus] No battery and CPU Temperature

### ISSUE THREAD

**Issue by Discotex79** [phhusson/treble_experimentations#252]
Hi,

in my Cubot X18 Plus i've noticed that the Battery and CPU Temperature is always 0°.
I've tried with various apps and give same result.
I've flashed the 9.0 aonly arm64 vanilla v105.

Thank you
Antonio

**Comment by phhusson** [comment]
I'm pretty sure that's vendor bug, is it the same on stock ROM?

I'm closing this because this is very old, and I don't really expect you to answer, but feel free to re-open it if needed.
