### ISSUE TITLE
Volte/IMS Bug on Samsung Devices Having Unisoc chipsets

### ISSUE THREAD

**Issue by itzgrv7** [phhusson/treble_experimentations#2525]
### Current Behavior:
  
Unable to use call and SMS services.  
### Describe the bug
 
Volte not supporting for Samsung devices , mine with UniSoc Chipset , Even on T vendor.
### Expected behavior
 
Expecting the fix to the error of volte
### Smartphone (please complete the following information):
 - Device: SAMSUNG GALAXY A03
 - Build Flavor: [e.g. system-squeak-arm64-ab-vndklite-gapps-secure.img.xz]
 - Version [e.g. V412]

**Comment by phhusson** [comment]
It's cute that you think it's reserved to Samsung devices with Unisoc chipsets.

**Comment by itzgrv7** [comment]
Ohh it means all Samsung devices have this issue🥹

**Comment by itzgrv7** [comment]
I am having face unlock bug also on this, Face is not detecting?? any fixes

**Comment by atomphil** [comment]
> Ohh it means all Samsung devices have this issue🥹

No rather means that it affects all units with Unisoc chipset. Maybe you can change the title.

**Comment by phhusson** [comment]
No, non-Samsumg Unisoc have working volte
