### ISSUE TITLE
<title>

### ISSUE THREAD

**Issue by happyeggchen** [phhusson/treble_experimentations#2530]
### Current Behavior:
  

Keeps printing "Empty SMPTE 2094-40 data"
In logcat

### Smartphone (please complete the following information):
 - Device: Redmi note 11T 5G(evergo)
 - Build Flavor: PixelExperience_Plus_treble_arm64_bvN-13.0-20230218-1750-UNOFFICIAL

### Additional context
 
I think something wrong with vulkan?Tho I don't know how to debug

**Comment by phhusson** [comment]
Why are you saying this is an issue?
Doesn't look like an issue to me

**Comment by happyeggchen** [comment]
nvm sorry for disturbing
