### ISSUE TITLE
Fingerprint on OPPO A5s not working

### ISSUE THREAD

**Issue by Khalylexe** [phhusson/treble_experimentations#2531]
### Current Behavior:
fingerprint sensor does not work
  
### Describe the bug
no fingerprint option in settings and when i try to test fingerprint sensor it doesn't work

### To Reproduce
1. Go to 'settings'
2. Click on 'Security'
3. Scroll down to 'Screen Lock'
4. No Fingerprint Option to scan

### Expected behavior
there should be an option to use biometric authentication in the settings

### Smartphone:
 - Device: Oppo A5s
 - Build Flavor: system9-arm64-aonly-gapps-su.img
 - Version v123

### Additional context
i'm 100% confident this is not a hardware issue because it works perfectly fine on stock rom

**Comment by Khalylexe** [comment]
yo does the ro.vendor.build.fingerprint have anything to do with this

**Comment by binboupan** [comment]
> yo does the ro.vendor.build.fingerprint have anything to do with this

No. Also fingerprint is broken on most (if not all) phones using GSIs.

**Comment by olsdf** [comment]
Have you found a solution?
