### ISSUE TITLE
How to install system.img (one file) inside super.img (two files, a and b)

### ISSUE THREAD

**Issue by Ed4Free** [phhusson/treble_experimentations#2539]
Hello, 

I have a smartphone Blackview BV4900s with android 11, and a Unisoc soc with which it is not possible to unlock flashing from fastboot.
Fortunately I have the stock ROM, and I can flash it with SPD Flash Tool. 
In this ROM there is no system.img but super.img
I unpacked super.bimg with imjtool (or lpunpack tool, the result is the same) as explained in [this page](https://blog.senyuuri.info/posts/2022-04-27-patching-android-super-images/).I saw that inside super.img there is system_a.img and system_b.img, The second one (b) is empty.
I unpacked  AOSP-11-system-roar-arm32_binder64-ab-vanilla.img with imjtool, I saw that there was only one file, image.img, although it is ab system partition.

My question is : how do I replace system in the stock ROM with AOSP system ?
Do I replace system_a.img in super.img with image.img I extracted from AOSP ?

Thanks a lot.

Thierry

**Comment by Ed4Free** [comment]
Thanks for you answer Cuynu.
I precise that I don't flash with Fastboot but with the constructor tool, like Odin for Samsung or SP Flash Tool for Mediatek. For Unisoc it is SPD Flash Tool.
I have verified that I can flash with SDP Flash Tool without "Fastboot flashing unlock" (but "Unlock OEM" is enabled in Android Development Options).
What I want to do is change system.img inside super.img of the stock ROM, then flash the stock ROM modified with SPD Flash Tool.

**Comment by pcurz** [comment]
if you can't unlock bootloader, it wont run custom images still

**Comment by Ed4Free** [comment]
Thanks again Cyunu. I trust you.  I just wanted to check that we were talking about flashing with SPD Flashtool and not not with Fastboot. It's also a sc9863a. on my phone.  I'll see if Blackview accept to change with a Mediatek. Thanks for the support.

**Comment by Ed4Free** [comment]
Close : not possible
