### ISSUE TITLE
[Xiamomi MI 8 SE] Signal lost due bad band selected by OS

### ISSUE THREAD

**Issue by AlonsoK28** [phhusson/treble_experimentations#254]
Device: `Xiaomi MI 8 SE`
Rom: `AOSP 9.0 v106`
Base: `Lastest MIUI EU for MI 8 SE`
Operator: AT & T
Bands of Operation: B2 `3G` and B4 / B5 `3G / LTE`
Region: Mexico

When you change the mobile network option `Settings> Network & Internet> Mobile Network> Advanced> Prefered network type` from 3G (default) to 4G the mobile network signal is completely lost

- Verifying with the `Netwrok Cell Info Lite` app I can notice that the network is operating on the **B7 band** at the moment of making that change, leaving me without a signal because my carrier does not transmit anything in that band

- Is it normal for this to happen?

- Is there a timeout to verify the operating band of the device / carrier 

- Are the bands adjusted according to the region?

**Comment by phhusson** [comment]
I doubt that bands are the issue.
Could you provide full logcat? (`logcat -b all`)

That's a GSM provier, not CDMA, right?
