### ISSUE TITLE
[Vivo 1806(MTK)]Unable to set lock screen password

### ISSUE THREAD

**Issue by PeterTea5822** [phhusson/treble_experimentations#2545]
### Current Behavior:
When set a lock screen password in the 'Settings' app, the 'Settings' app will be crash
 
### Log:
`04-30 18:26:03.395 I/hwcomposer(  858): [HWCDisplay] [Display_0 (type:1)] fps:40.685829,dur:1007.72,max:322.63,min:16.05  
04-30 18:26:03.531 E/ocessService0:0(10360): failed to create Unix domain socket: Operation not permitted
04-30 18:26:04.403 I/hwcomposer(  858): [HWCDisplay] [Display_0 (type:1)] fps:59.534889,dur:1007.81,max:19.74,min:14.33  
04-30 18:26:04.807 E/WifiVendorHal( 1603): getWifiLinkLayerStats_1_3_Internal(l.1153) failed {.code = ERROR_NOT_SUPPORTED, .description = }
04-30 18:26:04.898 I/hwservicemanager(  344): getTransport: Cannot find entry android.hardware.weaver@1.0::IWeaver/default in either framework or device VINTF manifest.
04-30 18:26:04.902 E/gatekeeperd( 1182): clear_sid: could not remove file [No such file or directory], attempting 0 write
04-30 18:26:04.905 I/TeeSysClient(  844): driver version: v7.0 [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/ClientLib/src/driver.cpp:104]
04-30 18:26:04.905 I/TeeSysClient(  844): driver open [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/ClientLib/src/driver.cpp:109]
04-30 18:26:04.915 I/TeeMcDaemon(  761): open: Open storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:178]
04-30 18:26:04.916 E/TeeMcDaemon(  761): open: No such file or directory opening storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:182]
04-30 18:26:04.917 I/TeeMcDaemon(  761): create: Create storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:134]
04-30 18:26:04.917 E/TeeMcDaemon(  761): creating storage folder failed with "No such file or directory"(errno 2) [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:137]
04-30 18:26:04.918 I/TeeMcDaemon(  761): open: Open storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:178]
04-30 18:26:04.919 E/TeeMcDaemon(  761): open: No such file or directory opening storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:182]
04-30 18:26:04.919 I/TeeMcDaemon(  761): create: Create storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:134]
04-30 18:26:04.919 E/TeeMcDaemon(  761): creating storage folder failed with "No such file or directory"(errno 2) [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:137]
04-30 18:26:04.920 I/TeeMcDaemon(  761): open: Open storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:178]
04-30 18:26:04.920 E/TeeMcDaemon(  761): open: No such file or directory opening storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:182]
04-30 18:26:04.920 I/TeeMcDaemon(  761): create: Create storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:134]
04-30 18:26:04.920 E/TeeMcDaemon(  761): creating storage folder failed with "No such file or directory"(errno 2) [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:137]
04-30 18:26:04.921 I/TeeMcDaemon(  761): open: Open storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:178]
04-30 18:26:04.921 E/TeeMcDaemon(  761): open: No such file or directory opening storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:182]
04-30 18:26:04.922 I/TeeMcDaemon(  761): create: Create storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:134]
04-30 18:26:04.922 E/TeeMcDaemon(  761): creating storage folder failed with "No such file or directory"(errno 2) [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:137]
04-30 18:26:04.925 I/TeeSysClient(  844): driver closed [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/ClientLib/src/driver.cpp:120]
04-30 18:26:04.927 I/TeeSysClient(  844): driver version: v7.0 [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/ClientLib/src/driver.cpp:104]
04-30 18:26:04.927 I/TeeSysClient(  844): driver open [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/ClientLib/src/driver.cpp:109]
04-30 18:26:04.935 I/TeeMcDaemon(  761): open: Open storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:178]
04-30 18:26:04.935 E/TeeMcDaemon(  761): open: No such file or directory opening storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:182]
04-30 18:26:04.935 I/TeeMcDaemon(  761): create: Create storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:134]
04-30 18:26:04.935 E/TeeMcDaemon(  761): creating storage folder failed with "No such file or directory"(errno 2) [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:137]
04-30 18:26:04.937 I/TeeMcDaemon(  761): open: Open storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:178]
04-30 18:26:04.937 E/TeeMcDaemon(  761): open: No such file or directory opening storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:182]
04-30 18:26:04.937 I/TeeMcDaemon(  761): create: Create storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:134]
04-30 18:26:04.937 E/TeeMcDaemon(  761): creating storage folder failed with "No such file or directory"(errno 2) [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:137]
04-30 18:26:04.938 I/TeeMcDaemon(  761): open: Open storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:178]
04-30 18:26:04.938 E/TeeMcDaemon(  761): open: No such file or directory opening storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:182]
04-30 18:26:04.939 I/TeeMcDaemon(  761): create: Create storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:134]
04-30 18:26:04.939 E/TeeMcDaemon(  761): creating storage folder failed with "No such file or directory"(errno 2) [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:137]
04-30 18:26:04.940 I/TeeMcDaemon(  761): open: Open storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:178]
04-30 18:26:04.940 E/TeeMcDaemon(  761): open: No such file or directory opening storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:182]
04-30 18:26:04.941 I/TeeMcDaemon(  761): create: Create storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:134]
04-30 18:26:04.941 E/TeeMcDaemon(  761): creating storage folder failed with "No such file or directory"(errno 2) [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:137]
04-30 18:26:04.942 I/TeeMcDaemon(  761): open: Open storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:178]
04-30 18:26:04.942 E/TeeMcDaemon(  761): open: No such file or directory opening storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:182]
04-30 18:26:04.942 I/TeeMcDaemon(  761): create: Create storage file "/data/vendor/mcRegistry/TbStorage/Store_0.tf" [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:134]
04-30 18:26:04.942 E/TeeMcDaemon(  761): creating storage folder failed with "No such file or directory"(errno 2) [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/Daemon/src/FSD2.cpp:137]
04-30 18:26:04.946 I/TeeSysClient(  844): driver closed [vendor/mediatek/proprietary/trustzone/trustonic/source/external/mobicore/common/410/ClientLib/src/driver.cpp:120]
04-30 18:26:04.961 D/mali_winsys( 1603): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
04-30 18:26:04.970 E/FrameEvents( 1603): updateAcquireFence: Did not find frame.
04-30 18:26:04.988 I/Process ( 8690): Sending signal. PID: 8690 SIG: 9
04-30 18:26:05.015 I/GED     ( 1603): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 15, oppidx_max 15, oppidx_min 0
04-30 18:26:05.083 I/Zygote  ( 1111): Process 8690 exited due to signal 9 (Killed)
04-30 18:26:05.087 W/InputManager-JNI( 1603): Input channel object 'f91c com.android.settings/com.android.settings.Settings (client)' was disposed without first being removed with the input manager!
04-30 18:26:05.090 W/InputManager-JNI( 1603): Input channel object '7f8647c com.android.settings/com.android.settings.homepage.DeepLinkHomepageActivityInternal (client)' was disposed without first being removed with the input manager!
04-30 18:26:05.092 W/InputManager-JNI( 1603): Input channel object '6c2c363 com.android.settings/com.android.settings.SubSettings (client)' was disposed without first being removed with the input manager!
04-30 18:26:05.098 I/Process ( 1603): Sending signal. PID: 8690 SIG: 9
04-30 18:26:05.112 W/InputManager-JNI( 1603): Input channel object '5d4d7ff com.android.settings/com.android.settings.password.ChooseLockPattern (client)' was disposed without first being removed with the input manager!
04-30 18:26:05.114 I/libprocessgroup( 1603): Successfully killed process cgroup uid 1000 pid 8690 in 0ms
04-30 18:26:05.116 I/Process ( 1603): Sending signal. PID: 8690 SIG: 9
04-30 18:26:05.121 W/InputManager-JNI( 1603): Input channel object 'a654347 com.android.settings/com.android.settings.SubSettings (client)' was disposed without first being removed with the input manager!
04-30 18:26:05.125 W/InputManager-JNI( 1603): Input channel object '7e3f905 com.android.settings/com.android.settings.SubSettings (client)' was disposed without first being removed with the input manager!
04-30 18:26:05.147 E/BpTransactionCompletedListener( 1610): Failed to transact (-32)
04-30 18:26:05.151 D/Zygote  ( 1111): Forked child process 12534
04-30 18:26:05.155 D/mali_winsys( 2225): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
04-30 18:26:05.155 E/OpenGLRenderer( 2225): Unable to match the desired swap behavior.
04-30 18:26:05.176 W/TransactionTracing( 1610): Could not find layer handle 0x71f78edd10
04-30 18:26:05.176 W/TransactionTracing( 1610): Could not find layer handle 0x71f794e1f0
04-30 18:26:05.183 I/adbd    (12173): jdwp connection from 12534
04-30 18:26:05.188 I/ndroid.systemui( 1998): NativeAlloc concurrent copying GC freed 42455(2230KB) AllocSpace objects, 14(280KB) LOS objects, 30% free, 13MB/19MB, paused 165us,173us total 207.918ms
04-30 18:26:05.198 E/IPCThreadState(12534): Got kernel major version 4
04-30 18:26:05.204 D/CompatibilityChangeReporter(12534): Compat change id reported: 171979766; UID 1000; state: ENABLED
04-30 18:26:05.228 W/ndroid.settings(12534): ClassLoaderContext shared library size mismatch. Expected=3, found=2 (PCL[]{PCL[/system/framework/org.apache.http.legacy.jar*3751013904]#PCL[/system/system_ext/framework/androidx.window.extensions.jar*3814077790]#PCL[/system/system_ext/framework/androidx.window.sidecar.jar*1802474064]} | PCL[]{PCL[/system/framework/org.apache.http.legacy.jar*3751013904]#PCL[/system/system_ext/framework/androidx.window.extensions.jar*3814077790]})
04-30 18:26:05.249 V/GraphicsEnvironment(12534): ANGLE Developer option for 'com.android.settings' set to: 'default'
04-30 18:26:05.249 V/GraphicsEnvironment(12534): ANGLE GameManagerService for com.android.settings: false
04-30 18:26:05.250 V/GraphicsEnvironment(12534): Neither updatable production driver nor prerelease driver is supported.
04-30 18:26:05.253 D/NetworkSecurityConfig(12534): No Network Security Config specified, using platform default
04-30 18:26:05.254 D/NetworkSecurityConfig(12534): No Network Security Config specified, using platform default
04-30 18:26:05.277 D/SettingsSliceProvider(12534): init
04-30 18:26:05.278 D/SettingsSliceProvider(12534): onCreateSliceProvider
04-30 18:26:05.284 I/system_server( 1603): NativeAlloc concurrent copying GC freed 29561(2331KB) AllocSpace objects, 0(0B) LOS objects, 25% free, 17MB/23MB, paused 354us,136us total 218.686ms
04-30 18:26:05.285 W/System  ( 1603): A resource failed to call HardwareBuffer.close. 
04-30 18:26:05.286 W/System  ( 1603): A resource failed to call HardwareBuffer.close. 
04-30 18:26:05.313 D/ActivityEmbeddingUtils(12534): isFlagEnabled = true
04-30 18:26:05.313 D/ActivityEmbeddingUtils(12534): isSplitSupported = true
04-30 18:26:05.413 I/hwcomposer(  858): [HWCDisplay] [Display_0 (type:1)] fps:33.638721,dur:1010.74,max:305.40,min:12.62  
04-30 18:26:05.531 E/ocessService0:0(10360): failed to create Unix domain socket: Operation not permitted`

### Thanks for your help!!!😊😘
How do I fix it? I can use Magisk to make modifications to the system  partition

**Comment by phhusson** [comment]
Your log is unreadable because it is missing line returns, can you make it again? And maybe just attach it as a file

**Comment by PeterTea5822** [comment]
> 您的日志不可读，因为它缺少行返回符，您可以再次进行吗？也许只是将其作为文件附加


### Log：
[log.txt](https://github.com/phhusson/treble_experimentations/files/11369118/log.txt)

Thank you for your response😍
I am sorry for my negligence😂

### Here's more information about the device:

- SOC: MT6771
- RAM:4G
- system-as-root:true
Please remind me to add if I miss something😘

**Comment by PeterTea5822** [comment]
> 您的日志不可读，因为它缺少行返回符，您可以再次进行吗？也许只是将其作为文件附加

**Comment by PeterTea5822** [comment]
Resubmit[Vivo 1806(MTK)]Unable to set lock screen password: #2546
