### ISSUE TITLE
[Mi Mix 2S] Mobile Data not working on MNVO Docomo

### ISSUE THREAD

**Issue by Kaggy** [phhusson/treble_experimentations#255]
The mobile data does not work when I use any Treble ROMs built off your base.
Mobile data works when on MIUI ROM, also works on another phone.
Phone calls worked fine.
Network band is U2100 (HSDPA) L2100 (LTE)
Have set the APN settings
APN: mineo-d.jp
User: mineo@k-opti.com
Password: mineo
Authentication type: CHAP

**Comment by Kaggy** [comment]
Likely related to this issue.
"[Sharp Aquos S2] Not all telecommunications operator work #190"

**Comment by phhusson** [comment]
Please provide full logcat (`logcat -b all`)
