### ISSUE TITLE
Can't Send/Receive Messages on Samsung Tab A8

### ISSUE THREAD

**Issue by SamDaaEpic** [phhusson/treble_experimentations#2556]
Hello.
I'm running Lineage OS 20 GSI rom on my Samsung Tab A8. I have also tried phhusson AOSP and many other phh supported GSI roms, but in none of them, I could get the Messages/SMS working. I used *#*#4636#*#* to check my phone information and there was no SMS-Service-Number in the SMSC field. So I put in my Carrier's (JIO, here in India) number that is "1234",129. But even after doing that I couldn't receive nor send messages. I also tried forcing 2G/3G but still nothing. I really want SMS to work in order to be able to receive OTP's and stuff. I know about VoLTE and that It wouldn't work beceause of Samsung's Proprietary IMS Implementation. But can you please help me try to get SMS working on my Samsung Galaxy Tab A8?

**Comment by SamDaaEpic** [comment]
Used https://github.com/Phhusson/IMS to get SMS working.

**Comment by tydudev** [comment]
How did you compiles it out in detail? I don't know gradle.
