### ISSUE TITLE
Fingerprint is not working on OPPO R11(CPH1707)

### ISSUE THREAD

**Issue by HLEndman** [phhusson/treble_experimentations#256]
The fingerprint setting was disappeared in settings，and the home button also not working.
I tried to copy the files about fingerprint from the stock ROM，and the home button is working，but fingerprint still not working，the fingerprint setting is still losing.
[getprop.txt](https://github.com/phhusson/treble_experimentations/files/2483851/getprop.txt)

**Comment by phhusson** [comment]
Is the treble implementation from Oppo or from community?

**Comment by HLEndman** [comment]
its working after I flashed a new patch now.

**Comment by olsdf** [comment]
What is the patch?
