### ISSUE TITLE
What does "-secure" mean ( in the GSI's name )

### ISSUE THREAD

**Issue by minou2020** [phhusson/treble_experimentations#2568]
Title

**Comment by JonnyTech** [comment]
From the Telegram support channel https://t.me/phhtreble

> Secure" variant fakes stuff to make it look like stock ROM to pass various stupid "security: measures, like safetynet, or removing root.
> This is makes sense for dumb apps that shit on users who think they own their phones.
> It does one useful security thing however, which is removing full access adb

**Comment by minou2020** [comment]
> From the Telegram support channel https://t.me/phhtreble
> 
> > Secure" variant fakes stuff to make it look like stock ROM to pass various stupid "security: measures, like safetynet, or removing root.
> > This is makes sense for dumb apps that shit on users who think they own their phones.
> > It does one useful security thing however, which is removing full access adb

Does it mean adb is unusable in this build ?
