### ISSUE TITLE
wi-fi access point does not work on MTK

### ISSUE THREAD

**Issue by Taras2000** [phhusson/treble_experimentations#257]
It is not possible to enable Internet distribution via a Wi-Fi access point.

**Comment by phhusson** [comment]
On which GSI version?
What's the behaviour?
Logs?

**Comment by Taras2000** [comment]
V105 v106
when you turn on the access point, it immediately turns off

**Comment by phhusson** [comment]
To the best of my knowledge hotspot works on all my Mediatek devices these days.

If you still happen to have the issue, please open a new issue with more infos. (logs & device name for starters)
