### ISSUE TITLE
[Motorola G51] Expose aux cams not working 

### ISSUE THREAD

**Issue by Mitezuss** [phhusson/treble_experimentations#2579]
Logs from: adb shell dumpsys media.camera

[STOCK.log](https://github.com/phhusson/treble_experimentations/files/13064586/STOCK.log)
[GSI.log](https://github.com/phhusson/treble_experimentations/files/13064588/GSI.log)

@phhusson 
Need more info ? or any test to do?

Regards

**Comment by phhusson** [comment]
How did you fix it?
