### ISSUE TITLE
How to flash Huawei P10 critical partitions?

### ISSUE THREAD

**Issue by michal25** [phhusson/treble_experimentations#2605]
How to flash Huawei P10 critical partitions?
adb reboot bootloader
fastboot flash erecovery_ramdisk magisk_patched-26400_ERECOVERY-ERECOVERY_RAMDISK.img 
Sending 'erecovery_ramdisk' (32768 KB)             OKAY [  0.978s]
Writing 'erecovery_ramdisk'                        FAILED (remote: 'Command not allowed')
fastboot: error: Command failed

adb reboot fastboot
power off the phone, this fastboot mode is not working

fastboot reboot fastboot
Rebooting into fastboot                            OKAY [  0.005s]
< waiting for any device >
Reboot into system partition

Smartphone is unlocked and rooted via Magisk
https://github.com/phhusson/treble_experimentations/discussions/2542

Any idea?
Thanks

**Comment by phhusson** [comment]
I'm not exactly sure how you thought this place was relevant...
