### ISSUE TITLE
[Samsung Note9] S-Pen mouse landscape position

### ISSUE THREAD

**Issue by Potatoforfun** [phhusson/treble_experimentations#261]
Spen works as a mouse in the aosp roms, when in portrait mode it is aligned well, but when phone is rotated to landscape mode, it is stuck in portrait. video in [xda post attachement](https://forum.xda-developers.com/attachment.php?attachmentid=4624505&d=1540204128) with logcat

**Comment by Potatoforfun** [comment]
Logcats that Actually show something, [Raw](https://forum.xda-developers.com/attachment.php?attachmentid=4631071&d=1540984289), [Cleaned](https://forum.xda-developers.com/attachment.php?attachmentid=4631070&d=1540984289) 

Seems like there is 5 default input devices, one being the touchscreen.
and when the device goes to landscape, 2 out of the 5 rotate, 3 don't.

Summary:
System----------------------sec_e-pen--------------------Does NOT rotate
System----------------------sec_touchscreen------------Does rotate
System----------------------sec_touchpad---------------Does NOT rotate
System----------------------sec_virtual-e-pen-----------Does NOT rotate
System----------------------sec_e-pen-pad--------------Does rotate
Bluetooth Mouse----------G603--------------------------Does rotate

looks like files are in /dev/input

**Comment by phhusson** [comment]
could you give the result of adb shell dumpsys input

Le mer. 31 oct. 2018 à 12:21, Potatoforfun <notifications@github.com> a
écrit :

**Comment by Potatoforfun** [comment]
this is for the rom I have.
https://pastebin.com/kE7fx4DR

I will restore back to your v26 rom to give the result for rom

**Comment by Potatoforfun** [comment]
Here is the one for your rom 9.0 v106
https://pastebin.com/aX8TgDh3

Very grateful phhusson for your contributions =)

**Comment by thatsameguy** [comment]
hello phhusson, I am the same guy. I finally found a fix.
according to [source documentation](https://source.android.com/devices/input/input-device-configuration-files), i made an [input configuration file (.idc)](https://forum.xda-developers.com/attachment.php?attachmentid=4633252&d=1541231236) by the name of the input device. I placed it /system/usr/idc. 
it simply has touch.orientationAware = 1
upon reboot it was working

please add it. thank you a lot.

**Comment by phhusson** [comment]
sec_e-pen.idc?

**Comment by thatsameguy** [comment]
Yes. It has the line above. It is in the zip file in the link.

**Comment by thatsameguy** [comment]
Yes. I believe so.. Thank you
