### ISSUE TITLE
[markw] Switch recent apps button not working on Redmi 4 Prime / Pro

### ISSUE THREAD

**Issue by rubensa** [phhusson/treble_experimentations#262]
I have a problem with my **Redmi 4 Prime/Pro** using **system-arm64-aonly-gapps-su.img.xz  v25**.

The first hardware button (I think is **139** hardware key) seems to be mapped to **MENU** so I can't access recent apps on my phone (only extra menu entries on some apps).

I've compared **usr/keylayout** content from **treble** to **xiaomi.eu_multi_HM4Pro_V8.1.3.0.MBECNDI_v8-6.0** and found some extra **kl** files in xiami.eu rom which include mapping key **139** to **APP_SWITCH** (**ft5x06_ts.kl**, **synaptics_dsx.kl**, **synaptics_dsxv26.kl** and **synaptics_rmi4_i2c.kl**).

I don't know exactly witch one is the responsible for the mapping change on my phone but... _should It be possible to include those files in treble rom?_

PS:  It's possible that I'm totally wrong with this as I'm not an android developer (only guessing).

**Comment by rubensa** [comment]
Ok, I checked vendor partition (from **VENDOR_AOSP_OLDSHIM_markw-20180803.zip**) and it includes **usr/keylayout/ft5x06_ts.kl**, which seems to be the responsible for remapping **139** to **APP_SWITCH** but...  _Why is not working?_

Any body could help me on this?  Isn't supposed that vendor override GSI?

PS: As temporary fix I manually modified usr/keylayout/Generic.kl to remap 139 from MENU to APP_SWITCH.

**Comment by TadiT7** [comment]
It may sound brutal, but we shouldn't fix custom Treble vendor problems in GSI. If we fix something in GSI, it's meant to support the stock Treble implementations, without the need to create a custom vendor. But as you already have a custom vendor, it should be fixed by its author.

**Comment by phhusson** [comment]
As @TadiT7 says, this is a vendor issue, since this is a community treble, see with your dev. (though I'm available if your dev needs help)
Just as a reference, Redmi Go's "recent apps" hardware button works fine.
