### ISSUE TITLE
Redmi 12 - "surfaceflinger" spams with errors 

### ISSUE THREAD

**Issue by sem1c0lon** [phhusson/treble_experimentations#2621]
### Current Behavior: 
Surfaceflinger spams with errors literally out of nowhere.
Also random reboots happen, once in a few hours, the more often I use my phone, thus the more often random reboots happen. I am talking about soft-reboots, e.g. the phone is working, everything is alright, and then the lineageos bootlogo pops up just out of nowhere.
I guess that also has to do something with the fact that there are surfaceflinger errors, although I haven't tried to debug it yet since it's not that easy to "catch" the random soft-reboot.

### Describe the bug
Surfaceflinger errors happen everytime there is some update in the UI. I have enabled "show seconds" in the status bar clock, so every second an "update" in the UI happens. If the phone is just idle, surfaceflinger errors pop up every second, which is the consequence of the clock in the status bar refreshing every second. When there are more "updates", e.g. If I just scroll in the settings, hence the more surfaceflinger errors I see in the log.

Also, after a few hours of using the phone, the UI becomes so laggy that I need to do "pkill surfaceflinger" to perform a soft-reboot and after that the UI is fine again.

### To Reproduce
Running "adb logcat" and seeing tons of surfaceflinger errors: 
"1704  1704 E surfaceflinger: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288"

### Smartphone (please complete the following information):
 - Device: Redmi 12 
 - Build Flavor: lineage_arm64_bgN-userdebug
 - Version: latest LineageOS 20 ARM64 bgN by Andy Yan

First log is the phone just being on the home screen for a minute, second log is me scrolling in the settings for 15 seconds.
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/14886873/logcat.txt)
[logcat2.txt](https://github.com/phhusson/treble_experimentations/files/14886874/logcat2.txt)

**Comment by phhusson** [comment]
I doubt this log is particularly relevant, let's focus on the lag

When it's lagging, or at least after few hours, run `top` inside `adb shell` and see which process takes the most RAM (probably `top -s 10` will sort by memory usage taken... or not). Check also which one takes the most CPU

**Comment by sem1c0lon** [comment]
Enabling the flashlight for a few times also makes the ui slow, unresponsible id say. Killing surfaceflinger solves the issue.

**Comment by sem1c0lon** [comment]
> I doubt this log is particularly relevant, let's focus on the lag
> 
> When it's lagging, or at least after few hours, run `top` inside `adb shell` and see which process takes the most RAM (probably `top -s 10` will sort by memory usage taken... or not). Check also which one takes the most CPU

Thanks, will do

**Comment by sem1c0lon** [comment]
After a few minutes of being in this unresponsive state the phone just soft rebooted on its own. Not sure what causes the problem.

**Comment by sem1c0lon** [comment]
Uhh, changing the Compatibility max aspect ratio to 1.86 in Phh settings seem to fix something?
Like at least after a few hours of using the phone the UI is fine, I am currently not sure, I need more time to test

**Comment by sem1c0lon** [comment]
I guess that fixed the issue.
