### ISSUE TITLE
[Huawei FIG-LX1] Flashlight function not working

### ISSUE THREAD

**Issue by joaquimorg** [phhusson/treble_experimentations#264]
Hi in the version **AOSP 9.0 v106** the **Flashlight** function is _disable_, but in the Camera the flashlight works.
![screenshot_20181024-085608](https://user-images.githubusercontent.com/1682318/47415957-8c97d280-d76c-11e8-9702-9938404cf16c.png)

**Comment by Minifiles** [comment]
I am experiencing the same on my Huawei P Smart FIG-LX1. 
I've tried to install a [flashlight app](https://play.google.com/store/apps/details?id=com.simplemobiletools.flashlight) to see if it's only in the quick tools.
When I try to turn on the flashlight in the app, it gives me the error: "Obtaining the camera failed"
I hope this helps troubleshooting this problem a little bit.

**Comment by scooter1556** [comment]
I have the same issue on my Honor 9 with all 9.0 builds (currently running v107).

**Comment by andretiagogr** [comment]
Did you try AOSP 9.0 v108? According to the changelog, the [flashlight was fixed on huawei devices](https://github.com/phhusson/treble_experimentations/releases/tag/v108).

**Comment by milankragujevic** [comment]
It was not on ATU L21.

**Comment by joaquimorg** [comment]
Yes is fixed !
