### ISSUE TITLE
Cat S22 Flip GSI android 14 not getting incoming calls

### ISSUE THREAD

**Issue by thejokervinay** [phhusson/treble_experimentations#2642]
Hi the Cat S22 Flip does not get incoming calls notifications even after clearing cache and storage of phone.app. have installed ims.apk and can receive texts and can send texts, can call even on volte, volte is also enabled, could you please check and let us know a solution for it, I've added both los20 where we receive calls texts everything, where in los21 the caller can can us it rings too but we don't get the notification to pick the call, have also added los21 logs too for checking.
Thankyou.
[(los20)logs.txt](https://github.com/user-attachments/files/16249289/los20.logs.txt)
[(los21)logs.txt](https://github.com/user-attachments/files/16249290/los21.logs.txt)

**Comment by axyzs** [comment]
I’ve been looking for a solution as well as I’ve experienced the same issues. I’ve tried at least 20 different GSI ROMs, and they all had the same problems. HOWEVER, there is an exception.

I have no idea what kind of magic this GSI ROM has, but it works with VoLTE without any issues. You can try the Lineage 21 Light version here: [Lineage 21 Light](https://sourceforge.net/projects/andyyan-gsi/files/lineage-21-light/).

For any GSI ROMs with full PHH Treble settings, I couldn’t get incoming calls to work. But the Lineage 21 Light version doesn’t have the full PHH Treble settings, yet it works magically. I’ve compared the configs and overlays, but couldn’t find any clues. I hope someone can shed some light on this.

**Comment by thejokervinay** [comment]
I did find a solution to this, unfortunately arm64 is not supported in our device which is the only one available in Lineage 21 light. But thankyou anyway.
