### ISSUE TITLE
Screen flickering on Xiaomi Redmi Note 12 Pro 5G (ruby)

### ISSUE THREAD

**Issue by jirihalbych** [phhusson/treble_experimentations#2644]
While not touching the display after few seconds the display starts to flicker. The brightness slider doesn't change the brightness which seems to be stuck to max.
Managed to change the brightness using "echo 2000 > /sys/class/leds/lcd-backlight/brightness"
Even with lower brightness, the screen starts to flicker (the flickering has different brightness than the current one)

 - Device: Xiaomi Redmi Note 12 Pro 5G (ruby)
 - Build Flavor: leaf-3.2-320-microG-leaf_gsi_arm64-img.zip
 Also happens on:
 - Build Flavor: system-td-arm64-ab-vanilla.img.xz 
 - Version: android_14.0.0_r27 ci-20240226

**Comment by snapboss** [comment]
adb shell settings put system min_refresh_rate 60

**Comment by jirihalbych** [comment]
Worked like magic! Thank you so much ^^
