### ISSUE TITLE
[P8 Lite 2017] Bootloop v25, v26 Logs

### ISSUE THREAD

**Issue by SuperKingZ** [phhusson/treble_experimentations#265]
P8 Lite 2017
PRA-LA1C185B384
October 2018 System Security
Disabled fstab Encryption 
Clean installation

[v23-working.log](https://github.com/phhusson/treble_experimentations/files/2510482/v23-Working.txt)
[v25-bootloop.log](https://github.com/phhusson/treble_experimentations/files/2510483/v25-bootloop.txt)
[v26-bootloop.log](https://github.com/phhusson/treble_experimentations/files/2510484/v26-bootloop.txt)

**Comment by Dil3mm4** [comment]
I'm sorry to chime in here @phhusson  but in reference to https://github.com/phhusson/device_phh_treble/pull/57 

`10-24 12:24:10.153  1036  1036 I vendor.huawei.hardware.hwdisplay.displayengine@1.0-service: main:27: We're the service for display engine hal.
10-24 12:24:10.154  1035  1035 E HAL     : load: id=hisupl.hi1102 != hmi->id=hisupl
10-24 12:24:10.154  1035  1035 E HiSuplHAL_HiSuplInterface: supl hw_get_module hisupl failed: -22
10-24 12:24:10.154  1035  1035 E venodr.huawei.hardware.hisupl@1.0-service: Could not get passthrough implementation for vendor.huawei.hardware.hisupl@1.0::ISuplclienttoserverInterface/default.`

Both in v25 and v26 logs.

**Comment by phhusson** [comment]
I'm closing this issue because it is very old.
Feel free to re-open it if needed.

**Comment by Iceows** [comment]
Hi
Can we reopen the issue ? I work on a correct implementation of the GPS on the PRA and I am blocked by this problem . 

09-30 08:30:52.686 13641 13641 E HAL     : load: id=hisupl.hi1102 != hmi->id=hisupl
09-30 08:30:52.687 13641 13641 E HiSuplHAL_HiSuplInterface: supl hw_get_module hisupl failed: -22
09-30 08:30:52.687 13641 13641 E venodr.huawei.hardware.hisupl@1.0-service: Could not get passthrough implementation for vendor.huawei.hardware.hisupl@1.0::ISuplclienttoserverInterface/default.
09-30 08:30:52.695     0     0 D [91057.464416s][pid:414,cpu3,logd.reader]logd: logdr: UID=0 GID=0 PID=13638 n tail=50 logMask=1 pid=13634 start=0ns timeout=0ns
09-30 08:30:52.735     0     0 I [91057.464752s][pid:1,cpu2,init]: Service 'hisupl_service' (pid 13641) exited with status 1
