### ISSUE TITLE
Umidigi Z2 - (MTK6763) no functional cell service for phone calls or data

### ISSUE THREAD

**Issue by 8472** [phhusson/treble_experimentations#267]
system.img for A-only ARM64 devices with GApps and SU installs and functions normally however there is no functional cell service (2G, 3G, 4G) support   -   Unable to make or receive phone calls.   No cell data.

**Comment by guzzleguy** [comment]
I have the same issue. The link doesn't work. Can someone please give me a gibt how to solche that problem. I flashed the Umidigi Z2 with the Treble GSI AOSP v109. I have -4- problems. 1. System camera doesn't work (solved with another camera app, Like open camera). 2. No receive/senden function of SMS/MMS. 3. No phone call function, receiving calls works. 4. No mobile data functionality. Dir meine the 3rd anderen 4th problems are important. 
Thanks a lot beforehand.

**Comment by lincolnayisi** [comment]
this worked for me until now. sim cards disable randomly. always have to keep rebooting the phone when I need to make calls.  sim 2 even tho is on roaming mostly losses network. 
I heard whether or not an attempt trying to change forceencrypte to encryptable in vendor/etc/fstab6763 causes cell connection problems. I see a lot of complaints concerning network, USSD, SMS, incoming calls on mtk devices trying to use gsi roms..... It is really a frustrating issue. if @phhusson could address this for us.. It will be a great deal.

**Comment by phhusson** [comment]
@lincolnayisi the issue you're describing doesn't have much to do with this one.
Please open a new one to discuss stability issue (WITH LOGS)
