### ISSUE TITLE
Vernee T3 Pro UI issues

### ISSUE THREAD

**Issue by Anatoly33** [phhusson/treble_experimentations#268]
Vernee T3 Pro (android 8.1)
Booted vanilla v106 but UI issues
[log_vernee_t3_pro.txt](https://github.com/phhusson/treble_experimentations/files/2526028/log_vernee_t3_pro.txt)

**Comment by Anatoly33** [comment]
UI does work fine now. Thanks.

**Comment by marcopilli** [comment]
Hi There. I'm interesting to use a custom rom on this Phone. Any tip to install any (what kind of, and where to get it). Are you test it in treble project? Tanks.
