### ISSUE TITLE
[Kirin655][PRA-**] Muting calls doesn't work

### ISSUE THREAD

**Issue by Dil3mm4** [phhusson/treble_experimentations#27]
https://pastebin.com/c76HWXwS

**Comment by phhusson** [comment]
Could be because of packages/services/Telephony send_mic_mute_to_AudioManager which needs to be "true", but I've decompiled Mate9's Teleservice apk and the resource is "false"

**Comment by Dil3mm4** [comment]
Did you test it on true on a actual build?

Il giorno mer 30 mag 2018 alle ore 10:04 Pierre-Hugues HUSSON <
notifications@github.com> ha scritto:

**Comment by Dil3mm4** [comment]
Little Bump

**Comment by sbtourist** [comment]
Any updates on this issue?

**Comment by phhusson** [comment]
Fixed downstream with:
https://github.com/Flex1911/android_packages_services_Telephony/commit/d356bc0dee644cea3beffbd8e78f1f9a7f5a3025
@Dil3mm4 is currently working on getting it here
