### ISSUE TITLE
Vernee T3 pro no mobile data

### ISSUE THREAD

**Issue by Anatoly33** [phhusson/treble_experimentations#270]
No data is transmited over mobile network.
Data transmission works only by wifi. Voice calls via mobile network works fine.
[vernee_t3pro_log.txt](https://github.com/phhusson/treble_experimentations/files/2529746/vernee_t3pro_log.txt)

**Comment by bigrammy** [comment]
> No data is transmited over mobile network.
> Data transmission works only by wifi. Voice calls via mobile network works fine.
> [vernee_t3pro_log.txt](https://github.com/phhusson/treble_experimentations/files/2529746/vernee_t3pro_log.txt)

See here https://github.com/phhusson/treble_experimentations/issues/373 and here https://github.com/phhusson/treble_experimentations/issues/406  Hopefully a fix for you too.

**Comment by phhusson** [comment]
yeah i'm pretty sure it's fixed with https://github.com/phhusson/platform_frameworks_opt_telephony/commit/07a474ec22ecfde83a4cfb6b74f962a905c18e65

**Comment by phhusson** [comment]
yeah i'm pretty sure it's fixed with https://github.com/phhusson/platform_frameworks_opt_telephony/commit/07a474ec22ecfde83a4cfb6b74f962a905c18e65
