### ISSUE TITLE
No charge light working on Sam s9

### ISSUE THREAD

**Issue by HTAEDFOLEGNA** [phhusson/treble_experimentations#271]
Any fixes?

**Comment by phhusson** [comment]
Sorry I don't understand your issue
It looks like it's two different issues...? If so, please open two independant issues

**Comment by HTAEDFOLEGNA** [comment]
Ok I edited to make one...I fixed the other

**Comment by phhusson** [comment]
But notification led works, right?

**Comment by HTAEDFOLEGNA** [comment]
Yes


-----Original Message-----

**Comment by HTAEDFOLEGNA** [comment]
So any update on charge light

**Comment by phhusson** [comment]
Works on my S9+ so I guess it got fixed somewhere
