### ISSUE TITLE
[Huawei][MTK][Pie][Oreo] Broken GSM/CDMA signal readings

### ISSUE THREAD

**Issue by TenSeventy7** [phhusson/treble_experimentations#272]
**ROM reads mobile signal as '0 dBm 99 asu' on certain, varying network modes, affecting different devices on a varying scale.**

[**Qualcomm Huawei devices**](https://github.com/phhusson/treble_experimentations/issues/272#issuecomment-434498628)
Tested on the Huawei Y6 (2018) (ATU-L22)
> HSPA(P) is only affected
> EDGE and LTE reports correct signal values
> Radio log: [modem_atomu.log](https://github.com/phhusson/treble_experimentations/files/2531959/modem_atomu.log)

[**Certain Huawei/Honor devices with Kirin SoC**](https://github.com/phhusson/treble_experimentations/issues/272#issuecomment-434587321)
Tested on the Honor 9 (STF-L09)
> LTE seems to be affected as well
> Radio log: [radio_kirin_stf.txt](https://github.com/phhusson/treble_experimentations/files/2533169/radio_kirin_stf.txt)

**MediaTek devices on Android Pie**
Tested on: [Vernee T3 Pro (2018) (MT6739); Homtom S99 (MT6750)](https://github.com/phhusson/treble_experimentations/issues/272#issuecomment-434583129)
> Only HSPA(P) is affected

**Comment by penn5** [comment]
Check the radio logs, iirc on hi6250(y6 2018) there is the correct strength there. Or maybe it's caused by IMS (phhusson knows what I'm talking about, I am hackintosh5)

**Comment by TenSeventy7** [comment]
Triggered a modem/radio restart with airplane mode.
[modem_atomu.log](https://github.com/phhusson/treble_experimentations/files/2531959/modem_atomu.log)

**Comment by Deepflex** [comment]
VKworld VK 7000 have the same problem

**Comment by Anatoly33** [comment]
Signal strench 0 dBm 99 asu on 3G always.
Indicator of signal is gray on 3G always.
On 2G, 4G normal.
phhGSI Pie, v106
Vernee T3 Pro (2018), mt6739, android 8.1
Homtom S99 (2018), mt6750, android 8.0

**Comment by TenSeventy7** [comment]
> Honor 9 (STF-L09)
> Kirin 960
> Pixel Experience GSI Official (Oreo, based on AOSP v26 as i remember)
> [radio_kirin_stf.txt](https://github.com/phhusson/treble_experimentations/files/2533169/radio_kirin_stf.txt)
Seems that it's affecting more Huawei devices than I expected.

Can you try adding this line to prop.default (in /system/etc) and see if this fixes your issue?
`persist.sys.signal.level=openkirin`

**Comment by wavingsnow** [comment]
[radio_kirin_stf_prop_edited.txt](https://github.com/phhusson/treble_experimentations/files/2533194/radio_kirin_stf_prop_edited.txt)

**Comment by TenSeventy7** [comment]
> [radio_kirin_stf_prop_edited.txt](https://github.com/phhusson/treble_experimentations/files/2533194/radio_kirin_stf_prop_edited.txt)

It didn't work as well?

**Comment by wavingsnow** [comment]
Currently signal bar shows that signal is low
DevCheck shows incorrect values too
(btw, switching to OpenKirin mode in trebleapp didnt work for me even on AOSP v106 Pie)

**Comment by TenSeventy7** [comment]
> Signal strench 0 dBm 99 asu on 3G always.
> Indicator of signal is gray on 3G always.
> On 2G, 4G normal.
> phhGSI Pie, v106
> Vernee T3 Pro (2018), mt6739, android 8.1
> Homtom S99 (2018), mt6750, android 8.0



> VKworld VK 7000 have the same problem

Can we get a radio log?

**Comment by Anatoly33** [comment]
On stock room currently.
After half hour.

ср, 31 окт. 2018 г., 10:49 John Vincent notifications@github.com:

**Comment by TenSeventy7** [comment]
Could confirm that the signal meter is still broken on Android Pie, regardless of set signal meter reading method.

**Comment by xBrownieCodez** [comment]
@TenSeventy7 and me made a workaround for pie

**Comment by oscx** [comment]
@xBrownieCodez may we know the workaround details or commit related to the hotfix? trying to solve the issue with Oreo, too...

**Comment by xBrownieCodez** [comment]
There is no public commit @oscx

**Comment by Deepflex** [comment]
@xBrownieCodez Hello can you tell me pls how you solve it?

**Comment by penn5** [comment]
I think the invalid values (0,99) might go away with the mcc/mnc fix after #486 is resolved

**Comment by exzemat** [comment]
> Currently signal bar shows that signal is low
> DevCheck shows incorrect values too
> (btw, switching to OpenKirin mode in trebleapp didnt work for me even on AOSP v106 Pie)
hello,
I have the same problem,with phh (aosp 9, last build) or other build (havocOS by skulshady).
Since no more Android 9 new build...any solution to patch existing build to make signal meter better ?
