### ISSUE TITLE
[ Nokia 7 Plus ] SIM cards not working [ Pie ]

### ISSUE THREAD

**Issue by ricaxxh** [phhusson/treble_experimentations#276]
When you start the system for the first time you get a signal in a single slot of the SIM cards, but when you restart the signal is lost and it does not detect any more SIM card or take the MEID
[log.txt](https://github.com/phhusson/treble_experimentations/files/2553527/log.txt)

**Comment by kutiz21** [comment]
I don't know this also a thing in QUIC phones.
