### ISSUE TITLE
[Honor 7x] [Oreo] Can't install AOSP 8.1 v25 & AOSP 8.1 v26

### ISSUE THREAD

**Issue by xngnln** [phhusson/treble_experimentations#278]
It worked before AOSP 8.1 v23, but v25 & v 26 doesn't work on Honor 7X, After flashing the image, the system will loop booting.

**Comment by phhusson** [comment]
This is a very old issue, so i'm closing it.
Feel free to re-open it if needed, but then please provide logs (and ofc test on latest versions)
