### ISSUE TITLE
[Mate9] Bluetooth keeps stopping issue

### ISSUE THREAD

**Issue by feiser2016** [phhusson/treble_experimentations#28]
When update my Mate9 firmware from MHA-AL00C00B231 to MHA-AL00 8.0.0.354, after fastboot flash system-arm64-aonly-gapps-su.img, always pop up error dialog "Bluetooth keeps stopping".

**Comment by phhusson** [comment]
can you give me a logcat?

**Comment by feiser2016** [comment]
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/1946376/logcat.txt)
