### ISSUE TITLE
[Moto E5] [Pie] Graphic Glitches

### ISSUE THREAD

**Issue by MikeBv** [phhusson/treble_experimentations#280]
The rom is almost stable for Moto E5 but glitches are disgusting, so I would love to see that the issue it's fixed please, it'll be much appreciated

**Comment by Dil3mm4** [comment]
The best non-descriptive issue ever. 
Please, detail your issue and attach a:
`adb logcat -b all`

**Comment by MikeBv** [comment]
I'm using v106 because v107 is not booting

**Comment by OliverArenas** [comment]
@mikebv Can you upload your logcat, I will not be able until the other week.

**Comment by OliverArenas** [comment]
@Dil3mm4 @phhusson 
[moto e5 plus glitches.txt](https://github.com/phhusson/treble_experimentations/files/2593522/moto.e5.plus.glitches.txt)
Here I leave my logcat, I hope to help solve this.

**Comment by samsu-mbilung** [comment]
add line to buildprop "debug.hwui.renderer=opengl" without quote

**Comment by phhusson** [comment]
https://github.com/phhusson/device_phh_treble/commit/14d7c12a979c312966116fa9ce6d88ae9ae9d15c
This fixed the issue
