### ISSUE TITLE
[Xiaomi Mi 6x] boot loop

### ISSUE THREAD

**Issue by markg85** [phhusson/treble_experimentations#281]
Hi,

I had tried the v106 and v107 releases, both give me an endless android logo booting up till indefinitely.

Now i don't know the commands to execute (in adb or fastboot) to help figuring out what is wrong, if one of you can help me with the commands for me to execute?

Cheers,
Mark

**Comment by suwakowww** [comment]
mine is normal, and flashed v107 recently.
try to disable some magisk module (if you have), wipe `/data`, `/cache`, `/dalvik-cache`, or flash another "base rom" (e.g.: MIUI)

**Comment by markg85** [comment]
Hmm, it works now.
Weird thing is, i had downloaded the gapps version. But after it started working gapps apparently is only the play store. Literally everything else was not there. Anyhow, that's a issue for another time :) This specific issue is a non-issue it seems, so closing.
