### ISSUE TITLE
Issue with using build-rom.sh 

### ISSUE THREAD

**Issue by wirmpolter** [phhusson/treble_experimentations#29]
chris@Lenovo-Y50:~/RR$ bash ../treble_experimentations/build-rom.sh android-8.1 rr

Your identity is: wirmpolter <wirmpolter@gmail.com>
If you want to change this, please re-run 'repo init' with --config-name

repo has been initialized in /home/chris/RR
HEAD is now at 479fdb6 Replace frameworks_opt_telephony
HEAD is now at 479fdb6... Replace frameworks_opt_telephony
HEAD is now at 06199a5 Include missing patches
HEAD is now at 06199a5... Include missing patches
Usage: repo sync [<project>...]

main.py: error: option -j: invalid integer value: '--force-sync'

**Comment by jamuir** [comment]
since you didn't specify the number of jobs in your command, the script should have computed a value for you:

https://github.com/phhusson/treble_experimentations/blob/a80a574c8890ea25254e1d571bfedf34ec135d07/build-rom.sh#L14-L22

I think it should be `uname -s` rather than `uname -a`.

**Comment by jamuir** [comment]
I opened a PR with a fix.

**Comment by wirmpolter** [comment]
Ah, gotcha. Will definitely give it a try after when im home now that you made the adjustment/fix

**Comment by wirmpolter** [comment]
It's working now

**Comment by jamuir** [comment]
great.

this issue can be closed then.
