### ISSUE TITLE
S9 BT Issues

### ISSUE THREAD

**Issue by SePiHL** [phhusson/treble_experimentations#290]
my withings steel hr sport isn't connectable anymore through bluetooth. says it's incompatible now.. bt low energy not supported. did you change something?!

**Comment by HTAEDFOLEGNA** [comment]
I have no by issues on my s9

**Comment by phhusson** [comment]
This is a very old issue, so I'm closing it.
Feel free to re-open it and update it with logs if it's still relevant.
