### ISSUE TITLE
[Xiaomi Mi Mix 2s] Bluetooth audio not routed through cars bluetooth

### ISSUE THREAD

**Issue by rbuehlma** [phhusson/treble_experimentations#291]
If I connect the Mi Mix 2s to the car, the audio still comes out of the mobiles speaker instead of the Bluetooth system.

This was tested with AOSP 9.0 v107 and miui_MIMIX2SGlobal_8.11.8_639ab1e5de_9.0.zip as base in two different cars.

If I connect to a headphone (Bose qc35) the audio is routed correctly.

Are there any logs I can provide which would help to analyze this?

**Comment by linuxct** [comment]
Same on cheryl but audio isn't un-re-routed. Device becomes mute after trying to play music on Bluetooth Headset.
