### ISSUE TITLE
[Sony Xperia XZ1 Compact] No battery usage data

### ISSUE THREAD

**Issue by wyzco** [phhusson/treble_experimentations#296]
[framework-res.zip](https://github.com/phhusson/treble_experimentations/files/2599498/framework-res.zip)
Original Pie framework from stock Sony Rom attached
[alogcat.2018-11-20-06-55-37-0500.txt](https://github.com/phhusson/treble_experimentations/files/2599577/alogcat.2018-11-20-06-55-37-0500.txt)
[alogcat.2018-11-20-06-53-19-0500.txt](https://github.com/phhusson/treble_experimentations/files/2599578/alogcat.2018-11-20-06-53-19-0500.txt)
Full Log
[Full-logcat.txt](https://github.com/phhusson/treble_experimentations/files/2600872/Full-logcat.txt)

**Comment by phhusson** [comment]
https://forum.xda-developers.com/project-treble/trebleenabled-device-discussion/guide-how-to-make-gsis-overlay-file-t3878974
