### ISSUE TITLE
[Redmi Note 6 Pro] Screen flickering on brightness value changed

### ISSUE THREAD

**Issue by phhusson** [phhusson/treble_experimentations#299]

**Comment by phhusson** [comment]
@RedmiNote6P please provide a dump of getprop when running GSI, and also the content of /sys/class/leds/lcd-backlight/brightness

**Comment by RedmiNote6P** [comment]
The # in /sys/class/leds/lcd-backlight/brightness is 1477.

[getprop.txt](https://github.com/phhusson/treble_experimentations/files/2608449/getprop.txt)

**Comment by AryToNeX** [comment]
This can be fixed by
`# setprop persist.sys.qcom-brightness 4095`

**Comment by phhusson** [comment]
Fixed in https://github.com/phhusson/device_phh_treble/commit/453790be163c58de4bd6cc5bd54163e9a21b2217
