### ISSUE TITLE
USB-C headphones doesn't works (Huawei Mate 10 Pro)

### ISSUE THREAD

**Issue by BenDevelopment** [phhusson/treble_experimentations#3]
The USB type C headphones doesn't play any sound (I've tested with official Huawei headphones only).
The up/down volume buttons works well.
I've tried with 3.5 jack headphones with the official USB-C to 3.5 jack adapter, it works well too.

**Comment by linuxct** [comment]
Just for the sake of info., in the Razer Phone audio routing through USB Type C headphones (plus adapters) does work.

**Comment by phhusson** [comment]
As of my AOSP v15 (also included in v16), I included some USB-C changes, and it worked on my Huawei Mate 9.
Can you test on Mate 10 Pro?
This didn't work on HTC U11+. It is likely it won't work on Razer either, but could be worth the try.

**Comment by linuxct** [comment]
On my Razer phone, USB Type C headphones and adapters did work on previous versions (talking about 26-03-2018 Lineage compilation based on phh Treble Vanilla). I'll test on the latest one soon.


via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=9.8.231&pv=8.1.0&source=email_footer_2] On Mon, Apr 09, 2018 at 1:01am, Pierre-Hugues HUSSON < notifications@github.com [notifications@github.com] > wrote:
As of my AOSP v15 (also included in v16), I included some USB-C changes, and it worked on my Huawei Mate 9.
Can you test on Mate 10 Pro?
This didn't work on HTC U11+. It is likely it won't work on Razer either, but could be worth the try.

**Comment by yefonme** [comment]
Same issue on HTC U11+, is there a way or clue to fix that? I want to study and have a try,though I am not professional. :)

**Comment by phhusson** [comment]
No answer since my 9 april 2018 request for test. Closing.
