### ISSUE TITLE
[Redmi Note 6 Pro] Fix framework-res overlay

### ISSUE THREAD

**Issue by phhusson** [phhusson/treble_experimentations#300]
- Need to fix auto-brightness
- Notch support

**Comment by phhusson** [comment]
@RedmiNote6P Please provide stock rom framework-res, and a screenshot of the notch if possible, else a photo.

**Comment by RedmiNote6P** [comment]
[framework-res.zip](https://github.com/phhusson/treble_experimentations/files/2608359/framework-res.zip)

Here is the stock rom framwork-res.apk.

**Comment by RedmiNote6P** [comment]
![20181122093444](https://user-images.githubusercontent.com/45264421/48908948-df32e000-ee39-11e8-840b-4e8eec5165e7.jpg)

**Comment by RedmiNote6P** [comment]
![20181122093444](https://user-images.githubusercontent.com/45264421/48908970-efe35600-ee39-11e8-97a5-678a2a5cf688.jpg)
