### ISSUE TITLE
[Redmi Note 6 Pro] No battery usage data

### ISSUE THREAD

**Issue by RedmiNote6P** [phhusson/treble_experimentations#301]
Here is logcat&Framework-res

[logcat.txt](https://github.com/phhusson/treble_experimentations/files/2608493/logcat.txt)
[framework-res.zip](https://github.com/phhusson/treble_experimentations/files/2608535/framework-res.zip)

**Comment by OliverArenas** [comment]
Dame Moto E5 plus

**Comment by OvlTkm** [comment]
Me, too.
(Using Redmi 6 Pro)
