### ISSUE TITLE
[No Audio]FMRadio not working

### ISSUE THREAD

**Issue by Ghost5050** [phhusson/treble_experimentations#305]
FMRadio not working. Moving apk to system apps from stock firmware 8.1 MTK would give this error.
https://del.dog/ubahupumex.cc

**Comment by Ghost5050** [comment]
Thanks

**Comment by phhusson** [comment]
Meaning it works...?

**Comment by Ghost5050** [comment]
I was stuck at library error libfmjni.so but I found out one that works. I am able to open the radio app but saddly when I press play it says currently not available.

**Comment by Ghost5050** [comment]
E(  532) checkOpenStreamSampleRate(), AUDIO_DEVICE_IN_FM_TUNER, wrong sampleRate 44100, use 48000 instead.  (AudioALSAStreamIn)
E(  532) -openInputStream(), set fail, return NULL  (AudioALSAStreamManager)
E(10557) open_dev failed, [fd=-1] /dev/radio0  (android_hardware_fm)
E(10557) open_dev failed, [fd=-1] /dev/radio0  (android_hardware_fm)
E(10557) Dev open failed  (android_hardware_fm)

**Comment by Ghost5050** [comment]
``
[test.txt](https://github.com/phhusson/treble_experimentations/files/2641430/test.txt) ->FMRadio logs
