### ISSUE TITLE
Backlight slightly too dim on ATU-L21 Pie

### ISSUE THREAD

**Issue by milankragujevic** [phhusson/treble_experimentations#306]
Backlight too dim at max brightness level in UI. 

ATU-L21 Pie 9.0 AEX official Treble GSI build.

Fixed with `echo 1023 > /sys/class/leds/lcd-backlight/brightness`. Needs permanent fix. 

Output of `cat /sys/class/leds/lcd-backlight/max_brightness` : 1023

**Comment by milankragujevic** [comment]
for some reason my phone crashes when i add it's signature or I manually setprop either in the script or in root shell... SeLinux and Huawei's VNDK libs have a problem... I don't know how to fix it, I reverted build.prop back and removed the props.

**Comment by milankragujevic** [comment]
`ro.vendor.build.fingerprint` is `HUAWEI/ATU-L21/HWATU-QG:8.0.0/HUAWEIATU-L21/142(C432):user/release-keys`.

**Comment by milankragujevic** [comment]
Bump :+1:

**Comment by phhusson** [comment]
You're not giving ANY information about your crash.
How am I supposed to do anything?

**Comment by TenSeventy7** [comment]
> for some reason my phone crashes when i add it's signature or I manually setprop either in the script or in root shell... SeLinux and Huawei's VNDK libs have a problem... I don't know how to fix it, I reverted build.prop back and removed the props.

[boot_fail_brightness1023.log](https://github.com/phhusson/treble_experimentations/files/2713660/boot_fail_brightness1023.log)

**Comment by phhusson** [comment]
You didn't change anything to /vendor?
Please make a log earlier in boot, this log is missing first start

**Comment by TenSeventy7** [comment]
No changes to vendor. Logcat is executed before the device boots on my PC.

**Comment by phhusson** [comment]
Ok, then do that:
Reset to original non-crashing value:
```
# setprop persist.sys.qcom-brightness -1
```
Wait for device to actually start
```# setprop persist.sys.qcom-brightness 4093
# stop
# logcat -c
```

Start logcat section here
```# start```
Here android will restart, logcat will get enough infos before crashing
