### ISSUE TITLE
MI A2 LITE / daisy per-device basis 

### ISSUE THREAD

**Issue by ipaant** [phhusson/treble_experimentations#308]
this attach contain 

- stock ROM's system/framework/framework-res.apk
- vendor/overlay folder if it exists
- dump of getprop

from mi a2 lite / daisy 

[mi a2 lite daisy.zip](https://github.com/phhusson/treble_experimentations/files/2644069/mi.a2.lite.daisy.zip)

**Comment by TadiT7** [comment]
Close the issue, since we have the full dump and it isn't a bug report.
