### ISSUE TITLE
issues specific to the Xiaomi Mi A2 Lite

### ISSUE THREAD

**Issue by lookitsnicholas** [phhusson/treble_experimentations#312]
great job overall, just a few things:

- the fingerprint sensor registers as a volume down key
- the Smart Lock (specifically Trusted Face) feature keeps crashing
- the status bar is cut off on both sides, horizontal margins need to be increased so that the battery indicator and clock aren't hitting the bezels

**Comment by TadiT7** [comment]
>     * the status bar is cut off on both sides, horizontal margins need to be increased so that the battery indicator and clock aren't hitting the bezels

Attach a photo please

**Comment by TadiT7** [comment]
> here you go
> 
> ![screen shot 2018-12-15 at 9 25 03 pm](https://user-images.githubusercontent.com/31457277/50049301-f323d780-00af-11e9-87ae-a168b9ca0be2.png)

Measure the rounded corner radius in pixels then.

**Comment by lookitsnicholas** [comment]
What is the proper procedure to do so?

**Comment by TadiT7** [comment]
> What is the proper procedure to do so?

Measure trough mockups, for example via single pixel white line in the corners. When it sticks out, then this is the radius.

**Comment by lookitsnicholas** [comment]
Is it be possible to use the rounded corner radius that's mapped to the lock screen? The status bar appears to be fine with those parameters.
