### ISSUE TITLE
[Nokia 1] No brightness slider broken/screen only reached at 12% and no Adaptive brightness

### ISSUE THREAD

**Issue by kutiz21** [phhusson/treble_experimentations#314]
adaptive brightness does not available in both 2 vendors 00WW_0 and 00WW_1

the max brightness the phone can reached in /sys/devices/platform/leds-mt65xx/leds/lcd-backlight/max_brightness is 255

but in brightness file only got around 105

i tried the way in this issue: https://github.com/phhusson/treble_experimentations/issues/306

the property "persist.extend.brightness" makes the screen even dimmer when it's true and back in 1/2 when its false (or this property doesnt exists in build.prop. it will do the same thing.)

only vendor version 00WW_1 (Not 00WW_0) has brightness slider issue on Android 8.1 build v26 arm-a

im testing the android 9 (might also affected)

and sliding the brightness slider doesn't do anything like running android-x86 build on a virtual machine

**Comment by phhusson** [comment]
Can you try to set persist.sys.qcom-brightness to 255?

**Comment by kutiz21** [comment]
This is a MTK phone and Nokia updated the kernel and vendor so its fine now.

Dumping 255 to somewhere in /sys/class/led-brightness will make it work as
you desired but it just so fustruating. I am glad Nokia fixed this
accidentally.

For adaptive brightness I use Pixel-exclusive layer apk to enable it.

**Comment by kutiz21** [comment]
setting properties for mtk device in system properties will not work too
