### ISSUE TITLE
[Note 9 - Exynos] Keystore issues

### ISSUE THREAD

**Issue by cawilliamson** [phhusson/treble_experimentations#315]
Hi there!

I use Bitwarden as my password management app but whenever I run this on any ROM based on your work I get:

`android.security.KeyStoreException: Signature/MAC verification failed`

Any ideas? Sadly this makes my password manager completely unusable since it just crashes the app completely with this error.

Edit: I have submitted a bug report already with Bitwarden: https://github.com/bitwarden/mobile/issues/422

**Comment by phhusson** [comment]
I'm closing this issue because it is very old, I think that nowadays Keystore works.

Feel free to re-open it if it's still relevant.
