### ISSUE TITLE
[Moto G6] [Pie] Bootloop

### ISSUE THREAD

**Issue by Wabo0** [phhusson/treble_experimentations#316]
On a Moto G6, while booting v107 or v108 (`system-arm-aonly-vanilla-nosu.img`), only the "Bootloader unlocked" text is shown for a couple of seconds. Then the screen blacks out (presumably restarting),  finally showing the "Bootloader unlocked" text again. This keeps on repeating.

`adb logcat` gives no output other then "waiting for device" (presumably this loop is happening before adb is started on the phone). 

I have until now been running v106 without major problems and flashed the new system image via fastboot to upgrade. I did not wipe '/data'. (If this is a likely reason, please tell me. Setting everything up from scratch is just such a hassle, so I haven't tried it yet.)

**Comment by Uclydde** [comment]
This is happening to me as well. I formatted /data, and that didn't fix the problem.

**Comment by phhusson** [comment]
Fixed with https://github.com/phhusson/platform_frameworks_av/commit/11fa6964aa3f75d0988bdc32ba584ea3bef2b69a

**Comment by Wabo0** [comment]
A current build (including the commit/fix mentioned above) boots fine.
Thanks :)
