### ISSUE TITLE
[Samsung Galaxy A6 Plus] Touch not work after turn off the screen for 1~2 minute& mtp not working even after #225

### ISSUE THREAD

**Issue by tmvkrpxl0** [phhusson/treble_experimentations#320]
As i mentioned at title, when i turn off the screen for 1~2 minute, touch does not work until reboot android.
so i can't let its screen off for a long time
and mtp is not working. i'll try #225 //EDIT: NOT WORKING
~~and sim card is not working. it works great in stock rom.~~
~~Sim card carrier: kt                               (korea telecom)~~
~~ps. Is this rom has more power option menu? if it has, it would be more better. i want to use more ~~~~power options on power menu(ex.reboot to bootloader, reboot to recovery or etc..)~~

**Comment by phhusson** [comment]
This sounds like
https://github.com/phhusson/device_phh_treble/commit/e064c6f3107ad92f8b19891a93104d80e8482935
but it has been fixed long before your issue, so I don't really know.
Did you have magisk at that time? Magisk could interfere with my fix.

**Comment by tmvkrpxl0** [comment]
> This sounds like
> [phhusson/device_phh_treble@e064c6f](https://github.com/phhusson/device_phh_treble/commit/e064c6f3107ad92f8b19891a93104d80e8482935)
> but it has been fixed long before your issue, so I don't really know.
> Did you have magisk at that time? Magisk could interfere with my fix.

this issue was wrote long time ago,
but mtp and screen issue is same in lastest release

**Comment by phhusson** [comment]
I guess you're not answering on magisk question because you do have magisk
