### ISSUE TITLE
Xiaomi Redmi 6 Pro notch support

### ISSUE THREAD

**Issue by Dekamir** [phhusson/treble_experimentations#321]
https://i.ibb.co/zrfMGPR/photo-2018-12-09-13-59-53.jpg
Should be 40 px as reported.

**Comment by phhusson** [comment]
That's on v108 right?

**Comment by Dekamir** [comment]
https://i.ibb.co/vZk9zD0/photo-2018-12-09-15-57-21.jpg
Yep.

**Comment by hainguyents13** [comment]
Ideal height is 62px: http://imgur.com/LhvECm2

**Comment by TadiT7** [comment]
> Ideal height is 62px: http://imgur.com/LhvECm2

You measure on non-fullres image. Everything looks like the overlay just isn't applied, because the value is taken directly from Mi A2 Lite.

**Comment by TadiT7** [comment]
> @TadiT7 that's the best I can do, what should I do now sir?

Send full getprop command output

**Comment by hainguyents13** [comment]
Here it is sir: https://gist.github.com/hainguyents13/8385890e39454f619bf8ffcf26b2dbf2

**Comment by TadiT7** [comment]
> Here it is sir: https://gist.github.com/hainguyents13/8385890e39454f619bf8ffcf26b2dbf2

"android:requiredSystemPropertyValue="+*iaomi/sakura*""

So the deal is @phhusson, are we sure it does work in this way? Maybe we can put asterisks only after the keyword?

**Comment by hainguyents13** [comment]
Found myself a way to fix this, just flash any redmi 6 pro compatible rom first, and then flash gsi image, then factory reset. Boom, notch issue fixed!
