### ISSUE TITLE
Enable Widevine (DRM) in AOSP 9

### ISSUE THREAD

**Issue by AlonsoK28** [phhusson/treble_experimentations#323]
Enable Widevine (DRM) for devices in AOSP 9 to have see Streaming services (i. e. Netflix) in high video quality (1080p +)

https://www.androidauthority.com/widevine-explained-821935/

**Comment by penn5** [comment]
You can't possibly do that; the keys are erased when unlocking the bootloader and at every subsequent boot (if they magically returned somehow).
