### ISSUE TITLE
Moto G5s support

### ISSUE THREAD

**Issue by Waaflee** [phhusson/treble_experimentations#325]
Is there any chance to support this device? I'm not a "proficient" developer yet but I'll try to help as much as I can and I'll learn anything that's needed to complete this project. I'm sorry to ask via this medium but I didn't know how else I could reach you.

**Comment by phhusson** [comment]
Sorry, I don't work on porting devices to Treble.
You might try to join my telegram channel at https://t.me/phhtreble to meet other porters
