### ISSUE TITLE
Flashlight not working on Huawei ATU-L21

### ISSUE THREAD

**Issue by xBrownieCodez** [phhusson/treble_experimentations#327]
The flashlight function is greyed out and also when taking photos the flash isn't working.

**Comment by phhusson** [comment]
Can you dump the result of getprop? (on either stock rom or GSI, it doesn't matter)

**Comment by BrownieCodeException** [comment]
[getprop_dump.log](https://github.com/phhusson/treble_experimentations/files/2684110/getprop_dump.log)

**Comment by BrownieCodeException** [comment]
Here, and thanks for responding :)

**Comment by BrownieCodeException** [comment]
As the line ro.hardware is qcom on my device, I think it's the vndk detect which you posted.

**Comment by BrownieCodeException** [comment]
I tried to add these setprop values manually and it works fine now :)

**Comment by xBrownieCodez** [comment]
[vndk-detect.zip](https://github.com/phhusson/treble_experimentations/files/2696829/vndk-detect.zip)
@phhusson I think this may solve the error.
