### ISSUE TITLE
[Redmi Note 6 Pro] Fingerprint does weird things™

### ISSUE THREAD

**Issue by TadiT7** [phhusson/treble_experimentations#328]
Yeah, we should do some empty mounts, but I'm lazy and actual tulip users should be more motivated for that.

**Comment by phhusson** [comment]
You probably just want to add tulip there:
https://github.com/phhusson/device_phh_treble/blob/android-9.0/rw-system.sh#L63

Can you confirm that to match ro.vendor.build.fingerprint, xiaomi/tulip works?

**Comment by AryToNeX** [comment]
Yes, it works with stock vendor.

**Comment by phhusson** [comment]
You didn't really understand the question, but whatever, it should work anyway:
https://github.com/phhusson/device_phh_treble/commit/fdb303e941822bb98448d422782bde1ed53a9688
