### ISSUE TITLE
[Oreo vendor on P][Kirin655][PRA-**] General camera issues 

### ISSUE THREAD

**Issue by Dil3mm4** [phhusson/treble_experimentations#33]
While taking a photo in a low light environment, the camera catches up a black pic.
This should be related to a shutter latency in my opinion, since it does shoot the pic after flash turn off.
Should affect other Huawei device as well.

**Comment by phhusson** [comment]
I don't really know if we'll ever fix those sort of things, I don't expect AOSP Camera to be really usable

**Comment by Dil3mm4** [comment]
IG there's some sort of race condition here as we've experienced with
the Torch Toggle, but, honestly I dunno where to play my "cards".

There was a similar error tho on nougat for Front Camera that someone
patched, if you're interested I may found out that patch and share it
over here.

Otherwise, feel free to close this.

2018-10-03 0:36 GMT+02:00, Pierre-Hugues HUSSON <notifications@github.com>:

**Comment by Dil3mm4** [comment]
https://del.dog/etabuyamoj.diff
Camera2Test result
