### ISSUE TITLE
[HUAWEI Y6 2018 ATU-L21] CPU is always at max

### ISSUE THREAD

**Issue by xBrownieCodez** [phhusson/treble_experimentations#330]
The CPU is always at 100% which makes the battery life terrible, happens on all Treble Roms, the CPU is a Qualcomm Snapdragon 425.

Best regards.

**Comment by phhusson** [comment]
what process eats the cpu according to top?

**Comment by milankragujevic** [comment]
it is not a treble problem, it's the kernel. flash custom kernel from pascua and you will not have the issue.

**Comment by milankragujevic** [comment]
what version of the kernel?

**Comment by BrownieCodeException** [comment]
All of them, the most cause a bootloop.

**Comment by phhusson** [comment]
> @phhusson There is no process which eats the cpu but it's still at 100%
What do you mean it's always at max then?

**Comment by BrownieCodeException** [comment]
@phhusson its Always running at the max frequency

**Comment by TenSeventy7** [comment]
> 
> 
> I also tried that kernel, same issue.
> 
> @phhusson There is no process which eats the cpu but it's still at 100%

`logd` is maxing out CPU usage to 100%, in addition to the stock kernel not having dynamic values and fully relies on Huawei's PowerGenie (found on stock ROMs) to do CPU scaling.

Fixing it currently requires a custom kernel and modifications to scaling.
@xBrownieCodez join us. t.me/HwAtomu_EN

**Comment by phhusson** [comment]
> > I also tried that kernel, same issue.
> > @phhusson There is no process which eats the cpu but it's still at 100%
> 
> `logd` is maxing out CPU usage to 100%, 
He litteraly said no process eats 100% cpu.


> in addition to the stock kernel not having dynamic values and fully relies on Huawei's PowerGenie (found on stock ROMs) to do CPU scaling.
Even though this might be true (I didn't check), battery life was more than ok on all my Huawei devices.
Nowadays most of battery life savings come from idle mode, not from CPU frequency scaling.

> Fixing it currently requires a custom kernel and modifications to scaling.
> @xBrownieCodez join us. 
Free advertising, and no help (even a bug report) towards upstream? Nice.

**Comment by xBrownieCodez** [comment]
Fixed with the latest release
