### ISSUE TITLE
[Redmi Note 6 Pro] Notification led is not behaving correctly

### ISSUE THREAD

**Issue by AryToNeX** [phhusson/treble_experimentations#332]
The LED remains on/off based on boot state.
If the device is powered on, the LED stays off and is triggered normally when apps send notifications.
If the device is rebooted, it stays on and it won't turn off.
If the device is charging and the ROM supports "battery charging light" feature, the LED will not blink at all while charging.

**Comment by phhusson** [comment]
I've merged some stuff for that, I guess it's fixed now.
