### ISSUE TITLE
Settings App crashing when setting a Display Lock

### ISSUE THREAD

**Issue by xBrownieCodez** [phhusson/treble_experimentations#338]
The Settings app crashes on pie but only on when using an img made by the build tools.

Here is the log: https://pastebin.com/raw/MghBjRrY

Best regards.

**Comment by phhusson** [comment]
You mean you built your own GSI using build.sh, and you get this issue only on that?

**Comment by xBrownieCodez** [comment]
Yes.

**Comment by xBrownieCodez** [comment]
On the downloaded img it works without problems.

**Comment by xBrownieCodez** [comment]
It was my fault, i forgot to wipe the cache, sorry.
