### ISSUE TITLE
[MI8EE] Boot Loop

### ISSUE THREAD

**Issue by mozerg** [phhusson/treble_experimentations#341]
I got Boot loop after flashing the rom

**Comment by xBrownieCodez** [comment]
Did you make a factory reset and wiped the cache?

**Comment by mozerg** [comment]
Yes i did

**Comment by xBrownieCodez** [comment]
Can you connect the phone via USB Cable to your pc and make a logcat via adb?

**Comment by mozerg** [comment]
Will this work knowing that device is on bootlooop ?
