### ISSUE TITLE
[Xiaomi Mi 8 SE] Bluetooth doesn't work on pie vendor

### ISSUE THREAD

**Issue by hayspat** [phhusson/treble_experimentations#347]
It gets stuck at "Connecting..." when i try to connect to the headset.
Logs: [bluetooth.txt](https://github.com/phhusson/treble_experimentations/files/2707960/bluetooth.txt)

**Comment by hayspat** [comment]
New logs with
adb logcat -b all -c
 adb logcat -b all -d > log.txt
[logs.txt](https://github.com/phhusson/treble_experimentations/files/2713611/logs.txt)

**Comment by guglicap** [comment]
Can confirm, same issue here. 
Sometimes it does connect but audio just isn't routed to the headset (both media and calls). 
Let me know if other logs are needed.

**Comment by phhusson** [comment]
For the reference, Bluetooth works fine on Mi Mix 3 pie vendor

**Comment by guglicap** [comment]
Good to know, I'd actually like to investigate this. Do you have any idea about what this could be caused by?

**Comment by guglicap** [comment]
So, here's what I've got so far. I've compared the vendor partition on PixelExperience 19.01.11 and the one on xiaomi.eu 9.1.3 (with working bluetooth) and they're almost the same. I'll attach the diff but I don't think there's anything relevant in there. I can confirm the problem is a connection timeout, here's a snippet from `adb shell dumpsys bluetooth_manager`

`Profile: A2dpService
  mActiveDevice: null
  mDevice: 78:44:05:52:29:52
    StateMachine: name=A2dpStateMachine state=Disconnected
    mIsPlaying: false
    mCodecConfig: {codecName:SBC,mCodecType:0,mCodecPriority:1001,mSampleRate:0x1(44100),mBitsPerSample:0x1(16),mChannelMode:0x2(STEREO),mCodecSpecific1:0,mCodecSpecific2:0,mCodecSpecific3:0,mCodecSpecific4:0}
    StateMachine: name=A2dpStateMachine state=Disconnected
    StateMachineLog:
      A2dpStateMachine:
       total records=11
       rec[0]: time=02-04 21:15:47.814 processed=Disconnected org=Disconnected dest=Connecting what=1(0x1) CONNECT: arg1=0, arg2=0, obj=null
       rec[1]: time=02-04 21:15:47.833 processed=Connecting org=Connecting dest=<null> what=101(0x65) STACK_EVENT: arg1=0, arg2=0, obj=A2dpStackEvent {type:EVENT_TYPE_CONNECTION_STATE_CHANGED, device:78:44:05:52:29:52, value1:CONNECTING}
       rec[2]: time=02-04 21:15:48.092 processed=Connecting org=Connecting dest=<null> what=101(0x65) STACK_EVENT: arg1=0, arg2=0, obj=A2dpStackEvent {type:EVENT_TYPE_CODEC_CONFIG_CHANGED, device:78:44:05:52:29:52, value1:0, codecStatus:{mCodecConfig:{codecName:SBC,mCodecType:0,mCodecPriority:1001,mSampleRate:0x1(44100),mBitsPerSample:0x1(16),mChannelMode:0x2(STEREO),mCodecSpecific1:0,mCodecSpecific2:0,mCodecSpecific3:0,mCodecSpecific4:0},mCodecsLocalCapabilities:[{codecName:LDAC,mCodecType:4,mCodecPriority:5001,mSampleRate:0xf(44100|48000|88200|96000),mBitsPerSample:0x7(16|24|32),mChannelMode:0x2(STEREO),mCodecSpecific1:0,mCodecSpecific2:0,mCodecSpecific3:0,mCodecSpecific4:0}, {codecName:AAC,mCodecType:1,mCodecPriority:2001,mSampleRate:0x1(44100),mBitsPerSample:0x1(16),mChannelMode:0x2(STEREO),mCodecSpecific1:0,mCodecSpecific2:0,mCodecSpecific3:0,mCodecSpecific4:0}, {codecName:SBC,mCodecType:0,mCodecPriority:1001,mSampleRate:0x1(44100),mBitsPerSample:0x1(16),mChannelMode:0x3(MONO|STEREO),mCodecSpecific1:0,mCodecSpecific2:0,mCodecSpecific3:0,mCodecSpecific4:0}],mCodecsSelectableCapabilities:[{codecName:SBC,mCodecType:0,mCodecPriority:1001,mSampleRate:0x1(44100),mBitsPerSample:0x1(16),mChannelMode:0x3(MONO|STEREO),mCodecSpecific1:0,mCodecSpecific2:0,mCodecSpecific3:0,mCodecSpecific4:0}]}}
       rec[3]: time=02-04 21:16:17.824 processed=Connecting org=Connecting dest=<null> what=201(0xc9) CONNECT_TIMEOUT: arg1=0, arg2=0, obj=null
       rec[4]: time=02-04 21:16:17.825 processed=Connecting org=Connecting dest=Disconnected what=101(0x65) STACK_EVENT: arg1=0, arg2=0, obj=A2dpStackEvent {type:EVENT_TYPE_CONNECTION_STATE_CHANGED, device:78:44:05:52:29:52, value1:DISCONNECTED}
       rec[5]: time=02-04 21:16:17.829 processed=Disconnected org=Disconnected dest=<null> what=101(0x65) STACK_EVENT: arg1=0, arg2=0, obj=A2dpStackEvent {type:EVENT_TYPE_CONNECTION_STATE_CHANGED, device:78:44:05:52:29:52, value1:DISCONNECTED}
       rec[6]: time=02-04 21:32:06.606 processed=Disconnected org=Disconnected dest=Connecting what=101(0x65) STACK_EVENT: arg1=0, arg2=0, obj=A2dpStackEvent {type:EVENT_TYPE_CONNECTION_STATE_CHANGED, device:78:44:05:52:29:52, value1:CONNECTING}
       rec[7]: time=02-04 21:32:06.646 processed=Connecting org=Connecting dest=<null> what=101(0x65) STACK_EVENT: arg1=0, arg2=0, obj=A2dpStackEvent {type:EVENT_TYPE_CODEC_CONFIG_CHANGED, device:78:44:05:52:29:52, value1:0, codecStatus:{mCodecConfig:{codecName:SBC,mCodecType:0,mCodecPriority:1001,mSampleRate:0x1(44100),mBitsPerSample:0x1(16),mChannelMode:0x2(STEREO),mCodecSpecific1:0,mCodecSpecific2:0,mCodecSpecific3:0,mCodecSpecific4:0},mCodecsLocalCapabilities:[{codecName:LDAC,mCodecType:4,mCodecPriority:5001,mSampleRate:0xf(44100|48000|88200|96000),mBitsPerSample:0x7(16|24|32),mChannelMode:0x2(STEREO),mCodecSpecific1:0,mCodecSpecific2:0,mCodecSpecific3:0,mCodecSpecific4:0}, {codecName:AAC,mCodecType:1,mCodecPriority:2001,mSampleRate:0x1(44100),mBitsPerSample:0x1(16),mChannelMode:0x2(STEREO),mCodecSpecific1:0,mCodecSpecific2:0,mCodecSpecific3:0,mCodecSpecific4:0}, {codecName:SBC,mCodecType:0,mCodecPriority:1001,mSampleRate:0x1(44100),mBitsPerSample:0x1(16),mChannelMode:0x3(MONO|STEREO),mCodecSpecific1:0,mCodecSpecific2:0,mCodecSpecific3:0,mCodecSpecific4:0}],mCodecsSelectableCapabilities:[{codecName:SBC,mCodecType:0,mCodecPriority:1001,mSampleRate:0x1(44100),mBitsPerSample:0x1(16),mChannelMode:0x2(STEREO),mCodecSpecific1:0,mCodecSpecific2:0,mCodecSpecific3:0,mCodecSpecific4:0}]}}
       rec[8]: time=02-04 21:32:36.610 processed=Connecting org=Connecting dest=<null> what=201(0xc9) CONNECT_TIMEOUT: arg1=0, arg2=0, obj=null
       rec[9]: time=02-04 21:32:36.610 processed=Connecting org=Connecting dest=Disconnected what=101(0x65) STACK_EVENT: arg1=0, arg2=0, obj=A2dpStackEvent {type:EVENT_TYPE_CONNECTION_STATE_CHANGED, device:78:44:05:52:29:52, value1:DISCONNECTED}
       rec[10]: time=02-04 21:32:36.640 processed=Disconnected org=Disconnected dest=<null> what=101(0x65) STACK_EVENT: arg1=0, arg2=0, obj=A2dpStackEvent {type:EVENT_TYPE_CONNECTION_STATE_CHANGED, device:78:44:05:52:29:52, value1:DISCONNECTED}
      curState=Disconnected`

As you can see it's trying to connect but failing with a CONNECT_TIMEOUT error. @phhusson any chance the problem could be the dest=<null> parameter in the CONNECTING event?

**Comment by hayspat** [comment]
Try deleting /vendor/overlay/bluetoothrescommon.apk. Fixed bt headset on miui 9.1.24 vendor.

**Comment by guglicap** [comment]
doesn't work on older vendor, I'm trying to update to this newer one now.

**Comment by guglicap** [comment]
So, yeah, actually I did a clean installed based on 9.1.24 vendor (speicifically, 9.1.24 miui + xiaomi.eu 9.1.4 + PE 190111) and BL works out of the box. I didn't even have to delete /vendor/overlay/bluetoothrescommon.apk

**Comment by hayspat** [comment]
I had the exact same setup you have and bt didn't work out of the box (clean install). I'm confused now.

**Comment by phhusson** [comment]
Possibly using the various bluetooth (huawei and mediatek) workarounds in misc treble settings could work
