### ISSUE TITLE
[Honor 8/Kirin950] Reboot after loading animation

### ISSUE THREAD

**Issue by RomichForce** [phhusson/treble_experimentations#35]
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/2005939/logcat.txt)

**Comment by anayw2001** [comment]
there are a bunch of sepolicy denials which you need to fix

**Comment by phhusson** [comment]
I'ts not because there are denials, that there is anytjhing to fix.

Anyway, the issue here is:
05-15 16:58:56.099  1627  1627 E System  : java.lang.RuntimeException: IR HAL present, but FEATURE_CONSUMER_IR is not set!

Nothing hard to fix, I'll just remove the check in there.

So as a work-around, you can remove /vendor/lib64/hw/consumerir.hi3650.so

**Comment by RomichForce** [comment]
Bootloop(
[log1.txt](https://github.com/phhusson/treble_experimentations/files/2014148/log1.txt)

**Comment by anayw2001** [comment]
Failed to dlopen android.hardware.keymaster@3.0-impl.so: dlopen failed: library "libkeymaster1.so" not found

**Comment by anayw2001** [comment]
you're also missing a bunch of libs

**Comment by phhusson** [comment]
@RomichForce can you edit /vendor/manifest.xml to remove the section related to android.hardware.ir?

**Comment by linxiaoji** [comment]
can't edit /vendor/manifest.xml,otherwise it will be stuck on the first screen.

**Comment by RomichForce** [comment]
I deleted this section and the smartphone booted!
Excellent! I am very grateful to you!
But SIM cards are not detected, the camera / flashlight does not work.
Wi-Fi, it seemed to me, works somehow strangely.
[log2.txt](https://github.com/phhusson/treble_experimentations/files/2016609/log2.txt)

**Comment by linxiaoji** [comment]
Why I can't do it, please tell me how to do it

**Comment by RomichForce** [comment]
@linxiaoji, at EMUI got ROOT and changed this file.

**Comment by linxiaoji** [comment]
@RomichForce thanks ,i see

**Comment by phhusson** [comment]
Should be fixed in next version with https://github.com/phhusson/platform_frameworks_base/commit/05cfa1f6ec8dbe9e6262a738e4bbaca2e1845fab

**Comment by linxiaoji** [comment]
@RomichForce Can you send the revised document to me? I can't start it after I delete it.

**Comment by RomichForce** [comment]
@phhusson, t
[logCam.txt](https://github.com/phhusson/treble_experimentations/files/2017709/logCam.txt)
hank you so much.
And what about the mobile network and camera? If you insert the SIM card into the second slot, it is detected, but the signal is weak EDGE.
Log with the launch of the camera is attached.

**Comment by linxiaoji** [comment]
Baseband problem, 950 is double base band in China, but there is only one overseas. @RomichForce

**Comment by phhusson** [comment]
Ah you need CDMA?

**Comment by linxiaoji** [comment]
Yes, in China, we only used China Telecom CDMA.

**Comment by linxiaoji** [comment]
There are two operators respectively using GSM, td-scdma, the td-scdma LTE, WCDMA and FDD - LTE

**Comment by phhusson** [comment]
Can you check if my latest Lineage release boots without the /vendor/manifest.xml modification?
https://github.com/phhusson/treble_experimentations/releases/tag/lineage-v4

**Comment by linxiaoji** [comment]
[lineageos.txt](https://github.com/phhusson/treble_experimentations/files/2019976/lineageos.txt)
Camera does not work,Mobile network is not working,CDMA calls have no sound,A screenshot can be done in Chinese,Failure of English screenshot @phhusson

**Comment by linxiaoji** [comment]
Bluetooth is not working

**Comment by linxiaoji** [comment]
[RR.txt](https://github.com/phhusson/treble_experimentations/files/2020013/RR.txt)
This is the logcat of Resurrection Remix，It has the same bug as los, the only difference being that it can use mobile networks.

**Comment by linxiaoji** [comment]
[getprop.txt](https://github.com/phhusson/treble_experimentations/files/2020091/getprop.txt)
This is emui's getprop

**Comment by phhusson** [comment]
Please open new issues for those.
This issue is only about reboot issue.

And I guess reboot issue is fixed considering your report.

**Comment by linxiaoji** [comment]
AOSP didn't update, so I couldn't start
