### ISSUE TITLE
[IS NOT ABLE TO BOOT] Motorola G6 Play (architecture 32bits).

### ISSUE THREAD

**Issue by thayosilva** [phhusson/treble_experimentations#356]
is not able to boot into my Motorola G6 play, arm-aonly version said to be compatible with 32bit Stock architecture, but does not start.,

**Comment by thayosilva** [comment]
> Eu preciso de mais detalhes. 
> O que acontece quando você tenta inicializar? 
> Você pode obter qualquer adb logcat? 
> / proc / last_kmsg de twrp?

phhusson a Build v109 I got started on my Motorola G6 play seems like the boot problem has been solved. but the wifi is not working correctly, it gets disconnected when I'm downloading, for example, another error is that even though I registered with the ID I can not log in to Google services, I installed the GAPPs Stock of openGapps, does it have any incompatibility?

**Comment by oscx** [comment]
status update: after several retry attempts with flashing the same img again, v109 arm 32bit seems to be OK and starting now. checking it out now.

**Comment by thayosilva** [comment]
> atualização de status: depois de várias tentativas de repetição com a mesma img piscando novamente, v109 arm 32bit parece estar OK e começando agora. verificando agora.

rest assured the build v109 works 100%

**Comment by thayosilva** [comment]
> > upgrade de status: depois de várias tentativas de repetição com uma mesma img piscando novamente, v109 braço 32bit parece estar OK e começando agora. verificando agora.
> 
> tenha certeza de que o build v109 funciona 100%
