### ISSUE TITLE
htc u11+ cannot boot 

### ISSUE THREAD

**Issue by jinbolx** [phhusson/treble_experimentations#36]
This version is not work on HTC U11+.(V18)
i tried both fastboot and twrp,they are donot work
My device is stuck on android boot.

**Comment by phhusson** [comment]
Logs?

**Comment by jinbolx** [comment]
![device-2018-05-17-170742](https://user-images.githubusercontent.com/14304952/40167941-ebf3d03a-59f4-11e8-8b03-84a1d90c80db.png)
   it is on this version

  fastboot  -S 500M flash system system.img


then it is stuck on boot animation with android.



which logs should i provide?

**Comment by jinbolx** [comment]
after flash boot.img it boots now
