### ISSUE TITLE
[9.0][Honor 7A][AUM-L29] camera keeps stopping

### ISSUE THREAD

**Issue by algphello** [phhusson/treble_experimentations#360]
this is logcat 
[v107-4.txt](https://github.com/phhusson/treble_experimentations/files/2752185/v107-4.txt)

**Comment by algphello** [comment]
@phhusson 
it's look like you didn't need answer to any qst from me 
just be clear about this

**Comment by phhusson** [comment]
???
I don't understand
The issue no longer exist?

**Comment by Tarikkassy** [comment]
can you tel me the gsi rom you have flashed i want to flash it in my phone
