### ISSUE TITLE
[Question] Lineage 15 builds

### ISSUE THREAD

**Issue by franzmueller** [phhusson/treble_experimentations#361]
I'm currently looking into using Lineage 15 (I need XPosed) for my device (Redmi Note 5, Treble compatible) and am wondering if there are any issues with building Lineage 15 with latest security patches. Don't get me wrong, building the system myself wouldn't be a problem, I'm just curious if there would be any issues since the last build in the relases section of this repo is kinda dated.

**Comment by milankragujevic** [comment]
Building LineageOS 16 is completely broken, but for 15 I'm not sure. I haven't had issues building it when I tried a few months ago...

**Comment by phhusson** [comment]
yeah I think lineage 15.1 should be all right

Le dim. 13 janv. 2019 à 15:42, franzmueller <notifications@github.com> a
écrit :
