### ISSUE TITLE
[Huawei Mate SE/Honor 7x] Bluetooth App crashes when pairing

### ISSUE THREAD

**Issue by Sparticuz** [phhusson/treble_experimentations#363]
When I try to pair my watch with the phone, it FC's the Bluetooth app. 
v108 & v109, no magisk

[log2.txt](https://github.com/phhusson/treble_experimentations/files/2756551/log2.txt)

**Comment by phhusson** [comment]
@penn5 what's your recommendation there?

**Comment by penn5** [comment]
Check on v111 with the bitmask, people say the bitmask fixed the crashing.

**Comment by Sparticuz** [comment]
Still crashing for me. I know I told @penn5 I'd get a HCI log from stock, but I haven't yet.

**Comment by penn5** [comment]
I thought it just said pairing failed after the patch, no actual crash? Also it's only the mi band, no other devices have had this issue afaik.

**Comment by Sparticuz** [comment]
I have the Garmin vivosport. When I go to pair it, I click Pair new device, it shows up. I click vivosport, a second or so and the whole interface goes away, bluetooth in the 'systray' turns off then back on, then pops back up to Pair new device. FC box does not show up.

**Comment by Sparticuz** [comment]
Correction, FC did pop up after third attempt

**Comment by penn5** [comment]
Can you get a logcat of this? On mi bands the issue is that the app reports "pairing failed" but no crash occurs, so maybe you need a new issue. If you make a new issue, tag me.

**Comment by penn5** [comment]
@phhusson this is a duplicate.

**Comment by phhusson** [comment]
Treble settings now have a bluetooth workaround in misc settings where you can select huawei to fix this
