### ISSUE TITLE
Media scanning doesn't find some media on external sdcard

### ISSUE THREAD

**Issue by sellerie98** [phhusson/treble_experimentations#364]
I am currently experiencing the following issue:

Some music from my Music folder on my microsdcard is not showing up in any music player I try.
The songs do exist on the sdcard and are playable when selecting them via a file manager, they are playable with the same music player that they are not showing up in. This doesnt seem to be dependend on the file format because I have songs/interprets both in flac and mp3 that are not showing up.
I verified multiple times now that none of the directories contain a .nomedia file.
When moving music folders (regardless of file format) to the internal storage, they are immediately showing up in e.g. Odyssey.

The used release is v108 on LG G7 ThinQ, the microsd card is a sandisk 128gb card with fat32.

**Comment by phhusson** [comment]
It's fixed?

**Comment by sellerie98** [comment]
Yes, it somehow just started scanning properly again for unknown reasons. Probably a few reboots and more time.
