### ISSUE TITLE
[Zenfone 5][ZE620KL] No fingerprint support

### ISSUE THREAD

**Issue by redbaty** [phhusson/treble_experimentations#366]
It seems you can use the fingerprint sensor for navigating (A.K.A Selecting menu items by swiping on it) but there's no option to use it at the lockscreen

**Comment by Imajkej** [comment]
same for me, it is being detected in aida64 but no settings. tried a lot of roms with android 9.0, only the ones based on 8.1 vendors?? works.

**Comment by phhusson** [comment]
@Imajkej does my 8.1 GSI has it working?

Please give me a logcat of startup on GSI

**Comment by redbaty** [comment]
@phhusson I dont know if it helps, but [this one works, and apparently it is built on top of yours](https://forum.xda-developers.com/project-treble/trebleenabled-device-development/gsi-lineageos-16-0-gsi-arm64-ab-how-to-t3908029)

**Comment by Imajkej** [comment]
Currently i'm working on my own custom ROM/Device tree for ze620kl so when I will resolve my own issues I sure will help with this.
