### ISSUE TITLE
Honor View 10: Statusbar starts at 1/3 of screen and only uses about 2/3 of it

### ISSUE THREAD

**Issue by CReimer** [phhusson/treble_experimentations#371]
This behavior started with v109. Switching back to v108 fixes this for me

![screenshot_20190111-000931](https://user-images.githubusercontent.com/1853907/51492171-20e7f480-1db1-11e9-8355-edb79bc83d2d.jpg)

**Comment by penn5** [comment]
Looks like a broken notch overlay? @TadiT7?

**Comment by TadiT7** [comment]
> Looks like a broken notch overlay? @TadiT7?

@phhusson never confirmed this bug on his unit :/

**Comment by CReimer** [comment]
After a complete factory reset everything seems to be located where it should be. Closing this
