### ISSUE TITLE
I'm having issues building RR 8.1

### ISSUE THREAD

**Issue by allowthere** [phhusson/treble_experimentations#372]
I'm running `bash ../treble_experimentations/build-rom.sh android-8.1 rr` (`git rev-parse HEAD` outputs "c3b861186646f37efed8fb5b0b015f361c94a10a") and the build crashes complaining of:

    dex2oatd F 01-21 15:58:55 22217 22217 heap.cc:438] Check failed: region_space_mem_map != nullptr        No region space mem map
    Runtime aborting...
    Dumping all threads without appropriate locks held: thread list lock mutator lock

...

Finishes off with:

    [ 97% 7612/7794] Building with Jack: /...r_intermediates/with-local/classes.dex
    ninja: build stopped: subcommand failed.
    16:01:28 ninja failed with: exit status 1

Is this a RR problem or a treble_experimentations problem (am I filing it in the right place?)

**Comment by penn5** [comment]
not a treble_experimentations problem.
