### ISSUE TITLE
[Nokia 6.1 2018] No support for 4K video recording

### ISSUE THREAD

**Issue by LuukEsselbrugge** [phhusson/treble_experimentations#379]
There is no option to select 4k video (Max 1080p) with the default camera or any other third party camera app (Google camera, Opencamera). 4K video is supported by this device in third party apps on the stock Nokia rom

Currently on AOSP 9.0 v109

**Comment by TadiT7** [comment]
Probably it's fault of a media profiles xml. The problem is, there are few of them, so basically find the one with the 4k mode available and copy its content to all of the ones where it isn't, and tell the result. Ofc remember to clear the data of affected apps.

**Comment by TadiT7** [comment]
Well, sorry, simply try
```
su
setprop media.settings.xml /vendor/etc/media_profiles_vendor.xml
```
And reboot, clearing the camera apps data.

**Comment by LuukEsselbrugge** [comment]
I tried both things. I also copy paste the 1080p video profiles and edited it to have 4k settings in media_profiles.xml and cleared app data / rebooted. Only option there is 720p and 1080p

**Comment by TadiT7** [comment]
> I tried both things. I also copy paste the 1080p video profiles and edited it to have 4k settings in media_profiles.xml and cleared app data / rebooted. Only option there is 720p and 1080p

Well, please tell me the codename of this device so I'll see if there's anything special about it. On the stock ROM, are the apps being able to shoot 4k videos, or only the stock camera app?

**Comment by LuukEsselbrugge** [comment]
code name is PL2 and yes I used other apps that shot 4K video

**Comment by TadiT7** [comment]
> code name is PL2 and yes I used other apps that shot 4K video

Send the output of `dumpsys media.camera` command on AOSP GSI and uncomment this line https://github.com/TadiT7/nokia_pl2_sprout_dump/blob/aa6da1203ae814a155be5fd07d8a29c52839dc24/vendor/build.prop#L212

**Comment by LuukEsselbrugge** [comment]
Output of dumpsys media.camera attacted
Removing the comment in build.prop causes the phone to stay stuck on the "Android" logo. adding it back via ADB made it boot again
[dumpsys.txt](https://github.com/phhusson/treble_experimentations/files/2810500/dumpsys.txt)

**Comment by phhusson** [comment]
Could you provide logs of when it doesn't boot?

**Comment by theimpulson** [comment]
Got the same issue on android-10 firmware on same device. Attaching logcat of when the device boot loops: https://paste.ubuntu.com/p/BY5rbgcdW4/

**Comment by phhusson** [comment]
crash is `09-27 07:42:25.492   927   927 F MediaProfiles: frameworks/av/media/libmedia/MediaProfiles.cpp:303 CHECK(codec != -1) failed.`

Issue is that media_profiles_vendor.xml uses `lpcm` code which doesn't exist in AOSP

I'll try to see if I have a way to ignore profiles with errors. (in this case lpcm isn't even actually used!)

**Comment by phhusson** [comment]
Workaround for that precise issue in https://github.com/phhusson/platform_frameworks_av/commit/ee00227dc5ddfc88b13fa37ba96f846950c03b4e
(I reproduced it on my Razer Phone, and after this patch I can start Android with vendor media profiles)

**Comment by theimpulson** [comment]
Confirming that this works. Thanks a lot!
