### ISSUE TITLE
[Honor v8/Kirin950] 

### ISSUE THREAD

**Issue by linxiaoji** [phhusson/treble_experimentations#38]
Reboot after loading animation

**Comment by linxiaoji** [comment]
Yes, the same as 8 glory

**Comment by phhusson** [comment]
8 glory? what?

**Comment by linxiaoji** [comment]
oh！sorry！the same as honor 8

**Comment by phhusson** [comment]
well then try to remove  /vendor/lib64/hw/consumerir.hi3650.so then

**Comment by linxiaoji** [comment]
All right, I'll try

**Comment by linxiaoji** [comment]
And then give you logcat again

**Comment by linxiaoji** [comment]
After deleting remove /vendor/lib64/hw/consumerir.hi3650.so, the card is in boot animation.
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/2015290/logcat.txt)
