### ISSUE TITLE
Resurrection remix 7 Gapps

### ISSUE THREAD

**Issue by Adamsapple1** [phhusson/treble_experimentations#380]
Trying to install google apps on Official Resurrection Remix OS 7 GSI. However during flash in TWRP I get error code 70. Saying I do not have enough room in my system partition. I looked this up and it appears that there have been some problems with error code 70 on this ROM in previous versions of it (RROS 6 and up). I have followed some YouTube tutorials on it as well on how to fix it but they do not work. This makes me really sad considering I only bought this device just for custom roms and there are pretty much none on it. If anyone has a fix that actually works please let me know.

**Comment by WesleyVanNeck** [comment]
Same for on my s9+

**Comment by Adamsapple1** [comment]
Figured it out! WesleyVanNeck just flash the rom, boot into the ROM, reboot to twrp, tap mount and mount the system. Then resize the system partition
