### ISSUE TITLE
[Motorola E5] Audio Stutter while standby

### ISSUE THREAD

**Issue by XavierWrz** [phhusson/treble_experimentations#381]
Device name: Moto E5 xt1944-3
Vendor: Oreo
Aosp version: v109

PS:Happens with both local music and online music (example Spotify)
I don't have audio mods, I have only magisk installed.
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/2808919/logcat.txt)

**Comment by GripKrieger** [comment]
I have magisk installed, also no audio mods

**Comment by GripKrieger** [comment]
It would be audio effects issue??

**Comment by GripKrieger** [comment]
in v110 it's fixed, it's awesome! Thread closed.

**Comment by GripKrieger** [comment]
nope, idk why but it's happening again

**Comment by GripKrieger** [comment]
v111 latest logcat
[test.log](https://github.com/phhusson/treble_experimentations/files/2933367/test.log)

**Comment by WhatzFakiie** [comment]
[2019-07-06-16-17-02.txt](https://github.com/phhusson/treble_experimentations/files/3364992/2019-07-06-16-17-02.txt)
