### ISSUE TITLE
Xiaomi MI Pad 4 screen dpi

### ISSUE THREAD

**Issue by subbota-a** [phhusson/treble_experimentations#383]
All works fine but it seems Android doesn't know anything abount the Tablet phisical screen size. I see very big fonts and pictures like if usual phone was inlarged.
Is it possible to make the tablet work as a tablet, not as a big phone?

**Comment by phhusson** [comment]
Oh right I forgot about this.

Well, for the moment you can do adb shell wm density 240 or adb shell wm density 160 from a computer.

**Comment by subbota-a** [comment]
Thanks for the quick response! I tried, the best is 360. Will I have to execute this command after each reboot?

**Comment by phhusson** [comment]
That's persistent until factory reset

Le mar. 29 janv. 2019 à 20:17, subbota-a <notifications@github.com> a
écrit :
