### ISSUE TITLE
[Xiaomi Mi A2 Lite (Daisy)] Front camera dont work in video calls in whatsapp

### ISSUE THREAD

**Issue by dead566** [phhusson/treble_experimentations#384]
When the video call in Whatsapp, the main camera works, instead of the front one. Camera switch button does not work. Only on aosp v109 gapps-su. On other gsi everything works fine. vendor stock oreo 8.1
[whatsapp_fbcam.txt](https://github.com/phhusson/treble_experimentations/files/2814243/whatsapp_fbcam.txt)
.

**Comment by dead566** [comment]
Hal3 enabled

**Comment by suwakowww** [comment]
try to append `camera.hal1.packagelist=<package1>,<package2>......` to `/system/build.prop`
such as `com.whatsapp`

**Comment by dead566** [comment]
Wont work

**Comment by phhusson** [comment]
So you enabled hal3, or it was already enabled?
If you enabled it, please try without it since that's stock vendor.

**Comment by dead566** [comment]
@phusson Now everything is clear. If you disable the hal3 front camera is working. I tried to turn it on and off through the magisk module, as well as edit build.prop, but this did not change anything. Thus, the whole thing in the activation of hal3. On other gsis all working with hal3 enabled.

**Comment by phhusson** [comment]
It works on descendant?

**Comment by phhusson** [comment]
Don't say it's broken only on this GSI if you've tested only CAF-based
GSIs...

**Comment by dead566** [comment]
ArrowOS AOSP based
