### ISSUE TITLE
[Xiaomi Redmi S2] Wifi hotspot not working

### ISSUE THREAD

**Issue by Grant0301** [phhusson/treble_experimentations#385]
On my Xiaomi Redmi S2, I can't turn on wifi hotspot. I'm using ARM A only gapps su v109
logcat:
[log.txt](https://github.com/phhusson/treble_experimentations/files/2815329/log.txt)

**Comment by phhusson** [comment]
Did you disable treble app by any chance?

**Comment by phhusson** [comment]
The logs seem to show you disabled "treble app", and you're not saying the opposite, so I'll just close that issue.
