### ISSUE TITLE
[Xiaomi Redmi Note 7] Unable to boot

### ISSUE THREAD

**Issue by liuhxq990619** [phhusson/treble_experimentations#387]
I just flashed the latest AOSP GSI through TWRP, but my Redmi Note 7 cannot enter the boot animation. It shows the first logo display and then get shutdown.

**Comment by phhusson** [comment]
You need to use a/b arm64 variant for that device.is it what you're doing?

**Comment by liuhxq990619** [comment]
While......I take it for granted that it is an A-only device. I will try the a/b version. ThX.

**Comment by liuhxq990619** [comment]
Hey. I tried the V110 verison Android Pie. Both A/B arm64 and A-only arm64 doesn't work._

**Comment by dkmgfk** [comment]
Hello, I assume you are Chinese on the account of your username.
我用的是米8SE，刚开始也没办法启动，表现为刷入img后重启卡米。
解决方法是刷入和原来MIUI版本匹配的xiaomi.eu的boot.img。MIUI自带的boot.img似乎会验证system是不是修改过了
https://github.com/phhusson/treble_experimentations/issues/398 这个是我提的issue，里面描述了使用上的一些问题，
目前作为主力机使用中

**Comment by stevea76** [comment]
@liuhxq990619 did you manage to get the GSI to boot on the Redmi Note 7?, I have recently got a Note 7 and if working would like to know what steps you took
