### ISSUE TITLE
[Xiaomi RedMi 3][ido] Some news about incall

### ISSUE THREAD

**Issue by WinKarbik** [phhusson/treble_experimentations#388]
Hello. All GSI builds have troubles with incall. It dnt work if audio blobs compiled with AUDIO_FEATURE_ENABLED_MULTI_VOICE_SESSIONS := true
but if I delete this flag from BoardConfig and compile audio blobs, incall work only for sim where mobile data enabled. Any idea to fix?

**Comment by phhusson** [comment]
since that's not an issue with my gsi itself, I'll close this bug.
I don't have much clue about your issue, but I recommend to discuss it on my telegram channel, you might find someone who experience something similar.
