### ISSUE TITLE
[Moto E5] Dark theme doesn't work

### ISSUE THREAD

**Issue by XavierWrz** [phhusson/treble_experimentations#389]
When entering the system settings and
 then in the screen section, I choose the theme of the device, by default it is in automatic, but when I try to change it to dark, this still show white in the overall system, only in the shutdown buttons looks dark
I don't have substratum or any theme mods.

[log.txt](https://github.com/phhusson/treble_experimentations/files/2826415/log.txt)

**Comment by kikekun3008** [comment]
Happening on all devices. The dark theme only is appliying on quick settings, power menu and volume panel

**Comment by GodcraftPlata** [comment]
Dark theme is implemented in Q, in Pie is just QS Panel, Volume Slider and Power Menu. Remember this is FULLY AOSP, so is meant to be like that.
