### ISSUE TITLE
Incoming sms issue on mt6750 (vendor 8.0)

### ISSUE THREAD

**Issue by Anatoly33** [phhusson/treble_experimentations#392]
v110 gapps su on mt6750 (homtom s99), same issue with vanilla
SMS issue:
Phone (Beeline Russia)
incoming sms works:
beeline -> beeline
mts rus -> beeline
megafon -> beeline
incoming sms not works:
tele2 rus -> beeline
"can't send message with Tele2, error 96"
On stock firmware incoming sms from Tele2 to Beeline works well.

**Comment by Anatoly33** [comment]
Issue solved.
You need to manually install SMS center for Tele2.
*#*#4636#*#*
Phone information - SMSC - Set up real phone number for SMSC

**Comment by SQReder** [comment]
Tried this with megafon smsc on MT6762m (cactus) with mo sucess
