### ISSUE TITLE
Huawei P10 bootloop on V109 and V110

### ISSUE THREAD

**Issue by LuqJensen** [phhusson/treble_experimentations#394]
I tried updating from V106 to V110 but experienced bootloops.
I backtracked and confirmed that V109 also bootloops.
V106 and V108 work perfectly fine.
Specifics are Huawei P10 C432B371 with protokernel by jbolho and magisk (tried with both 17.1 and 17.3, both work with V106 and V108). Did not try with magisk 18, due to rumoured stability issues.
I think i did the adb logcat correctly, otherwise please let me know.
[Logcat](https://gist.github.com/LuqJensen/5a9489cbfe78b710f0a772b607d29ab6)

**Comment by phhusson** [comment]
What's your ro.hw.oemName?

Error seems to be
```
02-11 22:24:14.062  2226  2252 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: android.ui
02-11 22:24:14.062  2226  2252 E AndroidRuntime: android.content.res.Resources$NotFoundException: Resource ID #0x10e003a type #0x3 is not valid
02-11 22:24:14.062  2226  2252 E AndroidRuntime:        at android.content.res.Resources.getInteger(Resources.java:1100)
02-11 22:24:14.062  2226  2252 E AndroidRuntime:        at com.android.server.policy.PhoneWindowManager.init(PhoneWindowManager.java:2140)
02-11 22:24:14.062  2226  2252 E AndroidRuntime:        at com.android.server.wm.WindowManagerService$4.run(WindowManagerService.java:914)
02-11 22:24:14.062  2226  2252 E AndroidRuntime:        at android.os.Handler$BlockingRunnable.run(Handler.java:893)
02-11 22:24:14.062  2226  2252 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
02-11 22:24:14.062  2226  2252 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
02-11 22:24:14.062  2226  2252 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
02-11 22:24:14.062  2226  2252 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:65)
02-11 22:24:14.062  2226  2252 E AndroidRuntime:        at com.android.server.ServiceThread.run(ServiceThread.java:44)
02-11 22:24:14.062 2226 2252 E AndroidRuntime: at com.android.server.UiThread.run(UiThread.java:43)
```

**Comment by LuqJensen** [comment]
VTR-L29

**Comment by phhusson** [comment]
Ok, can you try v111?
I think this would be fixed by https://github.com/phhusson/vendor_hardware_overlay/commit/62b7da4a32d7c14466d4200f08c09c4f7eee877b

**Comment by LuqJensen** [comment]
Still bootloops on v111. There was a guy on XDA who had v110 running without magisk though, so maybe i just cant use that?
Heres the log after installing v111, thank you.
[https://gist.github.com/LuqJensen/3bd29f677eadd2f8db407cebbab6e471](logcat)
I also noticed this, but idk if its related
`03-08 21:36:53.396  2475  2475 D idmap   : error: no read access to /vendor/overlay: Permission denied`

**Comment by LuqJensen** [comment]
Tried v111 after magisk uninstaller and with magisk 18.1. Both bootloops

**Comment by phhusson** [comment]
Could you try to remove /data/resource-cache/ ?

**Comment by LuqJensen** [comment]
Is that not included when wiping cache and dalvik? Because I have tried that as well. If not then, sure I will try it!

**Comment by phhusson** [comment]
Yes it's included in it, so no don't do that.

Can you paste the content of /data/resource-cache/overlays.list ?

**Comment by LuqJensen** [comment]
This is on V108, is that what you need? My twrp can't decrypt data so I can't get it from >V108
'
/system/overlay/treble-overlay-NightMode.apk /data/resource-cache/system@overlay@treble-overlay-NightMode.apk@idmap
/product/overlay/frameworkResOverlay.apk /data/resource-cache/product@overlay@frameworkResOverlay.apk@idmap
/system/overlay/treble-overlay-huawei.apk /data/resource-cache/system@overlay@treble-overlay-huawei.apk@idmap
/system/overlay/treble-overlay-huawei-VTR.apk /data/resource-cache/system@overlay@treble-overlay-huawei-VTR.apk@idmap
/system/overlay/treble-overlay-webview.apk /data/resource-cache/system@overlay@treble-overlay-webview.apk@idmap
'

**Comment by phhusson** [comment]
can you attach your /product/overlay/frameworkResOverlay.apk ?

**Comment by LuqJensen** [comment]
Here it is, I placed it in a zip for GitHub to accept it
[frameworkResOverlay.zip](https://github.com/phhusson/treble_experimentations/files/2949632/frameworkResOverlay.zip)

**Comment by phhusson** [comment]
Hum, try to remove the whole /system/overlay folder?

**Comment by LuqJensen** [comment]
Before flashing?
I was under the impression that that folder is created when flashing?

**Comment by phhusson** [comment]
Flash the system image, then in twrp mount /system, remove that folder, then reboot

**Comment by LuqJensen** [comment]
[https://gist.github.com/LuqJensen/e09187583d0b4fca50af198ab3ef8e26](logcat) for v111 no /system/overlay folder.
Seems to me it now just bootloops because it cant find night mode overlay?

**Comment by LuqJensen** [comment]
Do you know of any other things i could try?

**Comment by phhusson** [comment]
I'm closing this issue because it is very old
But if it is still relevant, feel free to reopen it.
