### ISSUE TITLE
Constant crashes

### ISSUE THREAD

**Issue by kikekun3008** [phhusson/treble_experimentations#396]
Stock launcher randomly force closes when opening recents. Is like rolling a dice, you don't know either if it's gonna work or if it'll crash. Also, i see crash messages when using other apps, like Telegram X
The architecture is Arm32-binder64

**Comment by phhusson** [comment]
Logs, device, ROM version, variant

Le mar. 12 févr. 2019 à 09:16, kikekun3008 <notifications@github.com> a
écrit :
