### ISSUE TITLE
camera app fc on Galaxy A8/A8+

### ISSUE THREAD

**Issue by prashantpaddune** [phhusson/treble_experimentations#397]
https://github.com/phhusson/treble_experimentations/wiki/Samsung-Galaxy-A8-and-A8-Plus-(Exynos)

I have camera fc on Phh AOSP... i got it working on AEX build, so i used few camera libs ( attached ) for AEX and camera Fc was fixed. But that seems to be a dirty fix. Logcat and fix attached
[log.txt](https://github.com/phhusson/treble_experimentations/files/2855761/log.txt)
[Camera Fix on GSI.zip](https://github.com/phhusson/treble_experimentations/files/2855765/Camera.Fix.on.GSI.zip)

**Comment by 5pla77er** [comment]
How do I fix??
What do I do with the Zip?
