### ISSUE TITLE
Adaptive brightness

### ISSUE THREAD

**Issue by BenDevelopment** [phhusson/treble_experimentations#4]
Adaptive brightness does not seem to work.
I cannot see where to activate this feature (there isn't the "A" button next to the brightness slider).
Only tested on Huawei Mate 10 Pro.

**Comment by phhusson** [comment]
Huawei phones are missing proper framework-res overlay.
You install of your own, see for instance: https://forum.xda-developers.com/project-treble/trebleenabled-device-development/overlay-enable-night-light-adaptive-t3741965

**Comment by phhusson** [comment]
V18 includes auto backlight overlay for huawei devices
