### ISSUE TITLE
No Doze enabled 

### ISSUE THREAD

**Issue by darren3** [phhusson/treble_experimentations#40]
I have discovered my tablet doesn't enter doze state, even when using root apps Greenify of Naptime to force aggressive doze. Greenify's logs don't show any time in doze also I downloaded gsam battery monitor which shows no time in doze. I downloaded "Check Doze support" from XDA and it shows the doze config flag is not enabled. Here is a link to the app 

https://forum.xda-developers.com/android/apps-games/app-check-doze-support-t3374265/post66741976?nocache=1#post66741976#

Upon further reading at source.android.com it seems doze is not enabled on AOSP by default, but can be integrated via the framework. Here is a link 

https://source.android.com/devices/tech/power/mgmt#integrate-doze

Would it be possible for you to integrate doze in future builds? This would help extend the battery life for users of your build.

**Comment by darren3** [comment]
Upon further reading on Greenify's site doze could be enabled in the build by enabling the flag com.android.internal.R.bool.config_enableAutoPowerModes

"Aggressive Doze should work on all devices with Android 6+, unless the Doze Mode is disabled by the ROM. If you are using a custom ROM made by community, ask the 
ROM modder to enable this flag in the ROM: com.android.internal.R.bool.config_enableAutoPowerModes"

https://greenify.uservoice.com/knowledgebase/articles/828360-what-is-aggressive-doze

**Comment by phhusson** [comment]
Thanks for that.
My only worry is that not all devices have a SMD sensor

**Comment by darren3** [comment]
They can still use aggressive doze from apps like Greenify or Naptime. Root isn't even required as commands can be sent via ADB. My Nexus 10 (running a build of AOSP 8.1) doesn't have the relevant sensor's so normal doze doesn't work but aggressive doze via the apps works great.

**Comment by darren3** [comment]
If they don't have the sensor and don't enable aggressive doze the device would just work as if doze wasn't available.

**Comment by phhusson** [comment]
Current CDD has no requirement on SMD:
https://source.android.com/compatibility/8.1/android-8.1-cdd.pdf
"[SR] are STRONGLY RECOMMENDED to implement the TYPE_SIGNIFICANT_MOTION
composite sensor"

But AutoPowerModes doc indeed doesn't say anything about a SMD sensor, and my Android Go devices without a SMD has it enabled, so I'm enabling it
Thanks

**Comment by darren3** [comment]
Great thanks, I look forward to the next build.

**Comment by darren3** [comment]
Doze is working perfectly in v19. Thanks.

**Comment by phhusson** [comment]
Thanks for the confirmation
