### ISSUE TITLE
All Aosp Android Oreo Versions don't boot in J415f (Samsung J4+)

### ISSUE THREAD

**Issue by kapmino2619** [phhusson/treble_experimentations#402]
1- I tried to flash all Aosp (Android Oreo) versions  on J415f but  in vain .
----------------------------------------
2- I tried to edit  rw-system.sh as in link 
https://github.com/phhusson/device_phh_treble/commit/4484ddd7f85227b197aa7fb2e885cb8d41b61a6I
But nothing changed phone didn't boot .
----------------------------------------
**In 1& After 2  Android logo animation is the only thing appear and phone reboot to recovery .**
@phhusson  
And Thanks

**Comment by phhusson** [comment]
Give details about "doesn't boot"
Is it stuck on bootlogo? Bootanimation? Does it reboot to bootloader? To
recovery?
Do you have access to adb?

Le jeu. 14 févr. 2019 à 20:18, kapmino2619 <notifications@github.com> a
écrit :

**Comment by kapmino2619** [comment]
1- Yes,it stuck on bootlogo .
2- No,it doesn't  reboot to bootloader .
3- Yes,it reboot to recovery .(I tried reboot system  many times but phone reboot to recovery )
4- I haven't access to adb .

**Comment by kapmino2619** [comment]
@phhusson 
logcat from **reboot system** through _recovery_ until  phone auto **reboot recovery**
[logs.txt](https://github.com/phhusson/treble_experimentations/files/2867055/logs.txt)

**Comment by phhusson** [comment]
Issue based on logs is:
```
01-01 00:10:08.905   354   354 W /system/bin/hwservicemanager: getTransport: Cannot find entry android.hardware.ir@1.0::IConsumerIr/default in either framework or device manifest.
01-01 00:10:08.905  4941  4941 E System  : ******************************************
01-01 00:10:08.906  4941  4941 E System  : ************ Failure starting core service
01-01 00:10:08.906  4941  4941 E System  : java.lang.RuntimeException: FEATURE_CONSUMER_IR present, but no IR HAL loaded!
01-01 00:10:08.906  4941  4941 E System  : 	at com.android.server.ConsumerIrService.<init>(ConsumerIrService.java:51)
01-01 00:10:08.906  4941  4941 E System  : 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:798)
01-01 00:10:08.906  4941  4941 E System  : 	at com.android.server.SystemServer.run(SystemServer.java:391)
01-01 00:10:08.906  4941  4941 E System  : 	at com.android.server.SystemServer.main(SystemServer.java:267)
01-01 00:10:08.906  4941  4941 E System  : 	at java.lang.reflect.Method.invoke(Native Method)
01-01 00:10:08.906  4941  4941 E System  : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
01-01 00:10:08.906  4941  4941 E System  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:787)
```

**Comment by kapmino2619** [comment]
All is well in v110 except (simcard2,mtp,fron camera flash ) .
@phhusson
Merci beaucoup.

**Comment by kapmino2619** [comment]
ok ,How to solve it ?

**Comment by phhusson** [comment]
https://github.com/phhusson/platform_frameworks_base/commit/2a14bbf3d274949e4d6bc6bd215eb09105d5f875 should fix the issue

**Comment by kapmino2619** [comment]
@phhusson  
There is elseif 
?????????

**Comment by phhusson** [comment]
Why close?

**Comment by kapmino2619** [comment]
Ok,I opened 
many in j4+ user from  xda that they need Aosp oreo will come tocomplete with you mr phhusson .
Thanks .
But take care there is elseif  statement 
Excuse me ,
Write What should others do 
Delete it with 2 if statment or put it in new if statement  .
Thanks .

**Comment by WinKarbik** [comment]
Try add line
config.disable_consumerir=true in build.prop

**Comment by Kopra159** [comment]
In /vendor or /system

**Comment by Kopra159** [comment]
fixed it this way.
@WinKarbik 
@phhusson
Thanks
