### ISSUE TITLE
u2f dont work mithout sms and nfc(yubikey), no mobile internet. cubot kingkong3 mk6763T

### ISSUE THREAD

**Issue by lachs3677** [phhusson/treble_experimentations#403]
hi is there any solution for my smartfone?

nfc dont work
sms dont work
mobile internet dont work

king kong 3 with latest firmware. https://www.cubot.net/support/firmware/kingkong3/cubot_king_kong_3_8091c_v10_11212018.html

with unofficial twrp
https://unofficialtwrp.com/cubot-kingkong-3-root-recovery-twrp/

thanks for great work

**Comment by Skyrimus** [comment]
https://github.com/phhusson/treble_experimentations/issues/57

**Comment by phhusson** [comment]
Fixed in V111?

**Comment by Skyrimus** [comment]
phhusson, on 6735 fixed already?
