### ISSUE TITLE
Bug on redmi 3 treble with new skorpion720 vendor + AEX 6.3 unnoficiall

### ISSUE THREAD

**Issue by adoelz** [phhusson/treble_experimentations#412]
Fingerprint not work after long time must restart & sim note same with data if call not sound

**Comment by gloeyisk** [comment]
> Fingerprint not work after long time must restart & sim note same with data if call not sound

It's not the ROM issue I guess, but the vendor itself.
Tell your `vendor-enabled`'s Builder for check the current issues.

**Comment by phhusson** [comment]
Unofficial treble, and not my AOSP GSI...
