### ISSUE TITLE
No Mobile Data on Cubot X18 Plus

### ISSUE THREAD

**Issue by cg3** [phhusson/treble_experimentations#413]
Hello,

I flashed the latest system-arm64-aonly-gapps-su.img.xz (9.0 v110) on my Cubot but mobile data does not work.
WLAN is working, I got an SMS, so something is working.
I tried different modes (2G, 3G, 4G) but all result in no data.

Can I provide some logs to debug/ solve this issue?

regards,
Christian

**Comment by phhusson** [comment]
Should be fixed in V111

**Comment by cg3** [comment]
It isn't. I installed PQ2A 190305.002 but with no luck.

Can I provide any information to solves this issue?

**Comment by phhusson** [comment]
You already checked your APN?

**Comment by oscx** [comment]
@cg3 have you upgraded or flashed with latest vendor (stock) image? with an older device of the same model, i had the same problem. fixed by flashing current stock vendor image.

**Comment by cg3** [comment]
@phhusson I reseted APNs to standard, disabled mobile data and enabled fly mode. After that I activated all setting for mobile device transfer, but got no connection.

@oscx I just upgraded from v110 to v111 without stock image. I will try that and already downloaded the stock rom from cubot. Did you flashed the cubot rom and afterwards the current version from 9.0?

**Comment by oscx** [comment]
@cg3 i flashed the cubot rom's vendor image (only, no other images from stock required) and flashed the phh treble 8.1 image to the system partition with SPFlash, too. then it's been OK without SIM problems.

**Comment by cg3** [comment]
I was able to flash the original stock image to the device. Now normal operation is restored and I can use mobile data again.
Unfortunately  the device wont boot now, if I flash the v111 aonly-gapps-su image. So I cannot verify if the solution really works.
