### ISSUE TITLE
Samsung brightness control not working at all

### ISSUE THREAD

**Issue by jypixel** [phhusson/treble_experimentations#414]
Device: Galaxy A8 star (astarqlte)
Brightness slider is not working at all, brightness is always 100% ( too bright ). /sys/class/leds/lcd-backlight/brightness & /sys/class/leds/lcd-backlight/max_brightness is 365 and it don't change
However, setting value /sys/class/leds/lcd-backlight/brightness by terminal is fine, but the value changes to 365 after touching brightness slider or reboot.  
[getprop.txt](https://github.com/phhusson/treble_experimentations/files/2915362/getprop.txt)

**Comment by phhusson** [comment]
Okay, please do:
adb root
then, have the device screen on, and try the following commands, and check what happens with the brightness level:

adb shell lightsctl BACKLIGHT ff
adb shell lightsctl BACKLIGHT 80
adb shell lightsctl BACKLIGHT ff808080
adb shell lightsctl BACKLIGHT 80808080
adb shell lightsctl BACKLIGHT 3ff
adb shell lightsctl BACKLIGHT 1fff
adb shell lightsctl BACKLIGHT ff HARDWARE 0 0
adb shell lightsctl BACKLIGHT 3ff HARDWARE 0 0
adb shell lightsctl BACKLIGHT 1fff HARDWARE 0 0

**Comment by jypixel** [comment]
brightness bar says always 100% but /sys/class/leds/lcd-backlight/brightness do not
lightsctl BACKLIGHT ff ==> 28
BACKLIGHT 80 ==> 14
BACKLIGHT ff808080 ==> 128
BACKLIGHT 80808080 ==> 128
BACKLIGHT 3ff ==> 30
BACKLIGHT 1fff ==> 47
BACKLIGHT ff HARDWARE 0 0 ==> 255
BACKLIGHT 3ff HARDWARE 0 0 ==> 365
BACKLIGHT 1fff HARDWARE 0 0 ==> 365
max_brightness is 365
[brightness level.txt](https://github.com/phhusson/treble_experimentations/files/2948981/brightness.level.txt)
[log.txt](https://github.com/phhusson/treble_experimentations/files/2948982/log.txt)

**Comment by phhusson** [comment]
Okay, so if I understand the issue correctly, when you set the brightness to minimum, it should dim a bit

**Comment by phhusson** [comment]
Could you try this system image?

https://drive.google.com/open?id=1vYQxJcvRoJkgV7y9NjH1l8Kbcx5CZv3D

**Comment by jypixel** [comment]
@phhusson !! Brightness control works really well with this image

**Comment by jypixel** [comment]
Fixed on AOSP V112 releases
