### ISSUE TITLE
[Huawei P Smart - Kirin 659] Photos with flash (stock camera AOSP) are very dark, almost black

### ISSUE THREAD

**Issue by ghost** [phhusson/treble_experimentations#42]
**v18 (2018-05-14) - system.img for A-only ARM64 devices with GApps and SU**

If you take photos with flash (on stock camera AOSP) they are very dark, almost black.

**Comment by Dil3mm4** [comment]
The shutter seems to be late @phhusson, no problems found on huawei stock camera (when it decides to work :D)

**Comment by phhusson** [comment]
dupe of #33
