### ISSUE TITLE
MTK XIAOMI REDMI 6A

### ISSUE THREAD

**Issue by DeeSh1** [phhusson/treble_experimentations#427]
doesn't work outcoming calls on Xiaomi Redmi 6A

**Comment by DeeSh1** [comment]
in AOSP 8 and 9

**Comment by abhilariya** [comment]
Please delete this issue, i already posted it

**Comment by kzull** [comment]
> Please delete this issue, i already posted it

HI,
Is this issue fixed ?

**Comment by abhilariya** [comment]
> > Please delete this issue, i already posted it
> 
> HI,
> Is this issue fixed ?

No, I'm waiting for phh.

**Comment by kzull** [comment]
> > > Please delete this issue, i already posted it
> > 
> > 
> > HI,
> > Is this issue fixed ?
> 
> No, I'm waiting for phh.

Thanks by reply

**Comment by phhusson** [comment]
Dupe of #423
