### ISSUE TITLE
State of v111 on Redmi Note 5 Pro (whyred) global

### ISSUE THREAD

**Issue by utack** [phhusson/treble_experimentations#428]
Hi phhusson,

I have been experimenting with the Redmi Note 5 Pro (Global, code whyred) and your v111 of Pie
This is the current state:
![bildschirmfoto vom 2019-03-08 19-10-13](https://user-images.githubusercontent.com/8551234/54046865-da6e1e00-41d5-11e9-8681-199b98361ccb.png)

A summary:
USB MTP is dead (not a showstopper)
Encryption during boot sometimes fails, but powercycle solves it (concerning, but not a showstopper)
Full GCAM including night sight works on Miui 10.2 vendor, amazing!
Media codecs with Miui 10.2 are dead (showstopper for Miui 10.2 vendor)

I would be extremely grateful if you could attack the media codec issue, so I can use the smoother vendor and amazing GCAM.
Vendior .img and .new.dat.br can be found [here](http://en.miui.com/thread-2340434-1-1.html)
Please let me know if you need any logcats or any other help!

Best
utack

**Comment by phhusson** [comment]
I'm very surprised to hear hardware codecs are broken, that's the very
first time anyone reports that to me on any devices.
Could you give me more informations?

**Comment by utack** [comment]
Miui 10.0.6 vendor (working)
`find -name *omx* -exec md5sum {} \;
ea106d4353b8ad2feea3b434a4e16c42  ./bin/hw/android.hardware.media.omx@1.0-service
b253d428b92ff4859a97d42e540488a9  ./bin/mm-qomx-idec-test
720ce0f21bfcc9fc584ec21b9d2e142e  ./bin/mm-qomx-ienc-test
7e55382dc3aa0e426d48aaff6ee8804a  ./bin/mm-vidc-omx-test
6ca4969957983686d552ef904b15f3d2  ./etc/init/android.hardware.media.omx@1.0-service.rc
2c9a46179366035982531e65e3b935f8  ./lib/libmm-omxcore.so
bec66e17fdbd5e2bd89f7f281d11f303  ./lib/libqomx_core.so
6a8bed8520e83bdeb4452f0a38dd8cdb  ./lib/libqomx_jpegdec.so
8c81925430e336fc1144c90d8798819c  ./lib/libqomx_jpegenc.so
f8ba6aa7c5304ccbff1b42ea173d9b03  ./lib/libqomx_jpegenc_pipe.so
ee61eca846029008ec3f9483c53a8a8e  ./lib64/libmm-omxcore.so
`


Miui 10.2 vendor (broken)
I actually run into the audio problems I reported on xda again, not booting :(
No idea what triggered it, very sorry I can't reproduce what I reported above
