### ISSUE TITLE
[Huawei P Smart - Kirin 659] Sporadic Error Messages

### ISSUE THREAD

**Issue by Troyificus** [phhusson/treble_experimentations#43]
**v18 (2018-05-14) - system.img for A-only ARM64 devices with GApps and SU**

During use error messages will frequently pop up, the main two being _Bluetooth has stopped_ and _Google Play Store Service have stopped_ (not exact wording, I'll update when the error occurs again.

**Comment by JokerLedger93** [comment]
I confirm this. Sometimes one app at time goes in FC and a message is showed on screen. I can't provide logcat because the situation it's totally random.
