### ISSUE TITLE
Galaxy s9 systemui stops on latest gsi

### ISSUE THREAD

**Issue by Elcid016** [phhusson/treble_experimentations#431]
[s9+log.txt](https://github.com/phhusson/treble_experimentations/files/2954592/s9%2Blog.txt)

  
when it boots systemui stops and phone stays very slow with black screen poping system ui is not responding,on older gsi its fine

**Comment by Elcid016** [comment]
It apear to be audio bootloop becouse of missing libfloatingfeature.so but its already on vendor

**Comment by phhusson** [comment]
Well it's not missing, it's because of a hack I do that got broken

**Comment by Elcid016** [comment]
oh ok i'm geci from telegram,thx for the attention,i can expect a fix?

**Comment by Elcid016** [comment]
> Well it's not missing, it's because of a hack I do that got broken

fix will come in next release?
