### ISSUE TITLE
Samsung Qualcomm in-call audio not working

### ISSUE THREAD

**Issue by jwndud10** [phhusson/treble_experimentations#432]
Device: Samsung A8 star

Almost everything works(Data, receiving/sending message), and incoming calls /outgoing calls work with no in-call audio
calling is okay, but no in-call audio.
booting ~ calling log
[log.txt](https://github.com/phhusson/treble_experimentations/files/2956718/log.txt)
sorry for my bad english..

**Comment by phhusson** [comment]
is that a qualcomm device?

**Comment by jypixel** [comment]
@phhusson yeah based on sdm660

**Comment by jypixel** [comment]
@phhusson yes based on sdm660

**Comment by phhusson** [comment]
Could you give me a link to stock ROM system.img and vendor.img ?

**Comment by jypixel** [comment]
https://drive.google.com/open?id=1QirOFSEwTQbf-ee8X4G06i1YYQpCZsBk
stock system/vendor img

**Comment by phhusson** [comment]
can you dump the result of lshal?

**Comment by jypixel** [comment]
@phhusson dump of the rom? or dump of the stock?

**Comment by jypixel** [comment]
sorry for giving the result
the result of lshal of treble rom
[log.txt](https://github.com/phhusson/treble_experimentations/files/2966270/log.txt)

**Comment by phhusson** [comment]
that's really no problem

so, there is no vendor.qti.hardware.radio.am@1.0 (that's the HAL responsible of making in-call audio work on qualcomm devices) on GSI, while it is there in the manifest. ok
Could you try to get that result on stock rom or would that take too much time?

**Comment by jypixel** [comment]
so dump the result of lshal after reverting to stock rom? i'm now going to stock rom

**Comment by phhusson** [comment]
yes please

**Comment by jypixel** [comment]
I got dump of the stock rom(lshal) but it don't seem to have vendor.qti.hardware.radio.am@1.0 (or just my eye is problem)
here is the log
[stocklog.txt](https://github.com/phhusson/treble_experimentations/files/2966339/stocklog.txt)

**Comment by phhusson** [comment]
ok, so I hoped that the fix would be easy, but it's not. It's working the same way as S9 Snapdragon.
I'll try to work on this this week-end.

**Comment by philip4allnew** [comment]
The incall audio works just fine with csb3 vendor for S9 Snapdragon.

**Comment by jypixel** [comment]
@philip4allnew p vendor??

**Comment by philip4allnew** [comment]
Yes

**Comment by jypixel** [comment]
@phhusson Still not working on V112

**Comment by phhusson** [comment]
Fixed in latest TD
