### ISSUE TITLE
Transfer files(MTP) doesn't work on J4+ 

### ISSUE THREAD

**Issue by Kopra159** [phhusson/treble_experimentations#440]
Solution please

**Comment by kapmino2619** [comment]
@phhusson

**Comment by tak1nu** [comment]
Which kernel are you using?, far as i know, HeliosPro kernel for SM-J600x doesn't has MTP support, so if you're using a custom kernel, ask to your kernel developer

**Comment by Kopra159** [comment]
It work in twrp recovery & stock  rom .

**Comment by Kopra159** [comment]
adb push and pull will be easy

**Comment by Kopra159** [comment]
IT will be fixed , wait ................

**Comment by Kopra159** [comment]
FIIIIIIIIIIIXXXXXXXXXXXXXEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDD
👍 
https://forum.xda-developers.com/showpost.php?p=79889493&postcount=142
