### ISSUE TITLE
Brightnes always at max on Galaxy S9+

### ISSUE THREAD

**Issue by Elcid016** [phhusson/treble_experimentations#441]
On release 108 brightnes is always at max and brightnes bar does nothing, using lightsctl commands return LIGHT_NOT_SUPPORTED, and
setprop persist.sys.qcom-brightness dont work too
Its a Galaxy s9+ qualcomm star2qlte  with pie vendor csb3

**Comment by Elcid016** [comment]
in /sys/class/backlight/panel0-backlight/max_brightness i got 50000

**Comment by Elcid016** [comment]
@phhusson  ps -A |grep light
system         903     1   14992   5136 binder_thread_read  0 S vendor.samsung.hardware.light@2.0-service

**Comment by phhusson** [comment]
Could you give me your getprop ro.vendor.build.fingerprint ?

**Comment by Elcid016** [comment]
> Could you give me your getprop ro.vendor.build.fingerprint ?

samsung/star2qltezh/star2qltechn:9/PPR1.180610.011/G9650ZHS3CSC1:user/release-keys

**Comment by phhusson** [comment]
Uh is that a Chinese mainland device or Hong Kong ?
Did it come with google apps preinstalled?

**Comment by Elcid016** [comment]
its the latin american one but i think its the same as hong kong variant, and yes it comes with google

**Comment by phhusson** [comment]
Ok, good. Thanks.

**Comment by Elcid016** [comment]
Fixed thxxx so much
