### ISSUE TITLE
GoogleCamera HAL3 problems

### ISSUE THREAD

**Issue by acras01** [phhusson/treble_experimentations#442]
On arrowOS, pixeldust and rr 7.0 with pie vendor (xiaomi mi a2 lite) i can't get working gcam. Other GSI not tried but users reported the same issue.
It closes with this log. Is it GSI related?
https://hastebin.com/afonadatam.rb

**Comment by phhusson** [comment]
Why is your vendor running permissive? You're not using stock vendor?
Did you edit vendor to enable camera 2 API or was it already enabled?

**Comment by acras01** [comment]
It is manually set to permissive. I want to clear if it is not enforcing problem. Vendor is stock. Camera2api enabled via setprop manually

**Comment by phhusson** [comment]
Which setprop?

**Comment by phhusson** [comment]
Provide a full logcat, not grepped

**Comment by acras01** [comment]
setprop persist.camera.HAL3.enabled 1
setprop persist.camera.stats.test 5
setprop persist.camera.eis.enabled 1

**Comment by acras01** [comment]
Here, please
[https://hastebin.com/ewidikunax.bash](url)

**Comment by phhusson** [comment]
And does that work on stock ROM?

**Comment by acras01** [comment]
Not all gcam mods, but yes.

**Comment by acras01** [comment]
Here is the log of the same camera mod starting and capturing on stock pie rom
https://hastebin.com/uyimoxepez.coffeescript

**Comment by Mitcano7** [comment]
> setprop persist.camera.HAL3.enabled 1
> setprop persist.camera.stats.test 5
> setprop persist.camera.eis.enabled 1

i encountered same issue a while ago, try editing build.prop adding this line
`persist.vendor.camera.HAL3.enabled|=1`

that worked for me, coupled with using old version of Gcam

**Comment by acras01** [comment]
Now on arrowos. Tried both setprop options. Nothing works. Stock camera crashes, open camera and Google camera too

**Comment by Yokosa** [comment]
For me, the same problem, stock vendor pie. If we enable API 2, the opencamera/othercamera does not work properly, the picture is cropped. On stock rom, gcam is working properly, on GSI every time an error pops up, you can not connect to the camera.

Logs:
https://hastebin.com/ucehomahup.makefile
