### ISSUE TITLE
WiFi and hotspot not working on Lenovo k5 play (L38011)

### ISSUE THREAD

**Issue by Mitcano7** [phhusson/treble_experimentations#444]
Device name: Lenovo k5 play (L38011)
AOSP version: v110
Logs: http://s000.tinyupload.com/index.php?file_id=58967232003829795777
Vendor version: Oreo 8.0
Stock ROM: https://drive.google.com/uc?id=1ZWlEUsIeN_uPYvRu7ayDpvZo4nNjgAuW&export=download

Booted on my device,
Wi-Fi and hotspot not working
Camera is a bit dark, I'll try other third party camera apps.
Every other thing works fine for now, I'll keep testing.

**Comment by Mitcano7** [comment]
Tried this fix still didn't work
https://treble.phh.me/system-wifi-lenovo-k5.img
WiFi and hotspot still not working.
(If it matters, I flashed directly... without wiping anything)

**Comment by 2pferdebert** [comment]
Backup your device and do a factory reset. Sometimes old configs and chaches are cousing trouble. I did not had WiFi problems but SMS problems with my z2 pro. Try it and if it doesn't work post a logcat, maybe some skilled people will see it.

**Comment by phhusson** [comment]
@mitcano7 I need logs on the test image

**Comment by phhusson** [comment]
As far as I know, this has been fixed on the user's side
