### ISSUE TITLE
[LG G7 ThinQ] Encryption is broken, device doesnt boot without skipping it

### ISSUE THREAD

**Issue by sellerie98** [phhusson/treble_experimentations#446]
After installing the korean pie update phh AOSP does not boot but keeps showing the boot animation, waiting for some service to start.
When entering ` setprop vold.decrypt trigger_restart_framework` the device soft reboots and boots to the lockscreen, but the internal storage remains unencrypted.
Logcat:
[logcatencrypt.txt](https://github.com/phhusson/treble_experimentations/files/3004706/logcatencrypt.txt)

**Comment by phhusson** [comment]
That's not stock kernel since it is running permissive...

**Comment by sellerie98** [comment]
The kernel is stock, it's just a modified boot image and started with selinux permissive

**Comment by phhusson** [comment]
"just"
And then next thing you'll say is that you have force encrypt disabled
and then that you have magisk?

**Comment by sellerie98** [comment]
I modified that boot image myself, don't have force encrypt disabled, and I did not install Magisk.

**Comment by sellerie98** [comment]
Wait a second, magisk could actually be in that boot image, but the magisk installer wasnt installed. My bad!

**Comment by phhusson** [comment]
No update since then, I'll guess that when flashing stock boot.img it started to work again.
