### ISSUE TITLE
[Honor Kirin950 hi3650] 

### ISSUE THREAD

**Issue by linxiaoji** [phhusson/treble_experimentations#45]
[lineageos.txt](https://github.com/phhusson/treble_experimentations/files/2019976/lineageos.txt)
Camera does not work,Mobile network is not working,Bluetooth is not working,CDMA calls have no sound,A screenshot can be done in Chinese,Failure of English screenshot @phhusson

**Comment by linxiaoji** [comment]
[RR.txt](https://github.com/phhusson/treble_experimentations/files/2020013/RR.txt)
This is the logcat of Resurrection Remix，It has the same bug as los, the only difference being that it can use mobile networks.

**Comment by linxiaoji** [comment]
[getprop.txt](https://github.com/phhusson/treble_experimentations/files/2020091/getprop.txt)
This is emui's getprop

**Comment by phhusson** [comment]
That's four different issues.

**Comment by linxiaoji** [comment]
AOSP didn't update, so I couldn't start
