### ISSUE TITLE
MT6763 some problems

### ISSUE THREAD

**Issue by kluknawa235** [phhusson/treble_experimentations#454]
HI have myphone blade 2 pro (helio p23)
rom is starting but, Bluetooth app is crashing, wifi never found any network or not turn on, imei is not showing, Pc not reoagnize phone if is connected.
here is log

[2019-04-02-00-22-00.txt](https://github.com/phhusson/treble_experimentations/files/3033974/2019-04-02-00-22-00.txt)

**Comment by penn5** [comment]
Please open separate issues for each bug.

**Comment by phhusson** [comment]
as @penn5  said

**Comment by weirdal3333** [comment]
Hey the fix it to clear the data and cache from the Bluetooth app, and the imei is an issue that wouldn't have happened if you flashed it without unlocking the bootloader.

You can flash anything with spflashtool for this chipset... 
Very secure /s

**Comment by weirdal3333** [comment]
Also, read this conversation to fix your imei, the instructions *should* work on all mtk phones: https://forum.xda-developers.com/general/help/umidigi-a3-pro-twrp-stock-rom-t3879959/post78782526

**Comment by kluknawa235** [comment]
> Hey the fix it to clear the data and cache from the Bluetooth app, and the imei is an issue that wouldn't have happened if you flashed it without unlocking the bootloader.
> 
> You can flash anything with spflashtool for this chipset...
> Very secure /s

i have unlocked bootloader, a try clear daba from BT app, bud after reboot is again crashing.

**Comment by weirdal3333** [comment]
Did you force stop, clear cache and data from the app's info section? You might have to 'show system apps' to get to it. Crashes might also be happening because of 2 bluetooth apps. Get rid of the crashing one.
