### ISSUE TITLE
need altenative download links

### ISSUE THREAD

**Issue by proganime1200** [phhusson/treble_experimentations#455]
downloaded 2 times all failed need a alternative download links such as gdrive or zippysahre

**Comment by jonaaa20** [comment]
Use IDM, i don't have any problems with downloads.

**Comment by penn5** [comment]
@phhusson spam needs closing, I have no perms.

**Comment by phhusson** [comment]
dunno, could be a real issue?

**Comment by milankragujevic** [comment]
@proganime1200  what country, isp, access method (xDSL, WISP, 3G, 4G, Satellite, Cable, Fiber), exact error...?
