### ISSUE TITLE
Bootloop at Galaxy A6 plus

### ISSUE THREAD

**Issue by tmvkrpxl0** [phhusson/treble_experimentations#457]
log: https://del.dog/fofasofupi.sql
i got android boot animation, but the animation never ends
i waited more than 2 hours(and i used stock boot and stock vendor to tested it again)
what should i do now..

**Comment by phhusson** [comment]
Could you get earlier logs?
Like force reboot after just one minute of boot animation, or even 30s

**Comment by tmvkrpxl0** [comment]
> Could you get earlier logs?
> Like force reboot after just one minute of boot animation, or even 30s

sorry, this issue is solved, but i forgot to close this issue
