### ISSUE TITLE
[Mi 9] Youtube 1080p60fps video lags and stuck

### ISSUE THREAD

**Issue by linjie997** [phhusson/treble_experimentations#458]
When trying to playback a Youtube video with a resolution of 720p and 60fps, the video start lagging until it does not buffer anymore.
I tried with both Youtube Vanced and latest from Play Store

Device: Xiaomi Mi 9

Log: [log.txt](https://github.com/phhusson/treble_experimentations/files/3040189/log.txt)

**Comment by phhusson** [comment]
Reproduced with youtube-dl + NOVA Video Player:

Formats with the issue:
VP9 1080p 60fps
VP9 4k 60fps has the issue
AVC 4k 60fps

Formats without the issue:
VP9 4k 30fps

**Comment by phhusson** [comment]
Works in Google's Q public GSI DP2

**Comment by phhusson** [comment]
Works in https://ci.android.com/builds/branches/aosp-pie-gsi/grid?head=5427994&tail=5427994 (broken sound)

**Comment by phhusson** [comment]
Issue doesn't appear with software video decoding

**Comment by phhusson** [comment]
I tried adding https://android-review.googlesource.com/c/platform/frameworks/av/+/935307, but that doesn't help

**Comment by linjie997** [comment]
Downloading the same video from YT with ArkTube, it can reproduced on local. But I guess it get converted

**Comment by phhusson** [comment]
Bwarf, I failed my tests. 4k 30fps fails too.
Actually we simply never hit hardware codecs.

**Comment by phhusson** [comment]
```
[  183.387345] subsys-restart: __subsystem_get(): Changing subsys fw_name to venus
[  183.389114] subsys-pil-tz aae0000.qcom,venus: loading /vendor/firmware_mnt/image/venus.mdt failed with error -13
[  183.391146] firmware venus.mdt: _request_firmware_load: firmware state wait timeout: rc = -2
[  183.391536] subsys-pil-tz aae0000.qcom,venus: venus: Failed to locate venus.mdt(rc:-11)                                                                                                                                                                                     
[  183.391559] msm_vidc:  err: Failed to download firmware
```

**Comment by phhusson** [comment]
Fixed in https://github.com/phhusson/platform_system_core/commit/76f83565cf05abe3219fa489a6945d8a540b3bb8

Thanks for the report

**Comment by linjie997** [comment]
I can confirm it works.
Great.
