### ISSUE TITLE
Include the damn overlay for deen (Motorola One)

### ISSUE THREAD

**Issue by milankragujevic** [phhusson/treble_experimentations#462]
...

**Comment by penn5** [comment]
It's not at https://github.com/phhusson/vendor_hardware_overlay/pulls...

**Comment by milankragujevic** [comment]
https://github.com/phhusson/vendor_hardware_overlay/pull/85

**Comment by penn5** [comment]
https://github.com/phhusson/vendor_hardware_overlay/commit/e426db35989b7ca86d7318014450e08c45ee80fe
