### ISSUE TITLE
[Moto G6 Play] Getting 'Uncertified in Play Protect'

### ISSUE THREAD

**Issue by hpigula** [phhusson/treble_experimentations#464]
Hello on my Moto G6 Play I'm getting 'Uncertified in Play Protect' after installing both Vanilla arm, A-Only img as well as GApps and su version :( I wish it worked cause I can't get past initial config of phone.

Please Help.

**Comment by phhusson** [comment]
If you scroll down on that screen, it tells you how to get past this.
Just do what it says.

You can bypass Google setup wizard by pressing four corners:
Press top left then top right then bottom right then bottom left

**Comment by hpigula** [comment]
Thanks for reply will try when it boots and the I'll update.

**Comment by hpigula** [comment]
Nothing works. It says to register device but when I click on link https://g.co/AndroidDeviceRegistartion given in this screen it's just E404:not found :( Clicking corners did not work at all :(

**Comment by phhusson** [comment]
It's
https://g.co/androiddeviceregistration

And yes four corners work. Try again. You don't have to tap literally in
the corners of the screen, just few cms away from the border is fine

**Comment by hpigula** [comment]
$ adb shell 'sqlite3 /data/data/com.google.android.gsf/databases/gservices.db "select * from main where name = \"android_id\";"' 

The above won't work from link cause there is no com.google.android.gsf is on my phone according to twrp :(

**Comment by phhusson** [comment]
Do it from Android, not TWRP

**Comment by hpigula** [comment]
$ adb shell 'sqlite3 /data/data/com.google.android.gsf/databases/gservices.db "select * from main where name = \"android_id\";"'

I have no gservices.db in this folder :( folder is empty

**Comment by hpigula** [comment]
is there any other thing I can do to register without gsf?

**Comment by hpigula** [comment]
Tried other rom after all and it worked.
