### ISSUE TITLE
[9.0][nokia 6.1]There's an internal problem with your device

### ISSUE THREAD

**Issue by superiums** [phhusson/treble_experimentations#473]
when boot to desktop, shows: There's an internal problem with your device .
AOSP 9.0 v112 , on nokia 6.1.
boot.img is based on android 8.1.
[log.txt](https://github.com/phhusson/treble_experimentations/files/3071631/log.txt)

**Comment by TadiT7** [comment]
It's harmless, I don't remember the exact cause.

**Comment by superiums** [comment]
@TadiT7  thanks, is there any way to disable the warning ?

**Comment by phhusson** [comment]
I'm closing this issue because it is very old.
If it's still relevant, feel free to re-open it.

You'll need to include the result of the `adb shell vintf` command.
