### ISSUE TITLE
doesnt boot up on my oreo go

### ISSUE THREAD

**Issue by proganime1200** [phhusson/treble_experimentations#476]
i tried your other lineage os 15 with go apps a only arm working on my redmi go but when i try to use aosp 9 it doesnt bootup we need aosp 9 for oreo go devices

**Comment by phhusson** [comment]
You say you want AOSP but try lineage? I'dont understand
Does AOSP boot?

Le lun. 15 avr. 2019 à 18:33, Ralph Garcia <notifications@github.com> a
écrit :

**Comment by proganime1200** [comment]
first comment updated

**Comment by phhusson** [comment]
Oh ok that makes more sense.
Could you describe better the issue?
Like does it reboot in loop? Going back to the bootloader every time?
Does it show android boot animation?
Do you get working adb?

**Comment by proganime1200** [comment]
So first when i tried to flash aosp 9 via fastboot always says failed to flash writing split into 3 980mb size error i forgot it but when i try the lineagos15 it flash via fastboot wiothout a problem writing split 2 930mb

**Comment by proganime1200** [comment]
I remember it says file too large even it is being splitted into 3 parts i used the latest platform tools

**Comment by phhusson** [comment]
Right that's your most likely issue.
I have no recent pie version which fits into 1GB.

Let me try to make one.

**Comment by proganime1200** [comment]
I think we need a aosp 9 build only for oreo go devices  with preinstalled go apps judt like what you do in lineageos15 go

**Comment by proganime1200** [comment]
Thanks boss i want to test this aosp 9 on my new redmi go

**Comment by phhusson** [comment]
Test that:
https://treble.phh.me/system-test-20190415-arm-a.img

**Comment by proganime1200** [comment]
yes thank you i will test this feedback soon <3

**Comment by proganime1200** [comment]
btw how did you fix device not certified error on google services tried to registered it on website using google services framework android ID still stuck on device not certified cannot login google

**Comment by proganime1200** [comment]
Finally tested the aosp 9 it boots <3 but there is a graphical glitch everwhere

**Comment by proganime1200** [comment]
bro

**Comment by lexihel** [comment]
It works perfectly on a KRIP K5, an mt6580 device from a small brand known as Kriptomobile, shipped with Android 8.1 Go Edition. Everything works great so far, no bugs. Funny thing is this is Standard AOSP so I had to install the full Google Asistant and Gapps instead of the Go Edition variants.
However, it is still running smooth and flawlessly.

**Comment by proganime1200** [comment]
It works too on my redmi go with 1.2gb system storage

**Comment by kutiz21** [comment]
> Right that's your most likely issue.
> I have no recent pie version which fits into 1GB.
> 
> Let me try to make one.

Version 107 works for me. Mine is maxed out 1.3 GB

**Comment by astrayal** [comment]
Can anyone fix the link above to the treble test image.
I need it for an obscure mediatek device mt6580 android go
and when I tried to grab the image linked to here I get a 404 error

**Comment by JonnyTech** [comment]
@astrayal continue at our thread on XDA

**Comment by karllex** [comment]
alguem tem o link ? pois esse esta dando erro 404
