### ISSUE TITLE
Moto E5 Play Issues

### ISSUE THREAD

**Issue by jerzeynights** [phhusson/treble_experimentations#477]
Wifi doesn't want to turn on. Just keeps saying optaining IP address and and does nothing else. Dark mode doesn't want to turn on. Turned it on in developer settings and regular settings but still a white overlay. Brightness settings, I have to turn it on to max to see anything during the day especially when the suns out. Will any of these issues get fixed eventually? Phone is Moto E5 (James Variant). Also if you need logs, how do I get them for those particular issues?

**Comment by phhusson** [comment]
the button on which you click said "new issue"
not "give all the issues you want in just one unreadable post"

**Comment by jerzeynights** [comment]
Whoops sorry about that
