### ISSUE TITLE
Inquiry: What's the average time to build?

### ISSUE THREAD

**Issue by weirdal3333** [phhusson/treble_experimentations#482]
I have a 1-3mb/s (15MiB/s) internet connection, an averagely fast computer (64bit amd 6 cores @ 2.5ghz/core) and 8 gigs of ram.

I'm probably average in terms of people who want to start developing, but this is still downloading! It's been 3 hours. Have I done something wrong or is this normal? If so, there should be a disclaimer in the computer specs section.

**Comment by AndyCGYan** [comment]
Slow downloading has to do with your network and is not related to building. Still, 3 hours is perfectly normal - the source code download will be some 20GB or so (not sure, haven't tracked) and it will end up using ~100GB on your drive.
Also, 8GB of RAM might end up as the bottleneck when you do get to build.

**Comment by weirdal3333** [comment]
Yay it just downloaded! it used about 50gb
My external drive is ext4 and 112.8gb. It's solid state and connected via sata cables. 
Is this too little space, and can I delete anything mid-build?

**Comment by weirdal3333** [comment]
My drive is a 114.8 GB solid state drive. Is that good enough? Also, the lineage151 code downloaded about 78GB of stuff... this seems odd; my build is lineage151 arm64-aonly-gapps-nosu

**Comment by AndyCGYan** [comment]
My quad-core HDD (non-SSD) rig usually finishes a first build in 3hrs and subsequent builds (accelerated by ccache) in 1~1.5hrs.
Building itself will produce another 80~100GB of intermediates, so your SSD won't be enough either way.

**Comment by weirdal3333** [comment]
I don't know when it failed, but I didn't have ninja-build installed. It's optimizing and building  with clang++ right now. Fingers crossed!

**Comment by AndroPlus-org** [comment]
BTW official requirements for AOSP are 400GB storage and 16GB RAM:
https://source.android.com/setup/build/requirements

**Comment by weirdal3333** [comment]
It failed because of storage...
I'm compiling on a 4tb drive now, it's rather slow though. 
Started the whole process over around 4:00pm UTC yesterday. It's still checking out files... I hope it compiles faster than this!

**Comment by weirdal3333** [comment]
It's still building... 60% 62300/102486 files 😅 
I guess I'll have to wait another day or two.

There really should be a disclaimer somewhere about needing ~500 GB of drive storage and 8-16 GB of RAM. It downloaded around 80 GB of files.

**Comment by AndyCGYan** [comment]
That building time sounds wrong, even my 6-core VM setup could build Oreo in some 3 to 4 hrs without hitting ccache...

**Comment by phhusson** [comment]
They are building on HDD, that could be the issue

**Comment by AndyCGYan** [comment]
But I am on HDD too...

**Comment by penn5** [comment]
> BTW official requirements for AOSP are 400GB storage and 16GB RAM:
> https://source.android.com/setup/build/requirements

Thats really outdated.

**Comment by penn5** [comment]
> That building time sounds wrong, even my 6-core VM setup could build Oreo in some 3 to 4 hrs without hitting ccache...

My quad core with a 7200rpm HDD would never get below 12 hours. I'm pretty sure it was due to DDR2 not DDR4

**Comment by weirdal3333** [comment]
It failed because the drive went to sleep, sorry about the drop in communication. The bottleneck was ram, as well.

I added a few swap USB drives and it compiled in the regular time (4 hours 37 minutes, exactly) 😂

Thanks guys!
