### ISSUE TITLE
Android studio emulator engineering build

### ISSUE THREAD

**Issue by xjpmauricio** [phhusson/treble_experimentations#483]
I'm looking for a Android studio emulator engineering build so I can develop system apps that use the shared user id system. Where can I download them or could I do the same with a user debug build?

**Comment by penn5** [comment]
Ehm, that's irrelevant. You can build a eng for goldfish, but you can use suid system even in user as long as you sign it as platform

**Comment by phhusson** [comment]
This has been answered on XDA
