### ISSUE TITLE
Samsung Galaxy j4 with phh treble v110 arm32 binder64

### ISSUE THREAD

**Issue by Mahmuod12550** [phhusson/treble_experimentations#484]
The GSI Seems to work fine in first boot the issues are:
1-Cant connect to a Hidden WiFi 
2-Sim Card 1 & 2 doesn't work
3-Camera Doesn't Work and front camera neither (but back camera flash works fine) 
4- The Recent button doesn't work
5-phh treble v111 and v112 doesn't boot
Fixed issues:
1-I can connect to a hidden WiFi using WiFi Manager App
2-Sim Card 1 is fixed using this code in terminal:
setprop persist.sys.phh.sdk_override /vendor/bin/hw/rild=27
3-i can take photos and videos (back & front) using Google camera v4.2.0.35 but this doesn't solve the problem as I can't do video calls using Whatsapp or whatever the log file is provided in the phhusson telegram channel.
4-The Recent button is fixed thanks to phhusson by adding the code in System/keylayout/Generic.kl file:
key 254 APP_SWITCH

**Comment by phhusson** [comment]
That's not one issue.

**Comment by Mahmuod12550** [comment]
Sorry
