### ISSUE TITLE
[Redmi Go] [Screen Record] slow

### ISSUE THREAD

**Issue by proganime1200** [phhusson/treble_experimentations#488]
whenever i use screen record it the screen begins to lag unlike the stock rom

**Comment by phhusson** [comment]
No device
Title doesn't match description

**Comment by proganime1200** [comment]
i use your modified aosp9 go it boots but worse performance

**Comment by phhusson** [comment]
????
I have no AOSP 9 Go?!?

**Comment by proganime1200** [comment]
https://treble.phh.me/system-test-20190415-arm-a.img this one build yeah its not go edition

**Comment by proganime1200** [comment]
> https://treble.phh.me/system-test-20190415-arm-a.img this one build yeah its not go edition

this build that i request from this link : https://github.com/phhusson/treble_experimentations/issues/476
