### ISSUE TITLE
[Asus ZenFone Max Pro] Audio issues

### ISSUE THREAD

**Issue by SudeepDuhoon** [phhusson/treble_experimentations#49]
1. **FIXED** 3.5mm jack doesn't work - earphone not getting detected, sound plays through loudspeaker (works in aex by AryanPatidar) ** Works by installing overlay by phhusson **
2. **FIXED** In call audio doesn't work - fixed by a [patch](https://forum.xda-developers.com/devdb/project/?id=27084#downloads) ** Works in new builds without patch **
3. **FIXED** Calls goes through loudspeaker in some builds but goes through earpiece in some. ** Works fine in new builds **
4. **PARTIALLY FIXED** No audio in Bluetooth headphone in calls but works fine for played media in new builds

[logs+etc.zip](https://github.com/phhusson/treble_experimentations/files/2022535/logs.etc.zip)

Note: etc folder i attached here is from stock system.img

**Comment by phhusson** [comment]
Do you have a /vendor/overlay?

**Comment by phhusson** [comment]
Can you reboot, run adb logcat -s PHH, make a call, and give me the logs?

Oh gosh, they have no XML audio policy, wtf have they done

**Comment by SudeepDuhoon** [comment]
Logs from 2018-16-05 rr build. Audio call patch flashed to vendor only system is untouched stock
Calls work over GSM (earpiece and loudspeaker both), VoLTE is broken (out)
[rr_nopatchsystem_soundthroughearpiece(lte+gsm).txt](https://github.com/phhusson/treble_experimentations/files/2025239/rr_nopatchsystem_soundthroughearpiece.lte.gsm.txt)

yes there is /vendor/overlay with 2 overlays already there (stock)

Note: the etc folder i attached is from stock rom

**Comment by phhusson** [comment]
I didn't check, that was /system/etc or /vendor/etc?
I need the logs without the framework patch (though it's good to know that it is possible to fix it only by updating vendor)
Can you attach the vendor/overlay?

**Comment by SudeepDuhoon** [comment]
Restore to stock vendor
**Calls works fine without any patch** in 2018-16-05 rr build (both earpiece and loudspeaker)
[no_patch_call.txt](https://github.com/phhusson/treble_experimentations/files/2025536/no_patch_call.txt)


That was from system, this is from vendor

[vendor-overlay.zip](https://github.com/phhusson/treble_experimentations/files/2025518/vendor-overlay.zip)
[vendor-etc - scve(facereco)deleted.zip](https://github.com/phhusson/treble_experimentations/files/2025530/vendor-etc.-.scve.facereco.deleted.zip) (deleted fareco to upload here)
[vendor-etc.zip](https://drive.google.com/open?id=13LbgWGT0eMOxVBturSw76PF4YiNh_2EU) (complete etc folder, gdrive)

**Comment by SudeepDuhoon** [comment]
I tested the Rr again, this time without call audio patch (stock vendor)
Audio through BT is **working**  for played media but NOT for calls

**Comment by phhusson** [comment]
Wait, I didn't realize that when you said RR, it wasn't mine.
Could you link to the sources of the RR you mentioned?

**Comment by phhusson** [comment]
Could you also dump me a getprop?

**Comment by aouerfelli** [comment]
I have a similar issue where audio does not play through the headphone jack. I found an [old issue on XDA](https://forum.xda-developers.com/project-treble/trebleenabled-device-development/experimental-phh-treble-t3709659/post76086555) that sounds like this one as well, though I don't know if it was solved.

I took quick log following your suggestion [here](https://forum.xda-developers.com/project-treble/trebleenabled-device-development/experimental-phh-treble-t3709659/post76086644). I asked Google Assistant to 'say something' with speakers first, then plugged in headphones and repeated the process, then unplugged them and did the same thing again. I don't have Bluetooth headphones, so unfortunately I can't test for that.
```sh
$ [adb logcat -d | grep -C20 -iE '(alsa|usb|audio)']
```
(https://pastebin.com/TKPeepUB)

Also here's [my getprop (Huawei Honor 7X)](https://pastebin.com/YVdkLKxx)

**Comment by phhusson** [comment]
@aouerfelli Your device is honor 7x? If so, please don't hijack this thread which mentions it is on a Zenfone

**Comment by SudeepDuhoon** [comment]
sorry for delay
RR was yours only but vendor was modified by that in call audio fix patch. restored vendor to stock.
**3.5mm jack is working** by your overlay.

here is getprop
[getprop.txt](https://github.com/phhusson/treble_experimentations/files/2041376/getprop.txt)

**Comment by phhusson** [comment]
When you say in-call and earphone/speaker works, it is with my AOSP GSI v18, with stock vendor?

3.5mm should be fixed in next release with:
https://github.com/phhusson/device_phh_treble/commit/456b7b722a5ebfc30d91e0acbab2756f9e1d3532
https://github.com/phhusson/vendor_hardware_overlay/commit/302a3f2afdc7ab31a0b072c385fca84d682eb2c7

**Comment by SudeepDuhoon** [comment]
I'm on your Rr gsi 19th may build with stock vendor

https://www.google.co.in/amp/s/forum.xda-developers.com/project-treble/trebleenabled-device-development/resurrection-remix-phh-treble-t3767688/amp/

And in-call audio through Earpiece and bottom speaker both, works without any patch
3.5mm works with overlay that will be fixed by default from next builds, thanx to you

**Comment by phhusson** [comment]
well, I'm afraid earpiece/speaker switch works only on RR, not AOSP

**Comment by SudeepDuhoon** [comment]
Will flash and report in 3hrs
Thanx

**Comment by phhusson** [comment]
thanks

**Comment by SudeepDuhoon** [comment]
aosp and aosip didn't boot for me (bootloop)
tested earpiece/loudspeaker on dotos too, it worked fine
