### ISSUE TITLE
[Samsung Galaxy j4] Camera doesn't work (AOSP v110 phh treble ROM)

### ISSUE THREAD

**Issue by Mahmuod12550** [phhusson/treble_experimentations#495]
Sorry for the first issue I created (it was more than one).
In short Camera doesn't work here is the log file:
https://hastebin.com/weluxayafa.cs
Thank you for your time.

**Comment by phhusson** [comment]
Fix issue title

**Comment by Mahmuod12550** [comment]
My mistake but sorry again the title can't be edited 😅unless I close the issue and open another one

**Comment by phhusson** [comment]
Any reason this hasn't been tested on v112?

**Comment by phhusson** [comment]
Also hastebin link is dead.

**Comment by KirillMolchanov** [comment]
> Any reason this hasn't been tested on v112?

v112 boot only on kernel with Selinux: permissive and vendor 8.0
on stok kernel and vendor 8.0 or 9.0 - stuck on logo
(Sources for 9.0 kernel not yet published)

On all gsi's not work MTP and SIM-cards, stok camera is closing
log: https://pastebin.com/vyGJEawp

On others camera apps:
https://imgur.com/AdVIpef
https://imgur.com/MMNCBzA
But photo is correct
 
Thanks for your work. Sorry for my English

**Comment by Mahmuod12550** [comment]
Our device is updated now with pie vendor i can install versions 113 it is working but same issue

**Comment by phhusson** [comment]
Is it fixed?

**Comment by Mahmuod12550** [comment]
Ok the issue is closed because the camera is already fixed in havoc os gsi
