### ISSUE TITLE
stay at the second screen

### ISSUE THREAD

**Issue by SmartRu** [phhusson/treble_experimentations#499]
`[
04-11 23:16:06.670   948   948 I CamX    : [ I][NCS    ] ssc_connection.cpp:142 ssc_qmi_connection() _service_accessed 0
04-11 23:16:06.671   948  1294 I CamX    : [ I][NCS    ] camxncsintfqsee.cpp:409 operator()() Received SUID event with length 1 datatype gravity
04-11 23:16:06.671   948  1294 I CamX    : [ I][NCS    ] camxncsintfqsee.cpp:1973 SetupSensorLinkOnly() Gravity sensor available numSensors 3 Enabled sensor bitmap 0xb
04-11 23:16:06.671   948   948 E QMI_FW  : QCCI qmi_client_release_async: svc_id: 400
04-11 23:16:06.671   948   948 E QMI_FW  : QCCI qmi_client_release_async: for xport cnt= 1
04-11 23:16:06.672   948   948 E QMI_FW  : QCCI qmi_client_release_async: svc_id: 400
04-11 23:16:06.672   948   948 E QMI_FW  : QCCI qmi_client_release_async: for xport cnt= 1
04-11 23:16:06.672   948   948 I CamX    : [ I][NCS    ] ssc_connection.cpp:142 ssc_qmi_connection() _service_accessed 0
04-11 23:16:06.672   948   948 E QMI_FW  : QCCI qmi_client_release_async: svc_id: 400
04-11 23:16:06.672   948   948 E QMI_FW  : QCCI qmi_client_release_async: for xport cnt= 1
04-11 23:16:06.672   948   948 E QMI_FW  : QCCI qmi_client_release_async: svc_id: 400
04-11 23:16:06.672   948   948 E QMI_FW  : QCCI qmi_client_release_async: for xport cnt= 1
04-11 23:16:06.672   948   948 I CamX    : [ I][NCS    ] ssc_connection.cpp:142 ssc_qmi_connection() _service_accessed 0
04-11 23:16:06.672   948   948 E QMI_FW  : QCCI qmi_client_release_async: svc_id: 400
04-11 23:16:06.672   948   948 E QMI_FW  : QCCI qmi_client_release_async: for xport cnt= 1
04-11 23:16:06.672   948   948 E QMI_FW  : QCCI qmi_client_release_async: svc_id: 400
04-11 23:16:06.672   948   948 E QMI_FW  : QCCI qmi_client_release_async: for xport cnt= 1
04-11 23:16:06.672   948   948 I CamX    : [ I][NCS    ] ssc_connection.cpp:142 ssc_qmi_connection() _service_accessed 0
04-11 23:16:06.672   948   948 E QMI_FW  : QCCI qmi_client_release_async: svc_id: 400
04-11 23:16:06.672   948   948 E QMI_FW  : QCCI qmi_client_release_async: for xport cnt= 1
04-11 23:16:06.672   948   948 E QMI_FW  : QCCI qmi_client_release_async: svc_id: 400
04-11 23:16:06.672   948   948 E QMI_FW  : QCCI qmi_client_release_async: for xport cnt= 1
04-11 23:16:06.672   948   948 I CamX    : [ I][NCS    ] ssc_connection.cpp:142 ssc_qmi_connection() _service_accessed 0
04-11 23:16:06.673   948  1302 I CamX    : [ I][NCS    ] camxncsintfqsee.cpp:409 operator()() Received SUID event with length 1 datatype gyro_cal
04-11 23:16:06.673   948  1302 I CamX    : [ I][NCS    ] camxncsintfqsee.cpp:1982 SetupSensorLinkOnly() GyroCal sensor available numSensors 4 Enabled sensor bitmap 0x8b
04-11 23:16:06.673   948   948 E QMI_FW  : QCCI qmi_client_release_async: svc_id: 400
04-11 23:16:06.674   948   948 E QMI_FW  : QCCI qmi_client_release_async: for xport cnt= 1
04-11 23:16:06.674   948   948 E QMI_FW  : QCCI qmi_client_release_async: svc_id: 400
04-11 23:16:06.674   948   948 E QMI_FW  : QCCI qmi_client_release_async: for xport cnt= 1
04-11 23:16:06.674   948   948 I CamX    : [ I][NCS    ] ssc_connection.cpp:142 ssc_qmi_connection() _service_accessed 0
04-11 23:16:06.676   948  1304 I CamX    : [ I][NCS    ] camxncsintfqsee.cpp:409 operator()() Received SUID event with length 1 datatype mag_cal
04-11 23:16:06.676   948  1304 I CamX    : [ I][NCS    ] camxncsintfqsee.cpp:1991 SetupSensorLinkOnly() MagCal sensor available numSensors 5 Enabled sensor bitmap 0x18b
04-11 23:16:06.676   948   948 E QMI_FW  : QCCI qmi_client_release_async: svc_id: 400
04-11 23:16:06.676   948   948 E QMI_FW  : QCCI qmi_client_release_async: for xport cnt= 1
04-11 23:16:06.680   948   948 W CamX    : [ W][NCS    ] camxncsintfqsee.cpp:177 QueryCapabilites() Sensor 2 not probed
04-11 23:16:06.682   948   948 W CamX    : [ W][NCS    ] camxncsintfqsee.cpp:177 QueryCapabilites() Sensor 4 not probed
04-11 23:16:06.682   948   948 W CamX    : [ W][NCS    ] camxncsintfqsee.cpp:177 QueryCapabilites() Sensor 5 not probed
04-11 23:16:06.682   948   948 W CamX    : [ W][NCS    ] camxncsintfqsee.cpp:177 QueryCapabilites() Sensor 6 not probed
04-11 23:16:06.682   948   948 I CamX    : [ I][NCS    ] camxncsservice.cpp:53 Initialize() Probed a QSEE session
04-11 23:16:06.682   948   948 I CamX    : [ I][NCS    ] camxncsservice.cpp:95 Initialize() Create locks
04-11 23:16:06.682   948   948 E CamX    : [ E][UTILS  ] camxosutilslinux.cpp:833 LibMap() dlopen: dlopen failed: library "/vendor/lib64/sensors.hal.tof.so" not found, on '/vendor/lib64/sensors.hal.tof.so'
04-11 23:16:06.684   948   948 E Sensors : openInput
04-11 23:16:06.684   948   948 E Sensors : devname: /dev/input/event9
04-11 23:16:06.684   948   948 E Sensors : devname: /dev/input/event8
04-11 23:16:06.684   948   948 E Sensors : devname: /dev/input/event6
04-11 23:16:06.684   948   948 E Sensors : inputName: STM VL53L0 proximity sensor found
04-11 23:16:06.684   948   948 E Sensors : ProximitySensor::ProximitySensor gets called!
04-11 23:16:06.684   948   948 E Sensors : ProximitySensor: input_name:event6, input_sysfs_path:/sys/class/input/input6
04-11 23:16:06.684   948   948 E Sensors : ProximitySensor::enable function called for stmvl53L0!
04-11 23:16:06.684   948   948 E Sensors : ProximitySensor:: en:0, flags:0, mEnabled:0
04-11 23:16:06.685   948   948 E Sensors : ProximitySensor::enable filename:/sys/class/input/input6/enable_ps_sensor
04-11 23:16:06.685   948   948 E Sensors : ProximitySensor::enable(0) - Write 2 to enable_ps_sensor
04-11 23:16:06.685   948   948 E Sensors : ProximitySensor::enable enabled VL53L0! Error code(2 should indicate success): 2 flag 0
04-11 23:16:06.685   948   948 E Sensors : open_sensors gets called!
04-11 23:16:06.685   948   948 E CamX    : [ E][NCS    ] camxncsintfcustom.cpp:277 SetupTOFLink() Open TOF sensor module! Error - 0.
04-11 23:16:06.685   948   948 E CamX    : [ E][NCS    ] camxncsintfcustom.cpp:449 get_ldaf_input_name() inputName: STM VL53L0 proximity sensor found
04-11 23:16:06.685   948   948 I CamX    : [ I][NCS    ] camxncsintfcustom.cpp:700 GetListOfSensors() TOF sensor name: Time of Flight Proximity Sensor
04-11 23:16:06.685   948   948 I CamX    : vendor: STMicroelectronics
04-11 23:16:06.685   948   948 I CamX    : handle: 4
04-11 23:16:06.685   948   948 I CamX    : type: 40
04-11 23:16:06.685   948   948 I CamX    : maxRange: 819.000000
04-11 23:16:06.685   948   948 I CamX    : minDelay: 30000
04-11 23:16:06.685   948   948 E CamX    : [ E][NCS    ] camxncsintfcustom.cpp:56 Initialize() Probed TOF sensor !!
04-11 23:16:06.687   948   948 E CamX    : [ E][CORE   ] camxvendortags.cpp:788 VendorTagManager() Locationmap has duplicated entry!
04-11 23:16:06.687   948   948 I chatty  : uid=1047(cameraserver) provider@2.4-se identical 8 lines
04-11 23:16:06.687   948   948 E CamX    : [ E][CORE   ] camxvendortags.cpp:788 VendorTagManager() Locationmap has duplicated entry!
04-11 23:16:06.687   948   948 W CamX    : [ W][HAL    ] camxhal3module.cpp:464 HAL3Module() CHI Module library function pointers exchanged
04-11 23:16:06.688   948   948 I CamX    : [ I][HAL    ] camxchicontext.cpp:2267 InitializeStaticMetadata() Enabled multi camera 1 Logical with front 0
04-11 23:16:06.688   948   948 I chatty  : uid=1047(cameraserver) provider@2.4-se identical 1 line
04-11 23:16:06.688   948   948 I CamX    : [ I][HAL    ] camxchicontext.cpp:2267 InitializeStaticMetadata() Enabled multi camera 1 Logical with front 0
04-11 23:16:06.689   948   948 E CHIUSECASE: park_debug m_numLogicalCameras = 4, i= 0
04-11 23:16:06.689   948   948 E CHIUSECASE: park_debug logicalcam->numPhysicalCameras = 1
04-11 23:16:06.689   948   948 E CHIUSECASE: park_debug m_numLogicalCameras = 4, i= 1
04-11 23:16:06.689   948   948 E CHIUSECASE: park_debug logicalcam->numPhysicalCameras = 1
04-11 23:16:06.689   948   948 E CHIUSECASE: park_debug m_numLogicalCameras = 4, i= 2
04-11 23:16:06.689   948   948 E CHIUSECASE: park_debug logicalcam->numPhysicalCameras = 1
04-11 23:16:06.689   948   948 E CHIUSECASE: park_debug m_numLogicalCameras = 4, i= 3
04-11 23:16:06.689   948   948 E CHIUSECASE: park_debug logicalcam->numPhysicalCameras = 2
04-11 23:16:06.689   948   948 I CamProvider@2.4-impl: Loaded "QTI Camera HAL" camera module
04-11 23:16:06.690   948   948 I ServiceManagement: Removing namespace from process name android.hardware.camera.provider@2.4-service to provider@2.4-service.
04-11 23:16:06.691   948   948 I android.hardware.camera.provider@2.4-service: Registration complete for android.hardware.camera.provider@2.4::ICameraProvider/legacy/0.
04-11 23:16:09.149  1136  1151 I ssc_sensor: diag_buffering_enabled:114, DIAG Buffering mode val: 1
04-11 23:16:09.150  1136  1151 I ssc_sensor: handle_diag_settings:184, Setting SNS TX MODE to CIRCULAR BUFF
04-11 23:16:09.150  1136  1151 E Diag_Lib: diag: In diag_configure_peripheral_buffering_tx_mode, request for buffer configuring pd 9
04-11 23:16:09.150  1136  1151 E Diag_Lib: diag: In diag_configure_peripheral_buffering_tx_mode, unable to set peripheral buffering mode, ret: -1, error: 5
04-11 23:16:09.150  1136  1151 E ssc_sensor: handle_diag_settings:203, Set SNS TX MODE failed and return val: -1
04-11 23:16:09.150  1136  1151 E ssc_sensor: wait_handle_flush:128, mkfifo error: 2
04-11 23:16:13.525   951   975 E CHRE    : Couldn't connect client socket to 'chre': No such file or directory
04-11 23:16:13.525   951   975 W CHRE    : Failed to (re)connect, next try in 500 ms
04-11 23:16:14.525   951   975 E CHRE    : Couldn't connect client socket to 'chre': No such file or directory
04-11 23:16:14.525   951   975 W CHRE    : Failed to (re)connect, next try in 1000 ms
04-11 23:16:14.928  1041  1041 I tftp_server: pid=1041 tid=1041 tftp-server : INF :[tftp_server.c, 667] rcvd request [1] [72] [1] [0] [94]
04-11 23:16:14.928  1041  1309 I tftp_server: pid=1041 tid=1309 tftp-server : INF :[tftp_server_utils.c, 113] file [readwrite/mcfg.tmp] : [/vendor/rfs/msm/mpss/readwrite/mcfg.tmp]
04-11 23:16:14.928  1041  1309 I tftp_server: pid=1041 tid=1309 tftp-server : INF :[tftp_server.c, 1222] OACK options : [7680, 200, 0, 10, 0, 0, 0, 0]
04-11 23:16:14.928  1041  1309 I tftp_server: pid=1041 tid=1309 tftp-server : INF :[tftp_os_la.c, 63] open : [-1] [-1] [384] [0] [/vendor/rfs/msm/mpss/readwrite/mcfg.tmp]
04-11 23:16:14.928  1041  1309 E tftp_server: pid=1041 tid=1309 tftp-server : ERR :[tftp_os_la.c, 70] open failed: [2] [No such file or directory]
04-11 23:16:14.928  1041  1309 E tftp_server: pid=1041 tid=1309 tftp-server : ERR :[tftp_server.c, 1718] open failed : [-2] [Unknown error -2]
04-11 23:16:14.928  1041  1309 E tftp_server: pid=1041 tid=1309 tftp-server : ERR :[tftp_protocol.c, 1229] sending error-pkt. Code = 1, Msg = Err=2 String=No such file or directory
04-11 23:16:14.929  1041  1041 I tftp_server: pid=1041 tid=1041 tftp-server : INF :[tftp_server.c, 667] rcvd request [1] [64] [2] [0] [95]
04-11 23:16:14.929  1041  1310 I tftp_server: pid=1041 tid=1310 tftp-server : INF :[tftp_server_utils.c, 113] file [readwrite/mcfg.tmp] : [/vendor/rfs/msm/mpss/readwrite/mcfg.tmp]
04-11 23:16:14.929  1041  1310 I tftp_server: pid=1041 tid=1310 tftp-server : INF :[tftp_server.c, 1222] OACK options : [7680, 200, 10, 0, 0, 0, 0, 0]
04-11 23:16:14.929  1041  1310 I tftp_server: pid=1041 tid=1310 tftp-server : INF :[tftp_server.c, 893] Using temp file[/vendor/rfs/msm/mpss/readwrite/mcfg.tmp.rfs_tmp] for atomic put
04-11 23:16:14.929  1041  1310 I tftp_server: pid=1041 tid=1310 tftp-server : INF :[tftp_os_la.c, 63] open : [-1] [-1] [384] [577] [/vendor/rfs/msm/mpss/readwrite/mcfg.tmp.rfs_tmp]
04-11 23:16:14.933  1041  1310 I tftp_server: pid=1041 tid=1310 tftp-server : INF :[tftp_server.c, 1500] WRQ stats : total-blocks = 1 : total-bytes = 1 : 1 timedout-pkts = 0, wrong-pkts = 0
04-11 23:16:14.933  1041  1310 I tftp_server: pid=1041 tid=1310 tftp-server : INF :[tftp_server.c, 1504] WRQ time stats : Total : [TX, RX] = [40, 441, 10]
04-11 23:16:14.933  1041  1310 I tftp_server: pid=1041 tid=1310 tftp-server : INF :[tftp_server.c, 1508] WRQ time stats : Tx [Min, Max] = [20, 20]
04-11 23:16:14.933  1041  1310 I tftp_server: pid=1041 tid=1310 tftp-server : INF :[tftp_server.c, 1512] WRQ time stats : Rx [Min, Max] = [197, 244]
04-11 23:16:14.933  1041  1041 I tftp_server: pid=1041 tid=1041 tftp-server : INF :[tftp_server.c, 667] rcvd request [1] [72] [1] [0] [96]
04-11 23:16:14.933  1041  1311 I tftp_server: pid=1041 tid=1311 tftp-server : INF :[tftp_server_utils.c, 113] file [readwrite/mcfg.tmp] : [/vendor/rfs/msm/mpss/readwrite/mcfg.tmp]
04-11 23:16:14.933  1041  1311 I tftp_server: pid=1041 tid=1311 tftp-server : INF :[tftp_server.c, 1222] OACK options : [7680, 200, 1, 10, 0, 0, 0, 0]
04-11 23:16:14.933  1041  1311 I tftp_server: pid=1041 tid=1311 tftp-server : INF :[tftp_os_la.c, 63] open : [-1] [-1] [384] [0] [/vendor/rfs/msm/mpss/readwrite/mcfg.tmp]
04-11 23:16:14.933  1041  1311 I tftp_server: pid=1041 tid=1311 tftp-server : INF :[tftp_protocol.c, 742] Recd END OF TRANSFER pkt. Code = 9, Msg = End of Transfer
04-11 23:16:14.933  1041  1311 I tftp_server: pid=1041 tid=1311 tftp-server : INF :[tftp_server.c, 1330] RRQ stats : sent_size = 0 total-blocks = 0 total-bytes = 0 timedout-pkts = 0, wrong-pkts = 0
04-11 23:16:14.933  1041  1311 I tftp_server: pid=1041 tid=1311 tftp-server : INF :[tftp_server.c, 1334] RRQ time stats : Total : [TX, RX] = [17, 159]
04-11 23:16:14.933  1041  1311 I tftp_server: pid=1041 tid=1311 tftp-server : INF :[tftp_server.c, 1340] RRQ time stats : Tx/Rx [Min, Max] = [17, 17, 159, 159]
04-11 23:16:14.933  1041  1311 I tftp_server: pid=1041 tid=1311 tftp-server : INF :[tftp_server.c, 1356] RRQ was successfully processed.
04-11 23:16:14.934  1041  1041 I tftp_server: pid=1041 tid=1041 tftp-server : INF :[tftp_server.c, 667] rcvd request [1] [37] [2] [0] [97]
04-11 23:16:14.934  1041  1312 I tftp_server: pid=1041 tid=1312 tftp-server : INF :[tftp_server_utils.c, 113] file [readwrite/mcfg.tmp] : [/vendor/rfs/msm/mpss/readwrite/mcfg.tmp]
04-11 23:16:14.934  1041  1312 I tftp_server: pid=1041 tid=1312 tftp-server : INF :[tftp_server.c, 1222] OACK options : [0, 0, 0, 0, 0, 0, 0, 0]
04-11 23:16:14.934  1041  1312 I tftp_server: pid=1041 tid=1312 tftp-server : INF :[tftp_server.c, 1589] unlink was success
04-11 23:16:14.935  1041  1041 I tftp_server: pid=1041 tid=1041 tftp-server : INF :[tftp_server.c, 667] rcvd request [1] [94] [1] [0] [98]
04-11 23:16:14.935  1041  1313 I tftp_server: pid=1041 tid=1313 tftp-server : INF :[tftp_server_utils.c, 113] file [readonly/modem_config/mcfg_hw/mbn_hw.dig] : [/vendor/rfs/msm/mpss/readonly/modem_config/
04-11 23:16:14.935  1041  1313 I tftp_server: pid=1041 tid=1313 tftp-server : INF :[tftp_server.c, 1222] OACK options : [7680, 200, 0, 10, 0, 0, 0, 0]
04-11 23:16:14.935  1041  1313 I tftp_server: pid=1041 tid=1313 tftp-server : INF :[tftp_os_la.c, 63] open : [-1] [-1] [384] [0] [/vendor/rfs/msm/mpss/readonly/modem_config/mcfg_hw/mbn_hw.dig]
04-11 23:16:14.935  1041  1313 E tftp_server: pid=1041 tid=1313 tftp-server : ERR :[tftp_os_la.c, 70] open failed: [13] [Permission denied]
04-11 23:16:14.935  1041  1313 E tftp_server: pid=1041 tid=1313 tftp-server : ERR :[tftp_server.c, 1718] open failed : [-13] [Unknown error -13]
04-11 23:16:14.935  1041  1313 E tftp_server: pid=1041 tid=1313 tftp-server : ERR :[tftp_protocol.c, 1229] sending error-pkt. Code = 2, Msg = Err=13 String=Permission denied
04-11 23:16:14.936  1041  1041 I tftp_server: pid=1041 tid=1041 tftp-server : INF :[tftp_server.c, 667] rcvd request [1] [94] [1] [0] [99]
04-11 23:16:14.936  1041  1314 I tftp_server: pid=1041 tid=1314 tftp-server : INF :[tftp_server_utils.c, 113] file [readonly/modem_config/mcfg_sw/mbn_sw.dig] : [/vendor/rfs/msm/mpss/readonly/modem_config/
04-11 23:16:14.936  1041  1314 I tftp_server: pid=1041 tid=1314 tftp-server : INF :[tftp_server.c, 1222] OACK options : [7680, 200, 0, 10, 0, 0, 0, 0]
04-11 23:16:14.936  1041  1314 I tftp_server: pid=1041 tid=1314 tftp-server : INF :[tftp_os_la.c, 63] open : [-1] [-1] [384] [0] [/vendor/rfs/msm/mpss/readonly/modem_config/mcfg_sw/mbn_sw.dig]
04-11 23:16:14.936  1041  1314 E tftp_server: pid=1041 tid=1314 tftp-server : ERR :[tftp_os_la.c, 70] open failed: [13] [Permission denied]
04-11 23:16:14.936  1041  1314 E tftp_server: pid=1041 tid=1314 tftp-server : ERR :[tftp_server.c, 1718] open failed : [-13] [Unknown error -13]
04-11 23:16:14.936  1041  1314 E tftp_server: pid=1041 tid=1314 tftp-server : ERR :[tftp_protocol.c, 1229] sending error-pkt. Code = 2, Msg = Err=13 String=Permission denied
04-11 23:16:16.526   951   975 E CHRE    : Couldn't connect client socket to 'chre': No such file or directory
04-11 23:16:16.526   951   975 W CHRE    : Failed to (re)connect, next try in 2000 ms
04-11 23:16:20.526   951   975 E CHRE    : Couldn't connect client socket to 'chre': No such file or directory
04-11 23:16:20.526   951   975 W CHRE    : Failed to (re)connect, next try in 4000 ms
04-11 23:16:28.526   951   975 E CHRE    : Couldn't connect client socket to 'chre': No such file or directory
04-11 23:16:28.526   951   975 W CHRE    : Failed to (re)connect, next try in 8000 ms
04-11 23:16:29.266   984  1019 D vendor.lge.hardware.lgmd@1.0-service: uevent received SUBSYSTEM=power_supply
04-11 23:16:29.266   984  1019 D vendor.lge.hardware.lgmd@1.0-service: readFile(/sys/class/power_supply/usb/present, 1)
04-11 23:16:29.266   984  1019 E vendor.lge.hardware.lgmd@1.0-service: readFile: Could not open /sys/class/power_supply/usb/is_ocp
04-11 23:16:43.217  1027  1061 E ANDR-PERF-MPCTL: First Boot check over.Going to 2nd Boot check.
04-11 23:16:44.526   951   975 E CHRE    : Couldn't connect client socket to 'chre': No such file or directory
04-11 23:16:44.526   951   975 W CHRE    : Failed to (re)connect, next try in 16000 ms
04-11 23:17:16.527   951   975 E CHRE    : Couldn't connect client socket to 'chre': No such file or directory
04-11 23:17:16.527   951   975 W CHRE    : Failed to (re)connect, next try in 32000 ms
04-11 23:17:17.561   984  1019 D vendor.lge.hardware.lgmd@1.0-service: uevent received SUBSYSTEM=power_supply
04-11 23:17:17.562   984  1019 D vendor.lge.hardware.lgmd@1.0-service: readFile(/sys/class/power_supply/usb/present, 1)
04-11 23:17:17.562   984  1019 E vendor.lge.hardware.lgmd@1.0-service: readFile: Could not open /sys/class/power_supply/usb/is_ocp
04-11 23:17:35.032  1040  1040 I vendor.rmt_storage: rmt_storage_connect_cb: clnt_h=0xb conn_h=0x77c002c010
04-11 23:17:35.032  1040  1040 I vendor.rmt_storage: rmt_storage_rw_iovec_cb: /boot/modem_fs1: req_h=0xb msg_id=3: R/W request received
04-11 23:17:35.032  1040  1040 I vendor.rmt_storage: wakelock acquired: 1, error no: 42
04-11 23:17:35.032  1040  1253 I vendor.rmt_storage: rmt_storage_client_thread: /boot/modem_fs1: Unblock worker thread (th_id: 514328184048)
04-11 23:17:35.059  1040  1253 I vendor.rmt_storage: rmt_storage_client_thread: /boot/modem_fs1: req_h=0xb msg_id=3: Bytes written = 2097152
04-11 23:17:35.059  1040  1253 I vendor.rmt_storage: rmt_storage_client_thread: /boot/modem_fs1: req_h=0xb msg_id=3: Send response: res=0 err=0
04-11 23:17:35.059  1040  1253 I vendor.rmt_storage: rmt_storage_client_thread: /boot/modem_fs1: About to block rmt_storage client thread (th_id: 514328184048) wakelock released: 1, error no: 0
04-11 23:17:35.059  1040  1253 I vendor.rmt_storage: 
04-11 23:17:35.060  1040  1040 I vendor.rmt_storage: rmt_storage_disconnect_cb: clnt_h=0xb conn_h=0x77c002c010
04-11 23:18:10.235   984  1019 D vendor.lge.hardware.lgmd@1.0-service: uevent received SUBSYSTEM=power_supply
04-11 23:18:10.236   984  1019 D vendor.lge.hardware.lgmd@1.0-service: readFile(/sys/class/power_supply/usb/present, 1)
04-11 23:18:10.236   984  1019 E vendor.lge.hardware.lgmd@1.0-service: readFile: Could not open /sys/class/power_supply/usb/is_ocp
04-11 23:18:20.527   951   975 E CHRE    : Couldn't connect client socket to 'chre': No such file or directory
04-11 23:18:20.527   951   975 W CHRE    : Failed to (re)connect, next try in 64000 ms
04-11 23:19:05.824   984  1019 D vendor.lge.hardware.lgmd@1.0-service: uevent received SUBSYSTEM=power_supply
04-11 23:19:05.824   984  1019 D vendor.lge.hardware.lgmd@1.0-service: readFile(/sys/class/power_supply/usb/present, 1)
04-11 23:19:05.824   984  1019 E vendor.lge.hardware.lgmd@1.0-service: readFile: Could not open /sys/class/power_supply/usb/is_ocp](url)`
the vendor can't boot with ur aosp pie rom but works well with newest resurrectionremix arm64 a/b rom

**Comment by phhusson** [comment]
I have absolutely no idea what the issue is, or which device is

**Comment by SmartRu** [comment]
LMG 710(lg g7 )with newest vendor...but it actually worked with some gsi roms

**Comment by phhusson** [comment]
What is the issue?
You still haven't said or I missed it in the noise. Either way your issue
title can't be understood

**Comment by SmartRu** [comment]
I am sorry that, I have flashed ur newest aosp gsi rom,but when I trying to boot it the device stayed at the interface which only showed the AOSP icon. But resurrectionremix GSI rom can direcly boot with my device
