### ISSUE TITLE
Support HW button backlight

### ISSUE THREAD

**Issue by phhusson** [phhusson/treble_experimentations#5]
On mido for instance,
ref: https://github.com/LineageOS/android_frameworks_base/commit/f3d5b2de9c22faaa2373bf6094a1a25c32c5e495#diff-89bc1a1ee9f726e5421e4a8801371c77L748

**Comment by TheScarastic** [comment]
https://github.com/LineageOS/android_frameworks_base/commit/77ec17f75a8477f5054699455e9b436ddaffa50c

**Comment by phhusson** [comment]
Added, thanks
