### ISSUE TITLE
swapped audio channels on Razer Phone 2

### ISSUE THREAD

**Issue by RadekBledowski** [phhusson/treble_experimentations#501]
Audio doesn't switch with device current position on Razer Phone 2

**Comment by phhusson** [comment]
Well to the best of my knowledge that's a global issue to all stereo devices
I wonder how Pixels handle that though

**Comment by RadekBledowski** [comment]
well i have some weird stuff in build.prop related to switching channels idk if that can help

**Comment by RadekBledowski** [comment]
# stereo speakers: orientation changes swap L/R channels
ro.audio.monitorOrientation=true
ro.audio.monitorRotation=true

yup after adding these its working

**Comment by RadekBledowski** [comment]
pixel 3 uses same build.prop values but in vendor
i cant do it as magisk module bc its only 2 props

**Comment by phhusson** [comment]
Yeah don't worry we'll add it in rw-system.sh

**Comment by phhusson** [comment]
FWIW, the only property that exists is ro.audio.monitorRotation=true not Orientation

**Comment by phhusson** [comment]
Can you test latest rw-system.sh? Just replace it in system/bin/rw-system.sh

https://github.com/phhusson/device_phh_treble/commit/75a2e0f64f332d095110cc80b81b728682b6578d

**Comment by RadekBledowski** [comment]
well i got bootloop and I'm not sure if i did something wrong because I'm noob
