### ISSUE TITLE
[Mate 20 Pro]Notch, FP reader, Signal

### ISSUE THREAD

**Issue by Diazz72** [phhusson/treble_experimentations#502]
Here are issues with Mate 20 PRO so far.

- Notch and status bar are not align.
- FP reader not working ( mate 20 pro has optical under display FP reader ).
- The signal is weak and 4g/LTE is not working ( only 3g works ).

Regards, Diazz72.

**Comment by phhusson** [comment]
This is not one issue, this is 3 different issues. So please open three different issues.

That said, 2. is already tracked (and "fixed") at https://github.com/phhusson/treble_experimentations/issues/468

And 3. is probably just that you need to select "4G" in network settings.

1. is probably easy but you need to give screenshots // photos.
