### ISSUE TITLE
Would you support Signature Spoofing by default

### ISSUE THREAD

**Issue by ivysrono** [phhusson/treble_experimentations#503]
[Signature Spoofing · microg/android_packages_apps_GmsCore Wiki](https://github.com/microg/android_packages_apps_GmsCore/wiki/Signature-Spoofing)

MicroG need it.

**Comment by penn5** [comment]
No, this is AOSP only.

**Comment by phhusson** [comment]
No, but you've got https://forum.xda-developers.com/project-treble/trebleenabled-device-development/arm64aosp-9-0-0r21-microg-ufofficial-t3878115
