### ISSUE TITLE
[Moto G6 Plus] Sound is buggy and occasionally comes through speakers when headphones are plugged in

### ISSUE THREAD

**Issue by ghost** [phhusson/treble_experimentations#506]
Phone: Moto G6 Plus
Version: AOSP 9.0 v112

Steps to reproduce:

- Play music without headphones that would be plugged in. Sound works normally.

- Plug in the headphones. The sound becomes buggy and sometimes stops playing. It can also come from speakers instead of headphones.

@phhusson , feel free to ask me about any logs.

**Comment by penn5** [comment]
Please install lesser audioswitch and verify that a) under debug, it is ALWAYS able to detect when headphones are plugged in and that b) when headphones are connected but sounds is going via speaker, you can switch the sound manually. If both are the case the fix is simple, and just requires me to move some code

**Comment by BugReporter2** [comment]
> a) under debug, it is ALWAYS able to detect when headphones are plugged in

Yes. Here are the Debug logs:

[Output](https://pastebin.com/kQD4fjqV)

[Input](https://pastebin.com/qNudDHHe)

[Devices](https://pastebin.com/Qdy0GN9A)

> ) when headphones are connected but sounds is going via speaker, you can switch the sound manually.

Yes I can. Sometimes the sound comes through the speakers (when I use Lesser Audioswitch) and I just switch the audio manually to the headphones.

But still when I use Lesser Audioswitch, the sound sometimes stops playing.

**Comment by penn5** [comment]
Ok I'll change the settings later, probably tonight

**Comment by BugReporter2** [comment]
> Ok I'll change the settings later, probably tonight

Ok!

Do you have any insight about [this sound issue](https://github.com/phhusson/treble_experimentations/issues/126)?
