### ISSUE TITLE
<1Gb builds

### ISSUE THREAD

**Issue by JonnyTech** [phhusson/treble_experimentations#509]
Will the <1Gb builds be updated regularly? Currently using http://treble.phh.me/system-test-20190415-arm-a.img and it works great for me. Would love to have builds released often. Or maybe a build script.

**Comment by JonnyTech** [comment]
Looking at the latest released builds [(AOSP 9.0 v113)](https://github.com/phhusson/treble_experimentations/releases/tag/v113):

`system-arm-aonly-vanilla-nosu.img` = partition size of 1313 MB / 1252 MiB (949848 blocks used)

which is too big, it needs to be the same as:

`system-test-20190415-arm-a.img` = partition size of 1073 MB / 1024 MiB (948452 blocks used)

There is plenty of space in the bigger image but how do I resize it or generate a correctly sized one?

**Comment by phhusson** [comment]
there is no easy way to resize after generation.
Theorically you could do simg2img then `resize2fs -M`, but it never worked correctly.
To fix the issue, one would need to edit build.sh to change the size of the partition between vanilla and gapps variant.

**Comment by JonnyTech** [comment]
Coincidentally, I have just finished resizing v113 vanilla and it flashed just fine. I wanted an excuse to deodex it anyway. The only thing that I was unable to do was to embed your superuser to the image (any tips?). So I have a vanilla v113 running with Magisk now. Thanks for your reply and hard work with the builds.

**Comment by JonnyTech** [comment]
If anyone is interested, GO compatible build here: https://androidfilehost.com/?w=files&flid=294180
