### ISSUE TITLE
installation question

### ISSUE THREAD

**Issue by rezad1393** [phhusson/treble_experimentations#518]
I am a bit confused.
I have xiaomi Mi Pad 4 ,which I think is treble enables( treble enabled is both required of image and HW right?) and I think it is on A partition so my images should be that way too right?

how do I install this ROM
is a a ROM that doesn't need any other ROMs installed over it?)
I ask this because in the xda thread for arrowOS gsi image it says to install it this way:

"Clean Flash
    Download the appropriate zip of GSI for your device (i.e. A or A/B)
    Extract the system.img
    **Flash any treble enabled ROM.**
    Wipe: Dalvik and Cache
    **Flash the GSI** (system image) from recovery
    Reboot & Enjoy
"
is this a generic installation for that ROM?
should I install that ROM first then install the gsi image from here?

I tried to do it the way the is explained in xda blog too:
wipe system data and cache
do factory reset
the install gsi image (does this mean the ones here in release and others that are in wiki list?)
then reboot.

I tried this with both the image in releases here and Resurection remix gsi ROM.

the 2nd way ( just installing the gsi ROM) results twrp asking me before reboot the no os is install and do I want to reboot to system (https://highonandroid.com/android-root-101/how-to-install-gsi-rom-on-any-android-device-w-project-treble-unlocked-bootloader-twrp-method/ ) this says to ingore this and reboot because the boot image gets created automatically? but doing so results in some reboots then fastboot page then shutdown.

the first way (gotten from arrrowOS page, result in just MI.com logo for a long time after reboot and nothing happens

edit:
got RRemix treble ROM to work after installing mokee ROM.
but now I got an issue that happened with other mipad4 rom at random.
it is that wifi doesnt work (no AP shown).

**Comment by proganime1200** [comment]
download treble check on playstore and download AIDA64 on playstore to check if it its arm 32 or arm 64

**Comment by rezad1393** [comment]
I think I resolved some of my issues.
I used a havoc-os treble enabled ROM customized for my device (xiaomi MiPad4 clover).
now another question.
how can I check to see is my running os is in treble mode, or does a device that is treble enabled (from the start of device manufacturer) will always be treble enabled? what happens when I install a non-treble rom on it then? or all the custom ROM that are produced for it are treble compatible and it is seemless?

and how can I see is a ROM file is treble enabled?

**Comment by proganime1200** [comment]
Check my first comment that'd the answer

**Comment by rezad1393** [comment]
I did install treble check 
but it only says that ,for example my phone, is capable of treble and seamless update.
my question is something else entirely.
basically can I install a non-treble ROM on a treble enabled device? (my gut says yes cause system and vendor are on the same partition then).
and is so how can I check when I am running my device that the ROM running on it is in treble mode(not just my device capability).
and also how can I check before installing a ROM if that ROM is treble mode (not the device I am trying to install it on)

**Comment by phhusson** [comment]
Basically no you can't know. The only way to check if a ROM is Treble-compliant is to boot a GSI really
