### ISSUE TITLE
[Asus ZenFone Max Pro] IMS VoIP bools values set to false

### ISSUE THREAD

**Issue by SudeepDuhoon** [phhusson/treble_experimentations#52]
VoLTE _In_ and _sms over VoLTE_ is working fine
VoLTE _out_ is not working
IMS is registered by custom patch but rom has IMS and VoIP bools values set to false so can't proceed further

**Comment by phhusson** [comment]
Can I see the custom patch?

Anyway sure I can make a rro to enable those bools

**Comment by SudeepDuhoon** [comment]
Gladly, here it is
[ims_patch_t4.zip](https://github.com/phhusson/treble_experimentations/files/2025503/ims_patch_t4.zip)

i can't test it though

**Comment by phhusson** [comment]
Just to be clear, we're speaking of framework-res' config_carrier_volte_available and config_dynamic_bind_ims ?
Or are you mentioning something else?
The only voip setting I see is "config_use_voip_mode_for_ims" but this is something for audio manager, if in voice call in audio works, it shouldn't be changed

My current plan is to make a RRO that detects if org.codeaurora.ims is installed, in which case it sets config_ims_package to org.codeaurora.ims, config_dynamic_bind_ims to true, and config_carrier_volte_available to true
Does that look right to you?

**Comment by SudeepDuhoon** [comment]
Yes but i made an overlay to enable these
Yet this patch didn't work
I made another one by comparing custom aex rom for asus max pro with stock and treble based rom, but couldn make it work till now

**Comment by SudeepDuhoon** [comment]
[ims_patch_01-6-18 - t7.zip](https://github.com/phhusson/treble_experimentations/files/2063482/ims_patch_01-6-18.-.t7.zip)
updating vendor with this patch fixes volte for asus max pro m1
volte works on official aex gsi, tested on 2018-06-01

**Comment by anggaara17** [comment]
which build with volte work on official AEX? AryanPatidar build, or TingyiChen build? because there are two maintainer in Aex, n they said has  official build.

**Comment by SudeepDuhoon** [comment]
flash any latest custom rom (or only vendor from it) for asus max pro and clean flash any gsi+patch
volte will work

**Comment by arvind-gr** [comment]
I tried **ims_patch_02-6-18 - t8.zip** patch on Oneplus 5 and it doesnt even boot. Any VoLTE patches for OP5..?
