### ISSUE TITLE
J7 2017 exynos 7870 ASOP PIE - status bar signal icon not working

### ISSUE THREAD

**Issue by marcrhandall** [phhusson/treble_experimentations#521]
Signal icon is not working but sms and mobile data is working fine, just the icon in the statusbar

**Comment by FedericoPeranzi** [comment]
Same Here

**Comment by phhusson** [comment]
Not an OEM treble device

**Comment by FedericoPeranzi** [comment]
> Not an OEM treble device

What do you mean? The S9 support GSI images, so Yes it's a OEM treble device

**Comment by phhusson** [comment]
This issue doesn't mention S9...
