### ISSUE TITLE
Building "android-9.0 rr" gives duplicate exfat error.

### ISSUE THREAD

**Issue by evilexecutable** [phhusson/treble_experimentations#528]
Meta

Android Version (pre-installed): Android 9.0 Pie
Model codename: crownlte
Vendor: Samsung
SoC: Exynos 9
Used GSI: None
Bootloader unlocked (duh): Yes
Description of issue

Running build-rom.sh with arguments "android-9.0 rr" errors out with there being two references to external/exfat in .repo/manifests.xml. I have tried taking them out manually, but to no avail.

**Comment by evilexecutable** [comment]
It's worth noting that building against android-8.1 works fine.

**Comment by phhusson** [comment]
Use build-dakkar, this is fixed in it.
