### ISSUE TITLE
[onc] The screen remains dim even when brightness is at max

### ISSUE THREAD

**Issue by aosplink** [phhusson/treble_experimentations#532]
Device: Redmi 7 [onc]
Treble-enabled: Yes (system-as-root, pie, was supported since launch)
Stock-Android-Version: 9.0 (Pie)
#### Description:
The screen never reaches the max brightness. The device cannot be returned to stock firmware and hence the only resolution would be to fix the issue on the GSI.

## Important: Read [this post](https://github.com/phhusson/treble_experimentations/issues/532#issuecomment-496194991)

**Comment by phhusson** [comment]
Please dump `cat /sys/class/leds/lcd-backlight/max_brightness` and `cat /sys/class/backlight/panel0-backlight/max_brightness`

Try setting the qcom brightness to 1023

**Comment by aosplink** [comment]
I will check the solution you've provided. Here is the decompiled framework resources archive from the stock ROM:
[f-res.zip](https://github.com/phhusson/treble_experimentations/files/3210747/f-res.zip)

###### [Generated using issuebot@1558596341 | /mnt/ntw/users/sayan/public/]

**Comment by aosplink** [comment]
```shell
cat /sys/class/leds/lcd-backlight/max_brightness
255
cat /sys/class/backlight/panel0-backlight/max_brightness
cat: /sys/class/backlight/panel0-backlight/max_brightness: No such file or directory
```
###### [Generated using issuebot@1558596870 | /mnt/ntw/users/sayan/public/]

**Comment by phhusson** [comment]
Ok then try setting the prop to 255?

**Comment by aosplink** [comment]
Setting the prop to 255 doesn't cause any flicker, however the display remains dimmed
###### [Generated using issuebot@1558597231 | /mnt/ntw/users/sayan/public/]

**Comment by phhusson** [comment]
Brightness value does change when setting it from the UI?
How much dim-ed are we talking about ? Like max is 80% of stock, or 10%?

**Comment by phhusson** [comment]
Answered from Telegram: 

> Brightness changes when using UI, max is about 80% of stock

**Comment by aosplink** [comment]
As discussed on the channel, both of us have determined that the High Brightness mode is missing for this specific device. Due to a failure (on my part) in *__devdex__-ing* the _services.vdex_ file, I am leaving a link to the entire framework for this device: [Redmi7-Framework.zip](https://drive.google.com/uc?export=download&id=10AQ34WwhqChrDHbxRJQwJ1bCmmV2Dn3y)
###### [Generated using issuebot@1558596870 | /mnt/ntw/users/sayan/public/]

**Comment by aosplink** [comment]
As discussed on the channel, both of us have determined that the High Brightness mode is missing for this specific device. Due to a failure (on my part) in *__devdex__-ing* the _services.vdex_ file, I am leaving a link to the entire framework for this device: [Redmi7-Framework.zip](https://drive.google.com/uc?export=download&id=10AQ34WwhqChrDHbxRJQwJ1bCmmV2Dn3y)
###### [Generated using issuebot@1558605624 | /mnt/ntw/users/sayan/public/ | (error: 2_dt_sync_error_del_lastmsg) ]

**Comment by aosplink** [comment]
@phhusson The current issues with this device:
- Adaptive Brightness **doesn't work**
- Display brightness **never reaches the maximum** even when done manually

As far as I can say, the device-tree is absolutely fantastic and most things work (another issue is with the microphone), just waiting for these two issues to be sorted

**Comment by aosplink** [comment]
**Important update on this issue**:
Seems like the UI is bugged instead of the props. Till now we had reached the conclusion that the issue is resulting from "MAX BRIGHTNESS MODE" support not working. **However, max_brightness_mode is not the issue**. Instead, **it seems to be a bug in the UI**. When I:
```shell
cat /sys/class/leds/lcd-backlight/max_brightness
255
```
Also `persist.sys.qcom-brightness` and `persist.display.max_brightness` are set to 255. Hence it is not an issue with the props. On further research on this issue, I discovered that if I:
```shell
cd /sys/class/leds/lcd-backlight/max_brightness
echo 255 > max_brightness
```
The **display lights up to the max brightness**. I do this over Terminal Emulator. When I maxed out the brightness slider, the value of `max_brightness` is 28, hence the slider prevents the brightness from reaching the maximum resulting in the screen dim.
I hope this information can help fix this specific issue.

**Comment by phhusson** [comment]
Ah. Very interesting indeed

If you do `lightsctl BACKLIGHT ff`
Does it set brightness to max?
Please attach /vendor/overlay

**Comment by aosplink** [comment]
`lightsctl BACKLIGHT ff` doesn't do anything, no change. I am uploading the /vendor/overlay in a moment

**Comment by phhusson** [comment]
`cat /data/resource-cache/overlay.list`

**Comment by aosplink** [comment]
## Meta
- GSI used: system-arm64-ab-gapps-su.img.xz (unzipped to the image)
- Flashed to system image partition using TWRP
## List of issues
- Adaptive brightness is missing (the option is not there in settings) and it doesn't work
- Brightness is 28 when brightness slider is at maximum position:
  When I do `cat /sys/class/leds/lcd-backlight/brightness` while the slider is at the maximum position, the value is 28. Whereas the value should be 255, as this is the value of `cat /sys/class/leds/lcd-backlight/max_brightness`.
## Attempts to fix
- `setprop persist.sys.qcom-brightness 255` This did not do any help
- `setprop persist.display.max_brightness 255` This did not help either
- overlay was compiled and that did not help either
## Support files
- [Decompiled framework-res.apk](https://github.com/phhusson/treble_experimentations/files/3210747/f-res.zip) from stock image
- [Entire system framework](https://drive.google.com/file/d/10AQ34WwhqChrDHbxRJQwJ1bCmmV2Dn3y/view?usp=sharing) which is located at `/system/framework` from stock image
## Probable causes
- We need to use an overlay
- The UI doesn't respect the `max_brightness`

**Comment by phhusson** [comment]
backlight value is different between middle and and max?

Please provide `adb shell dumpsys display` when slider is at the max, and when it's in the middle

**Comment by aosplink** [comment]
> backlight value is different between middle and and max?
> 
> Please provide `adb shell dumpsys display` when slider is at the max, and when it's in the middle

Please check [updated OP](https://github.com/phhusson/treble_experimentations/issues/532#issuecomment-496194991)

**Comment by phhusson** [comment]
Middle says:
```
  mPendingBacklight=30
  mActualState=ON
  mActualBacklight=30
```

Max says:
```
  mPendingState=ON
  mPendingBacklight=255
  mActualState=ON
  mActualBacklight=255
```

so everything looks good...?

**Comment by aosplink** [comment]
> Middle says:
> 
> ```
>   mPendingBacklight=30
>   mActualState=ON
>   mActualBacklight=30
> ```
> 
> Max says:
> 
> ```
>   mPendingState=ON
>   mPendingBacklight=255
>   mActualState=ON
>   mActualBacklight=255
> ```
> 
> so everything looks good...?

No change in real. That's pretty amazing, when I do `cat /sys/class/leds/lcd-backlight/brightness` when slider is in middle it concatenates 14 and when I do `cat /sys/class/leds/lcd-backlight/brightness` when slider is in max it concatenates 28

**Comment by phhusson** [comment]
Can you paste `getprop`?

**Comment by aosplink** [comment]
Here is: [getprop.txt](https://github.com/phhusson/treble_experimentations/files/3223787/getprop.txt)

**Comment by aosplink** [comment]
Any update on this? I've literally been waiting for a month

**Comment by aosplink** [comment]
This has been fixed. Closing

**Comment by ChemsoDev** [comment]
how you fixed it
