### ISSUE TITLE
[Redmi K20 Pro] Audio playback stutters

### ISSUE THREAD

**Issue by AndyCGYan** [phhusson/treble_experimentations#541]
Device: Redmi K20 Pro (raphael)
Treble status: Yes, A/B, native
Stock Android version: 9 - full dump [here](https://github.com/TadiT7/xiaomi_raphael_dump)

Audio playback stutters and sounds glitchy.
Tried the soundfx fix ([like this](https://github.com/phhusson/device_phh_treble/pull/74/commits/bcdbba8a0c5f1d33a3703df05a139cab779fb5d3)), doesn't seem to make a difference.

**Comment by phhusson** [comment]
Uh that really sounds like the issue you're linking.
Perhaps you have installed magisk? it is known to interfere with this

You can try that to double-check:
```
adb shell
$ su
# echo ro.audio.ignore_effects=true > /data/local.prop
# chmod 0600 /data/local.prop
# reboot
...
# getprop ro.audio.ignore_effects
true
#
```

**Comment by AndyCGYan** [comment]
> Uh that really sounds like the issue you're linking.
> Perhaps you have installed magisk? it is known to interfere with this
> 
> You can try that to double-check:
> 
> ```
> adb shell
> $ su
> # echo ro.audio.ignore_effects=true > /data/local.prop
> # chmod 0600 /data/local.prop
> # reboot
> ...
> # getprop ro.audio.ignore_effects
> true
> #
> ```

Output is exactly the same as you quoted, and yeah after doing this audio sounds normal now.
I do have Magisk installed - never expected that to interfere.

**Comment by AndyCGYan** [comment]
Solved with the fix in place, been using for a few days without issues. Closed.
