### ISSUE TITLE
[Huawei P9 Plus] Can´t flash img

### ISSUE THREAD

**Issue by Han98** [phhusson/treble_experimentations#546]
Hi,

everytime i flash the image i get this error:

target reported max download size of 471859200 bytes
sending sparse 'system' 1/4 (460796 KB)...
OKAY [ 10.817s]
writing 'system' 1/4...
FAILED (remote: sparse flash write failure)
finished. total time: 10.859

i tried it with -S 100m and sim2img.

**Comment by PhieF** [comment]
Hi, same problem here with huawei p9 ! :)

**Comment by penn5** [comment]
System version?
Output of `adb shell cat /proc/cmdline` (contains bootloader version)?
`/proc/balong/log/fastboot_log` after forcibly booting to recovery using rescue_recovery (this is complex - see below)
To get fastboot logs, make sure you have the stock images and TWRP. We will need to load them to RAM. Run
```
fastboot flash rescue_recovery_kernel STOCKKERNEL.img
fastboot flash rescue_recovery_ramdisk TWRPRAMDISK.img
fastboot flash rescue_recovery_vendor STOCK_RECOVERY_VENDOR.img
```
And the device will boot to twrp. From twrp you must take the file /proc/balong/log/fastboot_log and upload here

**Comment by PhieF** [comment]
```
loglevel=4 initcall_debug=n page_tracker=on slub_min_objects=12 unmovable_isolate1=2:192M,3:224M,4:256M printktimer=0xfff0a000,0x534,0x538 androidboot.selinux=enforcing buildvariant=user androidboot.swtype=normal fastboot_version=Chipset-chicago8.0.0.6(07EE)_FASTBOOT setup_logctl=0 enter_recovery=0 androidboot.mode=normal pmu_nv_addr=0x34a20014 low_volt_flag=0 boardid=0x00000d8e normal_reset_type=coldboot  TP_COLOR=225  COLOR_TMP=0 LCD_DENSITY=0 ddr_die=1536M@0M ddr_die=1536M@2048M  productid=0x3c014000 efuse_status=0 androidboot.serialno=MWS0216808006073 himntn=0111111111111010001011000000000000000010 boot_slice=0x0004df8d reboot_reason=coldboot last_bootup_keypoint=250 recovery_update=0 userlock=unlocked bootlock=unlocked hw_bfm_enable=1 ddr_density=14 swiotlb=2 mdmreglogbase=0x00000000 mdmreglogsize=0x00000000 modem_socp_enable=0 androidboot.hardware=hi3650 androidboot.veritymode=enforcing androidboot.verifiedbootstate=ORANGE emmc_freqsel=0x00000011 format_data=1 cpu_buck_reg=0x;;  LCD_ID=3 androidboot.ddrsize=3 oba_version=20181219040321_OBA_VERSION kce_status=1  bl1_time=957 bl2_time=9779 logo_time=2210 dsm_notify=1  console=ttyS0 
```

I already had twrp as a recovery, so here is fastboot log
[fastboot_log.txt](https://github.com/phhusson/treble_experimentations/files/3268359/fastboot_log.txt)

**Comment by phhusson** [comment]
Well I'm not a fan, but you could just flash using twrp until this is fixed

**Comment by penn5** [comment]
> Thanks !!
> 
> https://framabin.org/p/?1fc80610b1b7c063#kBZg/ai9lTVDSAUbQvSx3TmI5RUw4TK3Jw5+4JzpqXw=
> 
> I already had twrp as a recovery, so here is fastboot log
> [fastboot_log.txt](https://github.com/phhusson/treble_experimentations/files/3268359/fastboot_log.txt)
> current android is 9 but stock is 8, it should be treble OK but even stock roms from google won't boot, but flashing them is ok

Please do the instructions to get a live fastboot log. The one you sent is useless; it is the boot *after* fastboot flashing

**Comment by PhieF** [comment]
Is this better ?


[fastboot_log.txt](https://github.com/phhusson/treble_experimentations/files/3269472/fastboot_log.txt)
Thanks !

@phhusson  I tried through TWRP:
flashing "System" didn't work at all
Flashing "System Image" did something but I'm now unable to boot (twrp tells me I have no operating systems)
Which one is supposed to work ?

Thanks

**Comment by phhusson** [comment]
System image is supposed to work.

You're on EMUI8? Using AOSP v114, arm64 aonly?

**Comment by barisdemirdelen** [comment]
I can confirm with huawei p9 with emui 8 aosp v114 arm64 aonly su/nosu doesnt work via flashing to twrp as system image. Flashing completes succesfully but twrp says no os found. Mounting the /system via terminal gives invalid argument error.

With fastboot i also cant flash.

**Comment by phhusson** [comment]
Please give result of dmesg in TWRP after trying to mount /system

Le dim. 9 juin 2019 à 14:39, Barış Demirdelen <notifications@github.com> a
écrit :

**Comment by barisdemirdelen** [comment]
Sure, thanks for the fast response, here it is. This is me first flashing and then trying to mount it.

[dmesg.log](https://github.com/phhusson/treble_experimentations/files/3269527/dmesg.log)
[recovery.log](https://github.com/phhusson/treble_experimentations/files/3269528/recovery.log)

**Comment by phhusson** [comment]
`

<4>[   76.588745s][pid:324,cpu5,recovery]EXT4-fs (mmcblk0p52): bad
geometry: block count 524288 exceeds size of device (507904 blocks)

`

What's your system partition size?


Le dim. 9 juin 2019 à 14:48, Barış Demirdelen <notifications@github.com> a
écrit :

**Comment by barisdemirdelen** [comment]
Twrp says 1921MB with 1815MB used and 106MB free. Is there a better way to see?

**Comment by barisdemirdelen** [comment]
cat /proc/partitions says it has 2031616 blocks

**Comment by phhusson** [comment]
K so that's indeed too low for my images which are 2GB.
I'll try to change to your partition's size

Le dim. 9 juin 2019 à 14:58, Barış Demirdelen <notifications@github.com> a
écrit :

**Comment by barisdemirdelen** [comment]
I tried building with a 1.9gb partition size and everything went well with twrp and I was able to boot.

**Comment by phhusson** [comment]
Here is a test image:
https://treble.phh.me/system-arm64-p9.img

**Comment by PhieF** [comment]
Huawei p9 is ok with it, thanks !
