### ISSUE TITLE
GM8 Auto brightness, dt2w, led

### ISSUE THREAD

**Issue by opalfina** [phhusson/treble_experimentations#547]
I use a GM 8 device on Android A / B treble-assisted 8.1 using double-tap wake when using vendor and 8.1 oreo roms Does not work when using 8.1 vendor and 9.0 pie What is the solution that does not work when using 9.0 vendor and 9.0?
and only the red led light on the device is lit I hope you don't have any source of return
I am a developer

**Comment by opalfina** [comment]
@phhusson? Can you help? What are the required files?

**Comment by phhusson** [comment]
Open separate issues
and attach stock rom's system/framework/framework-res.apk to the auto brightness issue
