### ISSUE TITLE
[ocean] Moto G7 power works

### ISSUE THREAD

**Issue by basteln3rk** [phhusson/treble_experimentations#549]
I was able to install the ROM on moto g7 power (ocean) . No problems detected so far. Thanks for this ROM!

However, to install the ROM i needed to use the command

```
 fastboot flash system_a system-arm64-ab-gapps-su.img
```

Note the partition name is ``system_a`` not ``system`` as per the docs.

I have added ocean to the list of successfully booting devices in the wiki.

**Comment by basteln3rk** [comment]
i'm not sure if the ``system_a`` issue affects more devices, but it may be a good idea to add this to the documentation somewhere. Or should I create a wiki page for this device?

**Comment by phhusson** [comment]
Well yes, make a wiki page for this device.
The goal of the wiki is to list as many devices as possible, even if it's
just to say "just works"

>
