### ISSUE TITLE
[A/B] Boot doesn't set current slot as bootable after successful boot

### ISSUE THREAD

**Issue by AndroPlus-org** [phhusson/treble_experimentations#55]
On A/B partition devices, system must mark current slot as "bootable" after successful boot.
Otherwise bootloader counts down slot-retry-count and it reboots in bootloader recovery mode when slot-retry-count became 0.
https://source.android.com/devices/tech/ota/ab/ab_implement

Currently slot is not marked as bootable even if the device boots successfully.
I tested on Sharp AQUOS S2 SS2 (arm64).

**Comment by AndroPlus-org** [comment]
To workaround this issue, I added "PRODUCT_PACKAGES += bootctl" to  device_phh_treble/generate.sh
and run "bootctl mark-boot-successful" in adb shell after booting.

**Comment by phhusson** [comment]
I don't get such a problem on Razer Phone, that's a bit weird.
For the moment I've added bootctl:
https://github.com/phhusson/device_phh_treble/commit/6603eb018014c706a1e0e93e589f68571fce0124

Something as possible as on property:sys.boot_completed=1 bootctl mark-boot-successful in an init.rc shuold be enough I guess, but I want to check the behaviour on an A-only device first

**Comment by Jim-Bar** [comment]
Tested on a Google Pixel (arm64, A/B):
```
on property:sys.boot_completed=1
    exec u:r:phhsu_daemon:s0 root -- /system/bin/bootctl mark-boot-successful
```
I put that into `device/phh/treble/environ/init.treble-environ.rc`.

The bootloader successfully marked the slot as bootable. Before first boot:
```
$ fastboot getvar all
(…)
(bootloader) slot-count:2
(bootloader) current-slot:a
(bootloader) slot-retry-count:b:0
(bootloader) slot-unbootable:b:no
(bootloader) slot-successful:b:no
(bootloader) slot-retry-count:a:3
(bootloader) slot-unbootable:a:no
(bootloader) slot-successful:a:no
```
After first boot:
```
$ fastboot getvar all
(…)
(bootloader) slot-count:2
(bootloader) current-slot:a
(bootloader) slot-retry-count:b:0
(bootloader) slot-unbootable:b:no
(bootloader) slot-successful:b:no
(bootloader) slot-retry-count:a:2
(bootloader) slot-unbootable:a:no
(bootloader) slot-successful:a:yes
```

**Comment by phhusson** [comment]
There I commited:
https://github.com/phhusson/device_phh_treble/commit/b01b148356900210a27543129588cc322ca168fa
Not tested yet on either A or A/B

**Comment by Jim-Bar** [comment]
Fetched, and tested on a Google Pixel XL (A/B): it works.
