### ISSUE TITLE
[wiki] [Samsung Galaxy Tab S4] flashing instructions suggest using fastboot

### ISSUE THREAD

**Issue by jamuir** [phhusson/treble_experimentations#550]
https://github.com/phhusson/treble_experimentations/wiki/Samsung-Galaxy-Tab-S4-(SM-T83X)

The flashing instructions for the Samsung Galaxy Tab S4 suggest using the fastboot utility to flash a system image, but Samsung bootloaders do not support the fastboot protocol.

**Comment by jamuir** [comment]
This error might just be inherited from a copy-paste:

https://github.com/phhusson/treble_experimentations/wiki/Samsung-Galaxy-A7-2018

@ozon  @mKenfenheuer

**Comment by phhusson** [comment]
I'd say you're right, feel free to edit those pages

**Comment by jamuir** [comment]
fixed:

https://github.com/phhusson/treble_experimentations/wiki/Samsung-Galaxy-Tab-S4-(SM-T83X)/9f1b3f402af8889623428d22ba5c2e03b839d087

**Comment by phhusson** [comment]
thanks

Le ven. 11 oct. 2019 à 18:45, James Muir <notifications@github.com> a
écrit :
