### ISSUE TITLE
App icon disappears when are being dragged

### ISSUE THREAD

**Issue by Alphitaa** [phhusson/treble_experimentations#555]
Issue from Moto G6 play running arm a only 9.0 builds 

Also noticed that this happen with icons that don't have that animation of delay when dragging

**Comment by Dekamir** [comment]
So you mean, non-adaptive icons disappear?

**Comment by Alphitaa** [comment]
> So you mean, non-adaptive icons disappear?
> 
> Also, only hardware bugs should be reported.

Yes, and sorry i didn't know
