### ISSUE TITLE
[Samsung Galaxy S9 - SM-G9600] Auto brightness don't work

### ISSUE THREAD

**Issue by FedericoPeranzi** [phhusson/treble_experimentations#557]
With the last version of GSI (Pie), the Auto brightness in Galaxy S9 Latin version didn't work, always is in 100%, any idea how to fix it?

The processor it's: Snapdragon 845.

**Comment by phhusson** [comment]
It's not totally clear to me: do you mean this is a new issue, or you've
always had that issue?

Le lun. 10 juin 2019 à 22:12, Federico Peranzi <notifications@github.com> a
écrit :

**Comment by FedericoPeranzi** [comment]
I install the last GSI, and the brigtness it's on 100%, it's happend with all GSI i've install. I read may be if a change the persist.sys.qcom-brightness 4095 can be fixed, but don't know wich file i have to edit

**Comment by phhusson** [comment]
I'll take that as a yes...

Try that, from your computer:
```
> adb shell<enter>
$ su<enter>
# setprop persist.sys.phh.samsung_backlight 1
# reboot
```

**Comment by FedericoPeranzi** [comment]
The kernel i use has a bug, and don't read the storage from a computer, so can you tell me wich file a have to edit pleas?

**Comment by phhusson** [comment]
... just use adb like I just said

Le lun. 10 juin 2019 à 23:04, Federico Peranzi <notifications@github.com> a
écrit :

**Comment by FedericoPeranzi** [comment]
I've try with a terminal in my S9, but the autobrightness still in 100%

**Comment by phhusson** [comment]
what does `getprop persist.sys.phh.samsung_backlight` in that terminal say?

**Comment by FedericoPeranzi** [comment]
Nothing, I press enter, and then go to the line below

**Comment by phhusson** [comment]
k then it didn't work.
Then please do as I said, using adb from your computer.

**Comment by FedericoPeranzi** [comment]
So, I wait for the Kernel's fix, and then I replay. Thanks in advanced.

**Comment by phhusson** [comment]
You said MTP is broken, but ADB isn't broken...?

**Comment by FedericoPeranzi** [comment]
ADB too, couse don't recognize the phone, it's a kernel issue

**Comment by FedericoPeranzi** [comment]
@phhusson Later this week the kernel it's going to be fixed, and then I apply your solution for the brightness

**Comment by phhusson** [comment]
Oops, I've misread the title

Is manual backlight control working properly?

**Comment by FedericoPeranzi** [comment]
Yes, works fine

**Comment by FedericoPeranzi** [comment]
Any other way to fix this? or only via ADB?}

**Comment by phhusson** [comment]
You simply need to create an overlay

https://github.com/phhusson/treble_experimentations/wiki/How-to-create-an-overlay%3F

**Comment by MezaCorleehone** [comment]
These are the steps for my device.



Download the desired GSI (it MUST be A-only_arm64 Variant)
Unpack it if it was not in .IMG format
Wipe DATA, and reboot in TWRP
Go to TWRP, Install, Install IMAGE
Pick your GSI and select SYSTEM IMAGE
Install the kernel for GSI GSI Kernels
In TWRP mount System, then go to ADVANDED, File Manager, and delete this file: system / bin / rw_system.sh
Reboot system

**Comment by MezaCorleehone** [comment]
use the method

> adb shell
$ su
# setprop persist.sys.phh.samsung_backlight 1
# reboot

it does not work.

**Comment by FedericoPeranzi** [comment]
> You simply need to create an overlay
> 
> https://github.com/phhusson/treble_experimentations/wiki/How-to-create-an-overlay%3F

I try it but i cant, can you help me Bro?

**Comment by FedericoPeranzi** [comment]
The July vendor of the new version of Official Samsung's Firmware fix the issue!

**Comment by LjaPb** [comment]
> The July vendor of the new version of Official Samsung's Firmware fix the issue!

I installed off samsung firmware (august security patch) after installing gsi roms and doesn't work anywhere auto-brightness. Discovered weird fingerprint sensor behavior, the phone vibrates when touched, but I couldn’t add a single finger to the database. How do you install roms, maybe I'm doing something wrong?
