### ISSUE TITLE
[Huawei Honor 7X] Audio playing through speaker when headphone jack is connected

### ISSUE THREAD

**Issue by aouerfelli** [phhusson/treble_experimentations#56]
I an issue where audio does not play through the headphone jack. It's similar to #49 and this [old issue on XDA](https://forum.xda-developers.com/project-treble/trebleenabled-device-development/experimental-phh-treble-t3709659/post76086555), though I don't know if that one was ever solved.

I took a quick log following your suggestion [here](https://forum.xda-developers.com/project-treble/trebleenabled-device-development/experimental-phh-treble-t3709659/post76086644). I asked Google Assistant to 'say something' with speakers first, then plugged in headphones and repeated the process, then unplugged them and did the same thing again. I don't have Bluetooth headphones, so unfortunately I can't test for that.
```sh
$ adb logcat -d | grep -C20 -iE '(alsa|usb|audio)'
```
https://pastebin.com/TKPeepUB

Also here's [my getprop (Huawei Honor 7X)](https://pastebin.com/YVdkLKxx)

**Comment by phhusson** [comment]
I reproduced a jack-related issue on Mate 9/View 10: https://github.com/phhusson/treble_experimentations/issues/67
Can you try the "steps to reproduce" and see if at the end you get sound to the headphones?

**Comment by aouerfelli** [comment]
Doesn't seem to work for me unfortunately. I put up my unfiltered logs [here](https://pastebin.com/hR0pgJDJ) (the logs were taken using an app, so the format is a bit different).
