### ISSUE TITLE
V114 release - -Auto brightness not working - on Asus Zenfone 5 ZE620KL 

### ISSUE THREAD

**Issue by barbarkaan** [phhusson/treble_experimentations#565]
V114 release stock camera+automatic brightness does not work at all GSI rom the same problem - on Asus Zenfone 5 ZE620KL

**Comment by barbarkaan** [comment]
stock camera+automatic brightness does not work at all GSI rom the same problem

**Comment by phhusson** [comment]
That's two different issues, so open two different issues
