### ISSUE TITLE
[Umidigi One Max] Broken RIL = No Data / Calls

### ISSUE THREAD

**Issue by defvs** [phhusson/treble_experimentations#573]
Broken RIL on Umidigi One Max; 

PHHUSSON AOSP A-Only ARM64 9 Pie

MT6763. 2x SIM slots

- SIM (2x) can be unlocked

- Shows signal in the interface

- No Data

- Ongoing phone calls not received

- Outgoing phone calls fails

**Comment by phhusson** [comment]
That's on v114 with no magisk installed?
If not, please do

Le mer. 19 juin 2019 à 18:01, Daniel THIRION <notifications@github.com> a
écrit :

**Comment by defvs** [comment]
@phhusson negative. Magisk installed, disabled force-encrypt as well.

**Comment by phhusson** [comment]
Right there is a known issue on mediatek devices when disabling
force-encrypt at least

also it's likely magisk breaks some of my fixes

Le mer. 19 juin 2019 à 18:04, Daniel THIRION <notifications@github.com> a
écrit :

**Comment by defvs** [comment]
Does flashing using TWRP image flash cause issues ? Or is it the same as flashing using Mediatek's tool or flashtool ?

**Comment by phhusson** [comment]
Using TWRP should be fine

Le mer. 19 juin 2019 à 18:09, Daniel THIRION <notifications@github.com> a
écrit :

**Comment by defvs** [comment]
Closing the issue; the latest version seems to work. No issues even without force-encrypt
