### ISSUE TITLE
Samsung Galaxy J4+ (SM-J415FN) not booting

### ISSUE THREAD

**Issue by SebaUbuntu** [phhusson/treble_experimentations#574]
Samsung Galaxy J4+ not booting phh treble v110
Using arm a images

Started from Samsung One UI (Android 9) fw, it remain on Samsung logo

[logcat-v110.txt](https://github.com/phhusson/treble_experimentations/files/3311257/logcat.txt)

On v114 it go to Android logo, then it reboot after 5 sec

[logcat-v114.txt](https://github.com/phhusson/treble_experimentations/files/3311315/logcat.txt)

**Comment by SebaUbuntu** [comment]
Using Magisk patched boot.img to get logcat, if I use stock boot.img it doesn't boot at all

**Comment by phhusson** [comment]
Why did you close?

**Comment by SebaUbuntu** [comment]
Fixed by installing oreo fw and oreo patched boot.img
