### ISSUE TITLE
Corners not rounded in Moto E5 (Nora)

### ISSUE THREAD

**Issue by Loco1911** [phhusson/treble_experimentations#582]
The corners of the Moto E5 are not rounded in any treble rom, I think it is because they do not contain the specific overlay. Is it possible that they add it?

**Comment by GodcraftPlata** [comment]
Seems like there isn’t anything on stock framework nor on /vendor/overlay, this is related to SystemUI maybe. I’ll check.

**Comment by GodcraftPlata** [comment]
And yes, there are two dimens on decompiled SystemUI apk from stock:

`    <dimen name="rounded_corner_content_padding">2.0dip</dimen>
     <dimen name="rounded_corner_radius">8.0dip</dimen>`

I'll add a SystemUI overlay to my pull request.
