### ISSUE TITLE
[Samsung Galaxy S10 Snapdragon] Manual brightness non-fuctional

### ISSUE THREAD

**Issue by Flatty11** [phhusson/treble_experimentations#588]
Here's logcat screenshot when trying to move brightness slider:
![error](https://user-images.githubusercontent.com/52137767/60306421-c4cd6180-9948-11e9-920b-cd6fb5aed022.png)

**Comment by phhusson** [comment]
could you give me the result of `getprop ro.vendor.build.fingerprint` ?

**Comment by Flatty11** [comment]
> could you give me the result of `getprop ro.vendor.build.fingerprint` ?

samsung/beyond2qltezc/beyond2q:9/PPR1.180610.011/G9750ZCU1ASD4:user/release-keys

Also there is another version of the phone called "beyond2qltezh" - this one also with unlocked bl, but its for another market.

**Comment by phhusson** [comment]
k, can you check if those change backlight value:

```
> adb shell
$ su
# lightsctl BACKLIGHT 80
# lightsctl BACKLIGHT ff808080
# lightsctl BACKLIGHT 808080
# lightsctl-sec BACKLIGHT 808080
# lightsctl-sec BACKLIGHT 80
```

**Comment by phhusson** [comment]
(you can change every occurence of "80" to "20" or "c0" to try other values)

**Comment by Flatty11** [comment]
> k, can you check if those change backlight value:
> 
> ```
> > adb shell
> $ su
> # lightsctl BACKLIGHT 80
> # lightsctl BACKLIGHT ff808080
> # lightsctl BACKLIGHT 808080
> # lightsctl-sec BACKLIGHT 808080
> # lightsctl-sec BACKLIGHT 80
> ```

Here's what i get: 

![error2](https://user-images.githubusercontent.com/52137767/60541445-59a1d780-9d1a-11e9-9f47-29992a38643c.png)

**Comment by Flatty11** [comment]
None of them worked

**Comment by phhusson** [comment]
result of `lshal` ?

**Comment by Flatty11** [comment]
Anything can be else provided?

**Comment by Flatty11** [comment]
> result of `lshal` ?

lshal:
[hals.txt](https://github.com/phhusson/treble_experimentations/files/3441426/hals.txt)

Here's logcat after trying lightsctl-sec
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/3441417/logcat.txt)

Getprop results:
[full_getprop_S10Plus_855.txt](https://github.com/phhusson/treble_experimentations/files/3441422/full_getprop_S10Plus_855.txt)

**Comment by JosephShenton** [comment]
Did you fix this
