### ISSUE TITLE
Voice over LTE is not working in RIVA

### ISSUE THREAD

**Issue by LordShenron** [phhusson/treble_experimentations#59]
VoLTE is not working in these GSIs. Tried some GSIs but VoLTE is not working on RIVA(Xiaomi Redmi 5A). Treble is enabled on the device unofficially.

**Comment by LordShenron** [comment]
It's not working. Sim cards are detected after using the patch.

**Comment by 33bca** [comment]
It was working just fine some time ago and still works after install. It's just gone after reboot. 
Should be the same on Redmi 4A btw.

I'll look into it this week.

**Comment by SudeepDuhoon** [comment]
[ims_patch_02-6-18 - t8.zip](https://github.com/phhusson/treble_experimentations/files/2064625/ims_patch_02-6-18.-.t8.zip)
can you try this? backup your vendor partition first

**Comment by dgadelha** [comment]
@SudeepDuhoon no SIM card detected on Mi A1

**Comment by arvind-gr** [comment]
I tried this patch on Oneplus 5 and it doesnt even boot. Any VoLTE patches for OP5..?

**Comment by phhusson** [comment]
VoLTE should now work on CAF devices, with ims repacker done:
https://github.com/phhusson/apps_repacker_aosp/tree/master/VoLTE-CAF
