### ISSUE TITLE
[Galaxy S10/S10+ Exynos] Proximity sensor broken 

### ISSUE THREAD

**Issue by malinathani** [phhusson/treble_experimentations#592]
[sensorservice_s10+exynos.txt](https://github.com/phhusson/treble_experimentations/files/3344359/sensorservice_s10%2Bexynos.txt)

**Comment by phhusson** [comment]
So, Samsung doesn't declare "standard" proximity sensor, but instead two proprietary sensors:
```
0x0000000b) Proximity Pocket          | AMS, Inc.       | ver: 1 | type: com.samsung.sensor.proximity_pocket(65589) | perm: n/a | flags: 0x00000002
0x0000000e) Touch Proximity Sensor    | Samsung Electronics | ver: 1 | type: com.samsung.sensor.touch_proximity(65596) | perm: n/a | flags: 0x00000003
```

My guess is that we should use first one for hiding AOD, and the second one for powering-off the screen during calls.

**Comment by phhusson** [comment]
Fixed in https://github.com/phhusson/platform_frameworks_base/commit/9b74e9338549 + https://github.com/phhusson/platform_frameworks_native/commit/93922eb194

The user needs to tick "Enable extra sensors" in Samsung section of Treble settings.

This fix only applies to In-call
