### ISSUE TITLE
[AOSP 9.0][Lenovo S5 Pro L58041] 

### ISSUE THREAD

**Issue by jd-0** [phhusson/treble_experimentations#594]
Camera issues: I can take pictures with the stock app _only if flash is set to "On"_. I am able to take photos without flash while using some other apps, ex. Pokemon Go snapshot mode. MTP not working on this phone as well.
Thanks for the time and effort!

**Comment by kiikeep** [comment]
Have you tried enabling camera2api and using arnova's gcam? (ver. 1.7 works fine on K5 Pro)

**Comment by jd-0** [comment]
Camera and MTP issues are resolved now it seems
