### ISSUE TITLE
[MEIZU X8][AOSP 9.0 v115] [Bug]

### ISSUE THREAD

**Issue by bigquan** [phhusson/treble_experimentations#599]
1. MTP can't work.
2. Fingerprint entry is slow and there are errors.
3. The camera focus will flash.
4. Play the video, the video will flash.
5. Can't completely screen, keep a certain brightness when locking the screen.

I hope you can fix it, thank you.

**Comment by phhusson** [comment]
That's 5 different issues so open 5 different issues.

**Comment by bigquan** [comment]
sorry,I don't understand this，
