### ISSUE TITLE
SIM lock after standby for MTK 6797 (Oreo v32)

### ISSUE THREAD

**Issue by BOFH2k** [phhusson/treble_experimentations#608]
My Chuwi Hi9 Air (Helio X20) reports that SIM1 is locked after standby (happens since upgrade from Oreo v31 to v32 via wiping and flashing system in TWRP). This persists until reboot (with entering the SIM PIN).
See: https://github.com/phhusson/treble_experimentations/wiki/Chuwi-Hi9-Air

**Comment by phhusson** [comment]
Pin locked or network locked?

**Comment by BOFH2k** [comment]
The Android status bar message is "No SIM card - no service".
As I wrote before, the PIN dialog comes up on restart once.

**Comment by BOFH2k** [comment]
By the way, BT pairing doesn't work either with v32 - I do get a pin dialog for my Bluetooth keyboard but subsequently the pairing process doesn't complete.
Reverting back to v31 (wipe partition and flash via TWRP) solves this problem - as well as the one with SIM deactivation on standby...

**Comment by penn5** [comment]
For the BT issue check /r/phhtreble, I made a post to debug

**Comment by BOFH2k** [comment]
The BT issue seems to have been caused by a malfunctioning keyboard and the SIM issue was no longer exhibited after a total reset and reinstall of v32.
