### ISSUE TITLE
Kirin950 AOSP camera does not work

### ISSUE THREAD

**Issue by sanshu-rom** [phhusson/treble_experimentations#61]
This is logcat，And when the reading sms, it will be FC，ADB debug mode cannot be used
[log.txt](https://github.com/phhusson/treble_experimentations/files/2053290/log.txt)

**Comment by sanshu-rom** [comment]
Here is the vendor-HAL of kirin950. Do you need to use it?
[Honor.zip](https://github.com/phhusson/treble_experimentations/files/2056404/Honor.zip)

**Comment by sanshu-rom** [comment]
If you have a new test for kirin950, I can test it.

**Comment by phhusson** [comment]
Kirin 950 doesn't have their camera HAL treblized, and are not treble certified.
I won't support this.

But you should be able to find on XDA patches on top of my GSI to include missing libs.
