### ISSUE TITLE
huawei mediapad m5 lite not boot after flash system-arm64-aonly-gapps-su

### ISSUE THREAD

**Issue by butcher197926** [phhusson/treble_experimentations#612]
huawei mediapad m5 lite not boot after flash system-arm64-aonly-gapps-su what i must do?

**Comment by bzntm** [comment]
Some device can't boot GSIs with GApps, try a vanilla GSI and flash a separate GApps instead

**Comment by butcher197926** [comment]
> Some device can't boot GSIs with GApps, try a vanilla GSI and flash a separate GApps instead

Sorry but how flash separate GApps instead? Please tell me. I have a chinese mediapad m5 lite 10 and my friend ask me to do working google store. Sorry for my bad english. So please explain me how i may do it by the shortest solution. The main country of use this tab is Russia i don't need chinese content and apps. I need just working tablet with google)

**Comment by butcher197926** [comment]
I try to flash system-arm64-aonly-vanilla-nosu.img but no effect - device is not boot. Please help(

**Comment by phhusson** [comment]
You need to give more details.

Le jeu. 25 juil. 2019 à 14:06, butcher197926 <notifications@github.com> a
écrit :
