### ISSUE TITLE
[Whyred] Flashes violently when the screen is dimmed

### ISSUE THREAD

**Issue by ivysrono** [phhusson/treble_experimentations#615]
Similar to https://github.com/phhusson/treble_experimentations/issues/72 , maybe.
It can be reproduced while dragging the brightness adjustment bar.
The higher the brightness, the more serious the problem. There is basically no problem when the brightness is zero.

**Comment by penn5** [comment]
Try different settings of the qcom-brightness prop

**Comment by ivysrono** [comment]
By test and test:
bad: 42 and higher.
ok: 41 and lower.

Flashes violently on first boot system on any settings.

**Comment by penn5** [comment]
That's really weird. @phhusson

**Comment by ivysrono** [comment]
Test again.
Any brightness, we can reproduce this issue when switch [MoonReader](https://play.google.com/store/apps/details?id=com.flyersoft.moonreaderp)'s readmode and filelist.

**Comment by suwakowww** [comment]
It should be fixed already on https://github.com/phhusson/device_phh_treble/blob/android-9.0/rw-system.sh#L177

Did you used to flash MIUI EU ROMs?
try to execute following commands to check:
````shell
getprop ro.vendor.build.fingerprint
getprop ro.vendor.build.fingerprint_real
````

If you can't find  `xiaomi/whyred` on  `getprop ro.vendor.build.fingerprint` , or you can get return on `getprop ro.vendor.build.fingerprint_real`, try to flash back stock MIUI first.

**Comment by ivysrono** [comment]
```
phhgsi_arm64_a:/ $ getprop ro.vendor.build.fingerprint
Xiaomi/polaris/polaris:8.0.0/OPR1.170623.032/V9.5.19.0.ODGMIFA:user/release-keys
phhgsi_arm64_a:/ $ getprop ro.vendor.build.fingerprint_real
xiaomi/whyred/whyred:9/PKQ1.180904.001/9.4.18:user/release-keys/1555618074
```

**Comment by suwakowww** [comment]
> phhgsi_arm64_a:/ $ getprop ro.vendor.build.fingerprint
> Xiaomi/polaris/polaris:8.0.0/OPR1.170623.032/V9.5.19.0.ODGMIFA:user/release-keys
> phhgsi_arm64_a:/ $ getprop ro.vendor.build.fingerprint_real
> xiaomi/whyred/whyred:9/PKQ1.180904.001/9.4.18:user/release-keys/1555618074

If you get this return, I can sure you used to flash MIUI EU.
Try to edit `/vendor/build.prop`, then change:
````
ro.vendor.build.fingerprint=Xiaomi/polaris/polaris:8.0.0/OPR1.170623.032/V9.5.19.0.ODGMIFA:user/release-keys
````
to:
````
ro.vendor.build.fingerprint=xiaomi/whyred/whyred:9/PKQ1.180904.001/9.4.18:user/release-keys/1555618074
````
It can let you keep **current** vendor, or you should flash back stock MIUI first.
Don't forget to reboot (to take effect).

**Comment by ivysrono** [comment]
Thanks you very much. I may fix it by flash back stock MIUI, however, I can't boot phh's treble any more. I'm using AospExtended ROM now.
Thank you anyway.
