### ISSUE TITLE
【lenovo z5 9.0】Notification light is not working.

### ISSUE THREAD

**Issue by taoaoooo** [phhusson/treble_experimentations#619]
Test this feature with Light flow app.
![Screenshot_20190803-045932](https://user-images.githubusercontent.com/23213458/62399160-72b5d680-b5ad-11e9-84b3-ea7f39254e39.png)
[logging 。Verification code：o00m](https://pan.baidu.com/s/1dly_sth25NtXCcPKACW3oA)

**Comment by Iy204** [comment]
Lenovo Vendor problem . use Mokee for lenovo z5 Vendor .

**Comment by taoaoooo** [comment]
> 
> 
> Lenovo Vendor problem . use Mokee for lenovo z5 Vendor .

Yes, I'm already using it
