### ISSUE TITLE
No navigation gesture - AOSP 9.0 v117 amd64 aonly - poplar G8341

### ISSUE THREAD

**Issue by duffman128** [phhusson/treble_experimentations#626]
No navigation gesture after flashing system-arm64-aonly-vanilla-nosu.img (AOSP 9.0 v117), Magisk-v19.3(19300).zip and gapps for the Sony Xperia XZ1 poplar G8341 (single SIM).

**Comment by TadiT7** [comment]
The culprit is one of the overlays located here (unless you have no navbar at all):
https://github.com/AndroidDumps/sony_poplar_dsds_dump/tree/poplar_dsds-user-9-YOSHINO-2.2.0-190725-0908-1-dev-keys/vendor/overlay

You need to follow this guide to override the default overlay by Sony:
https://github.com/phhusson/treble_experimentations/wiki/How-to-create-an-overlay%3F

**Comment by phhusson** [comment]
@duffman128 just to be clear, in my AOSP, gesture is disabled by default, but you can enable it in the Settings.
Did you try that?

@TadiT7 fwiw I grep-ed vendo with config_swipe_up_gesture_setting_available and got no result

**Comment by TadiT7** [comment]
> @TadiT7 fwiw I grep-ed vendo with config_swipe_up_gesture_setting_available and got no result

There's also this to check, but it also may be just the user
https://github.com/AndroidDumps/sony_poplar_dsds_dump/tree/poplar_dsds-user-9-YOSHINO-2.2.0-190725-0908-1-dev-keys/oem

**Comment by phhusson** [comment]
`oem` is an extension of `system`; `product` is an extension of `vendor`.
Since overlays doesn't exist in `system`, but `vendor`, they can exist in
`product` but not `oem`

Anyway the grep didn't return anything in oem

**Comment by phhusson** [comment]
Errr right, there can be overlays in system or oem, just not static ones

**Comment by duffman128** [comment]
@TadiT7
I had no navigation at all.

@phhusson
The option wasn't there. It's as if my device was taken as one with physical buttons.

I haven't tried v119 yet. I'll probably wait for the next security patched version.

**Comment by duffman128** [comment]
By the way, is there a forum where I can ask general questions?

**Comment by duffman128** [comment]
Still no navigation for v119.

**Comment by duffman128** [comment]
Navigation Bar is now visible on v123
