### ISSUE TITLE
[Xiaomi Mi CC9e] [AOSP 9.0 v117] loudspeaker noise & popping & China Telecom SIM cannot call out

### ISSUE THREAD

**Issue by liuhxq990619** [phhusson/treble_experimentations#628]
Hey, I just flashed the AOSP v117 on my Xiaomi CC9e. Things work fine exclude loudspeker and TeleService. My loudspeaker has noise when playing. The China Telecom SIM card cannot call out and receive SMS. But the Cellular works fine.

Here is the full bug report file.
[https://mega.nz/#!biRhiaLI!y6JFliyOvlvvcTRwIAZ8Bu6yNJTQC52MbplqVc8tuF8](url)

ThX.

**Comment by suwakowww** [comment]
for broken sound, you can check this: https://github.com/phhusson/device_phh_treble/blob/android-9.0/rw-system.sh#L184
try to add your device into (can check by `getprop ro.vendor.build.fingerprint`) and wait next version (or edit `/system/bin/rw-system.sh` directly by yourself)

for China Telecom, try to close ...... “enable...4g lte...”

算了，顺手写一份中文吧...
爆音的话看上面给你的那个链接，按格式加上你手机的代号（用`getprop ro.vendor.build.fingerprint`可以查）然后等下一个版本（你想现在修复可以自己改`/system/bin/rw-system.sh`）
至于电信，把那个什么“启用增强型4g lte”什么关了应该就好了

**Comment by liuhxq990619** [comment]
谢谢！已经修改完成！
