### ISSUE TITLE
[Huawei P20 lite] Extreme overheat on quick charge

### ISSUE THREAD

**Issue by Dekamir** [phhusson/treble_experimentations#63]
**Happens in:** All Treble ROMs (all developers, builds, revisions, bases) are affected.

**Issue:** Phone gets severely hot while fast charging. It damages the phone.
**Adapter:** Huawei Quick Charge - Output: 5V-2A or 9V-2A

**Workaround:** Use a really low output charger (such as Apple iPhone's standard ones).
_A bad workaround. I recommend you to not use external adapters._

**Comment by phhusson** [comment]
Since the inclusion of Treble app, there is a user switch to select the charge speed
