### ISSUE TITLE
[Huawei P20 Lite] Fingerprint enrollment didn't work

### ISSUE THREAD

**Issue by washinson** [phhusson/treble_experimentations#632]
When I try to add new fingerprint I get this error.
![Screenshot_20190816-093247](https://user-images.githubusercontent.com/26326871/63158679-75d7aa80-c022-11e9-9acb-1d5cb85be180.png)

adb logcat > a.txt [a.txt](https://github.com/phhusson/treble_experimentations/files/3508968/a.txt)
adb logcat *:E > e.txt [e.txt](https://github.com/phhusson/treble_experimentations/files/3508970/e.txt)

P.S. Fingerprint gestures don't work. SELinux is enabled.

**Comment by penn5** [comment]
Duplicate.
