### ISSUE TITLE
not able to flash GAPPS for s10+

### ISSUE THREAD

**Issue by manofsteel2017** [phhusson/treble_experimentations#647]
Hi Phh, thanks for your hard work.
118/119 works great on s10+
except If i flash gapps su img version. Viper4android doesn't work and many rooted apps. given black screen due to conflict and Magisk doesn't pick up any root apps only Su does. 
even if i disabled Su but ended up not getting root at all if i do. 
I can't flash Gapps. it does flash but nothing is there after reboot. If i flash stock opengapps i got forced close. 
can we get a build with gapps without Su since most phones specially samsung ones will have magisk there anyway so it's reduntant to have both 
Thank you

**Comment by phhusson** [comment]
None of my Samsung devices use magisk :p

You can un-install included su by running phh-securize.sh



Le ven. 23 août 2019 à 15:17, manofsteel2017 <notifications@github.com> a
écrit :

**Comment by phhusson** [comment]
uh? Why would you remove it, anyway just flash image again?

Le ven. 23 août 2019 à 16:09, manofsteel2017 <notifications@github.com> a
écrit :

**Comment by manofsteel2017** [comment]
very annoying supersu out of date message as well

**Comment by Flatty11** [comment]
> btw, how do i run that phh-securize.sh line
> sorry noob

adb shell
su
phh-securize.sh 0

**Comment by manofsteel2017** [comment]
all good. 
thanks
