### ISSUE TITLE
Unable to exit "screen pinning"

### ISSUE THREAD

**Issue by JonnyTech** [phhusson/treble_experimentations#655]
Using the AOSP9 GSI in "Android Go" mode on a Redmi Go phone, it is impossible to exit "screen pinning" mode because there is no overview button available - one needs to hold down both back and overview buttons to exit. The only choice is to forcibly restart the phone. Is there a workaround?

**Comment by phhusson** [comment]
Enable software navigation bar?
Do you know what stock rom does? (I'm guessing it shows nav bar when
enabling screen pinning)

**Comment by JonnyTech** [comment]
Hmm, @phhusson, how to enable software navigation bar? I cannot find that option.

I do not know about stock as I flashed this GSI on the day that I got the phone..

**Comment by phhusson** [comment]
run `setprop persist.sys.phh.mainkeys 0` then reboot

**Comment by JonnyTech** [comment]
After executing `setprop persist.sys.phh.mainkeys 0` then rebooting there is no change.

**Comment by JonnyTech** [comment]
Issue #672 confirms my experience that that property change does not work on a Redmi Go.

**Comment by JonnyTech** [comment]
@phhusson, revisiting this as have returned to your GSI, running `AOSP 10.0 v215` still on Redmi Go.

The command `setprop persist.sys.phh.mainkeys 0` now works and switches the soft keys on and off:

![nosoft1](https://user-images.githubusercontent.com/3584732/80801756-40212480-8ba5-11ea-8154-c77de03e8b38.png)

![soft1](https://user-images.githubusercontent.com/3584732/80801779-516a3100-8ba5-11ea-9677-a1bd4f52daf2.png)

So trying screen pinning by selecting the pin with soft keys disabled and enabled:

![nosoft2](https://user-images.githubusercontent.com/3584732/80801843-85455680-8ba5-11ea-9941-793df1c5aa18.png)

![soft2](https://user-images.githubusercontent.com/3584732/80801854-8a0a0a80-8ba5-11ea-8418-2711486c15c0.png)

The informational message appears once pinned:

![nosoft3](https://user-images.githubusercontent.com/3584732/80801919-c0e02080-8ba5-11ea-8b0d-339b5fdea833.png)

![soft3](https://user-images.githubusercontent.com/3584732/80801933-c9385b80-8ba5-11ea-8c35-786dfa77bee0.png)

Do you notice the difference between them?

With softkeys disabled: Touch & hold Back and **Home** to unpin.

With softkeys enabled: Touch & hold Back and **Overview** to unpin.

Great - my device has built in keys for `context menu`, `home` and `back` - but not an `overview` button:

![xiaomi-redmi-go-1-nq8](https://user-images.githubusercontent.com/3584732/80802572-968f6280-8ba7-11ea-817e-1b3a0d39403c.png)

So it should be possible to exit screen pinning without having soft keys, therefore gaining screen estate...

But alas, it does not work. It is still impossible to exit by holding down the **back** and **home** buttons.

Do you have any further suggestions on how to exit screen pinning without enabling the soft keys?

**Comment by 0x15f2d** [comment]
Since Android 9 or 8. AOSP allows you just holding back button to exit the pinning if you only have physical keys. It didn't work with Android 5 previously and it needs oem to modify it. Try holding back whether having software keys on or off.

And do you know what .prop file locaton can overwrite all commands I put in?

Because im trying to set the phh or aosp property of software keys but i am unable to set it to 1

I tried default.prop from vendor, prop.default from system etc (My current android 10 build on root folder redirects default.prop to /system/etc) but they didnt work at all

Because I know those place that Android will pick first but seems like there is something else that has higher priority than those file.

**Comment by JonnyTech** [comment]
Much better on Android 11 - no more buttons issue!

![Imagepipe_0](https://user-images.githubusercontent.com/3584732/100225781-a93c0100-2f16-11eb-8b69-23ddf57d6f7c.jpg)
