### ISSUE TITLE
Can't flash system on a Wiko phone

### ISSUE THREAD

**Issue by Radeoxx** [phhusson/treble_experimentations#656]
I just tried to install this on my Wiko Lenny 5 as I seen it works on my phone at the wiki.

The problem is when I'm flashing it outputs this:

```
D:\Minimal ADB and Fastboot>fastboot flash system system-arm32_binder64-aonly-vanilla-nosu.img
target reported max download size of 134217728 bytes
erasing 'system'...
OKAY [  0.019s]
sending sparse 'system' 1/8 (131068 KB)...
OKAY [  4.175s]
writing 'system' 1/8...
FAILED (remote: sparse image size span overflow.)
finished. total time: 4.207s
```

I tried all the files available, just if I got the wrong one (still dont know how this nomenclature works very well) and around 4s it fails giving me the overflow.

**Comment by Radeoxx** [comment]
Sorry, I did it wrong, everything works fine now. Closing thread.

**Comment by lgierth** [comment]
@Radeoxx could you tell me what you changed to fix this? I'm seeing the same on a Nokia 1 Plus.
