### ISSUE TITLE
 havoc bootloop fix on axon 7 ( audio policy rooting fix )

### ISSUE THREAD

**Issue by atakan33** [phhusson/treble_experimentations#673]
Device axon 7 
vendor 8.1 
on havoc 2.9
i will say from havoc gsi developer vince31fr's words
Hi axon7 users, one thing that could be tried first is to delete the line 329 of the file /system/bin/rw-system.sh :
mount -o bind /mnt/phh/empty_dir /vendor/etc/audio || true

This line hides the vendor audio policy configuration, and maybe some changes in the default GSI audio policy configuration has a problem with your device.
It is in a recent addition of phhusson for fixing routes for Qualcomm devices.
fix is audio policy rooting

**Comment by phhusson** [comment]
Deleting this line is no fix, it will break a2dp on caf roms. 
But a fix for this issue has already been merged.

**Comment by atakan33** [comment]
thanks
