### ISSUE TITLE
bootloop v200 Mi 9

### ISSUE THREAD

**Issue by Logan-AnDev** [phhusson/treble_experimentations#675]
Hi, your latest prerelease based on android 10 causes a bootloop on the Mi 9.

**Comment by Niktendo** [comment]
Yes, I also ended in a bootloop.

**Comment by phhusson** [comment]
On pie vendor?
Logs?

**Comment by penn5** [comment]
Mi9 doesn't have Oreo

**Comment by phhusson** [comment]
It does have q beta

**Comment by biboyrafik25** [comment]
Stucks on logo miui too with 200 and 200a for my mi9 with pie vendor. Salutations

**Comment by Logan-AnDev** [comment]
Hi, I have the latest pie vendor installed on my phone.

**Comment by Logan-AnDev** [comment]
But its normal that the 200a version is very smaller than the 200 version ?

**Comment by biboyrafik25** [comment]
So its works for u ?

**Comment by Logan-AnDev** [comment]
No, i can't boot on this rom ether in v200 than in v200a.

**Comment by biboyrafik25** [comment]
I have a bootloop with all release.....already tried with fw+vendor Xiaomi.eu Android Q

**Comment by Logan-AnDev** [comment]
Me too, but the versions based on Android pie are working for me, but not the versions based on Android 10.

**Comment by Niktendo** [comment]
v200.d completely boots on Pie vendor but stucks at the Android boot logo on official Q vendor.

**Comment by phhusson** [comment]
I thought Mi 9 only had beta Q vendors, not actual release Q release

**Comment by Logan-AnDev** [comment]
> v200.d completely boots on Pie vendor but stucks at the Android boot logo on official Q vendor.

Thank you for your answers, i will try it.

**Comment by Logan-AnDev** [comment]
> v200.d completely boots on Pie vendor but stucks at the Android boot logo on official Q vendor.

How did you proced to install it. I have tryed, but my mi 9 bootloop on the mi logo. Could you help me please?

**Comment by biboyrafik25** [comment]
Boot OK for me. I was on havoc os gsi. Format data flash gsi and reboot

**Comment by Logan-AnDev** [comment]
Thank you, i have now successfully booted into the v200.d.
