### ISSUE TITLE
AOSP v10.0 v200 bootloop Umidigi A1 Pro

### ISSUE THREAD

**Issue by stevea76** [phhusson/treble_experimentations#676]
Umidigi A1 Po, VNDK 27, arm64 a only, 4.4.95 kernel, mt6739 8.1

Bootloop flashed system image on stock firmware.
I have attached files from /sys/fs/pstore  & last_kmsg

[UmidigiA1_Pro.zip](https://github.com/phhusson/treble_experimentations/files/3613975/UmidigiA1_Pro.zip)

**Comment by stevea76** [comment]
AOSP v10.0 v200a the same

**Comment by phhusson** [comment]
Boot is prevented by Audio HAL not starting.
From what I've seen on other devices, it could be because of lack of libgraphicsenv.so
