### ISSUE TITLE
Moto G6 Plus fingerprint scanner not recognized.

### ISSUE THREAD

**Issue by imprezzion** [phhusson/treble_experimentations#68]
ROM thinks the fingerprint is a rear mounted scanner but it is a front mounted thumb scanner. It does not respond.

**Comment by rakeeboy** [comment]
Here is the logs
[](https://drive.google.com/file/d/1vj1cjhC8rilnv9VfE9uO9rSoGIABRAgF/view?usp=drivesdk)

**Comment by phhusson** [comment]
Can you test on my latest AOSP v21?
The ROM you're using (is it one of mine? which one?) has a broken fingerprint. I'm amazed you can boot

**Comment by rakeeboy** [comment]
Yes, I'm using the aosp v21, it can boot, everything is ok,just the
fingerprint not work.

Pierre-Hugues HUSSON <notifications@github.com> 于 2018年7月2日周一 下午5:18写道：

**Comment by rakeeboy** [comment]
Any news?

**Comment by phhusson** [comment]
So the issue has been debugged.
The issue is that Motorla uses group names that doesn't exist in AOSP, which leads to several things being not accessible from fingerprint HAL:

```
#Stock init does chown system:tmot_cmd
chown system:9015  /sys/devices/soc/soc:fpc_fpc1020/irq
chown system:9015  /sys/devices/soc/soc:fpc_fpc1020/irq_cnt
#Stock init uses group called "fingerp"
chown system:9015 /data/.fps
```
