### ISSUE TITLE
Stuck bootlogo Redmi Go AOSP 10 V200.a

### ISSUE THREAD

**Issue by proganime1200** [phhusson/treble_experimentations#680]
stock android android bootanimation
image used:system-quack-arm-a.img.xz
/twrp recovery log/
[recovery1.log](https://github.com/phhusson/treble_experimentations/files/3615079/recovery1.log)
[recovery.log](https://github.com/phhusson/treble_experimentations/files/3615080/recovery.log)

/proc/last_kmsg
[last_kmsg.txt](https://github.com/phhusson/treble_experimentations/files/3615113/last_kmsg.txt)

**Comment by intelligentclaws** [comment]
Mine Redmi GO booting fine on v200.a
Wifi not working
gms service shows null for all notification contents

**Comment by proganime1200** [comment]
How did yoo do it??

**Comment by proganime1200** [comment]
nevermind it looks like installing stock unmodified boot.img booted android 10
