### ISSUE TITLE
(aosp-10 gsi) Camera doesnt work on axon 7 8.1 vendor

### ISSUE THREAD

**Issue by atakan33** [phhusson/treble_experimentations#686]
camera doesnt work 8.1 vendor 
A only 
here is the logcat
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/3617869/logcat.txt)
 

09-16 21:15:46.402 I/ServiceManagement(720): getService: Trying again for android.hardware.camera.provider@2.4::ICameraProvider/legacy/0...

**Comment by phhusson** [comment]
Why is this closed?

**Comment by atakan33** [comment]
because i cannot answer for this

**Comment by atakan33** [comment]
and this log from v200.a maybe logs changed
