### ISSUE TITLE
Moto G6 Plus GPS not working.

### ISSUE THREAD

**Issue by imprezzion** [phhusson/treble_experimentations#69]
GPS is not working at all. No signal or sattelites found.

**Comment by phhusson** [comment]
Grmbl, works fine on Moto E5.

**Comment by phhusson** [comment]
I've got a report that it is working, but this might be because of https://github.com/phhusson/vendor_hardware_overlay/commit/be28959c5aac3d9b4ae1add812fe5d1748ec2bd2
So I'll set this issue as "check with next release"
