### ISSUE TITLE
V200 arm64 Umidigi one max

### ISSUE THREAD

**Issue by th3d3ck3r** [phhusson/treble_experimentations#694]
I'm using the stock 8.1 vendor and when I start the phone it stays at the boot logo. No boot animation or anything just. Boot logo. The pie build work. Q does not

**Comment by th3d3ck3r** [comment]
Also I don't believe this phone has a 9 vendor.

**Comment by proganime1200** [comment]
use v200b and use stock boot.img

**Comment by th3d3ck3r** [comment]
with stock boot.img is defaults to fast boot and with magisk patched boot.img with and without the 200 phh magisk.

**Comment by th3d3ck3r** [comment]
> with stock boot.img is defaults to fast boot and with magisk patched boot.img with and without the 200 phh magisk.

it bootloops with no animation with magisk. sorry lol im new to this

**Comment by th3d3ck3r** [comment]
i am using the arm64 a only

**Comment by phhusson** [comment]
Uninstall Magisk, and get me logs from recovery :

/sys/fs/pstore and /proc/last_kmsg

Does my pie work fine?


Le mer. 18 sept. 2019 à 06:02, th3d3ck3r <notifications@github.com> a
écrit :

**Comment by th3d3ck3r** [comment]
yes pie works close to perfect... and i am going to do a complete reflash of the stock os then i will send you the logs tomorrow after work.

**Comment by drkiro** [comment]
Install the V200c, and I boot without problems, it works wifi, phone, data, fails to configure bluetooth

**Comment by th3d3ck3r** [comment]
> Install the V200c, and I boot without problems, it works wifi, phone, data, fails to configure bluetooth

with or without magisk

**Comment by th3d3ck3r** [comment]
it does boot v200c and magisk

**Comment by drkiro** [comment]
Yes, just start with Magisk and v200c

**Comment by th3d3ck3r** [comment]
boots well
