### ISSUE TITLE
Auto brightness does not work on oneplus 6

### ISSUE THREAD

**Issue by isnehalkiran** [phhusson/treble_experimentations#70]
sir,
brightness is always to 100% on oneplus 6.
Auto brightness is not working.
May be implementing something like this https://github.com/TheStrechh/android_device_xiaomi_msm8956-common/commit/9cd913bf4453c010e8e42d946d9bee537a86f1c8 will fix the auto brightness!!

thank you for your awesome work!!!

**Comment by phhusson** [comment]
Fixed with https://github.com/phhusson/vendor_hardware_overlay/commit/f101c458f423ccd96a181c40ba7c97b24d7531a4

**Comment by cawilliamson** [comment]
@phhusson Just wanted to confirm - this one is resolved and can be closed. 👍
