### ISSUE TITLE
[Samsung Galaxy S10 Snapdragon] Torch not working

### ISSUE THREAD

**Issue by Fzndox** [phhusson/treble_experimentations#711]
On V119 Phh Treble the torch is not working from the pulldown, however the camera flash is working.

I believe there may be a simple fix for this that I am unaware of. I believe other samsung models may have this issue.

**Comment by manofsteel2017** [comment]
Also not working on Android 10

**Comment by Fzndox** [comment]
Does anyone have any updates with regards to this?

**Comment by Fzndox** [comment]
This is fixed as per v216. Tested on the SM-G9730.
