### ISSUE TITLE
[Samsung Galaxy S10 Snapdragon] 200c not booting up?

### ISSUE THREAD

**Issue by manofsteel2017** [phhusson/treble_experimentations#713]
seems like no luck on SD S10+
stuck on  s10+ logo even after flashing phh magisk 
without it same issue

**Comment by manofsteel2017** [comment]
i flashed arm64 AB btw

**Comment by phhusson** [comment]
remove /system/etc/init/apex-setup.rc

Le ven. 20 sept. 2019 à 21:11, manofsteel2017 <notifications@github.com> a
écrit :

**Comment by manofsteel2017** [comment]
genius as always 
but no navbar and no playstore lol

**Comment by manofsteel2017** [comment]
for navbar 
add the line qemu.hw.mainkeys=0 in build.prop file

and for gapps download open gapps test arm64 10 from sourceforge 
everything is good for now
will open another ticket for any other issues
