### ISSUE TITLE
Moto G6 no boot (AOSP 10.0 v200.c)

### ISSUE THREAD

**Issue by luisdambrowski** [phhusson/treble_experimentations#716]
Moto g6 does not start after flash gsi!

-> system-quack-arm-a.img.xz

**Comment by ankitshah009** [comment]
Any updates received for this would be useful. Same issue faced by using above image on Lenovo P2 phone.

**Comment by phhusson** [comment]
yeah sure ""same issue"".
You also have a moto_keystore selinux class?

Le dim. 29 sept. 2019 à 17:41, Ankit Shah <notifications@github.com> a
écrit :

**Comment by luisdambrowski** [comment]
GSI starts but you need flash from lineageOS first!

**Comment by MarcosPearce** [comment]
what did you do to start ??  on mine it does not boot

**Comment by luisdambrowski** [comment]
flash lineageOs before gsi;

https://t.me/MotorolaG6
