### ISSUE TITLE
j4primelte(Galaxy J4+) no boot

### ISSUE THREAD

**Issue by elfennani** [phhusson/treble_experimentations#721]
My phone does not boot to aosp, no boot animation, just a bootloop. PLZ help.

I think I can't install Android 10 in this device, right?

**Comment by phhusson** [comment]
I guess you're speaking of v200.c
Have you installed my modified Magisk as instructed in the release notes?

Le dim. 22 sept. 2019 à 13:18, elfennani <notifications@github.com> a
écrit :

**Comment by elfennani** [comment]
Yes, I've installed it but no luck

**Comment by phhusson** [comment]
So it's stuck on bootloader logo or it reboots? 
Have you checked if you have adb working?

**Comment by elfennani** [comment]
just an infinite reboot on bootloader

**Comment by phhusson** [comment]
V119 boots?

**Comment by elfennani** [comment]
No I didn't tried it yet

**Comment by SebaUbuntu** [comment]
> No I didn't tried it yet

I have made it work, see https://forum.xda-developers.com/galaxy-j4+/development/booting-q-gsi-j4-t3970469

**Comment by elfennani** [comment]
Thanks, I've tried that already, but the problem was that phizero kernel is made only for android pie, but now it is updated.

**Comment by SebaUbuntu** [comment]
So now it work to you right? If yes, then good (I think you can close this thread)

**Comment by elfennani** [comment]
Yes it worked, thanks =)

**Comment by SebaUbuntu** [comment]
I'm glad my guide have worked :)
