### ISSUE TITLE
Blackscreen while offline-charging on kirin devices

### ISSUE THREAD

**Issue by darkestDark** [phhusson/treble_experimentations#73]
System: Lineage Treble vanilla
The Pictures for Offlinecharging are integrated in Rom by Huawei. The Charger expect them in /system/etc/charger.

Files are uploaded here:
https://mega.nz/#!RuZBnLrZ!67u8lOgNoZ2ynnMWbu9wVDNAbvlTUsAcbpmBqctThzY

**Comment by Dil3mm4** [comment]
Add them in your build and call it a day :)

**Comment by darkestDark** [comment]
the day was yesterday :)
i can't build it as magisk module (like kirin nfc), cause its not added in offline mode than. And readd it after every update ain't got fun. And a ln-s...? Don't know a target...
Btw... "i care about LOS"... ;)

**Comment by phhusson** [comment]
Well make a zip that contains it + HwCamera2

**Comment by Dil3mm4** [comment]
@phhusson if you're interested I could do "all resolutions treble-themed" charger images that could be inherited.

**Comment by darkestDark** [comment]
in my first post the images from charger are included with subdirs in the zip on Mega.

The Camera itself isnt read for including in Rom... there are two bugs left (atm i'm out of time to debug)...

**Comment by phhusson** [comment]
I'll put that in #241
