### ISSUE TITLE
Graphic rendering not working on Samsung J4+ (SM-J415xx)

### ISSUE THREAD

**Issue by SebaUbuntu** [phhusson/treble_experimentations#730]
[webview.txt](https://github.com/phhusson/treble_experimentations/files/3653940/webview.txt)

Almost everything related to 2D acceleration doesn't work
The major issue to me is webview not working (logs provided trying to open Webview Shell, it just don't load anything), so because of this problem, I can't login to Google.

Using AOSP GSI 200.C (Android 10)
Pie vendor

**Comment by elfennani** [comment]
Yeah, I have same issue here
