### ISSUE TITLE
(Samsung Galaxy S9+ Exynos SM-G965F) 

### ISSUE THREAD

**Issue by mssadewa** [phhusson/treble_experimentations#733]
Helo,

Thanks for treble android 10. 👍 
I've tested latest prerelease aosp 10.0 v200.c on my Galaxy S9+ Exynoss SM-G965F with
- Official TWRP 3.3.1-0
- From Latest Stock Firmware CSH5 (Sep '19)
- Endurance AOSP kernel 2.0.27
- Vendor from latest Stock Oreo Firmware BRJ6 (Oct '18)

What I do : 
- Flash Latest (CSH5) Firmware
- Install TWRP
- Install no dm-verity patch
- Flash oreo vendor
- Flash your system image (system-quack-arm64-a.img)
- Flash Endurance Kernel

Boot up normally and smoothly.

What doesn't work : 
- No navigation.
- Freeze or Hang when access settings.
- Can't enable wifi.
- Simcard is not detected.
- Can't logcat since I can't enable usb debugging.

Here is dmesg and recovery logs.
[logs_201909292036.zip](https://github.com/phhusson/treble_experimentations/files/3667388/logs_201909292036.zip)

Thanks for the great and amazing work 👍

**Comment by riyaadh47** [comment]
I did everything you did and I managed to get my system booted. Thanks.
To fix the issues you're having, flash Endurance GSI Kernel. It works perfectly for me.

**Comment by mssadewa** [comment]
Hi @riyaadh47,
Glad to hear that's works for you. awesome!
I was using endurance kernel too, Did u mean endurance kernel gsi v 1.2.33?

**Comment by riyaadh47** [comment]
Yup. That Kernel works great for me. Everything that's not working for you, is working for me.

**Comment by mssadewa** [comment]
Hi @riyaadh47,
The latest release of Endurance GSI kernel not works for me, it just stuck at samsung boot logo.
Could you may to share what setup for your device?

Thank you.

**Comment by riyaadh47** [comment]
I have the exact same setup as you. Only difference is I have Firmware CSG4.

**Comment by mssadewa** [comment]
Didn't find CSG4, Just found CSG8.
Tried it 4 times with no luck. 

Thanks for hints 👍

**Comment by riyaadh47** [comment]
Try this:
https://drive.google.com/open?id=1deYMi_3pActMUfTpWdrFWODTVvRQB_q5

**Comment by mssadewa** [comment]
Just flash that zip through twrp? should I flash it after or before the vendor image?

**Comment by riyaadh47** [comment]
Yes, flash through TWRP. If the Vendor is already flashed, it shouldn't matter.

**Comment by mssadewa** [comment]
Thanks @riyaadh47,
Flashing with endurance kernel aosp 1.2.xx it works with navbar but the device is always getting hot and the bluetooth is always stopped working.
Since this image works with you, I guess there is something wrong with my device or method. So, I closed this ticket.
