### ISSUE TITLE
[Lenovo S5]Headphone doesn't be recognized.

### ISSUE THREAD

**Issue by QiMingWH** [phhusson/treble_experimentations#75]
I flashed a GSI called PixelExperience.When I put my headphone on my cell phone, my cell phone didn't respond, and the music still played from the speaker.It is still the same after rebooting, and the same headphone can be used normally on other phones.

The log is that：--------- beginning of main
06-07 20:23:16.328 W/Notification( 5814): Use of stream types is deprecated for operations other than volume control
06-07 20:23:16.328 W/Notification( 5814): See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
06-07 20:23:17.292 I/PushManager( 3277): WebSocketClient::appStateChanged state changed from 1 to 2), self = 0xc7098010.
06-07 20:23:17.329 W/Notification( 5814): Use of stream types is deprecated for operations other than volume control
06-07 20:23:17.329 W/Notification( 5814): See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
06-07 20:23:17.614 D/audio_hw_primary(  611): out_standby: enter: stream (0xf47e4000) usecase(1: low-latency-playback)
06-07 20:23:17.762 D/audio_hw_primary(  611): disable_audio_route: reset and update mixer path: low-latency-playback
06-07 20:23:17.764 D/soundtrigger(  611): audio_extn_sound_trigger_update_stream_status: uc_id 1 of type 0 for Event 2, with Raise=0
06-07 20:23:17.765 D/hardware_info(  611): hw_info_append_hw_type : device_name = speaker
06-07 20:23:17.765 D/audio_hw_primary(  611): disable_snd_device: snd_device(2: speaker)
06-07 20:23:17.765 D/msm8916_platform(  611): platform_split_snd_device: snd_device(2) num devices(0) new_snd_devices(0)
06-07 20:23:17.773 I/soundtrigger(  611): audio_extn_sound_trigger_update_device_status: device 0x2 of type 0 for Event 0, with Raise=0
06-07 20:23:17.773 D/audio_hw_primary(  611): out_standby: exit
06-07 20:23:18.331 W/Notification( 5814): Use of stream types is deprecated for operations other than volume control
06-07 20:23:18.331 W/Notification( 5814): See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
06-07 20:23:18.667 D/audio_hw_primary(  611): start_output_stream: enter: stream(0xf47e4000)usecase(1: low-latency-playback) devices(0x2)
06-07 20:23:18.667 E/ANDR-PERF-MPCTL(  633): Invalid profile no. 0, total profiles 0 only
06-07 20:23:18.668 D/audio_hw_primary(  611): select_devices for use case (low-latency-playback)
06-07 20:23:18.668 D/audio_hw_primary(  611): select_devices: out_snd_device(2: speaker) in_snd_device(0: )
06-07 20:23:18.668 D/audio_hw_primary(  611): check_usecases_codec_backend:becf: check_usecases num.of Usecases to switch 0
06-07 20:23:18.668 D/hardware_info(  611): hw_info_append_hw_type : device_name = speaker
06-07 20:23:18.668 D/msm8916_platform(  611): platform_split_snd_device: snd_device(2) num devices(0) new_snd_devices(0)
06-07 20:23:18.668 D/audio_hw_primary(  611): enable_snd_device: snd_device(2: speaker)
06-07 20:23:18.668 I/soundtrigger(  611): audio_extn_sound_trigger_update_device_status: device 0x2 of type 0 for Event 1, with Raise=0
06-07 20:23:18.674 D/soundtrigger(  611): audio_extn_sound_trigger_update_stream_status: uc_id 1 of type 0 for Event 3, with Raise=0
06-07 20:23:18.674 D/audio_hw_utils(  611): audio_extn_utils_send_app_type_cfg: usecase->out_snd_device speaker
06-07 20:23:18.674 D/msm8916_platform(  611): platform_split_snd_device: snd_device(2) num devices(0) new_snd_devices(0)
06-07 20:23:18.675 E/msm8916_platform(  611): platform_get_snd_device_backend_index: BE DAI Name Table is not present
06-07 20:23:18.675 E/audio_hw_utils(  611): send_app_type_cfg_for_device: Couldn't get the backend index for snd device speaker ret=-14
06-07 20:23:18.675 I/audio_hw_utils(  611): send_app_type_cfg_for_device PLAYBACK app_type 69937, acdb_dev_id 14, sample_rate 48000, snd_device_be_idx -14
06-07 20:23:18.675 D/msm8916_platform(  611): platform_split_snd_device: snd_device(2) num devices(1) new_snd_devices(0)
06-07 20:23:18.675 D/ACDB-LOADER(  611): ACDB -> send_audio_cal, acdb_id = 14, path = 0, app id = 0x11131, sample rate = 48000
06-07 20:23:18.675 D/ACDB-LOADER(  611): ACDB -> send_asm_topology
06-07 20:23:18.675 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
06-07 20:23:18.675 D/ACDB-LOADER(  611): ACDB -> send_adm_topology
06-07 20:23:18.675 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
06-07 20:23:18.675 D/ACDB-LOADER(  611): ACDB -> send_audtable
06-07 20:23:18.675 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE_SIZE
06-07 20:23:18.676 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
06-07 20:23:18.676 D/ACDB-LOADER(  611): ACDB -> AUDIO_SET_AUDPROC_CAL
06-07 20:23:18.676 D/ACDB-LOADER(  611): ACDB -> send_audvoltable
06-07 20:23:18.676 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AUDPROC_VOL_STEP_TABLE_SIZE
06-07 20:23:18.676 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE, vol index 0
06-07 20:23:18.676 D/ACDB-LOADER(  611): ACDB -> AUDIO_SET_VOL_CAL cal type = 12
06-07 20:23:18.676 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_SIZE
06-07 20:23:18.676 D/ACDB-LOADER(  611): ACDB -> send_audstrmtable
06-07 20:23:18.676 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_V2
06-07 20:23:18.676 D/ACDB-LOADER(  611): ACDB -> audstrm_cal->cal_type.cal_data.cal_size = 16
06-07 20:23:18.676 D/ACDB-LOADER(  611): ACDB -> send_afe_topology
06-07 20:23:18.676 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AFE_TOPOLOGY_ID
06-07 20:23:18.676 D/ACDB-LOADER(  611): ACDB -> GET_AFE_TOPOLOGY_ID for adcd_id 14, Topology Id 1025e
06-07 20:23:18.676 D/ACDB-LOADER(  611): ACDB -> send_afe_cal
06-07 20:23:18.676 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE_SIZE
06-07 20:23:18.676 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
06-07 20:23:18.676 D/ACDB-LOADER(  611): ACDB -> AUDIO_SET_AFE_CAL
06-07 20:23:18.676 D/ACDB-LOADER(  611): ACDB -> send_hw_delay : acdb_id = 14 path = 0
06-07 20:23:18.676 D/ACDB-LOADER(  611): ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
06-07 20:23:18.676 D/audio_hw_primary(  611): enable_audio_route: apply mixer and update path: low-latency-playback
06-07 20:23:18.677 D/audio_hw_primary(  611): select_devices: done
06-07 20:23:18.735 D/msm8916_platform(  611): platform_set_channel_map mixer_ctl_name:Playback Channel Map12
06-07 20:23:18.735 D/msm8916_platform(  611): platform_set_channel_map: set mapping(1 2 0 0 0 0 0 0) for channel:2
06-07 20:23:18.736 D/audio_hw_primary(  611): start_output_stream: exit
06-07 20:23:18.740 W/StreamHAL(  611): Error from HAL stream in function get_presentation_position: Operation not permitted
06-07 20:23:18.741 W/StreamHAL(  611): Error from HAL stream in function get_presentation_position: Operation not permitted
06-07 20:23:19.409 D/cr_CronetHttpURLConnection( 5184): [CronetHttpURLConnection.java:419] setConnectTimeout is not supported by CronetHttpURLConnection
06-07 20:23:19.448 I/WifiService( 1306): getConnectionInfo uid=10101
06-07 20:23:19.448 D/WifiPermissionsUtil( 1306): Denied: no location permission
06-07 20:23:19.448 D/WifiPermissionsUtil( 1306): Denied: The current config is not for an open network.
06-07 20:23:19.462 I/WifiService( 1306): getConnectionInfo uid=10101
06-07 20:23:19.462 D/WifiPermissionsUtil( 1306): Denied: no location permission
06-07 20:23:19.462 D/WifiPermissionsUtil( 1306): Denied: The current config is not for an open network.
06-07 20:23:19.463 I/WifiService( 1306): getConnectionInfo uid=10101
06-07 20:23:19.463 D/WifiPermissionsUtil( 1306): Denied: no location permission
06-07 20:23:19.463 D/WifiPermissionsUtil( 1306): Denied: The current config is not for an open network.
06-07 20:23:19.468 I/WifiService( 1306): getConnectionInfo uid=10101
06-07 20:23:19.468 D/WifiPermissionsUtil( 1306): Denied: no location permission
06-07 20:23:19.468 D/WifiPermissionsUtil( 1306): Denied: The current config is not for an open network.
06-07 20:23:19.470 I/WifiService( 1306): getConnectionInfo uid=10101
06-07 20:23:19.470 D/WifiPermissionsUtil( 1306): Denied: no location permission
06-07 20:23:19.470 D/WifiPermissionsUtil( 1306): Denied: The current config is not for an open network.
06-07 20:23:19.473 I/WifiService( 1306): getConnectionInfo uid=10101
06-07 20:23:19.474 D/WifiPermissionsUtil( 1306): Denied: no location permission
06-07 20:23:19.474 D/WifiPermissionsUtil( 1306): Denied: The current config is not for an open network.
06-07 20:23:19.489 I/WifiService( 1306): getConnectionInfo uid=10101
06-07 20:23:19.491 D/WifiPermissionsUtil( 1306): Denied: no location permission
06-07 20:23:19.491 D/WifiPermissionsUtil( 1306): Denied: The current config is not for an open network.
06-07 20:23:20.192 I/WifiService( 1306): getConnectionInfo uid=10101
06-07 20:23:20.193 D/WifiPermissionsUtil( 1306): Denied: no location permission
06-07 20:23:20.193 D/WifiPermissionsUtil( 1306): Denied: The current config is not for an open network.
06-07 20:23:20.331 W/Notification( 5814): Use of stream types is deprecated for operations other than volume control
06-07 20:23:20.331 W/Notification( 5814): See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
06-07 20:23:20.438 D/cr_CronetHttpURLConnection( 5184): [CronetHttpURLConnection.java:419] setConnectTimeout is not supported by CronetHttpURLConnection
06-07 20:23:20.704 W/memtrack@1.0-se(  621): type=1400 audit(0.0:7540): avc: denied { search } for name="proc" dev="debugfs" ino=13915 scontext=u:r:hal_memtrack_default:s0 tcontext=u:object_r:qti_debugfs:s0 tclass=dir permissive=0
--------- beginning of system
06-07 20:23:21.090 I/ActivityManager( 1306): Start proc 15319:com.google.android.apps.photos/u0a81 for service com.google.android.apps.photos/com.google.android.libraries.social.mediamonitor.MediaMonitorJobSchedulerService
06-07 20:23:20.704 W/memtrack@1.0-se(  621): type=1400 audit(0.0:7541): avc: denied { search } for name="proc" dev="debugfs" ino=13915 scontext=u:r:hal_memtrack_default:s0 tcontext=u:object_r:qti_debugfs:s0 tclass=dir permissive=0
06-07 20:23:21.329 W/Notification( 5814): Use of stream types is deprecated for operations other than volume control
06-07 20:23:21.330 W/Notification( 5814): See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
06-07 20:23:21.560 I/zygote64(15319): Method exceeds compiler instruction limit: 17332 in void gen_binder.root.RootModule$Generated.a(android.content.Context, java.lang.Class, java.lang.Object, aeln)
06-07 20:23:21.754 W/memtrack@1.0-se(  621): type=1400 audit(0.0:7542): avc: denied { search } for name="proc" dev="debugfs" ino=13915 scontext=u:r:hal_memtrack_default:s0 tcontext=u:object_r:qti_debugfs:s0 tclass=dir permissive=0
06-07 20:23:21.754 W/memtrack@1.0-se(  621): type=1400 audit(0.0:7543): avc: denied { search } for name="proc" dev="debugfs" ino=13915 scontext=u:r:hal_memtrack_default:s0 tcontext=u:object_r:qti_debugfs:s0 tclass=dir permissive=0
06-07 20:23:21.859 D/audio_hw_primary(  611): out_standby: enter: stream (0xf47e4000) usecase(1: low-latency-playback)
06-07 20:23:21.985 D/audio_hw_primary(  611): disable_audio_route: reset and update mixer path: low-latency-playback
06-07 20:23:21.988 D/soundtrigger(  611): audio_extn_sound_trigger_update_stream_status: uc_id 1 of type 0 for Event 2, with Raise=0
06-07 20:23:21.988 D/hardware_info(  611): hw_info_append_hw_type : device_name = speaker
06-07 20:23:21.988 D/audio_hw_primary(  611): disable_snd_device: snd_device(2: speaker)
06-07 20:23:21.988 D/msm8916_platform(  611): platform_split_snd_device: snd_device(2) num devices(0) new_snd_devices(0)
06-07 20:23:21.995 I/soundtrigger(  611): audio_extn_sound_trigger_update_device_status: device 0x2 of type 0 for Event 0, with Raise=0
06-07 20:23:21.995 D/audio_hw_primary(  611): out_standby: exit
06-07 20:23:22.009 I/WifiService( 1306): requestActivityInfo uid=1000
06-07 20:23:22.010 I/WifiService( 1306): reportActivityInfo uid=1000
06-07 20:23:22.010 I/WifiService( 1306): getSupportedFeatures uid=1000
06-07 20:23:22.016 E/WifiHAL (  627): wifi_get_logger_supported_feature_set: Error -3 happened. 
06-07 20:23:22.020 E/WifiVendorHal( 1306): getSupportedFeatureSet(l.891) failed {.code = ERROR_NOT_SUPPORTED, .description = }
06-07 20:23:22.021 E/WifiHAL (  627): wifi_get_logger_supported_feature_set: Error -3 happened. 
06-07 20:23:22.077 E/BatteryExternalStatsWorker( 1306): no controller energy info supplied for bluetooth
06-07 20:23:24.347 D/audio_hw_primary(  611): start_output_stream: enter: stream(0xf47e4000)usecase(1: low-latency-playback) devices(0x2)
06-07 20:23:24.360 D/audio_hw_primary(  611): select_devices for use case (low-latency-playback)
06-07 20:23:24.360 D/audio_hw_primary(  611): select_devices: out_snd_device(2: speaker) in_snd_device(0: )
06-07 20:23:24.360 D/audio_hw_primary(  611): check_usecases_codec_backend:becf: check_usecases num.of Usecases to switch 0
06-07 20:23:24.360 D/hardware_info(  611): hw_info_append_hw_type : device_name = speaker
06-07 20:23:24.360 D/msm8916_platform(  611): platform_split_snd_device: snd_device(2) num devices(0) new_snd_devices(0)
06-07 20:23:24.360 D/audio_hw_primary(  611): enable_snd_device: snd_device(2: speaker)
06-07 20:23:24.360 I/soundtrigger(  611): audio_extn_sound_trigger_update_device_status: device 0x2 of type 0 for Event 1, with Raise=0
06-07 20:23:24.354 E/ANDR-PERF-MPCTL(  633): Invalid profile no. 0, total profiles 0 only
06-07 20:23:24.373 D/soundtrigger(  611): audio_extn_sound_trigger_update_stream_status: uc_id 1 of type 0 for Event 3, with Raise=0
06-07 20:23:24.373 D/audio_hw_utils(  611): audio_extn_utils_send_app_type_cfg: usecase->out_snd_device speaker
06-07 20:23:24.373 D/msm8916_platform(  611): platform_split_snd_device: snd_device(2) num devices(0) new_snd_devices(0)
06-07 20:23:24.373 E/msm8916_platform(  611): platform_get_snd_device_backend_index: BE DAI Name Table is not present
06-07 20:23:24.373 E/audio_hw_utils(  611): send_app_type_cfg_for_device: Couldn't get the backend index for snd device speaker ret=-14
06-07 20:23:24.373 I/audio_hw_utils(  611): send_app_type_cfg_for_device PLAYBACK app_type 69937, acdb_dev_id 14, sample_rate 48000, snd_device_be_idx -14
06-07 20:23:24.374 D/msm8916_platform(  611): platform_split_snd_device: snd_device(2) num devices(1) new_snd_devices(0)
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> send_audio_cal, acdb_id = 14, path = 0, app id = 0x11131, sample rate = 48000
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> send_asm_topology
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> send_adm_topology
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> send_audtable
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE_SIZE
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> AUDIO_SET_AUDPROC_CAL
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> send_audvoltable
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AUDPROC_VOL_STEP_TABLE_SIZE
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE, vol index 0
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> AUDIO_SET_VOL_CAL cal type = 12
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_SIZE
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> send_audstrmtable
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_V2
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> audstrm_cal->cal_type.cal_data.cal_size = 16
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> send_afe_topology
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AFE_TOPOLOGY_ID
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> GET_AFE_TOPOLOGY_ID for adcd_id 14, Topology Id 1025e
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> send_afe_cal
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE_SIZE
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
06-07 20:23:24.374 D/ACDB-LOADER(  611): ACDB -> AUDIO_SET_AFE_CAL
06-07 20:23:24.375 D/ACDB-LOADER(  611): ACDB -> send_hw_delay : acdb_id = 14 path = 0
06-07 20:23:24.375 D/ACDB-LOADER(  611): ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
06-07 20:23:24.375 D/audio_hw_primary(  611): enable_audio_route: apply mixer and update path: low-latency-playback
06-07 20:23:24.375 D/audio_hw_primary(  611): select_devices: done
06-07 20:23:24.429 D/msm8916_platform(  611): platform_set_channel_map mixer_ctl_name:Playback Channel Map12
06-07 20:23:24.429 D/msm8916_platform(  611): platform_set_channel_map: set mapping(1 2 0 0 0 0 0 0) for channel:2
06-07 20:23:24.430 D/audio_hw_primary(  611): start_output_stream: exit
06-07 20:23:24.434 W/StreamHAL(  611): Error from HAL stream in function get_presentation_position: Operation not permitted

**Comment by phhusson** [comment]
Looks like https://github.com/phhusson/treble_experimentations/issues/49
So should be fixed in next release.

**Comment by Luca0101** [comment]
Hi I have a problem with my Lenovo s5... I tried installing firstly Pixel experience rom but after Lenovo's logo it went into fastboot... So I decided to try the AOSP rom but it stucks in android logo... Which commands I should use into fastboot mode to re-flash the rom and overcome the bootloop? Finally if I won't find a solution I would want to return to stock rom but I didn't find it online... Do you have a link?
