### ISSUE TITLE
[10] v.200d Fingerprint-Sensor and Bluetooth @ Redmi Note 7 (lavender)

### ISSUE THREAD

**Issue by darkestDark** [phhusson/treble_experimentations#753]
Logs are [here](https://github.com/darkestDark/phh_aosp_hardware_issues).

Fingerprint seams to be a error in vendor service with signature.
Bluetooth seams to be a lib issue. 

But didnt have a deeper look in it...

**Comment by phhusson** [comment]
Does it work in pie?


Le sam. 5 oct. 2019 à 14:40, darkestDark <notifications@github.com> a
écrit :

**Comment by darkestDark** [comment]
Both, yes.

**Comment by phhusson** [comment]
Fwiw both your logs are unusable, just do a full logcat -b all

Le sam. 5 oct. 2019 à 14:45, darkestDark <notifications@github.com> a
écrit :

**Comment by darkestDark** [comment]
[Here](https://raw.githubusercontent.com/darkestDark/phh_aosp_hardware_issues/master/logcat_10-05-2019_14-48-00.txt) is the full log.

**Comment by darkestDark** [comment]
bluetooth done... was a missing caf-commit. stock kernel (pie) and genom custom kernel dont work... morfuz custom kernel has the commit and bt works...
so only fp sensor is missing...  and here the null value for mdeamon... will take a look on.

**Comment by darkestDark** [comment]
found it.
in /vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc 
the group uhid is not set.
After Adding Hal works. will write a pr...

**Comment by darkestDark** [comment]
Done with 
phhusson/platform_system_core@ef7918d
