### ISSUE TITLE
Media not working (Samsung J4+)

### ISSUE THREAD

**Issue by SebaUbuntu** [phhusson/treble_experimentations#758]
Media not working on Samsung J4+ (SM-J415FN) arm32, pie vendor
[log1.txt](https://github.com/phhusson/treble_experimentations/files/3694917/media.txt)
`10-06 22:23:11.671   699   699 F linker  : CANNOT LINK EXECUTABLE "/vendor/bin/hw/android.hardware.media.omx@1.0-service": library "libpdx_default_transport.so" not found`

1) Tried putting the missing lib 
[libpdx_default_transport.so](https://github.com/phhusson/treble_experimentations/files/3694946/libpdx_default_transport.so.zip)
[log2.txt](https://github.com/phhusson/treble_experimentations/files/3694920/media4.txt)
`10-06 23:29:14.808   705   705 F linker  : CANNOT LINK EXECUTABLE "/vendor/bin/hw/android.hardware.media.omx@1.0-service": cannot locate symbol "_ZN7android24MEDIA_MIMETYPE_AUDIO_AC4E" referenced by "/vendor/lib/libstagefright_omx_vendor.so"...`
This error came

2) result of "grep _ZN7android24MEDIA_MIMETYPE_AUDIO_AC4E -r /vendor/"
```
Binary file /vendor/lib/libstagefright_foundation.so matches
Binary file /vendor/lib/libstagefright_omx_utils.so matches
Binary file /vendor/lib/libstagefright_omx_vendor.so matches
Binary file /vendor/lib/libstagefright_soft_ac4dec.so matches
grep: /vendor/rfs/mdm/cdsp/hlos: No such file or directory
grep: /vendor/rfs/mdm/adsp/hlos: No such file or directory
grep: /vendor/rfs/mdm/tn/hlos: No such file or directory
grep: /vendor/rfs/mdm/mpss/hlos: No such file or directory
grep: /vendor/rfs/mdm/slpi/hlos: No such file or directory
grep: /vendor/rfs/apq/gnss/hlos: No such file or directory
grep: /vendor/rfs/msm/cdsp/hlos: No such file or directory
grep: /vendor/rfs/msm/adsp/hlos: No such file or directory
grep: /vendor/rfs/msm/mpss/hlos: No such file or directory
grep: /vendor/rfs/msm/slpi/hlos: No such file or directory
```
/vendor/lib/libstagefright_foundation.so
[libstagefright_foundation.so.zip](https://github.com/phhusson/treble_experimentations/files/3694942/libstagefright_foundation.zip)

```
nm -D libstagefright_foundation.so|grep AC4 
000260c0 D _ZN7android24MEDIA_MIMETYPE_AUDIO_AC4E
```
This symbol is indeed present in this lib

3) Tried to remove /system/lib/vndk-28/libstagefright_foundation.so
[log3.txt](https://github.com/phhusson/treble_experimentations/files/3694922/media5.txt)
    CANNOT LINK EXECUTABLE "/vendor/bin/hw/android.hardware.media.omx@1.0-service": cannot locate symbol "__system_properties_init" referenced by "/system/lib/vndk-28/libpdx_default_transport.so"...

Resulte of "strace -f -o /data/local/tmp/str /vendor/bin/hw/android.hardware.media.omx@1.0-service":
`CANNOT LINK EXECUTABLE "/vendor/bin/hw/android.hardware.media.omx@1.0-service": cannot locate symbol "__system_properties_init" referenced by "/system/lib/vndk-28/libpdx_default_transport.so"...`
str result:
[str](https://github.com/phhusson/treble_experimentations/files/3694923/str.txt)

**Comment by R0rt1z2** [comment]
A few shims should fix the missings symbol

**Comment by phhusson** [comment]
Yeah right, let's shim open-source components instead of just editing their
source code...

Le mer. 9 oct. 2019 à 09:02, Roger Ortiz <notifications@github.com> a
écrit :

**Comment by R0rt1z2** [comment]
It's just a "quick" fix. I know that the right fix it's add the symbol by editing the repo...

**Comment by phhusson** [comment]
Ah, well please try it then

Le mer. 9 oct. 2019 à 09:06, Roger Ortiz <notifications@github.com> a
écrit :

**Comment by DavivaD** [comment]
Same on J7 (2016). Arm64

**Comment by SebaUbuntu** [comment]
Fixed on v208 (or 207, didn't test)
