### ISSUE TITLE
[Pie] [Galaxy Tab S4] Power off / shutting down on boot

### ISSUE THREAD

**Issue by Avrution** [phhusson/treble_experimentations#776]
No matter what combination I try, or version, the tablet boots very quickly to the setup screen and then immediately shuts down / restarts to recovery.

I can successfully boot Lineage 16 (AndyYan), but this one is giving me trouble.

Tried both plugged in and unplugged.

**Comment by phhusson** [comment]
well give me a logcat

**Comment by Avrution** [comment]
Will work on that - first time doing it.  

Oddly enough, I plugged into a computer to run adb and noticed the tablet will boot this way.  As soon as I unplug, it shuts down.

**Comment by Avrution** [comment]
[filename.txt](https://github.com/phhusson/treble_experimentations/files/3725555/filename.txt)

**Comment by penn5** [comment]
Wipe data.

**Comment by Avrution** [comment]
Well crap, I have tried this at least 10 times from a complete wipe of everything and always had the same result.  

Doing a data wipe after the first boot seems to fix everything.
