### ISSUE TITLE
Turning off display during call by the proximity sensor

### ISSUE THREAD

**Issue by milankragujevic** [phhusson/treble_experimentations#778]
As phhusson has expressed desire to require bugs and questions to be submitted as Github issues, here I am. 

Can anyone confirm and also provide evidence whether it is possible to turn off the behavior of display off during call when the proximity sensor is covered.

Also, if it is possible, please provide instructions on how to do that.

The question is for both Pie and Quack GSIs.

The device is Samsung Galaxy A50 (SM-A505FN).

**Comment by milankragujevic** [comment]
I have not found any replies searching for "sensor", "proximity" [or "disable"] in the Telegram group, therefor require assistance in finding it, or prefferably someone to copy-paste the response here.

**Comment by milankragujevic** [comment]
Current state of the GSI is that this is **not possible**. See phhusson response here: https://t.me/phhtreble/270581

The issue is left open for a possible future solution or discussion.

**Comment by RandomAJL** [comment]
Wait, so your proximity sensor is working on the A50?

**Comment by milankragujevic** [comment]
@RandomAJL It depends, on GSI? I don't know, I haven't tested it.On OneUI it does work, and it is incredibly annoying.

**Comment by RandomAJL** [comment]
So why are you posting in treble_experimentations then?

**Comment by milankragujevic** [comment]
Because I was asking about GSI before I was going to install it. Stop being so pedantic when you haven't even understood the context of the issue. In any case I sold the phone, the issue is obsolete.

**Comment by phhusson** [comment]
@milankragujevic stop insulting people. If there is someone who doesn't understand something, it's you.

**Comment by milankragujevic** [comment]
Pedantic is not an insult, but "untitled asshole" is.
