### ISSUE TITLE
[Huawei P20 PRO] No dual SIM managemt (Phhusson 200d AB ARM64)

### ISSUE THREAD

**Issue by ganjaman666** [phhusson/treble_experimentations#786]
There's is no possibility to turn on the second SIM card, there's no option to manage dual SIM in the settings menu.

**Comment by phhusson** [comment]
try `setprop persist.radio​.multisim.config dsds` and reboot

Le dim. 20 oct. 2019 à 16:20, ganjaman666 <notifications@github.com> a
écrit :

**Comment by AjayL13601** [comment]
On the A50 we just add our own build.prop with : ro.multisim.simslotcount=2 and
ro.vendor.multisim.simslotcount=2 added to the end.

**Comment by RandomAJL** [comment]
setprop ro.multisim.simslotcount 2
setprop ro.vendor.multisim.simslotcount 2
