### ISSUE TITLE
[Huawei P20 PRO] Mobile signal strength show no range (Phhusson 200d AB ARM64)

### ISSUE THREAD

**Issue by ganjaman666** [phhusson/treble_experimentations#787]
Even if I'm connected to a mobile network with good range, indicator shows no range.

**Comment by 0x15f2d** [comment]
mine is 2 sim so it shows correctly on the 1st sim and the 2nd one is like the dBm maxed out to 32 bit number

MTK btw

**Comment by ganjaman666** [comment]
Mine is two SIM too. Only one SIM is active and it shows empty indicator on this active card.
