### ISSUE TITLE
Moto G6 no boot in AOSP 10.0 v201

### ISSUE THREAD

**Issue by luisdambrowski** [phhusson/treble_experimentations#792]
Always restarting; in unlock bootloader message;

*system-quack-arm-aonly-gapps.img.xz
**my pstore
[update_pstore.zip](https://github.com/phhusson/treble_experimentations/files/3759321/update_pstore.zip)

***pstore Dadud
[pstore.zip](https://github.com/phhusson/treble_experimentations/files/3759761/pstore.zip)

**Comment by phhusson** [comment]
That's recovery's pstore, not system's pstore.

You need to boot the GSI once, then reboot into recovery, and retrieve the logs from there. Don't reboot twice into recovery.

**Comment by luisdambrowski** [comment]
OK; but is the path the same?
At night I will try here and update the link;
And about kmsg I could not save to send to you;

**Comment by Wizzard174** [comment]
> Always restarting; in unlock bootloader message;
> 
> *system-quack-arm-aonly-gapps.img.xz
> **my pstore
> [update_pstore.zip](https://github.com/phhusson/treble_experimentations/files/3759321/update_pstore.zip)
> 
> ***pstore Dadud
> [pstore.zip](https://github.com/phhusson/treble_experimentations/files/3759761/pstore.zip)

Hi, First of all after booting into recovery wipe everything except internal storage.
Than flash unofficial Lineage os 16.0 (https://forum.xda-developers.com/moto-g6/development/rom-lineageos-16-0-t3941809)

than again wipe everything and flash this AOSP 10.0 v201 GSI.

It should boot.

**Comment by phhusson** [comment]
No, don't flash lineage vendor. Only use OEM vendor.

**Comment by luisdambrowski** [comment]
Exactly; I will not use LineageOS! @phhusson Any file or request about moto g6 will help; to have a stable gsi;

**Comment by Dadud** [comment]
Yeah I sent him an extra log to post here, his seemed incomplete

**Comment by phhusson** [comment]
Here is a test image:

https://treble.phh.me/system-test-arm64-ab.img

this is an arm64 a/b, if i'm not mistaken that's what your device uses?

**Comment by phhusson** [comment]
I also need to test this test image:

https://treble.phh.me/system-test-arm64-ab-keymaster2.img

(the second has a fix I prefer, but i'm not too sure the two ways work)

**Comment by Uclydde** [comment]
> Here is a test image:
> 
> https://treble.phh.me/system-test-arm64-ab.img
> 
> this is an arm64 a/b, if i'm not mistaken that's what your device uses?

Moto G6 is arm (32-bit),  a-only

**Comment by phhusson** [comment]
Here's current patch to try to fix this issue:
https://gist.github.com/phhusson/0eb1012036b5bf413be60e8851798e28

and current test image (arm/a-only)
https://treble.phh.me/system-keymaster-moto-arm-aonly.img

**Comment by Dadud** [comment]
test image boots fine. sound is not working however. ill post some logs in the other issue regarding the G6.

**Comment by ry755** [comment]
Can confirm that the test image boots fine on the G6 Play (jeter) with Pie vendor too. Sound seems to be the only thing broken.
