### ISSUE TITLE
[MOTO E5] AOSP 10.0 v200.e does not initialize.

### ISSUE THREAD

**Issue by amaterasushen** [phhusson/treble_experimentations#795]
I was testing the AOSP 10.0 v200.e version, but it does not boot into Moto E5. However, I can boot AOSP 10.0 v200.d, but it has many problems like glitchs and codecs.

In this latest version the Android logo doesn't look so I can't start logcat.

[pstore.zip](https://github.com/phhusson/treble_experimentations/files/3757818/pstore.zip)

OBS: when I used the older version, I was able to fix the serrated bug by adding the following lines to build.prop

`debug.hwui.profile = true`
`debug.egl.hw=1`
`debug.sf.hw=1`
`debug.sf.latch_unsignaled=1`

obs2 : The audio does not work. :)

**Comment by phhusson** [comment]
Right, thanks for the report.
Fixed with https://github.com/phhusson/device_phh_treble/commit/cf6e53c1fee0b95a14317a3626d89e24fc792aa7

**Comment by amaterasushen** [comment]
Sobre o glitch e o problema de aúdio? alguma solução possivel?
