### ISSUE TITLE
[Improvements] build-dakkar script

### ISSUE THREAD

**Issue by Dil3mm4** [phhusson/treble_experimentations#80]

**Comment by dakkar** [comment]
copying the relevant bits from the discussion in the PR:

* we should separate the syncing routines and the actual build routines
* or just ask for user input to know if they want to sync up sources again
* the stuff about resyncing/cleaning on the device tree deletes any modifications done by the user (e.g. new .mk that are not already in the upstream or any other mods done over other files), that should be avoided as well and could be "delegate" on the syncying stuff side

**Comment by Dil3mm4** [comment]
Sent a PR over your tweaks branch that should solve all the stuff in one shot.

**Comment by dakkar** [comment]
yep, I've seen it. I'm rewriting the whole thing, though, to make it more flexible and nicer to work with, see [my branch](https://github.com/dakkar/treble_experimentations/tree/dakkar-better-build-script)

**Comment by Dil3mm4** [comment]
Oh, perl stuff, not my business :joy:
