### ISSUE TITLE
[AOSP 10.0 v201][MTK6763] Stucks on bootlogo Doogee BL9000

### ISSUE THREAD

**Issue by HedigehoG** [phhusson/treble_experimentations#808]
[logcat.zip](https://github.com/phhusson/treble_experimentations/files/3775456/logcat.zip)
Device Doogee BL9000 (Last update from the manufacturer: sept 2018, android 8.1)
AOSP 10.0 v201 stucks on bootlogo, logcat print:
01-01 01:58:33.840  3806  3814 W libprocessgroup: Controller cpuset is not found
01-01 01:58:33.840  3806  3814 E libprocessgroup: CgroupMap::FindController called for [3806] failed, RC file was not initialized properly
01-01 01:58:33.932  3804  3804 E APM::Serializer: No BT SCO Headset device found, don't patch policy
01-01 01:58:33.934  3804  3804 E APM::AudioPolicyEngine/Config: parse: Could not parse document /vendor/etc/audio_policy_engine_configuration.xml
01-01 01:58:33.934  3804  3804 E APM::AudioPolicyEngine/Config: parseLegacyVolumeFile: Could not parse document /odm/etc/audio_policy_configuration.xml

With this, can you do something or stay on 8.1?

**Comment by MCArTyR** [comment]
don't know what the problem is, but have you cleaned data/cache/dalivk? Personally, I helped

**Comment by HedigehoG** [comment]
I think this clearly does not help me. Without analyzing the problem from the log file, you can’t solve it by ordinary cleaning of the old tails.

**Comment by DoYouSpeakOreo** [comment]
For now, you can stay on Android 9 phhusson

**Comment by HedigehoG** [comment]
With android 9, I have problems, Magisk does not issue a request for permissions to applications, the Wi-Fi hotspot does not work, and there is a problem with the NFC

**Comment by DoYouSpeakOreo** [comment]
If you have a lot of problems, stay on the official rom of your phone to avoid problems

**Comment by HedigehoG** [comment]
official rom has a lot of problems and the developer will never fix them. even the clock in the blind freezes

**Comment by DoYouSpeakTrump** [comment]
If you have problems with Magisk, do not install it.

**Comment by HedigehoG** [comment]
I have no problems with the magisk on 8.1, but there is on android 9. but without it it is impossible to launch NFC payments, and this is important

**Comment by phhusson** [comment]
Well if you've got NFC issue on my Pie GSI perhaps I can fix it. What's the issue?

**Comment by HedigehoG** [comment]
My main problem is the impossibility of getting root rights, I launched the NFC myself, and there was not enough desire to distribute the wifi to solve the problem

**Comment by HedigehoG** [comment]
@phhusson  спасибо за отличную прошивку!!!
Проверил Android 10 v204, работает нормально, почти всё ок! Но не проходит проверку SafetyNet и нужен особый "magisk-phh" для загрузки.

**Comment by phhusson** [comment]
English please.

**Comment by HedigehoG** [comment]
Oh. I didn’t think that answer so quickly! Thanks for AOSP!
And the question is: how can I fix the boot situation (bootloop) without a special magisk-phh and what can be done with the verification SafetyNet , the previous ones (8.1, 9) went fine

**Comment by waryag123** [comment]
Подскажите как вы победили NFC на android 9?тоже doogee bl9000

**Comment by HedigehoG** [comment]
я уже писал об этом на 4pda, сравните 2 файла hce-nci.conf (скорей всего неправильно написал) из раздела /system/etc и исправьте значения из оригинального образа в девятке. напишу вечером в личку

**Comment by waryag123** [comment]
Поможете?, Я нашёл похожий nfcst2.conf только в вендор в оригинальном system нет файла похожего на nfc.conf и что именно там менять?
