### ISSUE TITLE
[Moto G6/G6 Play] [AOSP 10] - Camera error while attempting to record video

### ISSUE THREAD

**Issue by ry755** [phhusson/treble_experimentations#809]
When I try to record a video, it shows an error saying "Can't connect to camera." The camera preview works, the error only shows after tapping the record button.
Taking photos works fine.

Tested using [system-keymaster-moto-arm-aonly.img](https://treble.phh.me/system-keymaster-moto-arm-aonly.img) from this issue: [https://github.com/phhusson/treble_experimentations/issues/792#issuecomment-546130091](https://github.com/phhusson/treble_experimentations/issues/792#issuecomment-546130091)

logcat attached: [log.txt](https://github.com/phhusson/treble_experimentations/files/3776345/log.txt)

**Comment by Wizzard174** [comment]
Hi,does sound works for you? If yes, which vendor did you used?

**Comment by ry755** [comment]
No, sound is broken for me. I'm using the latest stock Pie vendor on a G6 Play.

**Comment by MarcosPearce** [comment]
Can you tell me where you downloaded it?

**Comment by ry755** [comment]
The test build is available at [https://treble.phh.me/system-keymaster-moto-arm-aonly.img](https://treble.phh.me/system-keymaster-moto-arm-aonly.img), and the vendor files are [here for Jeter](https://mirrors.lolinet.com/firmware/moto/jeter/official/) or [here for Aljeter](https://mirrors.lolinet.com/firmware/moto/aljeter/official/)

**Comment by MarcosPearce** [comment]
thanks :)

**Comment by MarcosPearce** [comment]
thanks :)

**Comment by ry755** [comment]
Fixed in v204.
