### ISSUE TITLE
Ulefone Power 5 v201 (MT6763)

### ISSUE THREAD

**Issue by DoYouSpeakOreo** [phhusson/treble_experimentations#810]
I do not understand this command line and how can I run it and where?
setprop ro.skia.ignore_swizzle true ?
![Capture](https://user-images.githubusercontent.com/55408700/67699744-e862f000-f9ac-11e9-8269-20f899e71fdd.PNG)

**Comment by MarivanUG** [comment]
Just make sure you have super user privileges. Download termux ; Grant su access then type "su" on the terminal. After that just paste that.

**Comment by MCArTyR** [comment]
MarivanUG - In case you haven't noticed, it says " for bootloop fix".
DoYouSpeakOreo - Just connect your device to pc, and use this command "adb shell setprop ro.skia.ignore_swizzle true"

**Comment by DoYouSpeakOreo** [comment]
Do you think there will be a version without doing this?

**Comment by phhusson** [comment]
yes, next version should do that automatically

Le ven. 1 nov. 2019 à 17:19, DoYouSpeakOreo <notifications@github.com> a
écrit :

**Comment by DoYouSpeakOreo** [comment]
Okay, thank you, do not answer me on Twitter then, I asked you the question in French because I am Belgian and I speak French too xD
