### ISSUE TITLE
[Moto g6] [ARM] [AOSP 10.0] Sound not working

### ISSUE THREAD

**Issue by Wizzard174** [phhusson/treble_experimentations#811]
Sound not working on test build of this GSI (system-keymaster-moto-arm-aonly).
Doesn`t  work on pie vendor,neither on oreo vendor.

Doesn`t work on any earlier build of AOSP 10.0.

**Comment by phhusson** [comment]
Duplicate of https://github.com/phhusson/treble_experimentations/issues/794
