### ISSUE TITLE
[Moto G5 Plus] Camera not working

### ISSUE THREAD

**Issue by shivvvvvv** [phhusson/treble_experimentations#812]
Device Codename : Potter 
Version : AOSP 10.0 v201 (Gapps Version)
Vendor: Pie (Same cam issue on oreo lineage vendor)
UnOfficial Treble - I know I may not receive any kind of support for having unofficial treble but I still want to open a bug report here so if anyone who is experienced. I tried earlier version of AOSP 10 GSIs and had cam issues but I did not report at that time bcz phh was still working on fixing more things, So I though maybe cam can be fixed too if any other device having same issues like me but I still it does not work.

Logs from boot - [phh2.txt](https://github.com/phhusson/treble_experimentations/files/3781937/phh2.txt)

` F linker  : CANNOT LINK EXECUTABLE "/vendor/bin/mm-qcamera-daemon": library "libandroid.so" not found`

Don't know whats wrong, this file is there in system, I am sure its vendor issue but have no idea why its happening. Flashlight toggle is also grayed out. Gcam and other third party cams also not working.

Camera works well in all android 10 GSIs by erfan :-!

**Comment by phhusson** [comment]
That's not an OEM Treble
