### ISSUE TITLE
[AOSP 10.0 v201][Redmi 6A] Choppy(horrific) sound and broken camera.

### ISSUE THREAD

**Issue by myst33d** [phhusson/treble_experimentations#814]
AOSP 10.0 v201 has sound issues and broken camera.
Plus when i plug-in USB cable(and it plays horrifying sound), it makes weird graphical glitch on launcher menu, which changes with the sound, really weird.

[dumpsys.txt](https://github.com/phhusson/treble_experimentations/files/3788686/dumpsys.txt)
[bootlogs.txt](https://github.com/phhusson/treble_experimentations/files/3788687/bootlogs.txt)

![Screenshot_20191030-160323](https://user-images.githubusercontent.com/45560476/67856704-563f2100-fb3f-11e9-9a31-4b71066f5b48.png)

**Comment by myst33d** [comment]
Is this issue is still present? Can i close the issue now?

**Comment by myst33d** [comment]
Really? -_-

**Comment by phhusson** [comment]
I don't get it. Why are you asking?You're the one that opened the bug
