### ISSUE TITLE
Bootloop | Samsung S8 - SM-G950F

### ISSUE THREAD

**Issue by HarnickA** [phhusson/treble_experimentations#818]
Version - 201

Flavour - system-quack-arm64-aonly-vanilla

Description - Boots to the second android boot animation, then sits there indefinitely.

Please let me know if there's anything I can do to help. Bugtesting, more logs, etc.

Logcat

(Please be warned that this is very long. The log kept repeating, and I don't know how to find where a log ends and starts repeating.)

[log.txt](https://github.com/phhusson/treble_experimentations/files/3791712/log.txt)

**Comment by HarnickA** [comment]
Fixed. Was under the impression patched Magisk was unneeded with v201.

**Comment by gkeegan** [comment]
@phhusson if it is necessary to have patched magisk, I think v201 could have its release notes reflect that.
