### ISSUE TITLE
Galaxy A50 Rounded Corners Not Working

### ISSUE THREAD

**Issue by antonometrics** [phhusson/treble_experimentations#822]
I am using **AOSP 10.0 v201 system-quack-arm64-ab-vanilla** and it seems that changing the corner radius in phh menu doesn't work. Corners are too round.

What can I do to fix this?

**Comment by phhusson** [comment]
adb shell settings put secure sysui_rounded_size 0.0


Le ven. 1 nov. 2019 à 07:22, antonometrics <notifications@github.com> a
écrit :
