### ISSUE TITLE
AOSP 10.0 v201 Tecno Camon X stuck on boot animation

### ISSUE THREAD

**Issue by ItsTashi** [phhusson/treble_experimentations#825]
After flashing the rom the device booted into android 10 and everything was working well but when i rebooted the device I got stuck on the boot animation
If i reset it to default in recovery it boots, i grabbed some logs of when it was booted and when it was stuck

**Comment by phhusson** [comment]
Should be fixed with https://github.com/phhusson/platform_frameworks_base/commit/77737540ba9d3d7d8394cc4ef408db06e726b39e

**Comment by ItsTashi** [comment]
thanks, I'll wait for the next release
