### ISSUE TITLE
[v202][Redmi Go] No call sound (telephony)

### ISSUE THREAD

**Issue by creativchic** [phhusson/treble_experimentations#834]
[2019-11-03-01-57-32.txt](https://github.com/phhusson/treble_experimentations/files/3801044/2019-11-03-01-57-32.txt)

**Comment by phhusson** [comment]
Works in v119?
Does multimedia works fine other wise? (at least speaker & 3.5mm or bluetooth)
Please dump the result of `adb shell dumpsys media.audio_policy`

**Comment by creativchic** [comment]
> Works in v119?
> Does multimedia works fine other wise? (at least speaker & 3.5mm or bluetooth)
> Please dump the result of `adb shell dumpsys media.audio_policy`

**Comment by creativchic** [comment]
It's a kernel feature and old ACDB. Sory.
