### ISSUE TITLE
Meizu X8 v119 brightness change don't work

### ISSUE THREAD

**Issue by EnderFight** [phhusson/treble_experimentations#836]
Brightness change don't work and the screen does not go off when I turn off the screen

**Comment by phhusson** [comment]
Screen not going off is quite unusual.

I guess you mean only backlight doesn't go off, but the screen is actually off?

Please give me the result of `lshal`. Do you have some place I can download stock rom easily?

**Comment by EnderFight** [comment]
Yes, only backlight doesn't go off. You can download stock rom from this link http://www.flymeos.com/firmwarelist?modelId=125&type=1.

**Comment by velv** [comment]
It can be fixed with `setprop persist.sys.qcom-brightness 4095` + overlay...
