### ISSUE TITLE
Webview not implemented in v20 Go Gapps

### ISSUE THREAD

**Issue by max-wiko** [phhusson/treble_experimentations#84]
Looks like the Webview package has not been properly implemented in the V20 Go with Gapps (armv7).
It crashes the gms package making any Google account registration impossible.

`06-15 12:22:27.833   669  1610 W WebViewUpdater: creating relro file timed out
06-15 12:22:27.836  6636  6636 E WebViewFactory: Chromium WebView package does not exist
06-15 12:22:27.836  6636  6636 E WebViewFactory: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:319)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:383)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at android.webkit.CookieManager.getInstance(CookieManager.java:39)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at hhd.a(:com.google.android.gms@11966436:1)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at com.google.android.gms.auth.uiflows.addaccount.AbstractBrowserSignInFragment.onCreateView(:com.google.android.gms@11966436:1)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at hho.onCreateView(:com.google.android.gms@11966436:1)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at com.google.android.chimera.FragmentProxy.onCreateView(:com.google.android.gms@11966436:1)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at km.a(:com.google.android.gms@11966436:6)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at ld.a(:com.google.android.gms@11966436:364)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at ld.c(:com.google.android.gms@11966436:32)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at ld.a(:com.google.android.gms@11966436:231)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at kf.m(:com.google.android.gms@11966436:15)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at ld.b(:com.google.android.gms@11966436:12)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at ld.a(:com.google.android.gms@11966436:132)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at ld.b(:com.google.android.gms@11966436:7)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at ld.j(:com.google.android.gms@11966436:5)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at ld.c(:com.google.android.gms@11966436:28)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at ld.m(:com.google.android.gms@11966436:10)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at kt.onStart(:com.google.android.gms@11966436:4)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at cpx.superOnStart(Unknown Source:0)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at com.google.android.chimera.Activity.onStart(Unknown Source:2)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at com.google.android.chimera.Activity.publicOnStart(Unknown Source:0)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at cpx.onStart(:com.google.android.gms@11966436:3)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at android.app.Activity.performStart(Activity.java:7029)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at android.os.Looper.loop(Looper.java:164)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at java.lang.reflect.Method.invoke(Native Method)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
06-15 12:22:27.836  6636  6636 E WebViewFactory: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
06-15 12:22:27.837  6636  6636 D AndroidRuntime: Shutting down VM
06-15 12:22:27.838  6636  6636 E AndroidRuntime: FATAL EXCEPTION: main
06-15 12:22:27.838  6636  6636 E AndroidRuntime: Process: com.google.android.gms.ui, PID: 6636
06-15 12:22:27.838  6636  6636 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/com.google.android.gms.auth.uiflows.minutemaid.MinuteMaidActivity}: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:423)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at android.webkit.CookieManager.getInstance(CookieManager.java:39)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at hhd.a(:com.google.android.gms@11966436:1)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at com.google.android.gms.auth.uiflows.addaccount.AbstractBrowserSignInFragment.onCreateView(:com.google.android.gms@11966436:1)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at hho.onCreateView(:com.google.android.gms@11966436:1)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at com.google.android.chimera.FragmentProxy.onCreateView(:com.google.android.gms@11966436:1)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at km.a(:com.google.android.gms@11966436:6)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at ld.a(:com.google.android.gms@11966436:364)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at ld.c(:com.google.android.gms@11966436:32)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at ld.a(:com.google.android.gms@11966436:231)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at kf.m(:com.google.android.gms@11966436:15)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at ld.b(:com.google.android.gms@11966436:12)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at ld.a(:com.google.android.gms@11966436:132)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at ld.b(:com.google.android.gms@11966436:7)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at ld.j(:com.google.android.gms@11966436:5)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at ld.c(:com.google.android.gms@11966436:28)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at ld.m(:com.google.android.gms@11966436:10)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at kt.onStart(:com.google.android.gms@11966436:4)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at cpx.superOnStart(Unknown Source:0)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at com.google.android.chimera.Activity.onStart(Unknown Source:2)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at com.google.android.chimera.Activity.publicOnStart(Unknown Source:0)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at cpx.onStart(:com.google.android.gms@11966436:3)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:7029)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	... 9 more
06-15 12:22:27.838  6636  6636 E AndroidRuntime: Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:319)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:383)
06-15 12:22:27.838  6636  6636 E AndroidRuntime: 	... 34 more
06-15 12:22:27.854  6636  6636 I GCore-Chimera-Crash: Cg8KCWNvbnRhaW5lchC8hEkgAQ==
06-15 12:22:27.854  6636  6636 I GCore-Chimera-Crash: GCore-Chimera-Crash
06-15 12:22:27.865  6636  6636 I DeviceDrDatabaseHelper: Cleaning stale data from database!
06-15 12:22:27.893  6636  6636 W DeviceDoctorHandler: Crash Hash: 8b1619e6ae06fcc50f16ca9562168caa0901a2e9
06-15 12:22:27.912  6636  6636 W DeviceDoctorHandler: Not shushing due to process not found in the whitelist.
06-15 12:22:27.923   669  5499 W ActivityManager:   Force finishing activity com.google.android.gms/.auth.uiflows.minutemaid.MinuteMaidActivity
06-15 12:22:27.937  6636  6636 I Process : Sending signal. PID: 6636 SIG: 9
06-15 12:22:27.951   669  5499 I BroadcastQueue: Delay finish: com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
06-15 12:22:27.973   669  5499 I BroadcastQueue: Resuming delayed broadcast
06-15 12:22:27.998   669  3250 I ActivityManager: Process com.google.android.gms.ui (pid 6636) has died: fore TOP 
06-15 12:22:28.000   669  5687 I WindowManager: WIN DEATH: Window{fa37918 u0 com.google.android.gms/com.google.android.gms.auth.uiflows.addaccount.PreAddAccountActivity}
06-15 12:22:28.000   669   718 W zygote  : kill(-6636, 9) failed: No such process
06-15 12:22:28.025   336   491 I [Gralloc]: usage1: 0x900, format: 1 stride: 480 vertical_stride: 960 size: 1843200
06-15 12:22:28.030   336   491 I chatty  : uid=1000(system) HwBinder:336_1 identical 2 lines
06-15 12:22:28.032   336   491 I [Gralloc]: usage1: 0x900, format: 1 stride: 480 vertical_stride: 960 size: 1843200
06-15 12:22:28.036  6248  6248 I Finsky  : [2] com.google.android.finsky.q.a.onActivityResult(165): No new account added: Assume the user canceled and finish.
06-15 12:22:28.041   669   729 W ActivityManager: setHasOverlayUi called on unknown pid: 6636
06-15 12:22:28.048   669   718 W zygote  : kill(-6636, 9) failed: No such process
06-15 12:22:28.048   669   718 I zygote  : Successfully killed process cgroup uid 10035 pid 6636 in 48ms`

**Comment by max-wiko** [comment]
![screenshot_20180615-124203](https://user-images.githubusercontent.com/37664221/41464171-a381fff0-7099-11e8-817b-44ef7dd4b3c4.png)
![screenshot_20180615-124208](https://user-images.githubusercontent.com/37664221/41464172-a3a59ce4-7099-11e8-8414-c3c04890c9fc.png)

**Comment by phhusson** [comment]
Oh, oops, it got lost in a rebase.
Should be fixed by https://github.com/phhusson/device_phh_treble/commit/f09963530417f6cc358a65d4d3b0b320f1c6d07e

Thanks

**Comment by phhusson** [comment]
FWIW, it looks like your device doesn't have a vendor/overlay/framework-res.apk
Since you're the OEM, you should probably consider enabling it.
This would at least fix auto-backlight and lower power consumption

**Comment by max-wiko** [comment]
Thanks for the quick fix!
It seems the vendor/overlay/framework-res.apk was not properly named in our development build, nice find!
BTW, awesome job, we'll try to validate all our 2018 lineup to be compatible with your treble roms ;)

**Comment by phhusson** [comment]
> It seems the vendor/overlay/framework-res.apk was not properly named in our development build, nice find!
Hum, the name is irrelevant
If you have a framework-res rro file in vendor/overlay, it's suprising that you don't get the webviews, because webviews are supposed to be declared in the framework-res rro as well

> BTW, awesome job, we'll try to validate all our 2018 lineup to be compatible with your treble roms ;)
Nice, thanks :-)
FWIW, there is #57 that needs to be looked at for real compatibility

**Comment by max-wiko** [comment]
I'm forwarding to the system dev team so they can have a look at the system webview issue in /vendor.
We also have the RIL issue on our MTK products. I'm checking internally if we can do anything, but we may have our hands tied with NDAs.

**Comment by phhusson** [comment]
Just to be clear, the webview issue is definitely an issue of mine.

It's just that due to the way /vendor/overlay/ is done, you wouldn't hit this bug.
I've got two Android Go devices on which I've tested my gapps go integration, which have the /vendor/overlay framework-res overlay, and so they don't hit this issue.

And sure I understand you might hit NDA problems, just keep me updated
