### ISSUE TITLE
[AOSP 10.0 V202] Bootloop on BV9500

### ISSUE THREAD

**Issue by cernodile** [phhusson/treble_experimentations#844]
Installed on-top of 9.0 v119 and wiped data, cache and dalvik. Used TWRP to flash (although I don't think it matters here).

[logcat.txt](https://github.com/phhusson/treble_experimentations/files/3804992/logcat.txt)
[dmesg.txt](https://github.com/phhusson/treble_experimentations/files/3804994/dmesg.txt)

**Comment by phhusson** [comment]
Edit /system/build.prop and add

ro.audio.ignore_effects=true

Le lun. 4 nov. 2019 à 17:33, Joann Mõndresku <notifications@github.com> a
écrit :

**Comment by cernodile** [comment]
Thank you for your patience.
I added the line to build.prop, bootloops persist.

Here are the new logcat and dmsg logs.
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/3805144/logcat.txt)
[dmesg.txt](https://github.com/phhusson/treble_experimentations/files/3805145/dmesg.txt)

**Comment by kjp4756** [comment]
I'm no expert or anything but according to your original logcat there is reference to magisk.  I get a bootloop with magisk v20.  Maybe that's your issue?  Try restoring your original boot image.

**Comment by cernodile** [comment]
Thank you to both of you. That was the cause of my issue (ro audio thing also applies to AOSP 9.0 builds), I had no idea my boot image was patched with magisk still. The device has now booted and issue is resolved.
