### ISSUE TITLE
[Moto E5 Play Go (The 1GB RAM one)] No fingerprint sensor in any version

### ISSUE THREAD

**Issue by cssobral2013** [phhusson/treble_experimentations#847]

**Comment by phhusson** [comment]
Device?Log on boot?

**Comment by cssobral2013** [comment]
The device is a Moto E5 Play Go (the one with 1gb ram). Title was re-changed to reflect this.

Em seg, 4 de nov de 2019 9:58 PM, Pierre-Hugues HUSSON <
notifications@github.com> escreveu:

**Comment by cssobral2013** [comment]
The log just after I hard reboot is attached below.
[1.txt](https://github.com/phhusson/treble_experimentations/files/3810129/1.txt)

**Comment by phhusson** [comment]
Ok. Only relevant thing I can see is:
`09-12 18:20:13.310  2396  2396 D SystemConfig: Removed unavailable feature android.hardware.fingerprint`

Please report the result of `adb shell lshal`

**Comment by cssobral2013** [comment]
I'll verify later 'cause my PC is currently occupied now.

Em seg, 11 de nov de 2019 8:03 PM, Pierre-Hugues HUSSON <
notifications@github.com> escreveu:

**Comment by cssobral2013** [comment]
The result is here in the attachment.

[2.txt](https://github.com/phhusson/treble_experimentations/files/3837610/2.txt)

**Comment by phhusson** [comment]
Please send those files if they exist:
- /vendor/etc/vintf/manifest.xml
- /odm/etc/vintf/manifest.xml
- /oem/etc/vintf/manifest.xml
- /product/etc/vintf/manifest.xml

**Comment by cssobral2013** [comment]
Sorry but cannot find any file you mentioned. Am I missing something?

Em ter, 12 de nov de 2019 5:32 PM, Pierre-Hugues HUSSON <
notifications@github.com> escreveu:

**Comment by cssobral2013** [comment]
However, when installing stock rom, the fingerprint hora back.

Em ter, 12 de nov de 2019 7:19 PM, Cristiano Sobral <cssobral2013@gmail.com>
escreveu:

**Comment by phhusson** [comment]
Ah sorry. Those files:
- /vendor/manifest.xml
- /odm/manifest.xml
- /oem/manifest.xml
- /product/manifest.xml

**Comment by phhusson** [comment]
> However, when installing stock rom, the fingerprint hora back.

You mean fingerprint works in stock ROM? Why do you mention that? That's expected?
Or you're speaking of stock rom's vendor with my GSI?

**Comment by cssobral2013** [comment]
The xml in vendor is attached. The other xml's weren't found.
Em terça-feira, 12 de novembro de 2019, Pierre-Hugues HUSSON <
notifications@github.com> escreveu:

**Comment by phhusson** [comment]
Attached where?

**Comment by cssobral2013** [comment]
Sorry, Github doesn't see attachments when sending replies from email...


Em qua, 13 de nov de 2019 3:13 PM, Pierre-Hugues HUSSON <
notifications@github.com> escreveu:

**Comment by cssobral2013** [comment]
@phhusson, is attached below. No joking.
[vendor.zip](https://github.com/phhusson/treble_experimentations/files/3843561/vendor.zip)

**Comment by phhusson** [comment]
No problem.

Ok, with the GSI running, can you dump the result of `adb shell cat /system/etc/permissions/android.hardware.fingerprint.xml` ; and of `adb shell pm list features` ?

**Comment by cssobral2013** [comment]
The results of both are attached below.
android.hardware.fingerprint.xml: 
[3.txt](https://github.com/phhusson/treble_experimentations/files/3844031/3.txt)
adb shell pm list features:
[4.txt](https://github.com/phhusson/treble_experimentations/files/3844033/4.txt)

**Comment by cssobral2013** [comment]
> > However, when installing stock rom, the fingerprint hora back.
> 
> You mean fingerprint works in stock ROM? Why do you mention that? That's expected?
> Or you're speaking of stock rom's vendor with my GSI?

Just for information, if it's needed.

**Comment by phhusson** [comment]
`adb shell 'getprop |grep -e fingerprint -e fp'` ?

**Comment by cssobral2013** [comment]
The result is below.
[11.txt](https://github.com/phhusson/treble_experimentations/files/3854277/11.txt)
