### ISSUE TITLE
Resize /data

### ISSUE THREAD

**Issue by phhusson** [phhusson/treble_experimentations#85]
Some recovery-s (OP6) or fastboot (MTK devices) doesn't format /data with proper partition
The fix would be to detect if there is a huge discrepancy between partition size and FS size (we need a margin for FDE footer), and resize in that case

**Comment by phhusson** [comment]
OP6-specific fix in https://github.com/phhusson/device_phh_treble/commit/c9b139187f67383b98f979f21334e5a3c5029f16

**Comment by cawilliamson** [comment]
@phhusson Just wanted to confirm - this fix worked perfectly for me on a 128GB OP6.
