### ISSUE TITLE
the patches are from August not from October .AOSP 9.0 v120.

### ISSUE THREAD

**Issue by cigny61** [phhusson/treble_experimentations#850]

**Comment by phhusson** [comment]
it is October, only the string in the settings is wrong.

**Comment by cigny61** [comment]
thanks.

Il giorno mar 5 nov 2019 alle ore 09:09 Pierre-Hugues HUSSON <
notifications@github.com> ha scritto:

> it is October, only the string in the settings is wrong.
>
