### ISSUE TITLE
bootloop on Ulefone Power 5! (MTK6763)

### ISSUE THREAD

**Issue by DoYouSpeakTrump** [phhusson/treble_experimentations#858]
Still impossible to install this version on this phone, I do not understand.
Please phhusson, can you fix this problem, thanks.

**Comment by DoYouSpeakTrump** [comment]
I speak well of Android 10, Android 9 works very well.

**Comment by phhusson** [comment]
Logs?

**Comment by DoYouSpeakTrump** [comment]
Je parle français et je peux mieux me faire comprendre comme ça, je vous donnerai les journaux demain car je ne les ai pas sauvergardé sur une carte SD. Cela ne vous dérange pas que je parle français car tout le monde aujourd'hui utilise Google Traduction ? Merci

**Comment by phhusson** [comment]
Why did you close it?

**Comment by DoYouSpeakTrump** [comment]
I made a new one for others and you answer me too :)
