### ISSUE TITLE
Huawei  y6 2018 AOSP9.0 V 120

### ISSUE THREAD

**Issue by psihodelik2304** [phhusson/treble_experimentations#860]
i installed on huawei y6 2018 AOSP 9.0 v120 writes me android security patch level 1 August 2019 
is it a mistake

**Comment by proganime1200** [comment]
> i installed on huawei y6 2018 AOSP 9.0 v120 writes me android security patch level 1 August 2019
> is it a mistake

is camera working???

**Comment by phhusson** [comment]
Even though it says August, it is October

**Comment by psihodelik2304** [comment]
camera not working ok thanks phhusson
