### ISSUE TITLE
AOSP 9 v120

### ISSUE THREAD

**Issue by DoYouSpeakTrump** [phhusson/treble_experimentations#863]
There is a small display problem in version v120 because you say that you put the security version of October and there is August, in my opinion, you forgot to change the name phhusson xD

**Comment by phhusson** [comment]
it's not me it's Google. But yeah I'll do that for next

Le jeu. 7 nov. 2019 à 21:41, DoYouSpeakTrump <notifications@github.com> a
écrit :

**Comment by DoYouSpeakTrump** [comment]
Okay.

**Comment by DoYouSpeakTrump** [comment]
Thank You !
