### ISSUE TITLE
[AOSP 10] [v202] Incompatibility with Google Phone

### ISSUE THREAD

**Issue by lucasdeeiroz** [phhusson/treble_experimentations#866]
Until v202, Phh's Quack GSI (Gapps variation) has some files related to Google Phone missing. There are three of them:
- /system/etc/permissions/com.google.android.dialer.support.xml
- /system/etc/sysconfig/dialer_experience.xml
- /system/framework/com.google.android.dialer.support.jar

That causes the inability to update the app and a message warning about the device not being compatible with it every time you open it.

**Comment by kjp4756** [comment]
So that's why that message pops up every time you open phone!  Flashing opengapps v10 nano beta fixes it for me for now.

**Comment by lucasdeeiroz** [comment]
> So that's why that message pops up every time you open phone! Flashing opengapps v10 nano beta fixes it for me for now.

Yes, every OpenGApps package pushes those files into system. They call it "Dialer Framework".

**Comment by phhusson** [comment]
Should be fixed with https://github.com/phhusson/device_phh_treble/commit/562ee1f897efce7de86f34ed82a2df10a064999b

thanks
