### ISSUE TITLE
[Elephone Soldier] sound AOSP 8.1-9

### ISSUE THREAD

**Issue by yura73** [phhusson/treble_experimentations#874]
Hello. On all your releases AOSP 8.1-9, my smartphone ELEPHONE SOLIDER has no sound in the dynamics (there are headphones and spoken dynamics), I have made many unsuccessful attempts to fix this. Since your only ones that run on my smartphone I ask for your help and advice. I managed to find out that my smartphone has a separate audio chip for headphones. What logs and files from the firmware will be needed to solve this problem? I hope you'll give me a hand.

**Comment by phhusson** [comment]
let's start with `lshal`

**Comment by yura73** [comment]
[lshal.zip](https://github.com/phhusson/treble_experimentations/files/3827292/lshal.zip)

**Comment by yura73** [comment]
[audio.zip](https://github.com/phhusson/treble_experimentations/files/3836861/audio.zip)

**Comment by phhusson** [comment]
> [lshal.zip](https://github.com/phhusson/treble_experimentations/files/3827292/lshal.zip)
> stock firmware

Sorry, that's not what I meant.
I need you to run `lshal` command and paste its output..

Considering #877, could you re-explain the issue?

What do you mean you have no sound "in the dynamics"?

**Comment by yura73** [comment]
there is no sound in the main speaker (music, incoming call ringtone)

**Comment by yura73** [comment]
[lshal.txt](https://github.com/phhusson/treble_experimentations/files/3838199/lshal.txt)
stock firmware

**Comment by yura73** [comment]
[lshal.txt](https://github.com/phhusson/treble_experimentations/files/3838278/lshal.txt)
AOSP 9.0 v121

**Comment by yura73** [comment]
dear phhusson i did everything right?

**Comment by phhusson** [comment]
Does call-speaker work?
Does 3.5mm jack headsets work?

Please provide logcat on stock ROM, when doing this:
- boot
- start a music app, select a music, start playing it and click "pause"
- wait a minute
- press "play"

**Comment by yura73** [comment]
The call speaker is working.
The 3.5mm headset works well.
[logcatboot.txt](https://github.com/phhusson/treble_experimentations/files/3855927/logcatboot.txt)
[logcat music.txt](https://github.com/phhusson/treble_experimentations/files/3855928/logcat.music.txt)


I hope I did everything right.

**Comment by phhusson** [comment]
log looks good.
Please do the same logs on GSI so I can compare

**Comment by yura73** [comment]
[logcat boot.txt](https://github.com/phhusson/treble_experimentations/files/3858124/logcat.boot.txt)
[logcat music.txt](https://github.com/phhusson/treble_experimentations/files/3858125/logcat.music.txt)
AOSP 8.1 V32
Let me know if it is wrong.

**Comment by phhusson** [comment]
Ok, stock ROM has many logs about TFA98XX, which GSI logs doesn't have, so that's pretty good, that gives me something to work on.

Could you give me a downloadable link to your stock rom?

**Comment by yura73** [comment]
https://mega.nz/#F!xwBklAyS!EjTUSrGZi80daILLi_mHjg!Q5hizaLb
It inspires hope

**Comment by phhusson** [comment]
Ok, sounds like an easy bug ugly one after all.

Copy stock's /system/lib/libtfa98xx_v2.so to /vendor/lib/libtfa98xx_v2.so
and
/system/lib64/libtfa98xx_v2.so to /vendor/lib64/libtfa98xx_v2.so

I think this should fix your issue. If it doesn't, provide again logcat.boot and logcat.music.

I've attached the stock files for convenience.
[tfa.zip](https://github.com/phhusson/treble_experimentations/files/3866206/tfa.zip)

**Comment by yura73** [comment]
Yes, it really helped! A sound has appeared.
Thank you very much !
It remains to deal with bluetooth and the NSС which does not work on AOSP 9.

**Comment by phhusson** [comment]
NSC? You mean NFC?

Try the property mentioned at https://github.com/phhusson/treble_experimentations/issues/660

**Comment by yura73** [comment]
Sorry for the english. Yes NFC.

**Comment by yura73** [comment]
Thanks you ! You are great!
Everything works.

**Comment by philalat** [comment]
hy every body
i read this treath but i don't know how to copy the folders included in tfa.zip.
how copy them in the stock? which app can i use to do?
if i try to install via ADB, i get zip invalid.
best regards

**Comment by yura73** [comment]
to establish masgik
install total comanger
get root rights
unzip the archive and copy lib.

**Comment by philalat** [comment]
good morning
total comanger or total commander
how copy lib?
thanks

**Comment by yura73** [comment]
Total commander

**Comment by philalat** [comment]
Hy YURA
do you have update your elephone soldier?
i tried several versiosn as phhusson system android 9 or 10 but the phone start . however the phone stay on the android logo more than 6 hours and nothing else; so i installed the octopus OS and it's work except the sound .
best regards

**Comment by philalat** [comment]
ii find the folder lib, but elephone is arm64, i must use only lib64? and i must copy as phhusson said.
cpoy it in vendor;
that's right?
thanks for your help

**Comment by yura73** [comment]
![Screenshot_20200430-114328](https://user-images.githubusercontent.com/55551619/80690859-1817bf80-8ad8-11ea-9291-940229a93814.png)
Android 9-10 updates for a soldier does not exist in nature and will not.
all GSI have the same bugs (communication heap. access point. the flashlight buttons do not work.)

**Comment by yura73** [comment]
https://4pda.ru/forum/index.php?showtopic=916579&st=300

**Comment by philalat** [comment]
I was tooquick when i wrot, i tried android 9 v119 after android 10 v215 ; i have elephone logo then i egt the logo android but it stay and nore more; With octopus OS all works.
the link you join is in russian and googl cann't translate it, but i use this twrp 3.3.1 unofficial it's works.
for the picture i see  lib and lib 64, do you mean imust copy the two folder one in lib and the other in lib 64?

**Comment by philalat** [comment]
that's ok google translate the web page finally

**Comment by yura73** [comment]
where did you get the octopus os ?

**Comment by philalat** [comment]
https://github.com/phhusson/treble_experimentations/wiki/Generic-System-Image-%28GSI%29-list
and there you go in nadroid 9 official and you have OctopusOS (N°10 in the list)

**Comment by philalat** [comment]
official Android 9 Pie section

**Comment by yura73** [comment]
I tried it.  side flashlight and sos button do not work

**Comment by philalat** [comment]
i open total commander, i unzip tfa.zip on intrenal storage but i cann't copy the files ?

**Comment by yura73** [comment]
should succeed
Try it in twrp

**Comment by philalat** [comment]
how do you do with total commander?
i have the file on internal storage,  when i open total commander isee the both but when i want to copy in lib folder i cann't.
total commander is on your phone or your PC?

**Comment by yura73** [comment]
Total Commander on the phone

**Comment by philalat** [comment]
hy yura
ouf i found how to copy with total commander; now i can test this system.
thanks

**Comment by yura73** [comment]
unzip the archive copy to vendor

 overlay with replacement

**Comment by yura73** [comment]
[framework-res__auto_generated_rro.zip](https://github.com/phhusson/treble_experimentations/files/4558941/framework-res__auto_generated_rro.zip)

**Comment by yura73** [comment]
auto brightness correction and headphone connection

**Comment by philalat** [comment]
okay i'll try and you you look at the website that i sent?

**Comment by yura73** [comment]
i know this site

**Comment by philalat** [comment]
good morning yura
the folder framework when i extract it it's a .apk. when i want to install it the phone don't auhorize the complete installation.
you install   it with total commander?
have a nice day

**Comment by yura73** [comment]
using Total Commander
Delete the existing new copy folder.
no need to install!

**Comment by philalat** [comment]
i 'll try, the sound is ok now for the call, i don't try music player.

**Comment by philalat** [comment]
do you remember the folder for framework?

**Comment by yura73** [comment]
vendor/overlay

**Comment by philalat** [comment]
i deleted the one i found in system; it's not good bacause the phon when i start it stay on the logo octopus. i must do a restore and do the good action.

**Comment by yura73** [comment]
not from the system!!!!
from vendor overlay!!!!

**Comment by philalat** [comment]
too late!!!
but i do a restore and do the good action; that's strange to find twice the same .apk

**Comment by philalat** [comment]
hy yura 
did you install octopusOS? for me i noted several bug
1 - i lost the phone network
2- i cann't connect in share connection with my autoradio
3- idem with bluetooth for the autoradio
except that there is nice wallpaper.
best regards

**Comment by yura73** [comment]
I advise you to install Havoc-OS-v3.5-20200507-Official-arm64-aonly-vanilla-nosu.img.xz
https://sourceforge.net/projects/havoc-os/files/arm64-aonly/

**Comment by philalat** [comment]
i didn't try it so lets go. it's  9 or 10?

**Comment by philalat** [comment]
do you have try a android 10 system. i tried but the installation stay on logo android .Wether it bet with ADB or TWRP

**Comment by yura73** [comment]
copy these to the lib appropriate
[GSI.zip](https://github.com/phhusson/treble_experimentations/files/4630265/GSI.zip)
 folders vendor

**Comment by philalat** [comment]
what it do? i copy it before or after install the system.
i think it's after because i must use total commander and i can download it after installation and root.
that's okay?

**Comment by yura73** [comment]
Yes
this will help run 10 GSI

**Comment by philalat** [comment]
okay i do an unzip before or i copy GSI.zip as is?

**Comment by philalat** [comment]
no need to copy it in vendor /lib only in vendor folder

**Comment by yura73** [comment]
![Screenshot_20200514-215120 1](https://user-images.githubusercontent.com/55551619/81973836-63c87e00-962d-11ea-833a-95d97f5abff9.jpg)
![Screenshot_20200514-215137 1](https://user-images.githubusercontent.com/55551619/81973882-780c7b00-962d-11ea-935d-f99f3ec9d8ef.jpg)
vendor\lib
vendor\lib64

**Comment by philalat** [comment]
okay i followed, on my pc i extract on the same time you wrote me. I saw lib and lib 64 folders. 
but i can do the copy befor to flash or after?
because i installed TWRP on my soldier android 8 and i rooted it, so i have total commander in it.

**Comment by philalat** [comment]
under total commander it's write crush, ignore but not copy

**Comment by yura73** [comment]
before installing the system

**Comment by philalat** [comment]
okay i did it now i wait to download Havoc

**Comment by yura73** [comment]
Use Magisk-v20.3-phh.zip

**Comment by philalat** [comment]
i have on it, that with magisk i root elephone android 8

**Comment by yura73** [comment]
[Magisk-v20.3-phh.zip](https://github.com/phhusson/treble_experimentations/files/4630470/Magisk-v20.3-phh.zip)

**Comment by philalat** [comment]
thanks

**Comment by yura73** [comment]
otherwise the system does not start

**Comment by philalat** [comment]
yes i install the system and after i use magisk before to reboot with TWRP.

**Comment by yura73** [comment]
Yes

**Comment by philalat** [comment]
i say you good night and i'll told you if havoc works. 
thanks for al

**Comment by philalat** [comment]
all

**Comment by philalat** [comment]
good morning yura
it's seems to me that i need your help again
i try to install havok but it's stay on the logo havok ( a piece of circle which turn).
before install i do root of android 8, i downloaded total commander and i copied the folders inside lib and lib 64 in vendor lib and lib 64.

i try two method:
1 after factory reset in install the system.img and magisk but it's rebbot before the end of insrtallation
2 after factory reset, i install system.img and i reboot.

the results are the same like i say before, the phone start, logo elephone switch off, restart, logo havok, switch off, and logo havok again but it's stay on this moving logo.
do you have an idea
best regards

**Comment by yura73** [comment]
you need to copy not folders but from folders to folders

**Comment by yura73** [comment]
https://drive.google.com/file/d/19MCPekecqji-wimG6UceO9xz705ExDpo/view?usp=sharing
here backup vendor and buta
restore through tvrp and flash the system

**Comment by philalat** [comment]
hy yura
i need your help again with havok
before, i root android 8, install total commander and GSI LIB and LIB64 on VENDOR LIB and LIB64

After i try 2 methods:
1 factory eset, install system.img, install magisk. the installation don't go to the end , the phone reboot and satr and stop twice; after taht i got the logo havok (a piece of circle which turn)
2 factory reset, install system.img and reboot, the result is the same. The phone stay on moving logo havok, i let it about 1 hour ! After that i stopped and install new android 8.
do you have an idea?
best regards

**Comment by philalat** [comment]
i have the rom and system.img original (2018), i do the restore of it; actually i have original android 8 vendor and i have the root and TWRP on it.

**Comment by yura73** [comment]
https://drive.google.com/file/d/19MCPekecqji-wimG6UceO9xz705ExDpo/view?usp=sharing
here backup vendor and boot
unzip the zip restore through twrp and flash the system

**Comment by yura73** [comment]
system havoc 3.5

**Comment by philalat** [comment]
i'm going to download your backup,after  i try your solution ;
i'll give you feedback
see you later

**Comment by philalat** [comment]
my sytem is 2008 not 2018, i was wrong

**Comment by philalat** [comment]
do you wait a longtime before the installation after reboot? i don't need to copy GSI lib and lib64?

**Comment by yura73** [comment]
nothing to copy
need to wait some time

**Comment by philalat** [comment]
finally  havok start, YES!!!
now the little problme comes from recovery mode, when i want to reboot in recovery mode to fix the sound call problem. I cann't:
 in ADB command "adb devices" the phone is ok but unauthorized.  in fact when i use folder transfert it's works not.
in using up and power it don't reboot in recovery.
i keep on trying

**Comment by philalat** [comment]
do you have total commander on your PC, i download it but the text editor doesn't work with big folders. do you have one good with windows 10 64 bits?

**Comment by yura73** [comment]
this version has adb problems
How do you solve the sound call problem?

**Comment by yura73** [comment]
do you have one good with windows 10 64 bits?===yes

**Comment by yura73** [comment]
HOW IS IT GOING?
How do you solve the sound call problem?

**Comment by philalat** [comment]
Hy yura
Until this morning all was OK. But at about 10h00 i l'ost 4g network. I
must reboot ans there... Fastboot OK ans black screen. Si i started un
recovery mode, i do backup with jour folder vendor. I restart ans its
works. Now i dont know where is this problem of phone connection?

**Comment by philalat** [comment]
For the call problems, with havok i copy lid ans lib64 for the sound ans
it's works

**Comment by philalat** [comment]
good morning Yura
for the boot  which start in fastboot, it's seems to be fix.>On the other
hand, this morning no more 4G phone network i did restart the phone and the
4G is ok.
For the rest all seems to be good , i keep on trying on i do a feedback
thanks for your help because if you don't give me the backup i'll be always
on the same place.
best regards

**Comment by yura73** [comment]
Hi
use * # * # 4636 # * # * to select networks
of success

пн, 18 мая 2020 г. в 08:31, philalat <notifications@github.com>:

**Comment by philalat** [comment]
hy Yura
 *#*#4636#*#* doesn't works . before to do that i change the APN parameters with my network operator SFR;

**Comment by philalat** [comment]
*#*#4636#*#* doesn't work

**Comment by philalat** [comment]
i wrote * # * # 4636 # * # *

**Comment by philalat** [comment]
Good evening yura
I round two bugs
1 i cann't connect bluetooth earphones. I switch on bluetooth téléphone ans earphones but soldier dont fund thème.
2 share connections with autoradio, the code ils OK, wifi switch on on teh phone but the autoradio write no internet connection.
Best regards

**Comment by philalat** [comment]
Dont found them

**Comment by philalat** [comment]
Yura
I did a bluetooth reset but the soldier dont find the earphones, i noticed that bluetooth don't stay on

**Comment by yura73** [comment]
open settings
open Phh-Treble Settings
open Misc features
open Bluetooh workarounds
check the box Mediatek
reboot phone

**Comment by philalat** [comment]
I'll never found this action thanks!

**Comment by philalat** [comment]
Hy yura
It's works for earphone but not for the autoradio un share connection. The
code is good , the wifi OK but ni internet connections. Ils there another
setting to do?
Good evening

**Comment by yura73** [comment]
Hi
This is not yet available on MTK

**Comment by philalat** [comment]
With Android 8 i connected my soldier.

**Comment by philalat** [comment]
The autoradio is powered Android top.

**Comment by philalat** [comment]
Too

**Comment by yura73** [comment]
on GSI does not work

**Comment by philalat** [comment]
Hy Yura
i discovered another problem with earphone wireless. I can receive calls or heau sound of a movie, but i cann't hear the sound when i call?
Do you have an idea?
i checked smarlock is off
the earphones are able to connect share contacts, multimédia, calls and enter peripheric.
in anotehr hand, i lost always the 4g network so i restart.
best regards

**Comment by yura73** [comment]
Hi No, there is no solution for bluetooth headphones.  regarding the loss of communication 4g there is no decision.  unless Mr. Phhusson can solve it. let's hope.

**Comment by philalat** [comment]
thanks have a nice day

**Comment by yura73** [comment]
from this link you can download the overlay for our phone
https://drive.google.com/file/d/10rMbhYABthDk7THLUujSBFzckRKhOdV3/view?usp=drivesdk

**Comment by philalat** [comment]
HY Yura
i open .apk or i directly copy it in vendor/overlay?

**Comment by philalat** [comment]
when i want to copy it in vendor averlay via total commander, that write  "writing error in the target folder :vendor/overlay/treble-overlay-Elephone-Sloider.apk!

**Comment by philalat** [comment]
i have correct the name of the folder Soldier instead of Sloider.

**Comment by yura73** [comment]
try copying through TWRP
to the vendor overlay folder
I was mistaken in the name but it is not essential

**Comment by philalat** [comment]
hy yura
the copy is ok in vendor/overlay. I need to open the .apk or not? becuase when i want install it thats' run but befor the end it's write app not installed

**Comment by yura73** [comment]
Hey.  No, this application does not need to be installed, it integrates
when the phone starts

пт, 29 мая 2020 г., 20:47 philalat <notifications@github.com>:

**Comment by yura73** [comment]
copy to system / overlay

**Comment by philalat** [comment]
i restart the phone and i saw that .apk was installed . what's the use of this .apk?
because i cann't always use bluetooth earphone when i want to call. for reception calls or music that's OK
i try crdroid rom it's look more stable with phone network .

**Comment by yura73** [comment]
this overlay will make working auto brightness and much more. he is for the system
