### ISSUE TITLE
add libraries from native application Moto Camera 2

### ISSUE THREAD

**Issue by luisdambrowski** [phhusson/treble_experimentations#875]
@phhusson You said you can add the libraries you need to make Motorola's native camera application compatible;

I thought just adding the libraries; if the user decides to use the application, he can download it directly from the play store;

I use the moto g6 arm a only;
system-quack-arm-aonly-gapps.img.xz

**Comment by phhusson** [comment]
I won't include proprietary code. 
But which libs are you talking about?

**Comment by luisdambrowski** [comment]
Right; I mean being able to use Motorola's native app on your GSI; make it compatible with its use;

**Comment by luisdambrowski** [comment]
That's right; I thought about using Motorola's native camera app on your GSI; make it compatible; be able to install through the play store or upgrade;

**Comment by luisdambrowski** [comment]
Would this use be possible?

**Comment by phhusson** [comment]
You give me too little information. I can't answer with the little you've given me.

**Comment by phhusson** [comment]
Why close this issue?

Has this issue been fixed? It doesn't seem so.

**Comment by luisdambrowski** [comment]
When it is launched at v204; I will test this .zip below.
I believe this is what needs to make the "moto camera" app compatible with your GSI.
**Could look at the .zip and see if it is possible to add the files in your gsi; only the files the application requires;
https://drive.google.com/file/d/19G5H2Hq51z02V6LDmscI-nHxMgYPst9F/view?usp=drivesdk
