### ISSUE TITLE
[v119][ARM64 ab][Xiaomi Redmi Note 8] issues

### ISSUE THREAD

**Issue by lead4good** [phhusson/treble_experimentations#882]
Can't activate wifi, deactivates after one second. Which logs shall I provide?

- [ ] wifi not working
- [ ] audio not working (doesn't playback ringtones in settings)
- [ ] video playback of mp4 files doesn't work
- [ ] adaptive brightness seems to be not working
- [ ] very long boot time

[logcat.txt (without magisk)](https://github.com/phhusson/treble_experimentations/files/3828758/logcat.txt)
[dmesg.txt (magisk)](https://github.com/phhusson/treble_experimentations/files/3828759/dmesg.txt)

**Comment by phhusson** [comment]
If you're using Magisk, you need to uninstall it, that's a known incompatibility with it.
If you're not, provide `adb logcat` right after boot

**Comment by lead4good** [comment]
please see updated description

**Comment by lead4good** [comment]
Most of these issues seem to have been resolved after reflashing the global stock firmware. Closing for now...
