### ISSUE TITLE
Cubot P20 [AOSP 204] MT6750T: Camera not working 

### ISSUE THREAD

**Issue by Joker152** [phhusson/treble_experimentations#893]
Good afternoon! Can you fix the camera on Your Сubot P20 Android 8.0 MT6750T phone ? Logs attached. The Camera app does not see the device
[cam.txt](https://github.com/phhusson/treble_experimentations/files/3836137/cam.txt)
[log.txt](https://github.com/phhusson/treble_experimentations/files/3836138/log.txt)

**Comment by phhusson** [comment]
I can't find any info about camera yet in there, though I see a "simple" crash about fingerprint.
Does your device have a fingerprint sensor, and does it work?
If you do have a fingerprint sensor, and it doesn't work, open a new issue, with the same log.txt, and the select error log is `android.hardwar: type=1400 audit(0.0:96): avc: denied { read write } for name="madev0" dev="tmpfs" ino=1334 scontext=u:r:hal_fingerprint_default:s0 tcontext=u:object_r:device:s0 tclass=chr_file permissive=0`

**Comment by phhusson** [comment]
Ok, for camera It looks like the logs are too early to be caught this way.

Please do: `adb shell phh-su 0 setprop ctl.restart camera-provider-2-4` and re-do logcat

**Comment by Joker152** [comment]
[log.txt](https://github.com/phhusson/treble_experimentations/files/3837066/log.txt)

**Comment by Joker152** [comment]
The fingerprint didn't work,but that's the vendor's problem.

**Comment by phhusson** [comment]
What do you mean it's vendor problem?
It's a google certified device, released with oreo?If so, then no that's not vendor's problem.

**Comment by phhusson** [comment]
Uh that's weird. So your issue is that your vendor has a security patch level too high, but I can't see how you manage to boot?!?
You didn't do any weird things like using some blobs of some other device?

**Comment by Joker152** [comment]
The vendor was used from another device, so the fingerprint did not work. The fingerprint works with the native vendor. The camera does not work at all

**Comment by phhusson** [comment]
Ok, then please give me logcat on original unmodified OEM vendor.

**Comment by Joker152** [comment]
original unmodified OEM vendor
[log.txt](https://github.com/phhusson/treble_experimentations/files/3839776/log.txt)

**Comment by Joker152** [comment]
Unmodified OEM vendor
[log.txt](https://github.com/phhusson/treble_experimentations/files/3839805/log.txt)

**Comment by Joker152** [comment]
Fixed
