### ISSUE TITLE
AOSP Q v204 OP7T, fingerprint sensor not working

### ISSUE THREAD

**Issue by joske** [phhusson/treble_experimentations#897]
When I try to enroll fingerprint, nothing happens. I searched the issues list and apparently for some devices it does work, so logging bug report.

**Comment by phhusson** [comment]
Yeah under-display fingerprint sensor requires some work.
I have support for Xiaomi's under-display fingerprint, so adapting it to support OnePlus's under-display fingerprint should be fairly based on Lineage changes.
But this hasn't been done yet, and I don't have enough time to handle that myself.
However I'd be happy to help any dev who wants to do that.

**Comment by joske** [comment]
I'm a professional software dev (java/C/C++) but no experience in AOSP development. Try giving some pointers?

**Comment by phhusson** [comment]
See #449

**Comment by phhusson** [comment]
As a quick update, I managed to get optical fingerprint sensor to work on my Realme X2 Pro, which is very similar to OnePlus. There will probably be a fix soon-ish.
