### ISSUE TITLE
[Mtk 6763] | Tecno Ca8 (x pro) Media codec issue AOSP 10 V204

### ISSUE THREAD

**Issue by MarivanUG** [phhusson/treble_experimentations#900]
Most of the bugs seem to have been fixed with this update however Media play back is still an issue.

**Comment by dmurimi14** [comment]
What is the exact issue?

**Comment by MarivanUG** [comment]
Like when I open Facebook,Videos try to autoplay but they don't play well...the same thing happens with WhatsApp statuses and other inbuilt video apps. They play the same scene repeatedly...

**Comment by dmurimi14** [comment]
> Like when I open Facebook,Videos try to autoplay but they don't play well...the same thing happens with WhatsApp statuses and other inbuilt video apps. They play the same scene repeatedly...

I had the same issue on Infinix NOTE 5 but there is a way to fix it

**Comment by dmurimi14** [comment]
> > > Like when I open Facebook,Videos try to autoplay but they don't play well...the same thing happens with WhatsApp statuses and other inbuilt video apps. They play the same scene repeatedly...
> > 
> > 
> > I had the same issue on Infinix NOTE 5 but there is a way to fix it
> 
> Please share with me the fix

PM me on Telegram https://t.me/DennisMurimiWachira

**Comment by MarivanUG** [comment]
Thanks @dmurimi14.I'm ok now.

**Comment by HedigehoG** [comment]
> Thanks @dmurimi14.I'm ok now.

May be you help other?

**Comment by phhusson** [comment]
I guess their solution is to remove h264 decoding from
/vendor/etc/media_codecs.xml

**Comment by waryag123** [comment]
Hello, please tell me how you fixed the stuttering video in the social on android gsi 10. networks ???

**Comment by phhusson** [comment]
noone has actually fixed it yet, only workarounds.
