### ISSUE TITLE
Storage shows up as 16GBs on Mi 9

### ISSUE THREAD

**Issue by Syedayy** [phhusson/treble_experimentations#901]
My phone's storage size shows up as 16GBs on my 128GB Mi 9 running v204. This issue was present on v203 as well.

**Comment by phhusson** [comment]
The way you did factory reset is broken.
If you did the factory reset using stock recovery, I can a workaround for
it.

**Comment by Syedayy** [comment]
Factory reset using the stock recovery fixed the issue. Thank you for the suggestion!
