### ISSUE TITLE
Stuck at bootanimation

### ISSUE THREAD

**Issue by siddhrsh** [phhusson/treble_experimentations#902]
realme c2 
Mediatek 6762 & decrypted device
stuck at boot animation tried with stock boot & magisk patched boot too
installed patched boot image with phh Magisk 20.2 log
[magiskLog.txt](https://github.com/phhusson/treble_experimentations/files/3842016/magiskLog.txt)
with stock boot log
[Stocklog.txt](https://github.com/phhusson/treble_experimentations/files/3842046/Stocklog.txt)

**Comment by phhusson** [comment]
Try:
1. While the device is trying to boot, stuck on the boot animation, do `adb shell phh-su 0 setprop debug.stagefright.ccodec 0`, wait 5 more minutes, and if it still didn't boot, do the log again
2. Boot vanilla variant (i.e. the one without gapps)

**Comment by siddhrsh** [comment]
1.Boots after giving adb command but giving error of screen lock was already changed try again with new screen lock
2.Tried to boot vanilla variant same error as gapps varient (not tried with above adb command )
i have attached the log just check 
will it fix after giving adb command
[vanilalog.txt](https://github.com/phhusson/treble_experimentations/files/3844600/vanilalog.txt)

**Comment by siddhrsh** [comment]
@phhusson  please tell me bug is different or same????

**Comment by phhusson** [comment]
Why do you need to wait for me to try a simple adb command...?
For your 1. issue, just do a factory reset using stock recovery

**Comment by siddhrsh** [comment]
Thanks for helping i just want ans for 1st question only i tried it on same day of comment & i forgot to delete it
