### ISSUE TITLE
root remove

### ISSUE THREAD

**Issue by luisdambrowski** [phhusson/treble_experimentations#906]
I tested the gsi and saw only two errors;

but for my daily use I can't access with root, is this possible completely remove root?

**Comment by ponces** [comment]
You can do it running the follwoing commands:

`adb shell`
`su 0`
`/system/bin/phh-securize.sh`

**Comment by luisdambrowski** [comment]
This works; I still need to uninstall the superSu app.  With this command the app remains installed;

**Comment by ponces** [comment]
Yes, the script does not uninstall the app.
I believe it remains on `/system/app/me.phh.superuser`.

**Comment by luisdambrowski** [comment]
I need to remove it because I use an app that thinks the device is rooted; even not being;
