### ISSUE TITLE
arm-aonly-vanilla without supersu.

### ISSUE THREAD

**Issue by luisdambrowski** [phhusson/treble_experimentations#909]
@phhusson I need a version without root access completely, it is possible?

system-quack-arm-aonly-vanilla.img.xz

**Comment by phhusson** [comment]
Remove it with
`adb shell phh-su 0 /system/bin/phh-securize.sh`

Le ven. 15 nov. 2019 à 01:10, luis marcelo <notifications@github.com> a
écrit :

**Comment by luisdambrowski** [comment]
right; this removes root access; but does the supersu app remain?


I used this and the app remained;
adb shell
su 0
/system/bin/phh-securize.sh
