### ISSUE TITLE
Phh-magisk not working for AOSP 10 V204 [Mtk 6763] | Tecno Ca8

### ISSUE THREAD

**Issue by MarivanUG** [phhusson/treble_experimentations#912]
I prefer magisk over super su but unfortunately i'm unable to get magisk working on my device. I flashed the phh-magisk zip as per the recommendation of Aosp 10 v200 but the magisk manager still says magisk not installed. Any assistance is highly appreciated.

**Comment by Joker152** [comment]
libdirect-coredump.so from vendor/lib(lib64) copy to system/lib(lib64) and Magisk will work

**Comment by MarivanUG** [comment]
THis fix is for phh-magisk?

**Comment by MarivanUG** [comment]
> libdirect-coredump.so from vendor/lib(lib64) copy to system/lib(lib64) and Magisk will work
This fix worked for me. Thanks a lot
