### ISSUE TITLE
[Redmi Note 8] WiFi not turning on - AOSP 9.0 v121

### ISSUE THREAD

**Issue by MrPhyber** [phhusson/treble_experimentations#919]
Hello,
I flashed AOSP 9.0 v121 GSI on a Xiaomi Redmi Note 8 along with Magisk v20.1.
I picked arm64-ab-vanilla.
Almost everything works except for the WiFi. Seems to turn on but at the end it doesn't.
Along with this issue I'm providing dmesg output.
I tried to uninstall Magisk but the issue persists.

[dmesg.txt](https://github.com/phhusson/treble_experimentations/files/3854106/dmesg.txt)

**Comment by phhusson** [comment]
Usually this issue is caused by a mismatch between boot.img and vendor.img
version.
Flash back both vendor and boot from stock rom.
