### ISSUE TITLE
(AOSP 10 v.204) No way to dismiss tips in the settings

### ISSUE THREAD

**Issue by modestOne** [phhusson/treble_experimentations#921]
It's possible to dismiss only some of the tips by just doing whatever it is asking to do.
Before you you make a fix, is there a way to edit some config (i know what is root) or whatever and disable these tips?
My phone is Umidigi A5 Pro if it's relevant

>  ![Screenshot_20191116-192238](https://user-images.githubusercontent.com/45666259/69009860-e83e8a80-0983-11ea-9001-781e2a5dbaeb.png)

_PS: Also some of the video formats have super fast playback speed (so it skips most of the frames). It happens only in the Android UI and in some of the apps. I think it has something to do with my vendor. So i am asking just in case. Do you guys have this issue too or is it just me?_

**Comment by phhusson** [comment]
This is an AOSP "feature" there isn't much I'm going to do about it.
