### ISSUE TITLE
[Xiaomi Redmi 8A] olivelite Backlight strobe effect on Q and Pie

### ISSUE THREAD

**Issue by milankragujevic** [phhusson/treble_experimentations#923]
Hi,

I have a problem with the backlight on the `olivelite` (SDM439). When lowering or increasing brightness, the screen exibits a strobing effect, by pulsating the backlight very fast. 

After a second or two, the strobing stops and backlight works as intended. However, when the display tries to turn off (by animating a fade out), it strobes and then just suddenly turns off.

Turning on the display when exiting sleep mode does not exibit strobing.

I have created an overlay for the device, and copied power profile from `olive`, however, other than fixing the notch and padding in the status bar (though I did measure and edit the values to be appropriate for my device), nothing else changed.

This happens on Pie and Q, on v204 and v121.

**Comment by phhusson** [comment]
try adding your device to
https://github.com/phhusson/device_phh_treble/blob/android-9.0/rw-system.sh#L186

And push it to /system/bin/rw-system.sh

Le dim. 17 nov. 2019 à 19:55, Milan Kragujević <notifications@github.com> a
écrit :

**Comment by milankragujevic** [comment]
Resolved with @phhusson's suggestion. PR incoming. Closed.
