### ISSUE TITLE
Samsung S7 Edge (exynos) No Sound AOSP 10 V204

### ISSUE THREAD

**Issue by ramsakodvavi** [phhusson/treble_experimentations#926]
This version finally booted but there's no sound on call with or without hands free and no sound on speaker, youtube etc sound works on hands free.

**Comment by ramsakodvavi** [comment]
any fix or workaround?

**Comment by phhusson** [comment]
This isn't an OEM treble. Ask your treble dev.

**Comment by ramsakodvavi** [comment]
Ok, thank you.
