### ISSUE TITLE
Samsung S8 Plus - PixelExperience 10.0 BETA

### ISSUE THREAD

**Issue by pacocarismatico** [phhusson/treble_experimentations#929]
Hi,

I am having these issues:

- bluetooth is not working.
- some random reboot.

Many Thanks for your great work.

**Comment by phhusson** [comment]
Galaxy S8 isn't OEM treble, and I only trust bug reports on my aosp.
Now, there is a known instability issue on all Exynos devices, so you can
consider this is already taken in account.
For Bluetooth you'll need to ask your treble dev.

Le lun. 18 nov. 2019 à 10:02, pacocarismatico <notifications@github.com> a
écrit :
