### ISSUE TITLE
Aosp 10 bug°s in #mtk6739 

### ISSUE THREAD

**Issue by eg-abdurrahman** [phhusson/treble_experimentations#934]
My device with mt6739 soc,8.1 vendor..

I use 75 % gsi of all of the gsi buil till today..
In every gsi i got hotspot,location bug..except 8.1 gsi,,,
Android 10 also  doesn't work hotspot and location,,, #specially a game #pubg #freefire can't get .obb file.   internal and external storage work fine..
But the app didn't get the obb file.

**Comment by phhusson** [comment]
Please test if my AOSP GSI v122 has the hotspot problem
