### ISSUE TITLE
Msm xtended  10 not boting

### ISSUE THREAD

**Issue by eg-abdurrahman** [phhusson/treble_experimentations#937]
Msm xteneded 10,,even pie also didn't boot my device,,,,logcat showing media.audio_policy.xml not found

**Comment by phhusson** [comment]
I only support my AOSP directly.

**Comment by eg-abdurrahman** [comment]
Actually all the other gsi build from your aosp gsi.
For this i thought you will help..
Its ok
..i don't want it also..i just want to say your aosp gsi work on my device very well...
Just a location and hotspot won't work..and a game didn't getting its obb file from android\obb
