### ISSUE TITLE
[Moto G6 Play no boot][AOSP 10.0 v204]

### ISSUE THREAD

**Issue by MarcosPearce** [phhusson/treble_experimentations#938]
Does not boot, how do I get logcat? It's been a while since I'm trying, but to no avail.
Moto G6 Play XT1922-5

**Comment by phhusson** [comment]
Do you take the correct variant? 
Does pie GSI boot?

**Comment by MarcosPearce** [comment]
yes i'm using the correct, Gsi pie starts correctly

**Comment by Alphitaa** [comment]
Boot is already fixed for Pie vendor since v202. If you had Magisk installed previously you need to reflash a stock boot.img since any kind of magisk on the boot.img will make it bootloop at bootloader

**Comment by MarcosPearce** [comment]
alright I'll try this and post the result here

**Comment by MarcosPearce** [comment]
Result: gsi starts, camera working, digital printing working, sound working.

Thanks for the help and your attention
