### ISSUE TITLE
[HTC U11+ ocm][AOSP 10 v204 v208] Camera and bluetooth audio not working

### ISSUE THREAD

**Issue by 7HE-W0R1D** [phhusson/treble_experimentations#939]
Hi! I flashed my htc u11+ ocm to V204 but camera keeps on stopping, tried gcam, stock camera, and open camera, none worked. Also, bluetooth headsets don't work, sound only comes from speakers.
Tried AOSP 9.0, camera was fine but bluetooth audio didn't work still... Actually it only works on htc stock rom.
Some apps (TaoBao lite) cannot launch in AOSP 10, maybe because they dont support AOSP 10?
I'd love to help but I'm totally a noob at logcat and things like that, can anybody tell me what to do and which to provide?

**Comment by 7HE-W0R1D** [comment]
btw the rom crushed now, it automatically reboots and stuck at the android logo.

**Comment by phhusson** [comment]
Does camera work on v206?

**Comment by 7HE-W0R1D** [comment]
It's a 8.0 vendor.
I flashed v208 but the camera still don't work and screen glitches remain :(
Now the rom crushed again, the lock screen pattern didn't react, soon it reboots and now stuck on the android logo again.

**Comment by 7HE-W0R1D** [comment]
oops! Flashed the second time and I found that I could not boot the phone after the first boot. It just goes black, no android logo but has backlight on.
For logcat, is it enough to just connect the phone to pc and use the command "adb logcat" and copy all the things in the terminal?

**Comment by phhusson** [comment]
yes

**Comment by 7HE-W0R1D** [comment]
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/3984223/logcat.txt)
[info.txt](https://github.com/phhusson/treble_experimentations/files/3984226/info.txt)
I tried adb shell dumpsys media.camera > info.txt.
and adb logcat > logcat.txt
results are above, hope this will help.
Sorry about the huge size of logcat, I opened the camera app several times to try to capture the log because if I power the phone down it never reboots. Happy to provide more info ;)
