### ISSUE TITLE
[Huawei Mediapad M5/Kirin960] Bluetooth pairing issues

### ISSUE THREAD

**Issue by LeeHeap** [phhusson/treble_experimentations#94]
Hi
Bluetooth seems to be very selective of which devices it will pair with on the above device. For example I can pair a logitech BT keyboard, but not a logitech mouse.
No error UI is shown, the pairing procedure just states 'pairing' for a while and then stops. 

Logcat: https://pastebin.com/PZGYQBcQ

Rom build v20 for A devices with gapps and su

**Comment by phhusson** [comment]
@penn5

**Comment by penn5** [comment]
Probably fixed in newer builds through one way or another. Anyway I probably can't find anything in these logs I need hci traces

**Comment by phhusson** [comment]
Should be fixed with Huawei bluetooth workaround in treble settings
