### ISSUE TITLE
AOSP v204. No sound on Bluetooth headset.Device Axon7 8.1 Vendor

### ISSUE THREAD

**Issue by atakan33** [phhusson/treble_experimentations#941]
[audio_policy_configuration.zip](https://github.com/phhusson/treble_experimentations/files/3874921/audio_policy_configuration.zip)

[dumpsys media.audiopolicy.txt](https://github.com/phhusson/treble_experimentations/files/3874913/dumpsys.media.audiopolicy.txt)
[2019-11-21-08-11-35.txt](https://github.com/phhusson/treble_experimentations/files/3874914/2019-11-21-08-11-35.txt)

Axon 7 8.1 Vendor ( Not oem treble)

**Comment by StepanKHV** [comment]
You should use vendor 9.0 speedy. 
I use it and sound on Bluetooth work well.

**Comment by atakan33** [comment]
can you send audio_policy configuration.xml in vendor/etc

**Comment by StepanKHV** [comment]
audio_policy_configuration.xml
https://yadi.sk/d/EUyac0KgAckfFA

**Comment by atakan33** [comment]
@StepanKHV tried this with a little hope but doesnt work

**Comment by StepanKHV** [comment]
Use it as a vendor: https://androidfilehost.com/?fid=6006931924117923540

**Comment by JegorRysskin** [comment]
Using v206 also with speedy's vendor and the issue with bluetooth still persists.
