### ISSUE TITLE
[AOSP] [204] GPS not working

### ISSUE THREAD

**Issue by lucasdeeiroz** [phhusson/treble_experimentations#943]
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/3882582/logcat.txt)
GPS not working on Quack v204 on Motorola One (deen), Pie vendor. I get a "Caller doesn't have access to android.permission.ACCESS_FINE_LOCATION" error for Google Play Services in logcat, between others.

**Comment by phhusson** [comment]
Well grant it with adb shell pm grant?

**Comment by lucasdeeiroz** [comment]
I did that, but gms still gives me the same error. Still no GPS.

**Comment by lucasdeeiroz** [comment]
After granting permission manually, I get a lot of this in logcat:
```
ActivityManager: Appop Denial: Accessing service com.google.android.gms/com.google.android.location.internal.server.GoogleLocationService from pid=4723, uid=10056 requires appop COARSE_LOCATION
GCoreFlp: Unable to bind to GMS NLP
```

**Comment by lucasdeeiroz** [comment]
[logcat2.txt](https://github.com/phhusson/treble_experimentations/files/3882636/logcat2.txt)
Giving GMS both ACCESS_FINE_LOCATION and ACCESS_COARSE_LOCATION permission, I get these. I really don't know what it means.

**Comment by lucasdeeiroz** [comment]
The problem here was caused by a really stupid thing: Google Play Services had the location permission set to "only when the app is open" instead of "always". Solved and closed.
