### ISSUE TITLE
overlay for Redmi 7A

### ISSUE THREAD

**Issue by djemilbakhti** [phhusson/treble_experimentations#945]
[framework.zip](https://github.com/phhusson/treble_experimentations/files/3883594/framework.zip)

**Comment by phhusson** [comment]
Give `adb shell getprop` on gsi or stock

**Comment by djemilbakhti** [comment]
> Give `adb shell getprop` on gsi or stock and /vendor/build.prop

[build.prop.txt](https://github.com/phhusson/treble_experimentations/files/3883792/build.prop.txt)
[getprop.txt](https://github.com/phhusson/treble_experimentations/files/3883794/getprop.txt)
