### ISSUE TITLE
AOSP 10.0 v204 wifi issue on Pixel 3aXL

### ISSUE THREAD

**Issue by biboyrafik25** [phhusson/treble_experimentations#948]
device booting but wifi dont work at all

**Comment by phhusson** [comment]
It works fine on my P3a

Flash again stock unmodified boot.img and vendor.img (unmodified = no magisk, no disable encrypt, no twrp, ... at least on the booting slot)

**Comment by biboyrafik25** [comment]
steps are : disable verify boot/ flashPhh-Trebble/unmodified boot.img and vendor/ clear data and reboot?

**Comment by phhusson** [comment]
Yes
To be clear, disabling verify is done by flashing https://dl.google.com/developers/android/qt/images/gsi/vbmeta.img to vbmeta partition

**Comment by biboyrafik25** [comment]
Sorry, i have issues : can't erase system or flashing some error with fastbootD

**Comment by phhusson** [comment]
what is your actual error?

Le lun. 25 nov. 2019 à 11:43, biboyrafik25 <notifications@github.com> a
écrit :

**Comment by biboyrafik25** [comment]
![Capture](https://user-images.githubusercontent.com/55406730/69535689-bf6a5680-0f7c-11ea-9c1a-df7f3621832e.PNG)

**Comment by phhusson** [comment]
yeah you need to do `fastboot reboot fastboot` to Reboot into fastbootd

Le lun. 25 nov. 2019 à 12:11, biboyrafik25 <notifications@github.com> a
écrit :

**Comment by biboyrafik25** [comment]
Ok now im on fastbootd with reboot system or BL, recovery, or power of ....désolé mais je fais quoi maintenant ?
![Capture](https://user-images.githubusercontent.com/55406730/69536597-87fca980-0f7e-11ea-8fd1-dd59ce4436b7.PNG)

**Comment by phhusson** [comment]
now you can do fastboot flash system system.....img

Le lun. 25 nov. 2019 à 12:24, biboyrafik25 <notifications@github.com> a
écrit :

**Comment by biboyrafik25** [comment]
![Capture](https://user-images.githubusercontent.com/55406730/69537228-fa21be00-0f7f-11ea-8c90-8bf355b46e80.PNG)

**Comment by phhusson** [comment]
fastboot delete-logical-partition product_a


And try again the flash system


Le lun. 25 nov. 2019 à 12:34, biboyrafik25 <notifications@github.com> a
écrit :

**Comment by biboyrafik25** [comment]
Done
Now fastboot -w and reboot ?
![Capture](https://user-images.githubusercontent.com/55406730/69538184-04dd5280-0f82-11ea-98c7-01ce3f407119.PNG)

**Comment by phhusson** [comment]
I recommend to use recovery for factory reset rather than `fastboot -w`

Le lun. 25 nov. 2019 à 12:49, biboyrafik25 <notifications@github.com> a
écrit :

**Comment by biboyrafik25** [comment]
Yeah all works fine thx a lot for ur help and ur patience
