### ISSUE TITLE
[Galaxy S9 (Snapdragon)] Brightness is very low

### ISSUE THREAD

**Issue by unazz** [phhusson/treble_experimentations#95]
I think it will be fixed by adding "starqlte" (S9) and "star2qlte" (S9+) to this line
https://github.com/phhusson/treble_patches/blob/2acef1db091ca41920a750b14553e38f17532357/patches/platform_frameworks_base/0004-Fix-backlight-control-on-Galaxy-S9.patch#L27

**Comment by phhusson** [comment]
I commited it in
https://github.com/phhusson/platform_frameworks_base/commit/6b3a97fee5d074a87ce3cedeba54b3ac45cc5563

we'll see

**Comment by phhusson** [comment]
Sorry for the very long time to answer.

https://github.com/phhusson/platform_frameworks_base/commit/a770748f2aaef6ee35657d38e72927f208e25aad

Does this good look to you?

**Comment by unazz** [comment]
Good fix!

**Comment by unazz** [comment]
I flashed AOSP 9.0 v103, brightness is working well.
Thank you very much for the fix!!
