### ISSUE TITLE
aosp v121 fingerprint enrollment not completed with Huawei enjoy 7s 9.0 stock vender

### ISSUE THREAD

**Issue by Qerris** [phhusson/treble_experimentations#954]
[2019:11:29 11:08:10][pid:952,cpu4,fingerprint@2.1][I/fingerprint] fingerprint_ioctl FP_IOC_CMD_DISABLE_IRQ
[  383.406890] [pid:952,cpu4,fingerprint@2.1][I/fingerprint] fingerprint_ioctl FP_IOC_CMD_ENABLE_IRQ
[  383.406982] [pid:952,cpu4,fingerprint@2.1]tui_flg is 0, fp_ready_flg is 1, fp_fiq_flg is 0
[  383.407348] [pid:952,cpu4,fingerprint@2.1]tui_flg is 0, fp_ready_flg is 1, fp_fiq_flg is 0
[  383.482543] [pid:2358,cpu2,kworker/2:2](2358, kworker/2:2)cmd_monitor_tick: [cmd_monitor_tick] pid=785,pname=fingerprint@2.1,tid=952,tname=fingerprint@2.1,lastcmdid=21,count=19
timetotal=630000 us returned, remained command(s)=1
[  383.492492] [pid:240,cpu0,kworker/0:1H]sp805-wdt e8a06000.watchdog0: watchdog kick now 32K 12564749 rqclock 375521296989 ret 1
[  383.514312] [pid:952,cpu0,fingerprint@2.1]tui_flg is 0, fp_ready_flg is 1, fp_fiq_flg is 0
[  383.514373] [pid:952,cpu0,fingerprint@2.1][I/fingerprint] fingerprint_input_report key=117
[  383.514434] [pid:952,cpu0,fingerprint@2.1][I/fingerprint] fingerprint_ioctl FP_IOC_CMD_SEND_UEVENT
[  383.619445] [pid:671,cpu6,hwvibrator@1.0-]vibrator hisi_vibrator@fff34000: hisi_vibrator open
[  383.642700] [pid:0,cpu6,swapper/6]vibrator hisi_vibrator@fff34000: hisi_vibrator close
[  383.650451] [pid:671,cpu6,hwvibrator@1.0-]vibrator hisi_vibrator@fff34000: hisi_vibrator open
[  383.672882] [pid:0,cpu6,swapper/6]vibrator hisi_vibrator@fff34000: hisi_vibrator close
[  384.153503] [pid:952,cpu4,fingerprint@2.1][I/fingerprint] fingerprint_ioctl FP_IOC_CMD_DISABLE_IRQ
[  384.175323] [pid:952,cpu4,fingerprint@2.1][I/fingerprint] fingerprint_ioctl FP_IOC_CMD_ENABLE_IRQ
[  384.175415] [pid:952,cpu4,fingerprint@2.1]tui_flg is 0, fp_ready_flg is 1, fp_fiq_flg is 0
[  384.175659] [pid:952,cpu4,fingerprint@2.1]tui_flg is 0, fp_ready_flg is 1, fp_fiq_flg is 0
[  384.391754] [pid:952,cpu2,fingerprint@2.1]tui_flg is 0, fp_ready_flg is 1, fp_fiq_flg is 0
[  384.391845] [pid:952,cpu2,fingerprint@2.1][I/fingerprint] fingerprint_input_report key=117
[  384.391967] [pid:952,cpu2,fingerprint@2.1][I/fingerprint] fingerprint_ioctl FP_IOC_CMD_SEND_UEVENT
[  384.516754] [2019:11:29 11:08:11][pid:671,cpu5,hwvibrator@1.0-]vibrator hisi_vibrator@fff34000: hisi_vibrator open
[  384.542602] [pid:0,cpu5,swapper/5]vibrator hisi_vibrator@fff34000: hisi_vibrator close
[  384.547851] [pid:671,cpu5,hwvibrator@1.0-]vibrator hisi_vibrator@fff34000: hisi_vibrator open
[  384.572631] [pid:0,cpu5,swapper/5]vibrator hisi_vibrator@fff34000: hisi_vibrator close
[  385.162414] [pid:952,cpu5,fingerprint@2.1][I/fingerprint] fingerprint_ioctl FP_IOC_CMD_DISABLE_IRQ
[  385.186157] [pid:952,cpu5,fingerprint@2.1][I/fingerprint] fingerprint_ioctl FP_IOC_CMD_ENABLE_IRQ
[  385.186248] [pid:952,cpu5,fingerprint@2.1]tui_flg is 0, fp_ready_flg is 1, fp_fiq_flg is 0
[  385.347076] [pid:952,cpu1,fingerprint@2.1]tui_flg is 0, fp_ready_flg is 1, fp_fiq_flg is 0
[  385.347137] [pid:952,cpu1,fingerprint@2.1][I/fingerprint] fingerprint_input_report key=117
[  385.347259] [pid:952,cpu1,fingerprint@2.1][I/fingerprint] fingerprint_ioctl FP_IOC_CMD_SEND_UEVENT

**Comment by phhusson** [comment]
Probably fixed in https://github.com/phhusson/device_phh_treble/commit/07632a82916b10cda291e0c7aba2582159b0559b

(that's commit for Quack, I'm currently testing commit for Pie)

**Comment by phhusson** [comment]
https://github.com/phhusson/device_phh_treble/commit/dc8484b74fb928d400938d87b43e9a5417a1274c Tested successfully on my Honor View 10 on Pie

**Comment by Qerris** [comment]
Thanks for your great work!
