### ISSUE TITLE
[Honor 8]Boot Loop

### ISSUE THREAD

**Issue by k10876** [phhusson/treble_experimentations#955]
When I was flashing 9.0 v121, it failed to boot.
Boot Loop on 10.0 v204.
I have copied the output on command `adb logcat`, on 10.0 v204.
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/3907047/logcat.txt)

**Comment by phhusson** [comment]
The issue is that you're using Magisk.
You need to either uninstall Magisk or install customized magisk, see https://sourceforge.net/projects/expressluke-gsis/files/Extras/phh-magisk-ten/

**Comment by k10876** [comment]
Thanks a lot.
Problem resolved.
I hope the project would be much better!
