### ISSUE TITLE
[AOSP Q] [Asus Zenfone Max M2] Camera doesn''t work

### ISSUE THREAD

**Issue by Assunzain** [phhusson/treble_experimentations#966]
DEVICE : ASUS ZENFONE MAX M2 (X01AD)
Vendor : Pie Stock
Support : ARM64 AB

The camera and the flashlight are not working, and the camera application when opened will be forceclosed.

Tested on v204 and v205

**Comment by Assunzain** [comment]
[LOGS](https://drive.google.com/file/d/1-TfcNl49aFQVYfeFO3fE_I_WTzavnqyq/view?usp=drivesdk)

**Comment by phhusson** [comment]
You had multiple issues listed. I edited this one to only mention camera, please open other issues for your other problems.

**Comment by phhusson** [comment]
I need logs right after boot

**Comment by Assunzain** [comment]
okay

**Comment by Assunzain** [comment]
12-03 13:15:23.112 17087 17087 E vndksupport: Could not load /vendor/lib/hw/camera.msm8953.so from default namespace: dlopen failed: library "libandroid.so" not found.
12-03 13:15:23.112 17087 17087 E HAL     : load: module=/vendor/lib/hw/camera.msm8953.so
12-03 13:15:23.112 17087 17087 E HAL     : unknown
12-03 13:15:23.112 17087 17087 E CamProvider@2.4-impl: Could not load camera HAL module: -22 (Invalid argument)
12-03 13:15:23.112 17087 17087 E CamProvider@2.4-impl: HIDL_FETCH_ICameraProvider: camera provider init failed!
12-03 13:15:23.113 17087 17087 E android.hardware.camera.provider@2.4-service: Could not get passthrough implementation for android.hardware.camera.provider@2.4::ICameraProvider/legacy/0.

**Comment by Assunzain** [comment]
v206 same error

**Comment by Assunzain** [comment]
full logs https://drive.google.com/file/d/1-TfcNl49aFQVYfeFO3fE_I_WTzavnqyq/view?usp=drivesdk


sorry I don't know how to upload logs here

**Comment by Assunzain** [comment]
12-03 12:42:33.317  1457  1457 W ActivityManager: Unable to start service Intent { act=android.service.appprediction.AppPredictionService cmp=com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiPredictionService } U=0: not found 12-03 12:42:33.317  1457  1457 W RemoteAppPredictionService: could not bind to Intent { act=android.service.appprediction.AppPredictionService cmp=com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiPredictionService } using flags 67108865 12-03 12:42:33.359  1457  1634 I ActivityManager: Start proc 14176:com.android.camera2/u0a114 for activity {com.android.camera2/com.android.camera.CameraLauncher} 12-03 12:42:33.512 14176 14176 E AndroidRuntime: FATAL EXCEPTION: main 12-03 12:42:33.512 14176 14176 E AndroidRuntime: Process: com.android.camera2, PID: 14176 12-03 12:42:33.512 14176 14176 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.camera2/com.android.camera.CameraActivity}: java.lang.NullPointerException 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 12-03 12:42:33.512 14176 14176 E AndroidRuntime: Caused by: java.lang.NullPointerException 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at java.util.Hashtable.put(Hashtable.java:461) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at com.android.camera.one.v2.Camera2OneCameraManagerImpl.findCameraId(Camera2OneCameraManagerImpl.java:148) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at com.android.camera.one.v2.Camera2OneCameraManagerImpl.findFirstCameraFacing(Camera2OneCameraManagerImpl.java:114) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at com.android.camera.one.v2.Camera2OneCameraManagerImpl.<init>(Camera2OneCameraManagerImpl.java:77) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at com.android.camera.one.v2.Camera2OneCameraManagerImpl.create(Camera2OneCameraManagerImpl.java:61) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at com.android.camera.one.OneCameraModule.provideOneCameraManager(OneCameraModule.java:68) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at com.android.camera.CameraActivity.onCreateTasks(CameraActivity.java:1487) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at com.android.camera.util.QuickActivity.onCreate(QuickActivity.java:114) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7803) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7792) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306) 12-03 12:42:33.512 14176 14176 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 12-03 12:42:33.512 14176 14176 E

**Comment by phhusson** [comment]
Fixed in https://github.com/phhusson/vendor_vndk/commit/ff5ec22036e10de41bfa4b134d1a46de5c623fca
