### ISSUE TITLE
[Xiaomi] No audio from ringtones/notifications/alarms

### ISSUE THREAD

**Issue by AndyCGYan** [phhusson/treble_experimentations#968]
Device: Redmi K20 Pro (raphael), Mi 9 SE (grus), but potentially applies to all Xiaomi devices on Q vendor?
PHH AOSP version: v204
Vendor version: Q (MIUI 11)

No audio from ringtones/notifications/alarms, be it when they're previewed in Settings or actually triggered. Media playback and call audio works just fine though.
Log excerpt from when I preview one of the ringtones in Settings: [ring.txt](https://github.com/phhusson/treble_experimentations/files/3922260/ring.txt)

**Comment by elpollol** [comment]
I have the same exactly problem with MI8SE (sirius) with Q vendor.
[ringtonenotworking.txt](https://github.com/phhusson/treble_experimentations/files/3934880/ringtonenotworking.txt)

**Comment by AndyCGYan** [comment]
Seems to be fixed with an alternate `/vendor/etc/audio_policy_configuration.xml` (which is included in a "fix" flashable zip someone sent me). I'll upload both here, as well as a log excerpt from when I preview one of the ringtones in Settings using this alternate xml, so anyone knowledgeable can figure out what's the crucial difference.
[audio_policy_configuration.zip](https://github.com/phhusson/treble_experimentations/files/4040508/audio_policy_configuration.zip)
[ring-alternate.txt](https://github.com/phhusson/treble_experimentations/files/4040509/ring-alternate.txt)

**Comment by AndyCGYan** [comment]
Comparing the two configurations, one immediately obvious difference is an additional "Speaker Safe" device/path, which was then used when the original `audio_policy_configuration` is in place. Removing all mentions of this "safe" device/path from `audio_policy_configuration.xml` makes the device use "Speaker" again and the issue is fixed.
The "safe" device/path seems to be for mono speaker output, but K20 Pro doesn't have dual speakers in the first place, and the item isn't present in the configuration in Pie vendor anyway, so I assume this is safe to do.

**Comment by Koenkk** [comment]
I had exactly the same issue, after applying the fix from @AndyCGYan it works now! (including bluetooth audio and calling). Big thanks @AndyCGYan !

**Comment by phhusson** [comment]
Well if anyone comes here, before trying @AndyCGYan 's workaround, please try to select "Use alternate audio policy" in Qualcomm section of Treble settings, and report back.

**Comment by AndyCGYan** [comment]
> "Use alternate audio policy"

Can confirm that this works (after a reboot) - thanks, closing issue.
