### ISSUE TITLE
[Lineage/Others] Enable the "extend apps" flags

### ISSUE THREAD

**Issue by phhusson** [phhusson/treble_experimentations#97]
This is for screens > 16:9, to optionnally remove black bar at the bottom

**Comment by TadiT7** [comment]
Refer to:
https://github.com/LineageOS/android_device_samsung_star-common/commit/7a00b50a7045e1f41ec13dc29830086e7e0ac942
https://github.com/LineageOS/android_lineage-sdk/commit/5bfb5fafa6756422728be2867452fd86d1aed8c1

**Comment by phhusson** [comment]
Fixed even on AOSP with:

https://github.com/phhusson/platform_frameworks_base/commit/c5614e24c92589437b8737b3ac39f7d43e4bd61e
https://github.com/phhusson/treble_app/commit/159413cbd58703757208761f7e329fe93f8e7127
