### ISSUE TITLE
[Galaxy S9+ exynos] [Q vendor]] Brightness not working

### ISSUE THREAD

**Issue by tpaulprasad** [phhusson/treble_experimentations#970]
I have encountered problem on galaxy exynos s9+ on android 10 vendor
Brightness slider not working.Unable to adjust brightness

**Comment by phhusson** [comment]
Please provide result of `lshal`
and see if some of the following commands change brightness:
`lightsctl BACKLIGHT 808080800`
`lightctl BACKLIGHT 80`
`lightcstl BACKLIGHT 80 HARDWARE 0 0`

**Comment by tpaulprasad** [comment]
Please guide me how to execute these commands

**Comment by tpaulprasad** [comment]
Brightness started working after beta 2 update
