### ISSUE TITLE
chrome  video  

### ISSUE THREAD

**Issue by djemilbakhti** [phhusson/treble_experimentations#973]
AOSP Q v204 & v205
DEVICE :redmi 7a 

![Screenshot_20191205-111658](https://user-images.githubusercontent.com/39235831/70227039-33151c00-1752-11ea-8753-b27e46a40958.png)

**Comment by KhushrajRathod** [comment]
Please explain what exactly is wrong, and when does this issue occur. Is it only on this site, does it occur everywhere e.t.c. Test using v216 or v217, although v217 may be unstable

**Comment by djemilbakhti** [comment]
is fixed in chrome v80 and later
