### ISSUE TITLE
[Lenovo L78071] Strange behaviour of brightness slider, flickering when screen is dimming

### ISSUE THREAD

**Issue by whc2001** [phhusson/treble_experimentations#975]
Flashed latest system on my Lenovo Z5s (L78071), and seems like there are two problems related to backlight:

1. The brightness slider works in a strange manner:
```
> A normal brightness slider does this: 
[min value greater than 0] .................................................................[4095]
> The brightness slider of this system on my phone does this:
[289]......[433][0].[32]....[192]...[289]...[433][16].[64].[192]..[449][16].[64].[192]..[449].[594]

(... means linear changing, 0 means backlight completely off)
```
Seems like the slider is divided into multiple segments, the latter part is repeating multiple times really quick, and dragging the knob can cause a strobe effect. One specific spot on the former part can turn the backlight completely off.

2. When the screen automatically dims (because of screen timeout), the backlight flashes just like dragging the knob over the latter part of the brightness slider, tapping the screen to restore will have the same effect. However, if using power button to make the device sleep or wake up, the backlight acts normally.

I looked for past issues:
```
cat /sys/class/backlight/panel0-backlight/max_brightness
4095

getprop persist.sys.qcom-brightness
4095
```
Tried to set qcom-brightness to 4093, no effect.
[getprop-all.txt](https://github.com/phhusson/treble_experimentations/files/3929098/getprop-all.txt)

For now I can use terminal emulator to manually set `/sys/class/backlight/panel0-backlight/brightness` without any problem, and prevent screen goes dim by setting screen timeout to 30 minutes.

**Comment by phhusson** [comment]
try setting the property to 255 and -1

**Comment by whc2001** [comment]
Setting to 255 will cause max brightness maxing out at 449, setting to -1 solves the problem immediately (full range from 160 to 4095). Thanks!
