### ISSUE TITLE
nfc does not work Doogee bl9000

### ISSUE THREAD

**Issue by waryag123** [phhusson/treble_experimentations#977]
nfc does not work help. tried aosp 205 and 206. phone doogee bl9000 mtk 6763, arm64 A. android 8.1 out of the box.
logs 205
[2019-12-06-10-57-25.txt](https://github.com/phhusson/treble_experimentations/files/3931156/2019-12-06-10-57-25.txt)
[2019-12-06-11-04-28.txt](https://github.com/phhusson/treble_experimentations/files/3931157/2019-12-06-11-04-28.txt)
Logs 206
[full.txt](https://github.com/phhusson/treble_experimentations/files/3931162/full.txt)
[nfc.txt](https://github.com/phhusson/treble_experimentations/files/3931163/nfc.txt)
android 9 nfc not working too
Help, I can throw logs with android 9. Patches did not help.

**Comment by JegorRysskin** [comment]
Same on ZTE Axon 7

**Comment by waryag123** [comment]
> nfc does not work help. tried aosp 205 and 206. phone doogee bl9000 mtk 6763, arm64 A. android 8.1 out of the box.
> logs 205 
Phhusson help please do not android 9
> [2019-12-06-10-57-25.txt](https://github.com/phhusson/treble_experimentations/files/3931156/2019-12-06-10-57-25.txt)
> [2019-12-06-11-04-28.txt](https://github.com/phhusson/treble_experimentations/files/3931157/2019-12-06-11-04-28.txt)
> Logs 206
> [full.txt](https://github.com/phhusson/treble_experimentations/files/3931162/full.txt)
> [nfc.txt](https://github.com/phhusson/treble_experimentations/files/3931163/nfc.txt)
