### ISSUE TITLE
AOSP 10 Not Booting with New Magisk Zips

### ISSUE THREAD

**Issue by AmanPanchal** [phhusson/treble_experimentations#981]
The new Magisk ver like v20 is not Booting in this rom, except only your provided Magisk which is modded by phhusson , works!
I want to use a module so I want latest Magisk ver for it to work. Can someone tell the process to mod the new Magisk ver zip to make this rom boot or provide the modded latest Magisk zip yourself. 

Thanks
@phhusson

**Comment by phhusson** [comment]
ExpressLuke has updated versions:
https://sourceforge.net/projects/expressluke-gsis/files/Extras/phh-magisk-ten/
the patch is in `common/boot_patch.sh`
before the cpio edit that add magisk, add
```./magiskboot cpio ramdisk.cpio \
    "rm init.zygote32.rc" \
    "rm init.zygote64_32.rc"
```

**Comment by AmanPanchal** [comment]
Thanks, it worked!!
