### ISSUE TITLE
[v206][nubia z18 - NX606J] [overlay request]

### ISSUE THREAD

**Issue by demonical** [phhusson/treble_experimentations#982]
the brightnes is not working at all (stay at maximum level)
if someone can make an overlay to test.
brand: zte Nubia. model: NX606J / z18
cpu: sdm845
fw version: CN 2.26 /Android 8.1
tested on: v204/v205/v206.
deodexed framework-res.apk, framework-nubia-res.apk & build.prop from vendor image: 
EDIT: 
[framework_build.prop.zip](https://github.com/phhusson/treble_experimentations/files/3939446/framework_build.prop.zip)

if needed lshal:
[lshal log.txt](https://github.com/phhusson/treble_experimentations/files/3937277/lshal.log.txt)
and getprop:
[getprop.txt](https://github.com/phhusson/treble_experimentations/files/3937275/getprop.txt)
(there are also 2-3 problems, will issue them tomorrow in new request.)

**Comment by phhusson** [comment]
Please attach the zip to this issue rather than putting it on a google drive

**Comment by demonical** [comment]
here it is.
[framework_build.prop.zip](https://github.com/phhusson/treble_experimentations/files/3939440/framework_build.prop.zip)

**Comment by phhusson** [comment]
Push the apk in the attached zip
[v.zip](https://github.com/phhusson/treble_experimentations/files/3942198/v.zip)
 to /system/overlay

**Comment by demonical** [comment]
the same, not working.
[logcatW_after.txt](https://github.com/phhusson/treble_experimentations/files/3942250/logcatW_after.txt)

**Comment by phhusson** [comment]
oh fuck I should have read your issue before doing the overlay


> the brightnes is not working at all (stay at maximum level)

This has nothing to do with overlays.
Try the following possibilities, from root terminal:
`setprop persist.sys.qcom-brightness -1`
`setprop persist.sys.qcom-brightness 255`
`setprop persist.sys.qcom-brightness 4095`
