### ISSUE TITLE
[Honor 8][AOSP 10 v206] SIM Card can't be recognized

### ISSUE THREAD

**Issue by k10876** [phhusson/treble_experimentations#985]
com.android.phone often stops working.
I can't use mobile data even if SIM Card plugged in.
**Emergency Call Can't be used.**

**Comment by phhusson** [comment]
I need logs:
`adb logcat -b all > log.txt`
Did you try both SIM slots?

**Comment by phhusson** [comment]
#984 says that at least one SIM card slot works fine.

**Comment by phhusson** [comment]
K, after further research, this is indeed a duplicate of #984 
So I'm closing this issue. #984 will be fixed in next Q release.

**Comment by k10876** [comment]
Thanks a lot
