### ISSUE TITLE
Endless reboot loop Redmi 6a, How to fix??

### ISSUE THREAD

**Issue by sshashank790** [phhusson/treble_experimentations#987]
After successfully unlocking the bootloader of my Redmi 6a, I tried to flash TWRP recovery via fastboot but accidentally I flashed the recovery for the pie version, but I was on the oreo version, when I rebooted into recovery, it just started rebooting, again and again, now the mi logo is also not showing, the only thing I can see is my phone is vibrating again and again in every few minutes, I unable to turn it on and also I am unable to boot it into fastboot because it just keeps vibrating again and again. Please tell me how can I fix this??

**Comment by eg-abdurrahman** [comment]
let me tell you ,yoi flash the wrong twrp recovery..
you should port this with your stock recovery.
Now you need to  flash the stock recovery.
It will solved the problem.
if it not then you will need to flash the flash file of your mobile.

**Comment by proganime1200** [comment]
then you bricked your phone thank you very much

**Comment by sshashank790** [comment]
> let me tell you ,yoi flash the wrong twrp recovery..
> you should port this with your stock recovery.
> Now you need to flash the stock recovery.
> It will solved the problem.
> if it not then you will need to flash the flash file of your mobile.

But when I try  to connect it to my pc, it don't recognizes my device

**Comment by eg-abdurrahman** [comment]
adb must  be installed on your pc

**Comment by sshashank790** [comment]
By ADB do you mean by ADB Drivers, YES I've already installed ADB Drivers but the thing I am unable to boot into Fastboot or any other mode, actually my REDMI 6a doesn't let me boot, it just keeps vibrating until it gets fully discharged, the mi logo is also not showing, even the screen is not glowing, it is just vibrating?? Please tell me how can I fix this. Pleaseeee?

**Comment by sshashank790** [comment]
> then you bricked your phone thank you very much

Please tell me how can I fix this? I am very sad, even I don't have any extra phone...... Pleaseeeeeeee

**Comment by phhusson** [comment]
This really doesn't look like the proper place to discuss this, try xda
