### ISSUE TITLE
[Aquaris X2 Pro] All 10 version problem GPS

### ISSUE THREAD

**Issue by zerostar-git** [phhusson/treble_experimentations#989]
My device Aquaris X2 Pro got problem that usually it lost the GPS. Google Maps and other apps can't detect the location.

**Comment by phhusson** [comment]
Does it mean it works on Pie?

**Comment by NguyenNinhAnh** [comment]
Thank you for your answer. Sorry, I did not try any version of Pie.

**Comment by phhusson** [comment]
I'd like you to test on pie.
Also, please run GPS Test app from Play Store, go outside, let the app run for 5 minutes, take a screenshot, and post it here.
