### ISSUE TITLE
[AOSP v206][Moto E5 Nora]Battery usage data isn´t available and Adaptive brightness

### ISSUE THREAD

**Issue by DavidVelazquezR** [phhusson/treble_experimentations#990]
I installed the latest build of ASOP v206 but i cant find my battery usage data, it shows me that isn´t available, and the same goes for the adaptive brightness, i think this is beacasue the overlay its not implemented, so please if you known how to fix it,i can provide data to fix this, regards

**Comment by XavierWrz** [comment]
Try This Overlay
extract it and paste the apk in /system/overlay/
[treble-overlay-moto-e5.zip](https://github.com/phhusson/treble_experimentations/files/3937147/treble-overlay-moto-e5.zip)

**Comment by phhusson** [comment]
Fixed with https://github.com/phhusson/vendor_hardware_overlay/pull/160
