### ISSUE TITLE
follow up: Not booting past android logo AOSP 10.0 v206 [Alldocube M5XS T1001XS]

### ISSUE THREAD

**Issue by codergenius1** [phhusson/treble_experimentations#992]
> 
> 
> Issue is that you're using Magisk.
> If you want to use Magisk, you need to use a phh-ed magisk, like this:
> https://sourceforge.net/projects/expressluke-gsis/files/Extras/phh-magisk-ten/
> Though my recommendation is that you don't use magisk if you can.

followed this with v206
(1. without magisk,
2. with Magisk-v20.2-11b7076a-phh.zip,
3. with Magisk-v20.2-11b7076a-phh.zip+ https://zackptg5.com/downloads/Disable_Dm-Verity_ForceEncrypt_10.20.2019.zip )
but no success. attaching the logs as
1without_magisk.zip,
2with_magisk.zip &
3with_magisk+dm-verity.zip respectively
[1without_magisk.zip](https://github.com/phhusson/treble_experimentations/files/3938344/1without_magisk.zip)
[2with_magisk.zip](https://github.com/phhusson/treble_experimentations/files/3938345/2with_magisk.zip)
[3with_magisk+dm-verity.zip](https://github.com/phhusson/treble_experimentations/files/3938346/3with_magisk%2Bdm-verity.zip)

_Originally posted by @codergenius1 in https://github.com/phhusson/treble_experimentations/issues/974#issuecomment-563106463_

**Comment by phhusson** [comment]
Just say in #974...?

**Comment by codergenius1** [comment]
please mark open #974 again
