### ISSUE TITLE
[Question] Huawei Features - Battery

### ISSUE THREAD

**Issue by brackenhill-mob** [phhusson/treble_experimentations#995]
How do we know which battery setting to use? Is there an app in the Play Store which can tell us?

**Comment by phhusson** [comment]
I don't understand which setting you're talking about

Le lun. 9 déc. 2019 à 18:15, brackenhill-mob <notifications@github.com> a
écrit :

**Comment by brackenhill-mob** [comment]
Settings | Phh Treble Settings | Huawei features | Huawei fast charge

**Comment by brackenhill-mob** [comment]
I couldn't find this documented (any of the Phh Treble Settings)

**Comment by phhusson** [comment]
The option is self explicit. If you don't know how many amps your phone can take, don't change the option.

**Comment by brackenhill-mob** [comment]
OK. Our Honor View 10's can charge at 22.5W so I was trying to work out what setting I can use ;)

**Comment by phhusson** [comment]
In the case of charging a smartphone,  Watts is Volts times Amp
Huawei phones charge at 5Volts

Le lun. 9 déc. 2019 à 18:33, brackenhill-mob <notifications@github.com> a
écrit :

**Comment by brackenhill-mob** [comment]
That'll be 4000mA then ;)
